### ISSUE TITLE
docker: Error response from daemon

### ISSUE THREAD

**Issue by whk6688** [NVIDIA/TensorRT-LLM#1004]
### System Info

tensorRT-llm 0.8

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

docker run --rm -it --ipc=host --ulimit memlock=-1 --ulimit stack=67108864  \
                --gpus=all \
                --volume /home/wanghaikuan/code/TensorRT-LLM:/code/tensorrt_llm \
                --env "CCACHE_DIR=/code/tensorrt_llm/cpp/.ccache" \
                --env "CCACHE_BASEDIR=/code/tensorrt_llm" \
                --workdir /app/tensorrt_llm \
                --hostname nvidia-desktop-release \
                --name tensorrt_llm-release-wanghaikuan \
                --tmpfs /tmp:exec \
                tensorrt_llm/release:latest

### Expected behavior

orin platform can enter docker successfully. 
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/17873056/2ec77a5b-d06f-41e9-86dc-7d6ea5086461)

### actual behavior

docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'csv'
invoking the NVIDIA Container Runtime Hook directly (e.g. specifying the docker --gpus flag) is not supported. Please use the NVIDIA Container Runtime (e.g. specify the --runtime=nvidia flag) instead.: unknown.

### additional notes

NONE

**Comment by Shixiaowei02** [comment]
It may not be a bug related with the source code of TensorRT-LLM. Please refer to https://github.com/NVIDIA/nvidia-docker/issues/1225. Thanks!

**Comment by nv-guomingz** [comment]
please feel free to reopen this ticket if needed.
