### ISSUE TITLE
How to get hidden_state value?

### ISSUE THREAD

**Issue by Hukongtao** [NVIDIA/TensorRT-LLM#1005]
Since the engine after building is static, is there any way for me to obtain the intermediate results of the model?
Is --enable_debug_output a valid way?
But when infer, add --debug_mode will become very slow.

**Comment by byshiue** [comment]
Please refer https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/2023-05-19-how-to-debug.md, it is helpful to understand how to add output in TensorRT engine. `--enable_debug_output` use such way to record lots of intermediate results to debug. `debug_mode` would write these intermediate results to disk and hence it is very slow.

**Comment by Hukongtao** [comment]
> Please refer https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/2023-05-19-how-to-debug.md, it is helpful to understand how to add output in TensorRT engine. `--enable_debug_output` use such way to record lots of intermediate results to debug. `debug_mode` would write these intermediate results to disk and hence it is very slow.

Thanks a lot, using this way I can get the intermediate values of the model. But another problem was discovered. For the qwen1.8B model, the results after Attention will be quite different.

**Comment by Hukongtao** [comment]
> Since the engine after building is static, is there any way for me to obtain the intermediate results of the model? Is --enable_debug_output a valid way? But when infer, add --debug_mode will become very slow.

In fact, I have commented out the following sentence：
https://github.com/NVIDIA/TensorRT-LLM/blob/3d56a445e8ebf888e78be638faf6beec0a78f3c2/tensorrt_llm/runtime/generation.py#L2450
with --run_profiling, Inference time is slower than before acceleration
