### ISSUE TITLE
The installation fails

### ISSUE THREAD

**Issue by shengzhang37** [NVIDIA/TensorRT-LLM#1008]
### System Info

Error log:

```/usr/local/lib/python3.10/dist-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/__init__.py", line 29, in <module>
    from .hlapi.llm import LLM, ModelConfig
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/hlapi/__init__.py", line 1, in <module>
    from .llm import LLM, ModelConfig
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/hlapi/llm.py", line 18, in <module>
    from ..executor import GenerationExecutor, GenerationResult
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/executor.py", line 10, in <module>
    import tensorrt_llm.bindings as tllm
ImportError: /usr/local/lib/python3.10/dist-packages/tensorrt_llm/bindings.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops9is_pinned4callERKNS_6TensorEN3c108optionalINS5_6DeviceEEE
```

### Who can help?

@juney-nvidia
@ncomly-nvidia
 @kaiyux

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [x] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction
The installation of tensorrt-llm fails
```
nvidia-docker run --entrypoint /bin/bash -it nvidia/cuda:12.1.0-devel-ubuntu22.04
apt-get update && apt-get -y install python3.10 python3-pip openmpi-bin libopenmpi-dev
pip3 install tensorrt_llm -U --pre --extra-index-url https://pypi.nvidia.com
python3 -c "import tensorrt_llm; print(tensorrt_llm.__version__)"
 ```

Cannot be executed. 

### Expected behavior

import tensorrt_llm without issue

### actual behavior

`ImportError: /usr/local/lib/python3.10/dist-packages/tensorrt_llm/bindings.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops9is_pinned4callERKNS_6TensorEN3c108optionalINS5_6DeviceEEE`

### additional notes

No idea why it happens

**Comment by TobyGE** [comment]
same here

**Comment by harper-carroll** [comment]
same here.

**Comment by pankajroark** [comment]
Seems like a break. This installation was working well before for me, stopped working when I tried it fresh today.

**Comment by pankajroark** [comment]
torch version is higher in the latest installation `2.2.0` which isn't working. Rolling that back to `2.1.2` works for me.
```py
pip3 install torch==2.1.2
```
```bash
root@de7ef1fcf888:/usr/local/lib/python3.10/dist-packages/tensorrt_llm# python3 -c "import tensorrt_llm; print(tensorrt_llm.__version__)"
[TensorRT-LLM] TensorRT-LLM version: 0.8.0.dev20240123010.8.0.dev2024012301
```
I think tensorrt_llm could add constraints for torch version to fix this.

**Comment by TobyGE** [comment]
Thanks, worked for me

**Comment by Shixiaowei02** [comment]
This issue has been fixed (https://github.com/NVIDIA/TensorRT-LLM/pull/1017). Thanks you all!
