### ISSUE TITLE
Multi-Modal use more GPU memory？

### ISSUE THREAD

**Issue by xiaocaoxu** [NVIDIA/TensorRT-LLM#1011]
### System Info

GPU：NVIDIA GeForce RTX 3090

### Who can help?

@symphonylyh  @ncomly-nvidia 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

**Multi-Modal**:LLaVA(llama-7B)
Huggingface transformers use GPU memory is 16746MiB(fp16)
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/42837678/e255069d-95be-410b-a815-d7a8c85be4e0)

TensorRT-LLM use GPU memory is 21820 MiB(llm:int8, visual:fp16), if llm use fp16 is out of memory.
![img_v3_027k_6c355fed-e771-48e0-b28c-f4b1fdc9be8g](https://github.com/NVIDIA/TensorRT-LLM/assets/42837678/991d4f8f-b86b-42b9-a923-55a3c7c6138d)

### Expected behavior

int8 use gpu memory should lower than fp16

### actual behavior

int8 use gpu memory more than fp16

### additional notes

None

**Comment by symphonylyh** [comment]
@xiaocaoxu I think this is not LLaVA specific, but more related to LLaMA. One quick suggestion: can you please try `--enable_context_fmha` when calling the `llama/build.py`, and give an update here?

Our README didn't mention that specifically. After your confirmation, we can add that

**Comment by symphonylyh** [comment]
Hi @xiaocaoxu , I saw you closed the issue. Can you please share some quick findings of whether the enable_context_fmha flag addressed you concern? Thanks

**Comment by xiaocaoxu** [comment]
Sorry, it is my mistake，I didn't notice when loading image processor will load hugging face weight of llava.
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/42837678/e1ca913f-79d4-4dd3-8374-4c63f15f336a)
