### ISSUE TITLE
In-flight Batching of qwen 

### ISSUE THREAD

**Issue by lyc728** [NVIDIA/TensorRT-LLM#1023]
https://github.com/NVIDIA/TensorRT-LLM/tree/v0.7.0/examples/qwen There is no In-flight Batching of the Support Matrix here,
and v0.7.1 is no In-flight Batching of the Support Matrix here
howerver https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/qwen is support the In-flight Batching, I wonder if this really works

**Comment by lyc728** [comment]
After testing, it was found that in-flight batching did not play a role in speeding up, please reply, thank you
https://github.com/triton-inference-server/tensorrtllm_backend/issues/315

**Comment by byshiue** [comment]
Discuss in https://github.com/triton-inference-server/tensorrtllm_backend/issues/315, close this one.
