### ISSUE TITLE
An error occurred when compiling TensorRT-LLM

### ISSUE THREAD

**Issue by wang9702** [NVIDIA/TensorRT-LLM#1028]
### System Info

cuda: 12.3
cmake: 3.22.0
tensorrt: 9.2.0.post12.dev5
torch: 2.2.0

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. pull image nvcr.io/nvidia/tritonserver:23.12-trtllm-python-py3
2. Create startup container
3. Go into the container and run python3 scripts/build_wheel.py --clean --trt_root /usr/local/tensorrt

### Expected behavior

 Compile successfully

### actual behavior

When compiling TensorRT-LLM, I ran python3 scripts/ build_wheel-py --clean --trt_root /usr/local/tensorrt and got an error, as shown below
![Dingtalk_20240201175750](https://github.com/NVIDIA/TensorRT-LLM/assets/52562761/0a8e10a8-10c2-4ba9-9fd3-c55d8311b986)

### additional notes

Thanks for sharing this excellent project.

**Comment by Shixiaowei02** [comment]
Please reset the environment and try again. Thank you!

**Comment by wang9702** [comment]
> Please reset the environment and try again. Thank you!

Does it take a lot of memory to compile? I used over 30G at compile time, and it continues to increase.

**Comment by Shixiaowei02** [comment]
> > Please reset the environment and try again. Thank you!
> 
> Does it take a lot of memory to compile? I used over 30G at compile time, and it continues to increase.

Please try reducing the number of build threads.
