### ISSUE TITLE
Docker image size

### ISSUE THREAD

**Issue by yunfeng-scale** [NVIDIA/TensorRT-LLM#103]
Hi, following the instructions to build the docker and TRT-LLM I'm getting a docker image of size 28GB. Is this expected? If so is it possible to optimize for the size of the built image?

**Comment by jdemouth-nvidia** [comment]
Hi @yunfeng-scale , 

Indeed, that's the size of the Docker now. It's something we want to address in a future release. 

Thanks,
Julien
