### ISSUE TITLE
Should we run git lfs pull after git clone?

### ISSUE THREAD

**Issue by wangkuiyi** [NVIDIA/TensorRT-LLM#1033]
### System Info

Any

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

The document https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/build_from_source.md#fetch-the-sources presents the following commands

```
# TensorRT-LLM uses git-lfs, which needs to be installed in advance.
apt-get update && apt-get -y install git git-lfs

git lfs install
git lfs pull
git clone https://github.com/NVIDIA/TensorRT-LLM.git
cd TensorRT-LLM
git submodule update --init --recursive
```

However, it seems that the command `git lfs pull` should be after `git clone`. Am I correct?

### Expected behavior

No wrong behavior to be reported here because the above commands worked, as long as `git lfs install` is before `git clone`.

### actual behavior

No wrong behavior

### additional notes

I could be worng, but in my mind, the order of commands should be 
1. `git lfs install` This ensures that the following `git clone` command retrieves LFS files in addition to normal source files.
2. `git clone` 
3. `git lfs pull` This is optional because we had run `git lfs install` before `git clone`. It could be here anyway as a double check.

**Comment by Shixiaowei02** [comment]
Thanks for your correction! We have fixed it, which will be synced externally next week.
