### ISSUE TITLE
Are there any plans to add support for xverse model？

### ISSUE THREAD

**Issue by lwbmowgli** [NVIDIA/TensorRT-LLM#1036]

**Comment by StudyingShao** [comment]
Hi @lwbmowgli , please use the [llama example](https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/llama) in latest main branch and xverse is already supported by https://github.com/NVIDIA/TensorRT-LLM/pull/1019.
Xverse has the same structure as llama, so it works fine with llama pipeline.

**Comment by lwbmowgli** [comment]
It is indeed possible to build successfully, but the output test using run.py cannot output correctly.
python build.py --model_dir /mnt/liwenbo_workspace/trt_engine/XVERSE-7B-Chat \
    --max_batch_size 16 \
    --use_gpt_attention_plugin float16 \
    --output_dir /mnt/liwenbo_workspace/trt_engine/XVERSE-7B-Chat_triton-no-tp \
    --world_size 8 \
    --tp_size 8
mpirun -n 8 --allow-run-as-root \
python3 run.py --max_output_len=512 \
               --tokenizer_dir /mnt/liwenbo_workspace/trt_engine/XVERSE-7B-Chat \
               --engine_dir=/mnt/liwenbo_workspace/trt_engine/XVERSE-7B-Chat_triton \
               --input_text 你是谁?

Input [Text 0]: "你是谁?"
Output [Text 0 Beam 0]: "" 或者 "我不认识你。" 这样的话语。

2. 避免过于亲昵的称呼：如果你们是第一次见面，最好不要使用过于亲昵的称呼，如"宝贝"、"亲爱的"等。

3. 保持眼神接触：在对话时，保持适当的眼神接触可以显示出你的自信和真诚。

4. 注意自己的身体语言：保持直立的姿势，不要交叉手臂或者把手放在口袋里。

5. 避免过多的个人信息：在初次见面时，尽量避免分享过多的个人信息，如你的家庭、工作、财务状况等。

6. 避免过于深入的话题：在初次见面时，尽量避免讨论过于深入的话题，如政治、宗教等。

7. 避免过于快速的进展：如果你们的对话进展得过于快速，可能会让对方感到不舒服。

8. 避免过于直接的问题：在初次见面时，尽量避免直接问对方的年龄、收入等敏感问题。

9. 避免过于随便的态度：在初次见面时，尽量保持正式和尊重的态度。

10. 避免过于紧张：保持冷静和放松，不要让自己过于紧张。"

**Comment by lwbmowgli** [comment]
使用正确的格式解决了这个问题

**Comment by StudyingShao** [comment]
@lwbmowgli Please close the issue if there is no more question.
