### ISSUE TITLE
Attention sink

### ISSUE THREAD

**Issue by jqueguiner** [NVIDIA/TensorRT-LLM#104]
Hi 👋 and thanks for the amazing job can’t wait to see the developments in the next few weeks and months.

any plan to work on attention sink ?

**Comment by jdemouth-nvidia** [comment]
Hi @jqueguiner ,

Thanks for your support. We are considering adding that feature to TensorRT-LLM but nothing concrete at this point. We are not ready to commit on a date when it'll be added (if ever). 

Thanks,
Julien

**Comment by ncomly-nvidia** [comment]
Hi @jqueguiner . StreamingLLM, a technique which takes advantage of Attention Sinks, has been added to the [main branch](https://github.com/NVIDIA/TensorRT-LLM/discussions/789)! 

[Llama example](https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/llama#run-llama-with-streamingllm). Take a look & let us know what you think!

**Comment by zhyncs** [comment]
> Hi @jqueguiner . StreamingLLM, a technique which takes advantage of Attention Sinks, has been added to the [main branch](https://github.com/NVIDIA/TensorRT-LLM/discussions/789)!
> 
> [Llama example](https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/llama#run-llama-with-streamingllm). Take a look & let us know what you think!

Hi @ncomly-nvidia Has H2O been supported in latest main branch? Thanks.
