### ISSUE TITLE
4xTP on AWS g5.12xlarge : `Assertion failed: mpiSize == tp * pp` 

### ISSUE THREAD

**Issue by danielchalef** [NVIDIA/TensorRT-LLM#1047]
### System Info

1x AWS g5.12xlarge  (4x NVIDIA A10G)
Triton container: `nvcr.io/nvidia/tritonserver:24.01-trtllm-python-py3`

### Who can help?

@byshiue 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

1. Build engine for Mistral-7B finetune for 4x tp with world_size of 4 using Llama2 build script in this repo and TensorRT-LLM 0.7.1. Hardware: 1x AWS g5.12xlarge (4x NVIDIA A10G)
```
python scripts/tensorrt_llm/mistral/build.py \
        --model_dir "${MODELS_PATH}/${MODEL_ID}" \
        --dtype float16 \
        --remove_input_padding \
        --enable_context_fmha \
        --use_gpt_attention_plugin float16 \
        --paged_kv_cache \
        --use_gemm_plugin float16 \
        --max_input_len 2048 \
        --max_output_len 256 \
        --weight_only_precision int4 \
        --use_weight_only \
        --world_size ${WORLD_SIZE} \
        --tp_size  ${WORLD_SIZE} \
        --output_dir "${TRT_ENGINE_PATH}/${MODEL_ID}/${WORLD_SIZE}-gpu"
```

Model appears to correctly build, with 4x engine files and `config.json` with `tp` of 4.
   
2. Load model on 1x AWS g5.12xlarge (4x NVIDIA A10G) using Triton NGC container: `nvcr.io/nvidia/tritonserver:24.01-trtllm-python-py3`. On loading, the TensorRT-LLM backend only reports an MPI Size of 1 and engine loading fails with `Assertion failed: mpiSize == tp * pp`.

```
=============================
== Triton Inference Server ==
=============================

NVIDIA Release 24.01 (build 80100767)
Triton Server Version 2.42.0

Copyright (c) 2018-2023, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

I0205 01:26:49.348538 1 cache_manager.cc:480] Create CacheManager with cache_dir: '/opt/tritonserver/caches'
I0205 01:26:50.020319 1 pinned_memory_manager.cc:275] Pinned memory pool is created at '0x7fecd8000000' with size 268435456
I0205 01:26:50.046896 1 cuda_memory_manager.cc:107] CUDA memory pool is created on device 0 with size 67108864
I0205 01:26:50.046917 1 cuda_memory_manager.cc:107] CUDA memory pool is created on device 1 with size 67108864
I0205 01:26:50.046923 1 cuda_memory_manager.cc:107] CUDA memory pool is created on device 2 with size 67108864
I0205 01:26:50.046928 1 cuda_memory_manager.cc:107] CUDA memory pool is created on device 3 with size 67108864
[TensorRT-LLM][INFO] Initializing MPI with thread mode 1
[TensorRT-LLM][INFO] MPI size: 1, rank: 0
E0205 01:26:51.852711 1 backend_model.cc:691] ERROR: Failed to create instance: unexpected error when creating modelInstanceState: [TensorRT-LLM][ERROR] Assertion failed: mpiSize == tp * pp (/tmp/tritonbuild/tensorrtllm/tensorrt_llm/cpp/tensorrt_llm/runtime/worldConfig.cpp:89)
```
 

### Expected behavior

Expect the model to load successfully for inference.

### actual behavior

See failure above

### additional notes

n/a

**Comment by danielchalef** [comment]
Solved. `world_size` > 1 does not work out of the box with NGC Triton containers. The `scripts/launch_triton_server.py` script in the [TensorRT-LLM Backend](https://github.com/triton-inference-server/tensorrtllm_backend) repo needs to be used to start Triton using `miprun`.

**Comment by mayankagrawal-quantiphi** [comment]
Hi @danielchalef, I am also trying to infer a Mistral 7B model finetuned with LORA. I am using [these](https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/llama#run-llama-with-lora) steps to create the engine and infer. Upon runnning the same mpirun command as given in the link, I face the same error :

> RuntimeError: [TensorRT-LLM][ERROR] Assertion failed: mpiSize == tp * pp (/home/jenkins/agent/workspace/LLM/main/L0_PostMerge/tensorrt_llm/cpp/tensorrt_llm/runtime/worldConfig.cpp:94)

Can you kindly elaborate a bit more on how exactly did you solve the issue?

**Comment by danielchalef** [comment]
@mayankagrawal-quantiphi I launched Triton using the `scripts/launch_triton_server.py` script.
