### ISSUE TITLE
ALL outputs are</s>

### ISSUE THREAD

**Issue by bjleah** [NVIDIA/TensorRT-LLM#105]
When I built the baihuan2-13b-chat engine, I added max_ Input_ Len is set to 4096, but when generate, all outputs are"</s></s></s></s></s></s></s></s></s>"

build:
`python /code/tensorrt_llm/examples/baichuan/build.py --model_version v2_13b \
                --model_dir /home/liuye/model \
                --dtype float16 \
                --use_gemm_plugin float16 \
                --use_gpt_attention_plugin float16 \
	        --max_input_len 4096 \
                --output_dir /home/liuye/trt_engine/`

run:
`python run.py --model_version v2_13b \
              --max_output_len=1500 \
              --input_text="Below is the description of the relevant parameters for the PCB design drawings.Please analyze the text content and output it in JSON format as key-value pairs.If a corresponding value cannot be found,Please set it N/A.If there are multiple items,Please list them more.the PCB content is:\nFINISH: ENEPIG.THINKNESS:0.05UM<=AU<=0.15UM,0.3UM<=PD<0.8UM,3.0UM<=NI<=8.0UM.\nTHE SURFACE FINISHED COPPER MIN.THICKNESS MUST>=15UM,AND AVERANGE THICKNESS MUST>=20UM.\nTHE HOLE FINISHED COPPER MIN.THICKNESS MUST>=18UM,AND AVERAGE THICKNESS MUST>=20UM.\nDIMENSIONS ARE IN MILS.\nTHE TOLERANCES OF BOARD DIMENSIONS SHALL BE ACCORDING TO 6.10.2 OF DKBA3178.1.UNLESS OTHERWISE SPECIFIED,THE TOLERANCES OF DRILL SHALL BE ACCORDING TO 6.6.1 OF DKBA3178.1.\nFOUR-WIRE TEST SHOULD BE APPLICATED IN ELECTROLIC TESTING.\nX-OUT IS ACCEPTED. AND THE INDCATED MARK POINTS ON BOTH SIDES OF BROKEN BOARD SHOULD BE BLACKEDTHIS IS SHORT REACH OPTICAL MODULE PCB\nVIAS IN L1-L2 L2-L3 L8-L9 AND L9-L10 NEED FILLED WITH COPPER PLATINGL1-L2,L9L10 DIMPLE NEED TO BE CONTROLLED IN 10UM BUMP NEED TO BE CONTROLLED IN 5UM\n4MIL VIA IN L3-L8 SHOULD BE FINISHED BY POFV.ALL 4MIL VIA IN L3-L8 SHUOLD BE DRILLED BY 6MIL.\nWIRE BOND PAD IN THIS AREA.\nFOR THE 4.OMIL WIDTH PAD ADN LINE IN THIS AREA,THE TOP PAD WIDTH MUST>=75UM.WIREBOND AREA.NEED WIREBOND TEST BEFORE SHIPPING. WIREBOND TEST USE 1 MIL GOLD WIREDIE BOND PAD IN THIS AREA.\nGOLDEN FINGERS MUST BE BEVEL\nTHE DEPTH IS 0.30MM+/-0.1MM,THE ANGLE IS 45 +/- 5 DEGREE.\nTHE TWO BEVELS\"SIZE REFER TO DESCRIPTION IN DRILL.ARTTHE CHAMFER ANGLE IS 45 DEGREEIN THIS AREA,THE EDGE SIDE COPPER FEATURE TO THE BOARD EDGE TOLERANCE SHALL BE +/-0.1mm(INCLUDE THE TOP AND BOTTOM LAYER,EXCEPT THE BEVEL).THE TOLERANCES OF GOLD FINGER PCB WIDTH REFERS TO DRILL.ART DIMENSIONS.\nIF FINISHED HOLE DIAMETER < 1.25mm,REMOVE THE NON-FUNCTIONAL PAD ON THE VIAAND THROUGH HOLE,IF FINISHIED HOLE DIAMETER >= 1.25mm,DO NOT REMOVE THENO-FUNCTIONAL PAD .\nPLEASE DON\"T FABRICATE SILKBOTTOM LAYER,JUST FOR REFERENCE.\nADD DUMMY PAD IS NOT ALLOWED.\nADD 2D CODE AT THIS AREA.\nSIGNAL LAYER 2 (1/30Z+PLATING) ARTWORK LAYER02\n2.77mil\nSIGNAL LAYER 3 (1/30Z+PLATING) ARTWORK LAYER03\n4.86mil/\nThe JSON KEY are:{\"FINISH\": ,\"THINKNESS AU\": ,\"THINKNESS PD\": ,\"THINKNESS NI\": ,\"SURFACE MIN COPPER THICKNESS\": ,\"SURFACE AVERAGE COPPER THICKNESS\": ,\"HOLE MIN COPPER THICKNESS\": ,\"HOLE AVERAGE COPPER THICKNESS\": ,\"DIMENSIONS UNIT\": ,\"BOARD DIMENSIONS TOLERANCES\": ,\"DRILL TOLERANCES\": ,\"ADDING DUMMY PAD\":  ,\"REMOVE NON-FUNCTIONAL PAD\": ,\"GOLD FINGER WIDTH\": ,\"GOLD FINGER WIDTH TOLERANCES\": ,\"GOLDEN FINGERS DEPTH\": ,\"GOLDEN FINGERS ANGLE\": ,\"BEVELS SIZE\": ,\"BEVELS ANGLE\": ,\"BEVELS TOLERANCE\":,\"FLEX FOLDING TIMES REQUIRED\": ,\"FLEX FOLDING RADIUS\": ,\"FLEX ASHESIVE/PERPREG FLOW CONTROLLED\": ,\"FLEX PART WINDOWS\": ,\"SIGNAL LAYERS\": ,\"ARTWORK\": ,\"FILLED PLATING\": ,\"FINISHED POFV\": ,\"ELECTRONIC TESTING\": ,\"ACCEPTED X-OUT\": ,\"SURFACE ROUGHNESS\": ,}"\
              --tokenizer_dir /home/liuye/model \
              --engine_dir=/home/liuye/trt_engine/`

result:
`</s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s>`

**Comment by byshiue** [comment]
Can you share the following reproduced steps? 
- the scripts to build engine
- the scripts to run the example to generate the output you observed

**Comment by bjleah** [comment]
> Can you share the following reproduced steps?
> 
>     * the scripts to build engine
> 
>     * the scripts to run the example to generate the output you observed

Okay, I have updated my script to address the above issues

**Comment by byshiue** [comment]
I am afraid your input is break because there are some `"` in your input text. 

Can you try replacing the input text of the example https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/examples/baichuan/run.py#L75 by your input directly?

**Comment by bjleah** [comment]
> I am afraid your input is break because there are some `"` in your input text.
> 
> Can you try replacing the input text of the example https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/examples/baichuan/run.py#L75 by your input directly?



When I tried to ask the default question in run.py, the result was as follows
`Input: "世界上第二高的山峰是哪座?"
Output: " 乔戈里峰（Qogir Feng），海拔8611米，位于尼泊尔和中国边境，是世界上海拔第二高的山峰。`
It seems correct

**Comment by haojiwei** [comment]
@bjleah output </s> is to  satisfy max_output_len. Is EOS_TOKEN set right in `run.py` program?

**Comment by bjleah** [comment]
> I am afraid your input is break because there are some `"` in your input text.
> 
> Can you try replacing the input text of the example https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/examples/baichuan/run.py#L75 by your input directly?

It's back to normal after replacing the quotes. You're awesome，Super thanks！！！！

**Comment by bjleah** [comment]
> @bjleah output is to satisfy max_output_len. Is EOS_TOKEN set right in `run.py` program?

It's back to normal, it was just an issue with the quotes in the text.

**Comment by byshiue** [comment]
Thanks for update. close this bug.

**Comment by npuichigo** [comment]
@byshiue After using 4-bit weight-only quantization for Baichuan2-13B-Chat, the output error is the same as this issue.

```
python run.py \
    --model_version v2_13b \
    --max_output_len=50 \
    --tokenizer_dir=/workspace/Baichuan2-13B-Chat/ \
    --engine_dir=int4_weight_only/

Input: "世界上第二高的山峰是哪座？"
Output: "</s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s>"
```

**Comment by byshiue** [comment]
> @byshiue After using 4-bit weight-only quantization for Baichuan2-13B-Chat, the output error is the same as this issue.
> 
> ```
> python run.py \
>     --model_version v2_13b \
>     --max_output_len=50 \
>     --tokenizer_dir=/workspace/Baichuan2-13B-Chat/ \
>     --engine_dir=int4_weight_only/
> 
> Input: "世界上第二高的山峰是哪座？"
> Output: "</s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s>"
> ```

Please refer this issue https://github.com/NVIDIA/TensorRT-LLM/issues/37.
