### ISSUE TITLE
Can't build Llama2-7B Engine - incorrect Cuda device used by torch, several "The procedure entry point ... could not be located" errors.

### ISSUE THREAD

**Issue by AreDubya** [NVIDIA/TensorRT-LLM#1054]
### System Info

- x86_64 i9-13900K
- 32GB System Memory
- ASUS ROG Strix GeForce RTX® 4090
- 24GB GPU Memory
- TensorRT-LLM v0.7.1
- TensorRT  v9.2.0.post12.dev5
- Torch 2.1.0+cu121
- cuda-python               12.2.0
-  nvidia-cublas-cu12        12.3.4.1
-  nvidia-cuda-nvrtc-cu12    12.3.107
-  nvidia-cuda-runtime-cu12  12.3.101
-  nvidia-cudnn-cu12         8.9.7.29

- GPU Driver Version 551.23

- Windows 11 Pro 22H2 Build 22621.3007

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

1. Download Llama-2-7b-chat-hf from https://huggingface.co/meta-llama/Llama-2-7b-chat-hf
2. Download model.pt from https://catalog.ngc.nvidia.com/orgs/nvidia/models/llama2-7b/files?version=1.0
3. Clone this repo. 
4. Navigate to examples\llama, and run build.py using the build params from [the example RAG app's instructions](https://github.com/NVIDIA/trt-llm-rag-windows/blob/release/1.0/README.md#building-trt-engine)

### Expected behavior

Build a working TensorRT Engine. 

I tried to use the engine provided on catalog.ngc.nvidia.com. Unfortunately, the engine provided at catalog.ngc.nvidia.com has a missing version tag, and isn't usable here:

> PS C:\Users\rw\inference\trt-llm-rag-windows> python app.py --trt_engine_path "C:\Users\rw\inference\Llama\Llama-2-7b-chat-hr-TRT-engine-2" --trt_engine_name llama_float16_tp1_rank0.engine --tokenizer_dir_path "C:\Users\rw\inference\Llama\Llama-2-7b-chat-hf" --data_dir dataset/
C:\Users\rw\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\__init__.py:40: UserWarning: Importing BasePromptTemplate from langchain root module is no longer supported.
  warnings.warn(
C:\Users\rw\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\__init__.py:40: UserWarning: Importing PromptTemplate from langchain root module is no longer supported.
  warnings.warn(
[02/05/2024-13:05:31] [TRT] [E] 1: [stdArchiveReader.cpp::nvinfer1::rt::StdArchiveReader::stdArchiveReaderInitCommon::47] Error Code 1: Serialization (Serialization assertion stdVersionRead == kSERIALIZATION_VERSION failed.Version tag does not match. Note: Current Version: 228, Serialized Engine Version: 226)
Traceback (most recent call last):
  File "C:\Users\rw\inference\trt-llm-rag-windows\app.py", line 63, in <module>
    llm = TrtLlmAPI(
  File "C:\Users\rw\inference\trt-llm-rag-windows\trt_llama_api.py", line 166, in __init__
    decoder = tensorrt_llm.runtime.GenerationSession(self._model_config,
  File "C:\Users\rw\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorrt_llm\runtime\generation.py", line 457, in __init__
    self.runtime = _Runtime(engine_buffer, mapping)
  File "C:\Users\rw\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorrt_llm\runtime\generation.py", line 150, in __init__
    self.__prepare(mapping, engine_buffer)
  File "C:\Users\rw\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorrt_llm\runtime\generation.py", line 168, in __prepare
    assert self.engine is not None
AssertionError
Exception ignored in: <function _Runtime.__del__ at 0x00000121286D7910>
Traceback (most recent call last):
  File "C:\Users\rw\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorrt_llm\runtime\generation.py", line 266, in __del__
    cudart.cudaFree(self.address)  # FIXME: cudaFree is None??
AttributeError: '_Runtime' object has no attribute 'address'

### actual behavior

Upon launching the build command four popup windows appear with various "procedure entry point could not be located" errors. On clearing those, the command progresses, and provides this output:

> PS C:\Users\rw\inference\TensorRT-LLM\examples\llama> python build.py --model_dir "C:\Users\rw\inference\Llama\Llama-2-7b-chat-hf" --quant_ckpt_path "C:\Users\rw\inference\Llama\Llama2-7bChatInt4\model.pt" --dtype float16 --use_gpt_attention_plugin float16 --use_gemm_plugin float16 --use_weight_only --weight_only_precision int4_awq --per_group --enable_context_fmha --max_batch_size 1 --max_input_len 3000 --max_output_len 1024 --output_dir "C:\Users\rw\inference\Llama\Llama-2-7b-chat-hr-TRT-engine-3"
[02/05/2024-12:10:18] [TRT-LLM] [W] It is recommended to specify --remove_input_padding when using GPT attention plugin
[02/05/2024-12:10:18] [TRT-LLM] [I] Serially build TensorRT engines.
[02/05/2024-12:10:18] [TRT] [I] [MemUsageChange] Init CUDA: CPU +93, GPU +0, now: CPU 14283, GPU 1569 (MiB)
[02/05/2024-12:10:20] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +2740, GPU +314, now: CPU 17288, GPU 1883 (MiB)
[02/05/2024-12:10:20] [TRT-LLM] [W] Invalid timing cache, using freshly created one
[02/05/2024-12:10:20] [TRT-LLM] [I] [MemUsage] Rank 0 Engine build starts - Allocated Memory: Host 2.4885 (GiB) Device 2.1605 (GiB)
[02/05/2024-12:10:24] [TRT-LLM] [I] Loading weights from groupwise AWQ LLaMA checkpoint...
Traceback (most recent call last):
  File "C:\Users\rw\inference\TensorRT-LLM\examples\llama\build.py", line 906, in <module>
    build(0, args)
  File "C:\Users\rw\inference\TensorRT-LLM\examples\llama\build.py", line 850, in build
    engine = build_rank_engine(builder, builder_config, engine_name,
  File "C:\Users\rw\inference\TensorRT-LLM\examples\llama\build.py", line 665, in build_rank_engine
    load_func(tensorrt_llm_llama=tensorrt_llm_llama,
  File "C:\Users\rw\inference\TensorRT-LLM\examples\llama\weight.py", line 1370, in load_from_awq_llama
    awq_llama = torch.load(quant_ckpt_path)
  File "C:\Users\rw\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 1014, in load
    return _load(opened_zipfile,
  File "C:\Users\rw\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 1422, in _load
    result = unpickler.load()
  File "C:\Users\rw\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 1392, in persistent_load
    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "C:\Users\rw\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 1366, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "C:\Users\rw\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 381, in default_restore_location
    result = fn(storage, location)
  File "C:\Users\rw\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 274, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "C:\Users\rw\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 265, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on CUDA device '
RuntimeError: Attempting to deserialize object on CUDA device 1 but torch.cuda.device_count() is 1. Please use torch.load with map_location to map your storages to an existing device.
<img width="310" alt="Screenshot 2024-02-05 122851" src="https://github.com/NVIDIA/TensorRT-LLM/assets/520744/bc8570a9-24f2-441b-9e61-8a15ece4b702">
<img width="313" alt="Screenshot 2024-02-05 122836" src="https://github.com/NVIDIA/TensorRT-LLM/assets/520744/dde0dfad-652d-45c6-88ae-aca7d5ad7cf3">

### additional notes

I'm attempting to build this engine as a workaround to be able to use the [RAG demo app](https://github.com/NVIDIA/trt-llm-rag-windows/tree/release/1.0), as version mismatches prevent using the pre-built 4090 engine for llama-3-13b-chat. I was able to build an engine without the AWQ checkpoint, following basic directions from the examples\llama\readme.md:
`python build.py --model_dir "C:\Users\rw\inference\Llama\Llama-2-7b-chat-hf" --dtype float16 --remove_input_padding --use_gpt_attention_plugin float16  --enable_context_fmha --use_gemm_plugin float16 --output_dir "C:\Users\rw\inference\Llama\Llama-2-7b-chat-hr-TRT-engine"`

Unfortunately, that engine does nothing to get the RAG app working as the shapes are wrong.

**Comment by byshiue** [comment]
Please try adding 
```python
map_location=torch.device("cpu")
```
into torch.load

**Comment by AreDubya** [comment]
Thanks @byshiue, that allowed me to get through the build, and I could run the RAG app.  The accuracy of the answers from the model is quite varied though, the first few were quite good, then it started providing answers referencing the wrong subjects. Good answers I think, but they had nothing to do with my questions. I'm not sure how unusual that is, or if it can be chalked up to using the 7B instead of 13B, but I am attaching some output below. 

There were about 3,500 lines of `[TRT] [W]` and `[TensorRT-LLM][WARNING]` messages though, examples follow:

~ 300 lines of warnings similar to this:
> [02/11/2024-16:23:01] [TRT] [W] A shape layer can only run in INT32 precision
> [02/11/2024-16:23:01] [TRT] [W] IElementWiseLayer with inputs LLaMAForCausalLM/layers/0/ELEMENTWISE_SUM_0_output_0 and LLaMAForCausalLM/layers/0/post_layernorm/SHUFFLE_0_output_0: first input has type Half but second input has type Float.

~1,500 lines like this:
[02/11/2024-16:23:04] [TRT] [W] Missing scale and zero-point for tensor input_ids, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[02/11/2024-16:23:04] [TRT] [W] Missing scale and zero-point for tensor position_ids, expect fall back to non-int8 implementation for any layer consuming or producing given tensor

Then, a block of information:

> [02/11/2024-16:23:04] [TRT] [I] Global timing cache in use. Profiling results in this builder pass will be stored.
> [02/11/2024-16:23:17] [TRT] [I] [GraphReduction] The approximate region cut reduction algorithm is called.
> [02/11/2024-16:23:17] [TRT] [I] Detected 72 inputs and 33 output network tensors.
> [02/11/2024-16:23:23] [TRT] [I] Total Host Persistent Memory: 77632
> [02/11/2024-16:23:23] [TRT] [I] Total Device Persistent Memory: 0
> [02/11/2024-16:23:23] [TRT] [I] Total Scratch Memory: 66216448
> [02/11/2024-16:23:23] [TRT] [I] [BlockAssignment] Started assigning block shifts. This will take 553 steps to complete.
> [02/11/2024-16:23:23] [TRT] [I] [BlockAssignment] Algorithm ShiftNTopDown took 19.3656ms to assign 10 blocks to 553 nodes requiring 254978560 bytes.
> [02/11/2024-16:23:23] [TRT] [I] Total Activation Memory: 254978560
> [02/11/2024-16:23:23] [TRT] [I] Total Weights Memory: 3671451648
> [02/11/2024-16:23:23] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 28528, GPU 5991 (MiB)
> [02/11/2024-16:23:23] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +10, now: CPU 28528, GPU 6001 (MiB)
> [02/11/2024-16:23:23] [TRT] [W] TensorRT was linked against cuDNN 8.9.6 but loaded cuDNN 8.8.1

Followed by ~1,800 lines of these warnings:

> [TensorRT-LLM][WARNING] Cannot profile configuration 2 (for m=1, n=6144, k=4096). Skipped
> [TensorRT-LLM][WARNING] Cannot profile configuration 4 (for m=1, n=6144, k=4096). Skipped
> [TensorRT-LLM][WARNING] Cannot profile configuration 5 (for m=1, n=6144, k=4096). Skipped
> [TensorRT-LLM][WARNING] Cannot profile configuration 6 (for m=1, n=6144, k=4096). Skipped
> [TensorRT-LLM][WARNING] Cannot profile configuration 9 (for m=1, n=6144, k=4096). Skipped
> [TensorRT-LLM][WARNING] Cannot profile configuration 11 (for m=1, n=6144, k=4096). Skipped

Then this information block at the end:

> [02/11/2024-16:23:31] [TRT] [I] Engine generation completed in 26.9879 seconds.
> [02/11/2024-16:23:31] [TRT] [I] [MemUsageStats] Peak memory usage of TRT CPU/GPU memory allocators: CPU 501 MiB, GPU 12094 MiB
> [02/11/2024-16:23:31] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in building engine: CPU +0, GPU +3502, now: CPU 0, GPU 3502 (MiB)
> [02/11/2024-16:23:32] [TRT] [I] [MemUsageStats] Peak memory usage during Engine building and serialization: CPU: 24326 MiB
> [02/11/2024-16:23:32] [TRT-LLM] [I] Total time of building llama_float16_tp1_rank0.engine: 00:00:28
> [02/11/2024-16:23:32] [TRT-LLM] [I] Config saved to C:\Users\rw\inference\Llama\Llama-2-7b-chat-hr-TRT-engine-3\config.json.
> [02/11/2024-16:23:33] [TRT] [I] Loaded engine size: 3505 MiB
> [02/11/2024-16:23:33] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +10, now: CPU 18604, GPU 5969 (MiB)
> [02/11/2024-16:23:33] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 18604, GPU 5977 (MiB)
> [02/11/2024-16:23:33] [TRT] [W] TensorRT was linked against cuDNN 8.9.6 but loaded cuDNN 8.8.1
> [02/11/2024-16:23:34] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +3501, now: CPU 0, GPU 3501 (MiB)
> [02/11/2024-16:23:34] [TRT-LLM] [I] Activation memory size: 243.17 MiB
> [02/11/2024-16:23:34] [TRT-LLM] [I] Weights memory size: 3505.88 MiB
> [02/11/2024-16:23:34] [TRT-LLM] [I] Max KV Cache memory size: 2012.00 MiB
> [02/11/2024-16:23:34] [TRT-LLM] [I] Estimated max memory usage on runtime: 5761.05 MiB
> [02/11/2024-16:23:34] [TRT-LLM] [I] Serializing engine to C:\Users\rw\inference\Llama\Llama-2-7b-chat-hr-TRT-engine-3\llama_float16_tp1_rank0.engine...
> [02/11/2024-16:23:36] [TRT-LLM] [I] Engine serialized. Total time: 00:00:01
> [02/11/2024-16:23:36] [TRT-LLM] [I] [MemUsage] Rank 0 Engine serialized - Allocated Memory: Host 6.0711 (GiB) Device 2.1730 (GiB)
> [02/11/2024-16:23:36] [TRT-LLM] [I] Rank 0 Engine build time: 00:01:33 - 93.44808626174927 (sec)
> [02/11/2024-16:23:36] [TRT] [I] Serialized 52 bytes of code generator cache.
> [02/11/2024-16:23:36] [TRT] [I] Serialized 212118 bytes of compilation cache.
> [02/11/2024-16:23:36] [TRT] [I] Serialized 88 timing cache entries
> [02/11/2024-16:23:36] [TRT-LLM] [I] Timing cache serialized to C:\Users\rw\inference\Llama\Llama-2-7b-chat-hr-TRT-engine-3\model.cache
> [02/11/2024-16:23:36] [TRT-LLM] [I] Total time of building all 1 engines: 00:01:36

I also tried with `awq_llama = torch.load(quant_ckpt_path, map_location=torch.device("cuda:0"))`, which is the correct gpu id, but that was unsuccessful. 

`nvidia-smi` didn't show any use of the memory on the GPU by this process, but it crashed with this:

> python build.py --model_dir "C:\Users\rw\inference\Llama\Llama-2-7b-chat-hf" --quant_ckpt_path "C:\Users\rw\inference\Llama\Llama2-7bChatInt4\model.pt" --dtype float16 --use_gpt_attention_plugin float16 --use_gemm_plugin float16 --use_weight_only --weight_only_precision int4_awq --per_group --enable_context_fmha --max_batch_size 1 --max_input_len 3000 --max_output_len 1024 --output_dir "C:\Users\rw\inference\Llama\Llama-2-7b-chat-hr-TRT-engine-3"
> [02/11/2024-15:46:06] [TRT-LLM] [W] It is recommended to specify --remove_input_padding when using GPT attention plugin
> [02/11/2024-15:46:06] [TRT-LLM] [I] Serially build TensorRT engines.
> [02/11/2024-15:46:07] [TRT] [I] [MemUsageChange] Init CUDA: CPU +93, GPU +0, now: CPU 17993, GPU 1569 (MiB)
> [02/11/2024-15:46:09] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +2615, GPU +314, now: CPU 20874, GPU 1883 (MiB)
> [02/11/2024-15:46:09] [TRT-LLM] [W] Invalid timing cache, using freshly created one
> [02/11/2024-15:46:09] [TRT-LLM] [I] [MemUsage] Rank 0 Engine build starts - Allocated Memory: Host 2.4826 (GiB) Device 1.8270 (GiB)
> [02/11/2024-15:46:19] [TRT-LLM] [I] Loading weights from groupwise AWQ LLaMA checkpoint...
> Traceback (most recent call last):
>   File "C:\Users\rw\inference\TensorRT-LLM\examples\llama\build.py", line 906, in <module>
>     build(0, args)
>   File "C:\Users\rw\inference\TensorRT-LLM\examples\llama\build.py", line 850, in build
>     engine = build_rank_engine(builder, builder_config, engine_name,
>   File "C:\Users\rw\inference\TensorRT-LLM\examples\llama\build.py", line 665, in build_rank_engine
>     load_func(tensorrt_llm_llama=tensorrt_llm_llama,
>   File "C:\Users\rw\inference\TensorRT-LLM\examples\llama\weight.py", line 1554, in load_from_awq_llama
>     process_and_assign_weight(tensorrt_llm_llama.lm_head, v, 1)
>   File "C:\Users\rw\inference\TensorRT-LLM\examples\llama\weight.py", line 1477, in process_and_assign_weight
>     scale = amax / 8.0
> RuntimeError: CUDA error: out of memory
> CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
> For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
> Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


I'm happy I was able to complete the engine build, but I am wondering - are the results I'm describing and the output I included what you would expect to see? If so, are there any other concerns exposed in the output? If not, any other steps I should try?

Thanks again for your help!

**Comment by AreDubya** [comment]
@byshiue,
Further news to report - with the `map_location=torch.device("cpu")` you suggested added to the `torch.load` at examples\llama\weight.py:1370 I am able to build the engine for the LLama-2-13b-chat-hf locally. 

The accuracy of the answers based on context is still lacking, though pypdf generated over 1,000 messages regarding the input pdfs (`[02/12/2024-14:35:05] /Kids or /Limits found in PageLabels.`), so I don't believe that all of them were processed. I am going to revise the input dataset for the RAG demo app and test further, but, as far as I can see, the TensorRT-LLM issue has been addressed with your changes. 

I'm fine with closing this as solved, but I am leaving it open for the moment as I'm not sure that my results are as intended. If you think there's further work to do, or if you would like any information from me, just let me know. Otherwise, this can be closed as solved. Thanks again!
