### ISSUE TITLE
What is the role of TensorRT in TensorRT-LLM?

### ISSUE THREAD

**Issue by YJHMITWEB** [NVIDIA/TensorRT-LLM#1058]
Hi, I am new to TensorRT, but I have experience of using FasterTransformer. 

 As I understand, TensorRT-LLM inherits all the features in FasterTransformer, however, in FasterTransformer, TensorRT is not required to run those models. Thus, I am curious about why TensorRT is involved here? And how does it participate in compiling the model?

**Comment by byshiue** [comment]
TensorRT-LLM is based on the TensorRT to leverage the optimizer of TensorRT, this is helpful for scalability. At the same time, we use some plugins to support the latest features in short term and enhance the performance, like what we do in FasterTransformer.

**Comment by YJHMITWEB** [comment]
@byshiue Thanks!
