### ISSUE TITLE
Strange error messages after installation on clean Windows 11

### ISSUE THREAD

**Issue by gleberof** [NVIDIA/TensorRT-LLM#1062]
### System Info

- CPU i513600k
- GPU RTX49090
- TensorRT-LLM v0.7.1
- OS Windows 11 Home

### Who can help?

@byshiue @juney-nvidia 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Having clean windows 11 home and  following the instructions:
https://github.com/NVIDIA/TensorRT-LLM/blob/main/windows/README.md

- Install with ./setup_env.ps1
- pip install tensorrt_llm --extra-index-url https://pypi.nvidia.com --extra-index-url https://download.pytorch.org/whl/cu121

- Trying to convert llama2-13b-chat-hf (examples/llama)
```
python convert_checkpoint.py --model_dir .\model\Llama-2-13b-chat-hf --output_dir .\tllm_checkpoint_1gpu_fp16 --dtype float16
```
Getting wierd messages:
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/11750/0addd9cb-7dc4-4438-a632-242612fbc118)

![image](https://github.com/NVIDIA/TensorRT-LLM/assets/11750/c533b229-f9f3-43da-be17-1b320023adae)

![image](https://github.com/NVIDIA/TensorRT-LLM/assets/11750/f028a600-ec24-45cb-8c30-1e33f2131ae4)

![image](https://github.com/NVIDIA/TensorRT-LLM/assets/11750/e1653ae0-25ce-4ec3-bbc6-0c40aa83e84b)

What I'm doing wrong?

### Expected behavior

All shoud work without wierd erros

### actual behavior

Dropping the errors, not convering models

### additional notes

Python output after crash
```
Traceback (most recent call last):
  File "C:\Users\erofm\projects\TensorRT-LLM\examples\llama\convert_checkpoint.py", line 27, in <module>
    from tensorrt_llm.models.llama.weight import (load_from_fp8_llama,
ImportError: cannot import name 'load_from_fp8_llama' from 'tensorrt_llm.models.llama.weight' (C:\Program Files\Python310\lib\site-packages\tensorrt_llm\models\llama\weight.py)
```

**Comment by gleberof** [comment]
I manually replaced the files in C:\Program Files\Python310\Lib\site-packages\nvidia\cudnn from version 8 (installed automatically with tensorrt-llm wheel) by newer version from tar file https://developer.nvidia.com/cudnn-downloads?target_os=Windows&target_arch=x86_64&target_version=Agnostic&cuda_version=12

v9

the error messages are gone.

But the export error still remain - trying to setup docker and build package from scratch

**Comment by gleberof** [comment]
After some struggle manage to build the docker.

main brunch are not buildable

trying to build from rel branch

**Comment by tp5uiuc** [comment]
This maybe because `torch` and `tensorrt` are shipped with their own `cuDNN` libraries, and there are symbol clashes. Clicking OK makes them go away, but a more saner fix is the following
```
python -m pip install --upgrade pip
python -m pip install nvidia-cudnn-cu11==8.9.4.25 --no-cache-dir
python -m pip install --pre --extra-index-url https://pypi.nvidia.com/ tensorrt==9.2.0.post12.dev5 --no-cache-dir
python -m pip uninstall -y nvidia-cudnn-cu11
```
Can you try executing this before doing `pip install tensorrt_llm  --extra-index-url https://pypi.nvidia.com/ --extra-index-url https://pypi.nvidia.com/ --extra-index-url https://download.pytorch.org/whl/cu121`?

**Comment by ryomo** [comment]
I had the same issue which has been fixed by your commands.
Thank you !

**Comment by tp5uiuc** [comment]
Marking this as closed, please re-open if you re-encounter the bug :)
