### ISSUE TITLE
Is TensorRT-backend compatible with the new workflow? I am getting errors to indicate it is not

### ISSUE THREAD

**Issue by enochlev** [NVIDIA/TensorRT-LLM#1064]
Hello,

First of all appreciate the frequent updates.

I have noticed that a new workflow has been migrated to llama since the 0.9 update

but according to [this issue](https://github.com/triton-inference-server/tensorrtllm_backend/issues/330) it seems like the config file is diffrent from the old config file used with build.py

Would someone guide me on wether to
1. revert to old version of tensorRT-LLM
2. convert config file to old version
3. wait on an upcoming change to TensorRT-Backend

**Comment by enochlev** [comment]
After some research it appears the 0.9 version is not compatible with the latest tritonserver
via https://docs.nvidia.com/deeplearning/triton-inference-server/release-notes/rel-24-01.html#rel-24-01

closing issue

**Comment by plt12138** [comment]
the same error occurs in the benchmarks/python/benchmark.py in TensorRT-LLM v0.8.0
like this:

```
[TensorRT-LLM] TensorRT-LLM version: 0.8.0Traceback (most recent call last):
  File "/tensorrtllm_backend/tensorrt_llm/benchmarks/python/benchmark.py", line 405, in <module>
    main(args)
  File "/tensorrtllm_backend/tensorrt_llm/benchmarks/python/benchmark.py", line 299, in main
    benchmarker = GPTBenchmark(args, batch_size_options, in_out_len_options,
  File "/tensorrtllm_backend/tensorrt_llm/benchmarks/python/gpt_benchmark.py", line 44, in __init__
    super().__init__(args.engine_dir, args.model, args.dtype, rank,
  File "/tensorrtllm_backend/tensorrt_llm/benchmarks/python/base_benchmark.py", line 83, in __init__
    config_dtype = self.config['builder_config']['precision']
KeyError: 'builder_config'
```

**Comment by dh12306** [comment]
> Reference

have you fixed the problem ? I have the error with you

**Comment by enochlev** [comment]
When I got that error, the TensorRT-LLM and TensorRT-Backend were incompatible with each other... the build config is in a different format
