### ISSUE TITLE
TypeError: weight_only_quantize() got an unexpected keyword argument 'group_size'

### ISSUE THREAD

**Issue by Minami-su** [NVIDIA/TensorRT-LLM#1066]
python build.py --hf_model_dir Qwen-7B-Chat \
                --dtype float16 \
                --remove_input_padding \
                --use_gpt_attention_plugin float16 \
                --use_gemm_plugin float16 \
                --use_weight_only \
                --weight_only_precision int4_awq \
                --output_dir ./tmp/Qwen/7B/trt_engines

```
root@5cc760720dd9:/app/tensorrt_llm/examples/qwen# python build.py --hf_model_dir Qwen-7B-Chat                 --dtype float16                 --remove_input_padding                 --use_gpt_attention_plugin float16                 --use_gemm_plugin float16                 --use_weight_only                 --weight_only_precision int4_awq                 --output_dir ./tmp/Qwen/7B/trt_engines
[TensorRT-LLM] TensorRT-LLM version: 0.8.0.dev2024013000[02/08/2024-03:19:26] [TRT-LLM] [I] Serially build TensorRT engines.
[02/08/2024-03:19:27] [TRT] [I] [MemUsageChange] Init CUDA: CPU +13, GPU +0, now: CPU 118, GPU 1555 (MiB)


[02/08/2024-03:19:55] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +1811, GPU +316, now: CPU 2065, GPU 1871 (MiB)
[02/08/2024-03:19:55] [TRT-LLM] [W] Invalid timing cache, using freshly created one
Traceback (most recent call last):
  File "/app/tensorrt_llm/examples/qwen/build.py", line 705, in <module>
    build(0, args)
  File "/app/tensorrt_llm/examples/qwen/build.py", line 675, in build
    engine = build_rank_engine(builder, builder_config, engine_name,
  File "/app/tensorrt_llm/examples/qwen/build.py", line 493, in build_rank_engine
    tensorrt_llm_qwen = quantize_model(tensorrt_llm_qwen, args.quant_mode,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/quantized/quant.py", line 437, in quantize_model
    model = weight_only_quantize(model, quant_mode, **kwargs)
TypeError: weight_only_quantize() got an unexpected keyword argument 'group_size'
```

**Comment by Minami-su** [comment]
remove --use_weight_only

**Comment by mallorbc** [comment]
'Define the precision for the weights when using weight-only quantization.'
   'You must also use --use_weight_only for that argument to have an impact.

So it then does nothing?

**Comment by Minami-su** [comment]
> python build.py --hf_model_dir Qwen-7B-Chat --dtype float16 --remove_input_padding --use_gpt_attention_plugin float16 --use_gemm_plugin float16 --use_weight_only --weight_only_precision int4_awq --output_dir ./tmp/Qwen/7B/trt_engines
> 
> ```
> root@5cc760720dd9:/app/tensorrt_llm/examples/qwen# python build.py --hf_model_dir Qwen-7B-Chat                 --dtype float16                 --remove_input_padding                 --use_gpt_attention_plugin float16                 --use_gemm_plugin float16                 --use_weight_only                 --weight_only_precision int4_awq                 --output_dir ./tmp/Qwen/7B/trt_engines
> [TensorRT-LLM] TensorRT-LLM version: 0.8.0.dev2024013000[02/08/2024-03:19:26] [TRT-LLM] [I] Serially build TensorRT engines.
> [02/08/2024-03:19:27] [TRT] [I] [MemUsageChange] Init CUDA: CPU +13, GPU +0, now: CPU 118, GPU 1555 (MiB)
> 
> 
> [02/08/2024-03:19:55] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +1811, GPU +316, now: CPU 2065, GPU 1871 (MiB)
> [02/08/2024-03:19:55] [TRT-LLM] [W] Invalid timing cache, using freshly created one
> Traceback (most recent call last):
>   File "/app/tensorrt_llm/examples/qwen/build.py", line 705, in <module>
>     build(0, args)
>   File "/app/tensorrt_llm/examples/qwen/build.py", line 675, in build
>     engine = build_rank_engine(builder, builder_config, engine_name,
>   File "/app/tensorrt_llm/examples/qwen/build.py", line 493, in build_rank_engine
>     tensorrt_llm_qwen = quantize_model(tensorrt_llm_qwen, args.quant_mode,
>   File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/quantized/quant.py", line 437, in quantize_model
>     model = weight_only_quantize(model, quant_mode, **kwargs)
> TypeError: weight_only_quantize() got an unexpected keyword argument 'group_size'
> ```

Here is correct code:
python3 ../quantization/quantize.py --model_dir Qwen-7B-Chat \
                                    --dtype float16 \
                                    --qformat int4_awq \
                                    --output_dir ./qwen_7b_4bit_gs128_awq.pt \
                                    --calib_size 32
python build.py --hf_model_dir Qwen-7B-Chat \
                --quant_ckpt_path ./qwen_7b_4bit_gs128_awq.pt \
                --dtype float16 \
                --remove_input_padding \
                --use_gpt_attention_plugin float16 \
                --enable_context_fmha \
                --use_gemm_plugin float16 \
                --use_weight_only \
                --weight_only_precision int4_awq \
                --per_group \
                --world_size 1 \
                --tp_size 1 \
                --output_dir ./tmp/Qwen/7B/trt_engines/int4-awq/1-gpu
