### ISSUE TITLE
llama convert checkpoint error

### ISSUE THREAD

**Issue by ashish-kumar-hpe** [NVIDIA/TensorRT-LLM#1068]
### System Info

git clone https://github.com/NVIDIA/TensorRT-LLM.git
cd TensorRT-LLM

python examples/llama/convert_checkpoint.py --model_dir /mnt/pvc/TensorRT-LLM/Llama-2-7b-chat-hf/  --output_dir ./tllm_checkpoint_1gpu_fp16  --dtype float16

[02/08/2024-09:46:48] [TRT-LLM] [W] A required package 'psutil' is not installed. Will not monitor the device memory usages. P                                                                                lease install the package first, e.g, 'pip install pynvml>=11.5.0'.
Traceback (most recent call last):
  File "/mnt/pvc/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 27, in <module>
    from tensorrt_llm.models.llama.weight import (load_from_fp8_llama,
ModuleNotFoundError: No module named 'tensorrt_llm.models.llama.weight'

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

git clone https://github.com/NVIDIA/TensorRT-LLM.git
cd TensorRT-LLM

python examples/llama/convert_checkpoint.py --model_dir /mnt/pvc/TensorRT-LLM/Llama-2-7b-chat-hf/  --output_dir ./tllm_checkpoint_1gpu_fp16  --dtype float16

### Expected behavior

convert_checkpoint should be successful

### actual behavior

convert_checkpoint fails

### additional notes

convert_checkpoint should be successful

**Comment by nv-guomingz** [comment]
ModuleNotFoundError: No module named 'tensorrt_llm.models.llama.weight'

==================
It looks like you didn't install tensorrt_llm succesfully.
You may need to add `/mnt/pvc/TensorRT-LLM` into your PYTHONPATH varaible

**Comment by ashish-kumar-hpe** [comment]
1) installed tensorrt_llm 
pip install tensorrt_llm -U --extra-index-url https://pypi.nvidia.com

2) Fetch the latest Tensorrt-LLM  
git clone https://github.com/NVIDIA/TensorRT-LLM.git
cd TensorRT-LLM

3) Set PYTHONPATH
export PYTHONPATH=/mnt/pvc/TensorRT-LLM

4) Execute the conversion
cd /mnt/pvc/TensorRT-LLM
python examples/llama/convert_checkpoint.py --model_dir /mnt/pvc/TensorRT-LLM/Llama-2-7b-chat-hf/ --output_dir ./tllm_checkpoint_1gpu_fp16 --dtype float16

![image](https://github.com/NVIDIA/TensorRT-LLM/assets/65278896/4eec359e-40f0-458d-ac73-d2b777e613a3)

**Comment by nv-guomingz** [comment]
It seems that you didn't run trtllm inside the trtllm docker, right?
Follow the [doc](https://github.com/NVIDIA/tensorrt-llm?tab=readme-ov-file#installation), and check the installation via 
`python3 -c "import tensorrt_llm"`

**Comment by ashish-kumar-hpe** [comment]
Ok. I figured out. Just posting here in case anyone else might come across this kind of issue. 

1. I am using this image to spin up my container
nvcr.io/nvidia/tritonserver:23.12-trtllm-python-py3

2. Exec within the container and then within the container go to location '/opt/tritonserver' and do not change to any other directory path 

3. perform pip install 

pip3 install tensorrt_llm -U --pre --extra-index-url https://pypi.nvidia.com

Immediate this thing works 

python3 -c "import tensorrt_llm"

root@tensor-rt-llm:/opt/tritonserver# python3 -c "import tensorrt_llm"
[TensorRT-LLM] TensorRT-LLM version: 0.9.0.dev2024020600root@tensor-rt-llm:/opt/tritonserver#
root@tensor-rt-llm:/opt/tritonserver#

then git clone tensorrt_llm source for working with llama model to any directory, 

Execute following command from location '/opt/tritonserver' ( dont change from this location )

python /mnt/pvc/TensorRT-LLM/examples/llama/convert_checkpoint.py --model_dir /mnt/pvc/TensorRT-LLM/Llama-2-7b-chat-hf/ --output_dir ./tllm_checkpoint_1gpu_fp16 --dtype float16
