### ISSUE TITLE
[TRT] [E] 3: getPluginCreator could not find plugin: Gemmtensorrt_llm version: 1

### ISSUE THREAD

**Issue by hitcoogle** [NVIDIA/TensorRT-LLM#107]
I have install tensorRT and  tensorRT-LLM, when I build the bloom or llama model, that error occupy.

python build.py --model_dir ./bloom/560M/ \
                --dtype float16 \
                --use_gemm_plugin float16 \
                --use_gpt_attention_plugin float16 \
                --output_dir ./bloom/560M/trt_engines/fp16/1-gpu/

ERROR:
[10/25/2023-03:51:34] [TRT-LLM] [I] Loading weights from HF BLOOM...
[10/25/2023-03:51:35] [TRT-LLM] [I] Weights loaded. Total time: 00:00:00
[10/25/2023-03:51:35] [TRT] [E] 3: getPluginCreator could not find plugin: Gemmtensorrt_llm version: 1
Traceback (most recent call last):
  File "/tensorrt-llm/TensorRT-LLM/examples/bloom/build.py", line 515, in <module>
    build(0, args)

**Comment by jdemouth-nvidia** [comment]
Hi @hitcoogle , did you follow the build instructions and properly installed TRT-LLM? It looks like it cannot find the lib of plugins.

**Comment by hitcoogle** [comment]
> Hi @hitcoogle , did you follow the build instructions and properly installed TRT-LLM? It looks like it cannot find the lib of plugins.

yes, I follow the build instructions,  Here is my installation process:

1. docker base image:
nvcr.io/nvidia/pytorch:23.08-py3
2. install tensorrt:
pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com tensorrt==9.1.0.post12.dev4 tensorrt-libs==9.1.0.post12.dev4 tensorrt-bindings==9.1.0.post12.dev4 --no-deps
3. install tensorrt-llm
python3 ./scripts/build_wheel.py --trt_root /TensorRT-9.1.0.4 --install  --clean

**Comment by jdemouth-nvidia** [comment]
Did you `pip install` the TRT-LLM wheels?

**Comment by hitcoogle** [comment]
> pip install

yes, I install the output wheels : pip install tensorrt_llm-0.5.0-py3-none-any.whl
the version is:
tensorrt-llm              0.5.0

**Comment by xesdiny** [comment]
Have you solved this problem? I encountered it too.

**Comment by xesdiny** [comment]
> > pip install
> 
> yes, I install the output wheels : pip install tensorrt_llm-0.5.0-py3-none-any.whl the version is: tensorrt-llm 0.5.0

Is it because the environment PATH variables are not set correctly?

**Comment by WhatGhost** [comment]
@hitcoogle Have you solved this problem?

**Comment by sam-india-007** [comment]
@hitcoogle did you fix the issue?
