### ISSUE TITLE
Add Installing the libnccl2 Dependency to README.md

### ISSUE THREAD

**Issue by K-Wu** [NVIDIA/TensorRT-LLM#1074]
### System Info

RTX3090
Ubuntu 20.04.6 (5.4.0-170-generic)
CUDA 12.2

### Who can help?

Please consider adding the libnccl2 to the apt install command in the dependency installation paragraph in README.md. Importing TensorRT-LLM python package will look for the shared memory and trigger an error if libnccl2 is not installed.

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

NA

### Expected behavior

NA

### actual behavior

NA

### additional notes

NA

**Comment by hello-11** [comment]
@K-Wu Do you still have the problem? If not, we will close it soon.
