### ISSUE TITLE
how two run with 2 gpus

### ISSUE THREAD

**Issue by UncleFB** [NVIDIA/TensorRT-LLM#108]
I try to Build LLaMA 7B using 2-way tensor parallelism.
But when I execute run.py I got this error.AssertionError: Engine world size (2) != Runtime world size (1)

**Comment by byshiue** [comment]
You should use
```bash
mpirun -n 2 python run.py
```

**Comment by byshiue** [comment]
Close this bug. Feel free to reopen if needed.
