### ISSUE TITLE
使用 python run.py 运行  llama engine 时，报错

### ISSUE THREAD

**Issue by Rane2021** [NVIDIA/TensorRT-LLM#109]
root@ad-Super-Server:/app/tensorrt_llm/examples/llama# python3 run.py --max_output_len=512                --tokenizer_dir $model_path                --engine_dir=$model_save_path/fp16/1-gpu/ 
[1698219401.910371] [ad-Super-Server:2430 :f]        vfs_fuse.c:281  UCX  ERROR inotify_add_watch(/tmp) failed: No space left on device
ad-Super-Server:2430:2430 [0] NCCL INFO Bootstrap : Using eno2:192.168.140.12<0>
ad-Super-Server:2430:2430 [0] NCCL INFO cudaDriverVersion 12020
NCCL version 2.18.3+cuda12.2
ad-Super-Server:2430:2430 [0] NCCL INFO Plugin Path : /opt/hpcx/nccl_rdma_sharp_plugin/lib/libnccl-net.so
ad-Super-Server:2430:2430 [0] NCCL INFO P2P plugin IBext
ad-Super-Server:2430:2430 [0] NCCL INFO NET/IB : No device found.
ad-Super-Server:2430:2430 [0] NCCL INFO NET/IB : No device found.
ad-Super-Server:2430:2430 [0] NCCL INFO NET/Socket : Using [0]eno2:192.168.140.12<0> [1]br-0dc475d6e953:172.19.0.1<0> [2]br-58efa28c7832:172.29.0.1<0> [3]br-b9f03bc7cd9d:172.18.0.1<0> [4]br-e4844f06f8bd:172.20.0.1<0> [5]veth60839da:fe80::2495:81ff:fe83:e63%veth60839da<0> [6]veth3a76472:fe80::7862:a7ff:fe1e:4797%veth3a76472<0> [7]veth4680a63:fe80::70b5:4cff:fe31:90b5%veth4680a63<0> [8]vethb797fae:fe80::8070:68ff:fe9c:f85f%vethb797fae<0> [9]veth9dc4d65:fe80::28c7:76ff:fe30:2beb%veth9dc4d65<0> [10]vethb671864:fe80::cc6a:caff:fe9e:b67a%vethb671864<0> [11]veth263d732:fe80::dc5e:cdff:fe6b:9054%veth263d732<0> [12]vethf86db87:fe80::28cc:fff:fe03:46c4%vethf86db87<0>
ad-Super-Server:2430:2430 [0] NCCL INFO Using network Socket

ad-Super-Server:2430:2430 [0] misc/nvmlwrap.cc:64 NCCL WARN Failed to open libnvidia-ml.so.1
ad-Super-Server:2430:2430 [0] NCCL INFO misc/nvmlwrap.cc:181 -> 2
ad-Super-Server:2430:2430 [0] NCCL INFO init.cc:326 -> 2
ad-Super-Server:2430:2430 [0] NCCL INFO init.cc:1349 -> 2
ad-Super-Server:2430:2430 [0] NCCL INFO init.cc:1598 -> 2
ad-Super-Server:2430:2430 [0] NCCL INFO init.cc:1636 -> 2
[TensorRT-LLM][ERROR] Failed, NCCL error /src/tensorrt_llm/cpp/tensorrt_llm/runtime/ncclCommunicator.cpp:122 'unhandled system error (run with NCCL_DEBUG=INFO for details)'

**Comment by byshiue** [comment]
did you set enough shared memory when entering the container ?
take a look at here (https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/troubleshooting.html#sharing-data)

**Comment by Rane2021** [comment]
thanks it work!
