### ISSUE TITLE
First installation command on README is deprecated

### ISSUE THREAD

**Issue by HeAndres** [NVIDIA/TensorRT-LLM#1095]
In the README.md, the first command on the installation section is the following:
```
nvidia-docker run --entrypoint /bin/bash -it nvidia/cuda:12.1.0-devel-ubuntu22.04
```
However, nvidia-docker has been deprecated as stated in its [README.md](https://github.com/NVIDIA/nvidia-docker).

**Comment by HeAndres** [comment]
I did a PR, #1096 , trying to solve the issue

**Comment by tabbas97** [comment]
This made me spend hours trying to figure out what happened. This needs to be pushed into main ASAP.
