### ISSUE TITLE
calibration dataset

### ISSUE THREAD

**Issue by Hukongtao** [NVIDIA/TensorRT-LLM#1100]
I followed the steps provided in the tutorial to use awq-4bit quantization, but found that the accuracy was seriously lost after quantization.
https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/llama/README.md#awq
My model is the llama after SFT. Therefore, I want to know whether I need to use my own training set for calibration.
When using awq-4bit  result in dropped points, are there any parameters that can be adjusted?

**Comment by ehuaa** [comment]
+1 I have met the same problem with the accuracy drop after quantization, how can i debug with it or how to choose the calibration dataset? @Tracin @byshiue

**Comment by cieske** [comment]
+1 I also wonder if there is any reference for choosing an appropriate calibration dataset.

**Comment by hello-11** [comment]
@Hukongtao Do you still have the problem? If not, we will close it soon.
