### ISSUE TITLE
Pipeline Parallelism slightly faster than single gpu

### ISSUE THREAD

**Issue by SeungsuBaek** [NVIDIA/TensorRT-LLM#1102]
Hi.

About pipeline parallel and single gpu, got some weird situation.

Since pipeline parallelism has some overhead to transfer intermediate data, it is slow compared with single gpu. (latency / sec)

But pipeline parallel is always slightly faster than single gpu.

Why this happen? need help. 

I already have checked nsight system but can't find something.

**Environments.**
```
TensorRT : 9.2.0.5
TensorRT-LLM : main branch
CUDA : 12.2
CUDNN : 8.9.4.25-1
NCCL : 2.18.3-1
CUBLAS : 12.2.5.6-1
```

**Model.**
```
model : Lamma-7b
dtype : fp16
batch_size : 1
input length : 1024
output length : 512
```

**Configurations.**
```
# Single GPU Forward
./cpp/build/benchmarks/gptSessionBenchmark --model llama --engine_dir examples/llama/trt-engines/fp16/1-gpu/ --batch_size 1 --input_output_len 1024,512

# Multi GPU Forward with pipeline parallelism (2-stage)
mpirun -n 2 ./cpp/build/benchmarks/gptSessionBenchmark --model llama --engine_dir examples/llama/trt-engines/fp16/2-pp/ --batch_size 1 --input_output_len 1024,512
```

**Results.**
```
Single-GPU : 11.51 sec
2-GPU (pipeline) : 11.30 sec
```

**Comment by Hudayday** [comment]
Are there any updates on this issue?

**Comment by SeungsuBaek** [comment]
@Hudayday  Is the bug still happening? I'm studying other space, so i don't know what happen nowaday.
