### ISSUE TITLE
torchAllocator does not conform to the CUDA semantics of PyTorch.

### ISSUE THREAD

**Issue by tp-nan** [NVIDIA/TensorRT-LLM#1103]
Hi guys,
In this function,
https://github.com/NVIDIA/TensorRT-LLM/blob/0f041b7b57d118037f943fd6107db846ed147b91/cpp/tensorrt_llm/thop/torchAllocator.cpp#L49

The current stream and the designated CUDA stream(mStream) are being used simultaneously without synchronization, thereby violating PyTorch's CUDA semantics. 

The current stream was used by `torch::Tensor buf = torch::empty({bufSize}, torch::dtype(torch::kUInt8).device(torch::kCUDA));`

The  designated CUDA stream was used by `memSet(ptr, 0, size);`

## Note 
PyTorch CUDA Semantics: The CUDA memory allocator of PyTorch implements memory reuse at the stream level ([CUDA stream-ordered memory allocator](https://pytorch.org/docs/stable/notes/cuda.html#cuda-streams)).

The current stream: https://torchpipe.github.io/docs/preliminaries/pytorch_libtorch#current-stream 

## Proposed solutions
 - A:
```
void TorchAllocator::memSet(void* ptr, int const val, size_t const size)
{
    check_cuda_error(cudaMemsetAsync(ptr, val, size,c10::cuda::getCurrentCUDAStream()));
}
```
- B:  Switch to the designated CUDA stream (mStream) before calling torch::empty using c10::cuda::CUDAStreamGuard.
- C: A+B

**Comment by MartinMarciniszyn** [comment]
My understanding is as follows:

```
torch::Tensor buf = torch::empty({bufSize}, torch::dtype(torch::kUInt8).device(torch::kCUDA));
```

will call into [cudaMalloc](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__MEMORY.html#group__CUDART__MEMORY_1g37d37965bfb4803b6d4e59ff26856356). This operation is not associated with any particular stream, but will block on the host until the allocation is finished on the device. Afterwards we set the memory to zero using `cudaMemsetAsync` with some specific stream. This sequence of operations looks perfectly valid to me.

Do you have an actual example were things go wrong, that is, undefined results are produced?

**Comment by nan2088** [comment]
> torch::empty will call into [cudaMalloc](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__MEMORY.html#group__CUDART__MEMORY_1g37d37965bfb4803b6d4e59ff26856356). This operation is not associated with any particular stream.

Torch::empty may reuse cached memory(related to *the current stream*) and do not call cudaMalloc. This reuse is asynchronous, relative to the current stream.  See also https://discuss.pytorch.org/t/why-gpu-memory-allocations-are-associated-with-the-cuda-stream/63122

An official example is here  from https://pytorch.org/docs/stable/notes/cuda.html#cuda-streams
```
cuda = torch.device('cuda')
s = torch.cuda.Stream()  # Create a new stream.
A = torch.empty((100, 100), device=cuda)
s.wait_stream(torch.cuda.default_stream(cuda))  # STILL REQUIRED!
with torch.cuda.stream(s):
    A.normal_(0.0, 1.0)
    A.record_stream(s)
```
 
> Do you have an actual example were things go wrong, that is, undefined results are produced? 

https://github.com/NVIDIA/TensorRT-LLM/blob/3c373ebc5b5caf7e41198125131a153f3df08f09/cpp/tensorrt_llm/thop/dynamicDecodeOp.cpp#L102C6-L102C21

For example, in the case   FtDynamicDecode”s `forward` was called，but the current stream is not the  designated CUDA stream(mStream)

In our own online actual high throughput scenarios, we have encountered such issues, so we are particularly sensitive to them and try to conform to the CUDA semantics of PyTorch.

But currently, Im unclear whether torchAllocator will cause any problems in the Tensorrt-LLM scenario. I might specifically look into it over the next one or two months.

**Comment by MartinMarciniszyn** [comment]
Thank you for the explanations and the references, @tp-nan. For most of our use cases, the current stream in `torch` should be the same as the designated stream in `TorchAllocator`. However, I agree that we should guard explicitly against scenarios where this might not be the case. A simple solution would be adding a `stream_wait` operation after `torch::empty`. I will investigate this and the options you proposed above.
