### ISSUE TITLE
AWQ config parameter.

### ISSUE THREAD

**Issue by matichon-vultureprime** [NVIDIA/TensorRT-LLM#1106]
[AWQ: Activation-aware Weight Quantization for LLM Compression and Acceleration](https://arxiv.org/pdf/2306.00978.pdf)
The original study compares performance against the number of 'fraction of weights' ranging from 0.1% to 3% of activation.

How to configure the 'fraction of weights' of AWQ via AMMO?

**Comment by Tracin** [comment]
Hi, I think `fraction of weights` are float numbers in weights param that are sensitive to quantization. They are most likely to have larger magnitude than others. So you can just use `hist` on your model to identify them.

**Comment by kmati-dev** [comment]
I think the ```fraction of weights``` should be a percentage to keep the FP16 in the layer (activation or weight). 
One hundred percent of the ```fraction of weights``` could result in a fully FP16 model. 
The paper shows a range for keeping FP16 between 0.1% - 3%, which can improve the performance (accuracy) of the quantized model. 

So, the AMMO quantize method doesn't provide the parameter to configure the amount of FP16 to be kept in the quantized model.

I found the function ```def calibrate_weights``` and the default parameter ```percentile=99.99```. 
Could this parameter control the percentage to keep FP16?

**Comment by Tracin** [comment]
Sorry, that is not for AWQ I am afraid. And AMMO AWQ will not preserve any weights in FP16.
