### ISSUE TITLE
convert_checkpoint.py: error: unrecognized arguments: --world_size

### ISSUE THREAD

**Issue by mfournioux** [NVIDIA/TensorRT-LLM#1110]
I am converting a Mixtral8x7B with tensor parallelism using conversion script from llama folder : 

python convert_checkpoint.py --model_dir ./Mixtral-8x7B-v0.1 \
                             --output_dir ./tllm_checkpoint_mixtral_2gpu \
                             --dtype float16 \
                             --world_size 2 \
                             --tp_size 2

An error appears about world_size argument : 

convert_checkpoint.py: error: unrecognized arguments: --world_size 2

Should I remove this argument? 

Many thanks for your help

**Comment by byshiue** [comment]
Yes. `--world_size` is removed. Please remove it.

**Comment by thomas-hiddenpeak** [comment]
After removing this argument, how do we configure world size?
