### ISSUE TITLE
Some parameters are on the meta device device because they were offloaded to the cpu.

### ISSUE THREAD

**Issue by hldsoft** [NVIDIA/TensorRT-LLM#1117]
### System Info

x86_64 3700X 
GPU rtx3060 12G 
64G ddr4
Ubuntu 20.04
Dokcer 25.0.3

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

installed tensorrt-llm ,in docker 

### Expected behavior

root@5efd1bfd143e:/home/TensorRT-LLM/examples/chatglm# python3 convert_checkpoint.py --model_dir THUDM/chatglm3-6b --output_dir trt_ckpt/chatglm3_6b/fp16/1-gpu
[TensorRT-LLM] TensorRT-LLM version: 0.9.0.dev20240206000.9.0.dev2024020600
Inferring chatglm version from path...
Chatglm version: chatglm3
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████| 7/7 [00:02<00:00,  3.00it/s]
[02/20/2024-19:58:51] Some parameters are on the meta device device because they were offloaded to the cpu.
Traceback (most recent call last):
  File "/home/TensorRT-LLM/examples/chatglm/convert_checkpoint.py", line 1254, in <module>
    covert_and_save(rank)
  File "/home/TensorRT-LLM/examples/chatglm/convert_checkpoint.py", line 1235, in covert_and_save
    weights = convert_hf_chatglm(
  File "/home/TensorRT-LLM/examples/chatglm/convert_checkpoint.py", line 323, in convert_hf_chatglm
    qkv_weight, qkv_bias = get_weight_and_bias(
  File "/home/TensorRT-LLM/examples/chatglm/convert_checkpoint.py", line 251, in get_weight_and_bias
    return get_weight(params, prefix, dtype), get_bias(params, prefix, dtype)
  File "/home/TensorRT-LLM/examples/chatglm/convert_checkpoint.py", line 239, in get_weight
    return params[f'{prefix}.weight'].to(dtype).detach().cpu()

### actual behavior

# ChatGLM3-6B: single gpu, dtype float16
python3 convert_checkpoint.py --model_dir chatglm3_6b --output_dir trt_ckpt/chatglm3_6b/fp16/1-gpu

### additional notes

# ChatGLM3-6B: single gpu, dtype float16
python3 convert_checkpoint.py --model_dir chatglm3_6b --output_dir trt_ckpt/chatglm3_6b/fp16/1-gpu

**Comment by hldsoft** [comment]
I understand, it's because the graphics memory is exploding

**Comment by VeryVery** [comment]
Has it been fixed?

**Comment by Iven2132** [comment]
Any fix?

**Comment by Oluwatiseunla** [comment]
The reason for this warning is because of the memory, consider running on a larger capacity.
I ran the model again, I  still got this warning and but i also got my output.
