### ISSUE TITLE
Can I use tensorrt-llm depoly qwen1.5?

### ISSUE THREAD

**Issue by hljjjmssyh** [NVIDIA/TensorRT-LLM#1119]

**Comment by Tlntin** [comment]
this may you need [link](https://github.com/Tlntin/Qwen-TensorRT-LLM/tree/main/examples/qwen2)

**Comment by xinbingzhe** [comment]
I think Qwen1.5 model architecture is same as llama. Have you tried it.

**Comment by Franc-Z** [comment]
For TRTLLM-0.9.0, you can refer to https://github.com/Franc-Z/QWen1.5_TensorRT-LLM
