### ISSUE TITLE
In awq_int4_group_128  mode, why is the weight converted into int8 after rounding to [-8,7]?

### ISSUE THREAD

**Issue by brisker** [NVIDIA/TensorRT-LLM#1120]
When building **AWQ_int4_group_128** engine, the code [here](https://github.com/NVIDIA/TensorRT-LLM/blob/main/tensorrt_llm/models/llama/weight.py#L1362) seems to convert the weights which are already rounded to [-8,7] into **int8**, using  the following two command defined [[here](https://github.com/NVIDIA/TensorRT-LLM/blob/main/tensorrt_llm/models/llama/weight.py#L1337)] and [here](https://github.com/NVIDIA/TensorRT-LLM/blob/main/tensorrt_llm/models/llama/weight.py#L1338).

```
packer = torch.ops.trtllm.pack_int8_tensor_to_packed_int4
preprocessor = torch.ops.trtllm.preprocess_weights_for_mixed_gemm

int4_weight = preprocessor(packer(qweight_int8.cpu()), torch.quint4x2)
```

Isn't this **INT4** weight quantization? Why is int8 engaged here? This is confusing to me.

**Comment by Tracin** [comment]
Looks like we pack 2 int4 weights into one int8 number.

**Comment by hello-11** [comment]
@brisker Do you still have the question? If not, we will close it soon.
