### ISSUE TITLE
Getting unexpected Results from Smoothquant on Llama2-13B

### ISSUE THREAD

**Issue by Hongbosherlock** [NVIDIA/TensorRT-LLM#1121]
### System Info
A100 gpu
0.7.1 tensorrt-llm

### Reproduction
run smoothquant
```python
python3 hf_llama_convert.py \
        -i /target/model/hf_model_v16 \
        -o /target/model/sq0.8/ \
        -sq 0.5 \
        --tensor-parallelism 1 \
        --storage-type fp16
```
Build model for SmoothQuant in the _per_tensor_ mode.
```python
python3 build.py --ft_model_dir=/target/model/sq0.8/1-gpu/ \
                 --use_smooth_quant \
                 --dtype float16 \
                 --use_gpt_attention_plugin float16 \
                 --use_gemm_plugin float16 \
                 --use_layernorm_plugin float16 \
                 --output_dir /target/model/smooth_out \
                 --enable_context_fmha \
                 --remove_input_padding \
                 --use_inflight_batching \
                 --max_batch_size 100 \
                 --max_input_len 3000
```
I got the following warnnings:
**(1) `Parameter was initialized as float16 but set to float32`**

![c0fa11225521cb817df843ef731ec849](https://github.com/NVIDIA/TensorRT-LLM/assets/27813268/3ba860a6-bdb3-4165-a208-d2367085e86f)

(2) IElementWiseLayer with inputs LLaMAForCausalLM/layers/30/attention/PLUGIN_V2_GPTAttention_0_output_0 and LLaMAForCausalLM/layers/30/attention/SHUFFLE_0_output_0: **first input has type Half but second input has type Float.**

![9228431d98595a64cf3e7203b2a4451e](https://github.com/NVIDIA/TensorRT-LLM/assets/27813268/e7ef6ae6-ea48-49cb-9c5e-deee374faf3f)

(3)
`UNSUPPORTED_STATESkipping tactic 1 due to insufficient memory on requested size of 93750 detected for tactic 0x000000000000001e.
[TRT] [W] Tactic Device request: 93750MB Available: 81251MB. Device memory is insufficient to use tactic.
`
![6cd0958c3eba6d6f960b953de31cd831](https://github.com/NVIDIA/TensorRT-LLM/assets/27813268/560b6cdc-ca3f-4c28-b11e-73b8283a6e86)

Are these warnings normal? How should I resolve them?

at last I run:
```python
python3 run.py --max_output_len=90 \
               --tokenizer_dir=/target/model/hf_model_v16 \
               --engine_dir=/target/model/smooth_out \
```

I got the following results, it's nonsense:
```
output_ids: [44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866, 44866]
Output [Text 0 Beam 0]: "                       “
```

**Comment by Tracin** [comment]
The three kind of warnings are irrelevant to the bad accuracy.
Please try with `--per_channel` and `--per_token`

**Comment by Hongbosherlock** [comment]
> The three kind of warnings are irrelevant to the bad accuracy. Please try with `--per_channel` and `--per_token`

 thx, `--per_channel `and `--per_token` works for me.

Is `--per_channel ` for  **weight** and `--per_token`  for **activation** quantization in GEMM?

**Comment by Tracin** [comment]
> Is `--per_channel ` for **weight** and `--per_token` for **activation** quantization in GEMM?

Yes.
