### ISSUE TITLE
How to return logprobs from Generation Session

### ISSUE THREAD

**Issue by shashikg** [NVIDIA/TensorRT-LLM#1127]
Hi, Is it possible to return logprobs from a generation session? I am trying to return the logprobs for the whisper decoder but was not able to do so. 

I added this: `sampling_config.update(output_log_probs=True)` to sampling_config but no help `generation_session.decode` only returns the output token ids.

Thanks!

**Comment by hello-11** [comment]
@shashikg Do you still have the question? If not, we will close it soon.
