### ISSUE TITLE
Tensorrt_llm install issues

### ISSUE THREAD

**Issue by KarihaZach** [NVIDIA/TensorRT-LLM#1129]
### System Info

**When i install tensorrt_llm and type follow code : pip install tensorrt_llm --extra-index-url https://pypi.nvidia.com --extra-index-url https://download.pytorch.org/whl/cu121
it returns these error:**
Looking in indexes: https://pypi.org/simple, https://pypi.nvidia.com, https://download.pytorch.org/whl/cu121
Collecting tensorrt_llm
  Downloading tensorrt-llm-0.7.1.tar.gz (6.9 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\KarihaZach\AppData\Local\Temp\pip-install-hqtiy0_9\tensorrt-llm_f9311b1469704ce2bde863e0350fbfed\setup.py", line 90, in <module>
          raise RuntimeError("Bad params")
      RuntimeError: Bad params
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
**The environment of my computer is win10,cudnn9.0,cuda12.2.2,python 3.10.11.and i was already installed Microsoft MPI(including two file),Every time when i run the wheel,the error always stuck in the "Bad params".**
Please help me to handle this,thanks a lot!

### Who can help?

@juney-nvidia;@ncomly-nvidia;@kaiyux

**Comment by wimueller** [comment]
Are you sure you are using Python 3.10?

**Comment by nignal** [comment]
same problem.

Edit: changed python3.12 to 3.10 and working now.

**Comment by pfldy2850** [comment]
same here.

I cannot install this package on ubuntu 22.04.

**Comment by Shixiaowei02** [comment]
> same here.
> 
> I cannot install this package on ubuntu 22.04.

Are you using Python 3.10?

**Comment by stephanbertl** [comment]
Same here, python 3.10.12 on Ubuntu 22.04.

Install of latest tensorrt_llm-0.9.0.dev2024031200-cp310-cp310-linux_x86_64.whl gives "bad params", previous version works fine.

**Comment by aimestereo** [comment]
for me it failes on 3.10.12 and works on 3.10.11 (Docker `python:3.10.11-slim-buster`)

**Comment by hello-11** [comment]
@KarihaZach Do you still have the question? If not, we will close it soon.
