### ISSUE TITLE
Hang when try to build with one line (in container)

### ISSUE THREAD

**Issue by CjhHa1** [NVIDIA/TensorRT-LLM#113]
I am working on building my docker image and I stuck with cmake, I just follow your instructions and use the one line command
`make -C docker release_build`
I got stuck like below. My device is a NVIDIA A-800
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/72591262/6dbbe13d-3f04-42d3-884e-146ce925e4e9)

**Comment by nv-guomingz** [comment]
the building process is depend on your specific hardware configuration.
The command `python3 scripts/build_wheel.py --clean --trt_root /usr/local/tensorrt` tooks about 20+ minutes (Intel(R) Xeon(R) Silver 4314 CPU @ 2.40GHz + NVIDIA H100 80GB HBM3 + nvme ssd)
<img width="1249" alt="image" src="https://github.com/NVIDIA/TensorRT-LLM/assets/137257613/ed4f15c7-cda2-429b-b7b5-1eac5281d37a">

**Comment by byshiue** [comment]
Close this bug because the issue is inactivated. Feel free to ask here if you still have question/issue, we will reopen the issue.
