### ISSUE TITLE
KeyError: 'lm_head.weight' when trying to quantize llama2 model

### ISSUE THREAD

**Issue by noahnisbet** [NVIDIA/TensorRT-LLM#1134]
### System Info

I am working with a DGX H100 setup.

Hi, I hope you are doing well. I am facing an error when trying to quantize llama2. Below are the steps I am taking to quantize it. For some reason I am seeing a key error on this line: https://github.com/NVIDIA/TensorRT-LLM/blob/3c373ebc5b5caf7e41198125131a153f3df08f09/tensorrt_llm/commands/build.py#L329.

Thank you in advance for the help and let me know if I can provide any more information.

### Who can help?

@Tracin

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
python ../quantization/quantize.py --model_dir ./tmp/llama2_model/ \
                                   --dtype float16 \
                                   --qformat fp8 \
                                   --kv_cache_dtype fp8 \
                                   --output_dir ./checkpoints/tllm_checkpoint_16gpu_fp8 \
                                   --calib_size 512 \
                                   --tp_size 8 \
                                   --pp_size 2

trtllm-build --checkpoint_dir ./checkpoints/tllm_checkpoint_16gpu_fp8 \
                --gpt_attention_plugin float16 \
                --context_fmha enable \
                --output_dir ./tensorrt_engines/16gpu_tp8_pp2_fp8_h100 \
                --max_batch_size 512 \
                --max_input_len 1024 \
                --max_output_len 1024 \
                --gemm_plugin float16 \
	        --remove_input_padding enable
```

### Expected behavior

The trt engine to be created without errors

### actual behavior

```
  File "/usr/local/bin/trtllm-build", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/commands/build.py", line 514, in main
    parallel_build(source, build_config, args.output_dir, workers,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/commands/build.py", line 436, in parallel_build
    passed = build_and_save(rank, rank % workers, ckpt_dir,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/commands/build.py", line 408, in build_and_save
    engine = build(build_config,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/commands/build.py", line 285, in build
    preprocess_weights(weights, rank_config)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/commands/build.py", line 329, in preprocess_weights
    assert weights['lm_head.weight'].dtype == str_dtype_to_torch(
KeyError: 'lm_head.weight'
```

### additional notes

No other notes.

**Comment by rgandikota** [comment]
@Tracin  @byshiue  Could you please help answer this? We are facing this consistently when we try to quantize to fp8 on a H100 server. Appreciate your quick response on this

**Comment by Tracin** [comment]
Hi @noahnisbet Did you run with the latest main branch? I am going to reproduce it.

**Comment by rgandikota** [comment]
@Tracin Yes, we used the latest from the main branch.

**Comment by noahnisbet** [comment]
Hi @Tracin, any update on reproducing this error? Thanks again for your help. Let me know if I can provide any assistance.

**Comment by Tracin** [comment]
@noahnisbet Yeah, you can make this [section](https://github.com/NVIDIA/TensorRT-LLM/blob/main/tensorrt_llm/commands/build.py#L328-L332) under the condition of `if model_config.mapping.is_last_pp_rank():`
I will push a MR to fix this.

**Comment by noahnisbet** [comment]
Thank you @Tracin It works now! However, one thing I am seeing is the kv-cache is still the same size as a non-quantized engine. Is there a setting I need to change for that?

**Comment by noahnisbet** [comment]
Nevermind, I found out you can define the model runner with the following argument.

```
runner_kwargs = dict(engine_dir=self.engine_dir,
                                rank=self.runtime_rank,
                                free_gpu_memory_fraction=0.2)
            
model = ModelRunnerCpp.from_dir(**runner_kwargs)
```
