### ISSUE TITLE
Where is the source code for batch_manager and executor?

### ISSUE THREAD

**Issue by aikitoria** [NVIDIA/TensorRT-LLM#1135]
Why are there compiled binaries here if this library is supposed to be open source?

https://github.com/NVIDIA/TensorRT-LLM/tree/main/cpp/tensorrt_llm/batch_manager
https://github.com/NVIDIA/TensorRT-LLM/tree/main/cpp/tensorrt_llm/executor

**Comment by byshiue** [comment]
These parts are not open sourced.
