### ISSUE TITLE
Gemma inference question:   what is the tmp_vocab.model file for inference  and what version of triton server I can test this?

### ISSUE THREAD

**Issue by zmy1116** [NVIDIA/TensorRT-LLM#1138]
Hello,

I'm following the newly added example for gemma 
https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/gemma

I have two questions:

1. I'm able to create the engine, but I don't know how to do inference... because I can't find this `tmp/models/gemma_nv/checkpoints/tmp_vocab.mode`
Can you share some information how to generate this?

2. What version of triton server can I run this engine? 
The engine is built with 0.9.0.dev2024022000,   I couldn't run it with the ngc triton llm docker 
nvcr.io/nvidia/tritonserver:24.01-trtllm-python-py3

I think probably it can only run with the triton llm backend that matches this specific tensorrt llm version.   

I'm not sure what version of triton server is that..

Thanks

**Comment by byshiue** [comment]
1. It should be such vocab file https://github.com/google/gemma_pytorch/blob/main/tokenizer/tokenizer.model. 
2. It is indepenent to version of triton server. We don't have NGC docker image to support this latest TRT-LLM commit now. You need to build the triton server docker image by yourself now.

**Comment by zmy1116** [comment]
Hi,

Thanks for the quick response.  Yes I'm able to run gemma in tensorrt_llm now

I will build triton server myself and see if it works there as well

**Comment by zmy1116** [comment]
yeah it works on triton server as well 

thanks

**Comment by pravingadakh** [comment]
Hi @zmy1116 , we are also trying to deploy gemma model. We are able to use run.py and summarize.py with engine checkpoint. However when we try to deploy it with triton (built triton image from latest commit), we are receiving empty response from the model. We think it has something to do with the config. Would you help us with the config you have used to deploy with triton?

**Comment by zmy1116** [comment]
we followed this
https://github.com/triton-inference-server/tensorrtllm_backend/blob/main/docs/gemma.md

Pravin Gadakh ***@***.***> 于2024年4月1日周一 01:26写道：
