### ISSUE TITLE
Low performance of Pipeline Parallel vs Tensor Parallel engines on LLaMa 13B

### ISSUE THREAD

**Issue by WilliamBlaskowicz** [NVIDIA/TensorRT-LLM#1144]
**System information**
1. 4x NVIDIA A100 40GB SXM
2. TensorRT-LLM, commit a8018c14e6a9868b507a0517550b2cc6e41bd86e (packaged with Triton TensorRT-LLM backend)

**Question**

Hi everybody,

While experimenting with LLaMa 13B on TensorRT-LLM and different Pipeline/Tensor parallelism configurations, it seems like Pipeline parallelism always achieves lower performance (low throughput, high latency) than an equivalent Tensor parallel configuration. Furthermore, the Pipeline parallel models display almost no speedup against a single GPU LLM serving solution. Is this behavior expected with pipeline parallelism on LLaMa or is there something wrong? If this behavior is expected, is there another reason why one would chose pipeline over tensor parallelism?

**Example**
Comparing two identical engines with different Tensor and Pipeline parallelism:
1. ```PP=2, TP=2  --> 10.2s p90th latency @ 3.0 requests per second```
2. ```PP=1, TP=4  --> 6.4s p90th latency @ 3.0 requests per second```
3. ```PP=4, TP=1 --> cannot sustain such throughput```

Thank you in advance.

**Comment by byshiue** [comment]
PP cannot bring benefit on latency, it only increase the throughput. And in small batch size, PP cannot bring too many benefit even for throughput because it will split the full batch into several micro batches. 

So, the results you report are expected.
