### ISSUE TITLE
pip install of TensorRT-LLM not working on Windows

### ISSUE THREAD

**Issue by bkmckenzie** [NVIDIA/TensorRT-LLM#1152]
I issue the following from powershell and get the result shown below that:

PS C:\Users\bkmckenzie> pip install tensorrt_llm --extra-index-url https://pypi.nvidia.com --extra-index-url https://download.pytorch.org/whl/cu121
Looking in indexes: https://pypi.org/simple, https://pypi.nvidia.com, https://download.pytorch.org/whl/cu121
Collecting tensorrt_llm
  Downloading https://pypi.nvidia.com/tensorrt-llm/tensorrt_llm-0.7.1-cp310-cp310-win_amd64.whl (443.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 443.7/443.7 MB 7.4 MB/s eta 0:00:00
Collecting accelerate==0.20.3 (from tensorrt_llm)
  Downloading accelerate-0.20.3-py3-none-any.whl.metadata (17 kB)
Collecting build (from tensorrt_llm)
  Downloading build-1.0.3-py3-none-any.whl.metadata (4.2 kB)
Collecting colored (from tensorrt_llm)
  Downloading colored-2.2.4-py3-none-any.whl.metadata (3.6 kB)
Collecting cuda-python==12.2.0 (from tensorrt_llm)
  Downloading cuda_python-12.2.0-cp310-cp310-win_amd64.whl.metadata (770 bytes)
Collecting diffusers==0.15.0 (from tensorrt_llm)
  Downloading diffusers-0.15.0-py3-none-any.whl.metadata (19 kB)
Collecting mpi4py (from tensorrt_llm)
  Downloading mpi4py-3.1.5-cp310-cp310-win_amd64.whl.metadata (8.0 kB)
Collecting numpy (from tensorrt_llm)
  Downloading numpy-1.26.4-cp310-cp310-win_amd64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 3.4 MB/s eta 0:00:00
Collecting onnx>=1.12.0 (from tensorrt_llm)
  Downloading onnx-1.15.0-cp310-cp310-win_amd64.whl.metadata (15 kB)
Collecting polygraphy (from tensorrt_llm)
  Downloading https://pypi.nvidia.com/polygraphy/polygraphy-0.49.0-py2.py3-none-any.whl (327 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 327.9/327.9 kB 9.9 MB/s eta 0:00:00
Collecting pywin32 (from tensorrt_llm)
  Downloading pywin32-306-cp310-cp310-win_amd64.whl.metadata (6.6 kB)
Collecting sentencepiece>=0.1.99 (from tensorrt_llm)
  Downloading sentencepiece-0.2.0-cp310-cp310-win_amd64.whl.metadata (8.3 kB)
Collecting tensorrt==9.2.0.post12.dev5 (from tensorrt_llm)
  Downloading https://pypi.nvidia.com/tensorrt/tensorrt-9.2.0.post12.dev5.tar.gz (18 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      Traceback (most recent call last):
        File "c:\python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "c:\python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "c:\python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\bkmckenzie\AppData\Local\Temp\pip-build-env-nqsjxc1d\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\bkmckenzie\AppData\Local\Temp\pip-build-env-nqsjxc1d\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\bkmckenzie\AppData\Local\Temp\pip-build-env-nqsjxc1d\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\bkmckenzie\AppData\Local\Temp\pip-build-env-nqsjxc1d\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 120, in <module>
        File "C:\Users\bkmckenzie\AppData\Local\Temp\pip-build-env-nqsjxc1d\overlay\Lib\site-packages\setuptools\__init__.py", line 102, in setup
          _install_setup_requires(attrs)
        File "C:\Users\bkmckenzie\AppData\Local\Temp\pip-build-env-nqsjxc1d\overlay\Lib\site-packages\setuptools\__init__.py", line 70, in _install_setup_requires
          dist = MinimalDistribution(attrs)
        File "C:\Users\bkmckenzie\AppData\Local\Temp\pip-build-env-nqsjxc1d\overlay\Lib\site-packages\setuptools\__init__.py", line 52, in __init__
          super().__init__(filtered)
        File "C:\Users\bkmckenzie\AppData\Local\Temp\pip-build-env-nqsjxc1d\overlay\Lib\site-packages\setuptools\dist.py", line 297, in __init__
          for ep in metadata.entry_points(group='distutils.setup_keywords'):
      TypeError: entry_points() got an unexpected keyword argument 'group'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by bkmckenzie** [comment]
So, subsequent try of the same thing as before:

PS C:\Users\bkmckenzie> pip install tensorrt_llm --extra-index-url https://pypi.nvidia.com --extra-index-url https://download.pytorch.org/whl/cu121
Looking in indexes: https://pypi.org/simple, https://pypi.nvidia.com, https://download.pytorch.org/whl/cu121
Collecting tensorrt_llm
  Using cached https://pypi.nvidia.com/tensorrt-llm/tensorrt_llm-0.7.1-cp310-cp310-win_amd64.whl (443.7 MB)
Collecting accelerate==0.20.3 (from tensorrt_llm)
  Using cached accelerate-0.20.3-py3-none-any.whl.metadata (17 kB)
Collecting build (from tensorrt_llm)
  Using cached build-1.0.3-py3-none-any.whl.metadata (4.2 kB)
Collecting colored (from tensorrt_llm)
  Using cached colored-2.2.4-py3-none-any.whl.metadata (3.6 kB)
Collecting cuda-python==12.2.0 (from tensorrt_llm)
  Using cached cuda_python-12.2.0-cp310-cp310-win_amd64.whl.metadata (770 bytes)
Collecting diffusers==0.15.0 (from tensorrt_llm)
  Using cached diffusers-0.15.0-py3-none-any.whl.metadata (19 kB)
Collecting mpi4py (from tensorrt_llm)
  Using cached mpi4py-3.1.5-cp310-cp310-win_amd64.whl.metadata (8.0 kB)
Collecting numpy (from tensorrt_llm)
  Using cached numpy-1.26.4-cp310-cp310-win_amd64.whl.metadata (61 kB)
Collecting onnx>=1.12.0 (from tensorrt_llm)
  Using cached onnx-1.15.0-cp310-cp310-win_amd64.whl.metadata (15 kB)
Collecting polygraphy (from tensorrt_llm)
  Using cached https://pypi.nvidia.com/polygraphy/polygraphy-0.49.0-py2.py3-none-any.whl (327 kB)
Collecting pywin32 (from tensorrt_llm)
  Using cached pywin32-306-cp310-cp310-win_amd64.whl.metadata (6.6 kB)
Collecting sentencepiece>=0.1.99 (from tensorrt_llm)
  Using cached sentencepiece-0.2.0-cp310-cp310-win_amd64.whl.metadata (8.3 kB)
Collecting tensorrt==9.2.0.post12.dev5 (from tensorrt_llm)
  Using cached https://pypi.nvidia.com/tensorrt/tensorrt-9.2.0.post12.dev5.tar.gz (18 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      Traceback (most recent call last):
        File "c:\python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "c:\python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "c:\python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\bkmckenzie\AppData\Local\Temp\pip-build-env-3wbxo4eq\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\bkmckenzie\AppData\Local\Temp\pip-build-env-3wbxo4eq\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\bkmckenzie\AppData\Local\Temp\pip-build-env-3wbxo4eq\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\bkmckenzie\AppData\Local\Temp\pip-build-env-3wbxo4eq\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 120, in <module>
        File "C:\Users\bkmckenzie\AppData\Local\Temp\pip-build-env-3wbxo4eq\overlay\Lib\site-packages\setuptools\__init__.py", line 102, in setup
          _install_setup_requires(attrs)
        File "C:\Users\bkmckenzie\AppData\Local\Temp\pip-build-env-3wbxo4eq\overlay\Lib\site-packages\setuptools\__init__.py", line 70, in _install_setup_requires
          dist = MinimalDistribution(attrs)
        File "C:\Users\bkmckenzie\AppData\Local\Temp\pip-build-env-3wbxo4eq\overlay\Lib\site-packages\setuptools\__init__.py", line 52, in __init__
          super().__init__(filtered)
        File "C:\Users\bkmckenzie\AppData\Local\Temp\pip-build-env-3wbxo4eq\overlay\Lib\site-packages\setuptools\dist.py", line 297, in __init__
          for ep in metadata.entry_points(group='distutils.setup_keywords'):
      TypeError: entry_points() got an unexpected keyword argument 'group'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.



Seems this package is broken no?  Btw, trying to install this on a brand new Windows 11 machine.  Python 3.10 installed.

**Comment by byshiue** [comment]
Please follow the issue template to share the reprodcued steps and describe your issue, thank you for cooperation.

**Comment by bkmckenzie** [comment]
I clicked "New Issue" and filled out what came up??   Where is this issue template you speak of?

**Comment by byshiue** [comment]
When you click New issue, you should see such graph and click the `Get started`. 
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/11360707/68112764-1d22-4974-be68-0b9467c2ff3c)

**Comment by bkmckenzie** [comment]
Okay, so do I open a new issue, or just add that info here?

**Comment by bkmckenzie** [comment]
- CPU Architecture: x86_64
- CPU:  13th Gen Intel I9-13980HX, 1 Socket, 24 Core
- Memory:  64GB, 5200 MHz
- GPU Name: NVidia GeForce RTX 4090 Laptop
- GPU Memory Size: 16GB
- TensorRT-LLM Branch or Tag:  N/A
- Cuda version: 12.2
- CUDNN version: 9.0
- NVidia Driver Version: 537.13
- Python version: Python 3.10.0a4
- Microsoft MPI version: 10.0.12498.5
- Microsoft MPI SDK version: 10.0.12498.5
- OS Version Windows 11 23H2 Professional (10.0.22631.3155)

See first two posts to this issue for repro steps

**Comment by tp5uiuc** [comment]
Hi @bkmckenzie, 

I just verified that the wheel installs locally. Looking at your error logs, I see
```
File "C:\Users\bkmckenzie\AppData\Local\Temp\pip-build-env-nqsjxc1d\overlay\Lib\site-packages\setuptools\dist.py", line 297, in init
for ep in metadata.entry_points(group='distutils.setup_keywords'):
TypeError: entry_points() got an unexpected keyword argument 'group'
```
This suggests that `importlib_metadata` maybe running an older version (added support for the group kwarg was added in v3.6.0).

Can you try running 
```
python -m pip freeze

python -c "import importlib_metadata; print(importlib_metadata.version('importlib-metadata'))"
```
and report back with the output. FWIW this seems to be a recurrent issue, see https://github.com/pypa/twine/issues/796 , https://github.com/pypa/twine/issues/760

**Comment by remisharrock** [comment]
I do have the same issue here is MY output
``` python -m pip freeze
beautifulsoup4==4.12.3
borb==2.1.21
certifi==2024.2.2
cffi==1.16.0
charset-normalizer==3.3.2
colorama==0.4.6
cryptography==42.0.3
fonttools==4.49.0
idna==3.6
lxml==5.1.0
markdownify==0.11.6
pillow==10.2.0
pycparser==2.21
PyPDF2==3.0.1
pypng==0.20220715.0
python-barcode==0.15.1
qrcode==7.4.2
requests==2.31.0
setuptools==69.1.0
six==1.16.0
soupsieve==2.5
typing_extensions==4.9.0
Unidecode==1.3.8
urllib3==2.2.1
PS C:\Users\remis>
PS C:\Users\remis> python -c "import importlib_metadata; print(importlib_metadata.version('importlib-metadata'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'importlib_metadata'
```

**Comment by tp5uiuc** [comment]
Thanks @remisharrock, let me try this on a clean python installation and get back to you

**Comment by bkmckenzie** [comment]
Hmmm, here is my output:

C:\Users\bkmckenzie>python -m pip freeze

C:\Users\bkmckenzie>python -c "import importlib_metadata; print(importlib_metadata.version('importlib-metadata'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'importlib_metadata'

**Comment by tp5uiuc** [comment]
Tried with two different python versions (3.10.0, 3.10.4) and two different pip versions (22.0.4, 24.0), install passes without issues. Posting log below
```
PS C:\Users\tejaswinp> python3 --version
Python 3.10.4
PS C:\Users\tejaswinp> python3 -m pip install tensorrt_llm --extra-index-url https://pypi.nvidia.com --extra-index-url https://download.pytorch.org/whl/cu121
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com, https://pypi.nvidia.com, https://download.pytorch.org/whl/cu121
Collecting tensorrt_llm
  Downloading https://pypi.nvidia.com/tensorrt-llm/tensorrt_llm-0.8.0-cp310-cp310-win_amd64.whl (908.2 MB)
     ---------------------------------------- 908.2/908.2 MB 93.9 MB/s eta 0:00:00
Collecting numpy
  Downloading numpy-1.26.4-cp310-cp310-win_amd64.whl (15.8 MB)
     ---------------------------------------- 15.8/15.8 MB 108.9 MB/s eta 0:00:00
Collecting diffusers==0.15.0
  Downloading diffusers-0.15.0-py3-none-any.whl (851 kB)
     ---------------------------------------- 851.8/851.8 KB ? eta 0:00:00
Collecting pywin32
  Downloading pywin32-306-cp310-cp310-win_amd64.whl (9.2 MB)
     ---------------------------------------- 9.2/9.2 MB 146.3 MB/s eta 0:00:00
Collecting torch==2.1.0+cu121
  Downloading https://download.pytorch.org/whl/cu121/torch-2.1.0%2Bcu121-cp310-cp310-win_amd64.whl (2473.9 MB)
     ---------------------------------------- 2.5/2.5 GB 108.9 MB/s eta 0:00:00
Collecting sentencepiece>=0.1.99
  Downloading sentencepiece-0.2.0-cp310-cp310-win_amd64.whl (991 kB)
     ---------------------------------------- 991.5/991.5 KB 61.3 MB/s eta 0:00:00
Collecting colored
  Downloading colored-2.2.4-py3-none-any.whl (16 kB)
Collecting polygraphy
  Downloading https://pypi.nvidia.com/polygraphy/polygraphy-0.49.0-py2.py3-none-any.whl (327 kB)
     ---------------------------------------- 327.9/327.9 KB 19.9 MB/s eta 0:00:00
Collecting torchtext==0.16.0+cpu
  Downloading https://download.pytorch.org/whl/torchtext-0.16.0%2Bcpu-cp310-cp310-win_amd64.whl (1.9 MB)
     ---------------------------------------- 1.9/1.9 MB 120.6 MB/s eta 0:00:00
Collecting onnx>=1.12.0
  Downloading onnx-1.15.0-cp310-cp310-win_amd64.whl (14.3 MB)
     ---------------------------------------- 14.3/14.3 MB 108.9 MB/s eta 0:00:00
Collecting torchvision==0.16.0+cu121
  Downloading https://download.pytorch.org/whl/cu121/torchvision-0.16.0%2Bcu121-cp310-cp310-win_amd64.whl (5.8 MB)
     ---------------------------------------- 5.8/5.8 MB 179.6 MB/s eta 0:00:00
Collecting optimum
  Downloading optimum-1.17.1-py3-none-any.whl (407 kB)
     ---------------------------------------- 407.1/407.1 KB ? eta 0:00:00
Collecting tensorrt==9.2.0.post12.dev5
  Downloading https://pypi.nvidia.com/tensorrt/tensorrt-9.2.0.post12.dev5.tar.gz (18 kB)
  Preparing metadata (setup.py) ... done
Collecting torchdata==0.7.0
  Downloading https://download.pytorch.org/whl/torchdata-0.7.0-cp310-cp310-win_amd64.whl (1.3 MB)
     ---------------------------------------- 1.3/1.3 MB 82.5 MB/s eta 0:00:00
Collecting cuda-python==12.2.0
  Downloading cuda_python-12.2.0-cp310-cp310-win_amd64.whl (8.3 MB)
     ---------------------------------------- 8.3/8.3 MB 266.5 MB/s eta 0:00:00
Collecting psutil
  Downloading psutil-5.9.8-cp37-abi3-win_amd64.whl (255 kB)
     ---------------------------------------- 255.1/255.1 KB ? eta 0:00:00
Collecting tokenizers>=0.14
  Downloading tokenizers-0.15.2-cp310-none-win_amd64.whl (2.2 MB)
     ---------------------------------------- 2.2/2.2 MB 136.4 MB/s eta 0:00:00
Collecting janus
  Downloading janus-1.0.0-py3-none-any.whl (6.9 kB)
Collecting accelerate==0.25.0
  Downloading accelerate-0.25.0-py3-none-any.whl (265 kB)
     ---------------------------------------- 265.7/265.7 KB ? eta 0:00:00
Collecting transformers==4.36.1
  Downloading transformers-4.36.1-py3-none-any.whl (8.3 MB)
     ---------------------------------------- 8.3/8.3 MB 105.8 MB/s eta 0:00:00
Collecting evaluate
  Downloading evaluate-0.4.1-py3-none-any.whl (84 kB)
     ---------------------------------------- 84.1/84.1 KB ? eta 0:00:00
Collecting build
  Downloading build-1.1.1-py3-none-any.whl (19 kB)
Collecting pynvml>=11.5.0
  Downloading pynvml-11.5.0-py3-none-any.whl (53 kB)
     ---------------------------------------- 53.1/53.1 KB ? eta 0:00:00
Collecting mpi4py
  Downloading mpi4py-3.1.5-cp310-cp310-win_amd64.whl (472 kB)
     ---------------------------------------- 472.1/472.1 KB ? eta 0:00:00
Collecting wheel
  Downloading wheel-0.42.0-py3-none-any.whl (65 kB)
     ---------------------------------------- 65.4/65.4 KB ? eta 0:00:00
Collecting safetensors>=0.3.1
  Downloading safetensors-0.4.2-cp310-none-win_amd64.whl (269 kB)
     ---------------------------------------- 269.5/269.5 KB ? eta 0:00:00
Collecting huggingface-hub
  Downloading huggingface_hub-0.21.3-py3-none-any.whl (346 kB)
     ---------------------------------------- 346.2/346.2 KB ? eta 0:00:00
Collecting pyyaml
  Downloading PyYAML-6.0.1-cp310-cp310-win_amd64.whl (145 kB)
     ---------------------------------------- 145.3/145.3 KB ? eta 0:00:00
Collecting packaging>=20.0
  Downloading packaging-23.2-py3-none-any.whl (53 kB)
     ---------------------------------------- 53.0/53.0 KB ? eta 0:00:00
Collecting cython
  Downloading Cython-3.0.8-cp310-cp310-win_amd64.whl (2.8 MB)
     ---------------------------------------- 2.8/2.8 MB 86.4 MB/s eta 0:00:00
Collecting importlib-metadata
  Downloading importlib_metadata-7.0.1-py3-none-any.whl (23 kB)
Collecting filelock
  Downloading filelock-3.13.1-py3-none-any.whl (11 kB)
Collecting regex!=2019.12.17
  Downloading regex-2023.12.25-cp310-cp310-win_amd64.whl (269 kB)
     ---------------------------------------- 269.5/269.5 KB ? eta 0:00:00
Collecting requests
  Downloading requests-2.31.0-py3-none-any.whl (62 kB)
     ---------------------------------------- 62.6/62.6 KB ? eta 0:00:00
Collecting Pillow
  Downloading https://download.pytorch.org/whl/pillow-10.2.0-cp310-cp310-win_amd64.whl (2.6 MB)
     ---------------------------------------- 2.6/2.6 MB 163.2 MB/s eta 0:00:00
Collecting networkx
  Downloading https://download.pytorch.org/whl/networkx-3.2.1-py3-none-any.whl (1.6 MB)
     ---------------------------------------- 1.6/1.6 MB 102.3 MB/s eta 0:00:00
Collecting fsspec
  Downloading fsspec-2024.2.0-py3-none-any.whl (170 kB)
     ---------------------------------------- 170.9/170.9 KB 10.0 MB/s eta 0:00:00
Collecting sympy
  Downloading https://download.pytorch.org/whl/sympy-1.12-py3-none-any.whl (5.7 MB)
     ---------------------------------------- 5.7/5.7 MB 122.0 MB/s eta 0:00:00
Collecting typing-extensions
  Downloading typing_extensions-4.10.0-py3-none-any.whl (33 kB)
Collecting jinja2
  Downloading Jinja2-3.1.3-py3-none-any.whl (133 kB)
     ---------------------------------------- 133.2/133.2 KB ? eta 0:00:00
Collecting urllib3>=1.25
  Downloading urllib3-2.2.1-py3-none-any.whl (121 kB)
     ---------------------------------------- 121.1/121.1 KB ? eta 0:00:00
Collecting tqdm
  Downloading tqdm-4.66.2-py3-none-any.whl (78 kB)
     ---------------------------------------- 78.3/78.3 KB ? eta 0:00:00
Collecting protobuf>=3.20.2
  Downloading protobuf-4.25.3-cp310-abi3-win_amd64.whl (413 kB)
     ---------------------------------------- 413.4/413.4 KB ? eta 0:00:00
Collecting colorama
  Downloading https://download.pytorch.org/whl/colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting tomli>=1.1.0
  Downloading tomli-2.0.1-py3-none-any.whl (12 kB)
Collecting pyproject_hooks
  Downloading pyproject_hooks-1.0.0-py3-none-any.whl (9.3 kB)
Collecting pandas
  Downloading pandas-2.2.1-cp310-cp310-win_amd64.whl (11.6 MB)
     ---------------------------------------- 11.6/11.6 MB 131.2 MB/s eta 0:00:00
Collecting datasets>=2.0.0
  Downloading datasets-2.18.0-py3-none-any.whl (510 kB)
     ---------------------------------------- 510.5/510.5 KB 33.4 MB/s eta 0:00:00
Collecting xxhash
  Downloading xxhash-3.4.1-cp310-cp310-win_amd64.whl (29 kB)
Collecting dill
  Downloading dill-0.3.8-py3-none-any.whl (116 kB)
     ---------------------------------------- 116.3/116.3 KB ? eta 0:00:00
Collecting responses<0.19
  Downloading responses-0.18.0-py3-none-any.whl (38 kB)
Collecting multiprocess
  Downloading multiprocess-0.70.16-py310-none-any.whl (134 kB)
     ---------------------------------------- 134.8/134.8 KB ? eta 0:00:00
Collecting coloredlogs
  Downloading coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
     ---------------------------------------- 46.0/46.0 KB ? eta 0:00:00
Collecting transformers[sentencepiece]>=4.26.0
  Downloading transformers-4.38.2-py3-none-any.whl (8.5 MB)
     ---------------------------------------- 8.5/8.5 MB 109.4 MB/s eta 0:00:00
Collecting pyarrow>=12.0.0
  Downloading pyarrow-15.0.0-cp310-cp310-win_amd64.whl (24.8 MB)
     ---------------------------------------- 24.8/24.8 MB 165.1 MB/s eta 0:00:00
Collecting aiohttp
  Downloading aiohttp-3.9.3-cp310-cp310-win_amd64.whl (365 kB)
     ---------------------------------------- 365.2/365.2 KB ? eta 0:00:00
Collecting pyarrow-hotfix
  Downloading pyarrow_hotfix-0.6-py3-none-any.whl (7.9 kB)
Collecting idna<4,>=2.5
  Downloading idna-3.6-py3-none-any.whl (61 kB)
     ---------------------------------------- 61.6/61.6 KB ? eta 0:00:00
Collecting charset-normalizer<4,>=2
  Downloading charset_normalizer-3.3.2-cp310-cp310-win_amd64.whl (100 kB)
     ---------------------------------------- 100.3/100.3 KB ? eta 0:00:00
Collecting certifi>=2017.4.17
  Downloading certifi-2024.2.2-py3-none-any.whl (163 kB)
     ---------------------------------------- 163.8/163.8 KB ? eta 0:00:00
Collecting transformers[sentencepiece]>=4.26.0
  Downloading transformers-4.38.1-py3-none-any.whl (8.5 MB)
     ---------------------------------------- 8.5/8.5 MB 275.3 MB/s eta 0:00:00
  Downloading transformers-4.38.0-py3-none-any.whl (8.5 MB)
     ---------------------------------------- 8.5/8.5 MB 275.3 MB/s eta 0:00:00
  Downloading transformers-4.37.2-py3-none-any.whl (8.4 MB)
     ---------------------------------------- 8.4/8.4 MB 133.2 MB/s eta 0:00:00
  Downloading transformers-4.37.1-py3-none-any.whl (8.4 MB)
     ---------------------------------------- 8.4/8.4 MB 77.0 MB/s eta 0:00:00
  Downloading transformers-4.37.0-py3-none-any.whl (8.4 MB)
     ---------------------------------------- 8.4/8.4 MB 135.4 MB/s eta 0:00:00
  Downloading transformers-4.36.2-py3-none-any.whl (8.2 MB)
     ---------------------------------------- 8.2/8.2 MB 132.4 MB/s eta 0:00:00
Collecting humanfriendly>=9.1
  Downloading humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
     ---------------------------------------- 86.8/86.8 KB ? eta 0:00:00
Collecting zipp>=0.5
  Downloading zipp-3.17.0-py3-none-any.whl (7.4 kB)
Collecting MarkupSafe>=2.0
  Downloading MarkupSafe-2.1.5-cp310-cp310-win_amd64.whl (17 kB)
Collecting python-dateutil>=2.8.2
  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
     ---------------------------------------- 229.9/229.9 KB ? eta 0:00:00
Collecting pytz>=2020.1
  Downloading pytz-2024.1-py2.py3-none-any.whl (505 kB)
     ---------------------------------------- 505.5/505.5 KB ? eta 0:00:00
Collecting tzdata>=2022.7
  Downloading tzdata-2024.1-py2.py3-none-any.whl (345 kB)
     ---------------------------------------- 345.4/345.4 KB ? eta 0:00:00
Collecting mpmath>=0.19
  Downloading https://download.pytorch.org/whl/mpmath-1.3.0-py3-none-any.whl (536 kB)
     ---------------------------------------- 536.2/536.2 KB ? eta 0:00:00
Collecting multidict<7.0,>=4.5
  Downloading multidict-6.0.5-cp310-cp310-win_amd64.whl (28 kB)
Collecting yarl<2.0,>=1.0
  Downloading yarl-1.9.4-cp310-cp310-win_amd64.whl (76 kB)
     ---------------------------------------- 76.4/76.4 KB ? eta 0:00:00
Collecting attrs>=17.3.0
  Downloading attrs-23.2.0-py3-none-any.whl (60 kB)
     ---------------------------------------- 60.8/60.8 KB ? eta 0:00:00
Collecting frozenlist>=1.1.1
  Downloading frozenlist-1.4.1-cp310-cp310-win_amd64.whl (50 kB)
     ---------------------------------------- 50.4/50.4 KB ? eta 0:00:00
Collecting aiosignal>=1.1.2
  Downloading aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting async-timeout<5.0,>=4.0
  Downloading async_timeout-4.0.3-py3-none-any.whl (5.7 kB)
Collecting pyreadline3
  Downloading pyreadline3-3.4.1-py3-none-any.whl (95 kB)
     ---------------------------------------- 95.2/95.2 KB ? eta 0:00:00
Collecting six>=1.5
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Using legacy 'setup.py install' for tensorrt, since package 'wheel' is not installed.
Installing collected packages: sentencepiece, pywin32, pytz, pyreadline3, mpmath, zipp, xxhash, wheel, urllib3, tzdata, typing-extensions, tomli, tensorrt, sympy, six, safetensors, regex, pyyaml, pynvml, pyarrow-hotfix, psutil, protobuf, polygraphy, Pillow, packaging, numpy, networkx, multidict, mpi4py, MarkupSafe, idna, humanfriendly, fsspec, frozenlist, filelock, dill, cython, colored, colorama, charset-normalizer, certifi, attrs, async-timeout, yarl, tqdm, requests, python-dateutil, pyproject_hooks, pyarrow, onnx, multiprocess, jinja2, janus, importlib-metadata, cuda-python, coloredlogs, aiosignal, torch, responses, pandas, huggingface-hub, build, aiohttp, torchvision, torchdata, tokenizers, diffusers, accelerate, transformers, torchtext, datasets, evaluate, optimum, tensorrt_llm
  Running setup.py install for tensorrt ... done
Successfully installed MarkupSafe-2.1.5 Pillow-10.2.0 accelerate-0.25.0 aiohttp-3.9.3 aiosignal-1.3.1 async-timeout-4.0.3 attrs-23.2.0 build-1.1.1 certifi-2024.2.2 charset-normalizer-3.3.2 colorama-0.4.6 colored-2.2.4 coloredlogs-15.0.1 cuda-python-12.2.0 cython-3.0.8 datasets-2.18.0 diffusers-0.15.0 dill-0.3.8 evaluate-0.4.1 filelock-3.13.1 frozenlist-1.4.1 fsspec-2024.2.0 huggingface-hub-0.21.3 humanfriendly-10.0 idna-3.6 importlib-metadata-7.0.1 janus-1.0.0 jinja2-3.1.3 mpi4py-3.1.5 mpmath-1.3.0 multidict-6.0.5 multiprocess-0.70.16 networkx-3.2.1 numpy-1.26.4 onnx-1.15.0 optimum-1.17.1 packaging-23.2 pandas-2.2.1 polygraphy-0.49.0 protobuf-4.25.3 psutil-5.9.8 pyarrow-15.0.0 pyarrow-hotfix-0.6 pynvml-11.5.0 pyproject_hooks-1.0.0 pyreadline3-3.4.1 python-dateutil-2.9.0.post0 pytz-2024.1 pywin32-306 pyyaml-6.0.1 regex-2023.12.25 requests-2.31.0 responses-0.18.0 safetensors-0.4.2 sentencepiece-0.2.0 six-1.16.0 sympy-1.12 tensorrt-9.2.0.post12.dev5 tensorrt_llm-0.8.0 tokenizers-0.15.2 tomli-2.0.1 torch-2.1.0+cu121 torchdata-0.7.0 torchtext-0.16.0+cpu torchvision-0.16.0+cu121 tqdm-4.66.2 transformers-4.36.1 typing-extensions-4.10.0 tzdata-2024.1 urllib3-2.2.1 wheel-0.42.0 xxhash-3.4.1 yarl-1.9.4 zipp-3.17.0
WARNING: You are using pip version 22.0.4; however, version 24.0 is available.
You should consider upgrading via the 'C:\Users\tejaswinp\.pyenv\pyenv-win\versions\3.10.4\python3.exe -m pip install --upgrade pip' command.
```

`build` (a requirement of `trt-llm`) installs `importlib_metadata`, here's my version on 3.10.4
```
PS C:\Users\tejaswinp> python3 -c "import importlib_metadata; print(importlib_metadata.version('importlib-metadata'))"
7.0.1
```
but it's not surprising that when `trt-llm` installation fails, `importlib-metadata` does not show up. I notice an extra line in my logs
```Using legacy 'setup.py install' for tensorrt, since package 'wheel' is not installed.```
but I confirmed that's a non-issue.

Can I have your python and pip versions @remisharrock @bkmckenzie?

**Comment by bkmckenzie** [comment]
C:\Users\bkmckenzie>pip --version
pip 24.0 from c:\python310\lib\site-packages\pip (python 3.10)

C:\Users\bkmckenzie>python --version
Python 3.10.0a4

**Comment by tp5uiuc** [comment]
I could finally repro this with Python 3.10.0a4 @bkmckenzie. A workaround is to execute
```
python3 -m pip install wheel
```
before executing 
```
python3 -m pip install tensorrt_llm --extra-index-url https://pypi.nvidia.com --extra-index-url https://download.pytorch.org/whl/cu121
```
and then the command passes. Please give it a try and let me know thanks

**Comment by bkmckenzie** [comment]
Yes!  That worked like a champ!  Thank you!  I really appreciate you sticking with this!

**Comment by tp5uiuc** [comment]
Great, thanks for the confirmation. Closing this issue as completed, please feel free to re-open if you encounter it again :)
