### ISSUE TITLE
Building MIxtral on 8xA10 gives Cuda OOM

### ISSUE THREAD

**Issue by nivibilla** [NVIDIA/TensorRT-LLM#1156]
### System Info

8xA10

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Build Mixtral on a 8xA10 machine

### Expected behavior

should build as it should fit with tp8 in theory

### actual behavior

[TensorRT-LLM] TensorRT-LLM version: 0.9.0.dev2024022000
0.9.0.dev2024022000
Loading checkpoint shards: 100%|████████████████| 19/19 [00:46<00:00,  2.46s/it]
Traceback (most recent call last):
  File "/local_disk0/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 1509, in <module>
    main()
  File "/local_disk0/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 1485, in main
    covert_and_save(rank, convert_args)
  File "/local_disk0/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 1457, in covert_and_save
    weights = convert_hf_llama(
  File "/local_disk0/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 824, in convert_hf_llama
    torch.stack(list(model_params[f'model.layers.{l}.block_sparse_moe.experts.{expert}.{suffix}.weight']
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 896.00 MiB. GPU 1 has a total capacty of 21.99 GiB of which 747.06 MiB is free. Process 648875 has 21.25 GiB memory in use. Of the allocated memory 20.92 GiB is allocated by PyTorch, and 41.61 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

### additional notes

n/a

**Comment by mickaelseznec** [comment]
Hi @nivibilla, sorry for the late answer, can you try adding `--load_model_on_cpu`? That's just for the conversion step, then you should be able to run Mixtral on TP8 with A10.

**Comment by mickaelseznec** [comment]
Closing issue. Feel free to re-open in case my proposition didn't fix your issue.

**Comment by ghost** [comment]
If I use `--load_model_on_cpu`, doesn't this imply that no quantization calibration can be made for the Mixtral model as its not on GPU? 

How do I create W8A8 or INT8-kv cache versions of the Mixtral engine?

**Comment by mickaelseznec** [comment]
Actually, I've successfully build on 8xA30 (also 24GB of memory) with
`python3 examples/llama/convert_checkpoint.py --model_dir <..>/ --output_dir <...> --dtype float16 --tp_size 8`
Let me know if you have a reproducer for that OOM issue

**Comment by ghost** [comment]
> Actually, I've successfully build on 8xA30 (also 24GB of memory) with `python3 examples/llama/convert_checkpoint.py --model_dir <..>/ --output_dir <...> --dtype float16 --tp_size 8` Let me know if you have a reproducer for that OOM issue

Thanks @mickaelseznec, here's the reproduction on 8xA100 (40GB) using the 0.9.0 release

$ python examples/llama/convert_checkpoint.py --model_dir ./Mixtral-8x22B-Instruct-v0.1 --output_dir ./ckpt --dtype float16 --tp_size 8

[TensorRT-LLM] TensorRT-LLM version: 0.9.0
0.9.0
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████| 59/59 [12:56<00:00, 13.16s/it]
Traceback (most recent call last):
 in <module>
    main()
in main
    convert_and_save_hf(args)
in convert_and_save_hf
    execute(args.workers, [convert_and_save_rank] * world_size, args)
in execute
    f(args, rank)
in convert_and_save_rank
    llama = LLaMAForCausalLM.from_hugging_face(
in from_hugging_face
    llama = convert.from_hugging_face(
in from_hugging_face
    weights = load_weights_from_hf(config=config,
in load_weights_from_hf
    weights = convert_hf_llama(
in convert_hf_llama
    convert_layer(l)
in convert_layer
    f'model.layers.{l}.block_sparse_moe.experts.w3w1.weight'] = torch.concat(

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 384.00 MiB. GPU 0 has a total capacity of 39.39 GiB of which 134.81 MiB is free. Process 33539 has 0 bytes memory in use. Including non-PyTorch memory, this process has 0 bytes memory in use. Of the allocated memory 38.31 GiB is allocated by PyTorch, and 61.18 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expand

**Comment by wjj19950828** [comment]
@mickaelseznec same question in A100 * tp4

What do you recommend?

```shell
    torch.stack([model_params[f'model.layers.{l}.block_sparse_moe.experts.{expert}.{suffix}.weight'].detach()
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.50 GiB. GPU 0 has a total capacty of 79.33 GiB of which 367.81 MiB is free. Process 193307 has 78.96 GiB memory in use. Of the allocated memory 77.73 GiB is allocated by PyTorch, and 768.35 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
