### ISSUE TITLE
Usage of system prompt caching

### ISSUE THREAD

**Issue by littletomatodonkey** [NVIDIA/TensorRT-LLM#1159]
Hi, according to the readme.md, the `system prompt caching` is supported now, how can we use it ? thanks!

![image](https://github.com/NVIDIA/TensorRT-LLM/assets/14270174/081ceb38-4520-4830-97f6-aad43221f124)

**Comment by MuyeMikeZhang** [comment]
did you know how to use it?

**Comment by micyan01** [comment]
me too

**Comment by byshiue** [comment]
We have document about the cache resue [here](https://github.com/NVIDIA/TensorRT-LLM/blob/bf0a5afc92f4b2b3191e9e55073953c1f600cf2d/docs/source/kv_cache_reuse.md).

**Comment by micyan01** [comment]
Based on the document mentioned Above, User need to rebuilt tensorrt c++ first, which is not on hand.
