### ISSUE TITLE
build tensorrt-llm wheel failed for windows due to the batch_manager has no windows versinon

### ISSUE THREAD

**Issue by terryaic** [NVIDIA/TensorRT-LLM#1161]
### System Info

CPU: x86_64
OS: windows 11

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

docker build for wheel.

### Expected behavior

should be success

### actual behavior

no version found for windows tensorrt-llm-batch-manager.

### additional notes

quite easy to reproduce, just run the building trt-llm scripts under windows.

**Comment by tp5uiuc** [comment]
Hi @terryaic, same as #1209, currently windows build is only supported on the `rel` branch on which we do have the [windows version](https://github.com/NVIDIA/TensorRT-LLM/blob/rel/cpp/tensorrt_llm/batch_manager/x86_64-windows-msvc/tensorrt_llm_batch_manager_static.lib) of `batch_manager` updated for the latest release. Can you please check that branch out?
