### ISSUE TITLE
How to understand medusa_choices in example/run.py?

### ISSUE THREAD

**Issue by xikaluo** [NVIDIA/TensorRT-LLM#1163]
Hello, I'm just tried to apply Medusa decoding on llama model. However, I got confused about the argument medusa_choices. I found that this argument finally went into function _medusa_setup in runtime/medusa_utils.py. But the code of this function confused me. What is the meaning of number in medusa_choices? And how does this function implement the tree attention in Medusa paper? TYVM if you could provide some detailed introduction.

**Comment by rakib-hasan** [comment]
Hi. 
`medusa_choices` in TRT-LLM is equivalent of the tree representation in the [Medusa](https://github.com/FasterDecoding/Medusa/blob/main/notebooks/medusa_configuration_explained.ipynb) repo.
We did add one extension to it e.g. the choices [[0], [0,0], [0,0,0], [0,0,0,0]] can combined into just [[0,0,0,0]] i.e. no need to explicitly specify all the prefixes.

`_medusa_setup` is just preparing some buffers that get used during inference. Similar to [this](https://github.com/FasterDecoding/Medusa/blob/main/medusa/model/utils.py#L32). 
Some of those buffers e.g. `medusa_packed_mask` (a compressed version of the boolean tree attention mask) is given to the GPT attention plugin which runs the attention kernel that can apply the `medusa_packed_mask` if specified.

I hope this helps.

**Comment by xikaluo** [comment]
> Hi. `medusa_choices` in TRT-LLM is equivalent of the tree representation in the [Medusa](https://github.com/FasterDecoding/Medusa/blob/main/notebooks/medusa_configuration_explained.ipynb) repo. We did add one extension to it e.g. the choices [[0], [0,0], [0,0,0], [0,0,0,0]] can combined into just [[0,0,0,0]] i.e. no need to explicitly specify all the prefixes.
> 
> `_medusa_setup` is just preparing some buffers that get used during inference. Similar to [this](https://github.com/FasterDecoding/Medusa/blob/main/medusa/model/utils.py#L32). Some of those buffers e.g. `medusa_packed_mask` (a compressed version of the boolean tree attention mask) is given to the GPT attention plugin which runs the attention kernel that can apply the `medusa_packed_mask` if specified.
> 
> I hope this helps.

Ty for leading me to the medusa official notebook. I just forgot the 'root' node in the tree. Will keep on deploying it, thank you.
