### ISSUE TITLE
pip install tensorrt_llm --extra-index-url https://pypi.nvidia.com --extra-index-url https://download.pytorch.org/whl/cu121

### ISSUE THREAD

**Issue by realhaik** [NVIDIA/TensorRT-LLM#1165]
PS C:\ai\TensorLLM> pip install tensorrt_llm --extra-index-url https://pypi.nvidia.com --extra-index-url https://download.pytorch.org/whl/cu121
pip : DEPRECATION: Loading egg at c:\users\real\appdata\local\programs\python\python311\lib\site-packages\addict-2.4.0-py3.11.egg is deprecated. pip 24.3 will enforce 
this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
At line:1 char:1
+ pip install tensorrt_llm --extra-index-url https://pypi.nvidia.com -- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (DEPRECATION: Lo...ip/issues/12330:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
DEPRECATION: Loading egg at c:\users\real\appdata\local\programs\python\python311\lib\site-packages\aiofiles-23.2.1-py3.11.egg is deprecated. pip 24.3 will enforce this 
behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\real\appdata\local\programs\python\python311\lib\site-packages\ffmpy-0.3.1-py3.11.egg is deprecated. pip 24.3 will enforce this 
behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\real\appdata\local\programs\python\python311\lib\site-packages\gevent-23.7.0-py3.11-win-amd64.egg is deprecated. pip 24.3 will 
enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\real\appdata\local\programs\python\python311\lib\site-packages\geventhttpclient-2.0.2-py3.11-win-amd64.egg is deprecated. pip 24.3 
will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\real\appdata\local\programs\python\python311\lib\site-packages\gradio-3.40.1-py3.11.egg is deprecated. pip 24.3 will enforce this 
behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\real\appdata\local\programs\python\python311\lib\site-packages\gradio_client-0.4.0-py3.11.egg is deprecated. pip 24.3 will enforce 
this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\real\appdata\local\programs\python\python311\lib\site-packages\grpcio-1.57.0-py3.11-win-amd64.egg is deprecated. pip 24.3 will 
enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\real\appdata\local\programs\python\python311\lib\site-packages\httpx-1.0.0b0-py3.11.egg is deprecated. pip 24.3 will enforce this 
behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\real\appdata\local\programs\python\python311\lib\site-packages\importlib_metadata-6.8.0-py3.11.egg is deprecated. pip 24.3 will 
enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\real\appdata\local\programs\python\python311\lib\site-packages\importlib_resources-6.0.1-py3.11.egg is deprecated. pip 24.3 will 
enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\real\appdata\local\programs\python\python311\lib\site-packages\mdit_py_plugins-0.3.3-py3.11.egg is deprecated. pip 24.3 will 
enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\real\appdata\local\programs\python\python311\lib\site-packages\mmengine-0.8.4-py3.11.egg is deprecated. pip 24.3 will enforce this 
behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\real\appdata\local\programs\python\python311\lib\site-packages\opencv_python-4.8.0.76-py3.11-win-amd64.egg is deprecated. pip 24.3 
will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\real\appdata\local\programs\python\python311\lib\site-packages\orjson-3.9.5-py3.11-win-amd64.egg is deprecated. pip 24.3 will 
enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\real\appdata\local\programs\python\python311\lib\site-packages\platformdirs-3.10.0-py3.11.egg is deprecated. pip 24.3 will enforce 
this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\real\appdata\local\programs\python\python311\lib\site-packages\pybind11-2.11.1-py3.11.egg is deprecated. pip 24.3 will enforce this 
behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\real\appdata\local\programs\python\python311\lib\site-packages\pydub-0.25.1-py3.11.egg is deprecated. pip 24.3 will enforce this 
behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\real\appdata\local\programs\python\python311\lib\site-packages\pygments-2.16.1-py3.11.egg is deprecated. pip 24.3 will enforce this 
behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\real\appdata\local\programs\python\python311\lib\site-packages\python_multipart-0.0.6-py3.11.egg is deprecated. pip 24.3 will 
enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\real\appdata\local\programs\python\python311\lib\site-packages\python_rapidjson-1.10-py3.11-win-amd64.egg is deprecated. pip 24.3 
will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\real\appdata\local\programs\python\python311\lib\site-packages\quant_cuda-0.0.0-py3.11-win-amd64.egg is deprecated. pip 24.3 will 
enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\real\appdata\local\programs\python\python311\lib\site-packages\rich-13.5.2-py3.11.egg is deprecated. pip 24.3 will enforce this 
behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\real\appdata\local\programs\python\python311\lib\site-packages\semantic_version-2.10.0-py3.11.egg is deprecated. pip 24.3 will 
enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\real\appdata\local\programs\python\python311\lib\site-packages\tiktoken-0.4.0-py3.11-win-amd64.egg is deprecated. pip 24.3 will 
enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\real\appdata\local\programs\python\python311\lib\site-packages\tomli-2.0.1-py3.11.egg is deprecated. pip 24.3 will enforce this 
behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\real\appdata\local\programs\python\python311\lib\site-packages\tritonclient-2.36.0-py3.11.egg is deprecated. pip 24.3 will enforce 
this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\real\appdata\local\programs\python\python311\lib\site-packages\websockets-11.0.3-py3.11-win-amd64.egg is deprecated. pip 24.3 will 
enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\real\appdata\local\programs\python\python311\lib\site-packages\yapf-0.40.1-py3.11.egg is deprecated. pip 24.3 will enforce this 
behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
Looking in indexes: https://pypi.org/simple, https://pypi.nvidia.com, https://download.pytorch.org/whl/cu121
Collecting tensorrt_llm
  Using cached tensorrt-llm-0.7.1.tar.gz (6.9 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  python setup.py egg_info did not run successfully.
  exit code: 1
  
  [6 lines of output]
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\Real\AppData\Local\Temp\pip-install-u3y4yvyp\tensorrt-llm_88a6dbc662754cf0a41c985e2110d1ec\setup.py", line 90, in <module>
      raise RuntimeError("Bad params")
  RuntimeError: Bad params
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
Encountered error while generating package metadata.
See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

PS C:\ai\TensorLLM>

**Comment by hello-11** [comment]
@realhaik Do you still have the question? If not, we will close it soon.
