### ISSUE TITLE
FP8 quant with "--use_paged_context_fmha enable" on llama2-7b get wrong result

### ISSUE THREAD

**Issue by kimbaol** [NVIDIA/TensorRT-LLM#1169]
### System Info

GPU:L40S
OS:docker(tensorrt-llm make to produce image)
TensorRT-LLM version: 0.9.0.dev2024022000
driver:535.104.12
CUDA Version: 12.3

### Who can help?

@Tracin @byshiue 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. python quantization/quantize.py --model_dir /tmp/llama2-7b-hf  --dtype float16  --qformat fp8  --kv_cache_dtype fp8 --output_dir /tmp/llama2-7b/tllm_checkpoint_tp1_fp8/ --calib_size 512
2. trtllm-build --checkpoint_dir /tmp/llama2-7b/tllm_checkpoint_tp1_fp8/  --output_dir /tmp/llama2-7b/1tp_fp8/ --gemm_plugin float16  --strongly_typed  --max_batch_size 32 --use_paged_context_fmha enable
3. python run.py --engine_dir /tmp/llama2-7b/1tp_fp8/ --max_output_len=50 --tokenizer_dir /tmp/llama2-7b-hf/

### Expected behavior
```
Input [Text 0]: "<s> Born in north-east France, Soyer trained as a"
Output [Text 0 Beam 0]: "chef at the Lycée Hôtelier de Belfort, and then worked in a number of restaurants in France and Switzerland. He moved to London in 1999, and worked at the Savoy, the Dorchester and"
```

### actual behavior
```
Input [Text 0]: "<s> Born in north-east France, Soyer trained as a"
Output [Text 0 Beam 0]: "T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T T"
```
### additional notes

If build with "--use_paged_context_fmha disable", the result is correct.

**Comment by realhaik** [comment]
You want it also to produce the correct results? Unfortently here they are only about installing things, they dont care about results.

**Comment by Tracin** [comment]
@kimbaol  According to the title, does that mean we can get right result if `--use_paged_context_fmha` disabled?

**Comment by qiaoxj07** [comment]
> @kimbaol According to the title, does that mean we can get right result if `--use_paged_context_fmha` disabled?

@Tracin  Yes, disable `--use_paged_context_fmha` will get the right result.

I did several tests:
1. FP8 + `--use_paged_context_fmha enable` -> wrong result.
2. FP8 +  `--use_paged_context_fmha disable` -> right result.
3. FP16 + `--use_paged_context_fmha enable`  -> right result.

So I think maybe paged_context_fmha is not compatible with FP8 quant.

**Comment by Tracin** [comment]
Thanks for your test, must be some bug with FP8 and paged context fmha, we will investigate that.

**Comment by Tracin** [comment]
It turns out that paged_context_fmha do not support FP8. @PerkzZheng
