### ISSUE TITLE
always get same output result in multi time inference

### ISSUE THREAD

**Issue by xiaochus** [NVIDIA/TensorRT-LLM#117]
I use llama example to test vicuna-13B 1.2 FP16. The `decoder.decode` function always get the same result, event add the random sample parameters in SamplingConfig.  The output should be difference in each time inference.

```
    sampling_config = SamplingConfig(end_id=EOS_TOKEN,
                                     pad_id=PAD_TOKEN,
                                     top_k=50,
                                     top_p=1.0,
                                     temperature=0.7,
                                     num_beams=num_beams)
```

**Comment by jdemouth-nvidia** [comment]
Hi @xiaochus ,

I’m tempted to say that it depends. If you rerun the generation “entirely” and use the same random seed each time, it should actually always give the same result. So, can you tell us more about what you’re doing, please?

Thanks,
Julien

**Comment by eval-dev** [comment]
hi @jdemouth-nvidia I have the same issue. My input batch is the same prompt repeat N times. The outputs in batch are exact the same. Looks like sampling doesn't work. Confg:

```
    sampling_config = SamplingConfig(end_id=EOS_TOKEN,
                                     pad_id=PAD_TOKEN,
                                     top_k=50,
                                     top_p=1.0,
                                     temperature=1,
```

**Comment by eval-dev** [comment]
Looks like bc `dynamic_decoder.setup()` is called every time when calling `GenerationSession.decode()`: https://github.com/NVIDIA/TensorRT-LLM/blob/v0.5.0/tensorrt_llm/runtime/generation.py#L636 , as a result, the seed is constantly set to 0: https://github.com/NVIDIA/TensorRT-LLM/blob/v0.5.0/cpp/tensorrt_llm/layers/baseSamplingLayer.cpp#L122

One workaround is to allow users pass their own seed value via SamplingConfig. The `init=False` restriction needs to be removed: https://github.com/NVIDIA/TensorRT-LLM/blob/v0.5.0/tensorrt_llm/runtime/generation.py#L276

**Comment by byshiue** [comment]
A quick way to assing random seed is
```python
    sampling_config = SamplingConfig(end_id=EOS_TOKEN,
                                     pad_id=PAD_TOKEN,
                                     top_k=50,
                                     top_p=1.0,
                                     temperature=1,
    sampling_config.random_seed = torch.Tensor([1, 2]).to(torch.int64) # assume batch size is 2
```

**Comment by eval-dev** [comment]
> A quick way to assing random seed is
> 
> ```python
>     sampling_config = SamplingConfig(end_id=EOS_TOKEN,
>                                      pad_id=PAD_TOKEN,
>                                      top_k=50,
>                                      top_p=1.0,
>                                      temperature=1,
>     sampling_config.random_seed = torch.Tensor([1, 2]).to(torch.int64) # assume batch size is 2
> ```

@byshiue yeah, I'm able to get real randomness in this way.

**Comment by xiaochus** [comment]
> A quick way to assing random seed is
> 
> ```python
>     sampling_config = SamplingConfig(end_id=EOS_TOKEN,
>                                      pad_id=PAD_TOKEN,
>                                      top_k=50,
>                                      top_p=1.0,
>                                      temperature=1,
>     sampling_config.random_seed = torch.Tensor([1, 2]).to(torch.int64) # assume batch size is 2
> ```

@byshiue Thanks, this method works. I set the random_seed for every inference and get random output.

**Comment by byshiue** [comment]
Thank you for update, close this issue.

**Comment by shatealaboxiaowang** [comment]
In general, don't you just set temperature to 0 and get a random output? Why set random_seed ?
