### ISSUE TITLE
Medusa convert cpt doesn't work with safetensors version

### ISSUE THREAD

**Issue by nivibilla** [NVIDIA/TensorRT-LLM#1171]
### System Info

N/A

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [x] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

 try converting a medusa checkpoint using
text-generation-inference/Mistral-7B-Instruct-v0.2-medusa

### Expected behavior

Should load from safe tensors

### actual behavior

script expects a "medusa_lm_head.pt" in folder

### additional notes

n/a

**Comment by nivibilla** [comment]
Second error with
`Expected but not provided tensors: {'medusa_heads.3.medusa_layers.0.linear.bias', 'medusa_heads.3.lm_head.weight', 'medusa_heads.3.medusa_layers.0.linear.weight'}`

**Comment by rakib-hasan** [comment]
Thanks for reporting this. @nivibilla 
You are correct. The script needs to be updated to be able to load safe tensors as well.

**Comment by Tushar-ml** [comment]
Opened a PR #1535  for this

**Comment by Tushar-ml** [comment]
@ncomly-nvidia kindly review this PR

**Comment by Tushar-ml** [comment]
This has been merged, we can close this issue
