### ISSUE TITLE
int16 support

### ISSUE THREAD

**Issue by dongxuemin666** [NVIDIA/TensorRT-LLM#1178]
### System Info

Linux centos

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Thx for your excellent work
I wonder Is tensorRT-llm support int 16 quantization

### Expected behavior

none

### actual behavior

none

### additional notes

none

**Comment by byshiue** [comment]
Could you explain the motivation or target to support INT16? From computing view, INT16 should have same peak ops as float16 and bfloat16. Why do we need to use INT16 instread of using float16 or bfloat16?

**Comment by hello-11** [comment]
@dongxuemin666 Do you still have the question? If not, we will close it soon.
