### ISSUE TITLE
[Feature Request]Can you provide a C++ Demo code running LLM like llama.cpp

### ISSUE THREAD

**Issue by engineer1109** [NVIDIA/TensorRT-LLM#1179]
I see use ModelRunnerCpp use cpp runtime.
How can i use the interface cpp to run LLM models. (like https://github.com/ggerganov/llama.cpp)
Any sample Code? (No need tokenizers, just model init and run and input output)

**Comment by tikikun** [comment]
interested

**Comment by tikikun** [comment]
https://github.com/NVIDIA/TensorRT-LLM/blob/rel/cpp/tests/runtime/gptSessionTest.cpp

This ?

**Comment by engineer1109** [comment]
@tikikun It looks helpful. I will take time to try.
For more, it will be better to  provide a simple tutorial code like examples/run.py  for more easy to use.

**Comment by tikikun** [comment]
<img width="679" alt="image" src="https://github.com/NVIDIA/TensorRT-LLM/assets/22268502/4ef89670-5bc5-4d45-a7dc-e27793fe1134">
i have successfully compiled by facing this LLVM out of memory very strange, any suggestion ?

**Comment by tikikun** [comment]
16bit engine run fine with pyhton version

**Comment by tikikun** [comment]
push the sample code here

https://github.com/janhq/nitro-tensorrt-llm/tree/main/examples/example_trt_llm

**Comment by engineer1109** [comment]
> push the sample code here
> 
> https://github.com/janhq/nitro-tensorrt-llm/tree/main/examples/example_trt_llm

Looks Cool!
