### ISSUE TITLE
convert_hf_mpt_to_ft is hanging while downloading shards

### ISSUE THREAD

**Issue by tapansstardog** [NVIDIA/TensorRT-LLM#118]
Hi Team,

I am converting `mosaicml/mpt-30b` HF model to TF using [convert_hf_mpt_to_ft.py](https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/examples/mpt/convert_hf_mpt_to_ft.py). The progress is always hanging while downloading shards. Once all the shards of HF model are downloaded, the progress just hang there for 10-15 mins. I am not sure whether it is a hang or should I wait for some more time?

Steps performed:

1. Launch the Tensorrt-LLM container
`make -C docker release_run LOCAL_USER=1`

2. `python convert_hf_mpt_to_ft.py -i mosaicml/mpt-30b -o ./ft_ckpts/mpt-7b/fp16/ --tensor_parallelism 4 -t float16`

I have tried this on `launchpad` as well as on `EC2 g5.12xlarge` machine.

Also, as I can see for `llama` model we can directly pass HF model name to `build.py` however for `mpt` models I believe conversion from `HF` to `FT` model is mandatory. Is our understanding correct?

Thanks!

**Comment by tsharma82** [comment]
Update:
It was not a "hang". It made progress after around 25-30 mins.

**Comment by tapansstardog** [comment]
`Update`:
It was not a "`hang`". It made progress after around 25-30 mins.

**Comment by jdemouth-nvidia** [comment]
Thanks @tapansstardog for the update. I’m closing as Not-a-Bug. Reopen it if there is a real issue, please.

**Comment by tapansstardog** [comment]
@jdemouth-nvidia Can you confirm the second part:

> Also, as I can see for llama model we can directly pass HF model name to build.py however for mpt models I believe conversion from HF to FT model is mandatory. Is our understanding correct?

**Comment by byshiue** [comment]
> @jdemouth-nvidia Can you confirm the second part:
> 
> > Also, as I can see for llama model we can directly pass HF model name to build.py however for mpt models I believe conversion from HF to FT model is mandatory. Is our understanding correct?

The conversion is mandatory now. This process can be merged into `build.py`, but we split them because it is more convenient to do calibration on the weight for lower bit inference.
