### ISSUE TITLE
Mixtral - no run.py file

### ISSUE THREAD

**Issue by maciekpoplawski** [NVIDIA/TensorRT-LLM#1181]
### System Info

PC

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/mixtral
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/54249329/24140f6d-5edd-4946-8fcd-e26dd8bf4cc1)

https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/mixtral/examples/run.py
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/54249329/02da1c94-6bb5-4c41-aa82-bfa1b548120c)

### Expected behavior

run.py file present

### actual behavior

run.py file NOT present

### additional notes

---

**Comment by aikitoria** [comment]
This one? You have examples folder twice in your path. https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/run.py

**Comment by maciekpoplawski** [comment]
> This one? You have examples folder twice in your path. https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/run.py

im following official docs provided. Would be cool to fix the link for the run.py if it should point to somewhere else, hence the bug

**Comment by byshiue** [comment]
Thank you for the report. Yes, you should use https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/run.py. We will fix it in next update.
