### ISSUE TITLE
Multi Modal Question

### ISSUE THREAD

**Issue by haohuanw** [NVIDIA/TensorRT-LLM#1185]
in multi modal example, i see fake prompt id is different for every embedding token:

https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/multimodal/run.py#L271-L275

is this by design in TRT-LLM? my custom tokenizer tokenize into same id for embedding and i could workaround it to fit what trt-llm is looking for but i am wondering if this is something by design or there are someways to achieve with a combination of prompt tuning params?

**Comment by amukkara** [comment]
`fake_prompt_id` can contain same id multiple times and in any order.  If id is in `[0, vocab_size)` range, it indexes into text embedding table. If id is in `[vocab_size, vocab_size + max_prompt_embedding_table_size)`,  it indexes into prompt table.

In multimodal example, we provide image features as input to model in addition to text prompt. So, `fake_prompt_id` is initialized to `[vocab_size, vocab_size + 1, vocab_size + 2, ..,]`. These ids index into prompt table which contains image features.

**Comment by haohuanw** [comment]
sounds good. thanks for the explanation

**Comment by Popsicle0-0** [comment]
> `fake_prompt_id` can contain same id multiple times and in any order. If id is in `[0, vocab_size)` range, it indexes into text embedding table. If id is in `[vocab_size, vocab_size + max_prompt_embedding_table_size)`, it indexes into prompt table.
> 
> In multimodal example, we provide image features as input to model in addition to text prompt. So, `fake_prompt_id` is initialized to `[vocab_size, vocab_size + 1, vocab_size + 2, ..,]`. These ids index into prompt table which contains image features.

What conditions need to be met when using a prompt_table? I am trying to convert minicpm_llama3_v2.5, and if I have a custom method to merge input_id and vit, where should this logic be applied? I found that GenerationSession seems to only accept input_ids as input, and when I used input_embeds as the only input, various issues arose. I want to try using prompt_table. Do you have any suggestions?
