### ISSUE TITLE
gpu memory usage is too high

### ISSUE THREAD

**Issue by zaykl** [NVIDIA/TensorRT-LLM#1188]
### System Info

- CPU architecture: x86_64
- CPU/Host memory size: 32G
- GPU properties
- GPU name: RTX3090
- GPU memory size: 24GB
- Libraries
- - TensorRT-LLM branch or tag (e.g., main, v0.7.1): 0.9.0.dev2024022000
- OS (Ubuntu 22.04, CentOS 7, Windows 10): ubuntu22.04

### Who can help?

@kaiyux 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
python ./convert_checkpoint.py --model_dir /home/kk/data/aigodata/llmdata/meta-Llama-2-7b-chat-hf \
                              --output_dir /home/kk/data/aigodata/llmdata/meta-Llama-2-7b-chat-hf/trtint8 \
                              --dtype float16 \
                              --int8_kv_cache \
                             --use_weight_only \
                             --weight_only_precision int8

trtllm-build --checkpoint_dir /home/kk/data/aigodata/llmdata/meta-Llama-2-7b-chat-hf/trtint8 \
            --output_dir /home/kk/data/aigodata/llmdata/meta-Llama-2-7b-chat-hf/trtint8_engine \
            --gemm_plugin float16 \

python3 ../run.py --max_output_len=256 \
                  --run_profiling \
                  --tokenizer_dir /home/kk/data/aigodata/llmdata/meta-Llama-2-7b-chat-hf \
                  --engine_dir /home/kk/data/aigodata/llmdata/meta-Llama-2-7b-chat-hf/trtint8_engine \
                  --input_text "write a poem about \n"
```

### Expected behavior

The size of trt engine file rank0.engine is : 7G. Normally GPU memory usage should be 7~8G.

### actual behavior

And when execute the llama demo, the usage of GPU memory will be 20G. Why the GPU memory take so much?
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.29.02              Driver Version: 545.29.02    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3090        Off | 00000000:03:00.0 Off |                  N/A |
| 32%   40C    P2             340W / 350W |  22606MiB / 24576MiB |     99%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A     28974      C   python3                                   22580MiB |
+---------------------------------------------------------------------------------------+


```

### additional notes

The output result
```
Input [Text 0]: "<s> write a poem about \n"
Output [Text 0 Beam 0]: "\tthe beauty of nature"

Sure, here is a poem about the beauty of nature:

In nature's embrace I find my peace,
Beneath the trees, my spirit releases,
The rustle of leaves, a gentle breeze,
Echoes of life, that e'er will please.

The sun's warm rays upon my face,
Bring joy to this place, this sacred space,
Where nature's beauty, I do embrace,
And find solace in her gentle grace.

The flowers bloom, their colors bright,
A kaleidoscope of hues, a wondrous sight,
Their sweet fragrance, fills the air,
Invigorating all, who dare to share.

In nature's arms, I find my home,
A sense of belonging, where I am never alone,
For in her beauty, I am free,
To be myself, wild and carefree.

So here I'll stay, and dream awhile,
In nature's embrace, where love does smile,
For in her beauty, I find my peace,
```

**Comment by AbhinavDutta** [comment]
faced similar issue, for me llama 7b takes 73G!! (on 1xA100). looks like an excessively large kv cache is allocated that occupies all possible space. can you check if you face the same issue ?

**Comment by willosonico** [comment]
same issue here with vila 1.5-3b with int4_weightsonly quantization

| NVIDIA-SMI 525.60.13    Driver Version: 525.60.13    CUDA Version: 12.0     |
...
|    0   N/A  N/A   1056794      C   python3.10                      19620MiB |

**Comment by hello-11** [comment]
@zaykl Do you still have the question? If not, we will close soon.

**Comment by willosonico** [comment]
> [@zaykl](https://github.com/zaykl) Do you still have the question? If not, we will close soon.

He's not the only one with this bug

**Comment by zaykl** [comment]
> [@zaykl](https://github.com/zaykl) Do you still have the question? If not, we will close soon.

I don't see any suggest for this issue!

**Comment by ayaromenok** [comment]
> faced similar issue, for me llama 7b takes 73G!! (on 1xA100). looks like an excessively large kv cache is allocated that occupies all possible space. can you check if you face the same issue ?

"If neither maxTokens nor freeGpuMemoryFraction is specified, KV cache will by default allocate 90% of the remaining free GPU memory. "
https://nvidia.github.io/TensorRT-LLM/reference/memory.html

**Comment by ayaromenok** [comment]
@zaykl @willosonico 

There two separate issues with high memory consumption - KV cache and meory for runtime buffers/decoder/etc - related to default behavior - and can be changed via command line arguments:

tetllm-build:

--max_num_tokens - decrease number. For shot answer 512 is Ok. Typical value for llama.cpp(ollama, lmm-studio, etc) - 4096. 
--max_batch_size - decrease number up to 1 if you use single videocard without HBM memory

python3 ../run(or C++ runtime) 
 --kv_cache_free_gpu_memory_fraction decrease fraction number from 0.9(default) to to small value (0.001 for max_num_tokens 512,  0.004 for 4096 in case of 16GB videocard). Just found suitable to your model/video memory

In my case: model qwen2.5-coder-0.5B-instruct/int8 on Quadro A4000(16GB VRAM) default value was used around **15 GB** VRAM:
```
Loaded engine size: 875 MiB
Allocated 773.51 MiB for execution context memory.
TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 869 (MiB)
 Allocated 2.66 GB GPU memory for runtime buffers.
Allocated 5.76 GB GPU memory for decoder.
Allocated 4.53 GiB for max tokens in paged KV cache (395776).
```
and became  **1 182** MB VRAM with 512 tokens, batch  1 and gpu memory fraction 0.001
```
Loaded engine size: 875 MiB
Allocated 43.26 MiB for execution context memory.
TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 869 (MiB)
Allocated 1.33 MB GPU memory for runtime buffers.
Allocated 2.88 MB GPU memory for decoder.
Allocated 0.01 GiB for max tokens in paged KV cache (640).
```

**Comment by ayaromenok** [comment]
@zaykl @willosonico 

There two separate issues with high memory consumption - KV cache and memory for runtime buffers/decoder/etc - related to default behavior - and can be changed via command line arguments:

trtllm-build:
```--max_num_tokens``` - decrease number. For shot answers 512 is Ok. Typical value for llama.cpp(ollama, lmm-studio, etc) is 4096. 
```--max_batch_size ``` - decrease number up to 1 if you use single videocard without HBM memory

python3 ../run(or C++ runtime) 
``` --kv_cache_free_gpu_memory_fraction``` decrease fraction number from 0.9(default) to to small value (0.001 for max_num_tokens 512,  0.004 for 4096 in case of 16GB videocard). Just found suitable to your model/video memory

In my case: model qwen2.5-coder-0.5B-instruct/int8 on Quadro A4000(16GB VRAM) default value was used **15 202 MB** VRAM:
```
Loaded engine size: 875 MiB
Allocated 773.51 MiB for execution context memory.
Allocated 2.66 GB GPU memory for runtime buffers.
Allocated 5.76 GB GPU memory for decoder.
Allocated 4.53 GiB for max tokens in paged KV cache (395776).
```
and became  **1 182** MB VRAM with 512 tokens, batch  1 and gpu memory fraction 0.001
```
Loaded engine size: 875 MiB
Allocated 43.26 MiB for execution context memory.
Allocated 1.33 MB GPU memory for runtime buffers.
Allocated 2.88 MB GPU memory for decoder.
Allocated 0.01 GiB for max tokens in paged KV cache (640).
```

upd: memory consumption still  a bit higher than llama.cpp due to bigger weight file(which include some optimizations) for int8/Q8_0 model (875 vs 638MB), but other memory parameters looks similar. Also tensorrt-llm is faster than llama.cpp - 1.43sec vs 1.93sec for such small(0.5B) model, while became more leveled on bigger models

**Comment by zaykl** [comment]
@ayaromenok Thx. It help me a lot.
