### ISSUE TITLE
does trt-llm support w4a8 (int4 * int8)?

### ISSUE THREAD

**Issue by yyfcc17** [NVIDIA/TensorRT-LLM#1189]
for gpus like a30 and a100, they don't support fp8, is there a plan to support w4a8 (int4 * int8)?

**Comment by byshiue** [comment]
Currently, we don't have such plan in our roadmap. If you are interested, you could create a feature request ticket to help tracking, and we will consider its priority.

**Comment by yyfcc17** [comment]
FYI, there is a pr in cutlass, i will close this.

https://github.com/NVIDIA/cutlass/pull/1413
