### ISSUE TITLE
Failed to quantize LLaMA2 model using AWQ(W4A8)

### ISSUE THREAD

**Issue by asterich** [NVIDIA/TensorRT-LLM#1195]
### System Info

- CPU archtecture: x86_64
- CPU/Host memory size: 1008GB total
- GPU properties
   - GPU name: 2x NVIDIA L40 48GB
   - GPU memory size: 96GB total
- Libraries
   - tensorrt==9.2.0.post12.dev5
   - tensorrt-llm==0.9.0.dev2024022000
   - nvidia-ammo==0.7.3
   - Container used: tensorrt_llm/release:latest
- NVIDIA driver version: 535.154.05
- OS: Ubuntu 20.04 focal
- CUDA version: 12.2

### Who can help?

@Tracin

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Build the official docker image with [https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/build_from_source.md#option-1-build-tensorrt-llm-in-one-step](https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/build_from_source.md#option-1-build-tensorrt-llm-in-one-step)
2. quantize the model using the command provided [here](https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/llama):
```
python ../quantization/quantize.py --model_dir /tmp/my_model \
                                   --output_dir ./tllm_checkpoint_1gpu_awq_int8_kv_cache \
                                   --dtype float16 \
                                   --qformat int4_awq \
                                   --awq_block_size 128 \
                                   --kv_cache_dtype int8 \
                                   --calib_size 32
```

2. launch docker container:
```
sudo docker run --rm -it --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 \
           --gpus=all \
           --volume /data/asc24llama/zbtrs/TensorRT-LLM:/code/tensorrt_llm \
           --volume /data:/app/models \
           --volume /data/asc24llama/clash:/app/clash \
           --volume /data/tllm_checkpoint_1gpu_awq_int8_kv_cache:/app/modified_model \
           --env "CCACHE_DIR=/code/tensorrt_llm/cpp/.ccache" \
           --env "CCACHE_BASEDIR=/code/tensorrt_llm" \
           --workdir /app/tensorrt_llm \
           --hostname hepgpu3-release \
           --name tensorrt_llm-release-root \
           --tmpfs /tmp:exec \
           tensorrt_llm/release:latest
```
4. run trtllm-build:
```
trtllm-build --checkpoint_dir /app/modified_model \
            --output_dir /app/int8_kv_cache_int4_AWQ/1-gpu/ \
            --gemm_plugin float16
```

### Expected behavior

trtllm-build completes successfully

### actual behavior

The quantization completes without error, but trtllm-build failed with message:

```
[02/27/2024-14:41:16] [TRT] [W] IElementWiseLayer with inputs LLaMAForCausalLM/transformer/ln_f/REDUCE_AVG_0_output_0 and LLaMAForCausalLM/transformer/ln_f/SHUFFLE_1_output_0: first input has type Half but second input has type Float.
[02/27/2024-14:41:16] [TRT-LLM] [I] Build TensorRT engine Unnamed Network 0
[02/27/2024-14:41:16] [TRT] [W] Unused Input: position_ids
[02/27/2024-14:41:16] [TRT] [W] Calibrator is not being used. Users must provide dynamic range for all tensors that are not Int32 or Bool.
[02/27/2024-14:41:16] [TRT] [E] 4: [standardEngineBuilder.cpp::initCalibrationParams::1837] Error Code 4: Internal Error (Calibration failure occurred with no scaling factors detected. This could be due to no int8 calibrator or insufficient custom scales for network layers. Please see int8 sample to setup calibration correctly.)
```
Full log is provided here: [log.txt](https://github.com/NVIDIA/TensorRT-LLM/files/14447927/log.txt)

### additional notes

It seems that calibration didn't work successfully.

**Comment by aikitoria** [comment]
I had the same issue when trying to use int8 kv cache.

**Comment by Tracin** [comment]
Please try to add `--gpt_attention_plugin float16 --strongly_typed`

**Comment by asterich** [comment]
@Tracin 

Thank you for your reply!

I added these options to `trtllm-build` and it worked well, but when I try to run the model with the command below: 
```
python3 ../run.py --max_output_len=50 \
 --tokenizer_dir /app/models/Aquila/AquilaChat2-34B/ \
 --engine_dir=/app/int8_kv_cache_int4_AWQ/1-gpu \
 --input_file /code/tensorrt_llm/examples/llama/generated_chinese_questions.txt
```
I ended up with OOM error. Full logs are provided here: [log.txt](https://github.com/NVIDIA/TensorRT-LLM/files/14459202/log.txt)

As a contrast, when I try only AWQ 4-bit quantization using the official quantize and trtllm_build command without --gpt_attention_plugin float16 --strongly_typed, and execute it with the command: 
```
python3 ../run.py --max_output_len=50 \
 --tokenizer_dir /app/models/Aquila/AquilaChat2-34B/ \
 --engine_dir=/app/models/int4_AWQ/1-gpu \
 --input_file /code/tensorrt_llm/examples/llama/generated_chinese_questions.txt
```
This problem does not occur and the model worked perfectly. Why is that?

**Comment by zbtrs** [comment]
I had the same issue

**Comment by Tracin** [comment]
> @Tracin
> 
> Thank you for your reply!
> 
> I added these options to `trtllm-build` and it worked well, but when I try to run the model with the command below:
> 
> ```
> python3 ../run.py --max_output_len=50 \
>  --tokenizer_dir /app/models/Aquila/AquilaChat2-34B/ \
>  --engine_dir=/app/int8_kv_cache_int4_AWQ/1-gpu \
>  --input_file /code/tensorrt_llm/examples/llama/generated_chinese_questions.txt
> ```
> 
> I ended up with OOM error. Full logs are provided here: [log.txt](https://github.com/NVIDIA/TensorRT-LLM/files/14459202/log.txt)
> 
> As a contrast, when I try only AWQ 4-bit quantization using the official quantize and trtllm_build command without --gpt_attention_plugin float16 --strongly_typed, and execute it with the command:
> 
> ```
> python3 ../run.py --max_output_len=50 \
>  --tokenizer_dir /app/models/Aquila/AquilaChat2-34B/ \
>  --engine_dir=/app/models/int4_AWQ/1-gpu \
>  --input_file /code/tensorrt_llm/examples/llama/generated_chinese_questions.txt
> ```
> 
> This problem does not occur and the model worked perfectly. Why is that?

Sorry, what is the exact difference between them?

**Comment by asterich** [comment]
> > @Tracin
> > Thank you for your reply!
> > I added these options to `trtllm-build` and it worked well, but when I try to run the model with the command below:
> > ```
> > python3 ../run.py --max_output_len=50 \
> >  --tokenizer_dir /app/models/Aquila/AquilaChat2-34B/ \
> >  --engine_dir=/app/int8_kv_cache_int4_AWQ/1-gpu \
> >  --input_file /code/tensorrt_llm/examples/llama/generated_chinese_questions.txt
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I ended up with OOM error. Full logs are provided here: [log.txt](https://github.com/NVIDIA/TensorRT-LLM/files/14459202/log.txt)
> > As a contrast, when I try only AWQ 4-bit quantization using the official quantize and trtllm_build command without --gpt_attention_plugin float16 --strongly_typed, and execute it with the command:
> > ```
> > python3 ../run.py --max_output_len=50 \
> >  --tokenizer_dir /app/models/Aquila/AquilaChat2-34B/ \
> >  --engine_dir=/app/models/int4_AWQ/1-gpu \
> >  --input_file /code/tensorrt_llm/examples/llama/generated_chinese_questions.txt
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This problem does not occur and the model worked perfectly. Why is that?
> 
> Sorry, what is the exact difference between them?

The model from the previous command used AWQ+int8 kvcache quantization, while the latter only used AWQ for quantization.
