### ISSUE TITLE
Getting error when running tritonserver with tensorrt_llm whisper

### ISSUE THREAD

**Issue by shashikr2** [NVIDIA/TensorRT-LLM#1197]
### System Info

-GPU Name: A100

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Step 1:
build image with base image 23.12-trtllm-python-py3  by running the command  'make -C docker release_build'
Step 2: wget --quiet https://openaipublic.azureedge.net/main/whisper/models/e5b1a55b89c1367dacf97e3e19bfd829a01529dbfdeefa8caeb59b3f1b81dadb/large-v3.pt

Step 3: python3 whisper/build.py --output_dir models/whisper_large_v3 --model_dir data --model_name large-v3 --dtype float16  --max_batch_size 4 --max_beam_width 1 --max_output_len 448 --max_input_len 4 --use_gpt_attention_plugin --use_gemm_plugin

Step 4: Create python backend triton server config in which I simple used whisper run.py code 

Step 5: tritonserver --model-repository=triton_model/

### Expected behavior

It should not give this invalid pointer error when running python backend.Python

### actual behavior

[TensorRT-LLM] TensorRT-LLM version: 0.8.0[TensorRT-LLM] TensorRT-LLM version: 0.8.0[TensorRT-LLM] TensorRT-LLM version: 0.8.0free(): invalid pointer

### additional notes

Install tensorrt_llm over python backend tritonserver

**Comment by yuekaizhang** [comment]
@shashikr2  https://github.com/k2-fsa/sherpa/pull/551 Check this PR please.
