### ISSUE TITLE
llama quantize fp8 `export_model_config` hardcoded to float16?

### ISSUE THREAD

**Issue by phind-justin** [NVIDIA/TensorRT-LLM#1200]
### System Info

.

### Who can help?

@Tracin 

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [x] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

.

### Expected behavior

.

### actual behavior

.

### additional notes

v0.8.0

I'm trying to quantize a llama 70b to fp8 and it seems like `tensorrt_llm/models/llama/quantize.py` calls `quantize_and_export` which is defined in `models/quantized/ammo.py` which finally runs this:
```
                export_model_config(
                    model,
                    model_type,
                    torch.float16,
                    export_dir=export_path,
                    inference_tensor_parallel=tensor_parallel_size,
                    export_npz=True,
                )
```

what's important about the exported dtype hardcoded to float16? my model (llama 70b) is trained in bloat16. 

will exporting the fp8 scaling factors in float16 work with a `build.py --dtype bfloat16`?

**Comment by Tracin** [comment]
Actually `ammo.py` will be deprecated, you do not need to use this one. Please use `example/quantization/quantize.py` instead.
