### ISSUE TITLE
"Fp16 precision has been set for a layer or layer output, but fp16 is not configured in the builder" when trying to convert a nvidia-

### ISSUE THREAD

**Issue by giancarlo-metitieri** [NVIDIA/TensorRT-LLM#1201]
### System Info

- CPU Architecture: x86_64
- CPU Type: AMD Epyc 9654
- GPU Type: Nvidia H100
- Nvidia Docker Container: nvcr.io/nvidia/nemo:24.01.gemma

### Who can help?

@Tracin

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

1. Train a Gemma model with bfloat16, which leads to a model of following configuration: 
```
{
  "_name_or_path": "./lilac-ultra-base-bf16",
  "architectures": [
    "GemmaForCausalLM"
  ],
  "attention_bias": false,
  "attention_dropout": 0.0,
  "bos_token_id": 2,
  "eos_token_id": 1,
  "head_dim": 256,
  "hidden_act": "gelu",
  "hidden_size": 3072,
  "initializer_range": 0.02,
  "intermediate_size": 24576,
  "max_position_embeddings": 8192,
  "model_type": "gemma",
  "num_attention_heads": 16,
  "num_hidden_layers": 28,
  "num_key_value_heads": 16,
  "pad_token_id": 0,
  "rms_norm_eps": 1e-06,
  "rope_scaling": null,
  "rope_theta": 10000.0,
  "torch_dtype": "bfloat16",
  "transformers_version": "4.38.1",
  "use_cache": true,
  "vocab_size": 256000
}
```
2. Quantize the model via the official example quantization script to int4_awq & bf16, so that it ends in following configuration:
```
{
    "producer": {
        "name": "ammo",
        "version": "0.7.3"
    },
    "architecture": "GemmaForCausalLM",
    "dtype": "bfloat16",
    "num_hidden_layers": 28,
    "model_type": "gemma",
    "num_attention_heads": 16,
    "num_key_value_heads": 16,
    "hidden_size": 3072,
    "norm_epsilon": 1e-06,
    "vocab_size": 256000,
    "max_position_embeddings": 8192,
    "hidden_act": "gelu",
    "use_parallel_embedding": true,
    "embedding_sharding_dim": 0,
    "quantization": {
        "quant_algo": "W4A16_AWQ",
        "kv_cache_quant_algo": null,
        "group_size": 128,
        "has_zero_point": false,
        "pre_quant_scale": true,
        "exclude_modules": [
            "lm_head"
        ]
    },
    "mapping": {
        "world_size": 1,
        "tp_size": 1,
        "pp_size": 1
    },
    "head_size": 256,
    "intermediate_size": 24576,
    "position_embedding_type": "rope_gpt_neox"
}
``` 
3. Try to convert the model with trtllm-build `trtllm-build --checkpoint_dir ./gemma-quantized-awq/ --gemm_plugin bfloat16 --gpt_attention_plugin bfloat16 --max_batch_size 8 --max_num_tokens 4096 --max_output_len 140 --output_dir ./exported`

### Expected behavior

The model converts to TensorRT format correctly

### actual behavior

It is not possible to convert the nvidia-ammo quantized model via trtllm-build, and it gives the following error regarding fp16 precision being set for a layer or layer output but it not being configured:
```
[02/29/2024-20:41:18] [TRT] [W] IElementWiseLayer with inputs GemmaForCausalLM/transformer/layers/27/ELEMENTWISE_SUM_1_output_0 and GemmaForCausalLM/transformer/ln_f/SHUFFLE_0_output_0: first input has type BFloat16 but second input has type Float.
[02/29/2024-20:41:18] [TRT] [W] IElementWiseLayer with inputs GemmaForCausalLM/transformer/ln_f/REDUCE_AVG_0_output_0 and GemmaForCausalLM/transformer/ln_f/SHUFFLE_1_output_0: first input has type BFloat16 but second input has type Float.
[02/29/2024-20:41:18] [TRT-LLM] [I] Build TensorRT engine Unnamed Network 0
[02/29/2024-20:41:18] [TRT] [W] Unused Input: position_ids
[02/29/2024-20:41:18] [TRT] [E] 4: [network.cpp::validate::3516] Error Code 4: Internal Error (fp16 precision has been set for a layer or layer output, but fp16 is not configured in the builder)
[02/29/2024-20:41:18] [TRT-LLM] [E] Engine building failed, please check the error log.
[02/29/2024-20:41:20] [TRT-LLM] [I] Serializing engine to ./lilac_final_exported/rank0.engine...
```

### additional notes

I believe it might be related to how the config is initialized within the main file in tensorrt-llm

**Comment by Tracin** [comment]
How about add `--strongly_typed` for trtllm-build

**Comment by faust58** [comment]
> How about add `--strongly_typed` for trtllm-build

Hi, I had a similar warning 
[TRT] [W] A shape layer can only run in INT32 precision 
[TRT] [W] IElementWiseLayer with inputs LLaMAForCausalLM/vocab_embedding/GATHER_0_output_0 and LLaMAForCausalLM/layers/0/input_layernorm/SHUFFLE_0_output_0: first input has type Half but second input has type Float.
and the flag  --strongly_typed  fixed it, thank you so much)

**Comment by Macsim2** [comment]
Hi I'm having a same error message while converting onnx to plan model with precision int8.
anyone who resolved a issue or have some hints..?

**Comment by thangphan0168** [comment]
I have the same problem when building the engine for quantized Llama 3 70B with `tensorrt-llm==0.8.0`.
If I add `--strongly_typed` it will cause a different error:
`LLaMAForCausalLM/transformer/layers/0/attention/qkv/PLUGIN_V2_WeightOnlyGroupwiseQuantMatmul_0: could not find any supported formats consistent with input/output data types`

**Comment by hello-11** [comment]
@giancarlo-metitieri @scinerd68 Do you still have the question? If not, we will close it soon.
