### ISSUE TITLE
how to enable inflight batching for new trt-build?

### ISSUE THREAD

**Issue by phind-justin** [NVIDIA/TensorRT-LLM#1203]
### System Info

.

### Who can help?

@juney-nvidia 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

.

### Expected behavior

.

### actual behavior

.

### additional notes
0.8.0
previously there were options for the following in build.py
i've been able to translate most of the build options to the new system but i can't seem to figure out the following options:

```
        --use_parallel_embedding \
        --use_inflight_batching \
        --rotary_base 1000000 \
        --rotary_scaling dynamic 2.0 \
```

is it somehow in the build config or plugin config files passed in? those seem like just file versions of the params.

**Comment by phind-justin** [comment]
i understand inflight batching is part of gpt attention plugin which i have enabled - does it now do it automatically?

**Comment by QiJune** [comment]
Yes, to use inflight batching, you need to enable `gpt_attention_plugin`, `paged_kv_cache` and `remove_input_padding`
