### ISSUE TITLE
[Feature request] Chunked context support FP8. 

### ISSUE THREAD

**Issue by kimbaol** [NVIDIA/TensorRT-LLM#1204]
Chunked context is a great feature for GPU memory capacity bound scenario, by enable this feature, I can increase batch_size without worrying about (batch * avg_prefill_seq) may cause oom. 

However, chunked context required enabling 'paged_context_fmha', and currently FP8 is not compatible with paged_context_fmha.  https://github.com/NVIDIA/TensorRT-LLM/issues/1169#issuecomment-1970753421
```[tasklist]
### Tasks
```

**Comment by Shixiaowei02** [comment]
Yes, we do not support fp8 currently, but we will support it in the future. Thanks!

**Comment by njaramish** [comment]
@Shixiaowei02 Is this now supported? I'm reading the documentation here: https://github.com/NVIDIA/TensorRT-LLM/blob/a96cccafcf6365c128f004f779160951f8c0801c/docs/source/advanced/gpt-attention.md?plain=1#L67

**Comment by nv-guomingz** [comment]
Close it since this feature had been supported yet.
