### ISSUE TITLE
In this line 'hidden_size' is undefined

### ISSUE THREAD

**Issue by Coder-HHN** [NVIDIA/TensorRT-LLM#1205]
https://github.com/NVIDIA/TensorRT-LLM/blob/b7c309d1c9baa9c030680988cb73e461f6253b98/examples/multimodal/run.py#L309

**Comment by amukkara** [comment]
@Coder-HHN 
Thanks for pointing this out. This [definition](https://github.com/NVIDIA/TensorRT-LLM/blob/b7c309d1c9baa9c030680988cb73e461f6253b98/examples/multimodal/run.py#L301) should be before if else block.

**Comment by Coder-HHN** [comment]
你好，来信已收到，将尽快回复。谢谢。

**Comment by nv-guomingz** [comment]
Hi @Coder-HHN ,please reopen this ticket if needed.

**Comment by Coder-HHN** [comment]
你好，来信已收到，将尽快回复。谢谢。
