### ISSUE TITLE
When will support qwen1.5

### ISSUE THREAD

**Issue by mogoxx** [NVIDIA/TensorRT-LLM#1208]
python build.py --hf_model_dir /app/model/Qwen1.5-14B-Chat \
                --dtype float16 \
                --remove_input_padding \
                --use_gemm_plugin float16 \
                --use_gpt_attention_plugin float16 \
                --use_inflight_batching \
                --max_batch_size 2 \
                --max_input_len 2048 \
                --max_output_len 2048 \
                --output_dir /app/model/trt_engines/fp16/1-gpu

Traceback (most recent call last):
  File "/app/tensorrt_llm/examples/qwen/build.py", line 609, in <module>
    args = parse_arguments()
  File "/app/tensorrt_llm/examples/qwen/build.py", line 356, in parse_arguments
    hf_config = AutoConfig.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py", line 1039, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py", line 734, in __getitem__
    raise KeyError(key)
KeyError: 'qwen2'

**Comment by whk6688** [comment]
+1

**Comment by whk6688** [comment]
AttributeError: 'Qwen2Config' object has no attribute 'layer_norm_epsilon'

**Comment by ArlanCooper** [comment]
+1, waiting for

**Comment by litaotju** [comment]
@mogoxx 
I think the crashing stack
```
File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py", line 1039, in from_pretrained
config_class = CONFIG_MAPPING[config_dict["model_type"]]
File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py", line 734, in getitem
raise KeyError(key)
```
is from the transformers lib. Could you try to find out if the latest transformers lib support Qwen2?

**Comment by pfk-beta** [comment]
@litaotju Stactrace ends in transformers, but begins in convert. So problem might be in both places. In my case `transformers==4.39.1` and `TensorRT-LLM version: 0.9.0.dev2024031900` gives me the same error:
```Traceback (most recent call last):
  File "/workspace/TensorRT-LLM/examples/qwen/convert_checkpoint.py", line 1421, in <module>
    main()
  File "/workspace/TensorRT-LLM/examples/qwen/convert_checkpoint.py", line 1216, in main
    args.rms_norm_eps = hf_config.layer_norm_epsilon
  File "/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py", line 263, in __getattribute__
    return super().__getattribute__(key)
AttributeError: 'Qwen2Config' object has no attribute 'layer_norm_epsilon'
```

**Comment by bluejadezhou** [comment]
+1

**Comment by shiqingzhangCSU** [comment]
https://github.com/Tlntin/Qwen-TensorRT-LLM It seems implement qwen2。

**Comment by Franc-Z** [comment]
For TRTLLM-0.9.0, you can refer to https://github.com/Franc-Z/QWen1.5_TensorRT-LLM

**Comment by bao21987** [comment]
@Franc-Z your repo is not public accessible

**Comment by pfk-beta** [comment]
@bao21987 repo was public yesterday...

**Comment by Franc-Z** [comment]
@bao21987 Confirm, and you can access.

**Comment by ArlanCooper** [comment]
> @bao21987 Confirm, and you can access.

can you give me the access to visit it? thanks

**Comment by deutschthomas** [comment]
> For TRTLLM-0.9.0, you can refer to https://github.com/Franc-Z/QWen1.5_TensorRT-LLM

I also need the access

**Comment by Franc-Z** [comment]
It's reopen now @pfk-beta @ArlanCooper @deutschthomas

**Comment by zhangfuwen** [comment]
> https://github.com/Tlntin/Qwen-TensorRT-LLM

I tried this, the same error happens.

**Comment by Liu-Da** [comment]
> @litaotju Stactrace ends in transformers, but begins in convert. So problem might be in both places. In my case `transformers==4.39.1` and `TensorRT-LLM version: 0.9.0.dev2024031900` gives me the same error:
> 
> ```
>   File "/workspace/TensorRT-LLM/examples/qwen/convert_checkpoint.py", line 1421, in <module>
>     main()
>   File "/workspace/TensorRT-LLM/examples/qwen/convert_checkpoint.py", line 1216, in main
>     args.rms_norm_eps = hf_config.layer_norm_epsilon
>   File "/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py", line 263, in __getattribute__
>     return super().__getattribute__(key)
> AttributeError: 'Qwen2Config' object has no attribute 'layer_norm_epsilon'
> ```

+1

**Comment by riverind** [comment]
> https://github.com/Tlntin/Qwen-TensorRT-LLM It seems implement qwen2。

<img width="699" alt="截屏2024-06-13 11 21 48" src="https://github.com/NVIDIA/TensorRT-LLM/assets/122635377/877ab394-ed8f-4049-925d-c7b85882495a">


from the document, it seems actually qwen1.5
ref, https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/qwen/README.md

**Comment by effective-qdd** [comment]
TensorRT-LLM 0.10.0 supports qwen2 and I have tested qwen2-7b with example/qwen (convert checkpoint and build engine)
ref https://nvidia.github.io/TensorRT-LLM/release-notes.html#id4
![image](https://github.com/user-attachments/assets/c173df0c-0f97-47f6-9437-a81f1caf1935)

**Comment by nv-guomingz** [comment]
close this ticket since qwen 1.5 had been supported yet.
