### ISSUE TITLE
"output shape can not be computed" with smoothquant

### ISSUE THREAD

**Issue by chenho74** [NVIDIA/TensorRT-LLM#1211]
### System Info

A100 80GB

### Who can help?

@Tracin 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

__version__ = "0.9.0.dev2024020600"
TRT_VER="9.2.0.5"
CUDA_VER="12.3"
CUDNN_VER="8.9.4.25-1+cuda12.2"
NCCL_VER="2.19.3-1+cuda12.3"
CUBLAS_VER="12.3.4.1-1"

### Expected behavior

build sucessfully

### actual behavior

We ran into a "shape cannot be computed" error when building a custom model with smoothquant.
[graphShapeAnalyzer.cpp::needTypeAndDimensions::2221] Error Code 4: Internal Error (GPTLMHeadModel/layers/0/attention/dense/PLUGIN_V2_SmoothQuantGemm_0: output shape can not be computed
Any idea how we go about debugging this? What does this error message mean? Thanks.

### additional notes

Any idea how we go about debugging this? What does this error message mean? Thanks.

**Comment by Tracin** [comment]
Could you show your commands?

**Comment by chenho74** [comment]
Actually the root error is one line above:
[03/05/2024-15:35:38] [TRT] [E] 4: [graphShapeAnalyzer.cpp::dispatchComputeOutputExtents::1182] Error Code 4: Miscellaneous ((Unnamed Layer* 96) [Concatenation]: error while computing output extent)

Could you provide some guide on how to interpret this error? We are using the [`concat` operator provided](https://github.com/NVIDIA/TensorRT-LLM/blob/main/tensorrt_llm/functional.py#L2007) after our custom normalization plugin.
