### ISSUE TITLE
can rotary embeddings be easily changed as a config param post-build? or is a build required?

### ISSUE THREAD

**Issue by phind-justin** [NVIDIA/TensorRT-LLM#1214]
### System Info

.

### Who can help?

@juney-nvidia @byshiue @Tracin 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

.

### Expected behavior

.

### actual behavior

.

### additional notes

i quantized a llama model using quantization/quantize.py but there were no options for rotary embeddings in either build.py or quantize.py. 
It only seems like rotary embeddings are available in an option to convert.py in llama
what's the best way to set rotary embeddings in a quanitzed llama then?
should i manually modify the config file to include them pre-build or can that also just be set manually post-build?

**Comment by Tracin** [comment]
Could you please try modify that in config file before quantize?

**Comment by nv-guomingz** [comment]
Hi @phind-justin do u still have further issue or question now? If not, we'll close it soon.
