### ISSUE TITLE
Run.py in Mixtral example is missing.

### ISSUE THREAD

**Issue by derange-alembic** [NVIDIA/TensorRT-LLM#1217]
### System Info

In the example of Mixtral a [run.py](https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/mixtral/examples/run.py) is used to demonstrate the engine execution. But it's now 404. I guess it should be linked to [this](https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/run.py)?

### Who can help?

@juney-nvidia 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Please see the [example of Mixtral](https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/mixtral).

### Expected behavior

The link to run.py should work.

### actual behavior

It is now 404.

### additional notes

None.

**Comment by byshiue** [comment]
Same issue to https://github.com/NVIDIA/TensorRT-LLM/issues/1181. Close this one.
