### ISSUE TITLE
If i want to add a new module such as alltoall or self-designed module. How to do that？ can you give some tips?

### ISSUE THREAD

**Issue by Eutenacity** [NVIDIA/TensorRT-LLM#1218]
If i want to add a new module such as alltoall or self-designed module. How to do that？ can you give some tips?

**Comment by QiJune** [comment]
If it's a pure Python module, you could add it directly to the current Python codes.

If it's a C++ module, you need to make it as a TRT plugin first, then, expose it to Python. For example, here is the steps to add a NCCL `send` function to TRT-LLM:

1. develop a NCCL send plugin: https://github.com/NVIDIA/TensorRT-LLM/tree/main/cpp/tensorrt_llm/plugins/ncclPlugin
1. expose it as a send function: https://github.com/NVIDIA/TensorRT-LLM/blob/main/tensorrt_llm/functional.py#L3273

**Comment by Eutenacity** [comment]
thanks, i will have a try

**Comment by nv-guomingz** [comment]
Hi @Eutenacity do u still have further issue or question now? If not, we'll close it soon.
