### ISSUE TITLE
How to add Medusa decoding to server?

### ISSUE THREAD

**Issue by nivibilla** [NVIDIA/TensorRT-LLM#1219]
Hi, 

So i managed to build with Medusa, but the server example doesn't have the options needed to enable it.

**Comment by dongxuy04** [comment]
Hi nivibilla, do you mean the server demo `server.py` under `examples/server` in v0.8 or `fastapi_server.py` under `examples/apps` of current main by saying `server example`? If so, unfortunately, I am afraid it is just a server demo and may not adding more feature support.

**Comment by nv-guomingz** [comment]
Hi @nivibilla do u still have further issue or question now? If not, we'll close it soon.
