### ISSUE TITLE
How to init 2 models on 2 gpu_ids?

### ISSUE THREAD

**Issue by littletomatodonkey** [NVIDIA/TensorRT-LLM#1223]
Hi, could you please tell me how to init 2 different models on 2 gpu_ids?

I use the following command, but the 2 models are also inited on `cuda:0`

```py
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
# init using runner_cls.from_dir
model1 = create_llm(xxx1)
os.environ["CUDA_VISIBLE_DEVICES"] = "1"
model1 = create_llm(xxx2)
```

**Comment by QiJune** [comment]
Could you please try with `torch.cuda.set_device`?

```
torch.cuda.set_device(0)
# init using runner_cls.from_dir
model1 = create_llm(xxx1)
torch.cuda.set_device(1)
model1 = create_llm(xxx2)
```

**Comment by littletomatodonkey** [comment]
Hi, thanks for you reply, i tried it but it did not work. The 2 models are both init on "cuda:0".

In trt-llm, it will set device by local_rank, so i think it's why it did not work, but i do not know how to fix the problem without fixing the trt-llm cuda device setting code.

**Comment by wsjeon** [comment]
@littletomatodonkey Do you know how to resolve this issue?

**Comment by nv-guomingz** [comment]
Hi @littletomatodonkey do u still have further issue or question now? If not, we'll close it soon.
