### ISSUE TITLE
[feature request] consider integrate the QUICK kernel for AWQ quantization

### ISSUE THREAD

**Issue by shiqingzhangCSU** [NVIDIA/TensorRT-LLM#1225]
QUICK: [https://github.com/SqueezeBits/QUICK/tree/main](https://github.com/SqueezeBits/QUICK/tree/main)
It claims provide bertter performance for awq int4 quant。

**Comment by juney-nvidia** [comment]
@shiqingzhangCSU 
Thanks for sharing the paper. We also noticed the work before. 

There is already INT4 AWQ support in current TRT-LLM, including the corresponding kernel optimizations. 

Is there any specific reason for you to consider QUICK?

Thanks
June

**Comment by shiqingzhangCSU** [comment]
@juney-nvidia Thanks for your reply. There is no special reason, just considering that his optimization should be relatively general and may be able to improve the performance of INT4 AWQ (TRT-LLM). Perhaps these optimizations have already been done in TRT-LLM(I haven't looked very carefully at the source code of INT4 AWQ). 
By the way，in addition to the optimization of the inverse quantization algorithm in INT4 AWQ, does the matrix calculation after inverse quantization directly use cutlass optimization?

**Comment by Barry-Delaney** [comment]
@shiqingzhangCSU Thanks for the information. As for AWQ related GEMM inside TRT-LLM, we have customized CUDA kernels and CUTLASS kernels for different problem sizes respectively, and de-quantizing operations are already fused into these GEMM kernels for better performance.

**Comment by shiqingzhangCSU** [comment]
Thanks for your reply. @Barry-Delaney
