### ISSUE TITLE
TensorRT-LLM will support VIT?

### ISSUE THREAD

**Issue by Hukongtao** [NVIDIA/TensorRT-LLM#1226]

**Comment by zmy1116** [comment]
Isn't there any specific reason VIT can't be compiled in normal TensorRT?

**Comment by nan2088** [comment]
> Isn't there any specific reason VIT can't be compiled in normal TensorRT?

Hi, does smoothquant achieve higher accuracy than the built-in tensorrt int8 quantization? And how can we enable ViT to use smoothquant solely through TensorRT?

**Comment by KyleNewman97** [comment]
Not sure if this helps. But I re-implemented ViT with easy TensorRT export https://github.com/KyleNewman97/ViT-TensorRT.
