### ISSUE TITLE
Need help on how to get context logits on v0.6

### ISSUE THREAD

**Issue by AbhinavDutta** [NVIDIA/TensorRT-LLM#1228]
Hey, I need to get the values of the context logits. I have tried the three following things that seemed intuitive, but none of them worked.

1.Edit the config.json file to make :
```
"builder_config": {
    "gather_all_token_logits": true,
...
```

2. Set gather_all_token_logits = True (instead of gather_all_token_logits = builder_config.get('gather_all_token_logits',False) in model_runner.py) 

Both of them gave the following error 

```
RuntimeError: Tensor names in engine are not the same as expected, to use this GenerationSession, you need to use GPTLMHeadModel.prepare_inputs to create TRT Network inputs.
```

Can someone let me know, what I can do to get context logits ? Thanks!

**Comment by byshiue** [comment]
Could you try on latest v0.8?

**Comment by nv-guomingz** [comment]
Hi @AbhinavDutta do u still have further issue or question now? If not, we'll close it soon.
