### ISSUE TITLE
Various CUDA errors when pp_size > 1.

### ISSUE THREAD

**Issue by jybbjybb** [NVIDIA/TensorRT-LLM#1232]
First of all, when pp_size = 1, everything is good with tp_size = 1,2,4,8. 
My test on pipeline parallelism (pp_size > 1) always failed with different error in the last few rows in this post.

First convert: 
`
python convert_checkpoint.py --model_dir /mnt/LLM_checkpoints/Llama-2-7b-chat-hf/ --output_dir ./tllm_checkpoint_2gpu_tp1_pp2 --dtype float16 --tp_size 1  --pp_size 2
`
Output:
```
[TensorRT-LLM] TensorRT-LLM version: 0.9.0.dev2024022700
0.9.0.dev2024022700
Loading checkpoint shards: 100%
Weights loaded. Total time: 00:00:05
Weights loaded. Total time: 00:00:05
Total time of converting checkpoints: 00:00:45
```

Then build:
`
trtllm-build --checkpoint_dir ./tllm_checkpoint_2gpu_tp1_pp2/ --output_dir ./tmp/llama/7B/trt_engines/fp16/2-gpu/tp1_pp2 --gemm_plugin float16
`
Output is a lot of information, but it seems to work at last.
```
[03/04/2024-19:57:07] [TRT-LLM] [I] Engine serialized. Total time: 00:00:02
[03/04/2024-19:57:07] [TRT-LLM] [I] Total time of building all engines: 00:01:24

```
**(I think something is wrong here. There are warnings about layer input being Half or Float. But, only 0-15 Layer has the warning. LLaMA 7b should have 32 layers, the rest 16 layers are missing the warning.)**

Then run:
`mpirun -n 4 python3 ../run.py --max_output_len=50 --tokenizer_dir /mnt/LLM_checkpoints/Llama-2-7b-chat-hf/ --engine_dir=./tmp/llama/7B/trt_engines/fp16/4-gpu/tp1_pp4`

Then got the error
```
[TensorRT-LLM][INFO] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +6426, now: CPU 0, GPU 6426 (MiB)
[TensorRT-LLM][INFO] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +6426, now: CPU 0, GPU 6426 (MiB)
[TensorRT-LLM][INFO] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 6857, GPU 7139 (MiB)
[TensorRT-LLM][INFO] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 6857, GPU 7139 (MiB)
[TensorRT-LLM][INFO] [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 6857, GPU 7147 (MiB)
[TensorRT-LLM][WARNING] TensorRT was linked against cuDNN 8.9.6 but loaded cuDNN 8.9.2
[TensorRT-LLM][INFO] [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 6857, GPU 7147 (MiB)
[TensorRT-LLM][WARNING] TensorRT was linked against cuDNN 8.9.6 but loaded cuDNN 8.9.2
[TensorRT-LLM][INFO] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 6426 (MiB)
[TensorRT-LLM][INFO] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 6426 (MiB)
[TensorRT-LLM][INFO] Max tokens in paged KV cache: 266112. Allocating 69759664128 bytes.
[TensorRT-LLM][INFO] Max KV cache pages per sequence: 1
[TensorRT-LLM][INFO] Max tokens in paged KV cache: 266112. Allocating 69759664128 bytes.
[TensorRT-LLM][INFO] Max KV cache pages per sequence: 1
terminate called after throwing an instance of 'tensorrt_llm::common::TllmException'
  what():  [TensorRT-LLM][ERROR] CUDA runtime error in cublasLtMatmul(getCublasLtHandle(), mOperationDesc, alpha, A, mADesc, B, mBDesc, beta, C, mCDesc, C, mCDesc, (hasAlgo ? (&a
lgo) : NULL), mCublasWorkspace, workspaceSize, mStream): CUBLAS_STATUS_EXECUTION_FAILED (/home/jenkins/agent/workspace/LLM/main/L0_MergeRequest/tensorrt_llm/cpp/tensorrt_llm/comm
on/cublasMMWrapper.cpp:140)
```
And another run I got different types of errors, one of them was 
`tensorrt_llm::common::tllmexception' what(): [tensorrt-llm][error] cuda runtime error in ::cudaeventdestroy(event): an illegal memory access was encountered `

and another run I got another error: 
`Failed, NCCL error /home/jenkins/agent/workspace/LLM/main/L0_MergeRequest/tensorrt_llm/cpp/tensorrt_llm/plugins/ncclPlugin/sendPlugin.cpp:96 'unhandled cuda error (run with NCCL_DEBUG=INFO for details)'`

This is so weird...

**Comment by nv-guomingz** [comment]
Hi @jybbjybb Could u please try the latest code base to see if the issue still exists or not?
