### ISSUE TITLE
Support for Jais Models

### ISSUE THREAD

**Issue by grandiose-pizza** [NVIDIA/TensorRT-LLM#1237]
Please add [Jais](https://huggingface.co/core42) models to tensorrt-LLM

- [core42/jais-13b](https://huggingface.co/core42/jais-13b)
- [core42/jais-13b-chat](https://huggingface.co/core42/jais-13b-chat)
-  [core42/jais-30b-v3](https://huggingface.co/core42/jais-30b-v3)
-  [core42/jais-30b-chat-v3](https://huggingface.co/core42/jais-30b-chat-v3)

Jais models are pretrained and fine-tuned over a curated Arabic and English text/ prompt-response pairs datasets respectively. It is trained from scratch by Core42 in partnership with MBZUAI and Cerebras systems on their Condor Galaxy. The model architecture is based on transformer-based decoder-only (GPT-3) architecture and uses SwiGLU non-linearity. It implements ALiBi position embeddings, enabling the model to extrapolate to long sequence lengths, providing improved context handling and model precision.

The research can be studied here: https://arxiv.org/pdf/2308.16149.pdf

Metrics can be found here: https://huggingface.co/core42/jais-30b-chat-v3

These are SoTA Arabic-English bilingual models. The playground can be accessed at https://arabic-gpt.ai/

Here is the corresponding vLLM support recently made
https://github.com/vllm-project/vllm/pull/3183

Thanks in advance.

**Comment by 5cat** [comment]
`Jais` has been added as an example https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/jais
