### ISSUE TITLE
[FEA] Support Roberta model

### ISSUE THREAD

**Issue by esnvidia** [NVIDIA/TensorRT-LLM#124]
As title suggests, support the HF Roberta model with the pretrained weights here: https://huggingface.co/roberta-large

**Comment by jdemouth-nvidia** [comment]
Hi @esnvidia ,

Thanks for the suggestion. We will add it to the list of feature requests. Not sure if/when we will have time to implement it but we will keep it in mind. 

Thanks,
Julien

**Comment by AdamzNV** [comment]
As more and more new models enter the market, we have prepared comprehensive instructions for TRT-LLM developers on adapting to new models of interest. We encourage our community developers to expand the range of supported models, fostering an open ecosystem with rapid iterations.

Please try following these [instructions ](https://github.com/NVIDIA/TensorRT-LLM/tree/main/docs/source/architecture)and let us know if you encounter any issues during the adaptation process. We greatly appreciate your dedication.

**Comment by nv-guomingz** [comment]
This model had been supported in Tensorrt-llm https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/bert/build.py#L101


please feel free to reopen this ticket if needed.
