### ISSUE TITLE
How to build Qwen-72B-Chat-Int4 with tp = 2?

### ISSUE THREAD

**Issue by anxietymonger** [NVIDIA/TensorRT-LLM#1249]
For Qwen, in the [int4-gptq section of examples](https://github.com/NVIDIA/TensorRT-LLM/tree/v0.8.0/examples/qwen#int4-gptq), it uses `tp = 1`, but when I configure `tp = 2` or more, it raises an assertation error:
```
AssertationError: The current implementation of GQA requires the number of K/V heads to match the number of GPUs. This limitation will be removed in a future version.
```

However, if I set `n_kv_head = 2` (default of which is 32) corresponding to my number of GPUs, together with the configuration of `--per_group`, I presume that the quantization algorithm is unwillingly changed as a consequence. And the result of `run.py` did show that the compiled model could not inference properly (returned gibberish results). 

So my question is, how should I configure the building process correctly to make it work for multiple GPUs leveraging int4-gptq?

**Comment by byshiue** [comment]
Please follow the issue template to provide the details of your environments, the reproduced steps and the issue you encounter. Thank you for cooperation.

**Comment by anxietymonger** [comment]
@byshiue I don't think it's a problem specific to certain environments. And to reproduce, just follow the docs provided in [Int4-gptq section](https://github.com/NVIDIA/TensorRT-LLM/tree/v0.8.0/examples/qwen#int4-gptq) of `examples/qwen`.

**Comment by liyunhan** [comment]
> @byshiue I don't think it's a problem specific to certain environments. And to reproduce, just follow the docs provided in [Int4-gptq section](https://github.com/NVIDIA/TensorRT-LLM/tree/v0.8.0/examples/qwen#int4-gptq) of `examples/qwen`.

Do you fix the problem?

**Comment by liyunhan** [comment]
> @byshiue I don't think it's a problem specific to certain environments. And to reproduce, just follow the docs provided in [Int4-gptq section](https://github.com/NVIDIA/TensorRT-LLM/tree/v0.8.0/examples/qwen#int4-gptq) of `examples/qwen`.

In fact when i use tp=1, I got the same error

**Comment by liyunhan** [comment]
> @byshiue I don't think it's a problem specific to certain environments. And to reproduce, just follow the docs provided in [Int4-gptq section](https://github.com/NVIDIA/TensorRT-LLM/tree/v0.8.0/examples/qwen#int4-gptq) of `examples/qwen`.

You can try this "https://github.com/Tlntin/Qwen-TensorRT-LLM/issues/94", change "n_kv_head" to "None", then you can use tp_size 2 and world_size 2. this worked for me

**Comment by anxietymonger** [comment]
@liyunhan Your solution worked for me, thanks! But there's still a minor issue that when I set n_kv_head to None, I also have to delete the `num_kv_heads` line in the config.json in the engine dir after building, otherwise it raises an error complaining about the null type when executing run.py

**Comment by liyunhan** [comment]
@anxietymonger In fact,I encountered some other issues during the build process that haven't been resolved yet： `[backendBuilderConfig.cpp::validateBasicAssumptions::28] Error Code 9: Internal Error (Builder was created on device different than current device.)`

 You might want to ask your question at that link; perhaps he will tell you why.

**Comment by thomas-hiddenpeak** [comment]
The 0.9.0-dev version does not have the world_size parameter anymore, and after configuring tp_size, it is no different from not configuring it.

**Comment by nv-guomingz** [comment]
Hi @anxietymonger do u still have further issue or question now? If not, we'll close it soon.
