### ISSUE TITLE
Missing return statement

### ISSUE THREAD

**Issue by Rainingcity** [NVIDIA/TensorRT-LLM#125]
Hi team, this function is missing a `return True` at the end. Luckily it's not used anywhere yet. 
https://github.com/NVIDIA/TensorRT-LLM/blob/bd78e7840484d81acd06417ab6fdc2232b8a4874/tensorrt_llm/layers/attention.py#L135-L140

**Comment by byshiue** [comment]
Thank you for the remind. We will fix it soon.

**Comment by byshiue** [comment]
This issue is fixed by this MR https://github.com/NVIDIA/TensorRT-LLM/pull/148, you can try on latest main branch. Close this bug. Feel free to reopen if needed.
