### ISSUE TITLE
missing llama.convert module

### ISSUE THREAD

**Issue by gaetanboulard-lc** [NVIDIA/TensorRT-LLM#1252]
### System Info

python3.10
tensorrt-llm 0.8.0

### Who can help?

@byshiue 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

When trying to convert a llama2 model following the examples [here](https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/llama), I get this error:
```
ModuleNotFoundError: No module named 'tensorrt_llm.models.llama.convert'
```

### Expected behavior

module should exist

### actual behavior

module missing from the site-packages

### additional notes

tensorrt-llm freshly installed via pip: `pip3 install tensorrt_llm -U --extra-index-url https://pypi.nvidia.com`

**Comment by jeageun** [comment]
I also suffered this problem, but I figured out I need to launch the code in
`/app/tensorrt_llm/examples/llama` directory, not in other directory...
If you are using docker, try on this directory.

**Comment by gaetanboulard-lc** [comment]
Interesting. I tried that but it didn't work

I just copied `TensorRT-LLM/tensorrt_llm/models/llama/convert.py`  taken from the source code, to the packages installed by pip in `lib/python3.10/site-packages/tensorrt_llm/models/llama/`. Worked well.

**Comment by byshiue** [comment]
@gaetanboulard-lc If you don't find `convert.py` in `lib/python3.10/site-packages/tensorrt_llm/models/llama/`, it might be an issue of version mismatch. You could try to build and install the tensorrt_llm from source codes by following this [guide](https://github.com/NVIDIA/TensorRT-LLM/blob/v0.8.0/docs/source/build_from_source.md) to fix it.

**Comment by robmsmt** [comment]
I also had this issue. Will see if the suggestion to build from source work

**Comment by ghost** [comment]
I tried to copy the files over to 
```docker
COPY TensorRT-LLM/tensorrt_llm/models/llama/convert.py /usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/convert.py
```
, still didn't work.

**Comment by QiJune** [comment]
Please install the requirements.txt in the llama example first:

```python
pip install -r examples/llama/requirements.txt
```

**Comment by injet-zhou** [comment]
> Please install the requirements.txt in the llama example first:
> 
> ```python
> pip install -r examples/llama/requirements.txt
> ```

it works for me, thanks

**Comment by gaetanboulard-lc** [comment]
> Please install the requirements.txt in the llama example first:
> 
> ```python
> pip install -r examples/llama/requirements.txt
> ```

This installs a specific version of tensorrt-llm, not yet released. I assume this will come in the main release later.
Anyways, it works. Thank you.
