### ISSUE TITLE
Streaming not possible via run.py despite the option existing

### ISSUE THREAD

**Issue by iibw** [NVIDIA/TensorRT-LLM#1253]
### System Info

- tensorrt_llm=='0.9.0.dev2024030500'

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Use `examples/run.py` with the `--streaming` option.

I think any model will trigger this, but if not, run a Llama-based model.

### Expected behavior

Model output streamed to console.

### actual behavior

```
Traceback (most recent call last):
  File "/home/user/tensorrtllm_backend/tensorrt_llm/examples/llama/../run.py", line 574, in <module>
    main(args)
  File "/home/user/tensorrtllm_backend/tensorrt_llm/examples/llama/../run.py", line 418, in main
    outputs = runner.generate(
  File "/home/user/.conda/envs/trtllm/lib/python3.10/site-packages/tensorrt_llm/runtime/model_runner_cpp.py", line 293, in generate
    raise RuntimeError("Streaming is not supported in C++ session.")
RuntimeError: Streaming is not supported in C++ session.
```

### additional notes

Maybe I'm missing something obvious, but it appears that the streaming option in `run.py` exists despite streaming support not being implemented. Maybe it would be better to remove the streaming option until it is implemented or to go ahead and implement streaming support via [AsyncLLMEngine](https://github.com/NVIDIA/TensorRT-LLM/issues/711).

**Comment by byshiue** [comment]
Please try adding `--use_py_session` to use python runtime if you want to use streaming on python side.

**Comment by iibw** [comment]
That works for me. I'll close this issue since it has a purpose.
