### ISSUE TITLE
AWQ Quantization fails with other versions of torch

### ISSUE THREAD

**Issue by eycheung** [NVIDIA/TensorRT-LLM#126]
This is more of a feature request:

It seems like unless you use the pre-installed version of torch from `[nvcr.io/nvidia/pytorch:23.08-py3](http://nvcr.io/nvidia/pytorch:23.08-py3)` then there will be import failures running AWQ quantization.

```
from ammo.torch.quantization import cuda_ext
[NeMo W 2023-10-25 16:27:34 nemo_logging:349] /usr/local/lib/python3.10/dist-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
      warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:1                                                                                    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: /usr/local/lib/python3.10/dist-packages/ammo/torch/quantization/cuda_ext.cpython-310-x86_64-linux-gnu.so: undefined symbol:
_ZN3c106detail14torchCheckFailEPKcS2_jRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

**Can we make this more flexible?** I am maintaining my own image, and having to build the specific torch version just for awq quantization seems a bit heavy, and it seems unclear if I'll need to periodically update this version if a new version of ammo is released.

**Potential Ammo Workaround** I believe the legacy quantization functions work with multiple environments, but they only trigger when `ValueError` is raised. Can we also use legacy if `cuda_ext is None` and just log a warning?

**Comment by RalphMao** [comment]
Hi @eycheung , we will soon release an AMMO source wheel which does compilation on the fly

**Comment by eycheung** [comment]
Thank you @RalphMao, that would be amazing! I'll close this out and watch for the update.

**Comment by kevalmorabia97** [comment]
@eycheung we have updated the [tarball link](https://developer.nvidia.com/downloads/assets/cuda/files/nvidia-ammo/nvidia_ammo-0.3.0.tar.gz) to include 4 additional wheels for the 4 python versions that are cuda/cpu independent and does the compilation of some extensions on runtime based on your cuda and torch versions.
 
Wheel name: `nvidia_ammo-0.3.0-cp<python_version>-cp<python_version>-linux_x86_64.whl`

The updated `README.md` in the tarball contains instructions to trigger the compilation after installation. Let us know if you face any more issues.

**Comment by eycheung** [comment]
Thank you @kevalmorabia97 ! I'll try this today and will create an issue if I find anything. But this looks like exactly what I was looking for.

**Comment by eycheung** [comment]
Just confirming that this worked perfectly for me. Thanks again @kevalmorabia97 and @RalphMao !
