### ISSUE TITLE
Accuracy issue when compared with TGI for enc-dec model

### ISSUE THREAD

**Issue by sindhuvahinis** [NVIDIA/TensorRT-LLM#1261]
### System Info

- GPU Nvidia A100
- TensorRT-LLM v0.8.0

### Information

- [X] The official example scripts
- [] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Using this example script https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/enc_dec/run.py without any modification. 

We have been testing a flan-t5-xl model with python backend of TensorRT-LLM. But for some of the input sequences, the output seems to be generating less tokens. But when we host the same model with TGI, the output is as expected. 

I did compiled the model with 2048 max_input_len and max_output_len. Tested it with latest release v0.8.0. 

From the docs, I believe the default is greedy, Do I need to modify any of the parameters? 

### Expected behavior

Expect 900 tokens

### actual behavior

Generated 800 tokens. 

### additional notes

We cannot share the exact model or example because of the confidentiality. But we did compare it with TGI in the same host with 4 gpus.

**Comment by symphonylyh** [comment]
Hi @sindhuvahinis , were you able to retest on latest main or recent 0.10 release branches? There are many changes since March, and we believe such issue has been fixed for a while. With your confirmation, I will close the issue. Thanks!

**Comment by nv-guomingz** [comment]
Hi @sindhuvahinis do u still have further issue or question now? If not, we'll close it soon.

**Comment by sindhuvahinis** [comment]
Let's close it. We dont have that issue anymore.
