### ISSUE TITLE
Inquiry About Customizing Model Parameter Loading Logic

### ISSUE THREAD

**Issue by duanzhaol** [NVIDIA/TensorRT-LLM#1266]
Hello,

I am currently working with the tensorrt-llm library and have a specific need to customize the logic for loading model parameters. Specifically, I wish to load each tensor from a custom source rather than using the default loading mechanism provided by the library. Is such a modification feasible within the current architecture? If so, could you provide some guidance or suggestions on how to implement this?

```[tasklist]
### Tasks
```

**Comment by litaotju** [comment]
@duanzhaol you could directly assign the "Parameter" objects of a  TRT-LM model's different layers to numpy arrays.
