### ISSUE TITLE
Does lora support other llm besides llama? 

### ISSUE THREAD

**Issue by zhaocc1106** [NVIDIA/TensorRT-LLM#1276]
I saw v0.8.0 support lora. But i just found example of llama. Does lora support other llm? Should we adapt it ourself?

**Comment by byshiue** [comment]
Currently, TensorRT-LLM only supports LoRA on GPT and LLaMA.

**Comment by zhaocc1106** [comment]
> Currently, TensorRT-LLM only supports LoRA on GPT and LLaMA.

Any plan for chatglm?

**Comment by zzykira** [comment]
> > Currently, TensorRT-LLM only supports LoRA on GPT and LLaMA.
> 
> Any plan for chatglm?

you can try to merge lora layer to base layer all together, and apply the chatglm conversion. Theoretically, both lora A and lora B are Linear layer, the output of lora is Wa * WbT * x，and the base layer W_base * x + B_base. Therefore, the output is (W_base + Wa * WbT) * x + B_base. You can convert the original W_base to (W_base + Wa * WbT) before applying tensorRT-llm. We tried this way and got similar answer with the model with lora.

**Comment by tongjinle123** [comment]
what about chatglm with multi lora ?

**Comment by tongjinle123** [comment]
any suggestion about customizing the chatglm/model.py to support lora ?

**Comment by byshiue** [comment]
LoRA is optimized and it is a general feature now. Please take a try and feel free to open bug if you encounter any issue.
