### ISSUE TITLE
Deepseek moe support

### ISSUE THREAD

**Issue by akhoroshev** [NVIDIA/TensorRT-LLM#1277]
Hi!

Does trtllm support https://huggingface.co/deepseek-ai/deepseek-moe-16b-base ? Do you have any plans to support?

**Comment by akhoroshev** [comment]
I implemented this arch several times ago in trtllm

https://github.com/NVIDIA/TensorRT-LLM/pull/1758

**Comment by trebladev** [comment]
hi，
Thanks for your implementation that I can run deepseek-moe with trt-llm
But when I try to run it with 2x4090, got a attributeError: ‘PluginNode’ object has no attribute ‘_collect_strategies'/
Have you ever seem this? and do you know the solution?

**Comment by akhoroshev** [comment]
> Have you ever seem this? and do you know the solution?

No, I have not encountered such an error

**Comment by nv-guomingz** [comment]
@akhoroshev please feel free to reopen it since we've supported this model yet.
