### ISSUE TITLE
Support for do_sample

### ISSUE THREAD

**Issue by pawel-polyai** [NVIDIA/TensorRT-LLM#128]
Hi, thanks for the amazing repo! 

Some models generate much better text when the sampling is allowed (like T5). However, the current SamplingConfig doesn't allow for that. Is there any chance of adding this option to the generation?

For example, GenerationConfig when running T5 gives very differents result with do_sample=True compared (with the same top_k, top_p) to running the same setup with SamplingConfig.

**Comment by eval-dev** [comment]
hi, in my understanding when top_k and top_p have valid values and num_beans=1, it is equivalent to do_sample=True in huggingface.

**Comment by byshiue** [comment]
eval-dev's reply is correct. 
Close this bug, please reopen it if needed.
