### ISSUE TITLE
fail to convert llama2 model

### ISSUE THREAD

**Issue by whk6688** [NVIDIA/TensorRT-LLM#1283]
### System Info

4090

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1 git clone https://github.com/qwopqwop200/GPTQ-for-LLaMa.git
2 cd GPTQ-for-LLaMa
3 pip install -r requirements.txt
4 python llama.py ./tmp/llama/7B/ c4 --wbits 4 --true-sequential --groupsize 128 --save_safetensors ./llama-7b-4bit-gs128.safetensors

step 4 error.  
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/17873056/60fcc80d-f4b0-4c43-a594-ae6ce4234a30)

### Expected behavior

be able to run step 4.

### actual behavior

faiure

### additional notes

none

**Comment by whk6688** [comment]
is there another way to do it?

**Comment by whk6688** [comment]
oh, first error is:
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/17873056/094907e7-0efc-4f72-8cfc-2dde65ba1b7f)

**Comment by whk6688** [comment]
it looks like not work by another way to quantize model: (not support int4?)

python convert_checkpoint.py --model_dir /home/wanghaikuan/code/LLaMA-Factory/llama2-hf-lam \
                              --output_dir ./tllm_checkpoint_1gpu_fp16_wq \
                              --dtype float16 \
                              --use_weight_only \
                              --weight_only_precision int4

**Comment by nv-guomingz** [comment]
Hi @whk6688 could u please try our latest code base to see if the issue still exists or not?
