### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorrt_llm.bindings' after pip install uvicorn 

### ISSUE THREAD

**Issue by WuhanMonkey** [NVIDIA/TensorRT-LLM#1288]
### System Info

x86_64
Ubuntu20.04
A100x8
TRT-LLM version v0.9.0

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Follow the guidance in homepage to setup TRT-LLM.
2. Verify by `python3 -c "import tensorrt_llm"` and output the correct version.
3. Follow the instruction on https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/server.  Run `python3 -m examples.server.server <path_to_tllm_engine_dir> <tokenizer_type> &`
4. Complains about `uvicorn` module not found
5. `pip install uvicorn`
6. After installation, running same command to start serving reports the following issue:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/powerop/work/rwq/TensorRT-LLM/tensorrt_llm/__init__.py", line 46, in <module>
    from .hlapi.llm import LLM, ModelConfig
  File "/home/powerop/work/rwq/TensorRT-LLM/tensorrt_llm/hlapi/__init__.py", line 1, in <module>
    from .llm import LLM, ModelConfig
  File "/home/powerop/work/rwq/TensorRT-LLM/tensorrt_llm/hlapi/llm.py", line 18, in <module>
    from ..executor import (GenerationExecutor, GenerationResult,
  File "/home/powerop/work/rwq/TensorRT-LLM/tensorrt_llm/executor.py", line 11, in <module>
    import tensorrt_llm.bindings as tllm
ModuleNotFoundError: No module named 'tensorrt_llm.bindings'
```

### Expected behavior

Expect no import issue

### actual behavior

missing module named

### additional notes

Even after I uninstall the uvicorn, the issue still persist

**Comment by un-certainty** [comment]
The following command also produces the same error. I have followed the step in README. Checkpoint convertion and engine building are smooth. But cannot get `run.py` to work.

```
PYTHONPATH=. python examples/run.py --input_text "what is the second tallest mountain on earth?" --max_output_len=50 --tokenizer_dir=baichuan-inc/Baichuan-13B-Chat --engine_dir /path/to/trt-engines/fp16/1-gpu/
```

**Comment by HamidShojanazeri** [comment]
it seems the following working

follow the readme [here](https://github.com/NVIDIA/TensorRT-LLM/tree/4bb65f216f2f1dbddb022f4fdd8925c2856baa58#installation) and [here](https://github.com/NVIDIA/TensorRT-LLM/tree/4bb65f216f2f1dbddb022f4fdd8925c2856baa58/examples/llama). 
```
python3 server.py --model_dir /TensorRT-LLM/examples/llama/trt_engines/bf16/1-gpu/ --tokenizer_type /TensorRT-LLM/examples/llama/Llama-2-7b-ch
at-hf 

```

**Comment by WuhanMonkey** [comment]
Seems like if you use `apt-get install uvicorn` then no issues, but `pip install uvicorn` (which can be installed as part of the requirements.txt) will cause this issue. Likely a version mismatch.

**Comment by nv-guomingz** [comment]
hi @WuhanMonkey do u still have further issue or question now? If not, we'll close it soon.
