### ISSUE TITLE
Import Error: ModuleNotFoundError: No module named 'tensorrt_llm.lora_manager'

### ISSUE THREAD

**Issue by hademircii** [NVIDIA/TensorRT-LLM#1289]
### System Info

started receiving this error after rebuilding image today - that I believe picked up #1274 . (using `pip3 install tensorrt_llm -U --pre --extra-index-url https://pypi.nvidia.com`). 

```
Traceback (most recent call last):
  File "/TensorRT-LLM/examples/enc_dec/run.py", line 32, in <module>
    from tensorrt_llm.lora_manager import LoraManager
ModuleNotFoundError: No module named 'tensorrt_llm.lora_manager'
```

### Who can help?

[kaiyux](https://github.com/kaiyux)

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

follow the readme here
https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/enc_dec/README.md#run
to run line:
https://github.com/NVIDIA/TensorRT-LLM/blob/4bb65f216f2f1dbddb022f4fdd8925c2856baa58/examples/enc_dec/run.py#L32

### Expected behavior

import sucessfull.

### actual behavior

import fails.

### additional notes

-

**Comment by jagadeesh-k-ti** [comment]
same issue. is there any known workaround?

**Comment by hademircii** [comment]
a simple workaround is to work with a previous commit to main, right before #1274 ..

**Comment by luvwinnie** [comment]
same here. trying this link.

https://console.brev.dev/notebook/streamingllm-tensorrt-llm

**Comment by byshiue** [comment]
Could you share the tensorrt_llm version you use? I try to reproduce but fail. 
```bash
bhsueh@xxx:/tmp/TensorRT-LLM$ python3
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from tensorrt_llm.lora_manager import LoraManager
[TensorRT-LLM] TensorRT-LLM version: 0.9.0.dev2024031200
```

**Comment by luvwinnie** [comment]
I'm using this version.

```
>>> import tensorrt_llm
No protocol specified
[TensorRT-LLM] TensorRT-LLM version: 0.8.0
```

I think I should upgrade to latest and take a try.

**Comment by RankoR** [comment]
I had this issue when was using 0.9.0 version installed from pip over 0.8.0 version of this repo. Updating repo to 0.9.0 fixed it.

**Comment by nv-guomingz** [comment]
Hi @hademircii do u still have further issue or question now? If not, we'll close it soon.
