### ISSUE TITLE
Is there any need to run tuning for better performance?

### ISSUE THREAD

**Issue by sleepwalker2017** [NVIDIA/TensorRT-LLM#129]
On FT, we can do tuning to get better gemm kernels,  is that available on TRT-LLM?

**Comment by jdemouth-nvidia** [comment]
Hi @sleepwalker2017 ,

There's no such manual process with TensorRT-LLM. It's done automatically by TensorRT when building the TensorRT engine (for the kernels generated by TensorRT) or in the plugins that use on CUTLASS. For the plugins that use cuBLAS, it relies on a pre-trained heuristic in the cuBLAS library.

Thanks,
Julien

**Comment by sleepwalker2017** [comment]
> Hi @sleepwalker2017 ,
> 
> There's no such manual process with TensorRT-LLM. It's done automatically by TensorRT when building the TensorRT engine (for the kernels generated by TensorRT) or in the plugins that use on CUTLASS. For the plugins that use cuBLAS, it relies on a pre-trained heuristic in the cuBLAS library.
> 
> Thanks, Julien

Thank you for the explanation.
