### ISSUE TITLE
Is there a plan for FP8 support for MPT models?  It seems that FP8 KV cache is already available。

### ISSUE THREAD

**Issue by moonlightian** [NVIDIA/TensorRT-LLM#1291]
### System Info

None

### Who can help?

@Tracin 
https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/mpt

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

None

### Expected behavior

None

### actual behavior

None

### additional notes

None

**Comment by Tracin** [comment]
Hi I think we already support that
https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/mpt#16-fp8-post-training-quantization-with-ammo
