### ISSUE TITLE
[Feature Request] More realistic benchmark and throughput optimization

### ISSUE THREAD

**Issue by tp-nan** [NVIDIA/TensorRT-LLM#1292]
TensorRT-LLM has better kernel optimization, better model ecosystem support, and more quantization algorithm support compared to other large model inference libraries. However, during use, it is not easy to demonstrate its advantages in throughput scenarios(#73 #1097 #819 #965 #1255). The current benchmark is limited to designated parameters( for instances, batch sizes) that is not very close to reality.

Is it possible to replace the benchmark method with [vLLM's type of benchmark_throughput](https://github.com/vllm-project/vllm/blob/main/benchmarks/benchmark_throughput.py), and improve throughput in this scenario? #632

**Comment by Missmiaom** [comment]
Any updates?
