### ISSUE TITLE
v0.8.0 long text(100k) input, output precision worse(error)

### ISSUE THREAD

**Issue by BasicCoder** [NVIDIA/TensorRT-LLM#1299]
### System Info

- CPU: X86_64
- GPU: 4*NVIDIA A100 80GB PCIe
- TensorRT-LLM: 0.8.0

### Who can help?

@kaiyu @byshiue 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Use TRT-LLM v0.8.0 version.
```python
1. model convert and build
python ./examples/llama/convert_checkpoint.py --model_dir /workspace/70B_chat/70.long/ \
                            --output_dir /workspace/70B_chat/70.long/tllm_checkpoint_4gpu_tp4 \
                            --dtype float16 \
                            --tp_size 4 \
                            --rotary_base 500000 \
                            --rotary_scaling dynamic 4.0 > llama_70b_convert_tp4_v0.8x.log 2>&1

trtllm-build --checkpoint_dir /workspace/70B_chat/70.long/tllm_checkpoint_4gpu_tp4 \
            --output_dir /workspace/70B_chat/70.long/tllm_checkpoint_4gpu_tp4/trt_engines/fp16/4-gpu/ \
            --max_batch_size 4 \
            --max_input_len 100352 \
            --max_output_len 4096 \
            --logits_dtype float32 \
            --gemm_plugin float16 \
            --multi_block_mode enable \
            --context_fmha_fp32_acc enable \
            --use_custom_all_reduce disable \
            --enable_xqa disable \
            > llama_70b_convert_tp4_v0.8x.log 2>&1
2. model inference
mpirun -n 4 --allow-run-as-root python ./examples/run.py \
                        --max_output_len 100 \
                        --log_level info \
                        --input_file ./longtext.txt \
                        --max_input_length 100352 \
                        --tokenizer_dir /workspace/70B_chat/70.long/ \
                        --tokenizer_type llama \
                        --engine_dir /workspace/70B_chat/70.long/tllm_checkpoint_4gpu_tp4/trt_engines/fp16/4-gpu/ >> llama-70b_fp16_4tp_v0.8x.log 2>&1
```
An error occurred in the output result, and the output token idx exceeded the vocabulary size.
```python
output_ids[batch_idx][beam][output_begin:output_end]=tensor([39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423,
        39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423,
        39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423,
        39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423,
        39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423,
        39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423,
        39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423,
        39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423,
        39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423,
        39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423],
       device='cuda:0', dtype=torch.int32)
Traceback (most recent call last):
  File "/workspace/trt-llm/TensorRT-LLM/build/../examples/run.py", line 529, in <module>
    main(args)
  File "/workspace/trt-llm/TensorRT-LLM/build/../examples/run.py", line 455, in main
    print_output(tokenizer,
  File "/workspace/trt-llm/TensorRT-LLM/build/../examples/run.py", line 275, in print_output
    output_text = tokenizer.decode(outputs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 3750, in decode
    return self._decode(
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils.py", line 1001, in _decode
    filtered_tokens = self.convert_ids_to_tokens(token_ids, skip_special_tokens=skip_special_tokens)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils.py", line 982, in convert_ids_to_tokens
    tokens.append(self._convert_id_to_token(index))
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/tokenization_llama.py", line 280, in _convert_id_to_token
    token = self.sp_model.IdToPiece(index)
  File "/usr/local/lib/python3.10/dist-packages/sentencepiece/__init__.py", line 1179, in _batched_func
    return _func(self, arg)
  File "/usr/local/lib/python3.10/dist-packages/sentencepiece/__init__.py", line 1172, in _func
    raise IndexError('piece id is out of range.')
IndexError: piece id is out of range.
```
The length of input text tokens in `./longtext.txt` is less than 32000. When `rotary_scaling` is turned off, that is, `rotary_scaling=None`, the output results of the model are normal.

I adjusted the ntk mode from `dynamic` to `linear`. The model can produce results, but the model performance is poor. Using `rotary_scaling=linear, 4.0` method, the results of v0.8.0 and v0.6.1 versions are completely consistent, so the `dynamic` method may introduce accuracy issues.

However, the results on the v0.6.1 version are normal and consistent with the results of HF model inference.
v0.6.0 execute command:
```python
1. model convert and build
CUDA_VISIBLE_DEVICES=0 python ./examples/llama/build.py \
                --world_size 4 \
                --tp_size 4 \
                --model_dir /workspace/70B_chat/70.long/ \
                --dtype float16 \
                --vocab_size 39424 \
                --max_batch_size 4 \
                --max_input_len 100352 \
                --max_output_len 4096 \
                --max_beam_width 1 \
                --rotary_base 500000 \
                --rotary_scaling dynamic 4.0 \
                --use_gpt_attention_plugin float16 \
                --use_gemm_plugin float16 \
                --parallel_build \
                --enable_context_fmha \
                --multi_block_mode \
                --use_parallel_embedding \
                --embedding_sharding_dim 0 \
                --use_inflight_batching \
                --paged_kv_cache \
                --remove_input_padding \
                --output_dir /workspace/70B_chat/70.long/trt_engines_v0.6.1/fp16/4-gpu/ > llama_70b_convert_tp4.log 2>&1
2. model inference
CUDA_VISIBLE_DEVICES=0,1,2,3 mpirun -n 4 --allow-run-as-root python3 ./examples/llama/run.py --max_output_len=4096 \
               --tokenizer_dir /workspace/70B_chat/70.long/\
               --input_tokens ./longtext.txt \
               --engine_dir=/workspace/70B_chat/70.long/trt_engines_v0.6.1/fp16/4-gpu/ >> llama-70b_fp16_4tp.log 2>&1
```

### Expected behavior

The v0.8.0 version results are consistent with the v0.6.1 model results.

### actual behavior

When supporting ntk, the v0.8.0 version model result is wrong.

### additional notes

v0.8.0
tllm_checkpoint_4gpu_tp4:
[config.json](https://github.com/NVIDIA/TensorRT-LLM/files/14599689/config.json)

v0.8.0
trt_engines:
[config.json](https://github.com/NVIDIA/TensorRT-LLM/files/14599702/config.json)

huggingface:
[config.json](https://github.com/NVIDIA/TensorRT-LLM/files/14599736/config.json)

**Comment by PerkzZheng** [comment]
Thanks for the reporting. There is a bug with the dynamic scaling. 
Can you try to change [this line](https://github.com/NVIDIA/TensorRT-LLM/blob/main/cpp/tensorrt_llm/kernels/decoderMaskedMultiheadAttentionUtils.h#L2558) to:
```
float const updated_base = dynamic_scaling && kv_seq_len > max_positions ? base * __powf(b, p) : base;
```
we will include that fix in the main branch soon.

**Comment by ZHangZHengEric** [comment]
> ### System Info
> * CPU: X86_64
> * GPU: 4*NVIDIA A100 80GB PCIe
> * TensorRT-LLM: 0.8.0
> 
> ### Who can help?
> @kaiyu @byshiue
> 
> ### Information
> * [x]  The official example scripts
> * [ ]  My own modified scripts
> 
> ### Tasks
> * [ ]  An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
> * [x]  My own task or dataset (give details below)
> 
> ### Reproduction
> Use TRT-LLM v0.8.0 version.
> 
> ```python
> 1. model convert and build
> python ./examples/llama/convert_checkpoint.py --model_dir /workspace/70B_chat/70.long/ \
>                             --output_dir /workspace/70B_chat/70.long/tllm_checkpoint_4gpu_tp4 \
>                             --dtype float16 \
>                             --tp_size 4 \
>                             --rotary_base 500000 \
>                             --rotary_scaling dynamic 4.0 > llama_70b_convert_tp4_v0.8x.log 2>&1
> 
> trtllm-build --checkpoint_dir /workspace/70B_chat/70.long/tllm_checkpoint_4gpu_tp4 \
>             --output_dir /workspace/70B_chat/70.long/tllm_checkpoint_4gpu_tp4/trt_engines/fp16/4-gpu/ \
>             --max_batch_size 4 \
>             --max_input_len 100352 \
>             --max_output_len 4096 \
>             --logits_dtype float32 \
>             --gemm_plugin float16 \
>             --multi_block_mode enable \
>             --context_fmha_fp32_acc enable \
>             --use_custom_all_reduce disable \
>             --enable_xqa disable \
>             > llama_70b_convert_tp4_v0.8x.log 2>&1
> 2. model inference
> mpirun -n 4 --allow-run-as-root python ./examples/run.py \
>                         --max_output_len 100 \
>                         --log_level info \
>                         --input_file ./longtext.txt \
>                         --max_input_length 100352 \
>                         --tokenizer_dir /workspace/70B_chat/70.long/ \
>                         --tokenizer_type llama \
>                         --engine_dir /workspace/70B_chat/70.long/tllm_checkpoint_4gpu_tp4/trt_engines/fp16/4-gpu/ >> llama-70b_fp16_4tp_v0.8x.log 2>&1
> ```
> 
> An error occurred in the output result, and the output token idx exceeded the vocabulary size.
> 
> ```python
> output_ids[batch_idx][beam][output_begin:output_end]=tensor([39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423,
>         39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423,
>         39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423,
>         39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423,
>         39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423,
>         39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423,
>         39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423,
>         39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423,
>         39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423,
>         39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423, 39423],
>        device='cuda:0', dtype=torch.int32)
> Traceback (most recent call last):
>   File "/workspace/trt-llm/TensorRT-LLM/build/../examples/run.py", line 529, in <module>
>     main(args)
>   File "/workspace/trt-llm/TensorRT-LLM/build/../examples/run.py", line 455, in main
>     print_output(tokenizer,
>   File "/workspace/trt-llm/TensorRT-LLM/build/../examples/run.py", line 275, in print_output
>     output_text = tokenizer.decode(outputs)
>   File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 3750, in decode
>     return self._decode(
>   File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils.py", line 1001, in _decode
>     filtered_tokens = self.convert_ids_to_tokens(token_ids, skip_special_tokens=skip_special_tokens)
>   File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils.py", line 982, in convert_ids_to_tokens
>     tokens.append(self._convert_id_to_token(index))
>   File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/tokenization_llama.py", line 280, in _convert_id_to_token
>     token = self.sp_model.IdToPiece(index)
>   File "/usr/local/lib/python3.10/dist-packages/sentencepiece/__init__.py", line 1179, in _batched_func
>     return _func(self, arg)
>   File "/usr/local/lib/python3.10/dist-packages/sentencepiece/__init__.py", line 1172, in _func
>     raise IndexError('piece id is out of range.')
> IndexError: piece id is out of range.
> ```
> 
> The length of input text tokens in `./longtext.txt` is less than 32000. When `rotary_scaling` is turned off, that is, `rotary_scaling=None`, the output results of the model are normal.
> 
> I adjusted the ntk mode from `dynamic` to `linear`. The model can produce results, but the model performance is poor. Using `rotary_scaling=linear, 4.0` method, the results of v0.8.0 and v0.6.1 versions are completely consistent, so the `dynamic` method may introduce accuracy issues.
> 
> However, the results on the v0.6.1 version are normal and consistent with the results of HF model inference. v0.6.0 execute command:
> 
> ```python
> 1. model convert and build
> CUDA_VISIBLE_DEVICES=0 python ./examples/llama/build.py \
>                 --world_size 4 \
>                 --tp_size 4 \
>                 --model_dir /workspace/70B_chat/70.long/ \
>                 --dtype float16 \
>                 --vocab_size 39424 \
>                 --max_batch_size 4 \
>                 --max_input_len 100352 \
>                 --max_output_len 4096 \
>                 --max_beam_width 1 \
>                 --rotary_base 500000 \
>                 --rotary_scaling dynamic 4.0 \
>                 --use_gpt_attention_plugin float16 \
>                 --use_gemm_plugin float16 \
>                 --parallel_build \
>                 --enable_context_fmha \
>                 --multi_block_mode \
>                 --use_parallel_embedding \
>                 --embedding_sharding_dim 0 \
>                 --use_inflight_batching \
>                 --paged_kv_cache \
>                 --remove_input_padding \
>                 --output_dir /workspace/70B_chat/70.long/trt_engines_v0.6.1/fp16/4-gpu/ > llama_70b_convert_tp4.log 2>&1
> 2. model inference
> CUDA_VISIBLE_DEVICES=0,1,2,3 mpirun -n 4 --allow-run-as-root python3 ./examples/llama/run.py --max_output_len=4096 \
>                --tokenizer_dir /workspace/70B_chat/70.long/\
>                --input_tokens ./longtext.txt \
>                --engine_dir=/workspace/70B_chat/70.long/trt_engines_v0.6.1/fp16/4-gpu/ >> llama-70b_fp16_4tp.log 2>&1
> ```
> 
> ### Expected behavior
> The v0.8.0 version results are consistent with the v0.6.1 model results.
> 
> ### actual behavior
> When supporting ntk, the v0.8.0 version model result is wrong.
> 
> ### additional notes
> v0.8.0 tllm_checkpoint_4gpu_tp4: [config.json](https://github.com/NVIDIA/TensorRT-LLM/files/14599689/config.json)
> 
> v0.8.0 trt_engines: [config.json](https://github.com/NVIDIA/TensorRT-LLM/files/14599702/config.json)
> 
> huggingface: [config.json](https://github.com/NVIDIA/TensorRT-LLM/files/14599736/config.json)

I also encountered this problem , Using rotary_scaling= dynamic, 8.0 , rotary_base =500000 ,The length of input text tokens is  more than 4096 ,the output is error . 
Running the same model using vllm is normal
Have you already resolved it

**Comment by PerkzZheng** [comment]
there is another issue (https://github.com/NVIDIA/TensorRT-LLM/issues/1610) discussing about the dynamic scaling problems.
close this one.
