### ISSUE TITLE
QwenVL sample code may not read image embed properly

### ISSUE THREAD

**Issue by xikaluo** [NVIDIA/TensorRT-LLM#1300]
### System Info

-GPU: 1 * A100(80G)
-TensorRT-LLM version: 0.9.0.dev2024031200
-TensorRT version: 9.2.0.post12.dev5
-Nvidia Driver: Driver Version: 535.54.03 CUDA Version: 12.1
-OS: Ubuntu 22.04

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. use this script to build VIT engine:
CUDA_VISIBLE_DEVICES=0 python vit_onnx_trt.py \
    --pretrained_model_path /workspace/models/Qwen-VL-Chat \
    --onnxFile /workspace/trt_engines/Qwen-VL-Chat/onnx/visual_encoder.onnx \
    --planFile /workspace/trt_engines/Qwen-VL-Chat/plan/visual_encoder_fp16.plan \
    >vit_onnx_trt.log 2>&1

2. use this script to build Qwen-LM engine:
CUDA_VISIBLE_DEVICES=0 python ../qwen/build.py \
    --world_size 1 \
    --tp_size 1 \
    --pp_size 1 \
    --model_dir /workspace/models/Qwen-VL-Chat \
    --dtype float16 \
    --max_batch_size 1 \
    --max_input_len 2048 \
    --max_output_len 512 \
    --use_gpt_attention_plugin float16 \
    --use_gemm_plugin float16 \
    --enable_context_fmha \
    --remove_input_padding \
    --use_lookup_plugin float16 \
    --output_dir /workspace/trt_engines/Qwen-VL-Chat/llm-tp1pp1-in2048out512-bsz1 \
    >build_llm_engine.log 2>&1

3. use this script to run inference:
CUDA_VISIBLE_DEVICES=0 python run.py \
    --tokenizer_dir /workspace/models/Qwen-VL-Chat \
    --qwen_engine_dir /workspace/trt_engines/Qwen-VL-Chat/llm-tp1pp1-in2048out512-bsz1 \
    --vit_engine_dir /workspace/trt_engines/Qwen-VL-Chat/plan \
    --images_path='{"image": "./pics/demo.jpeg"}' \
    --input_dir='{"image": "./pics/demo.pt"}' \
    --input_text 描述一下这张图片

### Expected behavior

The code should provide proper description of the image

### actual behavior

The code seems to read neither image file nor image embedding. The output is irrelevant to the picture. In addition, if I change the path of input_dir and images_path, the output does not change

### additional notes

I think maybe it is due to the special method for processing input text embedding and image embedding, shown in https://huggingface.co/Qwen/Qwen-VL-Chat/blob/main/modeling_qwen.py#L630 to https://huggingface.co/Qwen/Qwen-VL-Chat/blob/main/modeling_qwen.py#L665. But to my knowledge, this method may not be implemented in https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/qwenvl/run.py? I'm not sure if the prompt_table is supposed to do this

**Comment by xikaluo** [comment]
Sorry, I just found that the 'max_prompt_embedding_table_size' argument is missed in building LLM engine. Things goes right after adding it to the script

**Comment by Popsicle0-0** [comment]
> ### System Info
> -GPU: 1 * A100(80G) -TensorRT-LLM version: 0.9.0.dev2024031200 -TensorRT version: 9.2.0.post12.dev5 -Nvidia Driver: Driver Version: 535.54.03 CUDA Version: 12.1 -OS: Ubuntu 22.04
> 
> ### Who can help?
> _No response_
> 
> ### Information
> * [x]  The official example scripts
> * [ ]  My own modified scripts
> 
> ### Tasks
> * [x]  An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
> * [ ]  My own task or dataset (give details below)
> 
> ### Reproduction
> 1. use this script to build VIT engine:
>    CUDA_VISIBLE_DEVICES=0 python vit_onnx_trt.py 
>    --pretrained_model_path /workspace/models/Qwen-VL-Chat 
>    --onnxFile /workspace/trt_engines/Qwen-VL-Chat/onnx/visual_encoder.onnx 
>    --planFile /workspace/trt_engines/Qwen-VL-Chat/plan/visual_encoder_fp16.plan \
>    > vit_onnx_trt.log 2>&1
> 2. use this script to build Qwen-LM engine:
>    CUDA_VISIBLE_DEVICES=0 python ../qwen/build.py 
>    --world_size 1 
>    --tp_size 1 
>    --pp_size 1 
>    --model_dir /workspace/models/Qwen-VL-Chat 
>    --dtype float16 
>    --max_batch_size 1 
>    --max_input_len 2048 
>    --max_output_len 512 
>    --use_gpt_attention_plugin float16 
>    --use_gemm_plugin float16 
>    --enable_context_fmha 
>    --remove_input_padding 
>    --use_lookup_plugin float16 
>    --output_dir /workspace/trt_engines/Qwen-VL-Chat/llm-tp1pp1-in2048out512-bsz1 \
>    > build_llm_engine.log 2>&1
> 3. use this script to run inference:
>    CUDA_VISIBLE_DEVICES=0 python run.py 
>    --tokenizer_dir /workspace/models/Qwen-VL-Chat 
>    --qwen_engine_dir /workspace/trt_engines/Qwen-VL-Chat/llm-tp1pp1-in2048out512-bsz1 
>    --vit_engine_dir /workspace/trt_engines/Qwen-VL-Chat/plan 
>    --images_path='{"image": "./pics/demo.jpeg"}' 
>    --input_dir='{"image": "./pics/demo.pt"}' 
>    --input_text 描述一下这张图片
> 
> ### Expected behavior
> The code should provide proper description of the image
> 
> ### actual behavior
> The code seems to read neither image file nor image embedding. The output is irrelevant to the picture. In addition, if I change the path of input_dir and images_path, the output does not change
> 
> ### additional notes
> I think maybe it is due to the special method for processing input text embedding and image embedding, shown in https://huggingface.co/Qwen/Qwen-VL-Chat/blob/main/modeling_qwen.py#L630 to https://huggingface.co/Qwen/Qwen-VL-Chat/blob/main/modeling_qwen.py#L665. But to my knowledge, this method may not be implemented in https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/qwenvl/run.py? I'm not sure if the prompt_table is supposed to do this

Hi, do you know why qwenvl can use prompt_table，without the special method for processing text embedding and image embedding?
