### ISSUE TITLE
Errors caused by source code installation

### ISSUE THREAD

**Issue by Hukongtao** [NVIDIA/TensorRT-LLM#1301]
### System Info

- CPU architecture: x86_64 GNU/Linux
- CPU memory size: 64G
- GPU: A100
- TensorRT-LLM commit : 4bb65f216f2f1dbddb022f4fdd8925c2856baa58
- TensorRT version: 9.3.0.post12.dev1
- CUDA version: 12.2 

### Who can help?

@by

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

According to:https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/build_from_source.md
```
sudo apt-get update && sudo apt-get -y install git git-lfs
git clone https://github.com/NVIDIA/TensorRT-LLM.git
cd TensorRT-LLM
git submodule update --init --recursive
git lfs install
git lfs pull
python3 ./scripts/build_wheel.py --trt_root /usr/local/tensorrt
```

### Expected behavior

Successfully installed

### actual behavior

![image](https://github.com/NVIDIA/TensorRT-LLM/assets/16505966/5f88a2a8-2d72-4856-b3da-e259e3e0ffd5)
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/16505966/8173eece-7eae-46c8-8887-0a73397edb1b)

### additional notes

It could be installed correctly before. Today I updated the code of the main branch. Then the installation reported an error.
The biggest update is the tensorrt version, but I also reinstalled tensorrt 9.3

**Comment by Hukongtao** [comment]
By increasing the CPU memory, the above problem disappears, but a new error appears：
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/16505966/4a8b4120-c961-49a6-8f86-158e1ae71b47)

**Comment by byshiue** [comment]
Might you running the build again with `--clean`?

**Comment by Hukongtao** [comment]
> Might you running the build again with `--clean`?

Yes, can't this parameter be used?

**Comment by byshiue** [comment]
Do you mean you build the tensorrt_llm with `--clean` again and it still fails?
