### ISSUE TITLE
INT8 KV caching + bf16 LLaMA engine generates garbage tokens (0.8.0 release)

### ISSUE THREAD

**Issue by vnkc1** [NVIDIA/TensorRT-LLM#1303]
### System Info

GPU : NVIDIA A100 80GB

package version
tensorrt-9.2.0.post12.dev5-cp310-none-linux_x86_64.whl
[TensorRT-LLM] TensorRT-LLM version: 0.8.00.8.0

### Who can help?

@Tracin @byshiue 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Installation
`python -m pip install tensorrt_llm==0.8.0 --extra-index-url https://pypi.nvidia.com`

2. Create checkpoint
`python ~/examples/llama/convert_checkpoint.py --model_dir ~/Llama-2-13b-chat-hf  --output_dir ~/checkpoints/bf16-tp4-int8kv --dtype bfloat16 --tp_size 4 --workers 4 --int8_kv_cache`

3. Create engine
`trtllm-build --checkpoint_dir ~/checkpoints/bf16-tp4-int8kv  --output_dir ~/bf16-tp4-int8kv --gpt_attention_plugin bfloat16 --gemm_plugin bfloat16 --remove_input_padding enable --paged_kv_cache enable --context_fmha enable --workers 4 --max_batch_size 32 --max_input_len 4096 --max_output_len 512`

4. Generate output from engine using `run.py`

### Expected behavior

Sensible generation

### actual behavior

Garbage generation (for all prompts) such as 
`And fear fear fear fear fear fear fear fear fear fear fear fear fear fear fear fear fear fear fear fear fear`

### additional notes

If it's not possible to build bf16 + int8 kv cache engines, could there be an error printed during build process?

**Comment by hientominh** [comment]
I got the same error with [llama-2-13B-4bit version 1.5](https://catalog.ngc.nvidia.com/orgs/nvidia/models/llama2-13b/files?version=1.5), tensorrt-llm release 0.8.0.
- Windows 11
- RTX 3090

```
python ..\run.py --max_output_len 50 --engine_dir C:\Users\HOME\Downloads\out-llama2-13b --tokenizer_dir C:\Users\HOME\Downloads\Llama2-13b-Chat-Int4\llama13_hf_tokenizer
[TensorRT-LLM][INFO] Engine version 0.8.0 found in the config file, assuming engine(s) built by new builder API.
[TensorRT-LLM][WARNING] [json.exception.out_of_range.403] key 'lora_target_modules' not found
[TensorRT-LLM][WARNING] Optional value for parameter lora_target_modules will not be set.
[TensorRT-LLM][WARNING] Parameter max_draft_len cannot be read from json:
[TensorRT-LLM][WARNING] [json.exception.out_of_range.403] key 'max_draft_len' not found
[TensorRT-LLM][WARNING] [json.exception.type_error.302] type must be string, but is null
[TensorRT-LLM][WARNING] Optional value for parameter kv_cache_quant_algo will not be set.
[TensorRT-LLM][INFO] MPI size: 1, rank: 0
[TensorRT-LLM][INFO] Loaded engine size: 6872 MiB
[TensorRT-LLM][INFO] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +1, GPU +8, now: CPU 17514, GPU 8143 (MiB)
[TensorRT-LLM][INFO] [MemUsageChange] Init cuDNN: CPU +6, GPU +8, now: CPU 17520, GPU 8151 (MiB)
[TensorRT-LLM][WARNING] TensorRT was linked against cuDNN 8.9.6 but loaded cuDNN 8.8.1
[TensorRT-LLM][INFO] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +6867, now: CPU 0, GPU 6867 (MiB)
[TensorRT-LLM][INFO] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 17561, GPU 8277 (MiB)
[TensorRT-LLM][INFO] [MemUsageChange] Init cuDNN: CPU +6, GPU +8, now: CPU 17567, GPU 8285 (MiB)
[TensorRT-LLM][WARNING] TensorRT was linked against cuDNN 8.9.6 but loaded cuDNN 8.8.1
[TensorRT-LLM][INFO] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 6867 (MiB)
[TensorRT-LLM][INFO] Allocate -1765801984 bytes for k/v cache.
[TensorRT-LLM][INFO] Using 18816 tokens in paged KV cache.
[TensorRT-LLM] TensorRT-LLM version: 0.8.0Input [Text 0]: "<s> Born in north-east France, Soyer trained as a"
Output [Text 0 Beam 0]: ".1., släktet$}}%--2 släktet..11.....2.-.$}}% year--- släktet.,,... släktet--. . släktet... släktet släktet$}}% släktet-"
```

**Comment by hientominh** [comment]
tensorrt-llm release 0.8.0 [mistral-7b-int4-chat version 1.2](https://catalog.ngc.nvidia.com/orgs/nvidia/models/mistral-7b-int4-chat/files)
- Windows 11
- RTX 4070ti

```
python ..\run.py --max_output_len 50 --tokenizer_dir C:\Users\Username\Downloads\files\mistral7b_hf_tokenizer\ --engine_dir C:\Users\Username\Downloads\out-mistral-test\
[TensorRT-LLM][INFO] Engine version 0.8.0 found in the config file, assuming engine(s) built by new builder API.
[TensorRT-LLM][WARNING] [json.exception.out_of_range.403] key 'lora_target_modules' not found
[TensorRT-LLM][WARNING] Optional value for parameter lora_target_modules will not be set.
[TensorRT-LLM][WARNING] Parameter max_draft_len cannot be read from json:
[TensorRT-LLM][WARNING] [json.exception.out_of_range.403] key 'max_draft_len' not found
[TensorRT-LLM][WARNING] [json.exception.type_error.302] type must be string, but is null
[TensorRT-LLM][WARNING] Optional value for parameter kv_cache_quant_algo will not be set.
[TensorRT-LLM][INFO] MPI size: 1, rank: 0
[TensorRT-LLM][INFO] Loaded engine size: 3938 MiB
[TensorRT-LLM][INFO] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 76385, GPU 6465 (MiB)
[TensorRT-LLM][INFO] [MemUsageChange] Init cuDNN: CPU +188, GPU +56, now: CPU 76573, GPU 6521 (MiB)
[TensorRT-LLM][WARNING] TensorRT was linked against cuDNN 8.9.6 but loaded cuDNN 8.8.1
[TensorRT-LLM][INFO] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +3934, now: CPU 0, GPU 3934 (MiB)
[TensorRT-LLM][INFO] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 76611, GPU 6647 (MiB)
[TensorRT-LLM][INFO] [MemUsageChange] Init cuDNN: CPU +2, GPU +8, now: CPU 76613, GPU 6655 (MiB)
[TensorRT-LLM][WARNING] TensorRT was linked against cuDNN 8.9.6 but loaded cuDNN 8.8.1
[TensorRT-LLM][INFO] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 3934 (MiB)
[TensorRT-LLM][WARNING] CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage and speed up TensorRT initialization. See "Lazy Loading" section of CUDA documentation https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#lazy-loading
[TensorRT-LLM][INFO] Allocate 1040187392 bytes for k/v cache.
[TensorRT-LLM][INFO] Using 40704 tokens in paged KV cache.
[TensorRT-LLM] TensorRT-LLM version: 0.8.0Input [Text 0]: "<s> Born in north-east France, Soyer trained as a"
Output [Text 0 Beam 0]: ".梦梦梦梦梦梦梦梦梦梦梦梦梦梦梦梦梦梦梦梦梦梦梦梦梦梦梦梦梦梦梦梦梦梦梦梦梦梦梦梦梦梦梦梦梦梦梦梦梦"
```

**Comment by byshiue** [comment]
Could you try building engine on the checkpoints without running `convert_checkpoint`? It looks the checkpoints you shared are quantized and converted.

**Comment by ghost** [comment]
> Could you try building engine on the checkpoints without running `convert_checkpoint`? It looks the checkpoints you shared are quantized and converted.

How do I build the engine without running `convert_checkpoint` in the 0.8.0 release?

**Comment by byshiue** [comment]
> > Could you try building engine on the checkpoints without running `convert_checkpoint`? It looks the checkpoints you shared are quantized and converted.
> 
> How do I build the engine without running `convert_checkpoint` in the 0.8.0 release?

You could try building engine by the checkpoint you download.

**Comment by Tracin** [comment]
@vnkc1 Sorry I could not reproduce the issue. We do support bf16 + int8kv.

**Comment by felixslu** [comment]
I got the same error on v0.8.0.

when I run "python  summarize.py --test_trt_llm ***  --max_ite 500"  on CNNDM datasets & llama2 7B.


**int8 kv-cache (weight fp16)**
`[03/19/2024-10:08:15] [TRT-LLM] [I] TensorRT-LLM (total latency: 1016.9027755260468 sec)  
  
[03/19/2024-10:08:15] [TRT-LLM] [I] TensorRT-LLM (total output tokens: 50000)  
 
[03/19/2024-10:08:15] [TRT-LLM] [I] TensorRT-LLM (tokens per second: 49.168908968839084)  
  
[03/19/2024-10:08:15] [TRT-LLM] [I] TensorRT-LLM beam 0 result   
 
[03/19/2024-10:08:15] [TRT-LLM] [I]   rouge1 : 10.212996533050415  
  
[03/19/2024-10:08:15] [TRT-LLM] [I]   rouge2 : 0.30712133332043057   
 
[03/19/2024-10:08:15] [TRT-LLM] [I]   rougeL : 7.992411871867308   
 
[03/19/2024-10:08:15] [TRT-LLM] [I]   rougeLsum : 9.289675203878891  `



**fp16 precision**
`[03/19/2024-09:17:45] [TRT-LLM] [I] TensorRT-LLM (total latency: 996.5542404651642 sec)  

[03/19/2024-09:17:45] [TRT-LLM] [I] TensorRT-LLM (total output tokens: 49182)  

[03/19/2024-09:17:45] [TRT-LLM] [I] TensorRT-LLM (tokens per second: 49.35205531516598)  

[03/19/2024-09:17:45] [TRT-LLM] [I] TensorRT-LLM beam 0 result  

[03/19/2024-09:17:46] [TRT-LLM] [I]   rouge1 : 21.979676431370258  

[03/19/2024-09:17:46] [TRT-LLM] [I]   rouge2 : 6.95267014536316  

[03/19/2024-09:17:46] [TRT-LLM] [I]   rougeL : 15.66345440557999  

[03/19/2024-09:17:46] [TRT-LLM] [I]   rougeLsum : 19.092060051464884`

**Comment by ghost** [comment]
@Tracin Are the installation, checkpoint creation and engine build commands specified sufficient to build a bf16 + int8 kv engine?

**Comment by ghost** [comment]
@Tracin I just re-did the repro (with the only difference being `--strongly_typed` option added to engine build to avoid errors on 0.8.0

@byshiue I don't see a command line option in `trtllm-build` to specify that INT8 KV cache is needed directly, without using `convert_checkpoint`. Could you specify the exact command?

**Comment by Tracin** [comment]
@vnkc1 @felixslu  
How about test on latest main branch? It works well on latest main from my side.

**Comment by ghost** [comment]
@Tracin I need an inference engine that would work with triton inference server. The support matrix for triton 0.24 only extends till 0.8.0 tensor Rt llm

**Comment by Tracin** [comment]
@vnkc1 @felixslu Looks like we have already started to debug this. Please remove `--workers 4` option from `convert_checkpoint.py`

**Comment by ghost** [comment]
@Tracin Thanks this worked for me, closing this issue.
