### ISSUE TITLE
Gemma convert_checkpoint.py script breaks at `quantize_fp8_weights()` when some HF parameters are offloaded to CPU

### ISSUE THREAD

**Issue by jhirschibar** [NVIDIA/TensorRT-LLM#1307]
### System Info

- Hardware:
   - CPU architecture: x86
   - RAM: 64 GB
   - GPU:
      - NVIDIA 4090 RTX
      - vRAM 24 GB
- Libraries:
   - TensorRT-LLM branch: main
   - CUDA version: 12.3
   - Docker container: `nvidia/cuda:12.3.2-devel-ubuntu22.04`
- Nvidia Driver version: 551.61
- OS: Ubuntu 22.04 in WSL2

### Who can help?

@Tracin @byshiue 

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

After building the container, installing python 3.10 and installing all the requirements from the `Gemma` example (without overwriting cuda python inherent in the container), I run the following command:

`CMD ["python3", "/opt/TensorRT-LLM/examples/gemma/convert_checkpoint.py", "--ckpt-type", "hf", "--model-dir", "google/gemma-7b-it/", "--dtype", "bfloat16", "--world-size", "1", "--output-model-dir", "/tmp/model/gemma-7b-it/gemma-7b-tensorrt", "--enable_fp8", "--fp8_kv_cache"]`

### Expected behavior

The script would produce a tensorrt checkpoint of the model with weights having been quantized to FP8. This would consist of a new directory `/tmp/model/gemma-7b-it/gemma-7b-tensorrt` being created containing a `config.json` file and a `rank0.safetensors` file.

### actual behavior

The script fails on the `quantized_fp8_weights()` function with this output and traceback:
```
[TensorRT-LLM] TensorRT-LLM version: 0.9.0.dev2024030500
Loading source parameters from google/gemma-7b-it
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████| 4/4 [00:10<00:00,  2.60s/it]
Source configuration determined from parameters: {'num_layers': 28, 'num_embed': 256000, 'embed_dim': 3072, 'hidden_dim': 24576, 'num_heads': 16, 'head_dim': 256, 'num_kv_heads': 16}
Determined TensorRT-LLM configuration {'architecture': 'GemmaForCausalLM', 'dtype': 'bfloat16', 'logits_dtype': 'float32', 'vocab_size': 256000, 'max_position_embeddings': 8192, 'hidden_size': 3072, 'num_hidden_layers': 28, 'num_attention_heads': 16, 'num_key_value_heads': 16, 'head_size': 256, 'hidden_act': 'gelu', 'intermediate_size': 24576, 'norm_epsilon': 1e-06, 'position_embedding_type': 'rope_gpt_neox', 'use_prompt_tuning': False, 'use_parallel_embedding': False, 'embedding_sharding_dim': 0, 'share_embedding_table': False, 'mapping': {'world_size': 1, 'tp_size': 1, 'pp_size': 1}, 'quantization': {'quant_algo': 'FP8', 'kv_cache_quant_algo': 'FP8', 'group_size': 128, 'has_zero_point': False, 'pre_quant_scale': False, 'exclude_modules': None, 'sq_use_plugin': False}, 'kv_dtype': 'fp8', 'max_lora_rank': 64}
Loading weights...
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  3.75it/s]
[03/15/2024-15:08:42] Some parameters are on the meta device device because they were offloaded to the cpu.
Weights loaded. Total time: 00:00:10
Traceback (most recent call last):
  File "/opt/TensorRT-LLM/examples/gemma/convert_checkpoint.py", line 991, in <module>
    main()
  File "/opt/TensorRT-LLM/examples/gemma/convert_checkpoint.py", line 984, in main
    convert(0, args, convert_args)
  File "/opt/TensorRT-LLM/examples/gemma/convert_checkpoint.py", line 871, in convert
    weight_scales = quantize_fp8_weights(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/gemma/weight.py", line 826, in quantize_fp8_weights
    weight = weights[trt_llm_name]
KeyError: 'transformer.layers.7.attention.qkv.weight'
```

### additional notes

I believe this is occuring because of the way that huggingface offloads parameters to CPU that do not fit entirely on the GPU at one time (hence the desire to quantize). However, this causes the current script to break as it iterates through the different layer names. It does not account for the huggingface's method of cycling these parameters. 

Additionally, the script broke early, at the `flatten_parameters()` step for a similar reason: huggingface inserts meta tensors as part of their cycling logic that were unhandled. I was able to circumvent this with a simple fix. I changed the `flatten_parameters() function to be this in the HFParser class:
```
def flatten_params(self, params):
    f_params = {}
    for k, v in params.items():
        if not v.is_meta:
            if v.dtype == torch.bfloat16:
                v = v.float()
            f_params[k] = torch_to_numpy(v)
    return f_params
```

**Comment by jhirschibar** [comment]
It may also be worth noting that the `main` branch documentation for the `Gemma` model does not reference the ability to load a checkpoint from Huggingface despite the `HFParser` being added in the last PR. The docs need updating.

**Comment by byshiue** [comment]
I will investigate the issue. For the document issue, it is mentioned [here](https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/gemma#support-matrix).

**Comment by byshiue** [comment]
Might you try using ammo to generate fp8 checkpoint? It is the recommended way after ammo is updated. The scripts are like
```bash
python ../quantization/quantize.py --model_dir google/gemma-7b-it/ \
            --dtype float16 \
            --qformat fp8 \
            --output_dir /tmp/model/gemma-7b-it/gemma-7b-tensorrt \
            --tp_size 1
```

**Comment by jhirschibar** [comment]
> Might you try using ammo to generate fp8 checkpoint? It is the recommended way after ammo is updated. The scripts are like
> 
> ```shell
> python ../quantization/quantize.py --model_dir google/gemma-7b-it/ \
>             --dtype float16 \
>             --qformat fp8 \
>             --output_dir /tmp/model/gemma-7b-it/gemma-7b-tensorrt \
>             --tp_size 1
> ```

This worked. Thank you very much for pointing me towards this!
