### ISSUE TITLE
how to set the  PromptTuningParams in GenerationInput?

### ISSUE THREAD

**Issue by TianDekuan** [NVIDIA/TensorRT-LLM#1308]
### System Info

o

### Who can help?

How to set up the `embeddingTable` and `tasks` parameters in the `PromptTuningParams` for `GenerationInput`, particularly when handling multi-batch inputs where every input has several images? To ensure that one can discern which image belongs to which input within the batch.
![微信图片_20240317192329](https://github.com/NVIDIA/TensorRT-LLM/assets/7059520/9a903509-d066-4cd9-8db0-10c25814b0b8)

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1

### Expected behavior

2

### actual behavior

3

### additional notes

4

**Comment by mickaelseznec** [comment]
What  runtime are you using? For triton backend, you can take a look at https://github.com/triton-inference-server/tensorrtllm_backend/blob/main/inflight_batcher_llm/client/inflight_batcher_llm_client.py#L560

**Comment by byshiue** [comment]
Close the issue because it is inactivate. Feel free to ask here if needed and we can repoen it at the time.
