### ISSUE TITLE
How to add a user-specified embedding to each token's embedding during model generation?

### ISSUE THREAD

**Issue by manlenzzz** [NVIDIA/TensorRT-LLM#1310]

**Comment by mickaelseznec** [comment]
Sounds like a task for prompt-tuning? https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/gpt/README.md#prompt-tuning

**Comment by manlenzzz** [comment]
Sorry, I didn't describe it clearly.

I am working on deploying a pre-trained multimodal model with TensorRT for inference acceleration. The model incorporates a Vision Transformer (ViT) and is designed to handle sequences that include both text tokens and image tokens.

For instance, the input IDs to the model might look like [1, 2, 3, ..., IMG_TOKEN_ID, ..., IMG_TOKEN_ID], where IMG_TOKEN_ID represents an image token. The corresponding embeddings for these IDs are [tok1-emb, ..., tok_imgid_emb, ..., tok_imgid_emb, ...], indicating that specific embeddings are used for image tokens.

I would like to know if TensorRT supports this type of modification/addition to generate‘s input_id for multimodal models, particularly for cases where the model input includes both text and image tokens, as described. My goal is to leverage TensorRT for inference acceleration on this pre-trained multimodal model

Thank you for your time and assistance.

**Comment by changhaizhou98** [comment]
In simple terms, I wish to add an externally provided embedding to the embedding corresponding to each input_id. The additional embedding to be added will vary with each input (possibly based on user input).

**Comment by changhaizhou98** [comment]
"I'm working with a multimodal model handling both text and image inputs, where the image and text tokens are combined into a single input sequence. Each image token corresponds to a specific embedding. I'm interested in exploring how to dynamically add an external embedding to the embeddings of these image tokens, with the external embedding varying based on user input. Could you provide guidance or examples on how to implement this, especially in the context of using TensorRT for inference acceleration?"

Thank you for your time and assistance.

**Comment by mickaelseznec** [comment]
Yes, that sounds like something you can do with prompt-tuning. Basically you would add new tokens id on top of your base vocabulary. For those extra tokens, you can provide an embedding table. It's available on tensorrt_llm triton backend, for example: https://github.com/triton-inference-server/tensorrtllm_backend/blob/main/all_models/inflight_batcher_llm/tensorrt_llm/config.pbtxt#L204

**Comment by byshiue** [comment]
Close the issue because it is inactivate. Feel free to ask here if needed and we can repoen it at the time.
