### ISSUE TITLE
need set promptTuningEnabled in splitInputs in gptSession.cpp

### ISSUE THREAD

**Issue by TianDekuan** [NVIDIA/TensorRT-LLM#1311]
### System Info

1

### Who can help?

2
![17](https://github.com/NVIDIA/TensorRT-LLM/assets/7059520/ee400144-cbee-4309-976b-13bde74f76a8)

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

3

### Expected behavior

4

### actual behavior

5

### additional notes

6

**Comment by mickaelseznec** [comment]
Sorry I don't get what's your issue, could you elaborate?

**Comment by byshiue** [comment]
Close the issue because it is inactivate. Feel free to ask here if needed and we can repoen it at the time.
