### ISSUE TITLE
Mixtral engine bfloat16 build failure

### ISSUE THREAD

**Issue by vnkc1** [NVIDIA/TensorRT-LLM#1313]
### System Info

p4d with 8 GPUs : NVIDIA A100 40GB x 8

package version
tensorrt-9.2.0.post12.dev5-cp310-none-linux_x86_64.whl
[TensorRT-LLM] TensorRT-LLM version: 0.8.00.8.0

### Who can help?

@byshiue 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Installation
`python -m pip install tensorrt_llm==0.8.0 --extra-index-url https://pypi.nvidia.com`

Create checkpoint
`python ./examples/llama/convert_checkpoint.py --model_dir  ~/Mixtral-8x7B-Instruct-v0.1 --output_dir ~/checkpoints/Mixtral-8x7B-Instruct-v0.1/bf16-tp8 --dtype bfloat16 --tp_size 8 --workers 8 --load_model_on_cpu`

### Expected behavior

Checkpoint created successfully

### actual behavior

    config[prefix + ".weight"].data = config[prefix + ".weight"].to(dtype)
RuntimeError: expected scalar type BFloat16 but found Float
https://github.com/NVIDIA/TensorRT-LLM/blob/v0.8.0/examples/llama/convert_checkpoint.py#L629

### additional notes

N/A

**Comment by djns99** [comment]
Hi @vnkc1,
Thanks for reaching out, could you provide the full output of the `convert_checkpoint.py` command?

**Comment by vnkc1** [comment]
I'm not able to reproduce this, my apologies for wasting your time. @djns99
