### ISSUE TITLE
[BUG]Compilation error in version 0.8.0

### ISSUE THREAD

**Issue by wjj19950828** [NVIDIA/TensorRT-LLM#1314]
1、commit id
4bb65f216f2f1dbddb022f4fdd8925c2856baa58
2、Reproduce command
```shell
python3 ./scripts/build_wheel.py --trt_root="/usr/local/tensorrt" &&     pip3 install ./build/tensorrt_llm*.whl
```
3、Error message
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/19977378/b8045e24-c0e4-4fd9-9eb5-dc5aaecc4c1b)

4、cutlass commit id
a8f2c80db0564c74f4efccac71993b971dfc448b

THX~

**Comment by wjj19950828** [comment]
@byshiue Can you reproduce this issue?

**Comment by litaotju** [comment]
These cuda driver APIs are used by cutlass. Could you try to build with new cuda driver?  

The API was introduced in cuda 12, which needs at least cuda driver 525.
