### ISSUE TITLE
[New Feature]Does W8A8 currently support mixed precision inference?

### ISSUE THREAD

**Issue by wjj19950828** [NVIDIA/TensorRT-LLM#1317]
Currently SQ encounters accuracy and diff rate issues

Is there any good solution?

Does TRT_LLM currently support mixed precision? FP16 is used in the Linear layer with high quantization sensitivity, and INT8 is used in others.

Thank you~

**Comment by wjj19950828** [comment]
@Tracin Do you have some suggestions?

Thanks~

**Comment by nv-guomingz** [comment]
No, we don't support mixed-precision at current stage.
