### ISSUE TITLE
Are there any way to use FP8 weights, FP16 activations quantization

### ISSUE THREAD

**Issue by ttim** [NVIDIA/TensorRT-LLM#1319]
### System Info

- H100
- Llama 70B model

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Quantize model weights with FP8 format but not activations

### Expected behavior

1. Activations kept in FP16, but weights in FP8

### actual behavior

1. Only possible to quantize both weights and activations to FP8

### additional notes

Maybe there is a way to enable it but I didn't find it

**Comment by Tracin** [comment]
I think you can modify code like removing QDQ pattern for activation and use original FP8 checkpoint to build a model.

**Comment by ttim** [comment]
@Tracin Currently I'm using `LLaMAForCausalLM.quantize` method and `trtllm-build` script. What exactly original checkpoint would mean in this case? Is it possible to build engine this way (FP8 weights only quantization basically)? Thank you!

**Comment by Tracin** [comment]
@ttim Sorry, I think we don't have FP8 x FP16 kernels right now, so you cannot do that.
