### ISSUE TITLE
Batch inference performance degrades when GPU memory available is very tight

### ISSUE THREAD

**Issue by haojiwei** [NVIDIA/TensorRT-LLM#132]
For multi-batch inference, adjust `run.sh` in `example/llama` according to [issues#42](https://github.com/NVIDIA/TensorRT-LLM/issues/42) and arrange input_ids to shape `[batch_size, input_ids_length]`.

When inference llama-13B for `batch_size=16` on a single A100-40GB, The memory usage remains 40327GB/40960GB and GPU utilization is as low as 7%.

Is this normal? And is there a suitable manual explaining how to perform multi-batch inference? 

More details. Set `max_batch_size`=64 in `build.py` to build engine. performance of this engine for `batch_size=4` inference is normal, for `batch_size=16` inference degrades and for `batch_size=64` inference encounter CUDA memory OOM in decoder.setup stage.

Set `max_batch_size`=16 in `build.py` to build engine. performance of this engine for `batch_size=16` inference is normal.

**Comment by byshiue** [comment]
It depends on problem size, it is common to observe low gpa utilization if batch size is not large. You can share you problem size.

For performance issue, when you set bs to 64, trt will search best kernel for bs 64, so the performance of bs 16 may be worse. You can share your number to help us check is there any issue.

**Comment by haojiwei** [comment]
> It depends on problem size, it is common to observe low gpa utilization if batch size is not large. You can share you problem size.

Same input ids, GPU utilization of `batch_size=4` is up to 98%. 

> For performance issue, when you set bs to 64, trt will search best kernel for bs 64, so the performance of bs 16 may be worse. You can share your number to help us check is there any issue.

Which number is needed?

**Comment by byshiue** [comment]
> Which number is needed?
The perf number you observe, like latency under different case.

**Comment by jdemouth-nvidia** [comment]
Hi @haojiwei , 

How do you compute "GPU Utilization"? Is that measured using Nsight Systems or another tool?

Thanks,
Julien

**Comment by haojiwei** [comment]
> Hi @haojiwei ,
> 
> How do you compute "GPU Utilization"? Is that measured using Nsight Systems or another tool?
> 
> Thanks, Julien

displayed by nvidia-smi

**Comment by haojiwei** [comment]
> > Which number is needed?
> > The perf number you observe, like latency under different case.

use `max_batch_size=64` to build engine on a single A100-40GB GPU.

Executing a `batch_size=1` inference takes 2298ms and a `batch_size=4` inference takes 2312ms for `max_output_len=100`. But for  `batch_size=16`, it takes 17548ms.

**Comment by jdemouth-nvidia** [comment]
Are you using the same input sequence for each item of the batch? And does the model produce the same output sequences for each item? In other words, are you sure that with `BS == 16` there's not an output sequence that is significantly longer than the longest sequence with `BS == 4`?

**Comment by haojiwei** [comment]
> Are you using the same input sequence for each item of the batch? And does the model produce the same output sequences for each item? In other words, are you sure that with `BS == 16` there's not an output sequence that is significantly longer than the longest sequence with `BS == 4`?

Using the default input_text 'Born in north-east France, Soyer trained as a'. And there is my adjustment on run.sh parse_input function:

<img width="989" alt="屏幕截图 2023-10-26 172856" src="https://github.com/NVIDIA/TensorRT-LLM/assets/47234697/158dfe15-9104-4814-accb-7ede7d126b5c">

**Comment by byshiue** [comment]
> > Are you using the same input sequence for each item of the batch? And does the model produce the same output sequences for each item? In other words, are you sure that with `BS == 16` there's not an output sequence that is significantly longer than the longest sequence with `BS == 4`?
> 
> Using the default input_text 'Born in north-east France, Soyer trained as a'. And there is my adjustment on run.sh parse_input function:
> 
> <img alt="屏幕截图 2023-10-26 172856" width="989" src="https://user-images.githubusercontent.com/47234697/278282318-158dfe15-9104-4814-accb-7ede7d126b5c.png">

Can you share the scripts to build the engine and the script to profile the program? 

If you change run.py to profile the program, please remember to add warmup and run more iterations for the program.

**Comment by haojiwei** [comment]
> > > Are you using the same input sequence for each item of the batch? And does the model produce the same output sequences for each item? In other words, are you sure that with `BS == 16` there's not an output sequence that is significantly longer than the longest sequence with `BS == 4`?
> > 
> > 
> > Using the default input_text 'Born in north-east France, Soyer trained as a'. And there is my adjustment on run.sh parse_input function:
> > <img alt="屏幕截图 2023-10-26 172856" width="989" src="https://user-images.githubusercontent.com/47234697/278282318-158dfe15-9104-4814-accb-7ede7d126b5c.png">
> 
> Can you share the scripts to build the engine and the script to profile the program?
> 
> If you change run.py to profile the program, please remember to add warmup and run more iterations for the program.

Due to unable copy from the server to host PC, the following command is typed by me, maybe some typo.

build command：

```bash
python3 build.py --model_dir /share/hf_models/WizardLM/WizardCoder-Python-13B-V1.0 \
        --dtype float16 \
        --use_gemm_plugin float16 \
        --use_gpt_attention_plugin float16 \
        --enable_context_fmha \
        --parallel_build \
        --world_size 1 \
        --tp_size 1 \
        --pp_size 1 \
        --max_batch_size 64 \
        --output_dir <engine_dir>
```

execute command (add `batch_size` args to batch input)

```bash
python3 run.py --max_output_len 100 \
        --tokenizer_dir /share/hf_models/WizardLM/WizardCoder-Python-13B-V1.0 \
        --engine_dir <engine_dir> \
        --num_beams 1 \
        --batch_size 16
```

Timing code in run.py:

<img width="767" alt="屏幕截图 2023-10-27 134832" src="https://github.com/NVIDIA/TensorRT-LLM/assets/47234697/e17c6993-21d7-4084-b226-0aaef4d69fd4">

**Comment by byshiue** [comment]
@haojiwei Have you tried building different engine for different size of problem? As I mentioned in https://github.com/NVIDIA/TensorRT-LLM/issues/132#issuecomment-1780611848, it is better to build with batch size you want to use.

**Comment by haojiwei** [comment]
> @haojiwei Have you tried building different engine for different size of problem? As I mentioned in [#132 (comment)](https://github.com/NVIDIA/TensorRT-LLM/issues/132#issuecomment-1780611848), it is better to build with batch size you want to use.

The matching batch size engine works well. But what makes me confusing is that `max_batch_size` engine is not compatible with small batch size.

**Comment by byshiue** [comment]
The engine will select the kernel which has best performance on the shape you set. Such kernel may have little worse perf on other shape. We are also investigating further optimization to prevent such issue.

**Comment by byshiue** [comment]
Close this bug because it is in-activate. Feel free to reopen it if needed.
