### ISSUE TITLE
nsys profiling fp16 shows unbelievably short gemms

### ISSUE THREAD

**Issue by shakedregev** [NVIDIA/TensorRT-LLM#1320]
When profiling LLama-70B with `tensorrt_llm.profiler` I'm getting 230 tokens per second in fp8 and 140 in fp16, so far so good. But when I use the nsys profiler, it shows that the gemms are taking roughly 100 microseconds for fp8 (which is expected), but only about 5 for fp16, which is way too fast. Running Mixtral in fp16 gives the same issue (but cannot compare to fp8). Any ideas? I followed the instructions in the example [here](https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/performance_analysis.md) for the profiling.

Here's the example for Mixtral 
`mpirun -n 8 --allow-run-as-root env TLLM_GPTM_PROFILE_START_STOP="0,63,127" ../profile_rank_0.bash python3 ../summarize.py --test_trt_llm --hf_model_dir Mixtral-8x7B-v0.1/ --data_type fp16 --engine_dir Mixtral-8x7B-v0.1/trt_engines/fp16/8gpu/`
![Screenshot 2024-03-19 at 6 02 31 PM](https://github.com/NVIDIA/TensorRT-LLM/assets/35384901/53d58fbb-df2f-4b8e-b574-f42ff78735af)
This is my `profile_rank_0.bash` file:
```
#!/bin/bash

if [ $OMPI_COMM_WORLD_LOCAL_RANK -eq 0 ]; then
  nsys profile -e "NSYS_MPI_STORE_TEAMS_PER_RANK=1" -t cuda,nvtx --gpu-metrics-device=${OMPI_COMM_WORLD_LOCAL_RANK} -c cudaProfilerApi --capture-range-end="repeat[]" --gpu-metrics-frequency=100000 "$@"
else
  "$@"
fi
```

**Comment by byshiue** [comment]
Could you share full nsys report of these two cases?

**Comment by shakedregev** [comment]
It's not letting me attach them here. In any case, I must've been doing something wrong on an initial fp8 run and I'm not able to reproduce these relatively slow times. It still seems fast for both fp16 and fp8, but maybe the kernels are just that good. Closing this, thanks
