### ISSUE TITLE
output difference is too large for baichuan2-13b int8 SmoothQuant

### ISSUE THREAD

**Issue by YihengBrianWu** [NVIDIA/TensorRT-LLM#1322]
### System Info

GPU: A100 SXM 80G * 2
TRT-LLM Version: 0.7.1
TensorRT Version: 9.2.0.post12.dev5
CUDA Version: 12.2

### Who can help?

@Tracin 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Download official baichuan2-13b chat model from hugging face
2. Get TRT engine on 1 GPU
2.1 execute below script to do smooth quant
`python3 hf_baichuan_convert.py -i /mnt/bn/wyh-train/baichuan-inc--Baichuan2-13B-Chat/model -o /mnt/bn/wyh-train/baichuan2_13b_sq_05_1gpu -sq 0.5 --tensor-parallelism 1 --storage-type fp16`
2.2 execute below script to build engine
`python3 build.py --model_version v2_13b --bin_model_dir=/mnt/bn/wyh-train/baichuan2_13b_sq_05_1gpu/1-gpu/ --use_smooth_quant --use_gpt_attention_plugin float16 --per_token --per_channel --output_dir /mnt/bn/wyh-train/baichuan2_13b_sq_05_1gpu_engine`
4. Get TRT engine on 2 GPUs
3.1. execute below script to do smooth quant
`python3 hf_baichuan_convert.py -i /mnt/bn/wyh-train/baichuan-inc--Baichuan2-13B-Chat/model -o /mnt/bn/wyh-train/baichuan2_13b_sq_05_2gpu -sq 0.5 --tensor-parallelism 2 --storage-type fp16`
3.2. execute below script to build engine
`python3 build.py --model_version v2_13b --bin_model_dir=/mnt/bn/wyh-train/baichuan2_13b_sq_05_2gpu/2-gpu/ --use_smooth_quant --use_gpt_attention_plugin float16 --per_token --per_channel --output_dir /mnt/bn/wyh-train/baichuan2_13b_sq_05_2gpu_engine --world_size 2`

### Expected behavior

Expected the output from 1 GPU engine and 2 GPUs engine is quite similar.

### actual behavior

prompt: 你是一个旅游规划者，你对世界上的所有城市都很了解。我要去北京旅游了，北京这个地方怎么样？

1GPU result: ["\n作为一个大语言模型，我可以帮助你更好地了解和探索北京这个美丽的城市！以下是一些建议和景点供您参考：
\n\n1. 故宫（Forbidden City）: 这座位于市中心的宫殿群是明清两代皇家的居所，拥有丰富的历史和文化遗产。您可以参观皇帝的生活场所、皇家宝物和精美的建筑艺术。
\n\n2. 天安门广场（Tiananmen Square）: 这个世界上最大的城市广场之一是您在北京旅行必游之地。在这里，您可以欣赏到人民英雄纪念碑、毛主席纪念堂和国家博物馆等标志性建筑。
\n\n3. 长城（Great Wall of China）: 北京附近有多处长城景区，如八达岭、慕田峪和马仁山等地。登上长城，俯瞰壮丽的山川景色，感受古代中国的军事防御工程。
\n\n4. 南锣鼓巷（Nan Luogu Lane）: 这是北京市内一条充满历史和文化氛围的古老胡同。漫步在狭窄的街道上，品尝当地的特色小吃，购买手工艺品，体验传统的北京生活。
\n\n5. 颐和园（Summer Palace）: 这是一座融合了皇家园林艺术的皇家园林，以昆明湖为中心，拥有美丽的湖泊、桥梁、亭台楼阁和各种植物景观。
\n\n6. 国家大剧院（National Centre for the Performing Arts）: 在欣赏一场精彩的演出之前，可以拍照留念这座现代建筑的杰作。
\n\n7. 王府井步行街（Wangfujing Street）: 这里是北京的购物天堂，琳琅满目的商店、餐馆和市场让您流连忘返。此外，还可以品尝到各种美食和小吃。
\n\n8. 鸟巢和水立方（Bird's Nest and Water Cube）: 这两座具有代表性的奥运场馆分别用于2008年北京奥运会的主体育场和游泳中心。它们都是现代建筑和工程设计的大师之作。
\n\n9. 798艺术区（798 Art District）: 这是一个充满创意的艺术社区，汇集了许多画廊、艺术家工作室和文化活动。这里也是摄影、雕塑和其他艺术品的天堂。
\n\n这些只是北京众多旅游景点中的一部分。希望您在游览这座城市时能够度过一个愉快的旅程！如果您需要更多关于行程安排或景点的信息，请随时向我咨询。
"]
2GPU result: ['\n作为一个大语言模型，我可以帮助你找到最好的餐厅和最好的服务员。我可以提供最准确的信息和最好看的信息。']

prompt: 你是一个旅游规划者，你对世界上的所有城市都很了解。我要去上海旅游了，能和我介绍一下上海这座城市么？包括不限于人文，地理，美食，历史等等。
1GPU result: ['\n当然可以！上海是中国的一个直辖市，位于中国的东部沿海地区，是中国的经济、金融、文化和航运中心。以下是关于上海的详细介绍：
\n\n1. 人文：上海市常住人口约为2400万，拥有丰富的多元文化。这里的居民来自全国各地，因此你可以在这里品尝到各地的特色美食和感受不同的地方风情。此外，上海还是中国最大的移民城市之一，吸引了大量外国人和国际人士前来工作和生活。
\n\n2. 地理：上海地处长江三角洲平原，地势平坦。市区位于黄浦江两岸及其支流苏州河沿岸。上海的气候属于亚热带湿润季风气候，四季分明，春季温暖湿润，夏季炎热多雨，秋季凉爽干燥，冬季寒冷多云。
\n\n3. 美食：上海菜是中国八大菜系之一，以清淡、鲜美、讲究烹饪技巧而著称。一些著名的上海小吃有南翔小笼包、生煎包、油墩子等。此外，由于上海是一个国际化大都市，你还可以在这里品尝到世界各地的美味佳肴。
\n\n4. 历史：上海的历史可以追溯到公元前5世纪。公元7世纪，上海成为渔村。到了宋代，这里逐渐发展成为一个重要的港口。明清时期，上海逐渐成为长江流域的一个重要商业和文化中心。鸦片战争后，上海沦为列强租界地，成为了中西文化交流的重要桥梁。新中国成立后，上海成为中国的一个直辖市，经济发展迅速，如今已成为全球一线城市之一。
\n\n在上海旅行时，你可以参观外滩的百年建筑群、豫园的古园林景观、南京路步行街的时尚购物区以及上海迪士尼乐园等特色景点。希望这些信息对您的上海之旅有所帮助！']
2GPU result: ['']

### additional notes

2GPUs engine sometime returns a very short sentence, or empty result, or repeat same phrase again and again until reach the max_new_tokens limit.

**Comment by Tracin** [comment]
Looks like you are using a stale version of TRTLLM, please try with the latest main branch.
