### ISSUE TITLE
[Question] SmoothQuant + int8 kv cache 

### ISSUE THREAD

**Issue by Hongbosherlock** [NVIDIA/TensorRT-LLM#1330]
I want to try smoothquant+ int8 kv cache on Llama2-13B,  Can these two be used together? 
such as:
```
python3 convert_checkpoint.py --model_dir /llama-models/llama-7b-hf  \
			      -—output_dir /tmp/tllm_checkpoint_1gpu_sq \
                              -—dtype float16 \ 
			      --smoothquant 0.5 \
                              --int8_kv_cache
```
If I only use `--smoothquant 0.5`,  when computing $K = W_k * X$,  it's INT8 GEMM, the same applies to V.
 Afterward, for the storage precision of the kv cache, is it **int8 or fp16**? I'm unsure when the dequantization occurs.

```[tasklist]
### Tasks
```

**Comment by byshiue** [comment]
These two features could be used together. The output of SQ gemm is FP16, and they are quantized in attention plugin and saved into kv cache buffer.

**Comment by Hongbosherlock** [comment]
> These two features could be used together. The output of SQ gemm is FP16, and they are quantized in attention plugin and saved into kv cache buffer.

Is there any code pointers?

Do you mean that when only using `--smoothquant`, the kv cache is saved in `fp16`, 
when using `--smoothquant` and `--int8_kv_cache` together , the kv cache is saved in `int8`?

**Comment by Hongbosherlock** [comment]
> These two features could be used together. The output of SQ gemm is FP16, and they are quantized in attention plugin and saved into kv cache buffer.

What I'm curious about is whether using `--smoothquant` and `--int8_kv_cache` simultaneously provides performance improvement compared to using `--smoothquant` alone, or if the effect is exactly the same?

I think that `smoothquant`  may include the effect of `int8_kv_cache`:

https://github.com/NVIDIA/TensorRT-LLM/blob/80bc07510ac4ddf13c0d76ad295cdb2b75614618/examples/llama/hf_llama_convert.py#L227-L231

**Comment by Hongbosherlock** [comment]
@byshiue @Tracin Could you please confirm if my understanding is correct?

**Comment by byshiue** [comment]
> Do you mean that when only using --smoothquant, the kv cache is saved in fp16,
> when using --smoothquant and --int8_kv_cache together , the kv cache is saved in int8?

Yes, that's correct.
