### ISSUE TITLE
FP8 quantization of Llama 70B fails with OOM 

### ISSUE THREAD

**Issue by ttim** [NVIDIA/TensorRT-LLM#1331]
### System Info

- I've tried both H100x1 and H100x2

### Who can help?

@Tracin

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Quantize Llama 70B model with `LLaMAForCausalLM.from_hugging_face(
        model_dir, dtype="bfloat16", quant_mode=QuantMode.from_description(use_fp8_qdq=True, use_fp8_kv_cache=True), mapping=Mapping()
    ).`
2. It fails with CUDA's OOM, during `export_model_config` in ammo package

### Expected behavior

Successful quantization of Llama 70B model

### actual behavior

Fails with OOM

### additional notes

I've tried both TP=2 and TP=1 version, on both H100x1 and H100x2 machines. Thank you!

**Comment by QiJune** [comment]
A BF16 LLaMA 70B  is about 140G, a FP8 LLaMA 70B is about 70G. So, the peak GPU memory consumption when doing FP8 quantizaton is more than 210G (there is also some activation memory occupation when doing calibration).

So we need a node with 4* H100 or 8 * H100 to run the quantization command. After quantization, 2 GPUs are okay to for building and run.

**Comment by chrjxj** [comment]
> A BF16 LLaMA 70B is about 140G, a FP8 LLaMA 70B is about 70G. So, the peak GPU memory consumption when doing FP8 quantizaton is more than 210G (there is also some activation memory occupation when doing calibration).
> 
> So we need a node with 4* H100 or 8 * H100 to run the quantization command. After quantization, 2 GPUs are okay to for building and run.

it will be nice to document this in the https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/quantization/README.md file
users could pick up a right server to srart with...

**Comment by QiJune** [comment]
Yes, we update the doc here: https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/llama#fp8-post-training-quantization

**Comment by MrD005** [comment]
@QiJune i am using 4xH100 and doing llama-2 34b fp8 quantization but still i am getting OOM error
