### ISSUE TITLE
What is prequant_scaling_factor?

### ISSUE THREAD

**Issue by chenzhengda** [NVIDIA/TensorRT-LLM#1334]

**Comment by byshiue** [comment]
It is scale for input activation used by SmoothQuant. You can see more details in SmoothQuant paper.

**Comment by chenzhengda** [comment]
@byshiue  Do you mean the per-channel smoothing factor?

**Comment by byshiue** [comment]
They are scales for "weights" or "activation", which are independent to "per channel" or "per tensor".

**Comment by chenzhengda** [comment]
Thanks a lot. And I found many tools and scripts for smoothquant in the code repository, which one should I use?
- https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/llama/convert_checkpoint.py 
- https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/quantization/README.md
- https://github.com/NVIDIA/TensorRT-LLM/tree/main/tensorrt_llm/quantization
