### ISSUE TITLE
Mixtral MoE engine errors out on 8k context length

### ISSUE THREAD

**Issue by vnkc1** [NVIDIA/TensorRT-LLM#1339]
### System Info

p4d (8 x A100 40GB GPUs)

### Who can help?

@byshiue 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Install 0.8.0 and create Mixtral Bf16 engine with max input length as 8192 and max batch size as 16 (TP-8).

`trtllm-build --checkpoint_dir ~/bf16-tp8  --output_dir ~/bf16-tp8-engine --gpt_attention_plugin bfloat16 --gemm_plugin bfloat16 --remove_input_padding enable --paged_kv_cache enable --context_fmha enable --workers 8 --max_batch_size 16 --max_input_len 8192 --max_output_len 512`

Run a workload of input tokens = 8000, max output tokens = 80, batch size = 4

### Expected behavior

Engine runs fine

### actual behavior

terminate called after throwing an instance of 'tensorrt_llm::common::TllmException'
what(): [TensorRT-LLM][ERROR] Assertion failed: elts_per_rank % elts_per_thread == 0 (

### additional notes

N/A

**Comment by mickaelseznec** [comment]
This is caused by using TP with the MoE router. Which has been removed on newer version for performance reasons anyway #1091 

I've tested on main branch and didn't reproduce the issue. Please re-open if you encounter another issue, thanks!

**Comment by ghost** [comment]
@mickaelseznec What would be your recommendation on setup configuration for Mixtral 8x7B, on a p4d (8x40GB) if I'm not using Tensor Parallelism?

**Comment by mickaelseznec** [comment]
So ideally you would keep TP with a version that works, so either:
- using TRT-LLM's main branch
- monkey-patching v0.8 with the fix provided in #1091 
- waiting for next stable version

You can also disable `custom_allreduce` at `trtllm-build` time.
