### ISSUE TITLE
Sample Config Not Working, example temperature

### ISSUE THREAD

**Issue by Tushar-ml** [NVIDIA/TensorRT-LLM#1341]
### System Info

GPU: A100 (40 GB)

### Who can help?

@byshiue @kai

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

set different temperature but will see no effect

### Expected behavior

it should result different output

### actual behavior

when setting different sample configuration like temperature, the output seems to come same, no difference word to word

### additional notes

try to run llama examples with temperature setting as well

**Comment by byshiue** [comment]
Please share the steps to reproduce the issue. Also, please check that you really enable the sampling instead of using greedy search because temperature does not bring effect on greedy search.

**Comment by Tushar-ml** [comment]
Hi @byshiue I have resolved this issue, top_k and top_p by default were 1 and 0, which makes temperature redundant.

Thanks for this great repo
