### ISSUE TITLE
Cpp benchmark

### ISSUE THREAD

**Issue by BigFaceBoy** [NVIDIA/TensorRT-LLM#1348]
What's the difference between gptManagerBenchmark  and  gptSessionBenchmark?
For example, I want to test Qwen7B， which benchmark should I choose? And is there perfomance difference?

**Comment by byshiue** [comment]
`gptManagerBenchmark` is used to run benchmark for inflight batching, `gptSessionBenchmark` is used to run benchmark of static batching. You could select one of them depending on your requirement.
