### ISSUE TITLE
Is int8(weights only or smooth qunant) support bert?

### ISSUE THREAD

**Issue by zhangxin81** [NVIDIA/TensorRT-LLM#1350]
Thansk for such a great job. And, I wander Is int8(weights only or smooth qunant) support bert?

**Comment by Hongbosherlock** [comment]
I have the same question.

**Comment by Hongbosherlock** [comment]
@byshiue @Tracin  can you please help me check this ? https://github.com/NVIDIA/TensorRT-LLM/issues/1330

**Comment by byshiue** [comment]
Hi, @zhangxin81. Sorry for late response. TRT-LLM does not support int8 weight only or smooth quant on bert now.
