### ISSUE TITLE
llama2 with beam search has large difference result

### ISSUE THREAD

**Issue by FourierTf** [NVIDIA/TensorRT-LLM#1352]
### System Info

GPU: A100 SXM 80G
TRT-LLM Version: 
    tensorrt-llm 0.9.0.dev2024020600
    tensorrt-llm 0.9.0.dev2024022700
TensorRT Version: 9.2.0.post12.dev5
CUDA Version: 12.2

### Who can help?

@byshiue

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

1.create engine
```
python convert_checkpoint.py --model_dir /tensorrt_llm/llama_ec --output_dir /tensorrt_llm/beams --dtype bfloat16  
trtllm-build --checkpoint_dir /tensorrt_llm/beams --output_dir /tensorrt_llm/engine_beam --gpt_attention_plugin bfloat16 - --max_beam_width 5 --max_batch_size 1 --max_input_len 100
```
2.model inference
```
python3 ec_run.py --max_output_len=50 --tokenizer_dir=/tensorrt_llm/tokenizer/ --engine_dir /tensorrt_llm/engine_beam/ --num_beams=5  --temperature=0.1 --input_file test_data.txt
```

### Expected behavior

 HF and TRT difference is less than 1%

### actual behavior

trtllm 0.9.0.dev2024020600 top1 is less 3.8% than HF result，top5 is less 4.4% than HF result.
trtllm 0.9.0.dev2024022700 top1 is less 20.8% than HF result，top5 is less 4% than HF result.

when use `--gemm_plugin disable` `--context_fmha disable` `--context_fmha_fp32_acc enable`,trtllm 0.9.0.dev2024020600 top1 is less 1.1% than HF result，top5 is less 2% than HF result.

### additional notes

The significant decline in version 0.9.0.dev2024022700 is confusing, and any suggestions for improving accuracy？

**Comment by byshiue** [comment]
How about adding `--gemm_plugin disable --context_fmha disable --context_fmha_fp32_acc enable` in 2024022700 version?

**Comment by FourierTf** [comment]
> How about adding `--gemm_plugin disable --context_fmha disable --context_fmha_fp32_acc enable` in 2024022700 version?

when use `--gemm_plugin disable --context_fmha disable --context_fmha_fp32_acc enable` in trtllm 0.9.0.dev2024022700, top1 is less 14.5% than HF result，top5 is less 2.4% than HF result.

**Comment by JohnGiorgi** [comment]
@FourierTf When you run the model with HuggingFace, what is the `early_stopping` parameter of `.generate()` set to? I am also seeing large differences in performance with a fine-tuned Mistral v0.1 7b and am starting to suspect its partially due to differences in `early_stopping` between HF and TRT-LLM (see [here](https://github.com/NVIDIA/TensorRT-LLM/issues/1370)).

**Edit: disabling early stopping brings results from TRT-LLM much closer to HF.**

**Comment by FourierTf** [comment]
> @FourierTf When you run the model with HuggingFace, what is the `early_stopping` parameter of `.generate()` set to? I am also seeing large differences in performance with a fine-tuned Mistral v0.1 7b and am starting to suspect its partially due to differences in `early_stopping` between HF and TRT-LLM (see [here](https://github.com/NVIDIA/TensorRT-LLM/issues/1370)). **Edit: disabling early stopping brings results from TRT-LLM much closer to HF.**

thank you. I use default `early_stopping` parameter and will try disable early stopping parameter
