### ISSUE TITLE
starcoder2 has different outputs than original model

### ISSUE THREAD

**Issue by tonylek** [NVIDIA/TensorRT-LLM#1354]
### System Info

A100-40gb machine
trtllm 0.9dev from the current main branch

### Who can help?

@kaiyux 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

1. Compile starcoder2-3b based on the Readme file in examples/gpt.
2. Infer with the input: 'def largest_divisor(n: int) -> int:\n    """ For a given number n, find the largest number that divides n evenly, smaller than n\n    >>> largest_divisor(15)\n    5\n    """'
3. Do the same inference with the huggingface model.
4. You can use this code for example.
```
m_starcoder = AutoModelForCausalLM.from_pretrained('bigcode/starcoder2-3b/')
res = m_starcoder.generate(inputs=torch.LongTensor([[610,22936,100,526,22282,45,115,63,648,46,984,648,63,303,1547,2643,331,2716,1470,329,49,2309,341,22936,1470,708,4469,13014,329,4462,651,49,14788,2806,329,303,8257,22936,100,526,22282,45,54,58,46,303,244,58,303,1547]]),max_new_tokens=25, return_dict_in_generate=True, output_scores=True, eos_token_id=0)
```
### Expected behavior

```
def largest_divisor(n: int) -> int:
    """ For a given number n, find the largest number that divides n evenly, smaller than n
    >>> largest_divisor(15)
    5
    """
    for i in range(n, 1, -1):
        if n % i == 0:
            return
```
### Actual behavior

```
def largest_divisor(n: int) -> int:
    """ For a given number n, find the largest number that divides n evenly, smaller than n
    >>> largest_divisor(15)
    5
    """
    for i in range(1, n + 1):
        if n % i == 0:
            return i
```
### Additional notes

In addition is model is also pretty slow compared to running it on a framework such as tgi.
Not sure what is the reason for that, usually running on trtllm works much faster for me

**Comment by byshiue** [comment]
For the different resutls between HF and TRT-LLM, the results of TRT-LLM look reasonable and it is expected that HF and TRT-LLM might generate different results because different kernel implementation. So, it is not a bug.

For performance issue, could you share the number you observe and the steps to reproduce?

**Comment by tonylek** [comment]
Hi, thank you for your response. I agree that TRT-LLM might generate different results because different kernel implementation.
But this is a case where the output of TRT-LLM is completely wrong and this is not the only case. I ran HumanEval (python) on the hf implementation and on the TRT-LLM implementation and the difference was:
hf - 31.05
trt-llm - 14.9
This is an enormous degradation, I don't believe this is only because of kernel impl.

Regarding the performance issue, I reran my benchmarks using the code that was released yesterday and it seems more reasonable. But I wonder if there is a reason why it is not implemented more like the llama model family since it is with GQA and more similsr to llama/ mistral than to starcoder1 and gpt. Wouldn't it be faster?

**Comment by byshiue** [comment]
Could you share the reproduced steps to show the score differences? You could try using the `summarize.py` or `mmlu.py`. 

We use GPT because the model architecture of starcoder is same to GPT. When the model uses GQA, GPT will also use GQA kernel automatically.

**Comment by tonylek** [comment]
I found the problem, the rotary config base was wrong, it was missing in the conversion from the hf ckpt.
I opened a PR about it: https://github.com/NVIDIA/TensorRT-LLM/pull/1403

**Comment by byshiue** [comment]
Close the issue because the issue should be fixed in latest main branch. Feel free to reopen it if needed.
