### ISSUE TITLE
When the input of llava is long, the output result is abnormal

### ISSUE THREAD

**Issue by zh0ngtian** [NVIDIA/TensorRT-LLM#1355]
### System Info

- CPU architecture: x86_64
- CPU/Host memory size: 2T
- GPU name: A800-SXM4-80GB
- CUDA version: 12.2
- TensorRT-LLM tag: v0.8.0
- NVIDIA driver version: 535.129.03

### Who can help?

When I use long input in example https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/multimodal#llava-and-vila, the output is abnormal, like:
`ation\nation\n\nation\n\n\n\n\n\n1\n1\n1\n1\n1\n\nion,\nion\nation\nation\n1\n1\n1\n1\n1\n1\n1\n1\n1\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n1\n1`

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. convert model

```bash
python3 convert_checkpoint.py \
        --model_dir /path/to/llava-1.5-7b-hf \
        --output_dir $tmp_dir  \
        --dtype float16

trtllm-build \
        --checkpoint_dir $tmp_dir \
        --gpt_attention_plugin float16 \
        --gemm_plugin float16 \
        --context_fmha enable \
        --max_batch_size 1 \
        --max_input_len 5120 \
        --max_output_len 1024 \
        --output_dir $output_dir \
        --max_multimodal_len 5760
```

2. modify `run.py` to set long inputs:

put these codes in https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/multimodal/run.py#L155 

```python
repeat_times = 8
visual_features = visual_features.repeat(1, repeat_times, 1)
visual_atts = visual_atts.repeat(1, repeat_times)
```

3. run `build_visual_engine.py`

4. run `run.py`

```bash
python3 run.py \
    --max_new_tokens 1024 \
    --input_text "Please describe this picture" \
    --visual_engine_dir visual_engines/llava-1.5-7b-hf \
    --hf_model_dir /path/to/llava-1.5-7b-hf \
    --llm_engine_dir $output_dir \
    --decoder_llm
```

### Expected behavior

When `repeat_times` is 7 or less, the result is normal:

`The image features a large fountain with a water spout, located near a building. The fountain is situated in front of a lion statue, which is situated on a pedestal. The scene is set against a backdrop of a city skyline, creating a picturesque view.\n\nThere are several people in the scene, with some standing near the fountain and others scattered around the area. A boat can be seen in the water, adding to the overall ambiance of the scene.`

### actual behavior

When `repeat_times` is 8 or bigger, the result is abnormal:

`ation\nation\n\nation\n\n\n\n\n\n1\n1\n1\n1\n1\n\nion,\nion\nation\nation\n1\n1\n1\n1\n1\n1\n1\n1\n1\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n1\n1`

### additional notes

The cause of the problem seems to be that an internal limit has been exceeded, but the parameters controlling this limit are not visible externally.

**Comment by amukkara** [comment]
@zh0ngtian We are exceeding maximum context size of llava-1.5-7b (4096) when `repeat_times > 7`. Can you use a different model with larger context size?

**Comment by YongliangMiao** [comment]
this is my code, and I am in the same situation. Llava code provided in huggingface is really hard to put up with...........
  conversation = [ {
                        "role": "user",
                        "content": [
                            {"type": "text", "text": prompt},
                            {"type": "image","image":image},
                            ],
                        },]
                    chat_template='<|im_start|>user\n<image>\n<your_text_prompt_here><|im_end|><|im_start|>assistant\n"'
                    precoessed_prompt = processor.apply_chat_template(conversation, add_generation_prompt=True,chat_template=chat_template)
                    print(precoessed_prompt)
                    inputs = processor(prompt, return_tensors="pt",truncation=True).to("cuda")
                    # autoregressively complete prompt
                    output=processor.decode(model.generate(**inputs, max_new_tokens=max_new)[0], skip_special_tokens=True)
