### ISSUE TITLE
Invalid batch dimension of Tensorrt llm Engine

### ISSUE THREAD

**Issue by luxiushu2023** [NVIDIA/TensorRT-LLM#136]
Bloom 7b model example:

**# int8 weight only + int8 kv cache**
`python3 hf_bloom_convert.py -i ./bloomz-7b -o ./bloom_7b_kv --calibrate-kv-cache -t float16`

**# Build model with both INT8 weight-only and INT8 KV cache enabled**
```
python3 TensorRT-LLM/examples/bloom/build.py --bin_model_dir=./bloom_7b_kv/1-gpu \
--output_dir ./bloom_7b_kv_models/tensorrt_llm/1/ \
--dtype float16 \
--use_gpt_attention_plugin float16 \
--use_gemm_plugin float16 \
--use_layernorm_plugin \
--int8_kv_cache \
--use_weight_only
```

**#start triton inferece server**
/opt/tritonserver/bin/tritonserver --model-repository ./bloom_7b_kv_models

**#perf_analyzer with batch size 8 failed, but batch size 1 is normal**
```
perf_analyzer -m tensorrt_llm -x 1 \
-b 8 \
-i gRPC \
-u "localhost:8001" \
--shape input_ids:200 \
--shape input_lengths:1 \
--shape request_output_len:1 \
--measurement-interval=10000 \
--input-data /share/bloom_perf_data \
--concurrency-range 2
```

**#got invalid batch error**
```
Thread [122] had error: Encountered error for requestId 1100661314: Cannot process new request: Expected batch dimension to be 1 for each request for input tensor input_ids

Thread [123] had error: Encountered error for requestId 112805733: Cannot process new request: Expected batch dimension to be 1 for each request for input tensor input_ids
```

**Any advise for this problem?**

**Comment by jdemouth-nvidia** [comment]
Hi @luxiushu2023 ,

Have you tried running the problem with `BS == 8` using the Triton server directly (i.e. without `perf_analyzer`)? 

Thanks,
Julien

**Comment by luxiushu2023** [comment]
when  I try perf_analyer with BS==8, the error still the same, but with gpt benchmark tool, the result is normal, may be this is perf_analyer's bug?

```
python3 ./TensorRT-LLM/benchmarks/python/benchmark.py  \
-m "bloom_7b" \
--engine_dir ./tensorrtllm_models/bloom_7b_kv_models/tensorrt_llm/1/ \
--batch_size "1;8" \
--input_output_len "200,200"

```

**Comment by jdemouth-nvidia** [comment]
That's what I would suspect.

**Comment by uppalutkarsh** [comment]
Hi @luxiushu2023,

[This](https://github.com/triton-inference-server/tensorrtllm_backend/blob/release/0.5.0/tools/gpt/identity_test.py) script can help you compute latency and throughput. 

Please note this will run perf experiments on `tensorrt_llm`, not end-to-end `ensemble`. 

Can you try once and let us know if it solves the purpose, you can explore `end_to_end_test.py` too depending on your triton model repo and deployment type (decoupled).

**Comment by luxiushu2023** [comment]
Modify the input data set (prompts input len=200, and specify output len =200  ) end_to_end_test.py
```
    text ='.....'
    contents = generate_contents(text)
    output_len = 200
    for i in range(10):
        prompts.append(contents)
        output_lens.append(output_len)
```
Then start triton inference server. with batch size=8, and different concurrency , the result of  end_to_end_test.py  like this:
```
CUDA_VISIBLE_DEVICES=5 python3 ./tensorrtllm_backend/tools/inflight_batcher_llm/end_to_end_test.py  -u "localhost:8001" -i 'grpc' -c 1 --max_input_len 200 
[INFO] Start testing on 10 prompts.
[INFO] Functionality test succeed.
[INFO] Warm up for benchmarking.
[INFO] Start benchmarking on 10 prompts.
[INFO] Total Latency: 3992.67 ms

CUDA_VISIBLE_DEVICES=5 python3 ./tensorrtllm_backend/tools/inflight_batcher_llm/end_to_end_test.py  -u "localhost:8001" -i 'grpc' -c 4 --max_input_len 200 
[INFO] Start testing on 10 prompts.
[INFO] Functionality test succeed.
[INFO] Warm up for benchmarking.
[INFO] Start benchmarking on 10 prompts.
[INFO] Total Latency: 3969.616 ms

CUDA_VISIBLE_DEVICES=5 python3 ./tensorrtllm_backend/tools/inflight_batcher_llm/end_to_end_test.py  -u "localhost:8001" -i 'grpc' -c 128 --max_input_len 200  
[INFO] Start testing on 10 prompts.
[INFO] Functionality test succeed.
[INFO] Warm up for benchmarking.
[INFO] Start benchmarking on 10 prompts.
[INFO] Total Latency: 3968.909 ms
```

[1] How calc the tokens per secs,   (output len 200 * 10)/Total latency 3968.909  = 2000/3.96890 = 503 tokens_per_secs , is that right?

[2] Another question is with different concurrency, the total latency are almost the same?

**Comment by luxiushu2023** [comment]
While increase total promts ,the through out is increase too.

CUDA_VISIBLE_DEVICES=5 python3 ./tensorrtllm_backend/tools/inflight_batcher_llm/end_to_end_test.py  -u "localhost:8001" -i 'grpc' -c 1 --max_input_len 200 --dataset  "llama2" 
[INFO] Warm up for benchmarking.
[INFO] Start benchmarking on 80 prompts.
[INFO] Total Latency: 20995.617 ms

Through out:（80*200)/20.995617 = 762.  tokens per secs , is neer with benchmark result with same batch size(8) 

thanks @jdemouth-nvidia @uppalutkarsh
