### ISSUE TITLE
LLaVA has low performance in int4 quantization

### ISSUE THREAD

**Issue by AlexanderKomarov** [NVIDIA/TensorRT-LLM#1361]
### System Info

CPU: x86_64
GPU: A10G
CUDA Version: 12.3
Driver Version: 535.54.03
TensorRT-LLM version: 0.8.0 installed from pypi.nvidia.com
Python: 3.10
  

### Who can help?

@Tracin @kaiyux 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I tested LLaVA model from this [example LLaVA](https://github.com/NVIDIA/TensorRT-LLM/tree/v0.8.0/examples/multimodal#llava). I compared the performance LLM with passing visual embedding fp16 vs int4 by `run.py`.

FP16
TensorRT-LLM LLM latency: 0.18526424407958986 sec
INT4
TensorRT-LLM LLM latency: 0.153300039768219 sec

So I got only 20% acceleration. 

But when I tried to compare the performance only LLM without passing visual embedding fp16 vs int4. I managed to get speed up about 4x.

### Expected behavior

I expected to get an acceleration about 4x.

### actual behavior

I got only 20% acceleration.

### additional notes

Is it expected behavior?

**Comment by byshiue** [comment]
Might you run the profilers by nsight systems to help comparing? The scripts are like
```bash
nsys profile -o tmp pythone run.py
```

**Comment by AlexanderKomarov** [comment]
sure

[Uploading llava_int4_vs_fp16.zip…]()

**Comment by AlexanderKomarov** [comment]
sure, 

[llava_int4_vs_fp16.zip](https://github.com/NVIDIA/TensorRT-LLM/files/14822777/llava_int4_vs_fp16.zip)

**Comment by byshiue** [comment]
In your case, the context phase is much longer than generation phase, and int4 only brings benefit for generation phase because the dequantization on context phase is expensive. So, in your case, the 20% acceleration is expected.

If you use shorter input length and longer output length, like input length 128 + output length 1024, you should observe more speedup because such case is more friend for int4.

**Comment by AlexanderKomarov** [comment]
@byshiue thank you a lot for the explanation.
