### ISSUE TITLE
NVIDIA AMMO documentation

### ISSUE THREAD

**Issue by fedem96** [NVIDIA/TensorRT-LLM#1368]
Is there any official documentation of NVIDIA AMMO toolkit? If so, where is it?

In particular, I'd be interested in documentation about:
- implemented features
- supported quantization techniques for each model type
- changelog between versions

@Tracin @juney-nvidia

**Comment by juney-nvidia** [comment]
@RalphMao do you have any comments on this ask? :)

**Comment by dmitrymailk** [comment]
Same. How I can find source code of this library? I want to write custom quantization pipeline for encoder-decoder models like T5.

**Comment by yao-matrix** [comment]
same question here.

**Comment by puppetm4st3r** [comment]
x2

**Comment by ChristianPala** [comment]
Hi folks!
Are there updates on the docs?

**Comment by lix19937** [comment]
+1

**Comment by RalphMao** [comment]
Hi all, thank you for your interest. The AMMO toolkit has been renamed to "TensorRT model optimizer" and the documentation is available at https://nvidia.github.io/TensorRT-Model-Optimizer/ . Examples related with Model Optimizer is available at https://github.com/NVIDIA/TensorRT-Model-Optimizer?tab=readme-ov-file

**Comment by RalphMao** [comment]
> Same. How I can find source code of this library? I want to write custom quantization pipeline for encoder-decoder models like T5.

The library is available on PyPi, with source open (instead of open source). You can access most of the files but some files doesn't have the approval for open source (yet)

**Comment by ashwin-js** [comment]
Hi @dmitrymailk , I am also exploring ways to run 4bit quantized encoder - decoder model in tensorrt-llm. Where you able to make any progress on that front ?

**Comment by nv-guomingz** [comment]
Hi @fedem96 , plz feel free to reopen it if needed.
