### ISSUE TITLE
Can I use the docker image of pytorch 23.03 to compile & run

### ISSUE THREAD

**Issue by wrfgup** [NVIDIA/TensorRT-LLM#137]
I want to run TensorRT-LLM on a docker image with ubuntu20, could I choose nvcr.io/nvidia/pytorch:23.03-py3 as my base image to compile & run

**Comment by byshiue** [comment]
You can take a try, but we have not verified.

**Comment by jdemouth-nvidia** [comment]
TensorRT-LLM was released and tested with the 23.08 container. It's ok to test with 23.03 but that's not supported, in the sense that we are not validating TensorRT-LLM with that container.
