### ISSUE TITLE
Support for HF early_stopping heuristic?

### ISSUE THREAD

**Issue by JohnGiorgi** [NVIDIA/TensorRT-LLM#1370]
Hi! Both HF and TRT-LLM support an `early_stopping` argument. HF's implementation supports three options (`True`, `False`, `"never"`) defaulting to `False`. Where [their docs describe it as](https://huggingface.co/docs/transformers/en/main_classes/text_generation#transformers.GenerationConfig.early_stopping)

> `False`: where an heuristic is applied and the generation stops when is it very unlikely to find better candidates. 

Is there any way to get this behavior in TRT-LLM? I can see that I can set `early_stopping` to an int, which I think maps to HF accordingly:

- TRT `>0` --> HF `True`
- TRT `0` --> HF `"never"`

I am asking because I am noticing big differences in model outputs between HF and TRT-LLM and I am starting to suspect this difference in early stopping behavior is part of the reason.

**Comment by byshiue** [comment]
Thank you for the report. We are working on that. We will update here when the feature is completed.

**Comment by JohnGiorgi** [comment]
Awesome! Thanks. I confirmed for me that disabling early stopping brings results with TRT-LLM much closer to HF using a fine-tuned Mistral v0.1 7B model.

It might be worth warning folks about this somewhere in the documentation as anyone using beam search who doesn't realize that TRT-LLM and HF have different default arguments for early stopping is going to get burned. Another option is to disable early stopping by default to be more in line with HF defaults.

**Comment by byshiue** [comment]
The latest example https://github.com/NVIDIA/TensorRT-LLM/blob/850b6fa1e710d25769f2b560d897d2bd424a645e/examples/summarize.py#L277 should have such options. It still has few bugs and would be fixed in the update of this week.

**Comment by JohnGiorgi** [comment]
> The latest example https://github.com/NVIDIA/TensorRT-LLM/blob/850b6fa1e710d25769f2b560d897d2bd424a645e/examples/summarize.py#L277 should have such options. It still has few bugs and would be fixed in the update of this week. 

Awesome, thank you!
