### ISSUE TITLE
ModelRunner cannot specify GPU

### ISSUE THREAD

**Issue by Gforky** [NVIDIA/TensorRT-LLM#1375]
### System Info

I encountered a problem specifying the GPU when using the Python API of TensorRT-LLM v0.7.0. When I load the engine using ModelRunner.from_dir, it defaults to using the GPU with index 0, even if I use the CUDA_VISIBLE_DEVICES parameter to specify the GPU. Is there any way to specify the GPU?

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

1. Build a tensorrt engine, in any precision.
2. Load model using Triton-Inference-Server's python backend, load engine using ModelRunner.from_dir.
3. Serving with two instances using 2 GPUS.

### Expected behavior

Each GPU serving one inference instance.

### actual behavior

All inference instances are using GPU 0.

### additional notes

Using Tensorrt-LLM v0.7.0

**Comment by bnuzhanyu** [comment]
I did not test v0.7.0, but v0.7.1 is OK.
Do you use CUDA_VISIBLE_DEVICES like this?
CUDA_VISIBLE_DEVICES=1 python xxx 
If you set env in your python code, I think you should make sure the code is running before "import tensorrt_llm".

**Comment by Gforky** [comment]
> I did not test v0.7.0, but v0.7.1 is OK. Do you use CUDA_VISIBLE_DEVICES like this? CUDA_VISIBLE_DEVICES=1 python xxx If you set env in your python code, I think you should make sure the code is running before "import tensorrt_llm".

Yes！That's the issue, I should set CUDA_VISIBLE_DEVICES before import tensorrt_llm
, thank you.
