### ISSUE TITLE
How to add a custom simple network and be able to use TensorRT-LLM to generate an engine and infer

### ISSUE THREAD

**Issue by 1757525671** [NVIDIA/TensorRT-LLM#1376]
### System Info

None

### Who can help?

@juney-nvidia @kaiyux
How can I add a custom simple network and be able to use the TensorRT-LLM generation engine and infer, for example, the network is self.attention with random weights and the input is random? Can you provide a sample, thank you.

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

None

### Expected behavior

None

### actual behavior

None

### additional notes

None

**Comment by byshiue** [comment]
This document https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/workflow.md explain the workflow of TensorRT-LLM, hoping it is helpful.
