### ISSUE TITLE
[Question] question about the pad_token in LLaVA, why set it  same as eos_token?

### ISSUE THREAD

**Issue by DefTruth** [NVIDIA/TensorRT-LLM#1381]
### System Info

The pad_token of LLaVA in TRTLLM is different with LLaVA-HF and Official LLaVA repo, why set the LLaVA pad_token  same as the eos_token in TRTLLM? 
```python  
 self.tokenizer.padding_side = "right"
 # Official LLaVA repo: pad_token_id   =0,     pad_token     =<unk>,   vocab_size =32000, 0~31999
 # After convert to HF: pad_token_id   =32001, pad_token     =<pad>
 #                      image_token_id =32000, special_token =<image>, vocab_size =32064=32001+pad_shape
 # The LLaVA in TRTLLM: pad_token_id   =2,     pad_token     =</s>,    vocab_size =32064               
 self.tokenizer.pad_token = self.tokenizer.eos_token  # why?
```
some codes: 
```bash  
>>> from transformers import AutoTokenizer
>>> tk = AutoTokenizer.from_pretrained("./llava-v1.5-13b")
>>> tk.pad_token
'<unk>'
>>> tk.pad_token_id
0
>>> tk.convert_ids_to_tokens([0])
['<unk>']
>>> tkn = AutoTokenizer.from_pretrained("./llava-v1.5-13b-hf-new")
>>> tkn.pad_token
'<pad>'
>>> tkn.pad_token_id
32001
```

### Who can help?

@byshiue @juney-nvidia 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

null

### Expected behavior

the pad_token should not change

### actual behavior

the pad_token has been set the same as eos_token

### additional notes

null

**Comment by amukkara** [comment]
@DefTruth Thanks for pointing out this error. `pad_token` should not be set to `eos_token`. We will fix this in next release.
