### ISSUE TITLE
it's same AttentionMaskType.bidirectional not work?

### ISSUE THREAD

**Issue by laipaang** [NVIDIA/TensorRT-LLM#1384]
why change chatglm2 to AttentionMaskType.bidirectional not work?

https://github.com/NVIDIA/TensorRT-LLM/blob/850b6fa1e710d25769f2b560d897d2bd424a645e/tensorrt_llm/models/chatglm/model.py#L53

**Comment by wili-65535** [comment]
By default, FMHA is enabled and ChatGLM2 uses casual mask inside FMHA (bidirectional mask is not supported in FMHA), so the assignment here is useless.
You can disable the FMHA and use bidirectional mask.

**Comment by laipaang** [comment]
> By default, FMHA is enabled and ChatGLM2 uses casual mask inside FMHA (bidirectional mask is not supported in FMHA), so the assignment here is useless. You can disable the FMHA and use bidirectional mask.

`trtllm-build --context_fmha disable`

**Thx, it works!!!**
