### ISSUE TITLE
[Question] Question about Memory Usage in TRT-LLM

### ISSUE THREAD

**Issue by 1649759610** [NVIDIA/TensorRT-LLM#1390]
Hi, 

Recently, I quantized Llama model with FP8 precision, I have a question about memory usage when running model: 

What dtype of Layernorm use to do computation, FP8, FP16 or FP32?
What dtype of token embedding or ROPE embedding use to do computation, FP8, FP16, FP32?

Look forward you reply, Thanks.

**Comment by byshiue** [comment]
The computing of layer-norm and ROPE are on FP16 or FP32, depending on the op types and some flags (like `context_fmha_fp32_acc`).
