### ISSUE TITLE
C++ runtime gptSessionTest failed

### ISSUE THREAD

**Issue by chenpei2** [NVIDIA/TensorRT-LLM#1396]
I ran gptSessionTest with command 

> ./tests/gptSessionTest --gtest_filter=ChatGlm3SessionTest.HalfSamplingAttentionPluginBS1BM1

 and failed. Error messages:

> Running main() from /code/tensorrt_llm/cpp/build/_deps/googletest-src/googletest/src/gtest_main.cc
> Note: Google Test filter = ChatGlm3SessionTest.HalfSamplingAttentionPluginBS1BM1
> [==========] Running 1 test from 1 test suite.
> [----------] Global test environment set-up.
> [----------] 1 test from ChatGlm3SessionTest
> [ RUN      ] ChatGlm3SessionTest.HalfSamplingAttentionPluginBS1BM1
> [TensorRT-LLM][INFO] Engine version 0.9.0.dev2024040200 found in the config file, assuming engine(s) built by new builder API.
> [TensorRT-LLM][WARNING] [json.exception.type_error.302] type must be string, but is null
> [TensorRT-LLM][WARNING] Optional value for parameter quant_algo will not be set.
> [TensorRT-LLM][WARNING] [json.exception.type_error.302] type must be string, but is null
> [TensorRT-LLM][WARNING] Optional value for parameter kv_cache_quant_algo will not be set.
> [TensorRT-LLM][WARNING] [json.exception.out_of_range.403] key 'num_medusa_heads' not found
> [TensorRT-LLM][WARNING] Optional value for parameter num_medusa_heads will not be set.
> [TensorRT-LLM][WARNING] [json.exception.out_of_range.403] key 'max_draft_len' not found
> Expected equality of these values:
>   modelSpec.mUsePackedInput
> Expected equality of these values:
>   modelSpec.mUsePackedInput
>     Which is: false
>   modelConfig.usePackedInput()
>     Which is: true
> [TensorRT-LLM][INFO] Initializing MPI with thread mode 1
> [TensorRT-LLM][INFO] MPI size: 1, rank: 0
> [TensorRT-LLM][INFO] Loaded engine size: 11911 MiB
> [TensorRT-LLM][INFO] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 11951, GPU 15713 (MiB)
> [TensorRT-LLM][INFO] [MemUsageChange] Init cuDNN: CPU +2, GPU +10, now: CPU 11953, GPU 15723 (MiB)
> [TensorRT-LLM][INFO] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +11908, now: CPU 0, GPU 11908 (MiB) 
> [TensorRT-LLM][INFO] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +8, now: CPU 11990, GPU 15851 (MiB)
> [TensorRT-LLM][INFO] [MemUsageChange] Init cuDNN: CPU +0, GPU +8, now: CPU 11990, GPU 15859 (MiB)
> [TensorRT-LLM][INFO] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 11908 (MiB) 
> [TensorRT-LLM][INFO] Max tokens in paged KV cache: 1024. Allocating 29360128 bytes.
> [TensorRT-LLM][INFO] Max KV cache pages per sequence: 5
> [  FAILED  ] ChatGlm3SessionTest.HalfSamplingAttentionPluginBS1BM1 (23808 ms)
> [----------] 1 test from ChatGlm3SessionTest (23808 ms total)
> 
> [----------] Global test environment tear-down
> [==========] 1 test from 1 test suite ran. (23808 ms total)
> [  PASSED  ] 0 tests.
> [  FAILED  ] 1 test, listed below:
> [  FAILED  ] ChatGlm3SessionTest.HalfSamplingAttentionPluginBS1BM1
> 
>  1 FAILED TEST

No error messages if comment `verifyModelConfig`

The current gptSessionTest asks for a .npy file generated by a python script as input.How to convert input text into GptSession::generate inputs with C++ code?

**Comment by MartinMarciniszyn** [comment]
Please follow the [instructions to run C++ tests](https://github.com/NVIDIA/TensorRT-LLM/tree/main/cpp/tests).

**Comment by chenpei2** [comment]
> Please follow the [instructions to run C++ tests](https://github.com/NVIDIA/TensorRT-LLM/tree/main/cpp/tests).

problem not solved, why close this issue?

**Comment by MartinMarciniszyn** [comment]
The instructions explain exactly how to generate all files necessary for running the tests. If this does not work for you, please provided detailed instructions how to reproduce the issue. We cannot support any other use cases than running the tests with the provided input.
