### ISSUE TITLE
Memory type of sampling params

### ISSUE THREAD

**Issue by akhoroshev** [NVIDIA/TensorRT-LLM#1399]
This [document](https://github.com/NVIDIA/TensorRT-LLM/blob/118b3d7e7bab720d8ea9cd95338da60f7512c93a/docs/source/inference_request.md?plain=1#L16) describes tensor datatypes for [GptManager InferenceRequest](https://github.com/NVIDIA/TensorRT-LLM/blob/118b3d7e7bab720d8ea9cd95338da60f7512c93a/cpp/include/tensorrt_llm/batch_manager/inferenceRequest.h) 

My question is: what kind of memory is needed for these tensors? Pinned/Pagable/Device? I can't find information about this.

**Comment by byshiue** [comment]
They are on device memories.

**Comment by akhoroshev** [comment]
@byshiue I tested with kPINNED and kCPU and that works too

**Comment by byshiue** [comment]
For the results, they are all on cpu side. We will copy them to GPU in the core part.
