### ISSUE TITLE
How tensorRT-LLM generates sentences of different output(generation) lengths in one batch?

### ISSUE THREAD

**Issue by FlyingPotatoZ** [NVIDIA/TensorRT-LLM#140]
We found that tensorRT-LLM supports in-flight Batching (continous batching), which means that the output lengths of different sentences in the same batch can be different.

However, we found that the generation length of different sentences is the same (maximum generation length).
This means that the sentence did not generate a terminator or was not terminated by a terminator, before reaching the maximum output length.

We would like to ask the following questions:
1. Can tensorRT-LLM set a separate generation length for each sentence in the same batch like vLLM?
2. How tensorRT-LLM generates sentences of different output(generation) lengths in the same batch? Do we need to modify the terminator manually?

**Comment by byshiue** [comment]
TensorRT-LLM supports seperate generation length. It is controled by "request_output_len" [here](https://github.com/triton-inference-server/tensorrtllm_backend/blob/release/0.5.0/all_models/inflight_batcher_llm/tensorrt_llm/config.pbtxt#L48).

**Comment by byshiue** [comment]
Close this bug. Feel free to reopen it if needed.
