### ISSUE TITLE
How to stop TensorRT v0.8 from allocating all available gpu global storage for KV cache

### ISSUE THREAD

**Issue by AbhinavDutta** [NVIDIA/TensorRT-LLM#1400]
### System Info

NVIDIA A100

### Who can help?

@kaiyux @byshiue 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
python3 convert_checkpoint.py --model_dir XXXX \
        --smoothquant 0.5 \
        --output_dir .XXXX
 
trtllm-build --checkpoint_dir XXXX \
        --gemm_plugin float16 \
        --output_dir .XXXX \
        --max_batch_size 1 --max_input_len 4096 --max_output_len 1024 --max_num_tokens 4096 --max_beam_width 5 
 
python3 ../run.py --input_text "Y tho?" \
        --max_output_len 50 \
        --tokenizer_dir XXXX \
        --engine_dir XXXX \
```

### Expected behavior

Allocate 7GB for model, 1-2GB for KV cache , total 9GB

### actual behavior

73GB used, 67GB used for KV Cache!

```
[TensorRT-LLM][INFO] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 6683 (MiB)
[TensorRT-LLM][INFO] Allocate 69524783104 bytes for k/v cache. 
[TensorRT-LLM][INFO] Using 132608 tokens in paged KV cache.
```

### additional notes

Let me know how to control how much space that can be taken up by KV cache

**Comment by byshiue** [comment]
With enabling paged_kv_cache, TensorRT-LLM will pre-allocate some memory as memory pool for kv cache. Without specific setting, it often takes most of free memory. You could control it by some arguments like freeGpuMemoryFraction. More details are in https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/gpt_attention.md#kv-caches and https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/batch_manager.md#optional-gptmanager-parameters.
