### ISSUE TITLE
Mistral 7B v0.1 model inference latency increases despite sliding window attention size

### ISSUE THREAD

**Issue by vnkc1** [NVIDIA/TensorRT-LLM#1404]
### System Info

p4d (8 x A100 40GB GPUs)

### Who can help?

@kaiyux @byshiue 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Install 0.8.0 and create Mistral 7B Bf16 engine with max input length as 8192 and max batch size as 32 (TP-4).

`trtllm-build --checkpoint_dir ~/bf16-tp4-checkpoint  --output_dir ~/bf16-tp4-engine --gpt_attention_plugin bfloat16 --gemm_plugin bfloat16 --remove_input_padding enable --paged_kv_cache enable --context_fmha enable --workers 4 --max_batch_size 32 --max_input_len 8192 --max_output_len 512`

2. Pass 4096 as `max_attention_window_size` to run script here
https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/run.py

Benchmark for batch size = 32 and for input token length = 4000, 6000, 8000

### Expected behavior

Latency should top out at 4k input token length due to sliding window attention

### actual behavior

Latency doubles from 4k to 8k input token length.

### additional notes

N/A

**Comment by PerkzZheng** [comment]
Even with sliding window attention, the performance with s = 8k is not the same as s = 4k. 

you can divide the query dimension into two parts, 
1. s <= 4k: which is the same as case where s = 4k.
2. 4k < s < 8K: which should take longer time than first part.

it is better to compare the 8k case with or without sliding window attention.

**Comment by ghost** [comment]
I don't think the latency should be doubling from 4k to 8k though

**Comment by PerkzZheng** [comment]
> I don't think the latency should be doubling from 4k to 8k though

bs = 32 normally have saturated the GPU resources, so 

1. GEMMs: roughly 2x latency because of 2x M
2. Attention: roughly 3x latency  (see my previous comment that the 2nd part will always attend to 4k). 

you can breakdown the nsys timelines and see how GEMM and fmha perform. 
Note that without sliding window attention, it should about 4x latency for the attention part.
