### ISSUE TITLE
tensorrt_llm Import error

### ISSUE THREAD

**Issue by zx6006** [NVIDIA/TensorRT-LLM#1408]
### System Info

official container version:  nvcr.io/nvidia/tritonserver:24.03-trtllm-python-py3
CUDA version:12.4
GPU: 4090
tensorrt                        9.3.0.post12.dev1
tensorrt-bindings         9.3.0.post12.dev1
tensorrt-libs                 9.3.0.post12.dev1
tensorrt_llm                 0.9.0.dev2024040200

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

python3 -c "import tensorrt_llm; print(tensorrt_llm.__version__)"

### Expected behavior

/

### actual behavior

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/__init__.py", line 47, in <module>
    from .hlapi.llm import LLM, ModelConfig
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/hlapi/__init__.py", line 1, in <module>
    from .llm import (LLM, KvCacheConfig, ModelConfig, ParallelConfig,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/hlapi/llm.py", line 15, in <module>
    import tensorrt_llm.bindings as tllm
ImportError: /usr/local/lib/python3.10/dist-packages/tensorrt_llm/bindings.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZNK12tensorrt_llm8executor25SpeculativeDecodingConfig22getAcceptanceThresholdEv

### additional notes

/

**Comment by acmore** [comment]
seems like the symbol is included in `tensorrt_llm/libs/libtensorrt_llm.so` but not in `tensorrt_llm/bindings.cpython-310-x86_64-linux-gnu.so`, I could resolve this issue by setting `LD_PRELOAD=/usr/local/lib/python3.10/dist-packages/tensorrt_llm/libs/libtensorrt_llm.so`

**Comment by zx6006** [comment]
> seems like the symbol is included in `tensorrt_llm/libs/libtensorrt_llm.so` but not in `tensorrt_llm/bindings.cpython-310-x86_64-linux-gnu.so`, I could resolve this issue by setting `LD_PRELOAD=/usr/local/lib/python3.10/dist-packages/tensorrt_llm/libs/libtensorrt_llm.so`

thanks a lot, I downgraded tensort_llm to `V0.8.0`, and now it runs as expect; I haven't tried the `9.3.0.post12.dev1` version yet

**Comment by felixslu** [comment]
`python3 -c "import tensorrt_llm; print(tensorrt_llm.version)"
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/__init__.py", line 39, in <module>
    import tensorrt_llm.bindings  # NOQA
ImportError: /usr/local/lib/python3.10/dist-packages/tensorrt_llm/bindings.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZNK12tensorrt_llm8executor25SpeculativeDecodingConfig22getAcceptanceThresholdEv

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/__init__.py", line 41, in <module>
    raise ImportError(
ImportError: Import of the `bindings` module failed. Please check the package integrity. If you are attempting to use the pip development mode (editable installation), please execute `build_wheels.py` first, and then run `pip install -e .``

I counter this error on v0.9.0 too,Maybe it is a bug?

**Comment by felixslu** [comment]
> seems like the symbol is included in `tensorrt_llm/libs/libtensorrt_llm.so` but not in `tensorrt_llm/bindings.cpython-310-x86_64-linux-gnu.so`, I could resolve this issue by setting `LD_PRELOAD=/usr/local/lib/python3.10/dist-packages/tensorrt_llm/libs/libtensorrt_llm.so`

unluckily , It does not work for me.

**Comment by shixuan94** [comment]
> > seems like the symbol is included in `tensorrt_llm/libs/libtensorrt_llm.so` but not in `tensorrt_llm/bindings.cpython-310-x86_64-linux-gnu.so`, I could resolve this issue by setting `LD_PRELOAD=/usr/local/lib/python3.10/dist-packages/tensorrt_llm/libs/libtensorrt_llm.so`
> 
> thanks a lot, I downgraded tensort_llm to `V0.8.0`, and now it runs as expect; I haven't tried the `9.3.0.post12.dev1` version yet

I encountered the exact same problem with you... So on which docker image do you install v0.8.0?

**Comment by zx6006** [comment]
> > > seems like the symbol is included in `tensorrt_llm/libs/libtensorrt_llm.so` but not in `tensorrt_llm/bindings.cpython-310-x86_64-linux-gnu.so`, I could resolve this issue by setting `LD_PRELOAD=/usr/local/lib/python3.10/dist-packages/tensorrt_llm/libs/libtensorrt_llm.so`
> > 
> > 
> > thanks a lot, I downgraded tensort_llm to `V0.8.0`, and now it runs as expect; I haven't tried the `9.3.0.post12.dev1` version yet
> 
> I encountered the exact same problem with you... So on which docker image do you install v0.8.0?

you can get the official docker image via [NGC](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/tritonserver/tags)
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/90826536/ddae1d73-a4a9-4a6c-bb92-359fc0dde617)

**Comment by byshiue** [comment]
24.03-trtllm-python-py3 docker image installs the tensorrt_llm 0.8.0 by default, so you cannot install pypi tensorrt_llm 0.9.0 and run on it. If you want to run tensorrt_llm 0.9.0, you need to build the 0.9.0 from source in the 24.03-trtllm-python-py3 docker image, or try using the 24.04 docker image.

**Comment by zx6006** [comment]
> 24.03-trtllm-python-py3 docker image installs the tensorrt_llm 0.8.0 by default, so you cannot install pypi tensorrt_llm 0.9.0 and run on it. If you want to run tensorrt_llm 0.9.0, you need to build the 0.9.0 from source in the 24.03-trtllm-python-py3 docker image, or try using the 24.04 docker image.

thanks for your reply 
however, in fact, I built the `tensorrt_llm-0.9.0.dev2024040200-cp310-cp310-linux_x86_64.whl` file within the 24.03-trtllm-python-py3 container, and based on it, I installed `tensorrt_llm 0.9.0.dev2024040200`, but it did not take effect
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/90826536/931d03c1-7f0b-4381-8db3-092ceb16dd97)

**Comment by shixuan94** [comment]
With 

export LD_PRELOAD="/usr/local/lib/python3.10/dist-packages/tensorrt_llm/libs/libtensorrt_llm.so /usr/local/lib/python3.10/dist-packages/tensorrt_llm/libs/libnvinfer_plugin_tensorrt_llm.so /usr/local/lib/python3.10/dist-packages/tensorrt_llm/libs/libth_common.so"

, I successfully run the benchmarks on tritonserver docker. However, bash becomes unavailable.

Therefore, I overwrite the .so files, and it works out, the gptSessionBenchmark can run successfully. (Better to backup before copy.)

cp /usr/local/lib/python3.10/dist-packages/tensorrt_llm/libs/* /opt/tritonserver/backends/tensorrtllm

Wish this be helpful for anyone in need...

**Comment by byshiue** [comment]
> With
> 
> export LD_PRELOAD="/usr/local/lib/python3.10/dist-packages/tensorrt_llm/libs/libtensorrt_llm.so /usr/local/lib/python3.10/dist-packages/tensorrt_llm/libs/libnvinfer_plugin_tensorrt_llm.so /usr/local/lib/python3.10/dist-packages/tensorrt_llm/libs/libth_common.so"
> 
> , I successfully run the benchmarks on tritonserver docker. However, bash becomes unavailable.
> 
> Therefore, I overwrite the .so files, and it works out, the gptSessionBenchmark can run successfully. (Better to backup before copy.)
> 
> cp /usr/local/lib/python3.10/dist-packages/tensorrt_llm/libs/* /opt/tritonserver/backends/tensorrtllm
> 
> Wish this be helpful for anyone in need...

Thank you for the report. That's because when you install the `.whl` file, it only install the python package. But the triton backend does not use python backend, but load the `.so` files in `/opt/tritonserver/backends/tensorrtllm/`. So, your solution to replace the .so files are correct. 

Close this bug.
