### ISSUE TITLE
Could this repo support for cuda11.8? my device couldn't install with cuda12.1

### ISSUE THREAD

**Issue by fuxuelinwudi** [NVIDIA/TensorRT-LLM#1409]
### System Info

A100 80G, UBUNTU 20.04 LTS 

### Who can help?

1

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

1

### Expected behavior

1

### actual behavior

1

### additional notes

1

**Comment by byshiue** [comment]
It might work, but we don't verify on that and we cannot provide any guarantee.
