### ISSUE TITLE
What is the meaning for the benchmark output `tokens_per_sec` and `generation_tokens_per_second`? 

### ISSUE THREAD

**Issue by sleepwalker2017** [NVIDIA/TensorRT-LLM#1410]
I run benchmark like this:
```
mpirun -n 2 --allow-run-as-root python benchmark.py \
    -m llama_13b \
    --mode plugin \
    --batch_size "1;8;16" \
    --input_output_len "710,190" \
    --max_input_len 750 --max_output_len 200
```
I got this:
```
[BENCHMARK] model_name llama_13b world_size 2 num_heads 40 num_kv_heads 40 num_layers 40 hidden_size 5120 vocab_size 32000 precision float16 batch_size 1 input_length 710 output_length 190 gpu_peak_mem(gb) 0.0 build_time(s) 116.39 tokens_per_sec 43.09 percentile95(ms) 5120.208 percentile99(ms) 5120.208 latency(ms) 4409.816 compute_cap sm80 quantization QuantMode.0 generation_time(ms) 3751.546 total_generated_tokens 189.0 generation_tokens_per_second 50.379
```

I see there are two token per sec numbers, which is correct? and what is the meaning for each of them?

I can't find any documentation mentioning that.

**Comment by byshiue** [comment]
`tokens_per_sec` means the throughput of end to end inference. It is computed by `generated_tokens / total_latency`. In your case, it is computed by `190 / 4409.816 * 1000 = 43.09`.

`generation_tokens_per_second` only consider the generation. It means the thorughput during generation and computed by `generated_tokens / generation_time`. In your case, it is computed by  `189 / 3751.546 * 1000 = 50.379`.

**Comment by sleepwalker2017** [comment]
> `tokens_per_sec` means the throughput of end to end inference. It is computed by `generated_tokens / total_latency`. In your case, it is computed by `190 / 4409.816 * 1000 = 43.09`.
> 
> `generation_tokens_per_second` only consider the generation. It means the thorughput during generation and computed by `generated_tokens / generation_time`. In your case, it is computed by `189 / 3751.546 * 1000 = 50.379`.

Got it, the lower number includes the prefill stage.

**Comment by YiandLi** [comment]
what about  `gpu_peak_mem` mean ? It is 0 in my case.

**Comment by byshiue** [comment]
Could you take a try on latest main branch?
