### ISSUE TITLE
TensorRT-LLM/examples /hf_lora_convert.py doesn't support ChatGLM .safetensor Lora weights

### ISSUE THREAD

**Issue by wangqy1216** [NVIDIA/TensorRT-LLM#1411]
Just as what I mentioned in the title, 

 Keys for ChatGLM Lora Weights:
dict_keys(['base_model.model.transformer.encoder.layers.0.self_attention.query_key_value.lora_A.weight', 'base_model.model.transformer.encoder.layers.0.self_attention.query_key_value.lora_B.weight', 'base_model.model.transformer.encoder.layers.1.self_attention.query_key_value.lora_A.weight', 'base_model.model.transformer.encoder.layers.1.self_attention.query_key_value.lora_B.weight'])

Keys for example Lora Weights:
lora_model: dict_keys(['base_model.model.model.layers.0.self_attn.q_proj.lora_A.weight', 'base_model.model.model.layers.0.self_attn.q_proj.lora_B.weight', 'base_model.model.model.layers.0.self_attn.v_proj.lora_A.weight', 'base_model.model.model.layers.0.self_attn.v_proj.lora_B.weight', 'base_model.model.model.layers.1.self_attn.q_proj.lora_A.weight', 'base_model.model.model.layers.1.self_attn.q_proj.lora_B.weight', 'base_model.model.model.layers.1.self_attn.v_proj.lora_A.weight', 'base_model.model.model.layers.1.self_attn.v_proj.lora_B.weight',])

hf_lora_convert.py doesn't support the keys for ChatGLM layer names

**Comment by byshiue** [comment]
TensorRT-LLM does not support LoRA on ChatGLM yet.
