### ISSUE TITLE
Streaming has some issues with spaces and 

### ISSUE THREAD

**Issue by Anindyadeep** [NVIDIA/TensorRT-LLM#1414]
### System Info

I am using an A100 GPU 80 GB 

### Who can help?

@ncomly-nvidia @kaiyux @byshiue 

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Let's take three cases,

### Case 1: Running the official [run.py](https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/run.py) script.

Here on [line num: 272, 280](https://github.com/NVIDIA/TensorRT-LLM/blob/118b3d7e7bab720d8ea9cd95338da60f7512c93a/examples/run.py#L272-L280) I have removed the `print(f'Input [Text {batch_idx}]: \"{input_text}\"')` and replaced this line:

```
print(f'Output [Text {batch_idx} Beam {beam}]: \"{output_text}\"')
```

with this:

```
print(output_text)
```

For which everything is running, but I am getting an output with all the history, where I was expecting to get only the next token to be streamed. 

### Expected behavior

I should be getting something like:

```
i
am 
doing
well
,
thank 

.... and do on
```

### actual behavior

```bash
i am doing well,
i am doing well, thank
i am doing well, thank you
i am doing well, thank you for
i am doing well, thank you for asking
i am doing well, thank you for asking!
i am doing well, thank you for asking! how
i am doing well, thank you for asking! how about
i am doing well, thank you for asking! how about you
i am doing well, thank you for asking! how about you?
i am doing well, thank you for asking! how about you?</s>
```

### additional notes

I even tried with approach where I re-wrote some part of the `print_output` function like this

```python

def print_output(tokenizer, output_ids, input_lengths, sequence_lengths):
    batch_size, num_beams, _ = output_ids.size()
    if output_csv is None and output_npy is None:
        for batch_idx in range(batch_size):
            inputs = output_ids[batch_idx][0][:input_lengths[batch_idx]].tolist(
            )
            out_idx = 0
            input_text = tokenizer.decode(inputs)
            for beam in range(num_beams):
                output_begin = input_lengths[batch_idx] + out_idx
                output_end = sequence_lengths[batch_idx][beam]
                outputs = output_ids[batch_idx][beam][
                    output_begin:output_end].tolist()
                output_text = tokenizer.decode(outputs)
                print(output_text)
                out_idx += 1 
```

However with this approach I do get an output like this

```
i
am 
doing
well
,
thank 

.... and do on
```

But when I do write this

```python
import sys 

def print_output(tokenizer, output_ids, input_lengths, sequence_lengths):
    batch_size, num_beams, _ = output_ids.size()
    if output_csv is None and output_npy is None:
        for batch_idx in range(batch_size):
            inputs = output_ids[batch_idx][0][:input_lengths[batch_idx]].tolist(
            )
            out_idx = 0
            input_text = tokenizer.decode(inputs)
            for beam in range(num_beams):
                output_begin = input_lengths[batch_idx] + out_idx
                output_end = sequence_lengths[batch_idx][beam]
                outputs = output_ids[batch_idx][beam][
                    output_begin:output_end].tolist()
                output_text = tokenizer.decode(outputs)
                sys.stdout.write(output_text)
                out_idx += 1 
```

In this case, I get lot of problems in whitespace handling, which is causing another problem. Because in the end, for using streaming, I need to stream the tokens properly, so that they do not get repeated. But this is not working.

**Comment by byshiue** [comment]
The streaming feature only provide the function that the tokenizer could get the latest output ids immedidately.

Even if using streaming, you still need to detokenize some tokens together to make sure the tokenizer could work well because some tokens sometimes map to a word. It is limitation of tokenizer.
