### ISSUE TITLE
What is the recommended way to do benchmark

### ISSUE THREAD

**Issue by sleepwalker2017** [NVIDIA/TensorRT-LLM#1421]
1. There are two folders, python and cpp, what is the relationship between them?
2. which is recommended to do benchmark?

3. I want to benchmark the token throughput when using lora. Seems only static batching is supported currently.
Is there any script to benchmark the performance using lora?

**Comment by kaiyux** [comment]
1. Scripts in `python` is benchmarking the Python runtime of TensorRT-LLM, while `cpp` includes scripts to benchmark the C++ runtime, which includes support to benchmark static batching and inflight batching implementation.
2. C++ runtime is more recommended to do the benchmark.
3. Inflight batching is supported for LoRA. You can find documents to benchmark LoRA [here](https://github.com/NVIDIA/TensorRT-LLM/tree/main/benchmarks/cpp#benchmarking-lora), and more details regarding LoRA [here](https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/llama#run-llama-with-lora).

Thanks.

**Comment by sleepwalker2017** [comment]
> 1. Scripts in `python` is benchmarking the Python runtime of TensorRT-LLM, while `cpp` includes scripts to benchmark the C++ runtime, which includes support to benchmark static batching and inflight batching implementation.
> 2. C++ runtime is more recommended to do the benchmark.
> 3. Inflight batching is supported for LoRA. You can find documents to benchmark LoRA [here](https://github.com/NVIDIA/TensorRT-LLM/tree/main/benchmarks/cpp#benchmarking-lora), and more details regarding LoRA [here](https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/llama#run-llama-with-lora).
> 
> Thanks.

Thank you, I'll try that

**Comment by sleepwalker2017** [comment]
> 1. Scripts in `python` is benchmarking the Python runtime of TensorRT-LLM, while `cpp` includes scripts to benchmark the C++ runtime, which includes support to benchmark static batching and inflight batching implementation.
> 2. C++ runtime is more recommended to do the benchmark.
> 3. Inflight batching is supported for LoRA. You can find documents to benchmark LoRA [here](https://github.com/NVIDIA/TensorRT-LLM/tree/main/benchmarks/cpp#benchmarking-lora), and more details regarding LoRA [here](https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/llama#run-llama-with-lora).
> 
> Thanks.

Hello, seems there is something wrong with the lora feature.
```
python examples/llama/convert_checkpoint.py --model_dir ${MODEL_CHECKPOINT} \
                              --output_dir ${CONVERTED_CHECKPOINT} \
                              --dtype ${DTYPE} \
                              --tp_size ${TP} \
                              --pp_size 1 \
                              --lora_target_modules attn_qkv \
                              --max_lora_rank ${MAX_LORA_RANK}
```

the `convert_checkpoint.py` file has no arguments for `--lora_target_modules` and `--max_lora_rank`

**Comment by kaiyux** [comment]
@sleepwalker2017 Sorry, the documents under benchmark directory for LoRA is outdated, we will fix them. Please refer to the documents [here](https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/llama#run-llama-with-lora) and try the commands there, which should be updated.

**Comment by sleepwalker2017** [comment]
> @sleepwalker2017 Sorry, the documents under benchmark directory for LoRA is outdated, we will fix them. Please refer to the documents [here](https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/llama#run-llama-with-lora) and try the commands there, which should be updated.

I got this new issue when generating test data for lora inflight batching 
https://github.com/NVIDIA/TensorRT-LLM/issues/1453

**Comment by dtlzhuangz** [comment]
@kaiyux I wonder why I cppbenchmark a built engine of fp8 in 4090, the prefill speed seem to be much slower than the results benchmarked by python. Here are the scripts. Thank you.
`python /app/tensorrt_llm/benchmarks/python/benchmark.py -m baichuan2_7b_chat --quantization fp8 --mode plugin --world_size 1 --max_input_len 1024 --max_batch_size 8 --max_output_len 50 --batch_size "1;2;4;8"  --input_output_len "1024,1;1024,50"`
The scripts for building fp8 engine:
`python /app/tensorrt_llm/examples/quantization/quantize.py --model_dir ${WORK_HF_DIR} \
                                   --dtype float16 \
                                   --qformat fp8 \
                                   --output_dir /tmp/ckpts_fp8 \
                                   --calib_size 512`
`
trtllm-build --checkpoint_dir /tmp/ckpts_fp8/ --output_dir ${TRT_ENGINE} --remove_input_padding enable   --remove_input_padding enable  --gemm_plugin float16 --gpt_attention_plugin float16 --remove_input_padding enable --context_fmha enable --use_paged_context_fmha enable --paged_kv_cache enable --max_input_len=1024 --max_batch_size=${MAX_BATCH_SIZE} --max_output_len=64
`
`/app/tensorrt_llm/cpp/build/benchmarks/gptSessionBenchmark --engine_dir ${TRT_ENGINE} --input_output_len "1024,1;1024,50" --batch_size "1;2;4;8"`

**Comment by hello-11** [comment]
@sleepwalker2017 Do you still have the question? If not, we will close it soon.
