### ISSUE TITLE
Window attention with huge window size(such as 65k) encountered shared mem error

### ISSUE THREAD

**Issue by jesonxiang** [NVIDIA/TensorRT-LLM#1424]
### System Info

A800
trtllm v0.8

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. build engine with large seqlen, eg. 256k input
2. use huge window attention size, eg. 65k window
3. inference with 256k prompt

### Expected behavior

can infer normally by using multi-block decoding.

### actual behavior

<img width="1651" alt="企业微信截图_557dce88-faf7-480f-af09-72ea2d6b22ef" src="https://github.com/NVIDIA/TensorRT-LLM/assets/47811306/0af2dd93-926c-4c7f-8449-53b5918f8dbe">

### additional notes

some informations may help:
1. 65k window will also trigger multi-block mode
2. the calculation of params.timesteps_per_block in function _multi_block_grid_setup_ also use the max input length, but not the real windowed block size.
3. shared mem usage in function _smem_size_in_bytes_ leads the wrong space, core.

**Comment by byshiue** [comment]
Sorry for late response. It is a known issue about computing the share memory size when we use sliding window. We will fix it soon.

**Comment by PerkzZheng** [comment]
the fix will be included in next week's update (Tuesday). Feel free to give it a try.
