### ISSUE TITLE
Is it possible to change topK/topP during generation in GptManager?

### ISSUE THREAD

**Issue by akhoroshev** [NVIDIA/TensorRT-LLM#1425]
For example I want to change topP value after some condition is met.

Basically I have access to runtimeTopP/K tensors via [getters]( https://github.com/NVIDIA/TensorRT-LLM/blob/main/cpp/include/tensorrt_llm/batch_manager/inferenceRequest.h#L246)

But is it safe to modify these values during generation? Will the changes be visible?

**Comment by byshiue** [comment]
No. TensorRT-LLM does not support such feature.
