### ISSUE TITLE
gpt build.py error

### ISSUE THREAD

**Issue by hpz4311** [NVIDIA/TensorRT-LLM#143]
hello, I am runing the example/gpt/build.py with dummy weight
python3 build.py --world_size=8 \
                 --log_level=verbose \
                 --n_layer=20 \
                 --n_embd=2560 \
                 --n_head=40 \
                 --max_batch_size=10 \
                 --dtype float16 \
                 --remove_input_padding \
                 --use_gpt_attention_plugin \
                 --enable_context_fmha \
                 --use_gemm_plugin \
                 --output_dir=my_path 2>&1 | tee build.log
I get an error of incompatible function arguments  in add_plugin_v2(plug_inputs, gemm_plug) in linear.py:53, it seems the gemm_plug is NONE
my cuda is 12.1 , A100, torch is 1.12.0,  openmpi 3.1.0, tensorrt 9.1

**Comment by jdemouth-nvidia** [comment]
Hi @hpz4311 , 

Since you're using CUDA 12.1, I guess you have not built TensorRT-LLM using the recommended build method. Can you provide us with more details about how you built TensorRT-LLM, please? Also, what's your operating system? 

Thanks,
Julien

**Comment by hpz4311** [comment]
> Hi @hpz4311 ,
> 
> Since you're using CUDA 12.1, I guess you have not built TensorRT-LLM using the recommended build method. Can you provide us with more details about how you built TensorRT-LLM, please? Also, what's your operating system?
> 
> Thanks, Julien

thank you for reply , I have check the error and my cuda eviroment, I found that my cude driver is 515 version which is not compatible with cuda_12.1, after upgrade it , it worked and I have successfully run the single-node 8-GPU gpt.   
but now I have 2 machine, each with 8 A100. How can I get and run a 2_pp_8_tp gpt model. It seems the build.py and run.py is only support for Tensor parallelism。By the way, I can not find the communication operator between  different Pipeline。 welcome for clarifying my confusion, thank you .

**Comment by jdemouth-nvidia** [comment]
Hi @hpz4311 ,

We have not yet validated multi-node configurations with TensorRT-LLM. In particular, we have not carefully tested PP across nodes so I don’t recommend you try that for now. 

Thanks,
Julien

**Comment by byshiue** [comment]
Close this bug. Reopen if needed.
