### ISSUE TITLE
 How does TensorRT-LLM multimoda support GroundingDINO

### ISSUE THREAD

**Issue by MouseSun846** [NVIDIA/TensorRT-LLM#1430]
1、How does TensorRT-LLM multimoda support GroundingDINO？
2、Can TensorRT-LLM multimoda support GroundingDINO？How to do?

[GroundingDINO](https://github.com/IDEA-Research/GroundingDINO)

**Comment by byshiue** [comment]
I am not sure the model architecture of GroundingDINO. If it is same to any supported models in https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples, it might be supported. Otherwise, it is not supported in TensorRT-LLM now.

**Comment by hello-11** [comment]
@MouseSun846 Do you still have the question? If not, we will close it soon.

**Comment by MouseSun846** [comment]
thanks,I have no problem now.
