### ISSUE TITLE
Unable to install via pip (Unable to find wheel for tensorrt-llm 0.9.0)

### ISSUE THREAD

**Issue by jasonngap1** [NVIDIA/TensorRT-LLM#1442]
### System Info

- CPU architecture: x86_84
- GPU: A100
- Python version: 3.10.13 on a virtual env

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. pip install -U --pre --extra-index-url https://pypi.nvidia.com/ tensorrt-llm

### Expected behavior

TensorRT-LLM installed

### actual behavior

![image](https://github.com/NVIDIA/TensorRT-LLM/assets/100476127/b5e1ce61-193b-4d43-8f36-1d8b1ecab375)

### additional notes

I have tried previous solutions of closed issues (like the below) to install cudnn ~=8.9 first, but it does not help.
```
pip3 install "nvidia-cudnn-cu12~=8.9"
pip3 install -U --pre --extra-index-url https://pypi.nvidia.com/ tensorrt-llm
```

**Comment by dat-lequoc** [comment]
I encountered the same error very recently. There may be a problem with the newly released package: [tensorrt_llm-0.9.0.dev2024040900-cp310-cp310-linux_x86_64.whl](https://pypi.nvidia.com/tensorrt-llm/tensorrt_llm-0.9.0.dev2024040900-cp310-cp310-linux_x86_64.whl#sha256=eb4fa7eee1ce6e4722b40dd2a7acec251392c26fff684c9aaf29d50c9a4908d7)

Rolling back to the last version works fine for me :
```
pip3 install --extra-index-url https://pypi.nvidia.com/ tensorrt_llm==0.9.0.dev2024040200
```

**Comment by jasonngap1** [comment]
Thank you very much, the installation with version 0.9.0.dev2024040200 was successful.

**Comment by ghost** [comment]
Is the `0.9.0.dev2024040200` version equivalent to `0.9.0`?
