### ISSUE TITLE
How to add extra ops to Transformer layer?

### ISSUE THREAD

**Issue by heibaidaolx123** [NVIDIA/TensorRT-LLM#1443]
Hi, I want to try Cohere model in TRT-llm, and there's qk-norm in the model, and I dont know how to compile it into the engine.
According to the [doc](https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/checkpoint.md), it seems that only input and post norm are supported. So how to add qk-norm?
Any help would be appreciated.
Thanks.

**Comment by juney-nvidia** [comment]
@QiJune  Can you help follow with this Cohere question?
