### ISSUE TITLE
How to Define a arbitrary Tensor in model definition?

### ISSUE THREAD

**Issue by robosina** [NVIDIA/TensorRT-LLM#145]
I've got a sinusoidal positional encoding, and I'm trying to make a new model for my network. **I need to create a new Tensor(placeholder) for this positional encoding**. But when I try to make the Tensor, I get errors related to 'default_net' or something like that. How can I define a Tensor of arbitrary size in my model definition? I want to be able to copy PyTorch weights into it later. Thanks in advance.

**Comment by jdemouth-nvidia** [comment]
Hi @robosina ,

Can you share the code that leads to errors, please? It’ll be easier to help you this way. 

Thanks,
Julien

**Comment by robosina** [comment]
@jdemouth-nvidia Thanks for replying back, I will try to show a simple case, please suppose the following `EncoderModel`, in this class I need to define `self.position_embedding` as a Tensor(such as np.array):

``` python
class EncoderModel(Module):

    def __init__(self,*args,*kwargs):
        super().__init__()
        self.position_embedding = Tensor(name="position_embedding", dtype=trt.float32, shape=[max_position_embeddings, hidden_size])
                                            
   def forward(self,
          input_ids: Tensor,
          input_lengths=None,
          position_ids=None,
          token_type_ids=None):
   
        # get hidden_states
        hidden_states = ...

        # add hidden_states with positional encoding
        hidden_states = hidden_states + positional_encoding                                   
```

I have observed the following errors after running the `build.py` for my new model:

```
Use builder to create network first, and use `set_network` or `net_guard` to set it to default
  File "/app/tensorrt_llm/examples/ts/model.py", line 451, in __init__
    self.position_embedding = Tensor(name="position_embedding", dtype=trt.float32, shape=[max_position_embeddings, hidden_size])
  File "/app/tensorrt_llm/examples/ts/build.py", line 171, in build_rank_engine
    tllm_model = EncoderModel(
  File "/app/tensorrt_llm/examples/ts/build.py", line 330, in build
    engine = build_rank_engine(builder, builder_config, engine_name,
  File "/app/tensorrt_llm/examples/ts/build.py", line 358, in run_build
    build(0, args)
  File "/app/tensorrt_llm/examples/ts/build.py", line 366, in <module>
    run_build(component='encoder')
AssertionError: Use builder to create network first, and use `set_network` or `net_guard` to set it to default
```

I intended to use a Tensor to store my weights in a straightforward manner. Thanks.

**Comment by jdemouth-nvidia** [comment]
Hi @robosina ,

Assuming the tensor is known when you build the engine, I suggest that you take a look at how we define the weights of the Embedding layer here: https://github.com/NVIDIA/TensorRT-LLM/blob/11e14500f35dd781b535ba009c906f55ecfee3b5/tensorrt_llm/layers/embedding.py#L53

This parameter is then bound in the `weight.py` script of the model. For example, for the GPT model, you can see: https://github.com/NVIDIA/TensorRT-LLM/blob/11e14500f35dd781b535ba009c906f55ecfee3b5/examples/gpt/weight.py#L194.

If the weights are dynamic, we can discuss how to add a network input but I guess they are fixed. 

Thanks,
Julien

**Comment by robosina** [comment]
@jdemouth-nvidia Thanks
