### ISSUE TITLE
TRT-LLM 0.9.0 support for A6000?

### ISSUE THREAD

**Issue by zhang001122** [NVIDIA/TensorRT-LLM#1452]
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/149790792/19855c51-f0f5-475e-bfdc-bf268873b7cf)
trt-llm 0.9.0 has released and support sm80 sm86,
My Question is TRT-llm support for A6000?
And any benchmark of throughout score of it?

**Comment by byshiue** [comment]
TensorRT-LLM supports A6000, but we don't have any benchmark on it.

**Comment by zhang001122** [comment]
ok  thanks
