### ISSUE TITLE
If i use my fine-tune model rather than the official model, do i need to replace the dataset (cnn_dailymail) when using gptq&awq quantization method?

### ISSUE THREAD

**Issue by Kevinddddddd** [NVIDIA/TensorRT-LLM#1468]
Do i need to replace cnn_dailymail dataset with my own dataset?

**Comment by byshiue** [comment]
Could you take a try to use the cnn_dailymail dataset to do quantization first? From our previous experiment, the accuracy should be acceptable. 

If you want to use custom dataset, you might need to match the format of offical dataset.

**Comment by Kevinddddddd** [comment]
> Could you take a try to use the cnn_dailymail dataset to do quantization first? From our previous experiment, the accuracy should be acceptable.
> 
> If you want to use custom dataset, you might need to match the format of offical dataset.

Thanks!

**Comment by Kevinddddddd** [comment]
> Could you take a try to use the cnn_dailymail dataset to do quantization first? From our previous experiment, the accuracy should be acceptable.
> 
> If you want to use custom dataset, you might need to match the format of offical dataset.

Thanks!

**Comment by Kevinddddddd** [comment]
> Could you take a try to use the cnn_dailymail dataset to do quantization first? From our previous experiment, the accuracy should be acceptable.
> 
> If you want to use custom dataset, you might need to match the format of offical dataset.

Thanks!
