### ISSUE TITLE
how to build across multiple nodes?

### ISSUE THREAD

**Issue by esmeetu** [NVIDIA/TensorRT-LLM#147]
hi, I have two machines with two gpus each. And I have already built one docker image on one machine which works normally. But I want to build my model using tp-size 4. So how do i communicate with another machine so that i can use 4 gpu to build and run model. Any helpful docs here?

Note: there is no nvlink between two machines. They are hosted locally connected by normal network.

**Comment by jdemouth-nvidia** [comment]
Hi @esmeetu ,

We've done some simple tests to build and run on two nodes but it has not been thoroughly tested yet. To support multi-node configs, you have to use `mpirun` commands (`mpirun -n 4 ...`).

Thanks,
Julien

**Comment by byshiue** [comment]
Close this bug because the issue is inactivated. Feel free to ask here if you still have question/issue, we will reopen the issue.

**Comment by Jeffwan** [comment]
@byshiue @jdemouth-nvidia Is there a documentation on this? We would like to know the steps to run multi-node inference and potential performance limitations introduced by MPU
