### ISSUE TITLE
Error while exporting to TensorRTLLM format - AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by pradeepdev-1995** [NVIDIA/TensorRT-LLM#1475]
### System Info

-A100 GPU machine
cuda
-docker : ```nvcr.io/nvidia/nemo:24.01.gemma``` 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I could finetune the gemma model and merge the adapter with base model by following this official notebook
https://github.com/NVIDIA/GenerativeAIExamples/blob/main/models/Gemma/lora.ipynb
Now Tried the given code for TensorRTLLM model conversion
```
from nemo.export import TensorRTLLM
trt_llm_exporter = TensorRTLLM(model_dir="/llmmodels/gemma_pubmedqa_merged_trt_llm")
trt_llm_exporter.export(nemo_checkpoint_path="/llmmodels/merged_model/gemma_lora_pubmedqa_merged.nemo", model_type="gemma", n_gpus=1)
```
But it is not working and gives this error
![Screenshot from 2024-04-18 20-05-52](https://github.com/NVIDIA/NeMo/assets/41164884/5e828643-f23c-4f79-b3a1-bdd6287df6ca)
I am using the docker container for the fine-tuning task
It seems the **model_config.yaml** file is being created inside temp directory during exporting ,but the created model_config.yml file is empty. that's why the Nontype object is returning

### Expected behavior

Not expecting any error

### actual behavior

Dont expect any error

### additional notes

nothing

**Comment by byshiue** [comment]
Could you ask in Nemo repo? It breaks in nemo codes and still not enter the tensorrt_llm.

**Comment by hello-11** [comment]
@pradeepdev-1995 Do you still have the question? If not, we will close it soon.
