### ISSUE TITLE
3090(24G) with single-gpu can't run 6B model(e.g chatglm2-6B)

### ISSUE THREAD

**Issue by mjp9527** [NVIDIA/TensorRT-LLM#149]
<img width="936" alt="image" src="https://github.com/NVIDIA/TensorRT-LLM/assets/54735487/cd2db3f9-005c-4370-8eb4-edbf4262a1b6">
load engine cost 12.5 G，and self.engine.device_memory_size needs 13 G，OOM for 3090 single-gpu

**Comment by jdemouth-nvidia** [comment]
Hi @mjp9527 ,

Can you post your command-lines to build and run the model, please? For example, we need to know the batch size and the sequence length to get a better sense of how much memory is required to run the model.

Thanks,
Julien

**Comment by mjp9527** [comment]
> Hi @mjp9527 ,
> 
> Can you post your command-lines to build and run the model, please? For example, we need to know the batch size and the sequence length to get a better sense of how much memory is required to run the model. 
> 
> Thanks, Julien

Thank you for your reply，all parameters are default parameters in https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/examples/chatglm2-6b/run.py#L30 ,  command is https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/examples/chatglm2-6b/README.md?plain=1#L36

**Comment by byshiue** [comment]
> > Hi @mjp9527 ,
> > Can you post your command-lines to build and run the model, please? For example, we need to know the batch size and the sequence length to get a better sense of how much memory is required to run the model.
> > Thanks, Julien
> 
> Thank you for your reply，all parameters are default parameters in https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/examples/chatglm2-6b/run.py#L30 , command is https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/examples/chatglm2-6b/README.md?plain=1#L36

Can you try adding the flag `--enable_context_fmha` during building engine? Besides, the `max_input_len` and `max_output_len` are 4096 and 2048 (https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/examples/chatglm2-6b/build.py#L91-L92), and hence it requires lots of memory. You can try reducing it if you don't need so long length.

**Comment by byshiue** [comment]
Close this bug because it is in-activate. Feel free to reopen it if needed.
