### ISSUE TITLE
W4A8 AWQ on Ada

### ISSUE THREAD

**Issue by youki-sada** [NVIDIA/TensorRT-LLM#1496]
### System Info

- Intel(R) Core(TM) i9-14900KF
- NVIDIA 4090 GPU
- TensorRT-LLM version 0.9.0
- docker 26.0.0

### Who can help?

@Tracin

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [x] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I followed the official procedure for LLaVA 7b w4a8 quantization.
```bash
python3 examples/quantization/quantize.py \
        --model_dir /weights/llava-1.5-7b-hf \
        --output_dir ./trt_models/llava-1.5-7b-hf/w4a8_awq/1-gpu \
        --dtype float16 \
        --qformat w4a8_awq \
        --calib_size 32
trtllm-build --checkpoint_dir ./trt_models/llava-1.5-7b-hf/w4a8_awq/1-gpu \
        --output_dir /trt_engines/llava-1.5-7b-hf/w4a8_awq/1-gpu \
        --gpt_attention_plugin float16 --gemm_plugin float16 \
        --max_batch_size 16 --max_input_len 2048 --max_output_len 512 --max_multimodal_len 9216 --paged_kv_cache disable
```
https://github.com/NVIDIA/TensorRT-LLM/tree/v0.9.0/examples/multimodal#llava-and-vila

### Expected behavior

I found that we can successfully `trtllm-build` and run quantized model for fp8 and int4_awq. I assumed Ada supports w4a8_awq since it is int4 weight and fp8 activation.

### actual behavior

However, we got `W4A(fp)8 kernel is unsupported on pre-Hopper architectures!` error.
> [TensorRT-LLM][ERROR] tensorrt_llm::common::TllmException: W4A(fp)8 kernel is unsupported on pre-Hopper architectures! (/src/tensorrt_llm/cpp/tensorrt_llm/plugins/weightOnlyGroupwiseQuantMatmulPlugin/weightOnlyGroupwiseQuantMatmulPlugin.cpp:152)

### additional notes

Do you have any plan to support w4a8_awq on Ada Lovelace GPUs?

**Comment by youki-sada** [comment]
We fixed the `trtllm-build` error by upgrading the TensorRT-LLM to `0.10.0.dev2024042300`. But still we faced following error during inference.
```
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
/usr/local/lib/python3.10/dist-packages/torch/nested/__init__.py:166: UserWarning: The PyTorch API of nested tensors is in prototype stage and will change in the near future. (Triggered internally at ../aten/src/ATen/NestedTensorImpl.cpp:177.)
  return _nested.nested_tensor(
terminate called after throwing an instance of 'tensorrt_llm::common::TllmException'
  what():  [TensorRT-LLM][ERROR] Assertion failed: No valid weight only groupwise GEMM tactic(It is usually caused by the failure to execute all candidate configurations of the CUTLASS kernel, please pay attention to the warning information when building the engine.) (/home/jenkins/agent/workspace/LLM/main/L0_PostMerge/tensorrt_llm/cpp/tensorrt_llm/plugins/weightOnlyGroupwiseQuantMatmulPlugin/weightOnlyGroupwiseQuantMatmulPlugin.cpp:451)
```

**Comment by Hongbosherlock** [comment]
afa I kndow, they are working on it.

**Comment by Tracin** [comment]
Exactly as @Hongbosherlock said, we are working on it : )

**Comment by white-wolf-tech** [comment]
Look forward to this masterpiece to save my L40s.
