### ISSUE TITLE
Will batch manager be open-sourced?

### ISSUE THREAD

**Issue by RandMist** [NVIDIA/TensorRT-LLM#150]
I have discovered that the batch manager components in the trtllm C++ runtime are accessible through APIs in the cpp/include folder, while the implementation details are concealed in C++ static libraries. This makes it challenging to implement some optimization techniques based on the batch manager（the c++ runtime inflight batching). Therefore, I would like to inquire whether the batch manager is temporarily or permanently closed-sourced.

**Comment by jdemouth-nvidia** [comment]
See https://github.com/NVIDIA/TensorRT-LLM/issues/74, please.
