### ISSUE TITLE
Is Mistral-7B v0.2 supported?

### ISSUE THREAD

**Issue by vnkc1** [NVIDIA/TensorRT-LLM#1503]
### System Info

A100 GPUs (40GB)

### Who can help?

@byshiue

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

n/a

### Expected behavior

n/a

### actual behavior

n/a

### additional notes

n/a

**Comment by nv-guomingz** [comment]
Yes, the tensorrt-llm already supported the  Mistral-7B v0.2 even we don't clarify it.
You may have a try with latest code.
