### ISSUE TITLE
Is there any feature related to GPT-like models that can be applied to BERT-like models?

### ISSUE THREAD

**Issue by zhangxin81** [NVIDIA/TensorRT-LLM#1517]
Is there any fesature related to GPT-like models that can be applied to BERT-like models?

**Comment by byshiue** [comment]
They have some common optimization idea, like fusing the multi head attention kernel, quantizing the model to int8 or fp8.

**Comment by Ashwin-Ramesh2607** [comment]
hI @byshiue, a related question. Does `BertAttentionPlugin` also use FlashAttention2 that `GptAttention` uses?

**Comment by byshiue** [comment]
Yes.
