### ISSUE TITLE
[Quenstion] TensorRT-LLM cannot do inference when sequence length > 200K?

### ISSUE THREAD

**Issue by 1649759610** [NVIDIA/TensorRT-LLM#1520]
Hi, 

@byshiue  @QiJune 

I build a llama model with long sequence (200K tokens+), but I encouter the problems as follows:
- when doing inference with sequence <195K, it work well.
- when doing inference with sequence >200K， it raise an kernel error as follows.

How is  it going？Or Does TensorRT-LLM not support to infer with sequence >200K currently?  how to solve this problem?

Any help will be appreciated.

![image](https://github.com/NVIDIA/TensorRT-LLM/assets/35913314/9e49717f-7338-4a05-8700-b1ea5ab08c24)

**Comment by byshiue** [comment]
It is a known issue on TRT 9, and planned to be fixed in TRT 10. The reason is because the data size of some intermediate buffer is overflow under int32 data type.

**Comment by 1649759610** [comment]
Thanks for your reply, and expect the TRT 10 version.
