### ISSUE TITLE
can trtllm-build process on cpu? 

### ISSUE THREAD

**Issue by thend-wk** [NVIDIA/TensorRT-LLM#1523]
### System Info

NVIDIA A800 40G

### Who can help?

@byshiue 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

can trtllm-build process on cpu? like parameter load_model_on_cpu in convert_checkpoint.py

### Expected behavior

none

### actual behavior

none

### additional notes

none

**Comment by hijkzzz** [comment]
trtllm-build requires NVIDIA GPUs to timing the kernel perf.

**Comment by thend-wk** [comment]
> trtllm-build requires NVIDIA GPUs to timing the kernel perf.

i get it, thanks
