### ISSUE TITLE
Typo of customAllReduce

### ISSUE THREAD

**Issue by MARD1NO** [NVIDIA/TensorRT-LLM#1526]
https://github.com/NVIDIA/TensorRT-LLM/blob/main/cpp/tensorrt_llm/kernels/customAllReduceKernels.cu#L121

dimension 2 -> dimension 1

**Comment by PerkzZheng** [comment]
thanks. we will fix that soon.

**Comment by MARD1NO** [comment]
> thanks. we will fix that soon.

:D And I wonder why custom AllReduce append the `PUSH_MODE`, it writes their input to other'ranks shared buffer, what is the benefit compare to copy input to local shared buffer?

**Comment by PerkzZheng** [comment]
> > thanks. we will fix that soon.
> 
> :D And I wonder why custom AllReduce append the `PUSH_MODE`, it writes their input to other'ranks shared buffer, what is the benefit compare to copy input to local shared buffer?

Ampere GPUs have some hardware problems that lead to a higher write bw, so we tend to use push_mode by default. there should be minor differences on Hopper or next architectures.

**Comment by MARD1NO** [comment]
> > > thanks. we will fix that soon.
> > 
> > 
> > :D And I wonder why custom AllReduce append the `PUSH_MODE`, it writes their input to other'ranks shared buffer, what is the benefit compare to copy input to local shared buffer?
> 
> Ampere GPUs have some hardware problems that lead to a higher write bw, so we tend to use push_mode by default. there should be minor differences on Hopper or next architectures.

Thanks!
