### ISSUE TITLE
Naming convention of cuBLAS function for MMA CUDA Kernel

### ISSUE THREAD

**Issue by usajid14** [NVIDIA/TensorRT-LLM#1541]
Hi,

What is the naming convention of the MMA CUDA Kernel in Tensorrt-LLM that uses cuBLAS?

e.g. what each thing means in following CUDA Kernel:

 sm90_xmma_gemm_f16f16_f16f32_f32_tn_n_tilesize128x128x64_warpgroupsize1x1x1_execute_segment_k_off_kernel__5x_cublas

@byshiue  @juney-nvidia 

Thank you!

**Comment by byshiue** [comment]
Thank you for the question. Unfortunatelly, this question is related to confidential information, so we cannot reply it.
