### ISSUE TITLE
Detected layernorm nodes in FP16.

### ISSUE THREAD

**Issue by akhoroshev** [NVIDIA/TensorRT-LLM#1544]
When i convert llama model with fp16 precision

```bash
python convert_checkpoint.py --model_dir /llama_dir --dtype float16 --output_dir /llama_dir_trt
trtllm-build --checkpoint_dir /llama_dir_trt  --output_dir  /llama_dir_trt_build --max_batch_size 64 --max_input_len 7168 --max_output_len 1024 --max_num_tokens 32768 --gpt_attention_plugin float16 --gemm_plugin float16 --context_fmha enable --paged_kv_cache enable --remove_input_padding enable
```

I see warnings in logs
```
[05/05/2024-13:14:38] [TRT] [W] Detected layernorm nodes in FP16.
[05/05/2024-13:14:38] [TRT] [W] Running layernorm after self-attention in FP16 may cause overflow. Exporting the model to the latest available ONNX opset (later than opset 17) to use the INormalizationLayer, or forcing layernorm layers to run in FP32 precision can help with preserving accuracy.
```

Does it accumulate in fp16 or in fp32?

My version of trtllm is https://github.com/NVIDIA/TensorRT-LLM/tree/06c0e9b1ec38f981d023a223b212b312cfb62417

**Comment by byshiue** [comment]
Thank you for the report. We will check why do we have such warning. But it should run under FP32.

**Comment by jinluyang** [comment]
Same problem when runnning qwen-14B, using float16, and my sentence output is different from pure pytorch. Using trtllm-0.8.0 @byshiue

**Comment by byshiue** [comment]
> Same problem when runnning qwen-14B, using float16, and my sentence output is different from pure pytorch. Using trtllm-0.8.0 @byshiue

If the results are different from pytorch but the quality is good or the score is similar, it is expected.

**Comment by nv-guomingz** [comment]
Please reopen this  ticket if there's further discussion.

**Comment by akhoroshev** [comment]
tensorrt_llm-0.11.0.dev2024060400

```
[06/09/2024-16:23:35] [TRT] [W] Detected layernorm nodes in FP16.
```

**Comment by akhoroshev** [comment]
@nv-guomingz reopen please

**Comment by nv-guomingz** [comment]
@akhoroshev Could we measure the trtllm engines' output quality via mmlu script?

**Comment by akhoroshev** [comment]
@nv-guomingz  I have no problems with the quality of generation, but this warning is very annoying. Previously @byshiue  said that it should run FP32

**Comment by nv-guomingz** [comment]
> @nv-guomingz I have no problems with the quality of generation, but this warning is very annoying. Previously @byshiue said that it should run FP32

Thanks for confirming, let me check with TRT guys for this warning and send u feedback later.

**Comment by DreamGenX** [comment]
This message seems to go away when using bfloat16 fwiw

**Comment by RobotGF** [comment]
> This message seems to go away when using bfloat16 fwiw

Maybe It only detect FP16?

**Comment by byshiue** [comment]
The issue is fixed on TensorRT 10.3, which is release last week. Close this bug.

**Comment by akhoroshev** [comment]
[09/24/2024-14:02:00] [TRT] [W] Detected layernorm nodes in FP16.

0.14.0.dev2024091000

@byshiue reopen please

**Comment by aboubezari** [comment]
I am seeing this warning log in TensorRT 10.5. Can we please re-open this issue?
