### ISSUE TITLE
4090 llama2-13b Assertion failed: No valid weight only groupwise GEMM tactic

### ISSUE THREAD

**Issue by PaulX1029** [NVIDIA/TensorRT-LLM#1547]
### System Info

4090 ubuntu22 docker  
TensorRT-LLM version: 0.9.0.dev2024040900

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1.python3 ../quantization/quantize.py --model_dir /mnt/checkpoint/models/llama2-13b/ --dtype float16 --qformat int4_awq --awq_block_size 256  --output_dir /mnt/tllm_checkpoint/llama2-13b/quantized_int4-awq --calib_size 64 --batch_size 32

2.trtllm-build --checkpoint_dir /mnt/tllm_checkpoint/llama2-13b/quantized_int4-awq/ --output_dir /mnt/trt_engines/llama2-13b/int4_AWQ/1-gpu/ --gemm_plugin float16 --max_batch_size=32 --max_input_len=2048 --max_output_len=1024 --use_custom_all_reduce disable

3.run.py

### Expected behavior

normal inference

### actual behavior

trt-build warning：
[TensorRT-LLM][WARNING] Have not found any valid GEMM config for shape (m=4096, n=3456, k=5120). Will try to use default or fail at runtime
[TensorRT-LLM][WARNING] Have not found any valid GEMM config for shape (m=8192, n=3456, k=5120). Will try to use default or fail at runtime
[TensorRT-LLM][WARNING] Have not found any valid GEMM config for shape (m=1, n=1280, k=13824). Will try to use default or fail at runtime
[TensorRT-LLM][WARNING] Have not found any valid GEMM config for shape (m=2, n=1280, k=13824). Will try to use default or fail at runtime
[TensorRT-LLM][WARNING] Have not found any valid GEMM config for shape (m=4, n=1280, k=13824). Will try to use default or fail at runtime
[TensorRT-LLM][WARNING] Have not found any valid GEMM config for shape (m=8, n=1280, k=13824). Will try to use default or fail at runtime
[TensorRT-LLM][WARNING] Have not found any valid GEMM config for shape (m=16, n=1280, k=13824). Will try to use default or fail at runtime
inference：
Assert fail
[TensorRT-LLM][ERROR] Assertion failed: No valid weight only groupwise GEMM tactic(It is usually caused by the failure to execute all candidate configurations of the CUTLASS kernel, please pay attention to the warning information when building the engine.) (/home/jenkins/agent/workspace/LLM/main/L0_PostMerge/tensorrt_llm/cpp/tensorrt_llm/plugins/weightOnlyGroupwiseQuantMatmulPlugin/weightOnlyGroupwiseQuantMatmulPlugin.cpp:452)

### additional notes

4090 Does not support the AWQ of the llama2-13b?The AWQ inference of llama2-7b is normal.

**Comment by byshiue** [comment]
Thank you for the report. Currently, the kernel only supports awq_block_size 64 or 128. Could you take a try?

**Comment by PaulX1029** [comment]
@byshiue thank you for reply！awq_block_size 64 or 128 fix this issue. I think i should close it.
