### ISSUE TITLE
Question about weight_sparsity

### ISSUE THREAD

**Issue by hcy682** [NVIDIA/TensorRT-LLM#1559]
# Environment

- GPU properties
   - GPU name  NVIDIA  A800
   - GPU memory size  80GB
- Libraries
   - TensorRT-LLM branch or tag  0.10.0.dev2024043000
   - TensorRT  9.3.0.post12.dev1
   - AMMO  0.9.3
   - CUDA  12.2
   - transformers  4.38.2
   - torch  2.2.2
   - accelerate  0.25.0
- NVIDIA driver version  535.54.03

# Reproduction Steps

I want to use TensorRT-LLM to deploy a llama2 model with semi-structured sparsity(2:4) to get inference acceleration.
So i use [Wanda](https://github.com/locuslab/wanda) to implement semi-structured pruning(2:4) to a llama2 model.

Then convert the model into TensorrtLLM checkpoint format:
 `python convert_checkpoint.py --model_dir /mnt/disk1/hcy/wanda/results/wanda/llama2-7b-semi  --output_dir tllm_checkpoint/llama2-7b-wanda-2:4 --dtype float16`

When compiling model, i set `--weight_sparsity` to enable the sparsity feature:
`trtllm-build --checkpoint_dir tllm_checkpoint/llama2-7b-wanda-2:4  --output_dir trt_engines/llama2-7b-wanda-2:4  --gemm_plugin float16  --weight_sparsity`

# Actual Behavior

The TensorRT logs doesn't report any information about the sparsity.

![image](https://github.com/NVIDIA/TensorRT-LLM/assets/91789722/931e9a97-263c-4b79-86ac-b9bf7ad6b783)

And when i use `benchmark.py` to test the pruned model, there is no acceleration:

`python /mnt/disk1/hcy/TensorRT-LLM/benchmarks/python/benchmark.py  -m llama_7b  --mode plugin  --batch_size "1"  --input_output_len "128,128"  --engine_dir trt_engines/llama2-7b-wanda-2:4`

model with semi-structured sparsity(2:4) ,   generation_tokens_per_second **52.829**

![image](https://github.com/NVIDIA/TensorRT-LLM/assets/91789722/709a1cd4-4e07-46db-8458-eb00716de873)

original model without  sparsity,  generation_tokens_per_second **52.386**

![image](https://github.com/NVIDIA/TensorRT-LLM/assets/91789722/a38c5c30-a36b-42fd-9bdc-0e444072954c)

It seems that the `--weight_sparsity` doesn't work.
So how can i get acceleration of semi-structured sparsity using TensorRT-LLM?
**Thanks!**

# Additional Notes
I have confirmed that the model has semi-structured sparsity (Among each group of four contiguous values, at least two must be zero) by outputting some weights.

**Comment by byshiue** [comment]
Please remove the `--gemm_plugin float16` because sparsity is not supported by gemm plugin.

**Comment by hcy682** [comment]
> Please remove the `--gemm_plugin float16` because sparsity is not supported by gemm plugin.

Thanks!😊 It works!

**Comment by wzhuang-xmu** [comment]
@hcy682 hi, I'm also trying to use tensorrt-llm to speed up sparse llama. How much can llama2-7b model with semi-structured sparsity(2:4) be accelerated? Can you tell me? It would be greatly appreciated if you could.

**Comment by hcy682** [comment]
> @hcy682 hi, I'm also trying to use tensorrt-llm to speed up sparse llama. How much can llama2-7b model with semi-structured sparsity(2:4) be accelerated? Can you tell me? It would be greatly appreciated if you could.

original llama2 model: 
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/91789722/a59db3c7-88eb-4d8b-821d-68b59b6a3a5d)

unstructured pruning (50%):
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/91789722/c9e48309-618c-4bf1-8deb-1e46b37f291f)

semi-structured pruning (2:4):
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/91789722/5351d838-a9b0-42c2-a963-fb735d2c8d18)

**Comment by wzhuang-xmu** [comment]
> > @hcy682 hi, I'm also trying to use tensorrt-llm to speed up sparse llama. How much can llama2-7b model with semi-structured sparsity(2:4) be accelerated? Can you tell me? It would be greatly appreciated if you could.
> 
> original llama2 model: ![image](https://private-user-images.githubusercontent.com/91789722/329511042-a59db3c7-88eb-4d8b-821d-68b59b6a3a5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMjk3ODgsIm5iZiI6MTcxNTMyOTQ4OCwicGF0aCI6Ii85MTc4OTcyMi8zMjk1MTEwNDItYTU5ZGIzYzctODhlYi00ZDhiLTgyMWQtNjhiNTliNmEzYTVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA4MjQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1YTFiMzgyZDg2NjUxNDhiMWNiOGVlNTI5NmFjYzVjMDBlZDU3MTQ4OTMxN2RmZDA5MzNlYTY5MmEzMjFjNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d0Kz1NcZUBA65h00O_i7pf4Kry4MEfEcnxO40Rnzx6c)
> 
> unstructured pruning (50%): ![image](https://private-user-images.githubusercontent.com/91789722/329511819-c9e48309-618c-4bf1-8deb-1e46b37f291f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMjk3ODgsIm5iZiI6MTcxNTMyOTQ4OCwicGF0aCI6Ii85MTc4OTcyMi8zMjk1MTE4MTktYzllNDgzMDktNjE4Yy00YmYxLThkZWItMWU0NmIzN2YyOTFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA4MjQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjNDYzMDQ5M2RmODEwMDc3YjIyMzc3N2FlMTYwNzRkMTRkZmEyMmM5NWE5NWQ1ODBhOThkM2IzZTU4OWY2NjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PCeJUh49muZ3WUeieP7o-kekhp9oTIF_qQPhtQSjjHc)
> 
> semi-structured pruning (2:4): ![image](https://private-user-images.githubusercontent.com/91789722/329512999-5351d838-a9b0-42c2-a963-fb735d2c8d18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMjk3ODgsIm5iZiI6MTcxNTMyOTQ4OCwicGF0aCI6Ii85MTc4OTcyMi8zMjk1MTI5OTktNTM1MWQ4MzgtYTliMC00MmMyLWE5NjMtZmI3MzVkMmM4ZDE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA4MjQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlNmI3Y2NkYTI4MDA4MTMxMGIzYzc2ZTJmYjIzMmY5NjNjNzgyYjk1Yzc5MDc4NDdjYjQzYjM4M2ZjMzFjNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8L--wLfLKefN6-xeqQMl_GjE2dcrpePijdN5F90q7Kc)

Thank you so much!

**Comment by aiiAtelier** [comment]
> > > @hcy682 hi, I'm also trying to use tensorrt-llm to speed up sparse llama. How much can llama2-7b model with semi-structured sparsity(2:4) be accelerated? Can you tell me? It would be greatly appreciated if you could.
> > 
> > 
> > original llama2 model: ![image](https://private-user-images.githubusercontent.com/91789722/329511042-a59db3c7-88eb-4d8b-821d-68b59b6a3a5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMjk3ODgsIm5iZiI6MTcxNTMyOTQ4OCwicGF0aCI6Ii85MTc4OTcyMi8zMjk1MTEwNDItYTU5ZGIzYzctODhlYi00ZDhiLTgyMWQtNjhiNTliNmEzYTVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA4MjQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1YTFiMzgyZDg2NjUxNDhiMWNiOGVlNTI5NmFjYzVjMDBlZDU3MTQ4OTMxN2RmZDA5MzNlYTY5MmEzMjFjNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d0Kz1NcZUBA65h00O_i7pf4Kry4MEfEcnxO40Rnzx6c)
> > unstructured pruning (50%): ![image](https://private-user-images.githubusercontent.com/91789722/329511819-c9e48309-618c-4bf1-8deb-1e46b37f291f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMjk3ODgsIm5iZiI6MTcxNTMyOTQ4OCwicGF0aCI6Ii85MTc4OTcyMi8zMjk1MTE4MTktYzllNDgzMDktNjE4Yy00YmYxLThkZWItMWU0NmIzN2YyOTFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA4MjQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjNDYzMDQ5M2RmODEwMDc3YjIyMzc3N2FlMTYwNzRkMTRkZmEyMmM5NWE5NWQ1ODBhOThkM2IzZTU4OWY2NjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PCeJUh49muZ3WUeieP7o-kekhp9oTIF_qQPhtQSjjHc)
> > semi-structured pruning (2:4): ![image](https://private-user-images.githubusercontent.com/91789722/329512999-5351d838-a9b0-42c2-a963-fb735d2c8d18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMjk3ODgsIm5iZiI6MTcxNTMyOTQ4OCwicGF0aCI6Ii85MTc4OTcyMi8zMjk1MTI5OTktNTM1MWQ4MzgtYTliMC00MmMyLWE5NjMtZmI3MzVkMmM4ZDE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA4MjQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlNmI3Y2NkYTI4MDA4MTMxMGIzYzc2ZTJmYjIzMmY5NjNjNzgyYjk1Yzc5MDc4NDdjYjQzYjM4M2ZjMzFjNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8L--wLfLKefN6-xeqQMl_GjE2dcrpePijdN5F90q7Kc)
> 
> Thank you so much!

Do you see the similar latency reduction under INT8 and FP8 mode?

**Comment by aiiAtelier** [comment]
Is it just about "gemm_plugin float16" or any gemm_plugin? For instance, when int8 matmul or fp8 matmul is enabled, will sparsity still help?

> > Please remove the `--gemm_plugin float16` because sparsity is not supported by gemm plugin.
> 
> Thanks!😊 It works!

**Comment by aiiAtelier** [comment]
Another question is on the direction of 2:4 sparsity: for example, my weights are something like the following . Does it work or it has to be transposed first before pruning? Thanks.

```
weight-check tensor([[  0, -21,   0, -35],
        [  0, -46,   0,  29],
        [-22,   0,  48,   0],
        [  0,   0, -46,  33]], dtype=torch.int8)

```

**Comment by hcy682** [comment]
> Another question is on the direction of 2:4 sparsity: for example, my weights are something like the following . Does it work or it has to be transposed first before pruning? Thanks.
> 
> ```
> weight-check tensor([[  0, -21,   0, -35],
>         [  0, -46,   0,  29],
>         [-22,   0,  48,   0],
>         [  0,   0, -46,  33]], dtype=torch.int8)
> ```

As long as your weights have semi-structured sparsity (for example 2:4--at least two '0' in four contiguous values), you can get acceleration by setting --weight_sparsity when compiling model.
I haven't tried FP8 mode. I have tried INT8 mode, and it is more fast than semi-structured sparsity.
