### ISSUE TITLE
the inference results of TRT-LLM are different from the HF model results(chatglm3-6b tools call mode)

### ISSUE THREAD

**Issue by FanZhang91** [NVIDIA/TensorRT-LLM#1561]
### System Info

NVIDIA GeForce 4090 Gpu

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

        Use HF function just like model.chat(tokenizer, query, history=history) to inference our model, the result is correct. But use tensorrt_llm to inference our model , the result is abnormal。
        The execute script in tensorrt_llm framework is just like this: "python3 ../run.py --input_text "What's new between ChatGLM3-6B and ChatGLM2-6B?" \
                  --max_output_len 50 \
                  --tokenizer_dir chatglm3_6b \
                  --engine_dir trt_engines/chatglm3_6b/fp16/1-gpu")。
           There seems to be a big difference  between ModelRunner.generate() method in tensorrt_llm and .chat() method in HF framework. Can you give me some suggestions to solve this problem?

### Expected behavior

null

### actual behavior

null

### additional notes

null

**Comment by byshiue** [comment]
Could you check that you have aglined the inputs (the input ids before entering the transformer layer are same) and the sampling/beamsearch arguments like topk, topp, temeperature, etc.

**Comment by FanZhang91** [comment]
> Could you check that you have aglined the inputs (the input ids before entering the transformer layer are same) and the sampling/beamsearch arguments like topk, topp, temeperature, etc.

yes, i keep input_ids(tools prior definition + query) and sampling/beamsearch arguments the same and output results are different

**Comment by nv-guomingz** [comment]
Hi @FanZhang91 do u still have further issue or question now? If not, we'll close it soon.
