### ISSUE TITLE
Could not find a version that satisfies the requirement tensorrt-cu12_bindings==10.0.1

### ISSUE THREAD

**Issue by zhangkom** [NVIDIA/TensorRT-LLM#1563]
### System Info

1,Hardware and CUDA info:
NVidia P40
NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0  

TensorRT-LLM souce code commit:
89ba1b1a67d570e41b03da87e5518eaff0d31fbf

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

2, Use a docker image: nvidia/cuda:11.6.1-devel-ubuntu20.04
Following the steps:
docker run --rm --runtime=nvidia --gpus all --entrypoint /bin/bash -it nvidia/cuda:11.6.1-devel-ubuntu20.04

//Install dependencies, TensorRT-LLM requires Python 3.10
apt-get update && apt-get -y install python3.10 python3-pip openmpi-bin libopenmpi-dev git

and all above are right.

3, But, when pip3 install tensorrt_llm -U --pre --extra-index-url https://pypi.nvidia.com

Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.1.5-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (26 kB)
Collecting nvidia-nvjitlink-cu12
  Using cached nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
ERROR: Could not find a version that satisfies the requirement tensorrt-cu12_bindings==10.0.1 (from tensorrt-cu12->tensorrt==10.0.1->tensorrt_llm) (from versions: none)
ERROR: No matching distribution found for tensorrt-cu12_bindings==10.0.1 (from tensorrt-cu12->tensorrt==10.0.1->tensorrt_llm)

4, pip install requirements.txt
ERROR: Could not find a version that satisfies the requirement requirements.txt (from versions: none)
ERROR: No matching distribution found for requirements.txt

How can I do, please?

### additional notes

none

**Comment by Shixiaowei02** [comment]
Hi! TensorRT-LLM does not support CUDA 11.x, please using the development container to avoid more error messages. Thank you!
