### ISSUE TITLE
InternVL-Chat-V1.5 support

### ISSUE THREAD

**Issue by chiquitita-101** [NVIDIA/TensorRT-LLM#1567]
pleaseeeeee, InternVL-Chat-V1.5 surpasses many proprietary multi-modal models, very powerful, pleaseeeee.

**Comment by diandianliu** [comment]
Hi, Is InternVL-Chat-V1.5 suported now?

**Comment by nv-guomingz** [comment]
> Hi, Is InternVL-Chat-V1.5 suported now?

Hi @AdamzNV @ncomly-nvidia  @juney-nvidia , would please add some comments here?

**Comment by AdamzNV** [comment]
We don't support this model yet. According to download statistics from Hugging Face, its popularity has been declining for the past half month.

**Comment by Hukongtao** [comment]
mark

**Comment by LatentLinker** [comment]
mark

**Comment by LIMr1209** [comment]
mark

**Comment by AmazDeng** [comment]
> We don't support this model yet. According to download statistics from Hugging Face, its popularity has been declining for the past half month.

@AdamzNV 
Please take a look at this ranking list. The score of the InternVL model is in the top 2.
https://rank.opencompass.org.cn/leaderboard-multimodal/?m=REALTIME

**Comment by zhaocc1106** [comment]
Can try: https://github.com/NetEase-Media/grps_trtllm

**Comment by nv-guomingz** [comment]
Hi @AmazDeng    we just enabled internvl2 supporting. do u still have further issue or question now? If not, we'll close it soon.

**Comment by LatentLinker** [comment]
@nv-guomingz Wow, that looks great

**Comment by AmazDeng** [comment]
> Hi [@AmazDeng](https://github.com/AmazDeng) we just enabled internvl2 supporting. do u still have further issue or question now? If not, we'll close it soon.

@nv-guomingz
Thank you for your work. Could you please provide the link to the relevant documentation?

**Comment by nv-guomingz** [comment]
> > Hi [@AmazDeng](https://github.com/AmazDeng) we just enabled internvl2 supporting. do u still have further issue or question now? If not, we'll close it soon.
> 
> [@nv-guomingz](https://github.com/nv-guomingz) Thank you for your work. Could you please provide the link to the relevant documentation?

https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/multimodal#internvl2

**Comment by AmazDeng** [comment]
> https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/multimodal#internvl2

@nv-guomingz
I checked the documentation, and tensorrt-llm only supports InternVL2-1B to InternVL2-26B. So, does tensorrt-llm support InternVL2-40B?

**Comment by nv-guomingz** [comment]
> > https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/multimodal#internvl2
> 
> [@nv-guomingz](https://github.com/nv-guomingz) I checked the documentation, and tensorrt-llm only supports InternVL2-1B to InternVL2-26B. So, does tensorrt-llm support InternVL2-40B?

I'm not the owner of this model but I think 40B should be supported if it's just a large varaint of InternVL2.
