### ISSUE TITLE
Does enc-dec model support inflight bathing? 

### ISSUE THREAD

**Issue by Oldpan** [NVIDIA/TensorRT-LLM#1573]
I found that trt-llm-dev supports paged KV cache for encoder-decoder models (like Nougat). Does the encoder-decoder model work with inflight batching? Or can we use other batching methods other than static batching to improve performance?  Thanks

**Comment by schetlur-nv** [comment]
@Oldpan for now we only support static batching for encoder-decoder models. But we plan inflight batching support in the coming weeks. Please keep an eye out. Feel free to reopen the issue if you have more questions.

**Comment by thanhlt998** [comment]
@schetlur-nv do you have any progresses here?

**Comment by symphonylyh** [comment]
@thanhlt998 releasing in this week's main branch release (today/tomorrow). Stay tuned.

**Comment by Oldpan** [comment]
@symphonylyh  
Thanks for the update, does this support encoders like nougat that require image inputs? I see that only bart and t5 are mentioned in the updated examples.
<img width="860" alt="image" src="https://github.com/NVIDIA/TensorRT-LLM/assets/9389127/ae776619-dd56-442c-8c39-d8592cb55a33">
