### ISSUE TITLE
Could not found tensorrt after install tensorrt-llm

### ISSUE THREAD

**Issue by thisissum** [NVIDIA/TensorRT-LLM#1576]
### System Info

I use ngc container nvcr.io/nvidia/pytorch:24.04-py3 on A100 GPU.

### Who can help?

@byshiue 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Just run
`pip3 install tensorrt_llm -U --pre --extra-index-url https://pypi.nvidia.com`
and 
`python3 -c "import tensorrt_llm"`

### Expected behavior

Expected `python3 -c "import tensorrt_llm"` run successfully.

### actual behavior

No module named 'tensorrt'

### additional notes

Null

**Comment by Shixiaowei02** [comment]
We have verified that TensorRT cannot be installed correctly together with PyTorch in the `nvcr.io/nvidia/pytorch:24.04-py3` image and are trying to fix it. Please use the recommended methods in the README. Thank you!

    ```bash
    # Obtain and start the basic docker image environment (optional).
    docker run --rm --runtime=nvidia --gpus all --entrypoint /bin/bash -it nvidia/cuda:12.1.0-devel-ubuntu22.04

    # Install dependencies, TensorRT-LLM requires Python 3.10
    apt-get update && apt-get -y install python3.10 python3-pip openmpi-bin libopenmpi-dev git

    # Install the latest preview version (corresponding to the main branch) of TensorRT-LLM.
    # If you want to install the stable version (corresponding to the release branch), please
    # remove the `--pre` option.
    pip3 install tensorrt_llm -U --pre --extra-index-url https://pypi.nvidia.com

    # Check installation
    python3 -c "import tensorrt_llm"
    ```

**Comment by chengshan008** [comment]
You should include this in the guide documentation. I really spent a lot of time figuring out these environmental issues.
