### ISSUE TITLE
Is there a version of nvidia-ammo for Windows?

### ISSUE THREAD

**Issue by Milesld** [NVIDIA/TensorRT-LLM#1579]
Thank you for your great work!
I'm trying to run tensorrt-llm on my windows pc. When I try to quantize the llma2 model to int8, I meet an error about nvidia-ammo. I try to install this by "pip download --extra-index-url https://pypi.nvidia.com nvidia-ammo", I meet the error of "RuntimeError: Didn't find wheel for nvidia-ammo 0.9.4". After I check the versions provided by https://pypi.nvidia.com/nvidia-ammo/, it seems that there isn't a version for windows.
So, I wonder how can I install nvidia-ammo on my computer.
Thank you.

**Comment by nv-guomingz** [comment]
Hi @Milesld, nvidia-ammo had been renamed to nvidia-modelopt (https://pypi.nvidia.cn/nvidia-modelopt/) and you can download the windows version from above link.

**Comment by nv-guomingz** [comment]
Hi @Milesld ,Did u install nvidia modelopt(aka nvidia ammo)for windows succesfully?
If so ,could we close this ticket?

**Comment by nv-guomingz** [comment]
Hi @Milesld please feel free to reopen this ticket if needed.
