### ISSUE TITLE
convert qwen 110b  gptq  checkpoint的时候，qkv_bias 的shape不能被3整除

### ISSUE THREAD

**Issue by CallmeZhangChenchen** [NVIDIA/TensorRT-LLM#1589]
![094c99ee1cd6bcfd56a550c1a68d80c2](https://github.com/NVIDIA/TensorRT-LLM/assets/57712520/4cb57a97-bee3-4bc6-ab09-e6779f0fda76)

**Comment by jershi425** [comment]
@CallmeZhangChenchen Thank you for the feedback. We have not supported Qwen-110B yet. We will support and validate it soon.

**Comment by Tlntin** [comment]
i got same error in qwen1.5-32b, i think may caused by GQA(group query attention).
I fix up it in this, pr [link](https://github.com/NVIDIA/TensorRT-LLM/pull/1637)

**Comment by nv-guomingz** [comment]
This week's update will contain the fixing submmited by @Tlntin .

**Comment by Hukongtao** [comment]
The model can be converted and built into the engine normally, but the inference results are garbled. Have you ever encountered this?
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/16505966/4131466e-f5de-4d6c-ba9e-03498b0ad444)

**Comment by Tlntin** [comment]
> The model can be converted and built into the engine normally, but the inference results are garbled. Have you ever encountered this? ![image](https://private-user-images.githubusercontent.com/16505966/346576754-4131466e-f5de-4d6c-ba9e-03498b0ad444.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0NDU0NDgsIm5iZiI6MTcyMDQ0NTE0OCwicGF0aCI6Ii8xNjUwNTk2Ni8zNDY1NzY3NTQtNDEzMTQ2NmUtZjVkZS00ZDZjLWJhOWUtMDM0OThiMGFkNDQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDEzMjU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlYzJjZGZjM2VhMGZjNjkzMGM1MGQ2OWNlOTI5NTZiZGYxZGIwOGU1MjczNjJlMjg1NjRhZWI2YzRlMjlhMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PJu9-65Iouy-QOfDuxfyoMVAT002oFYYwzlyh1dNqUY)

i think you need update auto-gptq and transformers to latest.

**Comment by Hukongtao** [comment]
> > The model can be converted and built into the engine normally, but the inference results are garbled. Have you ever encountered this? ![image](https://private-user-images.githubusercontent.com/16505966/346576754-4131466e-f5de-4d6c-ba9e-03498b0ad444.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0NDU0NDgsIm5iZiI6MTcyMDQ0NTE0OCwicGF0aCI6Ii8xNjUwNTk2Ni8zNDY1NzY3NTQtNDEzMTQ2NmUtZjVkZS00ZDZjLWJhOWUtMDM0OThiMGFkNDQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDEzMjU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlYzJjZGZjM2VhMGZjNjkzMGM1MGQ2OWNlOTI5NTZiZGYxZGIwOGU1MjczNjJlMjg1NjRhZWI2YzRlMjlhMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PJu9-65Iouy-QOfDuxfyoMVAT002oFYYwzlyh1dNqUY)
> 
> i think you need update auto-gptq and transformers to latest.

![image](https://github.com/NVIDIA/TensorRT-LLM/assets/16505966/b4b1c726-c0f7-460e-89ad-5c654853aa9c)
still have the problem

**Comment by Tlntin** [comment]
> > > The model can be converted and built into the engine normally, but the inference results are garbled. Have you ever encountered this? ![image](https://private-user-images.githubusercontent.com/16505966/346576754-4131466e-f5de-4d6c-ba9e-03498b0ad444.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0NDU0NDgsIm5iZiI6MTcyMDQ0NTE0OCwicGF0aCI6Ii8xNjUwNTk2Ni8zNDY1NzY3NTQtNDEzMTQ2NmUtZjVkZS00ZDZjLWJhOWUtMDM0OThiMGFkNDQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDEzMjU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlYzJjZGZjM2VhMGZjNjkzMGM1MGQ2OWNlOTI5NTZiZGYxZGIwOGU1MjczNjJlMjg1NjRhZWI2YzRlMjlhMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PJu9-65Iouy-QOfDuxfyoMVAT002oFYYwzlyh1dNqUY)
> > 
> > 
> > i think you need update auto-gptq and transformers to latest.
> 
> ![image](https://private-user-images.githubusercontent.com/16505966/346784056-b4b1c726-c0f7-460e-89ad-5c654853aa9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0OTQwOTQsIm5iZiI6MTcyMDQ5Mzc5NCwicGF0aCI6Ii8xNjUwNTk2Ni8zNDY3ODQwNTYtYjRiMWM3MjYtYzBmNy00NjBlLTg5YWQtNWM2NTQ4NTNhYTljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDAyNTYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmNjUxYjViMDg1Njc0Njc1YWUzN2IzM2Q2NzIzZjM3NzlhYjkxZDAzMDk1ZTViOGE1ODMyYjAxYzBmOWUwMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ncJF-RKMR0Idp8iwmEkYQrDWlVNVwQfgkTDoX7o_c8I) still have the problem

after update, have you build engine again?

**Comment by Hukongtao** [comment]
> > > > The model can be converted and built into the engine normally, but the inference results are garbled. Have you ever encountered this? ![image](https://private-user-images.githubusercontent.com/16505966/346576754-4131466e-f5de-4d6c-ba9e-03498b0ad444.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0NDU0NDgsIm5iZiI6MTcyMDQ0NTE0OCwicGF0aCI6Ii8xNjUwNTk2Ni8zNDY1NzY3NTQtNDEzMTQ2NmUtZjVkZS00ZDZjLWJhOWUtMDM0OThiMGFkNDQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDEzMjU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlYzJjZGZjM2VhMGZjNjkzMGM1MGQ2OWNlOTI5NTZiZGYxZGIwOGU1MjczNjJlMjg1NjRhZWI2YzRlMjlhMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PJu9-65Iouy-QOfDuxfyoMVAT002oFYYwzlyh1dNqUY)
> > > 
> > > 
> > > i think you need update auto-gptq and transformers to latest.
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/16505966/346784056-b4b1c726-c0f7-460e-89ad-5c654853aa9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0OTQwOTQsIm5iZiI6MTcyMDQ5Mzc5NCwicGF0aCI6Ii8xNjUwNTk2Ni8zNDY3ODQwNTYtYjRiMWM3MjYtYzBmNy00NjBlLTg5YWQtNWM2NTQ4NTNhYTljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDAyNTYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmNjUxYjViMDg1Njc0Njc1YWUzN2IzM2Q2NzIzZjM3NzlhYjkxZDAzMDk1ZTViOGE1ODMyYjAxYzBmOWUwMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ncJF-RKMR0Idp8iwmEkYQrDWlVNVwQfgkTDoX7o_c8I) still have the problem
> 
> after update, have you build engine again?

Yes,  I re-update rank0.safetensors and rank0.engine 
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/16505966/a28921b6-2862-4f03-a9af-adb5dd190f83)

**Comment by Hukongtao** [comment]
The v0.10.0 version may have some problems. I used the latest code from the main branch and it was aligned.

**Comment by tianzuishiwo** [comment]
> auto-gpt

I meet the same problems，do you solve the problem? 兄弟！

**Comment by tianzuishiwo** [comment]
> The model can be converted and built into the engine normally, but the inference results are garbled. Have you ever encountered this? ![image](https://private-user-images.githubusercontent.com/16505966/346576754-4131466e-f5de-4d6c-ba9e-03498b0ad444.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NTg2MjQsIm5iZiI6MTcyNDY1ODMyNCwicGF0aCI6Ii8xNjUwNTk2Ni8zNDY1NzY3NTQtNDEzMTQ2NmUtZjVkZS00ZDZjLWJhOWUtMDM0OThiMGFkNDQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDA3NDUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxYWY2ZGQ2ZTI5NmFjODkzMjFkZTMzNmFiMDQzNWFlMDg3OWE2MDQ4NTk1ZjNkMzRlYjRkZmVmMGNjN2U4YTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.icboTgnu0vRwenrtiBVKVWLfnzJCyIyrzJLWE2A0FrU)

I meet the same problems，do you solve the problem? 兄弟！
