### ISSUE TITLE
Question: Do we support input log probabilties with C++ inflight backend?

### ISSUE THREAD

**Issue by sindhuvahinis** [NVIDIA/TensorRT-LLM#1593]
Hello, Seeing this issue https://github.com/NVIDIA/TensorRT-LLM/issues/238, it was said `The log probs of input tokens are not supported now, it will be supported in near future.` 

Are we supporting log probs of input tokens right now with C++ inflight batching backend?

**Comment by byshiue** [comment]
Yes, it should be supported now.

**Comment by nv-guomingz** [comment]
Hi @sindhuvahinis do u still have further issue or question now? If not, we'll close it soon.
