### ISSUE TITLE
rotary_scaling build command doesnt work

### ISSUE THREAD

**Issue by avianion** [NVIDIA/TensorRT-LLM#1595]
### System Info

Nvidia H100 NVL x 2

### Who can help?

@kaiyux @juney-nvidia @byshiue 

In the documentation for llama, it states

Using RoPE Scaling

RoPE scaling is supported through GPT Attention Plugin. You can add --rotary_scaling <type> <factor> during the build command to enable it.

    The value of type can be either linear and dynamic.
    The value of factor can be any value larger than 1.0.

The implementation is identical to Huggingface's. Please refer to https://huggingface.co/docs/transformers/model_doc/llama2#transformers.LlamaConfig.rope_scaling for more details.

However using --rotary_scaling command does not work with trtllm-build or convert_checkpoint.py

Manually changing the value in config.json has no effect.

So what are we supposed to do to use rope scaling?

### Information

- [X] The official example scripts
- [x] My own modified scripts

### Tasks

- [x] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [x] My own task or dataset (give details below)

### Reproduction

Using RoPE Scaling
Try to add --rotary_scaling <type> <factor> during the build command, it will tell you there is no such command. In the latest version.

tensorrt-llm==0.10.0.dev2024050700
nvidia/cuda:12.4.1-devel-ubuntu22.04 
nvcr.io/nvidia/tritonserver:24.04-trtllm-python-py3

### Expected behavior

You can use rope scaling call as the parameter suggests in the documentation

### actual behavior

Rope scaling cannot be implemented in the build command or the create checkpoint command

### additional notes

How to implement rope or rotary scaling

**Comment by hijkzzz** [comment]
You could manually modify the rope base value in the Huggingface checkpoint.

**Comment by avianion** [comment]
@hijkzzz great. this actually worked. nice.

do any other values need to be modified?

for example, now that the context window is effectively 32k, surely in the build the max_input_length and max tokens need to be modifeid to 32k as well? or does it happen automagically?

**Comment by JohnGiorgi** [comment]
Also facing this issue. While setting the `rope_scaling` key in the model config seems to work, it's strange the docs specify the arg `--rotary_scaling` but the build command doesn't support it!

**Comment by avianion** [comment]
There should be a tutorial on the best settings for RoPE scaling with tensorrtllm. In other frameworks the support and documentation for RoPE scaling is better. hard to determine the best settings without that.

**Comment by byshiue** [comment]
The arguments about model configuration in build.py only works when it is not set in the config.json of the model. Namely, the priority of model config is higher. So, you need to change the config.json directly to setup the custom rope_scaling.

**Comment by TheCodeWrangler** [comment]
I am experiencing similar struggles

I have a pre-trained model with lora adapters (llama3, bfloat16)

The `trtllm_build` command contains the flag: `--multi_block_mode enable`

When I add `"rope_scaling": {"type": "dynamic", "factor": 1.5},` to the base model `config.json` the model still compiles and the values look correct in the engine files `config.json`

HOWEVER when I load my first set of adapter weights (which loaded successfully before adding the rope_scaling params) I experience a runtime error.

`terminate called after throwing an instance of 'tensorrt_llm::common::TllmException'
  what():  [TensorRT-LLM][ERROR] CUDA runtime error in ::cudaEventDestroy(event): an illegal memory access was encountered (/tmp/tritonbuild/tensorrtllm/tensorrt_llm/cpp/include/tensorrt_llm/runtime/cudaEvent.h:87)`

The model was trained with rope scaling so the compiled engine without rope scaling does not have the performance I trained for, and the compiled engine with rope scaling throws exceptions

Any guidance would be appreciated

**Comment by avianion** [comment]
@TheCodeWrangler try linear scaling. 

It worked fine for me. So far dynamic doesn't work at all on tensorrtllm no matter what we tried.

**Comment by avianion** [comment]
@byshiue can you try to see if dynamic scaling works? linear scaling works fine. if dynamic scaling doesnt work at all, then this is indeed a bug.

**Comment by TheCodeWrangler** [comment]
I just reran with "linear" instead of "dynamic"

I can confirm that the same steps now compile, load, and are able to generate (but give bad quality)

**Comment by avianion** [comment]
@TheCodeWrangler our quality was fine with rotary scaling 2.0. at 4.0 it started to degrade. using llama 3 70b. With linear scaling

I think the quality could be improved with dynamic, but as we have mentioned, it doesn't work at all.

**Comment by avianion** [comment]
@TheCodeWrangler make sure you increase your rotary base.

so lets say your rotary base is initially 500,000

if you use rope scaling 1.5

then you need to increase it to 750,000

**Comment by byshiue** [comment]
Since the original issue is solved and there is another bug to discuss the new issue, I will close this bug.
