### ISSUE TITLE
Huggingface Transformers version should be bumped

### ISSUE THREAD

**Issue by michaelroyzen** [NVIDIA/TensorRT-LLM#16]
Pinning `transformers==4.31.0` is incorrect, as it causes incorrect behavior with Code Llama conversion. The minimum supported transformers version with Code Llama is 4.33.1.

**Comment by byshiue** [comment]
Thank you for the remind. We will try upgrading the transformers version. It may takes some time to verify the correctness.

**Comment by byshiue** [comment]
This issue is fixed by this MR https://github.com/NVIDIA/TensorRT-LLM/pull/148, you can try on latest main branch. Close this bug. Feel free to reopen if needed.
