### ISSUE TITLE
Using the smoothquant to quantify the llama33b model, an oom problem occurred.

### ISSUE THREAD

**Issue by shhn1** [NVIDIA/TensorRT-LLM#160]
I use A100 80g to quantify llama 33b, why does oom appear during hf_llama_convert? The script I use is this:
`python3 hf_llama_convert.py -i /llama-models/llama-33b-hf -o /llama/smooth_llama_33B/sq0.8/ -sq 0.8 --tensor-parallelism 2 --storage-type fp16
`
The log information is in this txt file. 
[log.txt](https://github.com/NVIDIA/TensorRT-LLM/files/13185851/log.txt)

**Comment by juney-nvidia** [comment]
@shhn1 Thanks for reporting this. 
By checking the log.txt, it looks that you are invoking the command outside of TensorRT-LLM docker? Can you share the concrete steps of building/running TensorRT-LLM and running this conversion script? 
I am asking this to ensure that enough information can be gathered so it is easier for our engineers to re-produce the issue internally.

June

**Comment by shhn1** [comment]
Thank you for your reply : )
I follow the steps to build the docker and TensorRT-LLM:
https://github.com/NVIDIA/TensorRT-LLM/blob/1c4a0ee24cb0480c20a721c4bc6a77fc51644a22/docs/source/installation.md#build-step-by-step

Based on the above docker image, I install TensorRT-LLM Quantization Toolkit from this link. https://github.com/NVIDIA/TensorRT-LLM/tree/1c4a0ee24cb0480c20a721c4bc6a77fc51644a22/examples/quantization

There's one thing I'm confused about when loading the model. The model of llama 33b is only 62GB, but when loading the hf model at this step, I found that the memory of 2 GPUs was occupied by 60G+. 
`model = LlamaForCausalLM.from_pretrained(args.in_file, device_map="auto")`
https://github.com/NVIDIA/TensorRT-LLM/blob/1c4a0ee24cb0480c20a721c4bc6a77fc51644a22/examples/llama/hf_llama_convert.py#L174
<img width="652" alt="截屏2023-10-27 17 08 46" src="https://github.com/NVIDIA/TensorRT-LLM/assets/55838930/a907127b-f748-469e-8330-1d2bec102f67">


Then when the smooth process runs to layer-17, the above oom error in log.txt will appear.
https://github.com/NVIDIA/TensorRT-LLM/blob/1c4a0ee24cb0480c20a721c4bc6a77fc51644a22/examples/llama/hf_llama_convert.py#L103

I don't know why this happens? Is there any way to solve this? Thank you : )

**Comment by wm2012011492** [comment]
Hi @shhn1 , could you try `model = LlamaForCausalLM.from_pretrained(args.in_file, torch_dtype="auto", device_map="auto") `? Without setting `torch_dtype="auto"`, the datatype of the loaded weights will become float32.

**Comment by shhn1** [comment]
> Hi @shhn1 , could you try `model = LlamaForCausalLM.from_pretrained(args.in_file, torch_dtype="auto", device_map="auto") `? Without setting `torch_dtype="auto"`, the datatype of the loaded weights will become float32.

Thanks a lot for your kind reply! It works great for me : )
