### ISSUE TITLE
Question- language model onnx files location

### ISSUE THREAD

**Issue by apbose** [NVIDIA/TensorRT-LLM#1605]
Hi, I had a general question
For LLM models eg: llama, when we build the engine from the .safetensors and the json file created in `convert_checkpoint.py` , while building the TRT engine in `tensorrt_llm/commands/build.py`  is the engine directly created from the safetensors or is it converted to some intermediate format, eg : onnx. If so where is this (eg: onnx file) created?

**Comment by byshiue** [comment]
The engine is created from the safetensors.
