### ISSUE TITLE
Question: when Running Whisper TRT Max 90% GPU Utilization but 20% Tensor Core Utilization 

### ISSUE THREAD

**Issue by shashikr2** [NVIDIA/TensorRT-LLM#1607]
I have requestion why is GPU utilization is around 90% but Tensor Core Utilization is less than 25%. When I am running Whisper TRT on A10G card?

**Comment by symphonylyh** [comment]
Hi @shashikr2 , do you have some details on how you measured these? And especially at what phase you're observing this, the audio encoder phase, or the decoder phase?

**Comment by nv-guomingz** [comment]
Hi @shashikr2 do u still have further issue or question now? If not, we'll close it soon.
