### ISSUE TITLE
Why is the default value for `opt_num_tokens` equal to `max_batch_size * max_beam_width`, instead of a value like `0.5 * max_num_tokens`?

### ISSUE THREAD

**Issue by vnkc1** [NVIDIA/TensorRT-LLM#1613]
### System Info

n/a

### Who can help?

@byshiue @kaiyux 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

n/a

### Expected behavior

n/a

### actual behavior

n/a

### additional notes

Would it be more reasonable to set `opt_num_tokens` set to a value like half of `max_num_tokens` since `max_batch_size * max_beam_width` is not proportionate to the number of tokens in a batch.

**Comment by byshiue** [comment]
It is because we assume the model still runs the pure generation phase in most time. And for the generation phase, the input shape is `max_batch_size * max_beam_width`.
