### ISSUE TITLE
Possible version mismatch when building from source code on Linux

### ISSUE THREAD

**Issue by mosalov** [NVIDIA/TensorRT-LLM#1622]
### System Info

CPU architecture - ` x86_64`
GPU - `NVIDIA RTX A5000`
Driver version - `545.23.08`
TensorRT-LLM branch - `main`

### Who can help?

@juney-nvidia
@byshiue

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

As per https://nvidia.github.io/TensorRT-LLM/installation/build-from-source-linux.html#building-a-tensorrt-llm-docker-image
1. `make -C docker release_build`
2. `make -C docker release_run`
3. Then inside of the container: `pip3 freeze | grep tensorrt-llm`

### Expected behavior

I expect to see the last released version - 0.10.0.

### actual behavior

It is 0.11.0:
```
tensorrt-llm @ file:///app/tensorrt_llm/tensorrt_llm-0.11.0.dev2024051400-cp310-cp310-linux_x86_64.whl#sha256=abe93926086405cdc2b429b6a40ad7dc73787118cbac1599b3c03404e6f5f072
```

### additional notes

Is it just a mismatch in the version output, so it is otherwise safe to use?

**Comment by byshiue** [comment]
The version is correct. You can find it here https://github.com/NVIDIA/TensorRT-LLM/blob/bf0a5af/tensorrt_llm/version.py#L15. 

We are finalizing the development v0.10.0 and start developing v0.11.0. So, it is dev branch of v0.11.0.
