### ISSUE TITLE
Build with fine-tuned-huggingface-whisper

### ISSUE THREAD

**Issue by lionsheep24** [NVIDIA/TensorRT-LLM#1624]
### System Info

I have pretrained whisper-large-v2 model with my custom dataset, and tried to build tensorrt-llm.
But I got `[Errno 2] No such file or directory: '/workspace/models/whisper-large-v2/large-v2.pt'` when I run python3 build.py, even though given model dir has no .pt file. I found hugigngface-distil-whisper in README.md but I could not find large-v2, huggingface whisper implementation in this repo. 
Is there way to build huggingface whisper?

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

1. Dockerfile

```
# Use an official NVIDIA PyTorch image as a parent image
FROM nvidia/cuda:12.1.0-devel-ubuntu22.04

# Set a working directory
WORKDIR /workspace

ENV MPI_HOME=/usr/local/mpi
ENV PATH="$MPI_HOME/bin:$PATH"
ENV LD_LIBRARY_PATH="$MPI_HOME/lib:$LD_LIBRARY_PATH"

# Install necessary packages and dependencies for Triton Server
RUN apt-get update && apt-get -y install python3.10 python3-pip openmpi-bin libopenmpi-dev git

RUN pip install --upgrade pip setuptools wheel
RUN pip install tensorrt_llm -U --pre --extra-index-url https://pypi.nvidia.com
RUN git clone https://github.com/NVIDIA/TensorRT-LLM.git /workspace/TensorRT-LLM
WORKDIR /workspace/TensorRT-LLM
RUN pip install -r examples/whisper/requirements.txt

RUN apt-get update && \
    apt-get install -y git-lfs && \
    git lfs install


WORKDIR /workspace

COPY models /workspace/models
```
2. command
`python3 build.py --model_dir /workspace/models/whisper-large-v2 --model_name large-v2 --dtype float16 --max_batch_size 16 --output_dir whisper-large-v2-tensorrt-llm --use_gpt_attention_plugin float16 --use_gemm_plugin float16 --use_bert_attention_plugin float16 --enable_context_fmha`
3. files in "models" folder 

- added_tokens.json 
- generation_config.json 
- merges.txt
- normalizer.json
- pytorch_model.bin
- special_tokens_map.json
- tokenizer.json
- vocab.json
- config.json
- gitattributes
- model.safetensors 
- preprocessor_config.json 
- README.md
- tf_model.h5 
- tokenizer_config.json

**Comment by lionsheep0724** [comment]
Updates here.
I found some [discussions ](https://github.com/openai/whisper/discussions/830)about convert whisper to huggingface file, including changing layer name.
If I proceed vice versa to the work in the link above, could it solve my problem?

**Comment by yuekaizhang** [comment]
> Updates here. I found some [discussions ](https://github.com/openai/whisper/discussions/830)about convert whisper to huggingface file, including changing layer name. If I proceed vice versa to the work in the link above, could it solve my problem?

@lionsheep0724 
You are correct. You need to convert huggingface file back into openai checkpoint file. You may refer this file https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/whisper/distil_whisper/convert_from_distil_whisper.py.

**Comment by lionsheep24** [comment]
@yuekaizhang Yeah I have seen that page but I’m not sure the way it convert huggingface to openai works well even if the model is not distil-whisper
(because of difference in layer name or architecture by itself)

**Comment by yuekaizhang** [comment]
> @yuekaizhang Yeah I have seen that page but I’m not sure the way it convert huggingface to openai works well even if the model is not distil-whisper (because of difference in layer name or architecture by itself)

@lionsheep0724  You could first try to use the script to convert. If you find some errors, you may need to check the model_state_dict keys to make sure they could match.

**Comment by lionsheep24** [comment]
Hi @yuekaizhang,

I've successfully compiled hf-whisper to tensorrt-llm and am currently looking to deploy the model using Triton. However, I'm encountering some confusion regarding the expected I/O format for the server.

example/whisper run.py appears to process inputs as audio file paths. Contrastingly, my understanding is that Triton generally expects inputs in the form of tensors or arrays (audio or mel features). The [guide docs](https://nvidia.github.io/TensorRT-LLM/quick-start-guide.html) seem to use a similar input format as run.py for llama, (input_text) as shown in the documentation examples.

Could you clarify how I should handle the input format to properly integrate tensorrt-llm-whisper with Triton? Any guidance or pointers would be greatly appreciated!

Thank you!

**Comment by yuekaizhang** [comment]
> Hi @yuekaizhang,
> 
> I've successfully compiled hf-whisper to tensorrt-llm and am currently looking to deploy the model using Triton. However, I'm encountering some confusion regarding the expected I/O format for the server.
> 
> example/whisper run.py appears to process inputs as audio file paths. Contrastingly, my understanding is that Triton generally expects inputs in the form of tensors or arrays (audio or mel features). The [guide docs](https://nvidia.github.io/TensorRT-LLM/quick-start-guide.html) seem to use a similar input format as run.py for llama, (input_text) as shown in the documentation examples.
> 
> Could you clarify how I should handle the input format to properly integrate tensorrt-llm-whisper with Triton? Any guidance or pointers would be greatly appreciated!
> 
> Thank you!

@lionsheep0724  Check this python backend integration first https://github.com/k2-fsa/sherpa/tree/master/triton/whisper. We will support triton-trtllm-backend in the future.

**Comment by lionsheep24** [comment]
@yuekaizhang

Thank you for sharing and quick reply!

I reviewed the link you mentioned and have some questions regarding the implementation:

1. In the tensorrt-llm Whisper example, run.py loads the model via WhisperTRTLLM, encodes with tensorrt_llm.runtime.session.Session, and decodes with tensorrt_llm.runtime.GenerationSession. client.py in your shared link sends an audio array to a deployed Triton server, and the response appears to be in encoded bytes (i.e., the transcribed result).

2. The script for launching Triton (launch_server.sh) only provides the compiled model path to tritonserver. According to the details mentioned, the model’s input will be an array and its output should be text.

Considering the above, I have a question about how tritonserver runs the compiled model: Does the decode_wav_file function in run.py correspond to the model's inference process in tritonserver? (i.e., does tritonserver perform encode and decode operations via tensorrt_llm.runtime.session.Session and tensorrt_llm.runtime.GenerationSession?)

P.S. : I'm considering building a pytriton server with some modifications to the decode_wav_file function. Will there be any performance degradation when using the trtllm backend with pytriton? What are your thoughts on my approach?

**Comment by yuekaizhang** [comment]
> @yuekaizhang
> 
> Thank you for sharing and quick reply!
> 
> I reviewed the link you mentioned and have some questions regarding the implementation:
> 
> 1. In the tensorrt-llm Whisper example, run.py loads the model via WhisperTRTLLM, encodes with tensorrt_llm.runtime.session.Session, and decodes with tensorrt_llm.runtime.GenerationSession. client.py in your shared link sends an audio array to a deployed Triton server, and the response appears to be in encoded bytes (i.e., the transcribed result).
> 2. The script for launching Triton (launch_server.sh) only provides the compiled model path to tritonserver. According to the details mentioned, the model’s input will be an array and its output should be text.
> 
> Considering the above, I have a question about how tritonserver runs the compiled model: Does the decode_wav_file function in run.py correspond to the model's inference process in tritonserver? (i.e., does tritonserver perform encode and decode operations via tensorrt_llm.runtime.session.Session and tensorrt_llm.runtime.GenerationSession?)
> 
> P.S. : I'm considering building a pytriton server with some modifications to the decode_wav_file function. Will there be any performance degradation when using the trtllm backend with pytriton? What are your thoughts on my approach?

See here https://github.com/k2-fsa/sherpa/blob/master/triton/whisper/model_repo_whisper_trtllm/whisper/1/model.py.

Trtllm backend is not ready for enc-dec style models for now. You may try to use pytriton to directly warp the decode_wav_file function. Also, you are welcome to contribute once the pytriton solution ready.

**Comment by lionsheep24** [comment]
@yuekaizhang
Yeah let me follow example you shared first, then pytriton will be my next step.
Currently, I launched tritonserver with my compiled model. But I'm doubtful whether the pytriton backend can fully leverage the capabilities of the tensorrt-llm engine.

**Comment by lionsheep24** [comment]
@yuekaizhang 
Updates here!
I'm trying to compile my fine-tuned-huggingface-whisper but It does not work with below errors:

```
[06/05/2024-12:35:27] [TRT] [E] 4: [convolutionNode.cpp::validateTypes::76] Error Code 4: Internal Error (WhisperEncoder/conv1/conv1d/CONVOLUTION_0: input and kernel weights must have same type)
Traceback (most recent call last):
  File "/usr/local/bin/trtllm-build", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/commands/build.py", line 489, in main
    parallel_build(source, build_config, args.output_dir, workers,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/commands/build.py", line 368, in parallel_build
    passed = build_and_save(rank, rank % workers, ckpt_dir,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/commands/build.py", line 327, in build_and_save
    engine = build_model(build_config,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/commands/build.py", line 320, in build_model
    return build(model, build_config)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/builder.py", line 841, in build
    model(**inputs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/module.py", line 40, in __call__
    output = self.forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/enc_dec/model.py", line 1797, in forward
    x = self.conv1(x)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/module.py", line 40, in __call__
    output = self.forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/layers/conv.py", line 212, in forward
    return conv1d(input, self.weight.value,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/functional.py", line 3375, in conv1d
    output_2d = _create_tensor(layer.get_output(0), layer)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/functional.py", line 607, in _create_tensor
    assert trt_tensor.shape.__len__(
AssertionError: tensor WhisperEncoder/conv1/conv1d/CONVOLUTION_0_output_0 has an invalid shape
```
My build procedure is totally same with readme.md in example, as below:
1. python3 convert_from_distil_whisper.py --model_name /workspace/models/whisper-large-v2/2 --output_dir /workspace/models/whisper-openai --output_name large-v2
2. python3 convert_checkpoint.py --model_dir /workspace/models/whisper-openai --output_dir /workspace/models/whisper-tensorrt-llm --model_name large-v2 --dtype float16 --logits_dtype float16
3. trtllm-build --checkpoint_dir /workspace/models/whisper-tensorrt-llm/encoder --output_dir /workspace/models/1/encoder --paged_kv_cache disable --moe_plugin disable --enable_xqa disable --use_custom_all_reduce disable --max_batch_size 16 --gemm_plugin disable --bert_attention_plugin float16 --remove_input_padding disable

Let me share my Dockerfile, if you want to reproduce my issue.

```
# Use the NVIDIA CUDA image with development tools and Ubuntu 22.04
FROM nvidia/cuda:12.1.0-devel-ubuntu22.04
#FROM nvcr.io/nvidia/cuda:12.1.0-devel-ubuntu22.04
# Set the working directory
WORKDIR /workspace

# Environment variables for MPI
ENV MPI_HOME=/usr/local/mpi
ENV PATH="$MPI_HOME/bin:$PATH"
ENV LD_LIBRARY_PATH="$MPI_HOME/lib:$LD_LIBRARY_PATH"

# Install necessary packages
RUN apt-get update && apt-get -y install python3.10 python3-pip openmpi-bin libopenmpi-dev git git-lfs

# copy pip.conf
COPY .tmp/pip.conf /root/.config/pip/pip.conf
# copy cacert.pem
COPY .tmp/cacert.pem /opt/conda/lib/python3.10/site-packages/certifi/cacert.pem

# Inform Git about the CA bundle for certificate verification
RUN git config --global http.sslCAInfo /opt/conda/lib/python3.10/site-packages/certifi/cacert.pem

# Upgrade pip and install necessary Python packages
RUN pip install --upgrade pip setuptools wheel


# Clone the TensorRT-LLM repository
RUN git clone https://github.com/NVIDIA/TensorRT-LLM.git /workspace/TensorRT-LLM && \
    cd /workspace/TensorRT-LLM && \
    git checkout b777bd6
WORKDIR /workspace/TensorRT-LLM
#RUN pip install -r examples/whisper/requirements.txt

RUN pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com tensorrt-llm==0.11.0.dev2024060400 tiktoken datasets kaldialign openai-whisper librosa soundfile safetensors transformers janus

# Setup Git LFS
RUN git lfs install

# Copy necessary models and assets into the image
COPY models/whisper-large-v2 /workspace/models/whisper-large-v2
```

**Comment by nv-guomingz** [comment]
Hi @lionsheep24 do u still have further issue or question now? If not, we'll close it soon.
