### ISSUE TITLE
Fail to build Mixtral-8x22B-v0.1 with w4a16

### ISSUE THREAD

**Issue by gloritygithub11** [NVIDIA/TensorRT-LLM#1630]
### System Info

tensorrt                  10.0.1
tensorrt-cu12             10.0.1
tensorrt-cu12-bindings    10.0.1
tensorrt-cu12-libs        10.0.1
tensorrt-llm              0.10.0.dev2024050700

on 8*A100 40G

### Who can help?

@byshiue 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
set -e

export MODEL_DIR=/mnt/memory
export MODEL_OUTPUT_DIR=/app/models/tmp
export MODEL_NAME=Mixtral-8x22B-v0.1
export LD_LIBRARY_PATH=/usr/local/tensorrt/lib:$LD_LIBRARY_PATH
export PATH=/usr/local/tensorrt/bin:$PATH
export DTYPE=bfloat16
export PYTHONPATH=/app/tensorrt-llm:$PYTHONPATH

export CUDA_VISIBLE_DEVICES=0,1,2,3

python ../llama/convert_checkpoint.py \
    --model_dir $MODEL_DIR/${MODEL_NAME} \
    --output_dir $MODEL_OUTPUT_DIR/trt_models/${MODEL_NAME}/w4a16/4-gpu-tp \
    --dtype $DTYPE \
    --use_weight_only \
    --weight_only_precision int4 \
    --tp_size 4 \
    --load_model_on_cpu


trtllm-build \
    --checkpoint_dir $MODEL_OUTPUT_DIR/trt_models/${MODEL_NAME}/w4a16/4-gpu-tp \
    --output_dir $MODEL_OUTPUT_DIR/trt_engines/${MODEL_NAME}/w4a16/4-gpu-tp \
    --gemm_plugin $DTYPE \
    --gpt_attention_plugin $DTYPE \
    --max_batch_size 1 \
    --max_input_len 2048 \
    --max_output_len 1024


```

### Expected behavior

build success

### actual behavior

trtllm-build with following error

```
[05/20/2024-01:09:58] [TRT] [I] Global timing cache in use. Profiling results in this builder pass will be stored.
[05/20/2024-01:10:02] [TRT] [I] [GraphReduction] The approximate region cut reduction algorithm is called.
[05/20/2024-01:10:02] [TRT] [I] Detected 13 inputs and 1 output network tensors.
[05/20/2024-01:10:03] [TRT] [E] 2: Assertion engine failed. 
[05/20/2024-01:10:03] [TRT] [E] 2: [wtsEngineUtils.cpp::buildWtsEngine::104] Error Code 2: Internal Error (Assertion engine failed. )
[05/20/2024-01:10:03] [TRT-LLM] [E] Engine building failed, please check the error log.
[05/20/2024-01:10:03] [TRT-LLM] [I] Total time of building all engines: 00:00:25
```

### additional notes

is Mixtral-8x22B-v0.1 with w4a16 supported right now? where I can get the error log?

**Comment by byshiue** [comment]
MoE models don't support w4a16. Same to this issue https://github.com/NVIDIA/TensorRT-LLM/issues/1580. Close this one.

**Comment by gloritygithub11** [comment]
@byshiue I know Mixtral 8x7b does not support for int4_awq now and you are working on it.
I can build Mixtral 8x7b with w4a16, so this is why I create the new issue for Mixtral 8x22b to support w4a16 here.

**Comment by byshiue** [comment]
If you want to mention pure weight only w4a16, it is not supported, too.
