### ISSUE TITLE
In the process of quantizing fp8, how to switch the form of quantization, E4M3 or E5M2?

### ISSUE THREAD

**Issue by fuxuelinwudi** [NVIDIA/TensorRT-LLM#1631]
### System Info

11

### Who can help?

11

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

11

### Expected behavior

11

### actual behavior

11

### additional notes

11

**Comment by fuxuelinwudi** [comment]
please answer my question, thx

**Comment by byshiue** [comment]
In inference, we only use the `e4m3` format and there is not option.
