### ISSUE TITLE
Does TensorRT-LLM support A10?

### ISSUE THREAD

**Issue by 2292384454** [NVIDIA/TensorRT-LLM#1633]
### System Info

I didn't find A10 on the [Support Matrix](https://nvidia.github.io/TensorRT-LLM/reference/support-matrix.html#support-matrix), and when I run it on my A10 server, I got a segmentation fault. Doesn't TensorRT-LLM support A10?

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [x] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

python3 -c "import tensorrt_llm"

### Expected behavior

successfully import trt-llm

### actual behavior

[a8532d3de39c:00219] *** Process received signal ***
[a8532d3de39c:00219] Signal: Segmentation fault (11)
[a8532d3de39c:00219] Signal code: Address not mapped (1)
[a8532d3de39c:00219] Failing at address: 0x18
[a8532d3de39c:00219] [ 0] /usr/lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7ff7a001d520]
[a8532d3de39c:00219] [ 1] /usr/lib/x86_64-linux-gnu/libcuda.so.1(+0x2b924a)[0x7ff6e7aa124a]
[a8532d3de39c:00219] [ 2] /usr/lib/x86_64-linux-gnu/libcuda.so.1(+0x24ea26)[0x7ff6e7a36a26]
[a8532d3de39c:00219] [ 3] /usr/lib/x86_64-linux-gnu/libcuda.so.1(+0x2c7258)[0x7ff6e7aaf258]
[a8532d3de39c:00219] [ 4] /usr/local/lib/python3.10/dist-packages/tensorrt_llm/libs/libtensorrt_llm.so(+0x23e9991)[0x7ff575cde991]
[a8532d3de39c:00219] [ 5] /usr/local/lib/python3.10/dist-packages/tensorrt_llm/libs/libtensorrt_llm.so(+0x23e9ac0)[0x7ff575cdeac0]
[a8532d3de39c:00219] [ 6] /usr/lib/x86_64-linux-gnu/libc.so.6(+0x99ee8)[0x7ff7a0074ee8]
[a8532d3de39c:00219] [ 7] /usr/local/lib/python3.10/dist-packages/tensorrt_llm/libs/libtensorrt_llm.so(+0x243c209)[0x7ff575d31209]
[a8532d3de39c:00219] [ 8] /usr/local/lib/python3.10/dist-packages/tensorrt_llm/libs/libtensorrt_llm.so(+0x23dd27f)[0x7ff575cd227f]
[a8532d3de39c:00219] [ 9] /usr/local/lib/python3.10/dist-packages/tensorrt_llm/libs/libtensorrt_llm.so(+0x2408c2a)[0x7ff575cfdc2a]
[a8532d3de39c:00219] [10] /usr/local/lib/python3.10/dist-packages/tensorrt_llm/libs/libtensorrt_llm.so(_ZN12tensorrt_llm6common6LoggerC1Ev+0xc1)[0x7ff574093181]
[a8532d3de39c:00219] [11] /usr/local/lib/python3.10/dist-packages/tensorrt_llm/libs/libtensorrt_llm.so(_ZN12tensorrt_llm6common6Logger9getLoggerEv+0x3f)[0x7ff574093a4f]
[a8532d3de39c:00219] [12] /usr/local/lib/python3.10/dist-packages/tensorrt_llm/libs/libnvinfer_plugin_tensorrt_llm.so(_ZN12tensorrt_llm7plugins17LoraPluginCreatorC1Ev+0x107)[0x7ff5331e04e7]
[a8532d3de39c:00219] [13] /usr/local/lib/python3.10/dist-packages/tensorrt_llm/libs/libnvinfer_plugin_tensorrt_llm.so(getPluginCreators+0x97c)[0x7ff533206b0c]
[a8532d3de39c:00219] [14] /usr/local/lib/python3.10/dist-packages/tensorrt_llm/libs/libnvinfer_plugin_tensorrt_llm.so(initTrtLlmPlugins+0x48)[0x7ff533206cf8]
[a8532d3de39c:00219] [15] /usr/lib/x86_64-linux-gnu/libffi.so.8(+0x7e2e)[0x7ff79fd05e2e]
[a8532d3de39c:00219] [16] /usr/lib/x86_64-linux-gnu/libffi.so.8(+0x4493)[0x7ff79fd02493]
[a8532d3de39c:00219] [17] /usr/lib/python3.10/lib-dynload/_ctypes.cpython-310-x86_64-linux-gnu.so(+0xa3e9)[0x7ff79d2fe3e9]
[a8532d3de39c:00219] [18] /usr/lib/python3.10/lib-dynload/_ctypes.cpython-310-x86_64-linux-gnu.so(+0x13302)[0x7ff79d307302]
[a8532d3de39c:00219] [19] python3(_PyObject_MakeTpCall+0x25b)[0x55e7528f2a7b]
[a8532d3de39c:00219] [20] python3(_PyEval_EvalFrameDefault+0x6a79)[0x55e7528eb629]
[a8532d3de39c:00219] [21] python3(_PyFunction_Vectorcall+0x7c)[0x55e7528fc9fc]
[a8532d3de39c:00219] [22] python3(_PyEval_EvalFrameDefault+0x6bd)[0x55e7528e526d]
[a8532d3de39c:00219] [23] python3(_PyFunction_Vectorcall+0x7c)[0x55e7528fc9fc]
[a8532d3de39c:00219] [24] python3(_PyEval_EvalFrameDefault+0x198c)[0x55e7528e653c]
[a8532d3de39c:00219] [25] python3(+0x13f9c6)[0x55e7528e19c6]
[a8532d3de39c:00219] [26] python3(PyEval_EvalCode+0x86)[0x55e7529d7256]
[a8532d3de39c:00219] [27] python3(+0x23ae2d)[0x55e7529dce2d]
[a8532d3de39c:00219] [28] python3(+0x15ac59)[0x55e7528fcc59]
[a8532d3de39c:00219] [29] python3(_PyEval_EvalFrameDefault+0x2a27)[0x55e7528e75d7]
[a8532d3de39c:00219] *** End of error message ***
Segmentation fault (core dumped)

### additional notes

Does TensorRT-LLM support A10?

**Comment by byshiue** [comment]
A10 is supported. Could you share the full error log and the reprodueced steps?

**Comment by 2292384454** [comment]
> A10 is supported. Could you share the full error log and the reprodueced steps?

Thank you very much for your reply. I found that it was a problem with my driver, not with trt llm. I reinstalled my driver and the problem was resolved. I will close this issue. Thank you again for your reply, and I wish you a pleasant work experience.
