### ISSUE TITLE
Baichuan v2_13b run.py error

### ISSUE THREAD

**Issue by anxietymonger** [NVIDIA/TensorRT-LLM#164]
`build.py` with `--model_version v2_13b` specified was finished successfully (float16), but when try to execute `run.py`, an error occurred:

```
AttributeError: 'BaichuanTokenizer' object has no attribute 'sp_model'
```

Sorry for lacking details, since my working environment doesn't allow me to copy logs out.

**Comment by byshiue** [comment]
It looks a bug of transformers, please try install transformers==4.33.1

**Comment by anxietymonger** [comment]
Reinstalling transformers==4.33.1 (previously 4.34.1) fixed the problem. Closing the issue. Thank you very much for your help.
