### ISSUE TITLE
failed to use "stop_words_list" for tensorrt-llm==0.9.0

### ISSUE THREAD

**Issue by AGI-player** [NVIDIA/TensorRT-LLM#1642]
i use GenerationExecutorWorker for web service, using the parameters stop_words_list = [["hello, yes"]] by modifying the as_inference_request function in exectutor.py as follow:
<img width="486" alt="image" src="https://github.com/NVIDIA/TensorRT-LLM/assets/99712469/ba3b6fd0-f240-46a8-8ee8-5baea5a69bf2">
<img width="510" alt="image" src="https://github.com/NVIDIA/TensorRT-LLM/assets/99712469/cf70bddf-21f8-4155-aad5-ec830cf37c1f">
the ir parameter as follow:
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/99712469/15256616-a4d2-4d2a-8419-1fa9b0835d63)
then failed
<img width="493" alt="image" src="https://github.com/NVIDIA/TensorRT-LLM/assets/99712469/49e690c3-e683-42e5-9152-93205c50846f">

**Comment by byshiue** [comment]
Please follow the issue template to share the full end to end reproduced steps. Thank you for cooperation.

**Comment by AGI-player** [comment]
> Please follow the issue template to share the full end to end reproduced steps. Thank you for cooperation.


the trt engine was built with:
trtllm-build  --gemm_plugin float16 --max_batch_size=128 --max_input_len=8192 --max_output_len=0 --gpt_attention_plugin float16 --paged_kv_cache enable --remove_input_padding enable --context_fmha enable --max_num_tokens 104448

then use the TensorRT-LLM/examples/apps/fastapi_server.py for web service as follow:
python3 -m apps.fastapi_server path/to/engine/ path/to/tokenizer --port 8001

for parameters setting (temperature and stop words list), i modified the TensorRT-LLM/examples/apps/fastapi_server.py file
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/99712469/73d7428d-326f-4f24-b5b6-c045aa7a1611)

 and tensorrt_llm/exectutor.py file
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/99712469/69a5d24b-6bbe-426a-8e77-0e7fb6f949ba)


if i didn't pass the stop_words_list, it works well. 
<img width="457" alt="image" src="https://github.com/NVIDIA/TensorRT-LLM/assets/99712469/c5c2c80e-7f39-4a14-be03-d71df8a3f3d7">
<img width="628" alt="image" src="https://github.com/NVIDIA/TensorRT-LLM/assets/99712469/14ba8c07-c9ae-462c-81d9-d6bb17222ace">

It failed when i use the stop words list
<img width="499" alt="image" src="https://github.com/NVIDIA/TensorRT-LLM/assets/99712469/c1f97ae4-275a-4f62-9b8b-c4f0663ca0c6">

**Comment by Superjomn** [comment]
The `stop_words_list` is not supported well in 0.9.0, maybe you can try the latest main branch, we have refactored the `GenerationExecutor`, and the [stop_words](https://gitlab-master.nvidia.com/ftp/tekit/-/blob/main/tensorrt_llm/executor.py#L106) are supported.

**Comment by AGI-player** [comment]
> The `stop_words_list` is not supported well in 0.9.0, maybe you can try the latest main branch, we have refactored the `GenerationExecutor`, and the [stop_words](https://gitlab-master.nvidia.com/ftp/tekit/-/blob/main/tensorrt_llm/executor.py#L106) are supported.

I update the trt version to 0.11.0.dev2024052100，it doesn't work...

**Comment by fan-niu** [comment]
@Superjomn @byshiue  Same question, can you give an example of successful use of stop_words or stop_words_list? Thank you, I am currently using the service started by tensorrtllm_backend, the commit number is 75b0964, and the corresponding tensorrtllm version number is f430a4b

**Comment by nv-guomingz** [comment]
Hi @fan-niu do u still have further issue or question now? If not, we'll close it soon.
