### ISSUE TITLE
Performance (latency and throughput) of Phi-3-mini-128k-instruct on A100 (80GB) is very poor

### ISSUE THREAD

**Issue by kelkarn** [NVIDIA/TensorRT-LLM#1652]
### Environment

If applicable, please include the following:

**CPU architecture:** x86_64
**CPU/Host memory size:** Standard NC24ads A100 v4 (24 vcpus, 220 GiB memory)

### GPU properties

GPU name: A100
GPU memory size: 80GB
I am using the Azure offering of this GPU: Standard NC24ads A100 v4 (24 vcpus, 220 GiB memory)

### Libraries

**TensorRT-LLM branch or tag:** `main` branch, commit: https://github.com/NVIDIA/TensorRT-LLM/tree/bf0a5afc92f4b2b3191e9e55073953c1f600cf2d
**Container used:** custom built, using `build.py` via instructions here: https://github.com/triton-inference-server/tensorrtllm_backend/tree/ae52bce3ed8ecea468a16483e0dacd3d156ae4fe (internally, it seems to use Triton 24.03)

**NVIDIA driver version:** Driver Version: 535.54.03

OS: Ubuntu 22.04 (Jammy)

## Reproduction Steps

I followed the steps here: https://github.com/NVIDIA/TensorRT-LLM/tree/bf0a5afc92f4b2b3191e9e55073953c1f600cf2d/examples/phi

First build the checkpoint:
```
pip install -r requirements.txt

export MODEL_TYPE="Phi-3-mini-128k-instruct"
python ./convert_checkpoint.py --model_type ${MODEL_TYPE} \
                    --model_dir "microsoft/${MODEL_TYPE}" \
                    --output_dir ./phi-checkpoint \
                    --dtype float16
```

Then, build the engine:
```
trtllm-build \
    --checkpoint_dir ./phi-3-checkpoint \
    --output_dir ./phi-3-engine-full-32k \
    --weight_only_precision int4 \
    --context_fmha enable \
    --gemm_plugin float16 \
    --gpt_attention_plugin float16 \
    --remove_input_padding enable \
    --max_input_len 32768 \
    --max_output_len 1024 \
    --workers 1 \
    --max_batch_size 8
```

Then, serve this model in Triton (with an `ensemble`). Triton starts up successfully, then, I run the following `perf_analyzer` command:

```
perf_analyzer -m ensemble --input-data /azureuser/llm_inputs.json --measurement-interval 45000 --service-kind triton --request-rate-range 0.5 --request-distribution constant --stability-percentage 1000 -i grpc -u localhost:8001 --shape max_tokens:1 --shape text_input:1 --verbose-csv --collect-metrics
```

The `llm_inputs.json` for me has the following structure (in reality it has 319 documents):

```
{
    "data": [
        {
            "text_input": [
                "MY 1ST DOCUMENT TEXT HERE"
            ],
            "max_tokens": [
                1024
            ]
        },
        {
            "text_input": [
                "MY 2ND DOCUMENT TEXT HERE"
            ],
            "max_tokens": [
                1024
            ]
        },
        ...
    ]
}
```

Expected Behavior

I expect much better performance than what I saw, given that the Phi-3 int4 quantized model is only ~2.3GB in size.

Actual Behavior

The performance I get, when I make calls with `perf_analyzer` is as follows:

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-e61e9c48-7fff-0fef-39d2-cfcff25afeb7"><div dir="ltr" style="margin-left:-1.5pt;" align="left">
Input tokens count  | p50 ms   | p90 ms   | avg. client infer/sec  
-- | -- | -- | --
2K  | 8526.14 | 8557.86 | 0.44
4K  | 10718.53 | 10813.11 | 0.36
8K  | 14030.94 | 15030.53 | 0.28
16K  | 20306.08 | 24641.63 | 0.20
32K  | 20537.95 | 37949.98 | 0.15
</div></b>

Additional Notes

Provide any additional context here you think might be useful for the TensorRT-LLM team to help debug this issue (such as experiments done, potential things to investigate).

CC @kaiyux @byshiue.

**Comment by hijkzzz** [comment]
You should use flash decoding/ or increase the batch size to speed up the small model.
The model is too small to take full advantage of the computing resources.

**Comment by dhruvmullick** [comment]
@kelkarn did you figure out the reason for the poor performance? 

@hijkzzz, even if we increase the batch size, the latencies will not change. Shouldn't the expected latencies be much better than this?
