### ISSUE TITLE
Qwen-VL supports multiple images？

### ISSUE THREAD

**Issue by Hukongtao** [NVIDIA/TensorRT-LLM#1653]
Background ： 
I hope to use TensorRT-LLM to accelerate the qwen-vl model, But each of my query contains multiple images. After I read the docs and code,  
https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/qwenvl/README.md
https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/qwenvl/run.py#L332-L339
I think, qwen-vl supports multiple images.    
So I followed the steps in the documentation to try to speed up the model, and it worked.  
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/16505966/f5b84ab8-9bb4-4c2c-b343-1454be5044d3)      
            
Because max_batch_size=8，each request supports a maximum of 8 pictures I think. But something strange happened.   
When the number of images does not exceed 5, the model output after acceleration can be completely aligned with the output before acceleration. On the contrary, when the number of images exceeds 5, there is a big difference between the output of the model after acceleration and the output before acceleration.    
I can gave a example:    
The first generated token's score before accelerate:
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/16505966/45299801-5869-4543-9a82-c613cd4ff8a4)

The first generated token's score after accelerate:
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/16505966/a993041f-e679-40a9-b994-4885228bcf1c)

**Comment by Hukongtao** [comment]
The maximum value difference before and after acceleration is more than 1, which I think is a bit unreasonable. When the number of images does not exceed 5, the value difference is within an acceptable range. I think this is weird and I don't know what's causing it.

**Comment by calico-niko** [comment]
Same problem, when input image more than 1, the ouput result was different from huggingface model. @Hukongtao Have you found any solution?

**Comment by Hukongtao** [comment]
> Same problem, when input image more than 1, the ouput result was different from huggingface model. @Hukongtao Have you found any solution?

I didn't solve the problem. But this difference has no impact on my accuracy. So I suggest you measure the accuracy.
