### ISSUE TITLE
[Feature request] kv cache reuse policy feature request

### ISSUE THREAD

**Issue by akhoroshev** [NVIDIA/TensorRT-LLM#1654]
According to the [docs](https://github.com/NVIDIA/TensorRT-LLM/blob/5d8ca2faf74c494f220c8f71130340b513eea9a9/docs/source/kv_cache_reuse.md?plain=1#L50) reusable blocks are evicted based on LRU.

LRU is good approach. But I know that for some queries (promts) they won't be reused and I want these queries not to remain in the cache and not crowd out the queries I need.

I think this can be easily implemented by adding "priority" to the request.

**Comment by akhoroshev** [comment]
I mean  replacing the LRU key `timestamp` with the pair `(priority, timestamp)` for example

**Comment by schetlur-nv** [comment]
Thanks for the request @akhoroshev. We are discussing some ideas on more sophisticated caching policies, and we will consider this as part of that. Closing the issue for now.
