### ISSUE TITLE
Is there a roadmap to support TRT10.1?

### ISSUE THREAD

**Issue by KANGRuipeng** [NVIDIA/TensorRT-LLM#1663]
### System Info

 A100

### Who can help?

@n

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

None

### Expected behavior

Support TRT10.1

### actual behavior

Newest release depend on trt9.3

### additional notes

No

**Comment by nv-guomingz** [comment]
Hi @KANGRuipeng we'll update to trt 10.6 in coming 0.15 release
Feel free to reopen this ticket if needed.
