### ISSUE TITLE
could kv-reuse be used on v100 + next-trtllm-release, or a100 + trtllm-v0.9.0

### ISSUE THREAD

**Issue by forrestjgq** [NVIDIA/TensorRT-LLM#1671]
Hello, I followed https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/kv_cache_reuse.md and tried build model on v100 with trtllm v0.9.0, and it reports 
```
[TensorRT-LLM][ERROR] tensorrt_llm::common::TllmException: [TensorRT-LLM][ERROR] Assertion failed: PagedKV Context FMHA is not supported on Volta (/home/jenkins/agent/workspace/LLM/release-0.9/L0_PostMerge/tensorrt_llm/cpp/tensorrt_llm/plugins/gptAttentionCommon/gptAttentionCommon.cpp:466)
```

I wonder:
1. I note that this document is not provided in trtllm-v0.9.0, could it be enabled on A100 for llama3, with trtllm-v0.9.0
2. In next trtllm-release, could this feature be enabled on V100 for llama3?

**Comment by byshiue** [comment]
1. This feature should be supported in v0.9.0. Please let us know if you encounter any issue.
2. Supporting paged fmha on V100 is not in our roadmap now.

**Comment by forrestjgq** [comment]
> 1. This feature should be supported in v0.9.0. Please let us know if you encounter any issue.
> 2. Supporting paged fmha on V100 is not in our roadmap now.

@byshiue Thanks! What a pity.
