### ISSUE TITLE
Why fpA-int8 group&zero GEMV is removed?

### ISSUE THREAD

**Issue by leizhao1234** [NVIDIA/TensorRT-LLM#1673]

**Comment by byshiue** [comment]
Could you share more details about which file do you mention?

**Comment by leizhao1234** [comment]
https://github.com/NVIDIA/TensorRT-LLM/blob/main/cpp/tensorrt_llm/kernels/weightOnlyBatchedGemv/common.h#L33

enum class KernelType
{
    FP16Int4Groupwise,
    BF16Int4Groupwise,
    FP16Int8PerChannel,
    BF16Int8PerChannel,
    FP16Int4PerChannel,
    BF16Int4PerChannel
};

**Comment by byshiue** [comment]
What do you mean for "removed"?
