### ISSUE TITLE
Converting Meta-Llama-3-70B-Instruct into TensorrtLLM checkpoint format fails

### ISSUE THREAD

**Issue by erickbp** [NVIDIA/TensorRT-LLM#1677]
### System Info

Operating system: Linux (ubuntu 20.04)
vCPUs: 24
Memory (GiB): 220.0
CPU Architecture: x64
GPU: 1x a100 (80GB)

$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Thu_Mar_28_02:18:24_PDT_2024
Cuda compilation tools, release 12.4, V12.4.131
Build cuda_12.4.r12.4/compiler.34097967_0

### Who can help?

@Tracin @byshiue 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

sudo docker run --rm --runtime=nvidia --gpus all --entrypoint /bin/bash -it nvidia/cuda:12.1.0-devel-ubuntu22.04
apt-get update && apt-get -y install python3.10 python3-pip openmpi-bin libopenmpi-dev git
pip3 install tensorrt_llm -U --pre --extra-index-url https://pypi.nvidia.com
git clone https://github.com/NVIDIA/TensorRT-LLM
cd TensorRT-LLM/examples/llama/
pip install -r requirements.txt

...download Meta-Llama-3-70B-Instruct model from HF...

python3 convert_checkpoint.py --model_dir ./Meta-Llama-3-70B-Instruct/ --output_dir ./tllm_checkpoint_1gpu_fp16_wq --dtype float16 --use_weight_only --weight_only_precision int8

### Expected behavior

Convert the model into TensorrtLLM checkpoint format

### actual behavior

[TensorRT-LLM] TensorRT-LLM version: 0.11.0.dev2024052100
0.11.0.dev2024052100
Traceback (most recent call last):
  File "/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 459, in <module>
    main()
  File "/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 451, in main
    convert_and_save_hf(args)
  File "/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 387, in convert_and_save_hf
    execute(args.workers, [convert_and_save_rank] * world_size, args)
  File "/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 410, in execute
    f(args, rank)
  File "/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 374, in convert_and_save_rank
    llama = LLaMAForCausalLM.from_hugging_face(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/model.py", line 280, in from_hugging_face
    llama = convert.from_hugging_face(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/convert.py", line 1337, in from_hugging_face
    llama.load(weights)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/modeling_utils.py", line 421, in load
    raise RuntimeError(
RuntimeError: Required but not provided tensors:{'transformer.layers.61.attention.qkv.per_channel_scale', 'transformer.layers.3.mlp.fc.per_channel_scale', 'transformer.layers.38.mlp.gate.per_channel_scale', 'transformer.layers.79.attention.qkv.per_channel_scale', 'transformer.layers.4.attention.dense.per_channel_scale', 'transformer.layers.78.mlp.gate.per_channel_scale', 'transformer.layers.68.mlp.proj.per_channel_scale', 'transformer.layers.58.mlp.fc.per_channel_scale', 'transformer.layers.14.attention.qkv.per_channel_scale', 'transformer.layers.26.mlp.fc.per_channel_scale', 'transformer.layers.16.mlp.gate.per_channel_scale', 'transformer.layers.68.mlp.fc.per_channel_scale', 'transformer.layers.28.mlp.gate.per_channel_scale', 'transformer.layers.79.mlp.proj.per_channel_scale', 'transformer.layers.18.attention.qkv.per_channel_scale', 'transformer.layers.4.mlp.fc.per_channel_scale', 'transformer.layers.45.mlp.proj.per_channel_scale', 'transformer.layers.72.mlp.fc.per_channel_scale', 'transformer.layers.12.attention.qkv.per_channel_scale', 'transformer.layers.60.mlp.gate.per_channel_scale', 'transformer.layers.66.mlp.gate.per_channel_scale', 'transformer.layers.51.mlp.fc.per_channel_scale', 'transformer.layers.69.attention.qkv.per_channel_scale', 'transformer.layers.29.attention.qkv.per_channel_scale', 'transformer.layers.32.mlp.proj.per_channel_scale', 'transformer.layers.69.mlp.proj.per_channel_scale', 'transformer.layers.15.attention.dense.per_channel_scale', 'transformer.layers.73.mlp.gate.per_channel_scale', 'transformer.layers.76.attention.dense.per_channel_scale', 'transformer.layers.24.attention.dense.per_channel_scale', 'transformer.layers.10.mlp.gate.per_channel_scale', 'transformer.layers.12.mlp.proj.per_channel_scale', 'transformer.layers.39.mlp.fc.per_channel_scale', 'transformer.layers.59.attention.dense.per_channel_scale', 'transformer.layers.57.mlp.gate.per_channel_scale', 'transformer.layers.76.mlp.proj.per_channel_scale', 'transformer.layers.78.attention.dense.per_channel_scale', 'transformer.layers.79.mlp.gate.per_channel_scale', 'transformer.layers.34.mlp.gate.per_channel_scale', 'transformer.layers.74.mlp.proj.per_channel_scale', 'transformer.layers.35.mlp.fc.per_channel_scale', 'transformer.layers.67.attention.qkv.per_channel_scale', 'transformer.layers.55.attention.dense.per_channel_scale', 'transformer.layers.38.mlp.proj.per_channel_scale', 'transformer.layers.40.mlp.proj.per_channel_scale', 'transformer.layers.24.mlp.gate.per_channel_scale', 'transformer.layers.66.mlp.fc.per_channel_scale', 'transformer.layers.41.attention.dense.per_channel_scale', 'transformer.layers.67.mlp.gate.per_channel_scale', 'transformer.layers.21.mlp.fc.per_channel_scale', 'transformer.layers.8.attention.dense.per_channel_scale', 'transformer.layers.7.mlp.gate.per_channel_scale', 'transformer.layers.36.attention.dense.per_channel_scale', 'transformer.layers.1.mlp.fc.per_channel_scale', 'transformer.layers.6.mlp.proj.per_channel_scale', 'transformer.layers.10.attention.qkv.per_channel_scale', 'transformer.layers.65.attention.dense.per_channel_scale', 'transformer.layers.11.attention.qkv.per_channel_scale', 'transformer.layers.35.attention.dense.per_channel_scale', 'transformer.layers.17.mlp.proj.per_channel_scale', 'transformer.layers.59.mlp.fc.per_channel_scale', 'transformer.layers.17.attention.dense.per_channel_scale', 'transformer.layers.27.mlp.gate.per_channel_scale', 'transformer.layers.66.mlp.proj.per_channel_scale', 'transformer.layers.71.mlp.gate.per_channel_scale', 'transformer.layers.72.attention.dense.per_channel_scale', 'transformer.layers.32.attention.dense.per_channel_scale', 'transformer.layers.69.attention.dense.per_channel_scale', 'transformer.layers.22.mlp.fc.per_channel_scale', 'transformer.layers.23.attention.qkv.per_channel_scale', 'transformer.layers.69.mlp.fc.per_channel_scale', 'transformer.layers.9.attention.qkv.per_channel_scale', 'transformer.layers.57.mlp.fc.per_channel_scale', 'transformer.layers.15.mlp.gate.per_channel_scale', 'transformer.layers.62.mlp.proj.per_channel_scale', 'transformer.layers.56.mlp.gate.per_channel_scale', 'transformer.layers.72.mlp.gate.per_channel_scale', 'transformer.layers.39.attention.qkv.per_channel_scale', 'transformer.layers.6.mlp.fc.per_channel_scale', 'transformer.layers.10.mlp.proj.per_channel_scale', 'transformer.layers.23.mlp.proj.per_channel_scale', 'transformer.layers.25.mlp.fc.per_channel_scale', 'transformer.layers.51.attention.qkv.per_channel_scale', 'transformer.layers.50.mlp.gate.per_channel_scale', 'transformer.layers.45.mlp.fc.per_channel_scale', 'transformer.layers.57.mlp.proj.per_channel_scale', 'transformer.layers.31.attention.qkv.per_channel_scale', 'transformer.layers.51.mlp.gate.per_channel_scale', 'transformer.layers.74.attention.qkv.per_channel_scale', 'transformer.layers.19.mlp.gate.per_channel_scale', 'transformer.layers.48.attention.qkv.per_channel_scale', 'transformer.layers.0.attention.dense.per_channel_scale', 'transformer.layers.50.attention.dense.per_channel_scale', 'transformer.layers.60.mlp.proj.per_channel_scale', 'transformer.layers.25.mlp.gate.per_channel_scale', 'transformer.layers.1.mlp.proj.per_channel_scale', 'transformer.layers.30.attention.qkv.per_channel_scale', 'transformer.layers.64.attention.qkv.per_channel_scale', 'transformer.layers.64.mlp.proj.per_channel_scale', 'transformer.layers.61.mlp.gate.per_channel_scale', 'transformer.layers.11.mlp.fc.per_channel_scale', 'transformer.layers.47.attention.dense.per_channel_scale', 'transformer.layers.33.mlp.gate.per_channel_scale', 'transformer.layers.73.mlp.proj.per_channel_scale', 'transformer.layers.75.attention.dense.per_channel_scale', 'transformer.layers.42.mlp.gate.per_channel_scale', 'transformer.layers.65.attention.qkv.per_channel_scale', 'transformer.layers.31.attention.dense.per_channel_scale', 'transformer.layers.34.mlp.proj.per_channel_scale', 'transformer.layers.5.mlp.fc.per_channel_scale', 'transformer.layers.44.mlp.gate.per_channel_scale', 'transformer.layers.70.attention.dense.per_channel_scale', 'transformer.layers.46.mlp.proj.per_channel_scale', 'transformer.layers.23.mlp.fc.per_channel_scale', 'transformer.layers.66.attention.dense.per_channel_scale', 'transformer.layers.48.mlp.proj.per_channel_scale', 'transformer.layers.47.attention.qkv.per_channel_scale', 'transformer.layers.0.attention.qkv.per_channel_scale', 'transformer.layers.37.attention.dense.per_channel_scale', 'transformer.layers.55.mlp.proj.per_channel_scale', 'transformer.layers.43.attention.qkv.per_channel_scale', 'transformer.layers.49.mlp.proj.per_channel_scale', 'transformer.layers.14.mlp.gate.per_channel_scale', 'transformer.layers.17.mlp.fc.per_channel_scale', 'transformer.layers.42.mlp.fc.per_channel_scale', 'transformer.layers.47.mlp.proj.per_channel_scale', 'transformer.layers.75.mlp.gate.per_channel_scale', 'transformer.layers.35.mlp.proj.per_channel_scale', 'transformer.layers.54.mlp.proj.per_channel_scale', 'transformer.layers.45.attention.qkv.per_channel_scale', 'transformer.layers.77.attention.dense.per_channel_scale', 'transformer.layers.5.attention.dense.per_channel_scale', 'transformer.layers.22.mlp.gate.per_channel_scale', 'transformer.layers.50.mlp.proj.per_channel_scale', 'transformer.layers.22.attention.dense.per_channel_scale', 'transformer.layers.42.mlp.proj.per_channel_scale', 'transformer.layers.21.mlp.gate.per_channel_scale', 'transformer.layers.6.mlp.gate.per_channel_scale', 'transformer.layers.71.attention.dense.per_channel_scale', 'transformer.layers.68.attention.qkv.per_channel_scale', 'transformer.layers.21.mlp.proj.per_channel_scale', 'transformer.layers.34.attention.dense.per_channel_scale', 'transformer.layers.21.attention.dense.per_channel_scale', 'transformer.layers.41.mlp.proj.per_channel_scale', 'transformer.layers.28.attention.dense.per_channel_scale', 'transformer.layers.57.attention.qkv.per_channel_scale', 'transformer.layers.3.mlp.proj.per_channel_scale', 'transformer.layers.30.mlp.fc.per_channel_scale', 'transformer.layers.0.mlp.fc.per_channel_scale', 'transformer.layers.38.attention.qkv.per_channel_scale', 'transformer.layers.73.attention.dense.per_channel_scale', 'transformer.layers.58.attention.qkv.per_channel_scale', 'transformer.layers.58.mlp.proj.per_channel_scale', 'transformer.layers.59.attention.qkv.per_channel_scale', 'transformer.layers.67.attention.dense.per_channel_scale', 'transformer.layers.9.attention.dense.per_channel_scale', 'transformer.layers.11.mlp.gate.per_channel_scale', 'transformer.layers.71.mlp.fc.per_channel_scale', 'transformer.layers.56.attention.dense.per_channel_scale', 'transformer.layers.14.attention.dense.per_channel_scale', 'transformer.layers.76.attention.qkv.per_channel_scale', 'transformer.layers.75.attention.qkv.per_channel_scale', 'transformer.layers.49.attention.dense.per_channel_scale', 'transformer.layers.65.mlp.gate.per_channel_scale', 'transformer.layers.27.mlp.fc.per_channel_scale', 'transformer.layers.37.attention.qkv.per_channel_scale', 'transformer.layers.75.mlp.proj.per_channel_scale', 'transformer.layers.23.attention.dense.per_channel_scale', 'transformer.layers.29.attention.dense.per_channel_scale', 'transformer.layers.42.attention.dense.per_channel_scale', 'transformer.layers.51.attention.dense.per_channel_scale', 'transformer.layers.49.mlp.gate.per_channel_scale', 'transformer.layers.36.attention.qkv.per_channel_scale', 'transformer.layers.56.mlp.proj.per_channel_scale', 'transformer.layers.18.mlp.gate.per_channel_scale', 'transformer.layers.53.mlp.gate.per_channel_scale', 'transformer.layers.68.attention.dense.per_channel_scale', 'transformer.layers.79.attention.dense.per_channel_scale', 'transformer.layers.0.mlp.proj.per_channel_scale', 'transformer.layers.24.attention.qkv.per_channel_scale', 'transformer.layers.5.attention.qkv.per_channel_scale', 'transformer.layers.15.mlp.fc.per_channel_scale', 'transformer.layers.77.mlp.proj.per_channel_scale', 'transformer.layers.13.mlp.proj.per_channel_scale', 'transformer.layers.53.attention.dense.per_channel_scale', 'transformer.layers.38.mlp.fc.per_channel_scale', 'transformer.layers.60.attention.qkv.per_channel_scale', 'transformer.layers.43.attention.dense.per_channel_scale', 'transformer.layers.25.mlp.proj.per_channel_scale', 'transformer.layers.44.attention.dense.per_channel_scale', 'transformer.layers.59.mlp.gate.per_channel_scale', 'transformer.layers.48.mlp.gate.per_channel_scale', 'transformer.layers.67.mlp.fc.per_channel_scale', 'transformer.layers.30.mlp.proj.per_channel_scale', 'transformer.layers.56.mlp.fc.per_channel_scale', 'transformer.layers.49.attention.qkv.per_channel_scale', 'transformer.layers.70.mlp.proj.per_channel_scale', 'transformer.layers.9.mlp.fc.per_channel_scale', 'transformer.layers.45.attention.dense.per_channel_scale', 'transformer.layers.22.mlp.proj.per_channel_scale', 'transformer.layers.10.mlp.fc.per_channel_scale', 'transformer.layers.41.mlp.fc.per_channel_scale', 'transformer.layers.51.mlp.proj.per_channel_scale', 'transformer.layers.28.mlp.proj.per_channel_scale', 'transformer.layers.79.mlp.fc.per_channel_scale', 'transformer.layers.76.mlp.fc.per_channel_scale', 'transformer.layers.62.mlp.fc.per_channel_scale', 'transformer.layers.72.mlp.proj.per_channel_scale', 'transformer.layers.56.attention.qkv.per_channel_scale', 'transformer.layers.33.attention.qkv.per_channel_scale', 'transformer.layers.7.mlp.fc.per_channel_scale', 'transformer.layers.0.mlp.gate.per_channel_scale', 'transformer.layers.74.mlp.gate.per_channel_scale', 'transformer.layers.14.mlp.fc.per_channel_scale', 'transformer.layers.38.attention.dense.per_channel_scale', 'transformer.layers.54.attention.qkv.per_channel_scale', 'transformer.layers.31.mlp.gate.per_channel_scale', 'transformer.layers.63.mlp.fc.per_channel_scale', 'transformer.layers.57.attention.dense.per_channel_scale', 'transformer.layers.9.mlp.gate.per_channel_scale', 'transformer.layers.46.attention.dense.per_channel_scale', 'transformer.layers.1.attention.qkv.per_channel_scale', 'transformer.layers.40.attention.dense.per_channel_scale', 'transformer.layers.78.mlp.proj.per_channel_scale', 'transformer.layers.26.mlp.gate.per_channel_scale', 'transformer.layers.52.attention.qkv.per_channel_scale', 'transformer.layers.3.mlp.gate.per_channel_scale', 'transformer.layers.4.mlp.gate.per_channel_scale', 'transformer.layers.25.attention.qkv.per_channel_scale', 'transformer.layers.19.mlp.fc.per_channel_scale', 'transformer.layers.2.attention.qkv.per_channel_scale', 'transformer.layers.70.attention.qkv.per_channel_scale', 'transformer.layers.20.mlp.fc.per_channel_scale', 'transformer.layers.58.attention.dense.per_channel_scale', 'transformer.layers.1.attention.dense.per_channel_scale', 'transformer.layers.1.mlp.gate.per_channel_scale', 'transformer.layers.55.mlp.gate.per_channel_scale', 'transformer.layers.70.mlp.gate.per_channel_scale', 'transformer.layers.43.mlp.gate.per_channel_scale', 'transformer.layers.42.attention.qkv.per_channel_scale', 'transformer.layers.19.attention.qkv.per_channel_scale', 'transformer.layers.34.attention.qkv.per_channel_scale', 'transformer.layers.61.mlp.proj.per_channel_scale', 'transformer.layers.15.mlp.proj.per_channel_scale', 'transformer.layers.35.attention.qkv.per_channel_scale', 'transformer.layers.12.mlp.gate.per_channel_scale', 'transformer.layers.23.mlp.gate.per_channel_scale', 'transformer.layers.19.mlp.proj.per_channel_scale', 'transformer.layers.21.attention.qkv.per_channel_scale', 'transformer.layers.37.mlp.proj.per_channel_scale', 'transformer.layers.45.mlp.gate.per_channel_scale', 'transformer.layers.52.mlp.fc.per_channel_scale', 'transformer.layers.19.attention.dense.per_channel_scale', 'transformer.layers.62.attention.qkv.per_channel_scale', 'transformer.layers.68.mlp.gate.per_channel_scale', 'transformer.layers.52.mlp.gate.per_channel_scale', 'transformer.layers.34.mlp.fc.per_channel_scale', 'transformer.layers.32.mlp.gate.per_channel_scale', 'transformer.layers.16.mlp.fc.per_channel_scale', 'transformer.layers.28.mlp.fc.per_channel_scale', 'transformer.layers.50.attention.qkv.per_channel_scale', 'transformer.layers.62.attention.dense.per_channel_scale', 'transformer.layers.61.attention.dense.per_channel_scale', 'transformer.layers.60.attention.dense.per_channel_scale', 'transformer.layers.74.mlp.fc.per_channel_scale', 'transformer.layers.43.mlp.proj.per_channel_scale', 'transformer.layers.29.mlp.gate.per_channel_scale', 'transformer.layers.40.attention.qkv.per_channel_scale', 'transformer.layers.31.mlp.fc.per_channel_scale', 'transformer.layers.44.mlp.fc.per_channel_scale', 'transformer.layers.28.attention.qkv.per_channel_scale', 'transformer.layers.16.mlp.proj.per_channel_scale', 'transformer.layers.7.attention.qkv.per_channel_scale', 'transformer.layers.46.mlp.gate.per_channel_scale', 'transformer.layers.35.mlp.gate.per_channel_scale', 'transformer.layers.15.attention.qkv.per_channel_scale', 'transformer.layers.46.attention.qkv.per_channel_scale', 'transformer.layers.24.mlp.fc.per_channel_scale', 'transformer.layers.63.attention.qkv.per_channel_scale', 'transformer.layers.5.mlp.proj.per_channel_scale', 'transformer.layers.44.mlp.proj.per_channel_scale', 'transformer.layers.36.mlp.fc.per_channel_scale', 'transformer.layers.36.mlp.proj.per_channel_scale', 'transformer.layers.61.mlp.fc.per_channel_scale', 'transformer.layers.48.mlp.fc.per_channel_scale', 'transformer.layers.30.attention.dense.per_channel_scale', 'transformer.layers.77.attention.qkv.per_channel_scale', 'transformer.layers.8.mlp.proj.per_channel_scale', 'transformer.layers.8.mlp.fc.per_channel_scale', 'transformer.layers.2.attention.dense.per_channel_scale', 'transformer.layers.64.mlp.fc.per_channel_scale', 'transformer.layers.37.mlp.gate.per_channel_scale', 'transformer.layers.47.mlp.fc.per_channel_scale', 'transformer.layers.3.attention.dense.per_channel_scale', 'transformer.layers.65.mlp.fc.per_channel_scale', 'transformer.layers.12.attention.dense.per_channel_scale', 'transformer.layers.52.mlp.proj.per_channel_scale', 'transformer.layers.66.attention.qkv.per_channel_scale', 'transformer.layers.55.attention.qkv.per_channel_scale', 'transformer.layers.63.mlp.gate.per_channel_scale', 'transformer.layers.13.mlp.fc.per_channel_scale', 'transformer.layers.37.mlp.fc.per_channel_scale', 'transformer.layers.44.attention.qkv.per_channel_scale', 'transformer.layers.54.mlp.fc.per_channel_scale', 'transformer.layers.65.mlp.proj.per_channel_scale', 'transformer.layers.2.mlp.fc.per_channel_scale', 'transformer.layers.29.mlp.fc.per_channel_scale', 'transformer.layers.64.mlp.gate.per_channel_scale', 'transformer.layers.6.attention.dense.per_channel_scale', 'transformer.layers.26.attention.dense.per_channel_scale', 'transformer.layers.2.mlp.gate.per_channel_scale', 'transformer.layers.48.attention.dense.per_channel_scale', 'transformer.layers.40.mlp.gate.per_channel_scale', 'transformer.layers.26.mlp.proj.per_channel_scale', 'transformer.layers.27.mlp.proj.per_channel_scale', 'transformer.layers.59.mlp.proj.per_channel_scale', 'transformer.layers.16.attention.qkv.per_channel_scale', 'transformer.layers.33.mlp.fc.per_channel_scale', 'transformer.layers.9.mlp.proj.per_channel_scale', 'transformer.layers.12.mlp.fc.per_channel_scale', 'transformer.layers.7.attention.dense.per_channel_scale', 'transformer.layers.49.mlp.fc.per_channel_scale', 'transformer.layers.53.mlp.proj.per_channel_scale', 'transformer.layers.63.mlp.proj.per_channel_scale', 'transformer.layers.50.mlp.fc.per_channel_scale', 'transformer.layers.13.mlp.gate.per_channel_scale', 'transformer.layers.10.attention.dense.per_channel_scale', 'transformer.layers.53.attention.qkv.per_channel_scale', 'transformer.layers.17.attention.qkv.per_channel_scale', 'transformer.layers.77.mlp.gate.per_channel_scale', 'transformer.layers.24.mlp.proj.per_channel_scale', 'transformer.layers.74.attention.dense.per_channel_scale', 'transformer.layers.16.attention.dense.per_channel_scale', 'transformer.layers.47.mlp.gate.per_channel_scale', 'transformer.layers.3.attention.qkv.per_channel_scale', 'transformer.layers.73.mlp.fc.per_channel_scale', 'transformer.layers.33.attention.dense.per_channel_scale', 'transformer.layers.62.mlp.gate.per_channel_scale', 'transformer.layers.22.attention.qkv.per_channel_scale', 'transformer.layers.8.attention.qkv.per_channel_scale', 'transformer.layers.54.mlp.gate.per_channel_scale', 'transformer.layers.18.attention.dense.per_channel_scale', 'transformer.layers.39.attention.dense.per_channel_scale', 'transformer.layers.4.attention.qkv.per_channel_scale', 'transformer.layers.63.attention.dense.per_channel_scale', 'transformer.layers.73.attention.qkv.per_channel_scale', 'transformer.layers.32.mlp.fc.per_channel_scale', 'transformer.layers.60.mlp.fc.per_channel_scale', 'transformer.layers.43.mlp.fc.per_channel_scale', 'transformer.layers.17.mlp.gate.per_channel_scale', 'transformer.layers.39.mlp.proj.per_channel_scale', 'transformer.layers.20.attention.dense.per_channel_scale', 'transformer.layers.52.attention.dense.per_channel_scale', 'transformer.layers.32.attention.qkv.per_channel_scale', 'transformer.layers.5.mlp.gate.per_channel_scale', 'transformer.layers.8.mlp.gate.per_channel_scale', 'transformer.layers.20.attention.qkv.per_channel_scale', 'transformer.layers.41.attention.qkv.per_channel_scale', 'transformer.layers.76.mlp.gate.per_channel_scale', 'transformer.layers.25.attention.dense.per_channel_scale', 'transformer.layers.71.attention.qkv.per_channel_scale', 'transformer.layers.75.mlp.fc.per_channel_scale', 'transformer.layers.27.attention.dense.per_channel_scale', 'transformer.layers.20.mlp.proj.per_channel_scale', 'transformer.layers.69.mlp.gate.per_channel_scale', 'transformer.layers.33.mlp.proj.per_channel_scale', 'transformer.layers.13.attention.qkv.per_channel_scale', 'transformer.layers.40.mlp.fc.per_channel_scale', 'transformer.layers.11.attention.dense.per_channel_scale', 'transformer.layers.4.mlp.proj.per_channel_scale', 'transformer.layers.7.mlp.proj.per_channel_scale', 'transformer.layers.54.attention.dense.per_channel_scale', 'transformer.layers.27.attention.qkv.per_channel_scale', 'transformer.layers.30.mlp.gate.per_channel_scale', 'transformer.layers.36.mlp.gate.per_channel_scale', 'transformer.layers.70.mlp.fc.per_channel_scale', 'transformer.layers.31.mlp.proj.per_channel_scale', 'transformer.layers.71.mlp.proj.per_channel_scale', 'transformer.layers.13.attention.dense.per_channel_scale', 'transformer.layers.26.attention.qkv.per_channel_scale', 'transformer.layers.72.attention.qkv.per_channel_scale', 'transformer.layers.64.attention.dense.per_channel_scale', 'transformer.layers.11.mlp.proj.per_channel_scale', 'transformer.layers.18.mlp.fc.per_channel_scale', 'transformer.layers.29.mlp.proj.per_channel_scale', 'transformer.layers.55.mlp.fc.per_channel_scale', 'transformer.layers.41.mlp.gate.per_channel_scale', 'transformer.layers.46.mlp.fc.per_channel_scale', 'transformer.layers.2.mlp.proj.per_channel_scale', 'transformer.layers.78.attention.qkv.per_channel_scale', 'transformer.layers.39.mlp.gate.per_channel_scale', 'transformer.layers.6.attention.qkv.per_channel_scale', 'transformer.layers.58.mlp.gate.per_channel_scale', 'transformer.layers.67.mlp.proj.per_channel_scale', 'transformer.layers.77.mlp.fc.per_channel_scale', 'transformer.layers.20.mlp.gate.per_channel_scale', 'transformer.layers.14.mlp.proj.per_channel_scale', 'transformer.layers.18.mlp.proj.per_channel_scale', 'transformer.layers.53.mlp.fc.per_channel_scale', 'transformer.layers.78.mlp.fc.per_channel_scale'}
Exception ignored in: <function PretrainedModel.__del__ at 0x7f6760daf250>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/modeling_utils.py", line 377, in __del__
    self.release()
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/modeling_utils.py", line 374, in release
    release_gc()
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/_utils.py", line 443, in release_gc
    torch.cuda.ipc_collect()
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 813, in ipc_collect
    _lazy_init()
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 321, in _lazy_init
    raise DeferredCudaCallError(msg) from e
torch.cuda.DeferredCudaCallError: CUDA call failed lazily at initialization with error: 'NoneType' object is not iterable

CUDA call was originally invoked at:

  File "/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 9, in <module>
    import tensorrt_llm
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/__init__.py", line 32, in <module>
    import tensorrt_llm.functional as functional
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/functional.py", line 28, in <module>
    from . import graph_rewriting as gw
  File "<frozen importlib._bootstrap>", line 1078, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/graph_rewriting.py", line 12, in <module>
    from .network import Network
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/network.py", line 26, in <module>
    from tensorrt_llm.module import Module
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/module.py", line 17, in <module>
    from ._common import default_net
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/_common.py", line 26, in <module>
    import torch
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/torch/__init__.py", line 1427, in <module>
    _C._initExtension(manager_path())
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 1303, in <module>
    _lazy_call(_register_triton_kernels)
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 244, in _lazy_call
    _queued_calls.append((callable, traceback.format_stack()))

### additional notes

can anyone help identifying why it fails or what the error is?
Thanks

**Comment by byshiue** [comment]
duplicated issue to https://github.com/NVIDIA/TensorRT-LLM/issues/1628, close this one.
