### ISSUE TITLE
Convert llama2-70B-chat hf to FT with "--calibrate-kv-cache"  encount error

### ISSUE THREAD

**Issue by CN-COTER** [NVIDIA/TensorRT-LLM#168]
First of all,  thx for the amazing work!

When I convert my fintuned llama2-70B-chat hf model  to FT model with the following script:
`
         python3 hf_llama_convert.py -p 1 -i my_llama2_chat_70B_ckpt  -o output_ft_path --tensor-parallelism 4 --cal
ibrate-kv-cache --storage-type fp16
`

I just encounter the error ：

`
saving weights:   0%|                                                       | 0/560 [00:00<?, ?it/s]
`
`
Traceback (most recent call last):
  File "***/code/tensorrtllm_backend/tensorrt_llm/examples/llama/hf_llama_convert.py", line 335, in <module>
    hf_gpt_converter(args)
`
`
  File "***/code/tensorrtllm_backend/tensorrt_llm/examples/llama/hf_llama_convert.py", line 273, in hf_gpt_converter
    split_and_save_weight(*starmap_arg)
`
`
 File "***/code/tensorrtllm_backend/tensorrt_llm/examples/llama/convert.py", line 290, in split_and_save_weight
`

when excute
`
val = val.reshape(hidden_dim, 3, local_dim)
`
val.shape is not euqal to hidden_dim \* 3 \* local_dim

Does llama2-70B with GQA-feature supports int8 kv-cache upon current TRT-LLM？
I will be appreciate if anyone can give me a hand!

**Comment by anjalibshah** [comment]
For LLamav2-70B, can you run again and also add this flag ` --multi_query_mode ` ?

**Comment by jdemouth-nvidia** [comment]
Hi @CN-COTER , you may want to give the [`main`](https://github.com/NVIDIA/TensorRT-LLM/tree/main) branch a try. We have fixed a bug involving quantization and GQA (which is enabled for Llama v2 70B). Thanks.

**Comment by CN-COTER** [comment]
> Hi @CN-COTER , you may want to give the [`main`](https://github.com/NVIDIA/TensorRT-LLM/tree/main) branch a try. We have fixed a bug involving quantization and GQA (which is enabled for Llama v2 70B). Thanks.

**Comment by CN-COTER** [comment]
> Hi @CN-COTER , you may want to give the [`main`](https://github.com/NVIDIA/TensorRT-LLM/tree/main) branch a try. We have fixed a bug involving quantization and GQA (which is enabled for Llama v2 70B). Thanks.

Thx for ur reply, the problem is solved when i pull the latest main branch.
