### ISSUE TITLE
Question : llama/convert_checkpoint.py on locally saved model from HF

### ISSUE THREAD

**Issue by snassimr** [NVIDIA/TensorRT-LLM#1698]
Is it possible to use model_dir as local folder and not HF model repo ?
I have a model downloaded before and want to make convert_checkpoint.py work with this model in local folder.
https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/llama/convert_checkpoint.py

**Comment by nv-guomingz** [comment]
> Is it possible to use model_dir as local folder and not HF model repo ? I have a model downloaded before and want to make convert_checkpoint.py work with this model in local folder. https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/llama/convert_checkpoint.py

what's the model type of pre-downloaded model in this context? Is it a hf model or not?

**Comment by snassimr** [comment]
Hi @nv-guomingz 
Yep . I am talking about pre-downloaded hf model. Actually , I see that providing a model dir (local) and not HF repo works out of box. But I am not sure . Could you approve that local model dir (that contains pre-downloaded model) should work ?
Thanks in advance

**Comment by nv-guomingz** [comment]
> . Could you approve that local model dir (that contains pre-downloaded model) should work ?

Yes, if this local dir is a pre-downloaded hf model.
