### ISSUE TITLE
Where is download for Tensorrt 9.1.0.4 for Windows?

### ISSUE THREAD

**Issue by oscarbg** [NVIDIA/TensorRT-LLM#17]
Hi,
in "https://github.com/NVIDIA/TensorRT-LLM/tree/release/0.5.0/windows"
you mention download "Download and unzip [TensorRT 9.1.0.4](https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing-zip)" but it's not available..

also in https://github.com/NVIDIA/TensorRT/pull/3395/commits/b8adcfa894b241261f46f21d0dcc70b54a576263 we see how to download for Linux at least:
[TensorRT 9.1.0.4 for CUDA 12.2, Linux x86_64](https://developer.nvidia.com/downloads/compute/machine-learning/tensorrt/secure/9.1.0/tars/tensorrt-9.1.0.4.linux.x86_64-gnu.cuda-12.2.tar.gz)
but not yet for Windows..

opening here so get notified when available..

thanks..

**Comment by jdemouth** [comment]
If you don’t mind, I’m closing that issue and we will discuss that issue in https://github.com/NVIDIA/TensorRT-LLM/issues/18.
