### ISSUE TITLE
24.05-trtllm-python-py3 image size

### ISSUE THREAD

**Issue by Prots** [NVIDIA/TensorRT-LLM#1704]
Hello, I'm using 24.03-trtllm-python-py3 with image size 8.38 GB which is not small but ok.
I'm going to migrate to the newest versions like 24.04 or 24.05 but it size drastically increased to 18.46 GB or even 18.48 GB.
So my question what was the reason of +10 GB and how to create a smaller image with triton+tensorttllm? Thanks

**Comment by byshiue** [comment]
It is because many users ask to install the TensorRT-LLM python packages in the docker image (before 24.03, the docker image only contains the backend, it does not contain the TRT-LLM python packages) and some related dependencies about the installation.

**Comment by WingEdge777** [comment]
> It is because many users ask to install the TensorRT-LLM python packages in the docker image (before 24.03, the docker image only contains the backend, it does not contain the TRT-LLM python packages) and some related dependencies about the installation.

Hi, do you consider releasing a smaller image for serving-only purpose like 24.03? Normally, trtllm python sdk is only used in dev environment, and it can be easily installed by `pip install`. We don't see the necessity to put it in the docker image, as the package and its requirements occupy too much space/bandwidth.

**Comment by Prots** [comment]
When I pull images locally the size was showing twice bigger than expected 
<img width="967" alt="Screenshot 2024-06-04 at 14 33 28" src="https://github.com/NVIDIA/TensorRT-LLM/assets/2080252/5792d493-50ab-4350-b684-b716bd946969">

**Comment by Prots** [comment]
Ah, this is because of mulitplatform image.

**Comment by byshiue** [comment]
We will discuss that. Because using pip to install tensorrt-llm often leads to version mismatch before TRT-LLM supports backward compability, we determine to install the tensorrt-llm python package in the tritonserver docker image since the 24.04 docker image and lead to larger docker image size.

**Comment by Prots** [comment]
@byshiue is it possible to install triton + tensorrt_llm backend using multistage build? Like take py3-min image and copy all needed libs from trtllm-python-py3 image.

**Comment by Prots** [comment]
Another question about multi-platform image, I use 24.04-trtllm-python-py3 image as a base, added quantized llama3 model with 8.5 GB size and received about 42 GB result image. 
```
FROM nvcr.io/nvidia/tritonserver:24.04-trtllm-python-py3

COPY TensorRT-LLM/Meta-Llama-3-8B-Instruct-tokenizer /TensorRT-LLM/Meta-Llama-3-8B-Instruct-tokenizer
COPY tensorrtllm_backend/all_models/inflight_batcher_llm /tensorrtllm_backend/all_models/inflight_batcher_llm

CMD tritonserver --model-repository /tensorrtllm_backend/all_models/inflight_batcher_llm
```

Build command is 
`docker build -f Dockerfile --platform linux/amd64 --no-cache -t triton_llama3_int8_sq:0.0.2 .`
So I set `--platform linux/amd64` but docker takes whole image for both platforms linux/amd64 and linux/arm64. Why does it happen?

**Comment by gabriel-peracio** [comment]
Commenting mostly to prevent this issue from becoming `stale`.

@Prots Have you figured out a way to mutistage build `triton + tensorrt_llm`?

**Comment by Prots** [comment]
@gabriel-peracio yes, I did some investigation, not sure that I covered all cases but in my case it works and decreased image size. The idea is to take minimal triton image and copy/past only needed libs from triton+tensorrt_llm image:
````
FROM nvcr.io/nvidia/tritonserver:24.07-trtllm-python-py3 as base

FROM nvcr.io/nvidia/tritonserver:24.07-py3-min as final

COPY --from=base /lib/libboost_filesystem.so* /lib/

COPY --from=base /opt/tritonserver/bin /opt/tritonserver/bin
COPY --from=base /opt/tritonserver/lib /opt/tritonserver/lib
COPY --from=base /opt/tritonserver/backends/python /opt/tritonserver/backends/python
COPY --from=base /opt/tritonserver/backends/tensorrtllm /opt/tritonserver/backends/tensorrtllm

COPY --from=base /usr/lib/x86_64-linux-gnu/libb64* /usr/lib/x86_64-linux-gnu/
COPY --from=base /usr/lib/x86_64-linux-gnu/libdcgm* /usr/lib/x86_64-linux-gnu/
COPY --from=base /usr/lib/x86_64-linux-gnu/libxml2* /usr/lib/x86_64-linux-gnu/
COPY --from=base /usr/lib/x86_64-linux-gnu/libicu* /usr/lib/x86_64-linux-gnu/
COPY --from=base /usr/lib/x86_64-linux-gnu/libarchive* /usr/lib/x86_64-linux-gnu/

COPY --from=base /usr/local/lib/python3.10/dist-packages/tensorrt_llm/libs /usr/local/lib/python3.10/dist-packages/tensorrt_llm/libs
COPY --from=base /etc/ld.so.conf.d/tensorrt-llm.conf /etc/ld.so.conf.d/tensorrt-llm.conf
COPY --from=base /etc/ld.so.conf.d/triton-tensorrtllm-worker.conf /etc/ld.so.conf.d/triton-tensorrtllm-worker.conf

COPY --from=base /usr/local/TensorRT-9.3.0.1/targets/x86_64-linux-gnu/lib/libnvinfer.so.9.3.0 /usr/local/TensorRT-9.3.0.1/targets/x86_64-linux-gnu/lib/libnvinfer.so.9.3.0
COPY --from=base /usr/local/TensorRT-9.3.0.1/targets/x86_64-linux-gnu/lib/libnvinfer.so.9 /usr/local/TensorRT-9.3.0.1/targets/x86_64-linux-gnu/lib/libnvinfer.so.9
COPY --from=base /usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.7 /usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.7
COPY --from=base /usr/lib/x86_64-linux-gnu/libcudnn.so.8 /usr/lib/x86_64-linux-gnu/libcudnn.so.8
COPY --from=base /usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.7 /usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.7
COPY --from=base /usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8 /usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/TensorRT-9.3.0.1/targets/x86_64-linux-gnu/lib/
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/python3.10/dist-packages/tensorrt_llm/libs 

RUN ldconfig && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y python3-pip && \
    pip3 install -U pip --no-cache-dir && \
    pip3 install numpy transformers --no-cache-dir 

ENV PATH=/opt/tritonserver/bin:${PATH}

COPY TensorRT-LLM/Meta-Llama-3-8B-Instruct-GPTQ /TensorRT-LLM/Meta-Llama-3-8B-Instruct-tokenizer
COPY tensorrtllm_backend/all_models/inflight_batcher_llm /tensorrtllm_backend/all_models/inflight_batcher_llm

CMD ldconfig && tritonserver --model-repository /tensorrtllm_backend/all_models/inflight_batcher_llm```

**Comment by nv-guomingz** [comment]
@Prots  Please reopen it if needed
