### ISSUE TITLE
After deployment, each request exception generates a core.xxxx file 

### ISSUE THREAD

**Issue by taorui-plus** [NVIDIA/TensorRT-LLM#1715]
### System Info

GPU: NVIDIA-SMI 535.161.08             Driver Version: 535.161.08   CUDA Version: 12.3  

### Who can help?

@Pzzzzz5142 @fjosw @ami

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [x] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Start the service in this directory：sherpa/triton/whisper 

### Expected behavior

report bug without core.xxxx files

### actual behavior

generate too many core.xxxx files, each file is 2.4G. 
If the number of abnormal requests increases, the disk may explode easily.

### additional notes

Is there any setting that can prevent the generation of core.XXXX files?

**Comment by nv-guomingz** [comment]
Hi @Shixiaowei02  could u please add some comments here?

**Comment by nv-guomingz** [comment]
Hi @taorui-plus do u still have further issue or question now? If not, we'll close it soon.
