### ISSUE TITLE
When the request is large, the Triton server has a very high TTFT

### ISSUE THREAD

**Issue by Godlovecui** [NVIDIA/TensorRT-LLM#1719]
### System Info

RTX 8*4090

### Who can help?

@kai

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

1. run docker

docker run -d --gpus all --privileged --ipc=host --net=host --ulimit stack=67108864 --ulimit memlock=-1 -e HTTPS_PROXY= -e HTTP_PROXY= -e ALL_PROXY= -e https_proxy= -e http_proxy= -e all_proxy= -e CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 --name benchmark_trtllm -v /models/Meta-Llama-3-8B-Instruct:/models/Meta-Llama-3-8B-Instruct:ro -v /path/to/workspaces/tensorrtllm_backend/engine_outputs_llama3_8B_0524:/path/to/workspaces/tensorrtllm_backend/engine_outputs_llama3_8B_0524:ro -v /path/to/workspaces/tensorrtllm_backend/triton_model_repo:/path/to/workspaces/tensorrtllm_backend/triton_model_repo -w /workspace nvcr.io/nvidia/tritonserver:24.02 /path/to/workspaces/tensorrtllm_backend/triton_model_repo/launch_triton_server.py --world_size=8 --model_repo=/path/to/workspaces/tensorrtllm_backend/triton_model_repo

2. run benckmark. (the benchmark_serving.py file can be found in https://github.com/vllm-project/vllm/blob/main/benchmarks/benchmark_serving.py)

python /path/to/workspaces/mlops/test/benchmark_serving.py --backend trtllm --model /models/Meta-Llama-3-8B-Instruct --tokenizer /models/Meta-Llama-3-8B-Instruct --dataset /models/ShareGPT_Vicuna_unfiltered/ShareGPT_V3_unfiltered_cleaned_split.json --port 8000 --num-warmup-requests 32 --num-benchmark-requests 1024 --max-concurrent-requests 64 --stream --pad-requests --warn-dismatch-output-len --gpus 8 --sampling-policy fixed --fixed_prompt_len 1024 --fixed_output_len 1024 --endpoint v2/models/ensemble/generate_stream

### Expected behavior

The TTFT(time to first token) is acceptable to users in high requests

### actual behavior

The TTFT(time to first token) is too high in high requests

### additional notes

I run benchmark of Meta-Llama-3-8B-Instruct in RTX 8*4090,
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/68674291/21cdf91b-a32a-4382-b5b5-4a56fd65d034)
when request is 16, input sequence length is 1024, output sequence length is 1024, The TTFT(time to first token) is 0.403s, which is acceptable。
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/68674291/a5869170-1006-4630-b7ea-50a783ee435f)
However, when request is 1024,
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/68674291/6bbc1a36-dc78-4c95-bb44-1149262b602a)
The TTFT is 379.089s. Is this normal?
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/68674291/a6ac2c54-3a84-47a3-bc6f-a49feccfafbf)

**Comment by nv-guomingz** [comment]
Hi @schetlur-nv, would u please add some comments here?
