### ISSUE TITLE
Lora support with LLama3-70B and AWQ Quantization

### ISSUE THREAD

**Issue by smehta2000** [NVIDIA/TensorRT-LLM#1721]
### System Info

TensorRT LLM Main Branch Commit `f430a4`

### Who can help?

I'm using the latest main commit `f430a4`. After quantizing a llama3-70B model, I'm using lora weights with the --lora-plugin parameter set.

Looks like this is a expected failure case because of the assert statement. Are there plans to support the Lora Adapters with AWQ quantized Llama3-70B model?

@Tracin @ncomly-nvidia

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
python ../quantization/quantize.py \
--model_dir ./Meta-Llama-3-70b/ \
--dtype float16 \
--qformat int4_awq \
--awq_block_size 64 \
--output_dir ./Meta-Llama-3-70b/quantized_int4-awq \
--calib_size 512 \
--tp_size 1
```

```
trtllm-build \
--checkpoint_dir ./Meta-Llama-3-70b/quantized_int4-awq \
--output_dir ./Meta-Llama-3-70b/trt_engines/lora_1gpu_int4awq \
--gemm_plugin float16 \
--max_batch_size 4 \
--max_input_len 6144 \
--max_output_len 1024 \
--gpt_attention_plugin float16 \
--context_fmha enable \
--multi_block_mode enable \
--remove_input_padding enable \
--use_custom_all_reduce enable \
--paged_kv_cache enable \
--use_paged_context_fmha enable \
--lora_plugin float16 \
--lora_target_modules attn_q attn_k attn_v attn_dense mlp_h_to_4h mlp_gate mlp_4h_to_h \
--max_lora_rank 32 \
--lora_dir /TensorRT-LLM/examples/llama/llama-3-70b-llc-2
```

### Expected behavior

Build process would complete

### actual behavior

The trtllm-build process throws the following error
```
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/quantization/layers.py", line 641, in forward
  assert lora_runtime_params is None, "lora is not supported on WeightOnlyGroupwiseQuantRowLinear now"
AssertionError: lora is not supported on WeightOnlyGroupwiseQuantRowLinear now
```

### additional notes

NA

**Comment by hijkzzz** [comment]
@nv-guomingz This is a request for a new feature.
As vLLM currently supports LoRA + AWQ, maybe we should add it in the future release?

**Comment by nv-guomingz** [comment]
> @nv-guomingz This is a request for a new feature. As vLLM currently supports LoRA + AWQ, maybe we should add it in the future release?

+ @ncomly-nvidia @AdamzNV for vis.

**Comment by hijkzzz** [comment]
Fixed internally, will be released in the next dev version.

**Comment by teis-e** [comment]
> python ../quantization/quantize.py \
> --model_dir ./Meta-Llama-3-70b/ \
> --dtype float16 \
> --qformat int4_awq \
> --awq_block_size 64 \
> --output_dir ./Meta-Llama-3-70b/quantized_int4-awq \
> --calib_size 512 \
> --tp_size 1

Does this require to load the whole model on the gpu? Or is it quantized on the fly?

**Comment by smehta2000** [comment]
@teis-e  It loads the whole model. I needed 2 80GB GPUs to quantize

**Comment by teis-e** [comment]
Right. I wonder if it is possible to offload to disk/cpu

**Comment by nv-guomingz** [comment]
> Right. I wonder if it is possible to offload to disk/cpu

yes, you can add knob `--device cpu`

**Comment by nv-guomingz** [comment]
@smehta2000 Could we close this ticket now if there's no further issues?

**Comment by nv-guomingz** [comment]
Hi @teis-e please feel free to reopen this ticket if needed
