### ISSUE TITLE
Llama3-70B with AWQ performance issue

### ISSUE THREAD

**Issue by canamika27** [NVIDIA/TensorRT-LLM#1722]
### System Info

I am currently testing TensorRT LLM  Version 0.11.0.dev2024052800 and nvidia-modelopt version 0.11.2 on 8 x H100 GPUS

### Who can help?

I am trying to test the performance improvement of LLama3-70B-Instruct model with AWQ over baseline FP16 on 8 x H100 GPUs, but I observed till batch size 4 AWQ performed better than FP16 but after that performance degraded. Please find below sample result on generationTokensPerSec

![image](https://github.com/NVIDIA/TensorRT-LLM/assets/41502651/0a26d52b-1615-49dd-9de0-773ddb8b1196)

I am using C++ benchmark script provided in repo.

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Below code used for building engine in FP16

python convert_checkpoint.py --model_dir /code/tensorrt_llm/Meta-Llama-3-70B-Instruct/ \
                            --output_dir ./tllm_checkpoint_8gpu_tp8 \
                            --dtype float16 \
                            --tp_size 8

trtllm-build --checkpoint_dir ./tllm_checkpoint_8gpu_tp8 \
            --output_dir ./tmp/llama/70B/trt_engines/fp16/8-gpu/ \
            --gemm_plugin float16 \
            --paged_kv_cache disable \
	--context_fmha enable \
	--gpt_attention_plugin float16 \
	--max_batch_size 64 \
	--max_input_len 2048 \
	--max_output_len 2048 \
	--strongly_typed

Below code used for building engine in AWQ 

python quantize.py --model_dir /code/tensorrt_llm/Meta-Llama-3-70B-Instruct/ \
                                   --dtype float16 \
                                   --qformat int4_awq \
                                   --awq_block_size 128 \
                                   --output_dir ./quantized_int4-awq \
                                   --calib_size 32 --tp_size 8

trtllm-build --checkpoint_dir ./quantized_int4-awq --output_dir ./tmp/llama/70B/trt_engines/int4_AWQ/8-gpu/ --gemm_plugin float16 \
            --paged_kv_cache disable \
            --remove_input_padding enable \
	--context_fmha enable \
	--max_batch_size 64 \
	--max_input_len 2048 \
	--max_output_len 2048 \
	--strongly_typed

For Benchmarking I ran C++ benchmark with bash script shared in repo

### Expected behavior

AWQ should performance than FP16 for all batch size (tested from 1-64). I have tested the same setup on A100 and observed AWQ perform better in all batchsize

### actual behavior

Till batchzie 4 AWQ perform better than FP16 but after that performance degraded. I have shared the result on generationTokensPerSec

### additional notes

N/A

**Comment by hijkzzz** [comment]
This seems reasonable since it is mostly memory bound when bs is small and should be compute bound when the batch size is large. 
AWQ does not save computational overhead but even increases it. It merely reduces memory transfer. (Verified by Qi Zhang)
An ideal method of acceleration would be FP8 or SmoothQuant (W8A8).

**Comment by canamika27** [comment]
@hijkzzz  - But TRT-model-optimizer benchmark.md shows AWQ INT4 doing better on larger batch size  on H100 ?

![image](https://github.com/NVIDIA/TensorRT-LLM/assets/41502651/82468780-508b-40fc-96dc-4a7a6beef5ab)

link from where I got the image - https://github.com/NVIDIA/TensorRT-Model-Optimizer/blob/main/benchmark.md

**Comment by hijkzzz** [comment]
@Tracin  for viz. Thanks for your reminder.

**Comment by Tracin** [comment]
@canamika27 Hi, can you share the full raw data please? batch size / input len / output len / tokens per sec etc.

**Comment by canamika27** [comment]
@Tracin  -- Sure

For benchmarking I used same bash script given in repo https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/performance/perf-overview.md

in_out_sizes=("1:128,128" "4:128,128" "8:128,128" "16:128,128" "32:128,128" "64:128,128")
for in_out in ${in_out_sizes[@]}
do
	batch_size=$(echo $in_out | awk -F':' '{ print $1 }')
	in_out_dims=$(echo $in_out | awk -F':' '{ print $2 }')
	echo "BS: $batch_size, ISL/OSL: $in_out_dims"

	mpirun -n 8 --allow-run-as-root --oversubscribe ./cpp/build/benchmarks/gptSessionBenchmark --engine_dir /tmp/llama/70B/trt_engines/int4_AWQ/8-gpu/ --warm_up 1 --batch_size $batch_size --duration 0 --num_runs 5 --input_output_len $in_out_dims
done

Please find the result below

![image](https://github.com/NVIDIA/TensorRT-LLM/assets/41502651/9a57c346-303d-4933-a6cc-e0f2f30f9f15)

Used TensorRT LLM Version 0.11.0.dev2024052800 and nvidia-modelopt version 0.11.2 on 8 x H100 GPUS

**Comment by Tracin** [comment]
@canamika27 Hi, after check with team, data in Modelopt doc is not compared under same tp_size. Specifically, for batch_size=2, AWQ and FP8 use tp_size=1 and compared with FP16 tp_size=2. For batch_size=32 and 64, AWQ and FP8 use tp_size=2 and FP16 uses tp_size=4.

**Comment by canamika27** [comment]
@Tracin  -- Thanks for the information, so can the tp_size=8 causing performance degradation for AWQ model ? so for quantized or fp8 model we need to run on lower tp_size as compared to FP16

**Comment by hijkzzz** [comment]
> @Tracin -- Thanks for the information, so can the tp_size=8 causing performance degradation for AWQ model ? so for quantized or fp8 model we need to run on lower tp_size as compared to FP16

This is a trick.

**Comment by canamika27** [comment]
@Tracin -- I tried AWQ with tp_size=1 and FP16 with tp_size=1 & tp_size=2 (for llama3-8B) still I am getting low throughput at batch size>=8. How to reproduce the results shared in TensorRT-Model-Optimizer benchmark.md (https://github.com/NVIDIA/TensorRT-Model-Optimizer/blob/main/benchmark.md)

![image](https://github.com/NVIDIA/TensorRT-LLM/assets/41502651/a6689e91-2a64-4629-a034-5709d20c01f0)
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/41502651/a6689e91-2a64-4629-a034-5709d20c01f0)

![image](https://github.com/NVIDIA/TensorRT-LLM/assets/41502651/131c36c1-5488-412c-8366-3da299371a69)
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/41502651/131c36c1-5488-412c-8366-3da299371a69)
