### ISSUE TITLE
Conditionals seems to be evaluated eagerly

### ISSUE THREAD

**Issue by CrimsonRadiator** [NVIDIA/TensorRT-LLM#1724]
### System Info

-   TensorRT-LLM version: 0.10.0.dev2024050700  
    (I doubt any other information is relevant)

### Who can help?

@kaiyux 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

Modify existing Transformer Decoder block structure to use `conditional` operation in the following way

```python
    def forward(self, x, ...): 
    	router_decision = constant_to_tensor_(True)
    	original = x
    	...
    	x = conditional(router_decision, self.input_layernorm(x), original)
    	x = conditional(router_decision, self.mlp(x), original)
    	...
    	return x
```
In Qwen case, the forward in `QWenDecoderLayer`:
```python
    def forward(
        self,
        hidden_states: Tensor,
        attention_mask=None,
        use_cache=False,
        kv_cache_params=None,
        attention_params=None,
    ):
        router_decision = constant_to_tensor_(False)

        original_residual = hidden_states


        hidden_states = conditional(router_decision, self.input_layernorm(hidden_states), original_residual)

        attention_output = conditional(router_decision,
                                       self.attention(
                                            hidden_states,
                                            attention_mask=attention_mask,
                                            use_cache=use_cache,
                                            kv_cache_params=kv_cache_params,
                                            attention_params=attention_params,
                                       )[0],
                                       original_residual)

        if use_cache:
            attention_output, presents = attention_output, None

        hidden_states = conditional(router_decision, original_residual + attention_output, original_residual)

        residual = hidden_states

        hidden_states = conditional(router_decision, self.post_layernorm(hidden_states), original_residual)

        hidden_states = conditional(router_decision, self.mlp(hidden_states), original_residual)

        hidden_states = conditional(router_decision, residual + hidden_states, original_residual)

        if use_cache:
            return (hidden_states, presents)
        return hidden_states


```

### Expected behavior

Changing `True` to `False` should lower the model latency by a lot

### actual behavior

The latency is constant regardless of `router_decision` value

### additional notes

I’m working on a dynamic token routing implementation for Transformer blocks. These are methods where, during inference, you route tokens either through the block or around the block. See the recent Mixture Of Depths paper for example: [https://arxiv.org/abs/2404.02258](https://arxiv.org/abs/2404.02258).

The only way I found so far to implement this in `TensorRT-LLM`, is using `conditional` operation from `functional.py`. Unfortunately, during my experiments, it seems that both branches of `conditional` are executed eagerly rather than lazily.

In my code, I have a transformer block with structure like:

```python
    def forward(self, x, ...): 
    	router_decision = constant_to_tensor_(True)
    	original = x
    	...
    	x = conditional(router_decision, self.input_layernorm(x), original)
    	x = conditional(router_decision, self.mlp(x), original)
    	...
    	return x
```

So essentially, if `router_decision` is `True`, then we do a lot of computation, and if it is `False` we skip a lot of computation.

In this simplified example, `router_decision` is constant, while in real code it is data-dependent (calculated using `x`)

Nevertheless, it seems that it doesn’t matter what is the value of `router_decision` is, the computation time is the same (and consistent with executing the block, not skipping).

During my experiments, I’ve modified `model.py` of Qwen model and measured latencies using `run.py` script. Here are the values of avg. latency:

-   True: `4.05 sec`
-   False: `4.05 sec`
-   Deleted: `0.76 sec`

Where True / False cases refer to the value of `router_decision`, and Deleted is “forced” skip connection:

```python
    def forward(self, x, ...): 
	    return x
```

Which should have similar latency to the False case.

This result is surprising, since in the TensorRT documentation [https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#work-with-conditionals](https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#work-with-conditionals) we can read that conditional operations should be evaluated lazily (unless I’m missing something)

So here are my questions:

1.  Am I abusing `conditional` operation by setting `true_input` not as simple tensor but result of some operation ( `self.mlp(x)` in `conditional(router_decision, self.mlp(x), original)`). If so, how would you implement this routing?
2.  Are conditionals in `TensorRT-LLM` always eagerly evaluated?
3.  Can we force them to be lazily evaluated?

It’s not easy for me to isolate the problem, and I’m not sure at which level it even is (conditional implementation in `TensorRT-LLM`? Some graph rewriting in `TensorRT`?)

Without lazy evaluation of conditionals, it’s unfortunately impossible to implement dynamic token routing methods in TensorRT, which is a promising research direction.

I can provide you with the code needed to reproduce the results if needed, and I’m happy to help in other ways.

**Comment by hijkzzz** [comment]
Let me summarize: the issue is that the current API of TRT-LLM cannot efficiently implement real SkipLayer.
A way to implement this is by making `conditional` API lazy execution.
Do you conveniently provide a performance test script (using condition vs deleted)

**Comment by nv-guomingz** [comment]
+ @AdamzNV  @ncomly-nvidia  for vis

**Comment by avianion** [comment]
Following up on this @CrimsonRadiator did you find a way to make this work?

This flow is also required in our project

@nv-guomingz @hijkzzz Any fix yet?

**Comment by CrimsonRadiator** [comment]
@avianion I didn't find any workaround

Replicating this bug (?) is not straightforward and unfortunately I didn't have time to do so.

**Comment by sunghyunjun** [comment]
It seems that a solution has been found.
You can either use the `Class Conditional` from commit b777bd6 or refer to its implementation.

https://github.com/NVIDIA/TensorRT-LLM/blob/b777bd64750abf30ca7eda48e8b6ba3c5174aafd/tensorrt_llm/functional.py#L1309

An example of its usage can be found below.

https://github.com/NVIDIA/TensorRT-LLM/blob/b777bd64750abf30ca7eda48e8b6ba3c5174aafd/tensorrt_llm/layers/attention.py#L648

The official documentation states the following:

> Instances of IIfConditionalInputLayer can be used to specify which layers are invoked eagerly and which are invoked lazily. This is done by tracing the network layers backwards, starting with each of the conditional outputs. Layers that are data-dependent on the output of at least one IIfConditionalInputLayer are considered internal to the conditional and are therefore evaluated lazily. In the extreme case that no instances of IIfConditionalInputLayer are added to the conditional, all of the layers are executed eagerly, similarly to ISelectLayer.

In other words, you need to use `add_input` to provide an input tensor to `IIfConditionalInputLayer` and build the graph from there.

When using the previous conditional method, if you pass `self.input_layernorm(x)`, it seems that the graph output tensor becomes the `IIfConditionalInputLayer` instead of being traced from `x`.

`x = conditional(router_decision, self.input_layernorm(x), original)`

The general structure will look something like this. I achieved lazy evaluation this way.
The following code has not been tested. It applies the `Class Conditional` implementation.



```python
conditional = default_trtnet().add_if_conditional()
condition = router_decision
if condition.ndim() > 0:
    condition = F.view(condition, [])
conditional.set_condition(condition.trt_tensor)

# Input tensors
original_in_node = conditional.add_input(original.trt_tensor)
original_ = F._create_tensor(original_in_node.get_output(0), original_in_node)
x_in_node = conditional.add_input(x.trt_tensor)
x_ = F._create_tensor(x_in_node.get_output(0), x_in_node)
layernorm = self.input_layernorm(x_)

# Set outputs
x_out_node = conditional.add_output(layernorm.trt_tensor, original_.trt_tensor)
x = F._create_tensor(x_out_node.get_output(0), x_out_node)
```

**Comment by nv-guomingz** [comment]
Hi @CrimsonRadiator do u still have further issue or question now? If not, we'll close it soon.
