### ISSUE TITLE
Whisper custom vocabulary with special token support

### ISSUE THREAD

**Issue by prise6** [NVIDIA/TensorRT-LLM#1727]
Hello,
I'm wondering if you tested to provide an "initial prompt" with whisper v3 to inform the model of specific vocab for the transcription task ?

It's written that we can follow this kind of template:
```
<|startofprev|>specific jargon<|startoftranscript|><|en|><|transcribe|>
```
Source : https://github.com/openai/whisper/discussions/117

In my test, it doesn't seem to work : `specific jargon` is re-written at the beggining of my transcription.

Before going further, is this feature available in your implementation ?

Thank you.

**Comment by hijkzzz** [comment]
Assign to @yuekaizhang.

**Comment by yuekaizhang** [comment]
> the beggining of my transcription.
> 
> Before going further, is this feature available in your implementation ?

@prise6 You could modify here https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/whisper/run.py#L249. You will get the same result with openai/whisper.
