### ISSUE TITLE
When I used convert_checkpoint.py to convert LLama3 hf format, It print killed

### ISSUE THREAD

**Issue by xjl456852** [NVIDIA/TensorRT-LLM#1728]
### System Info

- CPU architecture ( x86_64)
- CPU/Host memory size (48GB)
- GPU properties
  - GPU name ( NVIDIA RTX4070)
  - GPU memory size (8GB)

- Libraries
  - TensorRT-LLM branch or tag (v0.8.0)
  - Versions of TensorRT  CUDA
  - Container used (nvidia/cuda:12.4.0-devel-ubuntu22.04 )
- NVIDIA driver version 12.4
- OS (Windows 10)

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1.  git clone -b v0.8.0 https://github.com/NVIDIA/TensorRT-LLM.git  

2 . docker run -itd --name trt-llm --runtime=nvidia --gpus all -v  G:/data/ai/llm:/root/projects -v G:/data/ai/llm/models:/root/models -p 8000:8000  nvidia/cuda:12.4.0-devel-ubuntu22.04  

3. docker exec -it trt-llm /bin/bash

4. apt-get update && apt-get -y install python3.10 python3-pip openmpi-bin libopenmpi-dev git  

5. pip3 install tensorrt_llm==0.8.0 -U --extra-index-url https://pypi.nvidia.com  
6. cd /root/projects/TensorRT-LLM/examples/llama
7. python3 convert_checkpoint.py --model_dir /root/models/Meta-Llama-3-8B-Instruct-hf \
--output_dir /root/models/output/example-2/tllm_checkpoint_1gpu_fp16_wq \
--dtype float16 \
--use_weight_only \
--load_model_on_cpu \
--weight_only_precision int8

### Expected behavior

success

### actual behavior

Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:09<00:00,  2.38s/it]Weights loaded. Total time: 00:07:40
Killed

### additional notes

My computer has a lot of free cpu memory.
but the command prompt killed, no other informations.
<img width="532" alt="880cf1ddf2d2583e596342b5ec39cd2" src="https://github.com/NVIDIA/TensorRT-LLM/assets/8008097/1e11e2e5-f9b5-49ad-b71a-4f543f93cb9b">

**Comment by hijkzzz** [comment]
Could you please try the main branch?
Older versions such as 0.8 are not recommended.
Converting llama3 8b requires about 16GB of available memory.

**Comment by xjl456852** [comment]
When I used main branch to run the command, the code prompts the following.
```python
[TensorRT-LLM] TensorRT-LLM version: 0.8.0Traceback (most recent call last):
  File "/root/projects/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 9, in <module>
    from tensorrt_llm._utils import release_gc
ImportError: cannot import name 'release_gc' from 'tensorrt_llm._utils' (/usr/local/lib/python3.10/dist-packages/tensorrt_llm/_utils.py)
```

**Comment by hijkzzz** [comment]
Hi just try:
```
pip install tensorrt_llm==0.11.0.dev2024052800
```
using docker image: nvcr.io/nvidia/tritonserver:24.05-trtllm-python-py3

**Comment by PrintGjb** [comment]
Converting llama3 8b requires about 48GB of available memory.
