### ISSUE TITLE
Warning: Function too large, generated debug information may not be accurate.

### ISSUE THREAD

**Issue by nanmi** [NVIDIA/TensorRT-LLM#1730]
### System Info

GPU:A100
Mem: 1007G
TRTLLM: v0.9.0
G++\NVCC

When I build TensorRT_LLM, Warning: Function too large, generated debug information may not be accurate.

**Comment by 5cat** [comment]
Hello! May I ask if you can share the steps to preproduce the steps? Do you mean building the model or building tensorrt_llm source code?
If you could add the logs as well that would be helpful

**Comment by zzz3bbb3** [comment]
> Hello! May I ask if you can share the steps to preproduce the steps? Do you mean building the model or building tensorrt_llm source code? If you could add the logs as well that would be helpful

Thank you for your reply. My question is about the compilation process of TensorRT_LLM source code. The compilation method is the basic build_wheel.py application.

**Comment by nv-guomingz** [comment]
Hi @5cat do u still have further issue or question now? If not, we'll close it soon.
