### ISSUE TITLE
Enabling w4a16 and 2:4 sparsity.

### ISSUE THREAD

**Issue by jianyuheng** [NVIDIA/TensorRT-LLM#1731]
I found that performance which enabling w4a16 and 2：4 sparsity is similar to enabling w4a16 alone.

**Comment by hijkzzz** [comment]
from Chong (TRT-LLM engineer): Recently, I have been testing the sparse performance of TRT-LLM.
Indeed, both BF16 and FP8 have acceleration ratios within 5% (GPT3-843M).

**Comment by youki-sada** [comment]
@hijkzzz @jianyuheng Do you have any information for reduction of VRAM footprint?
