### ISSUE TITLE
How to use `enable_block_reuse` for `ModelRunner` class ?

### ISSUE THREAD

**Issue by DefTruth** [NVIDIA/TensorRT-LLM#1736]
### System Info

none

### Who can help?

@juney-nvidia 

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

none

### Expected behavior

How to use `enable_block_reuse` for `ModelRunner` class ?

### actual behavior

any docs?

### additional notes

none

**Comment by nv-guomingz** [comment]
You may refer to https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/summarize.py#L790
