### ISSUE TITLE
Loading part of the model using one GPU

### ISSUE THREAD

**Issue by Hudayday** [NVIDIA/TensorRT-LLM#1743]
I plan to measure the latency and other performance metrics of a model using high-level Tensor Parallelism. However, when using TensorRT-LLM, I have to run the model using all GPUs.

Is there a way to either:

Convert the HF checkpoint to TensorRT-LLM format for just one slice of the model,
or
Run the model by loading one slice on one GPU?

**Comment by hijkzzz** [comment]
Use `export CUDA_VISIBLE_DEVICES=xxxx`?

**Comment by Hudayday** [comment]
No, it will crash if you build engine for more than 1 GPU but only use 1 GPU

**Comment by hijkzzz** [comment]
> No, it will crash if you build engine for more than 1 GPU but only use 1 GPU

You can use --workers to specify the number of worker processes to build the engine.
such as tp_size = 4, workers = 1

**Comment by Hudayday** [comment]
I mean to perform real inference serving using a part of the model on a single GPU, not to build the engine. 

For example, if I build Llama-70B with tp = 8, can I eventually run it with mpirun = 1 instead of 8? 

I don't need the output; I just want to know the end-to-end latency of this part of the model on this GPU. This is how I intend to test the performance of a slice of the model.

**Comment by hijkzzz** [comment]
> I mean to perform real inference serving using a part of the model on a single GPU, not to build the engine.
> 
> For example, if I build Llama-70B with tp = 8, can I eventually run it with mpirun = 1 instead of 8?
> 
> I don't need the output; I just want to know the end-to-end latency of this part of the model on this GPU. This is how I intend to test the performance of a slice of the model.

TRT-LLM does not support this feature currently.
