### ISSUE TITLE
what's the difference between ModelRunner and ModelRunnerCpp? Any docs?

### ISSUE THREAD

**Issue by DefTruth** [NVIDIA/TensorRT-LLM#1744]
### System Info

None

### Who can help?

@ju

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

None

### Expected behavior

None

### actual behavior

None

### additional notes

None

**Comment by hijkzzz** [comment]
ModelRunnerCpp is recommended (Higher performance and more complete features)
ModelRunner is the Python Runner.

**Comment by DefTruth** [comment]
> ModelRunnerCpp is recommended (Higher performance and more complete features) ModelRunner is the Python Runner.

@hijkzzz so, it means that i can try to change the  `ModelRunner` class to `ModelRunnerCpp` class directly and may get higher performance, for example: https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/multimodal/run.py#L27, I use this script for LLaVA model and want to enable block reuse feature.

**Comment by hijkzzz** [comment]
> > ModelRunnerCpp is recommended (Higher performance and more complete features) ModelRunner is the Python Runner.
> 
> @hijkzzz so, it means that i can try to change the `ModelRunner` class to `ModelRunnerCpp` class directly and may get higher performance, for example: https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/multimodal/run.py#L27, I use this script for LLaVA model and want to enable block reuse feature.

Some models can only use their own runner (such as DiT)

**Comment by DefTruth** [comment]
@hijkzzz llava切换成ModelRunnerCpp根本跑不起来，报了一堆错误.... 而且ModelRunner和ModelRunnerCpp很多接口不一致。。。。

**Comment by DefTruth** [comment]
> @hijkzzz llava切换成ModelRunnerCpp根本跑不起来，报了一堆错误.... 而且ModelRunner和ModelRunnerCpp很多接口不一致。。。。体验很差。。。。

包括ModelRunnerCpp、SamplingConfig等，存在许多同名但是不完全等价的两套API，有没有简单一点的方式可以在llava的示例之中切换成ModelRunnerCpp，并且使用kv cache reuse？

**Comment by DefTruth** [comment]
为啥要有两套呢？而不是只维护一套ModelRunnerCpp？感觉trtllm经常跑着跑着就跑不通了，特别是想要升级的时候。性能确实是很好，但是用户体验实在太差了。跑都跑不起来性能再好有啥用.................

**Comment by DefTruth** [comment]
大部分时间都花在排查trtllm各种奇怪的问题上了。。。。。。

**Comment by hijkzzz** [comment]
> 为啥要有两套呢？而不是只维护一套ModelRunnerCpp？感觉trtllm经常跑着跑着就跑不通了，特别是想要升级的时候。性能确实是很好，但是用户体验实在太差了。跑都跑不起来性能再好有啥用.................

Yes, we are improving this aspect, such as the High-level API：https://github.com/NVIDIA/TensorRT-LLM/tree/main/tensorrt_llm/hlapi. ModelRunnerCpp is recommended for the most models.

**Comment by DefTruth** [comment]
切换成ModelRunnerCpp报了很多类似错误：
```bash
 0%|          | 1/300 [00:06<31:49,  6.39s/it][TensorRT-LLM][ERROR] 7: [shapeMachine.cpp::executeContinuation::905] Error Code 7: Internal Error (LLaMAForCausalLM/transformer/vocab_embedding/__add__/elementwise_binary/ELEMENTWISE_SUM_0: dimensions not compatible for elementwise. Broadcast has incompatible dimensions: 743 != 103 && 743 != 1 && 103 != 1. Instruction: CHECK_BROADCAST 743 103.)
[TensorRT-LLM][ERROR] Encountered an error in forwardAsync function: Invalid input shape (/workspace/dev/openllm/TensorRT-LLM/cpp/tensorrt_llm/runtime/tllmRuntime.cpp:205)
1       0x7ff56dcc654c /root/anaconda3/envs/aigc/lib/python3.10/site-packages/tensorrt_llm/libs/libtensorrt_llm.so(+0x77a54c) [0x7ff56dcc654c]
2       0x7ff56fddb6bf tensorrt_llm::batch_manager::TrtGptModelInflightBatching::setupContext(std::vector<std::shared_ptr<tensorrt_llm::batch_manager::LlmRequest>, std::allocator<std::shared_ptr<tensorrt_llm::batch_manager::LlmRequest> > > const&, std::vector<std::shared_ptr<tensorrt_llm::batch_manager::LlmRequest>, std::allocator<std::shared_ptr<tensorrt_llm::batch_manager::LlmRequest> > > const&, int) + 367
3       0x7ff56fddb8f9 tensorrt_llm::batch_manager::TrtGptModelInflightBatching::executeBatch(tensorrt_llm::batch_manager::ScheduledRequests const&) + 489
4       0x7ff56fde8d09 tensorrt_llm::batch_manager::TrtGptModelInflightBatching::forwardAsync(std::list<std::shared_ptr<tensorrt_llm::batch_manager::LlmRequest>, std::allocator<std::shared_ptr<tensorrt_llm::batch_manager::LlmRequest> > > const&) + 2425
```
太痛苦了

**Comment by hijkzzz** [comment]
> 切换成ModelRunnerCpp报了很多类似错误：
> 
> ```shell
>  0%|          | 1/300 [00:06<31:49,  6.39s/it][TensorRT-LLM][ERROR] 7: [shapeMachine.cpp::executeContinuation::905] Error Code 7: Internal Error (LLaMAForCausalLM/transformer/vocab_embedding/__add__/elementwise_binary/ELEMENTWISE_SUM_0: dimensions not compatible for elementwise. Broadcast has incompatible dimensions: 743 != 103 && 743 != 1 && 103 != 1. Instruction: CHECK_BROADCAST 743 103.)
> [TensorRT-LLM][ERROR] Encountered an error in forwardAsync function: Invalid input shape (/workspace/dev/openllm/TensorRT-LLM/cpp/tensorrt_llm/runtime/tllmRuntime.cpp:205)
> 1       0x7ff56dcc654c /root/anaconda3/envs/aigc/lib/python3.10/site-packages/tensorrt_llm/libs/libtensorrt_llm.so(+0x77a54c) [0x7ff56dcc654c]
> 2       0x7ff56fddb6bf tensorrt_llm::batch_manager::TrtGptModelInflightBatching::setupContext(std::vector<std::shared_ptr<tensorrt_llm::batch_manager::LlmRequest>, std::allocator<std::shared_ptr<tensorrt_llm::batch_manager::LlmRequest> > > const&, std::vector<std::shared_ptr<tensorrt_llm::batch_manager::LlmRequest>, std::allocator<std::shared_ptr<tensorrt_llm::batch_manager::LlmRequest> > > const&, int) + 367
> 3       0x7ff56fddb8f9 tensorrt_llm::batch_manager::TrtGptModelInflightBatching::executeBatch(tensorrt_llm::batch_manager::ScheduledRequests const&) + 489
> 4       0x7ff56fde8d09 tensorrt_llm::batch_manager::TrtGptModelInflightBatching::forwardAsync(std::list<std::shared_ptr<tensorrt_llm::batch_manager::LlmRequest>, std::allocator<std::shared_ptr<tensorrt_llm::batch_manager::LlmRequest> > > const&) + 2425
> ```
> 
> 太痛苦了

For the multi-modal models, you could use python runtime first.

**Comment by DefTruth** [comment]
@hijkzzz 很抱歉，吐槽地有点过了。trtllm性能很不错，点赞。但是最近使用遇到实在太过问题了，包括结合triton server后遇到一些其他的问题。以及想要升级，发现升级后旧代码跑不通的问题。有点难绷。希望trtllm越做越好~

**Comment by DefTruth** [comment]
再补画一个自己会比较喜欢的使用模式。假设存在一个模块为trtllm-launcher，它可以将目前TensorRT-LLM各个分离的阶段（convert、build、server）进行整合和自动化。

- Automatic Checkpoint Converter: 首先convert是可以自动化的，现在是放在了examples而不是核心模块；
- Automatic Engine Builder: 其次build engine（非ammo量化）的耗时其实也很短，也完全是可以自动化的；
- Triton Server Wrapper: 而且triton server的概念没有必要暴露给用户，并且server的代码应该属于框架的一部分，参考lmdeploy的做法，完全是可以封装起来，让用户无感知；
- OpenAI Compatible Server: 最后，OpenAI协议要支持起来。没支持的话，大概率会导致用户需要自己额外封装，很可能会引入额外的bug，排查起来耗时耗力，还不太好给出复现问题的脚本。

![image](https://github.com/NVIDIA/TensorRT-LLM/assets/31974251/1e6dc02e-70fa-47ad-bf2d-afc71ac9f4cd)

**Comment by DefTruth** [comment]
Can we use ModelRunnerCpp for  multi-modal models now?

**Comment by lmcl90** [comment]
@DefTruth We have already run QWenVL by calling the executor API in c++. ModelRunenerCpp must be the python wrapper for the executor API and should already support multimodal models.  One issue to note is that reuse kv cache blocks are not supported, otherwise the error mentioned above will occur：

> > 切换成ModelRunnerCpp报了很多类似错误：
> > ```shell
> >  0%|          | 1/300 [00:06<31:49,  6.39s/it][TensorRT-LLM][ERROR] 7: [shapeMachine.cpp::executeContinuation::905] Error Code 7: Internal Error (LLaMAForCausalLM/transformer/vocab_embedding/__add__/elementwise_binary/ELEMENTWISE_SUM_0: dimensions not compatible for elementwise. Broadcast has incompatible dimensions: 743 != 103 && 743 != 1 && 103 != 1. Instruction: CHECK_BROADCAST 743 103.)
> > [TensorRT-LLM][ERROR] Encountered an error in forwardAsync function: Invalid input shape (/workspace/dev/openllm/TensorRT-LLM/cpp/tensorrt_llm/runtime/tllmRuntime.cpp:205)
> > 1       0x7ff56dcc654c /root/anaconda3/envs/aigc/lib/python3.10/site-packages/tensorrt_llm/libs/libtensorrt_llm.so(+0x77a54c) [0x7ff56dcc654c]
> > 2       0x7ff56fddb6bf tensorrt_llm::batch_manager::TrtGptModelInflightBatching::setupContext(std::vector<std::shared_ptr<tensorrt_llm::batch_manager::LlmRequest>, std::allocator<std::shared_ptr<tensorrt_llm::batch_manager::LlmRequest> > > const&, std::vector<std::shared_ptr<tensorrt_llm::batch_manager::LlmRequest>, std::allocator<std::shared_ptr<tensorrt_llm::batch_manager::LlmRequest> > > const&, int) + 367
> > 3       0x7ff56fddb8f9 tensorrt_llm::batch_manager::TrtGptModelInflightBatching::executeBatch(tensorrt_llm::batch_manager::ScheduledRequests const&) + 489
> > 4       0x7ff56fde8d09 tensorrt_llm::batch_manager::TrtGptModelInflightBatching::forwardAsync(std::list<std::shared_ptr<tensorrt_llm::batch_manager::LlmRequest>, std::allocator<std::shared_ptr<tensorrt_llm::batch_manager::LlmRequest> > > const&) + 2425
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 太痛苦了
> 
> For the multi-modal models, you could use python runtime first.

**Comment by DefTruth** [comment]
> @DefTruth We have already run QWenVL by calling the executor API in c++. ModelRunenerCpp must be the python wrapper for the executor API and should already support multimodal models. One issue to note is that reuse kv cache blocks are not supported, otherwise the error mentioned above will occur：
> 
> > > 切换成ModelRunnerCpp报了很多类似错误：
> > > ```shell
> > >  0%|          | 1/300 [00:06<31:49,  6.39s/it][TensorRT-LLM][ERROR] 7: [shapeMachine.cpp::executeContinuation::905] Error Code 7: Internal Error (LLaMAForCausalLM/transformer/vocab_embedding/__add__/elementwise_binary/ELEMENTWISE_SUM_0: dimensions not compatible for elementwise. Broadcast has incompatible dimensions: 743 != 103 && 743 != 1 && 103 != 1. Instruction: CHECK_BROADCAST 743 103.)
> > > [TensorRT-LLM][ERROR] Encountered an error in forwardAsync function: Invalid input shape (/workspace/dev/openllm/TensorRT-LLM/cpp/tensorrt_llm/runtime/tllmRuntime.cpp:205)
> > > 1       0x7ff56dcc654c /root/anaconda3/envs/aigc/lib/python3.10/site-packages/tensorrt_llm/libs/libtensorrt_llm.so(+0x77a54c) [0x7ff56dcc654c]
> > > 2       0x7ff56fddb6bf tensorrt_llm::batch_manager::TrtGptModelInflightBatching::setupContext(std::vector<std::shared_ptr<tensorrt_llm::batch_manager::LlmRequest>, std::allocator<std::shared_ptr<tensorrt_llm::batch_manager::LlmRequest> > > const&, std::vector<std::shared_ptr<tensorrt_llm::batch_manager::LlmRequest>, std::allocator<std::shared_ptr<tensorrt_llm::batch_manager::LlmRequest> > > const&, int) + 367
> > > 3       0x7ff56fddb8f9 tensorrt_llm::batch_manager::TrtGptModelInflightBatching::executeBatch(tensorrt_llm::batch_manager::ScheduledRequests const&) + 489
> > > 4       0x7ff56fde8d09 tensorrt_llm::batch_manager::TrtGptModelInflightBatching::forwardAsync(std::list<std::shared_ptr<tensorrt_llm::batch_manager::LlmRequest>, std::allocator<std::shared_ptr<tensorrt_llm::batch_manager::LlmRequest> > > const&) + 2425
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 太痛苦了
> > 
> > 
> > For the multi-modal models, you could use python runtime first.

thanks for you rely! 
@lmcl90 you mean this one? https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/qwenvl/run.py

**Comment by lmcl90** [comment]
@DefTruth Yes, it is.

**Comment by zhangts20** [comment]
> @DefTruth Yes, it is.

你好，这个文件里边的 generate 好像也是 python 实现的？有 c++ 实现的 demo 吗，谢谢！
