### ISSUE TITLE
Does TensorRT-LLM support high concurrent requests?

### ISSUE THREAD

**Issue by Godlovecui** [NVIDIA/TensorRT-LLM#1745]
### System Info

RTX 8*4090

### Who can help?

@kaiyux @byshiue @ncoml

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

None

### Expected behavior

None

### actual behavior

None

### additional notes

I use TensorRT-LLM + Triton server to deploy llama3-8B, the response time（0.089s） is very low when request is 1, howerver,  the response time is 6.68s when request is 2, which is ~80x bigger. How to fix it ?

**Comment by hijkzzz** [comment]
Have you turned on Inflight batching and set engine max-batch-size to > 1

**Comment by Godlovecui** [comment]
> Have you turned on Inflight batching and set max-batch-size to > 1

yes, I build engine with --max_batch_size=64 and set batching_strategy to inflight_batching in tensorrt_llm/config.pbtxt

**Comment by hijkzzz** [comment]
> > Have you turned on Inflight batching and set max-batch-size to > 1
> 
> yes, I build engine with --max_batch_size=64 and set batching_strategy to inflight_batching in tensorrt_llm/config.pbtxt

Can you provide a reproducible settings (versions? deps?) and the python script? Please try the latest version under main branch first, if there is a problem on main branch we will try to fix it.

**Comment by Godlovecui** [comment]
The version is v0.9.0. 
Thank you very much!

**Comment by hijkzzz** [comment]
> The version is v0.9.0. Mr Hu, Are you base in Shanghai? How can we chat with wechat(Bobcuicui)? Thank you very much!

Just try pip install tensorrt_llm==0.11.0.dev2024060400
also update the trition_server (https://github.com/triton-inference-server/tensorrtllm_backend/commit/39ba55a745266bbc50cf19af0f5dfcad1c939c12).
Thanks

**Comment by Godlovecui** [comment]
The 0.11.0.dev is not a pulished version.  The version of triton server is only v0.9.0。The two version are incompatible，which may have other issues.

**Comment by hijkzzz** [comment]
Hi the main branch of triton_tensorrtllm_backend and tensorrt_llm (now it is =0.11.0.dev2024060400) is updated simultaneously
