### ISSUE TITLE
‘cudaStream_t’ has not been declared when building tensorrt_llm v0.10.0

### ISSUE THREAD

**Issue by zhangts20** [NVIDIA/TensorRT-LLM#1748]
### System Info

CPU: INTEL
GPU Name: A100-SXM4-80GB
TensorRT-LLM: tag v0.10.0
Container Used: No
Driver Version: 535.54.03
CUDA Version: 12.1
OS: Ubuntu 22.04
Others: tensorrt==10.0.1.16, pytorch==2.2.0+cu121, python==3.10.12

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

python scripts/build_wheel.py --trt_root=/usr/local/tensorrt --clean --install --cuda_architectures="80-real"

### Expected behavior

Works fine

### actual behavior

xxx/TensorRT-LLM/cpp/tensorrt_llm/kernels/lruKernel.h:48:37: error: ‘cudaStream_t’ has not been declared
   48 | void invokeRGLRU(lruParams& params, cudaStream_t stream);
      |                                     ^~~~~~~~~~~~
xxx/TensorRT-LLM/cpp/tensorrt_llm/kernels/lruKernel.h:51:43: error: ‘cudaStream_t’ has not been declared
   51 | void invokeRGLRUUpdate(lruParams& params, cudaStream_t stream);
      |                                           ^~~~~~~~~~~~

### additional notes

No

**Comment by hijkzzz** [comment]
Env issue
Try this container: nvcr.io/nvidia/tritonserver:24.05-trtllm-python-py3

**Comment by zhangts20** [comment]
@hijkzzz Can you share the solution? I want to install tensorrt_llm in my own docker env, thanks

**Comment by hijkzzz** [comment]
> @hijkzzz Can you share the solution? I want to install tensorrt_llm in my own docker env, thanks

You could build the container that come FROM this container
Or use pip install tensorrt_llm==xxx in your container.

**Comment by zhangts20** [comment]
@hijkzzz thanks! I have installed it successfully using pip install tensorrt_llm==xxx

**Comment by yorickvP** [comment]
In case anyone else wants to build from source, add `#include <cuda_runtime.h>` to `cpp/tensorrt_llm/kernels/lruKernel.h`
