### ISSUE TITLE
The new llama build failed.

### ISSUE THREAD

**Issue by liyu-tan** [NVIDIA/TensorRT-LLM#175]
I tried to use the main branch triton. (heard that the early stop had been fixed, so want to test it)
And I tried to convert the engine with 7b model. I got this error:
```
-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/torch/multiprocessing/spawn.py", line 74, in _wrap
    fn(i, *args)
  File "/home/ga/uber-bundle/uber-triton-workspace/src/tensorrtllm_backend/tensorrt_llm/examples/llama/build.py", line 668, in build
    int8_trt_flag = args.quant_mode.has_act_or_weight_quant() or (
AttributeError: 'QuantMode' object has no attribute 'has_act_or_weight_quant'
```

Not sure if there is other things need to upgrade?

**Comment by uppalutkarsh** [comment]
HI @liyu-tan ,

Can you share the commands you are using to build image, build engine along with your GPU, CUDA details?

**Comment by jdemouth-nvidia** [comment]
Also, are you sure you've properly re-built from a clean directory and re-installed the wheels. I see the function `has_act_or_weight_quant` in `QuantMode` in the `main` branch at [line 72](https://github.com/NVIDIA/TensorRT-LLM/blob/d8b408e6dcc1d45982a8b94399cd74b78f80befa/tensorrt_llm/quantization/mode.py#L72C15-L72C15).

**Comment by liyu-tan** [comment]
Hi Julien,

What I did is clone the main branch, since (Alec and Ananth recommends that
our P0 (early stop, and output_0 is ensemble endpoint also contain input)
is being solved in the main branch. This is blocking our production use
case.

What I tried is follow alec's guide to build it.

The conversion cmd is:
python examples/llama/build.py --max_batch_size 1 --max_input_len 3400
--max_output_len 500 --model_dir=/home/liyu.tan/Llama-2-7b-hf-ft-delivery/
--use_gpt_attention_plugin float16 --use_gemm_plugin float16
--use_rmsnorm_plugin float16  --use_inflight_batching
 --remove_input_padding --parallel_build --enable_context_fmha
 --paged_kv_cache --output_dir
/home/liyu.tan/Llama-2-7b-hf-ft-delivery/trt_engines/2-gpu-oct
--world_size=2 --tp_size=2


best,

Liyu

**Comment by wm2012011492** [comment]
Hi @liyu-tan , could you make sure your `build.py` and TRT-LLM package are from the same branch? There's an API change between main branch and release/0.5.0, i.e. main branch uses `args.quant_mode.has_act_or_weight_quant()` while release/0.5.0 uses `args.quant_mode.has_act_and_weight_quant()`.

**Comment by byshiue** [comment]
Close this bug because the issue is inactivated. Feel free to ask here if you still have question/issue, we will reopen the issue.
