### ISSUE TITLE
[Question] "Building from source code is necessary if you want the best performance"

### ISSUE THREAD

**Issue by DreamGenX** [NVIDIA/TensorRT-LLM#1750]
In the guide it says:

> Building from source code is necessary if you want the best performance
https://nvidia.github.io/TensorRT-LLM/installation/build-from-source-linux.html

I have a custom serving stack that requires me to build from source, and would like to understand what sort of performance knobs / benefits are available at build time.

**Comment by hijkzzz** [comment]
@QiJune @kaiyux Can you comment on this question?

**Comment by nv-guomingz** [comment]
@DreamGenX please refer to https://nvidia.github.io/TensorRT-LLM/performance/perf-best-practices.html

**Comment by DreamGenX** [comment]
@nv-guomingz Thank you, but I have read that guide, and that's about arguments for `trtllm-build`. The snipped from above is about building the library from source, so I was curious about that:

> **Building from source code** is necessary if you want the **best performance**
> https://nvidia.github.io/TensorRT-LLM/installation/build-from-source-linux.html

**Comment by nv-guomingz** [comment]
@Shixiaowei02 , would u please add comments here? is there any potential perf improvement introduced by building from the source code ?
