### ISSUE TITLE
[Question] Sutable GCP image to run TensorRT-LLM

### ISSUE THREAD

**Issue by snassimr** [NVIDIA/TensorRT-LLM#1752]
Hi,

I am really struggling to arrange a GCP VM instance with full set of Nvidia installations to run command : 

docker run --rm --runtime=nvidia --gpus all --entrypoint /bin/bash -it nvidia/cuda:12.1.0-devel-ubuntu22.04

I wonder if GCP has some ready image for this ?

Thanks

**Comment by hijkzzz** [comment]
could you try any ubuntu +cuda12.4 image and use pip install tenaorrt_llm == xxx  to intall the latest package?

**Comment by snassimr** [comment]
This GCP image allows me to complete my work and have all pre-installation : 

![image](https://github.com/NVIDIA/TensorRT-LLM/assets/6830626/58168a9c-18af-484d-9788-19e3e68f2289)
