### ISSUE TITLE
server.cc:251] failed to enable peer access for some device pairs

### ISSUE THREAD

**Issue by Godlovecui** [NVIDIA/TensorRT-LLM#1754]
### System Info

RTX 8*4090
version:
TensorRT-LLM: v0.9.0
tensorrtllm_backend: v0.9.0

### Who can help?

@kaiyux @BY

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

None

### Expected behavior

None

### actual behavior

None

### additional notes

When I deploy llama3-8B in trition server, it raises below error:
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/68674291/a1349560-fa8c-42f8-9ebf-790d543376bd)
but, it also print server launch successfully flag:
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/68674291/78b920e1-77a0-4d1a-8fa8-2cc82ee0b111)
However, when I send requests to server,
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/68674291/c8f2f7bb-e821-4089-a9e5-879751e47866)
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/68674291/4776dac5-034d-4e93-b72a-53cf3865a0bb)

How to fix it? Thank you~

**Comment by nv-guomingz** [comment]
Hi @Godlovecui ， I saw u're using the 0.9.0 trtllm, is it possible to try the latest main branch and see if the issue still exists or not?

**Comment by TheCodeWrangler** [comment]
Have you tried

`nvidia-smi topo -p2p r`

To inspect if the drivers for your GPUS are installed and support the peer to peer access?

Also I have encounterd similar issues where my default GPU installation required me to compile with `disabled` on the `use_custom_all_reduce` flag
