### ISSUE TITLE
failed to install tensorrt-llm==0.11.0.dev2024060400

### ISSUE THREAD

**Issue by AGI-player** [NVIDIA/TensorRT-LLM#1764]
installing the newest version==0.11.0.dev2024060400 , as follow:

conda create -n trt_llm python==3.10
conda activate trt_llm
apt-get update && apt-get -y install python3-pip openmpi-bin libopenmpi-dev git git-lfs
pip3 install tensorrt_llm -U --pre --extra-index-url https://pypi.nvidia.com

then, python3 -c "import tensorrt_llm" failed
<img width="730" alt="image" src="https://github.com/NVIDIA/TensorRT-LLM/assets/99712469/4a7efa72-6d4a-4025-8144-ba2150a18183">
<img width="557" alt="image" src="https://github.com/NVIDIA/TensorRT-LLM/assets/99712469/42b15cd8-3aef-45c3-89dd-aa7b54fef631">

**Comment by nv-guomingz** [comment]
@Shixiaowei02  would u please take a look on this question?

**Comment by Shixiaowei02** [comment]
I can not reproduce this issue using the official docker container, could you please provide me all the dependency versions or using the official docker image too? Thank you!

**Comment by AGI-player** [comment]
> I can not reproduce this issue using the official docker container, could you please provide me all the dependency versions or using the official docker image too? Thank you!

pip list as follows:
Package                  Version
------------------------ --------------------
accelerate               0.31.0
aiohttp                  3.9.5
aiosignal                1.3.1
annotated-types          0.7.0
async-timeout            4.0.3
attrs                    23.2.0
build                    1.2.1
certifi                  2024.6.2
charset-normalizer       3.3.2
cloudpickle              3.0.0
colored                  2.2.4
coloredlogs              15.0.1
cuda-python              12.5.0
datasets                 2.19.2
diffusers                0.28.2
dill                     0.3.8
evaluate                 0.4.2
filelock                 3.14.0
frozenlist               1.4.1
fsspec                   2024.3.1
h5py                     3.10.0
huggingface-hub          0.23.3
humanfriendly            10.0
idna                     3.7
importlib_metadata       7.1.0
janus                    1.0.0
Jinja2                   3.1.4
lark                     1.1.9
markdown-it-py           3.0.0
MarkupSafe               2.1.5
mdurl                    0.1.2
mpi4py                   3.1.4
mpmath                   1.3.0
multidict                6.0.5
multiprocess             0.70.16
networkx                 3.3
ninja                    1.11.1.1
numpy                    1.26.4
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-modelopt          0.11.2
nvidia-nccl-cu12         2.20.5
nvidia-nvjitlink-cu12    12.5.40
nvidia-nvtx-cu12         12.1.105
onnx                     1.16.1
optimum                  1.20.0
packaging                24.1
pandas                   2.2.2
pillow                   10.3.0
pip                      24.0
polygraphy               0.49.9
protobuf                 5.27.1
psutil                   5.9.8
PuLP                     2.8.0
pyarrow                  16.1.0
pyarrow-hotfix           0.6
pydantic                 2.7.3
pydantic_core            2.18.4
Pygments                 2.18.0
pynvml                   11.5.0
pyproject_hooks          1.1.0
python-dateutil          2.9.0.post0
pytz                     2024.1
PyYAML                   6.0.2rc1
regex                    2024.5.15
requests                 2.32.3
rich                     13.7.1
safetensors              0.4.3
scipy                    1.13.1
sentencepiece            0.2.0
setuptools               69.5.1
six                      1.16.0
StrEnum                  0.4.15
sympy                    1.13.0rc1
tensorrt                 10.0.1
tensorrt-cu12            10.0.1
tensorrt-cu12-bindings   10.0.1
tensorrt-cu12-libs       10.0.1
tensorrt-llm             0.11.0.dev2024060400
tokenizers               0.19.1
tomli                    2.0.1
torch                    2.3.0
tqdm                     4.66.4
transformers             4.40.2
triton                   2.3.0
typing_extensions        4.12.2
tzdata                   2024.1
urllib3                  2.2.1
wheel                    0.43.0
xxhash                   3.4.1
yarl                     1.9.4
zipp                     3.19.2

**Comment by AGI-player** [comment]
> I can not reproduce this issue using the official docker container, could you please provide me all the dependency versions or using the official docker image too? Thank you!

the new version 0.11.0.dev2024061800 can be installed successfully.
