### ISSUE TITLE
C++ GptManager setEndId + tensor parallelism -> engine hangs / frozen

### ISSUE THREAD

**Issue by DreamGenX** [NVIDIA/TensorRT-LLM#1767]
### System Info

I tried to use `setEndId` with `InferenceRequest` and the C++ `GptManager`. When I do so, here's what happens:

- The end token id is reached
- The rank 0 worker correctly stops (send response callback will also correctly indicate "finished")
- The other ranks never finish and are stuck at GPU 100%

This is not a problem with `setMaxNewTokens` stop condition -- in that case, all ranks finish correclty.

My workaround:

- Do not use `setEndId` at all
- Inside the send response callback, check if the last token id is == end id, if so, schedule the request to be stopped using poll stop signals callback

My setup:

- `[TensorRT-LLM] TensorRT-LLM version: 0.11.0.dev2024060400`
- 4xH100 SXM with nvlink
- Llama 3 70B quantized to fp8

More info:

- It works fine without setEndId -- setMaxNewTokens stops all ranks as expected
- It works fine with tensor parallelism == 1 (on smaller model)

```
trtllm-build \
--checkpoint_dir /workspace/llama3-70b-fp8 \
--output_dir /workspace/llama3-70b-fp8-tp4-engine \
--gemm_plugin auto \
--use_custom_all_reduce enable \
--multiple_profiles enable \
--max_num_tokens 32768 \
--max_batch_size 48 \
--max_input_len 8192 \
--max_output_len 4096 \
--workers 64 
```

I also tried with `--use_custom_all_reduce disable`, same issue.

### Who can help?

@bys

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

 - Use C++ GptManager with a multi-GPU setup. Use setEndId to make the model stop.
 - Issue a request that will result in endId being produced before max output tokens are reached.
 - Sometimes the first request might work and only the second one gets stuck.

### Expected behavior

  - All ranks should stop

### actual behavior

- Only rank 0 stops, other ranks hang with 100% GPU usage forever

### additional notes

 N/A

**Comment by nv-guomingz** [comment]
@schetlur-nv would u please take a look this issue?

**Comment by DreamGenX** [comment]
This was a user error: https://github.com/NVIDIA/TensorRT-LLM/issues/1771
