### ISSUE TITLE
Using TensorRT-LLM/examples/apps/fastapi_server.py as server inside TensorRT-LLM docker

### ISSUE THREAD

**Issue by snassimr** [NVIDIA/TensorRT-LLM#1768]
### System Info

- CPU architecture : x86_64
- CPU/Host memory size : 32 GB 
- GPU name L4 at g2-standard-8 (GCP)
- GPU memory size 24GB 
- TensorRT-LLM branch or tag (e.g., main, v0.10.0) 
- Nvidia Driver Version : 12.5
- OS - Ubuntu 22.04

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. sudo docker pull nvidia/cuda:12.5.0-devel-ubuntu22.04
2. Follow https://developer.nvidia.com/blog/turbocharging-meta-llama-3-performance-with-nvidia-tensorrt-llm-and-nvidia-triton-inference-server/
    a. docker run --rm --runtime=nvidia --gpus all --entrypoint /bin/bash -it nvidia/cuda:12.5.0-devel-ubuntu22.04
    b. apt-get update && apt-get -y install python3.10 python3-pip openmpi-bin libopenmpi-dev
    c. pip3 install tensorrt_llm==0.10.0 -U --extra-index-url https://pypi.nvidia.com/
3. Create new docker image with server/fastapi_server.py
4. Run python3 fastapi_server.py --host 0.0.0.0 --port 80 after container up based on image from 3

### Expected behavior

Run without error and docker endpoint can be used for inference

### actual behavior

Error : 
root@29b2b6327d38:/server# python3 fastapi_server.py --host 0.0.0.0 --port 80
Traceback (most recent call last):
  File "/server/fastapi_server.py", line 10, in <module>
    from tensorrt_llm.executor import GenerationExecutorWorker, GenerationResult
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/__init__.py", line 32, in <module>
    import tensorrt_llm.functional as functional
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/functional.py", line 28, in <module>
    from . import graph_rewriting as gw
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/graph_rewriting.py", line 12, in <module>
    from .network import Network
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/network.py", line 26, in <module>
    from tensorrt_llm.module import Module
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/module.py", line 17, in <module>
    from ._common import default_net
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/_common.py", line 31, in <module>
    from ._utils import str_dtype_to_trt
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/_utils.py", line 29, in <module>
    from tensorrt_llm.bindings.BuildInfo import ENABLE_MULTI_DEVICE
**ImportError: /lib/x86_64-linux-gnu/libcuda.so.1: file too short**

root@29b2b6327d38:/server# nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Wed_Apr_17_19:19:55_PDT_2024
Cuda compilation tools, release 12.5, V12.5.40
Build cuda_12.5.r12.5/compiler.34177558_0

### additional notes

I want to use TensorRT-LLM without Triton Inference Server

**Comment by nv-guomingz** [comment]
Hi @Shixiaowei02 , could u please take a look this ticket?

**Comment by hijkzzz** [comment]
Could you try cuda12.4 container and `pip install tensorrt_llm==0.11.0.dev2024061100`.

**Comment by snassimr** [comment]
Hi @hijkzzz ,

Thanks for your response.

Do you mean this stack 

1. nvidia/cuda:12.4.0-devel-ubuntu22.04
2.  pip install tensorrt_llm==0.11.0.dev2024061100
3. TensorRT-LLM/examples/apps/fastapi_server.py from latest commit 

Should work ?

**Comment by hijkzzz** [comment]
> Hi @hijkzzz ,
> 
> Thanks for your response.
> 
> Do you mean this stack
> 
> 1. nvidia/cuda:12.4.0-devel-ubuntu22.04
> 2. pip install tensorrt_llm==0.11.0.dev2024061100
> 3. TensorRT-LLM/examples/apps/fastapi_server.py from latest commit
> 
> Should work ?

I think this should be an env issue.

**Comment by snassimr** [comment]
Hi @hijkzzz ,

I am getting same error with nvidia/cuda:12.4.0-devel-ubuntu22.04 and pip install tensorrt_llm==0.11.0.dev2024061100.

If anything can be done in the case ?

What do you mean "env issue" ? Some missing piece of software on g2-standard-8 (GCP) ?

**Comment by Superjomn** [comment]
The latest `TensorRT-LLM/examples/apps/fastapi_server.py` is broken, we will fix it in next Tuesday's release in the main branch, which should be on 6-25.

**Comment by Superjomn** [comment]
> File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/_utils.py", line 29, in
from tensorrt_llm.bindings.BuildInfo import ENABLE_MULTI_DEVICE
ImportError: /lib/x86_64-linux-gnu/libcuda.so.1: file too short

This error seems quite odd, it should be the wheel and the env not compatible, please ensure you are using the right docker and wheel.

**Comment by snassimr** [comment]
Hi @Superjomn and @hijkzzz ,

I am a little bit confused how I can proceed : if I need to arrange some check with new TensorRT-LLM after 6-25 or check wheel and env compatibility ? If second : how to check the compatibility ?

**Comment by levidehaan** [comment]
So someone updated the tensorrt_llm.executor and removed GenerationExecutorWorker and replaced it with ExecutorBindingsWorker which works nothing alike.
kind of a bummer, i just got into this and it's really cool, but im trying to build a fastapi server, with some of my own stuff, but can't get it off the ground.

rolled back packages, etc.. but the new features are in the new code, also it's a bunch of examples that were broken.

i've been trying to figure it out, but i just don't have the time unfortunately, something about using the executorbindings worker and then submitting a request but i keep getting back error with MPI worldsize is off, so i've been trying to find out where that setting got moved to. 

if i figure it out, ill come back here, but for now back to llama.cpp, got a demo today, was really hoping to show off what tensorrt can do, maybe next week? eh? eh?

btw, fantastic work, loved the command line runner, can't wait to see it in action in combo with my others.

**Comment by levidehaan** [comment]
```python
import argparse
import asyncio
import json
from typing import Optional
import tensorrt_llm
from colored import cprint
from tensorrt_llm._utils import mpi_barrier, mpi_rank, mpi_world_size
from tensorrt_llm.executor import SamplingParams
from mpi4py import MPI
import uvicorn
import torch
from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse, Response, StreamingResponse
from tensorrt_llm.bindings.executor import ExecutorConfig
from tensorrt_llm.executor import ExecutorBindingsWorker, GenerationResult

tensorrt_llm.logger.set_level('info')

TP_SIZE = 2
PP_SIZE = 1  # Assuming no pipeline parallelism, update if necessary
TIMEOUT_KEEP_ALIVE = 5  # seconds
TIMEOUT_TO_PREVENT_DEADLOCK = 1  # seconds
app = FastAPI()
executor: Optional[ExecutorBindingsWorker] = None


@app.get("/stats")
async def stats() -> Response:
    assert executor is not None
    return JSONResponse(json.loads(await executor.aget_stats()))


@app.get("/health")
async def health() -> Response:
    """Health check."""
    return Response(status_code=200)


@app.post("/generate")
async def generate(request: Request) -> Response:
    if executor is None:
        return JSONResponse({"error": "Executor is not initialized"}, status_code=503)
    executor.block_subordinates()

    request_dict = await request.json()

    sampling_params = SamplingParams(max_new_tokens=request_dict.get("max_tokens", 500), temperature=request_dict.get("temperature", 0.5),
                                     top_p=request_dict.get("top_p", 0.89), top_k=request_dict.get("top_k", 50),
                                     repetition_penalty=request_dict.get("repetition_penalty", 1.05),
                                     frequency_penalty=request_dict.get("frequency_penalty", 0.2),
                                     presence_penalty=request_dict.get("presence_penalty", 0.6))
    prompt = request_dict.pop("prompt", "")

    cprint(f"Prompt: {prompt}", "green")
    output = executor.generate(prompt, sampling_params=sampling_params)
    cprint(f"Output: {output}", "green")
    cprint(f"Output DIR: {dir(output)}", "blue")

    # mpi_barrier()
    return JSONResponse({"texts": output.text})


def initialize_executor(args, mpi_rank):
    global executor
    cprint(f"Initializing executor for rank {mpi_rank}", "green")
    executor_config = ExecutorConfig(max_beam_width=args.max_beam_width)
    torch.cuda.set_device(mpi_rank)

    hf_model_dir = args.hf_model_dir
    engine_dir = args.engine_dir
    tokenizer_dir = hf_model_dir

    mpi_barrier()
    tensorrt_llm.logger.warning(f"Build finished for rank {mpi_rank}")
    executor = ExecutorBindingsWorker(engine_dir, tokenizer_dir, executor_config)
    cprint("Executor created", "green")


async def start_server(args):
    config = uvicorn.Config(app, host=args.host, port=args.port, log_level="info",
                            timeout_keep_alive=TIMEOUT_KEEP_ALIVE)
    server = uvicorn.Server(config)
    await server.serve()


async def main(args):
    mpi_rank = MPI.COMM_WORLD.Get_rank()
    world_size = MPI.COMM_WORLD.Get_size()
    cprint(f"MPI rank: {mpi_rank}, world size: {world_size}", "green")
    if world_size != TP_SIZE * PP_SIZE:
        raise ValueError("MPI world size must be equal to TP_SIZE * PP_SIZE")

    if mpi_rank < TP_SIZE:
        initialize_executor(args, mpi_rank)

    if mpi_rank == 0:
        await start_server(args)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--hf_model_dir", type=str, required=True,
                        help="Read the model data and tokenizer from this directory")
    parser.add_argument("--engine_dir", type=str, required=True, help="Directory to save and load the engine.")
    parser.add_argument("--host", type=str, default=None)
    parser.add_argument("--port", type=int, default=8000)
    parser.add_argument("--max_beam_width", type=int, default=1)
    parser.add_argument("--max_tokens", type=int, default=200)
    args = parser.parse_args()
    # set MPI world size to 2

    cprint(f"MPI COMM WORLD SIZE: {dir(MPI.COMM_WORLD)}", "green")
    cprint(f"MPI COMM WORLD SIZE: {MPI.COMM_WORLD.Get_size()}", "green")
    asyncio.run(main(args))
```
    
    
there you go, you can test it with this:

```python

import concurrent.futures
import subprocess

# Define the prompts and other parameters for the curl commands
prompts = [
    "the following is a python script that ssh into a remote linux box and pulls all the log files it can find, then moves them to a temp local dir, extracts all the logs (even the tar.gz ones), line by line, and then sorts them by time putting most recent logs at the top, and outputs it all as combined.log",
    "the following is a bash script to backup a MySQL database, compress it, and move it to an AWS S3 bucket.",
    "the following is a Python script to scrape a website for all its images and download them into a specified directory.",
    "the following is a JavaScript function to fetch data from an API and display it on a webpage.",
    "the following is a C program to read a file, count the number of words, and print the count."
]

def run_curl(prompt, index):
    command = [
        "curl", "-s", "-X", "POST", "http://0.0.0.0:8000/generate",
        "-H", "Content-Type: application/json",
        "-d", f'{{"prompt": "{prompt}", "max_tokens": 1000, "temperature": 0.5}}'
    ]
    result = subprocess.run(command, capture_output=True, text=True)
    return f"Output of command {index + 1}:\n{result.stdout}\n"

# Use ThreadPoolExecutor to run curl commands in parallel
with concurrent.futures.ThreadPoolExecutor(max_workers=5) as executor:
    futures = [executor.submit(run_curl, prompt, i) for i, prompt in enumerate(prompts)]
    for future in concurrent.futures.as_completed(futures):
        print(future.result())
```
        
run with:
```bash
 mpirun -np 2 python app/app.py  --engine_dir tensor_models/llama3_8b_tensor --hf_model_dir Meta-Llama-3-8B
```

**Comment by Superjomn** [comment]
Thanks for your patch. This `fastapi_server.py` is just an example, it is glad to see you have a workable one on your own.
 
The internal patch was merged yesterday targeting our next version (v0.11), but you can access the code in next Tuesday's release (7-2).  The major modification is replacing the usage of low-level `GenerationExecutorWorker` with `LLM` APIs, which should be more stable.

**Comment by snassimr** [comment]
Hi @levidehaan ,

I still have a problem . I think I have some problem in env . Could you share you stack ? 

Here my stack :

nvidia/cuda:12.5.0-devel-ubuntu22.04
pip install tensorrt_llm==0.10.0

Could you also share the command to start fast_api_server.py ?

Thanks

**Comment by Superjomn** [comment]
Sorry for replying late. @snassimr 

For development/test, I always install the latest main branch, which is a Tuesday release version, you can refer to [this guide for Linux installation](https://nvidia.github.io/TensorRT-LLM/installation/linux.html), and the corresponding command is `pip3 install tensorrt_llm -U --pre --extra-index-url https://pypi.nvidia.com` to install the latest main branch.

Tomorrow, the latest `fastapi_server.py` update should be available on Github, you can refer to the doc for the command to launch it.

**Comment by snassimr** [comment]
Hi @Superjomn ,

I am still getting the error . Did fastapi_server.py have been updated ?

Exploring my env here the information about my cuda : 

`nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Thu_Mar_28_02:18:24_PDT_2024
Cuda compilation tools, release 12.4, V12.4.131
Build cuda_12.4.r12.4/compiler.34097967_0`

`ls -l /lib/x86_64-linux-gnu/libcuda.so.1
lrwxrwxrwx 1 root root 20 Jul  7 21:22 /lib/x86_64-linux-gnu/libcuda.so.1 -> libcuda.so.550.54.15`

**Comment by snassimr** [comment]
Hi @Superjomn ,

I got some advance and now the error is something else . When you expect v0.11 be ready ? 

The error I get : 

root@63d049970e87:/server# python3 fastapi_server.py model  --host 0.0.0.0 --port 8000
[TensorRT-LLM] TensorRT-LLM version: 0.12.0.dev2024070200
[07/10/2024-21:36:27] [TRT-LLM] [E] Failed to parse the arguments for the LLM constructor: can't set attribute 'kv_dtype'
Traceback (most recent call last):
  File "/server/fastapi_server.py", line 112, in <module>
    entrypoint()
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/server/fastapi_server.py", line 97, in entrypoint
    llm = LLM(model_dir,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/hlapi/llm.py", line 103, in __init__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/hlapi/llm.py", line 91, in __init__
    self.args = LlmArgs.from_kwargs(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/hlapi/llm_utils.py", line 330, in from_kwargs
    ret.setup()
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/hlapi/llm_utils.py", line 369, in setup
    self._load_config_from_engine(Path(self.model_dir))
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/hlapi/llm_utils.py", line 438, in _load_config_from_engine
    engine_config = EngineConfig.from_json_file(engine_dir / "config.json")
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/builder.py", line 608, in from_json_file
    return cls(PretrainedConfig.from_dict(config['pretrained_config']),
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/modeling_utils.py", line 244, in from_dict
    return config_cls(**config)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/config.py", line 60, in __init__
    super().__init__(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/modeling_utils.py", line 223, in __init__
    raise err
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/modeling_utils.py", line 218, in __init__
    setattr(self, key, value)
AttributeError: can't set attribute 'kv_dtype'
Exception ignored in: <function LLM.__del__ at 0x7f3f1758a4d0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/hlapi/llm.py", line 335, in __del__
    self.shutdown()
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/hlapi/llm.py", line 319, in shutdown
    if self.mpi_session is not None:
AttributeError: 'LLM' object has no attribute 'mpi_session'

**Comment by nv-guomingz** [comment]
Hi @snassimr do u still have further issue or question now? If not, we'll close it soon.

**Comment by snassimr** [comment]
Hi , @nv-guomingz ,

You can close the issue . Eventually it worked.
