### ISSUE TITLE
pip install results in ImportError

### ISSUE THREAD

**Issue by coppock** [NVIDIA/TensorRT-LLM#1774]
### System Info

- TensorRT-LLM: 0.11.0.dev2024061100
- TensorRT: 10.0.1
- GPU: NVIDIA A30
- NVIDIA Driver: 555.42.02
- CUDA: 12.4
- Operating System: Ubuntu 20.04
- Python: 3.10.12

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

_pip_ install tensorrt_llm in a new virtual environment; then try to import it.

```
ubuntu$ python -m venv .venv
ubuntu$ . .venv/bin/activate
(.venv) ubuntu$ pip install tensorrt_llm -U --pre --extra-index-url https://pypi.nvidia.com
(.venv) ubuntu$ python -c 'import tensorrt_llm'
```

### Expected behavior

Importing tensorrt_llm in the virtual environment should succeed without error.

### actual behavior

Importing tensorrt_llm results in an ImportError because **libnvinfer** isn't found.

```
(.venv) ubuntu$ python -c 'import tensorrt_llm'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/pcoppock/mlos/.venv/lib/python3.10/site-packages/tensorrt_llm/__init__.py", line 32, in <module>
    import tensorrt_llm.functional as functional
  File "/data/pcoppock/mlos/.venv/lib/python3.10/site-packages/tensorrt_llm/functional.py", line 25, in <module>
    import tensorrt as trt
  File "/data/pcoppock/mlos/.venv/lib/python3.10/site-packages/tensorrt/__init__.py", line 18, in <module>
    from tensorrt_bindings import *
  File "/data/pcoppock/mlos/.venv/lib/python3.10/site-packages/tensorrt_bindings/__init__.py", line 67, in <module>
    from .tensorrt import *
ImportError: libnvinfer.so.8: cannot open shared object file: No such file or directory
(.venv) ubuntu$ 
```

### additional notes

This issue is almost certainly a downstream effect of NVIDIA/TensorRT#3936.

**Comment by coppock** [comment]
This issue went away after I removed **~/.cache/pip** and **~/.local/lib/python3.10** and reinstalled in a new virtual environment.

**Comment by sixtycat** [comment]
> This issue went away after I removed **~/.cache/pip** and **~/.local/lib/python3.10** and reinstalled in a new virtual environment.

Thank you for save my life.
