### ISSUE TITLE
Unable to convert LLaVa model to tensorrt

### ISSUE THREAD

**Issue by tanveer-sayyed** [NVIDIA/TensorRT-LLM#1776]
### System Info

- CPU architecture: x86_64
- CPU memory: 110GB
- GPU properties:
     - GPU Name: NVIDIA A100 80GB PCIe
 - Libraries:
     - tensorrt-llm==0.11.0.dev2024060400
     - CUDA Version: 12.2
     - container used: No
     - python version: 3.10.14
 - NVIDIA driver version: 535.171.04
 - OS: Ubuntu 20.04

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

 - steps followed to install tensorrt_llm:
     1. !curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg \
  && curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
    sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
    sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
    2. !apt-get update
    3. !git clone https://github.com/NVIDIA/TensorRT-LLM/
    4. !apt-get update && apt-get -y install python3.10 python3-pip openmpi-bin libopenmpi-dev
    5. !pip3 install tensorrt_llm -U --pre --extra-index-url https://pypi.nvidia.com

https://github.com/TinyLLaVA/TinyLLaVA_Factory --> we used a finetuned version of TinyLLaVA-1.5B

python3 TensorRT-LLM/examples/llama/convert_checkpoint.py     --model_dir checkpoints/tiny-llava-base-TinyLLaVA-1.5B-v1-finetune-lora-vi-al-nud-2_7-bs-merged     --dtype float16     --output_dir tmp/trt_models/tiny-llava-base-TinyLLaVA-1.5B-v1-finetune-lora-vi-al-nud-2_7-bs-merged/int8_weightonly/1-gpu      --use_weight_only     --weight_only_precision int8
No protocol specified
[TensorRT-LLM] TensorRT-LLM version: 0.11.0.dev2024060400
0.11.0.dev2024060400
Traceback (most recent call last):
  File "/home/XXXX/miniconda3/envs/conda_RT/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 971, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/home/XXXX/miniconda3/envs/conda_RT/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 673, in __getitem__
    raise KeyError(key)
KeyError: 'tiny_llava'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/XXXX/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 439, in <module>
    main()
  File "/home/XXXX/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 431, in main
    convert_and_save_hf(args)
  File "/home/XXXX/TensorRT-LLM/examples/llama/convert_checkpoint.py", line 344, in convert_and_save_hf
    hf_model = load_hf_llama(model_dir, load_model_on_cpu)
  File "/home/XXXX/miniconda3/envs/conda_RT/lib/python3.10/site-packages/tensorrt_llm/models/llama/convert.py", line 647, in load_hf_llama
    hf_config = AutoConfig.from_pretrained(model_dir, trust_remote_code=True)
  File "/home/XXXX/miniconda3/envs/conda_RT/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 973, in from_pretrained
    raise ValueError(
ValueError: The checkpoint you are trying to load has model type `tiny_llava` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.

### Expected behavior

We referred to the support matrix and as per [this](https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/multimodal#llava-and-vila) link. There should not have been any problem.

### actual behavior

- 

### additional notes

- 
```[tasklist]
### Tasks
```

**Comment by symphonylyh** [comment]
Hi @tanveer-sayyed , did you verify that the original LLaVA `llava-1.5-7b-hf` can work in your environment? We didn't look into TinyLLaVA before, and doubt that we should treat them as the same model structure

**Comment by symphonylyh** [comment]
and from the error log, it doesn't look like a TRT-LLM issue, but a TinyLLaVA issue...

It can't even load checkpoint correctly into HuggingFace. I would suggest adding tweaks to get this custom model recognized by HF first, and then try with TRT-LLM starting from there

**Comment by tanveer-sayyed** [comment]
hi @symphonylyh ... yes we tried loading the default llava-1.5-7b-hf model. The error was the same.

**Comment by symphonylyh** [comment]
in that case, it's likely the environment setup issue? the error also suggests "This could be because of an issue with the checkpoint, or because your version of Transformers is out of date."

If you follow the README https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/installation/linux.md#installing-on-linux closely, there should be no issue as we have daily testing to ensure every model works

**Comment by tanveer-sayyed** [comment]
Thanks for the response. Let me try out your suggestions; will respond then.

**Comment by nv-guomingz** [comment]
Hi @symphonylyh  do u still have question  on this issue, if not we'll close it.
