### ISSUE TITLE
ERROR: No matching distribution found for torchdata==0.7.0.dev20230828

### ISSUE THREAD

**Issue by andyluo7** [NVIDIA/TensorRT-LLM#178]
I tried to install tensorrt_llm on windows 11 using the prebuilt python wheel. An error occurred as below. How to fix it?

PS C:\Windows\system32> pip install tensorrt_llm --extra-index-url https://pypi.nvidia.com --extra-index-url https://download.pytorch.org/whl/nightly/cu121
Looking in indexes: https://pypi.org/simple, https://pypi.nvidia.com, https://download.pytorch.org/whl/nightly/cu121
Collecting tensorrt_llm
  Downloading https://pypi.nvidia.com/tensorrt-llm/tensorrt_llm-0.5.0-0-cp310-cp310-win_amd64.whl (431.5 MB)
     ---------------------------------------- 431.5/431.5 MB 13.6 MB/s eta 0:00:00
ERROR: Could not find a version that satisfies the requirement torchdata==0.7.0.dev20230828 (from tensorrt-llm) (from versions: 0.3.0a0, 0.3.0a1, 0.3.0, 0.4.0, 0.4.1, 0.5.0, 0.5.1, 0.6.0, 0.6.1, 0.7.0.dev20230830, 0.7.0.dev20230831, 0.7.0.dev20230901, 0.7.0.dev20230902, 0.7.0.dev20230903, 0.7.0.dev20230904, 0.7.0.dev20230905, 0.7.0.dev20230906, 0.7.0.dev20230907, 0.7.0.dev20230908, 0.7.0.dev20230909, 0.7.0.dev20230910, 0.7.0.dev20230911, 0.7.0.dev20230912, 0.7.0.dev20230913, 0.7.0.dev20230914, 0.7.0.dev20230915, 0.7.0.dev20230916, 0.7.0.dev20230917, 0.7.0.dev20230918, 0.7.0.dev20230919, 0.7.0.dev20230920, 0.7.0.dev20230921, 0.7.0.dev20230922, 0.7.0.dev20230923, 0.7.0.dev20230924, 0.7.0.dev20230925, 0.7.0.dev20230926, 0.7.0.dev20230927, 0.7.0.dev20230928, 0.7.0.dev20230929, 0.7.0.dev20230930, 0.7.0.dev20231001, 0.7.0.dev20231002, 0.7.0.dev20231003, 0.7.0.dev20231004, 0.7.0.dev20231005, 0.7.0.dev20231006, 0.7.0.dev20231007, 0.7.0.dev20231008, 0.7.0.dev20231009, 0.7.0.dev20231010, 0.7.0.dev20231011, 0.7.0.dev20231012, 0.7.0.dev20231013, 0.7.0.dev20231014, 0.7.0.dev20231015, 0.7.0.dev20231016, 0.7.0.dev20231017, 0.7.0.dev20231018, 0.7.0.dev20231019, 0.7.0.dev20231020, 0.7.0.dev20231021, 0.7.0.dev20231022, 0.7.0.dev20231023, 0.7.0.dev20231024, 0.7.0.dev20231025, 0.7.0.dev20231026, 0.7.0.dev20231027, 0.7.0.dev20231028, 0.7.0)
ERROR: No matching distribution found for torchdata==0.7.0.dev20230828

**Comment by jdemouth-nvidia** [comment]
Hi @andyluo7 ,

Thanks for reporting the issue. Let me discuss with our Windows experts and report back.

Thanks,
Julien

**Comment by ziwangqi** [comment]
你可以在自己下载的项目里把requirements-windows.txt这个文件里的所有20230828手动改成20230902

**Comment by juney-nvidia** [comment]
Closed since it has been fixed in both main and release branches.
