### ISSUE TITLE
single A100 runs llama-7B with batch_size>=64 input_len(max)=1024 output_len(max)=512

### ISSUE THREAD

**Issue by rhmaaa** [NVIDIA/TensorRT-LLM#1783]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 514.00 MiB. GPU 0 has a total capacity of 79.14 GiB of which 21.25 MiB is free. Process 1091649 has 79.09 GiB memory in use. Of the allocated memory 78.44 GiB is allocated by PyTorch, and 140.44 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by rhmaaa** [comment]
python3 convert_checkpoint.py --model_dir ./llama-7b \
                --output_dir ./tmp/tllm_checkpoint_1gpu_sq \
                --dtype float16 \
                --smoothquant 0.5 \
                --per_token \
                --per_channel \
                --int8_kv_cache

trtllm-build --checkpoint_dir ./tmp/tllm_checkpoint_1gpu_sq \
                  --max_batch_size $batch_size \
                  --max_input_len $max_input_len \
                  --max_output_len $output_len \
                  --output_dir ./tmp/llama/7B/trt_engines/sq/1-gpu/ \
                  --gemm_plugin float16

python3 ../summarize.py --engine_dir ./tmp/llama/7B/trt_engines/sq/1-gpu/ \
                        --batch_size $batch_size \
                        --test_trt_llm \
                        --hf_model_dir ./llama-7b \
                        --max_input_len $max_input_len \
                        --output_len $output_len \
                        --data_type fp16 \
                        --tensorrt_llm_rouge1_threshold=14

**Comment by rhmaaa** [comment]
@pathorn @Superjomn @aaronp24 @lopuhin

**Comment by nv-guomingz** [comment]
Hi @rhmaaa the title of this issue does not match the bug description. Could you please make this consistent?

**Comment by rhmaaa** [comment]
I am using a single A100 GPU to perform w8a8 quantization on the llama 7b model. When running the following command with batch_size >= 64, 
python3 convert_checkpoint.py --model_dir ./llama-7b
--output_dir ./tmp/tllm_checkpoint_1gpu_sq
--dtype float16
--smoothquant 0.5
--per_token
--per_channel
--int8_kv_cache

trtllm-build --checkpoint_dir ./tmp/tllm_checkpoint_1gpu_sq
--max_batch_size $batch_size
--max_input_len $max_input_len
--max_output_len $output_len
--output_dir ./tmp/llama/7B/trt_engines/sq/1-gpu/
--gemm_plugin float16

python3 ../summarize.py --engine_dir ./tmp/llama/7B/trt_engines/sq/1-gpu/
--batch_size $batch_size
--test_trt_llm
--hf_model_dir ./llama-7b
--max_input_len $max_input_len
--output_len $output_len
--data_type fp16
--tensorrt_llm_rouge1_threshold=14


an error occurs:
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 514.00 MiB. GPU 0 has a total capacity of 79.14 GiB of which 21.25 MiB is free. Process 1091649 has 79.09 GiB memory in use. Of the allocated memory 78.44 GiB is allocated by PyTorch, and 140.44 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation. See documentation for Memory Management (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

I roughly calculated that the memory should be sufficient, but TensorRT shows that the memory is insufficient.

**Comment by nv-guomingz** [comment]
What's your tensorrtllm version?
I tried your configuration with batch_size=64/Input_len 1024/output len512 on H100 80GB, I managed to run your cmd mentioned above.

Would u please have a try with latest trt-llm?

**Comment by rhmaaa** [comment]
I use tensorrt_llm==0.9.0.dev2024040900. Thanks, I will try it again.

**Comment by nv-guomingz** [comment]
Hi @rhmaaa , did you manage to run your case with latest code?
If so, could we close this ticket now?
