### ISSUE TITLE
How can i customize position_ids for my own model?

### ISSUE THREAD

**Issue by littletomatodonkey** [NVIDIA/TensorRT-LLM#1797]
Hi, in my model, some of the position ids are same(which are all vision tokens). For example, for an input with seq_length as 5, 1~3 ids are vision tokens. The common position ids are

```
[0, 1, 2, 3, 4]
```

But for me, i want to set it as follows. (All the vision tokens are same)

```
[0, 1, 1, 1, 2]
```

Is there any reference in TRT-LLM to finish it with gpt_attention_plugin? Thanks!

**Comment by hijkzzz** [comment]
Please refer to the CogVLM: https://github.com/NVIDIA/TensorRT-LLM/blob/2a115dae84f13daaa54727534daa837c534eceb4/tensorrt_llm/layers/attention.py#L1469

**Comment by littletomatodonkey** [comment]
> Please refer to the CogVLM:
> 
> https://github.com/NVIDIA/TensorRT-LLM/blob/2a115dae84f13daaa54727534daa837c534eceb4/tensorrt_llm/layers/attention.py#L1469

All position ids in cogvlm are fixed, and actually in TRT-LLM cogvlm realization, position_ids is a dead input tensor for gpt_attention, do you know which case can be refered for input position_ids? Thanks!

**Comment by littletomatodonkey** [comment]
i solved it by realizing ROPE myself after qkv calculation and set rope_embedding_type as None in gpt_attention_plugin.

**Comment by avianion** [comment]
@littletomatodonkey please share your code. also running into the same issue.

**Comment by littletomatodonkey** [comment]
You can refer to chatglm model build process. There are 3 steps
1. compute position embedding by yourself using input position id (attention.py)
2. in gpt_attention plugin, set rope type as none for your model type.
3. transfer position id into generation.py

I use python runtime in TRT-LLM 071 as in newer version, it's hard to hack code in the gptmanager.
