### ISSUE TITLE
Support for ChatGLM3 plz

### ISSUE THREAD

**Issue by Pevernow** [NVIDIA/TensorRT-LLM#180]
Project Homepage: https://github.com/THUDM/ChatGLM3

ChatGLM3 has become the best Chinese model among models with parameters less than 10b.
Please add support for ChatGLM3, thank you.

**Comment by juney-nvidia** [comment]
@Pevernow  thanks for the suggestion. We will add into the list of models that were requested and work with product team to prioritize it correspondingly. 

June
