### ISSUE TITLE
pip3 install tensorrt_llm-0.8.0-cp310-cp310-linux_x86_64.whl  Bad param

### ISSUE THREAD

**Issue by najsword** [NVIDIA/TensorRT-LLM#1804]
Collecting nvidia-ammo~=0.7.0 (from tensorrt-llm==0.8.0)
  Using cached nvidia-ammo-0.7.4.tar.gz (6.9 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-t8atiqhs/nvidia-ammo_8f3b1a4dfa1c43088155976cbbc6fd2f/setup.py", line 90, in <module>
          raise RuntimeError("Bad params")
      RuntimeError: Bad params
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

How to solove it?

**Comment by hijkzzz** [comment]
Installing older versions < 0.10 is not recommended
please `pip install tensorrt_llm==0.11.0.dev2024061800` or `pip install tensorrt_llm== 0.10.0`

**Comment by najsword** [comment]
> Installing older versions < 0.10 is not recommended please `pip install tensorrt_llm==0.11.0.dev2024061800` or `pip install tensorrt_llm== 0.10.0`

just for so many people has verified with v.0.8.0.  say: thats  easy to build
