### ISSUE TITLE
RuntimeError: CUDA error: invalid resource handle - int8_kv_cache & smoothquant

### ISSUE THREAD

**Issue by andyluo7** [NVIDIA/TensorRT-LLM#181]
I tried to run bloom 560M examples with int8 kv cache or smoothquant. It passed the calibration but have the following error during saving weights. fp16 and int8 weight only worked fine. 
BTW, I ran this on WSL2 with RTX4090. All the installation went well. 
Can you let me know how to fix it? 

root@ryzen-ai-release:/code/tensorrt_llm/examples/bloom# python3 hf_bloom_convert.py -i bloom/560M -o ./c-model/bloom/int8_kv_cache/560M --calibrate-kv-cache -t float16

=============== Arguments ===============
out_dir: ./c-model/bloom/int8_kv_cache/560M
in_file: bloom/560M
tensor_parallelism: 1
processes: 4
calibrate_kv_cache: True
smoothquant: None
model: bloom
storage_type: float16
dataset_cache_dir: None
load_model_on_cpu: False
convert_model_on_cpu: False
========================================
The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
Some weights of BloomForCausalLM were not initialized from the model checkpoint at bloom/560M and are newly initialized: ['lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Downloading builder script: 4.95kB [00:00, 19.3MB/s]
Downloading metadata: 2.65kB [00:00, 11.4MB/s]
Downloading and preparing dataset lambada/plain_text (download: 319.03 MiB, generated: 936.19 MiB, post-processed: Unknown size, total: 1.23 GiB) to /root/.cache/huggingface/datasets/lambada/plain_text/1.1.0/e32d76a7236c9ebb30099bc73d677c3acf32ddffb411836fe9ffc091ad3f3bec...
Downloading data: 100%|█████████████████████████████████████████████████████████████| 335M/335M [00:23<00:00, 14.1MB/s]
Dataset lambada downloaded and prepared to /root/.cache/huggingface/datasets/lambada/plain_text/1.1.0/e32d76a7236c9ebb30099bc73d677c3acf32ddffb411836fe9ffc091ad3f3bec. Subsequent calls will reuse this data.
calibrating model: 100%|█████████████████████████████████████████████████████████████| 512/512 [00:14<00:00, 36.19it/s]
saving weights:  44%|████████████████████████████                                    | 126/288 [00:05<00:07, 22.97it/s]Process SpawnPoolWorker-3:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/reductions.py", line 130, in rebuild_cuda_tensor
    storage = storage_cls._new_shared_cuda(
  File "/usr/local/lib/python3.10/dist-packages/torch/storage.py", line 1085, in _new_shared_cuda
    return torch.UntypedStorage._new_shared_cuda(*args, **kwargs)
RuntimeError: CUDA error: invalid resource handle
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

saving weights:  50%|████████████████████████████████                                | 144/288 [00:05<00:05, 25.61it/s]Process SpawnPoolWorker-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/reductions.py", line 130, in rebuild_cuda_tensor
    storage = storage_cls._new_shared_cuda(
  File "/usr/local/lib/python3.10/dist-packages/torch/storage.py", line 1085, in _new_shared_cuda
    return torch.UntypedStorage._new_shared_cuda(*args, **kwargs)
RuntimeError: CUDA error: invalid resource handle
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

root@ryzen-ai-release:/code/tensorrt_llm/examples/bloom# nvidia-smi
Sun Oct 29 04:34:05 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.103                Driver Version: 537.13       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090 ...    On  | 00000000:01:00.0 Off |                  N/A |
| N/A   47C    P8               2W / 100W |     17MiB / 16376MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A        25      G   /Xwayland                                 N/A      |
+---------------------------------------------------------------------------------------+

**Comment by juney-nvidia** [comment]
@andyluo7  so you are running TensorRT-LLM on Windows? If so, we haven't done WSL based validation yet. You can refer [this](https://github.com/NVIDIA/TensorRT-LLM/tree/release/0.5.0/windows) doc for TensorRT-LLM Windows support.

June

**Comment by andyluo7** [comment]
@juney-nvidia , i am facing the issue #178 and #179 on windows. So I tried to see if it works on WSL.
