### ISSUE TITLE
Is it "INT8 or FP8" with "--use_weight_only --weight_only_precision int8 --qformat fp8"

### ISSUE THREAD

**Issue by aiiAtelier** [NVIDIA/TensorRT-LLM#1810]
### System Info

GPU - A10

### Who can help?

@Tracin 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Hi there, 

With "--use_weight_only --weight_only_precision int8 --qformat fp8", will the quantization be in INT8 or FP8? 

### Expected behavior

FP8 dtype when printing out weights.

### actual behavior

The weights are in torch.int8.

### additional notes

N/A

**Comment by nv-guomingz** [comment]
May I know your full cmd with above parameters？
