### ISSUE TITLE
internlm2-chat-20b model convert_checkpoint.py does not have “--int8_kv_cache” option

### ISSUE THREAD

**Issue by 256256mjw** [NVIDIA/TensorRT-LLM#1817]
Why is there no --int8_kv_cache option when I want to use convert_checkpoint.py to build int8_kv_cache internlm2-chat-20b model?
  convert_checkpoint.py is in /TensorRT-LLM/examples/internlm2/convert_checkpoint.py

**Comment by nv-guomingz** [comment]
internlm2 was implemented by https://github.com/NVIDIA/TensorRT-LLM/pull/1392.
The original implementation didn't enable such feature like internlm.

**Comment by nv-guomingz** [comment]
Hi @256256mjw  do u still have further issue or question now? If not, we'll close it soon.
