### ISSUE TITLE
TensorRT-LLM Build

### ISSUE THREAD

**Issue by jiangix-paper** [NVIDIA/TensorRT-LLM#184]
I want to install tensorrt-llm without container. So I run the following command:
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/62198809/c5e34737-04df-4bd9-9181-c275e6133271)
And it works. Then I run the following command to build the tensorrt_llm:
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/62198809/b1592d7b-d471-46e4-8e98-bc8ae97d6497)
My trt_root is ./Tensorrt-9.1.0.4 which is extracted from https://developer.nvidia.com/downloads/compute/machine-learning/tensorrt/secure/9.1.0/tars/tensorrt-9.1.0.4.linux.x86_64-gnu.cuda-11.8.tar.gz
But I have the error:
Error: could not load cache
Traceback (most recent call last):
  File "/data/TensorRT-LLM/TensorRT-LLM/./scripts/build_wheel.py", line 248, in <module>
    main(**vars(args))
  File "/data/TensorRT-LLM/TensorRT-LLM/./scripts/build_wheel.py", line 152, in main
    build_run(
  File "/data/anaconda3/envs/tensorrt-llm/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cmake --build . --config Release --parallel 109 --target tensorrt_llm tensorrt_llm_static nvinfer_plugin_tensorrt_llm th_common ' returned non-zero exit status 1.

**Comment by AndreSlavescu** [comment]
I ran into the same issue when building, and I believe it's because there is an issue with cmake and how it references the cmake lists. 
The only way I got the project to run was by building the docker image. Followed the steps here:
https://nvidia.github.io/TensorRT-LLM/installation.html

**Comment by juney-nvidia** [comment]
It is suggested to build TensorRT-LLM by following the installation guide mentioned in the documentation since the docker image can help ensure the consistency of the environment. 

June
