### ISSUE TITLE
Running LoRA inference with inflight batching is much slower than running base model.

### ISSUE THREAD

**Issue by limertang** [NVIDIA/TensorRT-LLM#1852]
### System Info

GPU Name:  NVIDIA A800
TensorRT-LLM: 0.10.0
Nvidia Driver: 535.129.03
OS: Ubuntu 22.04
triton-inference-server backend：tensorrtllm_backend

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Buid and inference model by [ https://github.com/triton-inference-server/tensorrtllm_backend/tree/main/inflight_batcher_llm  section：](https://gitlab.msxf.com/ai-infrastructure/tensorrtllm_backend/tree/branch-b92bdd7/inflight_batcher_llm#running-lora-inference-with-inflight-batching)
below is my step：

**- convert ckt:**
`python convert_checkpoint.py \`
`    --model_dir /work/model/Qwen1.5-7B-Chat \`
`    --output_dir ./ckt_out_1gpu \`
`    --dtype float16`

**- build engine:**
>  trtllm-build --checkpoint_dir ./ckt_out_1gpu \
>         --output_dir ./trt_engine_lora_triton/fp16/1-gpu \
>         --gemm_plugin float16 \
>         --lora_plugin float16 \
>         --max_batch_size 4 \
>         --max_input_len 512 \
>         --max_output_len 512 \
>         --max_lora_rank 8 \
>         --gpt_attention_plugin float16 \
>         --paged_kv_cache enable \
>         --remove_input_padding enable \
>         --use_paged_context_fmha enable \
>         --use_custom_all_reduce disable \
>         --lora_target_modules attn_q attn_k attn_v attn_dense mlp_h_to_4h mlp_gate mlp_4h_to_h

**- convert lora weight:**
`python3 /work/ensorRT-LLM/examples/hf_lora_convert.py -i /work/model/Qwen1.5-7B-Chat-750Mb-lora/ -o Qwen1.5-7B-Chat-750Mb-lora-weight --storage-type float16`
**- inference by tritonserver with lora**
**- test latency of per token**

### Expected behavior

**Latency of per token with LoRA inference should be close to the latency of running base model.**

### actual behavior

But in fact,  Running LoRA inference is **2x slower** than running base model.

### additional notes

I tested the following 3 cases and **I found the performance is related to the build parameter  “--lora_target_modules”**. It will become slower as long as you set this parameter , even though running without lora.  However，inference with lora will more slower.

**1、Build engine without parameter “--lora_target_modules”,  inference without lora,  latency  of per token is 12ms** 

>     trtllm-build --checkpoint_dir ./ckt_out_1gpu \
>     --output_dir ./trt_engine_lora_triton/fp16/1-gpu \
>     --gemm_plugin float16 \
>     --lora_plugin float16 \
>     --max_batch_size 4 \
>     --max_input_len 512 \
>     --max_output_len 512 \
>     --max_lora_rank 256 \
>     --gpt_attention_plugin float16 \
>     --paged_kv_cache enable \
>     --remove_input_padding enable \
>     --use_paged_context_fmha enable \
>     --use_custom_all_reduce disable 

 **2、Build engine with parameter “--lora_target_modules”, inference without lora,  latency  of per token is 22ms**

>     trtllm-build --checkpoint_dir ./ckt_out_1gpu \
>     --output_dir ./trt_engine_lora_triton/fp16/1-gpu \
>     --gemm_plugin float16 \
>     --lora_plugin float16 \
>     --max_batch_size 4 \
>     --max_input_len 512 \
>     --max_output_len 512 \
>     --max_lora_rank 256 \
>     --gpt_attention_plugin float16 \
>     --paged_kv_cache enable \
>     --remove_input_padding enable \
>     --use_paged_context_fmha enable \
>     --use_custom_all_reduce disable  \
>     --lora_target_modules attn_q attn_k attn_v attn_dense mlp_h_to_4h mlp_gate mlp_4h_to_h

3、**Build engine with parameter “--lora_target_modules” as step2,  and inference with lora weight, latency  of per token is 25.6ms**

**Comment by chrjxj** [comment]
checked with developer. 

**A)** 
- with v0.10, I ran a simple test and comparsion, seems LoRA version used 50% more time per inference, than std version 
- it is expected to fix /improve in v0.11

**B)** 
- actually v0.10 doesn't support  Qwen1.5/2 Lora, although no warming msg during the workflow
-  expected to support Qwen1.5/2 Lora by trtllm v0.11
