### ISSUE TITLE
Errors in code for importing llama model from Huggingface

### ISSUE THREAD

**Issue by ivodopyanov** [NVIDIA/TensorRT-LLM#1855]
### System Info

- CPU architecture x86_64
- Host memory size 32Gb
- GPU Nvidia RTX 2060
- GPU memory size 12 Gb
- TensorRT-LLM v0.10.0

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. 
https://github.com/NVIDIA/TensorRT-LLM/blob/v0.10.0/tensorrt_llm/models/llama/convert.py#L1411 - act_range has default value {}
https://github.com/NVIDIA/TensorRT-LLM/blob/v0.10.0/tensorrt_llm/models/llama/convert.py#L631 - act_range has default value []; this function is called from the previous one.
https://github.com/NVIDIA/TensorRT-LLM/blob/v0.10.0/tensorrt_llm/models/llama/convert.py#L749 - no None checks for values of act_range, so it yield Exception if used with default value

2.
https://github.com/NVIDIA/TensorRT-LLM/blob/v0.10.0/tensorrt_llm/models/llama/weight.py#L312 - the only place where layer is being initialized is here https://github.com/NVIDIA/TensorRT-LLM/blob/v0.10.0/tensorrt_llm/models/llama/weight.py#L202 ... and it is initialized with None.

### Expected behavior

No exceptions

### actual behavior

Code raises an exception

### additional notes

-

**Comment by nv-guomingz** [comment]
Sorry, could u plz share us more details on reproducing issue?
B.T.W, please try main branch instead of previously tag.

**Comment by ivodopyanov** [comment]
Code to reproduce:
> from tensorrt_llm.mapping import Mapping
> from tensorrt_llm.models import LLaMAForCausalLM
> from tensorrt_llm.quantization import QuantAlgo
> from tensorrt_llm.models.llama.convert import create_config_from_hugging_face, load_from_hf_checkpoint
> from tensorrt_llm.models.modeling_utils import QuantConfig, PretrainedConfig
> 
> MODEL_DIR = "path to my locally saved model"
> 
> mapping = Mapping()
> quantization = QuantConfig(quant_algo=QuantAlgo.W4A16, kv_cache_quant_algo=QuantAlgo.INT8)
> config = create_config_from_hugging_face(MODEL_DIR, "float16", mapping, quantization)
> pretrained_config = PretrainedConfig.from_dict(config)
> llama = LLaMAForCausalLM.from_config(pretrained_config)
> weights = load_from_hf_checkpoint(model_dir=MODEL_DIR, mapping=mapping, config=pretrained_config)

It yields another error I've forgot to mention.:

> Traceback (most recent call last):
>   File "C:\Users\1\Projects\ragllm\rag_llm\parsers\llama_to_tensorrt2.py", line 15, in <module>
>     weights = load_from_hf_checkpoint(model_dir=MODEL_DIR,
>   File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorrt_llm\models\llama\weight.py", line 298, in load_from_hf_checkpoint
>     split_v.transpose(), plugin_weight_only_quant_type)
> TypeError: transpose() received an invalid combination of arguments - got (), but expected one of:
>  * (int dim0, int dim1)
>  * (name dim0, name dim1)

After I've fixed this one by copying load_from_hf_checkpoint function and editing split_v.transpose() to split_v.t(), it began to fail on the second point from my original list.

**Comment by nv-guomingz** [comment]
It looks like u wanna to simplify the process of generating trtllm checkpoint, right?

**Comment by ivodopyanov** [comment]
Yes, kinda. I was trying to convert Huggingface Llama model to TRT format and was cutting all parts unnecessary for me to make code more simple.

**Comment by nv-guomingz** [comment]
It's not our recommend way to use TensorRT-LLM and we don't verify such script yet.
You may have a try with our high-level API example https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/high-level-api as reference.

**Comment by ivodopyanov** [comment]
> from tensorrt_llm.quantization import QuantAlgo
> from tensorrt_llm import LLM, ModelConfig
> from tensorrt_llm.models.modeling_utils import QuantConfig
> 
> MODEL_DIR = "path to local Llama folder"
> 
> quant_config = QuantConfig(quant_algo=QuantAlgo.W4A16)
> model_config = ModelConfig(model_dir=MODEL_DIR,
>                            quant_config=quant_config)
> llm = LLM(config=model_config)

Fails with 

> [TensorRT-LLM] TensorRT-LLM version: 0.10.0
> Loading Model: [1/3]	Load HF model to memory
> Traceback (most recent call last):
>   File "C:\Users\1\Projects\ragllm\rag_llm\parsers\llama_to_tensorrt3.py", line 10, in <module>
>     llm = LLM(config=model_config)
>   File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorrt_llm\hlapi\llm.py", line 505, in __init__
>     self._build_model()
>   File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorrt_llm\hlapi\llm.py", line 694, in _build_model
>     runtime_context = model_loader()
>   File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorrt_llm\hlapi\llm.py", line 942, in __call__
>     step()
>   File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorrt_llm\hlapi\llm.py", line 1062, in _load_model_from_hf
>     model2struct[model_arch].quantize(
>   File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorrt_llm\models\llama\model.py", line 414, in quantize
>     convert.quantize(
>   File "C:\Users\1\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorrt_llm\models\llama\convert.py", line 1361, in quantize
>     with open(os.path.join(output_dir, 'config.json'), 'w') as f:
> FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\1\\AppData\\Local\\Temp\\tmppb317z5yllm-workspace/quantized-checkpoint\\config.json'
