### ISSUE TITLE
Llama 3 70B XQA Support

### ISSUE THREAD

**Issue by avianion** [NVIDIA/TensorRT-LLM#1858]
Can someone confirm whether or not Llama 3 70B or LLama 3 8B supports XQA?

"Another optimization for MQA/GQA in generation phase called XQA optimization. It is still experimental feature and support limited configurations. LLAMA2 70B is one model that it supports."

The docs state this, but it doesn't mention llama 3 

If not, when will you support this?

**Comment by nv-guomingz** [comment]
Yes, LLAMA3 supports XQA optimization.
