### ISSUE TITLE
Out-of-memory error when building TensorRT-LLM in the container

### ISSUE THREAD

**Issue by gedatsu217** [NVIDIA/TensorRT-LLM#186]
I'm trying to build TensorRT-LLM in the container with `python3 ./scripts/build_wheel.py --trt_root /usr/local/tensorrt`, according to [installation.md](https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/docs/source/installation.md), but it failed. Looks get killed on the way of building. 

![Screenshot from 2023-10-29 15-21-50](https://github.com/NVIDIA/TensorRT-LLM/assets/46126918/14613198-e7bc-4b45-8592-af0065f6de67)

Then, I checked `dmesg` and found that was probably because of OOM. 
![Screenshot from 2023-10-29 15-19-22](https://github.com/NVIDIA/TensorRT-LLM/assets/46126918/68285000-3116-46b5-bbc8-359a992395ba)

How can I solve it?
Driver Version: 535.113.01, CUDA Version: 12.2, GPU: Tesla T4
The memory size is 32GB, so I guess it's not too low.

**Comment by jdemouth-nvidia** [comment]
Hi @gedatsu217 ,

Can you try to launch the container with more memory (`--ulimit stack=67108864` is what we use in the Makefile, you might need more)? Or, can you reduce the number of CPU jobs using 

```
python3 ./scripts/build_wheel.py --trt_root /usr/local/tensorrt -j <N>
```

where you could try with `N = 4`, `N = 8` or `N = 16`.

Thanks,
Julien

**Comment by gedatsu217** [comment]
Thank you!! I successfully built it using N=16 and without a memory limit.

**Comment by jdemouth-nvidia** [comment]
Awesome! I’m closing the bug. Thanks.
