### ISSUE TITLE
change **kwargs to **default_kwargs to enable trust remote code, fast, etc..

### ISSUE THREAD

**Issue by levidehaan** [NVIDIA/TensorRT-LLM#1863]
https://github.com/NVIDIA/TensorRT-LLM/blob/9691e12bce7ae1c126c435a049eb516eb119486c/tensorrt_llm/hlapi/tokenizer.py#L63

**Comment by nv-guomingz** [comment]
@Superjomn Would u please take a look this question?

**Comment by Superjomn** [comment]
Good suggestion, thanks.

We will support `enable_trust_remote_code` in the future when we broaden the model coverage from Llama to other models. Currently, you can also pass an external tokenizer into the `LLM` instance instead.

**Comment by levidehaan** [comment]
Roger that, 
i was pointing out that youre not using the extra kwargs, i enabled them and stopped getting errors loading models that needed some of those settings. Might be safe to enable,, or maybe set a flag to enable?
