### ISSUE TITLE
Run inference / do a forward pass on certain segments of LLM only during inference

### ISSUE THREAD

**Issue by avianion** [NVIDIA/TensorRT-LLM#1866]
Many research papers add an additional lm_head or decoder_layer to an LLM.

What is the process in the C++ or pytorch runtime to selectively run a forward pass on inference only on a single layer or head of the model, as is common for example in Medusa decoding?

**Comment by QiJune** [comment]
Hi @avianion , could you please give some reference codes(in PyTorch) to show the forward pass? Thanks
