### ISSUE TITLE
batch inference is different with single

### ISSUE THREAD

**Issue by 1096125073** [NVIDIA/TensorRT-LLM#1879]
### System Info

x85-64
4 A10
0.9.0

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

A private model of type llama2, when using the same input batch inference, such as batch_size=4, yields four different answers. （topk=0,topp=0,run.py）

### Expected behavior

four answers should be the same

### actual behavior

yields four different answers.

### additional notes

![image](https://github.com/NVIDIA/TensorRT-LLM/assets/30305505/01eef2f2-a3c4-4b18-be99-6eb532afcd55)

**Comment by 1096125073** [comment]
i have disable custom_all_reduce when build engine

**Comment by QiJune** [comment]
Hi @1096125073 , since different batch sizes may lead to different kernels. So, the results can be different. This is a known issue.

**Comment by 1096125073** [comment]
> Hi @1096125073 , since different batch sizes may lead to different kernels. So, the results can be different. This is a known issue.

Thank you for your answer! I'm sorry, I think it might be because I didn't express myself clearly. When I infer that the batch is 4, the input to the batch is the same, but the four outputs I get are different.

**Comment by QiJune** [comment]
@1096125073 Yes, I get your point:  repeat the same input prompt 4 times, and make it a batch, but the outputs are different from batch size 1.  Unfortunately, it's a known issue. 

BTW, do you observe the similar phenomenon in PyTorch?

**Comment by 1096125073** [comment]
b

> @1096125073 Yes, I get your point: repeat the same input prompt 4 times, and make it a batch, but the outputs are different from batch size 1. Unfortunately, it's a known issue.
> 
> BTW, do you observe the similar phenomenon in PyTorch?
Sorry, I said these four outputs are different from each other, just like the picture above.

**Comment by 1096125073** [comment]
> @1096125073 Yes, I get your point: repeat the same input prompt 4 times, and make it a batch, but the outputs are different from batch size 1. Unfortunately, it's a known issue.
> 
> BTW, do you observe the similar phenomenon in PyTorch?

Sorry, I said these four outputs are different from each other, just like the picture above.

**Comment by QiJune** [comment]
Hi @1096125073 , I tried the llama2 model:

```bash
python convert_checkpoint.py --model_dir=/llm-models/llama-models-v2/llama-v2-7b-hf/ --output_dir=./ckpt --dtype bfloat16

trtllm-build --checkpoint_dir=./ckpt --output_dir=./engine --gemm_plugin bfloat16 --max_output_len=256 --max_batch_size=4

python ../run.py --engine_dir=./engine --max_output_len=10 --tokenizer_dir /llm-models/llama-models-v2/llama-v2-7b-hf/  --input_text 'How are you' 'How are you' 'How are you' 'How are you'
```

Here is the result:

```
Input [Text 0]: "<s> How are you"
Output [Text 0 Beam 0]: "doing? I hope you are doing well. I"
Input [Text 1]: "<s> How are you"
Output [Text 1 Beam 0]: "doing? I hope you are doing well. I"
Input [Text 2]: "<s> How are you"
Output [Text 2 Beam 0]: "doing? I hope you are doing well. I"
Input [Text 3]: "<s> How are you"
Output [Text 3 Beam 0]: "doing? I hope you are doing well. I"
```

**Comment by QiJune** [comment]
@1096125073 Could you please try the main branch? It seems you are using 0.9.0 version.

**Comment by yuxianq** [comment]
@1096125073 Do you use multiple GPUs? If you use multi-GPU, you can use NCCL_ALGO=Tree to ensure stable reduce order. NCCL usually select Ring algo, which has unstable reduce order, which causes different results in the same batch. If you use single GPU, then it should be other issue.

**Comment by 0xd8b** [comment]
@QiJune I encountered the same issue with the T5 model (float16). The inference results vary slightly with different batch sizes during extensive sample testing. Is this a normal phenomenon? I saw a similar issue in one of the issues on this page: https://github.com/dmlc/gluon-nlp/issues/1344.

**Comment by 1096125073** [comment]
> @1096125073 Do you use multiple GPUs? If you use multi-GPU, you can use NCCL_ALGO=Tree to ensure stable reduce order. NCCL usually select Ring algo, which has unstable reduce order, which causes different results in the same batch. If you use single GPU, then it should be other issue.

Yes，this is the answer i want，thanks

**Comment by chiendb97** [comment]
@QiJune 
I'm experiencing issues even when using single GPU. If the discrepancies in results are due to varying kernel choices, is there a way to sacrifice some performance in exchange for more stability?

**Comment by DZADSL72-00558** [comment]
+1 here
