### ISSUE TITLE
rank0.python: Failed to modify UD QP to INIT on mlx5_4: Operation not permitted

### ISSUE THREAD

**Issue by Luosuu** [NVIDIA/TensorRT-LLM#1888]
### System Info

- x86_64 CPU
- NVIDIA A100-SXM4-80GB x1

### Who can help?

@byshiue @ju

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I was running the [Quick Start Tutorial](https://nvidia.github.io/TensorRT-LLM/quick-start-guide.html)

I successfully converted the model into TensorRT-LLM checkpoint format. But when compilation:
```
→  trtllm-build --checkpoint_dir llama-2-7b-ckpt \
>     --gemm_plugin float16 \
>     --output_dir ./llama-2-7b-engine
udc-an26-1:rank0.python: Failed to modify UD QP to INIT on mlx5_4: Operation not permitted
udc-an26-1:rank0.python: Failed to modify UD QP to INIT on mlx5_4: Operation not permitted
```

I am running in an interactive SLURM session and udc-an26-1 is the internal node name.

### Expected behavior

It should compile the model with `trtllm-build` tool.

### actual behavior

The program stopped with output:
```
udc-an26-1:rank0.python: Failed to modify UD QP to INIT on mlx5_4: Operation not permitted
udc-an26-1:rank0.python: Failed to modify UD QP to INIT on mlx5_4: Operation not permitted
```

### additional notes

When running more than 1 GPUs, the converting process would run into the same error.

```
python3 convert_checkpoint.py --model_dir meta-llama/Llama-2-7b-chat-hf --output_dir llama-2-7b-ckpt
udc-an26-1:rank0.python3: Failed to modify UD QP to INIT on mlx5_4: Operation not permitted
udc-an26-1:rank0.python3: Failed to modify UD QP to INIT on mlx5_4: Operation not permitted
```

**Comment by QiJune** [comment]
It seems that it's related with openucx, I find a simiar issue: https://github.com/openucx/ucx/issues/9468

TensorRT-LLM depends on mpi4py.  @Luosuu could you please try to run this simple script on your cluster?

```python
from mpi4py import MPI

comm = MPI.COMM_WORLD
rank = comm.Get_rank()

if rank == 0:
    data = {'key1' : [7, 2.72, 2+3j],
            'key2' : ( 'abc', 'xyz')}
else:
    data = None
data = comm.bcast(data, root=0)
```

**Comment by Luosuu** [comment]
@QiJune Thanks for reply!

Yes I run into the same error when running the provided script.

```bash
→ python ucx_test.py 
udc-an26-1:rank0.python: Failed to modify UD QP to INIT on mlx5_4: Operation not permitted
udc-an26-1:rank0.python: Failed to modify UD QP to INIT on mlx5_4: Operation not permitted
```

Do you have any suggestion for workaround? Thank you very much.

**Comment by QiJune** [comment]
Then, it seems that this error is not releated with TRT-LLM core library. The mpi4py can not be executed in your cluster. I don't have good idea yet.

**Comment by Luosuu** [comment]
Yes, you are right. I am closing this issue.
