### ISSUE TITLE
0xC0000409 error during initializing LLM object with TRT checkpoint

### ISSUE THREAD

**Issue by ivodopyanov** [NVIDIA/TensorRT-LLM#1893]
### System Info

CPU architecture: x86_64
Host memory size: 32 Gb
GPU: Nvidia GeForce RTX 2060
GPU memory size: 12 Gb
TensorRT-LLM tag: 0.10.0
CUDA version: 12.5
Python version: 3.10

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

I execute following code:

> from tensorrt_llm import LLM, ModelConfig
> from tensorrt_llm.models.modeling_utils import QuantConfig
> 
> MODEL_DIR = "path to TRT checkpoint"
> 
> quant_config = QuantConfig()
> model_config = ModelConfig(model_dir=MODEL_DIR,
>                            quant_config=quant_config)
> llm = LLM(config=model_config)

### Expected behavior

Model initializes successfully

### actual behavior

Error:

> C:\Users\1\AppData\Local\Programs\Python\Python310\python.exe C:/Users/1/Projects/ragllm/rag_llm/parsers/llama_to_tensorrt3.py 
> [TensorRT-LLM] TensorRT-LLM version: 0.10.0
> Loading Model: [1/3]	Load TRT checkpoints to memory
> Time: 0.461s
> Loading Model: [2/3]	Build TRT-LLM engine
> 
> Process finished with exit code -1073740791 (0xC0000409)

### additional notes

-

**Comment by hello-11** [comment]
@ivodopyanov Could you use the latest version of TrtLLM?
