### ISSUE TITLE
[Quesetion]Recommendation and Future Maintenance of gptSession for Inference in C++ Runtime: Flexibility Concerns with Executor

### ISSUE THREAD

**Issue by Yoh-Z** [NVIDIA/TensorRT-LLM#1894]
Is it recommended to use GPTSession for inference in the C++ runtime? Will this part continue to be maintained and exposed to users in the future? Although using the executor is convenient, its flexibility is too limited. For example, methods like split-wise cannot be further developed for testing purposes.

**Comment by QiJune** [comment]
@Shixiaowei02 could you please take a look? Thanks

**Comment by MartinMarciniszyn** [comment]
`GptSession` is deprecated and will not be further maintained. Please submit feature requests for Executor API in case of any missing flexibility.
