### ISSUE TITLE
Is any plan to support Dual Chunk Attention (DCA)?

### ISSUE THREAD

**Issue by gaoteng-git** [NVIDIA/TensorRT-LLM#1898]
[DCA ](https://arxiv.org/html/2402.17463v1) is an effective method to run long input context inference. 
Does TensorRT-LLM plan to support this feature?

**Comment by nanmi** [comment]
> [DCA ](https://arxiv.org/html/2402.17463v1) is an effective method to run long input context inference. Does TensorRT-LLM plan to support this feature?

I have implemented a version of DCA based on the TRT plugin, but I haven't tested it rigorously yet. Once it passes the test, I will open source it.
