### ISSUE TITLE
Asking future plan on build from source part.

### ISSUE THREAD

**Issue by Yupjun** [NVIDIA/TensorRT-LLM#190]
Currently, instruction of building TensorRT-LLM from source is based on docker build.
Do you have any plan to building TensorRT-LLM on local linux? like Ubuntu 20.04 LTS.

**Comment by jdemouth-nvidia** [comment]
Hi @Yupjun ,

For the moment, we strongly recommend Docker to make sure the environment matches ours. If you build from source on your local system, we will do our best to help you (as you can see in many of the GitHub issues where we are trying to help users who are not following our recommended way to build TensorRT-LLM ;)) but we do not plan to make “building outside a Docker container” one of our recommended solutions in a near future. 

We plan to offer a pre-built Docker container in a near future to simplify the life of users who don’t want to build from sources. But that’s not what you’re asking for. 

Thanks,
Julien
