### ISSUE TITLE
Sparsity fp8 Llama-3-8b on RTX4090 has no speed improvement against dense one

### ISSUE THREAD

**Issue by lishicheng1996** [NVIDIA/TensorRT-LLM#1913]
Hi!
I tried Sparsity fp8 Llama-3-8b on RTX4090, but doesn't get performance improvement. I checked the trt-llm build log, which shows that depite there are layers eligible to use sparse tactics, they are not chosen.
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/43111799/810f420a-65ee-42a0-869a-aac392c75c97)

I see sparsity example on H100 in the benchmark. I'm wodering why it doesn't work on 4090. And may I ask is there 4090 support plan in roadmap?

Thanks!

**Comment by QiJune** [comment]
@Tracin Could you please have a look? Thanks

**Comment by Tracin** [comment]
@lishicheng1996 Basiclly, this is due to less efficient of sparse kernel compared with dense one, so they are not chosen. Can you verify it on H100? I do not see any plan about FP8 sparsity on 4090.

**Comment by lishicheng1996** [comment]
> @lishicheng1996 Basiclly, this is due to less efficient of sparse kernel compared with dense one, so they are not chosen. Can you verify it on H100? I do not see any plan about FP8 sparsity on 4090.

Thank you!
