### ISSUE TITLE
[model request]  PaliGemma support

### ISSUE THREAD

**Issue by kitterive** [NVIDIA/TensorRT-LLM#1931]
有计划支持谷歌的paligemma多模态模型吗?

**Comment by AdamzNV** [comment]
It seems that PaliGemma's download popularity on Hugging Face is much lower than Llava's.

**Comment by nzarif** [comment]
Hi,
I wanna also up this request and ask if you have plans for adding PaliGemma support to TensorRT-LLM? If yes, can you please provide an estimate on when approximately it will be available?

Thanks!

**Comment by AdamzNV** [comment]
As more and more new models enter the market, we have prepared comprehensive instructions for TRT-LLM developers on adapting to new models of interest. We encourage our community developers to expand the range of supported models, fostering an open ecosystem with rapid iterations.

Please try following these [instructions ](https://github.com/NVIDIA/TensorRT-LLM/tree/main/docs/source/architecture)and let us know if you encounter any issues during the adaptation process. We greatly appreciate your dedication.
