### ISSUE TITLE
Cannot install tensorrt_llm

### ISSUE THREAD

**Issue by Dawn-2-Winter** [NVIDIA/TensorRT-LLM#1933]
### System Info

<img width="567" alt="image" src="https://github.com/NVIDIA/TensorRT-LLM/assets/91579901/59fe7e11-83db-425d-a5f9-96ab24135b2d">

I use image nvidia/cuda   12.1.0-devel-ubuntu22.04 from docker pull

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

# Obtain and start the basic docker image environment.
docker run --rm --runtime=nvidia --gpus all --volume ${PWD}:/TensorRT-LLM --entrypoint /bin/bash -it --workdir /TensorRT-LLM nvidia/cuda:12.1.0-devel-ubuntu22.04

# Install dependencies, TensorRT-LLM requires Python 3.10
apt-get update && apt-get -y install python3.10 python3-pip openmpi-bin libopenmpi-dev

# Install the stable version (corresponding to the cloned branch) of TensorRT-LLM.
pip3 install tensorrt_llm==0.8.0 -U --extra-index-url https://pypi.nvidia.com

### Expected behavior

install success

### actual behavior

like image

### additional notes

no

**Comment by geraldstanje** [comment]
did you try: nvidia/cuda:12.4.0-devel-ubuntu22.04 or docker pull nvidia/cuda:12.5.0-devel-ubuntu22.04 ?

**Comment by byshiue** [comment]
I have verified that these commands work

```bash
docker run --rm --runtime=nvidia --gpus all --shm-size 25g \
  --entrypoint /bin/bash -it nvidia/cuda:12.4.0-devel-ubuntu22.04

sudo apt-get update && sudo apt-get -y install python3.10 python3-pip openmpi-bin libopenmpi-dev git git-lfs

pip3 install tensorrt-llm==0.11.0.dev2024062500 -U --pre --extra-index-url https://pypi.nvidia.com
```

Could you take a try?
