### ISSUE TITLE
[Model Request] InternVL2.0 support

### ISSUE THREAD

**Issue by BasicCoder** [NVIDIA/TensorRT-LLM#1934]
InternVL2.0 and InternVL1.5 have the same architecture, maybe the download statistics needs to be reconsidered.
Similar issue: #1567

**Comment by LatentLinker** [comment]
mark

**Comment by Hukongtao** [comment]
mark

**Comment by Hukongtao** [comment]
mark

**Comment by bymechul** [comment]
Yes, this model is very strong in the visual part. but there is no one to support it.

**Comment by AmazDeng** [comment]
> Yes, this model is very strong in the visual part. but there is no one to support it.

+1

**Comment by zhaocc1106** [comment]
Can try https://github.com/NetEase-Media/grps_trtllm. Support InternVL2 by trtllm, and support deploying a service.

**Comment by scuizhibin** [comment]
> Can try https://github.com/NetEase-Media/grps_trtllm. Support InternVL2 by trtllm, and support deploying a service.

牛皮 6666

**Comment by scuizhibin** [comment]
> Can try https://github.com/NetEase-Media/grps_trtllm. Support InternVL2 by trtllm, and support deploying a service.

能使用吗？这个模型？
