### ISSUE TITLE
On 2*V100, the performance is worse than FT

### ISSUE THREAD

**Issue by sleepwalker2017** [NVIDIA/TensorRT-LLM#194]
Here is the token/sec I tested on 2* V100. 

![image](https://github.com/NVIDIA/TensorRT-LLM/assets/26128514/a66b177f-a77c-42e1-a9e0-fcd083dda354)

As batch gets larger, the gap is larger.

**Comment by jdemouth-nvidia** [comment]
Hi @sleepwalker2017 ,

Can you give us the command-lines that you used to produce those results, please? 

Thanks,
Julien

**Comment by sleepwalker2017** [comment]
> Hi @sleepwalker2017 ,
> 
> Can you give us the command-lines that you used to produce those results, please?
> 
> Thanks, Julien

I'm using vicuna 13B, the convert command is:

```shell
python build.py --model_dir $1 \
                --dtype float16 \
                --use_gpt_attention_plugin float16 \
                --use_gemm_plugin float16 \
                --output_dir ./tmp/llama/13B/trt_engines/fp16/2-gpu/ \
                --max_batch_size 24 \
                --world_size 2 \
                --tp_size 2
```

The run command is: 
```shell
mpirun -n 2 --allow-run-as-root python3 run.py --max_output_len=96 \
               --tokenizer_dir /data/models/llama-7b-hf \
               --engine_dir=./tmp/llama/13B/trt_engines/fp16/2-gpu/
```

The code I'm using is modified based on `7295ce25aa157548afa6b2d2cea635c33d0cce5c` :

```shell
diff --git a/examples/llama/run.py b/examples/llama/run.py
index d42a8a2..1b496c1 100644
--- a/examples/llama/run.py
+++ b/examples/llama/run.py
@@ -241,8 +241,14 @@ def generate(
     input_ids, input_lengths = parse_input(input_text, input_file, tokenizer,
                                            EOS_TOKEN,
                                            model_config.remove_input_padding)
+    t = np.loadtxt('len_32.csv', delimiter=',', dtype=np.int32)
+    input_ids = torch.Tensor(t).int().cuda()

+    if len(input_ids.shape) == 1:
+        input_ids = input_ids.reshape(1, -1)
+    input_lengths = torch.Tensor(input_ids.shape[0] * [input_ids.shape[-1]]).int().cuda()
     max_input_length = torch.max(input_lengths).item()
+
decoder.setup(input_lengths.size(0), max_input_length, max_output_len,
                   num_beams)

@@ -251,6 +257,25 @@ def generate(
                                     sampling_config,
                                     streaming=streaming)
     torch.cuda.synchronize()
+
+    ite = 10
+    import time
+
+    st = time.time()
+    for _ in range(ite):
+        output_gen_ids = decoder.decode(input_ids,
+                                        input_lengths,
+                                        sampling_config,
+                                        streaming=streaming)
+    torch.cuda.synchronize()
+
+    duration = time.time() - st
+    print(input_ids.shape, output_gen_ids.shape, duration)
+    output_len = output_gen_ids.shape[-1] - input_lengths[0].item()
+    batch = input_lengths.shape[0]
+
+    tps = batch * output_len * ite / duration
+
     if streaming:
         for output_ids in throttle_generator(output_gen_ids,
                                              streaming_interval):
@@ -262,6 +287,7 @@ def generate(
         if runtime_rank == 0:
             print_output(output_ids, input_lengths, max_output_len, tokenizer,
                          output_csv, output_npy)
+    print("tps is", tps)


 if __name__ == '__main__':
```

The data is multiple pieces of this file

```
1,24062,1747,278,11996,732,29899,29992,22053,457,10811,29176,584,3014,310,4908,15411,1919,478,29711,1919,2627,29871,29906,29896,1919,29871,29906,29900,29900,29929,869
1,24062,1747,278,11996,732,29899,29992,22053,457,10811,29176,584,3014,310,4908,15411,1919,478,29711,1919,2627,29871,29906,29896,1919,29871,29906,29900,29900,29929,869
1,24062,1747,278,11996,732,29899,29992,22053,457,10811,29176,584,3014,310,4908,15411,1919,478,29711,1919,2627,29871,29906,29896,1919,29871,29906,29900,29900,29929,869
1,24062,1747,278,11996,732,29899,29992,22053,457,10811,29176,584,3014,310,4908,15411,1919,478,29711,1919,2627,29871,29906,29896,1919,29871,29906,29900,29900,29929,869
```

**Comment by jdemouth-nvidia** [comment]
Thanks a lot @sleepwalker2017. For best performance, we recommend the C++ runtime. Have you tried with that runtime?

**Comment by sleepwalker2017** [comment]
> Thanks a lot @sleepwalker2017. For best performance, we recommend the C++ runtime. Have you tried with that runtime?

no  I haven't. I'll try that.

**Comment by sleepwalker2017** [comment]
> Thanks a lot @sleepwalker2017. For best performance, we recommend the C++ runtime. Have you tried with that runtime?

Hi, I see the files in cpp/tests/runtime folder, but I can't find an example for llama.

Do I have to write llama structures myself? I mean, to load weights, to run inference layer by layer, to do sampling using topk or top p step by step?

**Comment by duladissa** [comment]
> > Thanks a lot @sleepwalker2017. For best performance, we recommend the C++ runtime. Have you tried with that runtime?
> 
> no I haven't. I'll try that.

@sleepwalker2017  Were you able to try the C++ runtime? Can you share if there is any documentation to be referred?

**Comment by duladissa** [comment]
@jdemouth-nvidia @sleepwalker2017 I tried to build the C++ Runtime using below steps but i'm getting an error while loading tensorrt_llm model

Repo : https://github.com/triton-inference-server/tensorrtllm_backend/tree/release/0.5.0
Branch : release/0.5.0

Step 1: Update [Dockerfile.trt_llm_backend](https://github.com/triton-inference-server/tensorrtllm_backend/blob/release/0.5.0/dockerfile/Dockerfile.trt_llm_backend#L43) to use --cpp_only 

`RUN cd tensorrt_llm && python3 scripts/build_wheel.py --clean --cpp_only --trt_root="${TRT_ROOT}" && cd ..`

Step 2: Build the docker image of triton_trt_llm

`DOCKER_BUILDKIT=1 docker build -t triton_trt_llm -f dockerfile/Dockerfile.trt_llm_backend .`

Step 3: Launch Triton server

`docker run --rm -it --shm-size=2g -p8000:8000 -p8001:8001 -p8002:8002 --gpus=8 -v $(pwd)/all_models:/app/all_models triton_trt_llm bash`

`python3 scripts/launch_triton_server.py --world_size=8 --model_repo=/app/all_models/inflight_batcher_llm `


While loading the tensorrt_llm model i'm receiving below error

`E1115 13:49:37.267016 120 model_repository_manager.cc:563] Invalid argument: ensemble 'ensemble' depends on 'tensorrt_llm' which has no loaded version. Model 'tensorrt_llm' loading failed with error: version 2 is at UNAVAILABLE state: Not found: unable to load shared library: /opt/tritonserver/backends/tensorrtllm/libtriton_tensorrtllm.so: undefined symbol: _ZNK12tensorrt_llm7runtime13GptJsonConfig14engineFilenameERKNS0_11WorldConfigERKSs;`

**Comment by sleepwalker2017** [comment]
> @jdemouth-nvidia @sleepwalker2017 I tried to build the C++ Runtime using below steps but i'm getting an error while loading tensorrt_llm model
> 
> Repo : https://github.com/triton-inference-server/tensorrtllm_backend/tree/release/0.5.0 Branch : release/0.5.0
> 
> Step 1: Update [Dockerfile.trt_llm_backend](https://github.com/triton-inference-server/tensorrtllm_backend/blob/release/0.5.0/dockerfile/Dockerfile.trt_llm_backend#L43) to use --cpp_only
> 
> `RUN cd tensorrt_llm && python3 scripts/build_wheel.py --clean --cpp_only --trt_root="${TRT_ROOT}" && cd ..`
> 
> Step 2: Build the docker image of triton_trt_llm
> 
> `DOCKER_BUILDKIT=1 docker build -t triton_trt_llm -f dockerfile/Dockerfile.trt_llm_backend .`
> 
> Step 3: Launch Triton server
> 
> `docker run --rm -it --shm-size=2g -p8000:8000 -p8001:8001 -p8002:8002 --gpus=8 -v $(pwd)/all_models:/app/all_models triton_trt_llm bash`
> 
> `python3 scripts/launch_triton_server.py --world_size=8 --model_repo=/app/all_models/inflight_batcher_llm `
> 
> While loading the tensorrt_llm model i'm receiving below error
> 
> `E1115 13:49:37.267016 120 model_repository_manager.cc:563] Invalid argument: ensemble 'ensemble' depends on 'tensorrt_llm' which has no loaded version. Model 'tensorrt_llm' loading failed with error: version 2 is at UNAVAILABLE state: Not found: unable to load shared library: /opt/tritonserver/backends/tensorrtllm/libtriton_tensorrtllm.so: undefined symbol: _ZNK12tensorrt_llm7runtime13GptJsonConfig14engineFilenameERKNS0_11WorldConfigERKSs;`

It's a known issue, I think they are fixing it. You need to remove the `--cpp_only ` to build trt-llm.

**Comment by byshiue** [comment]
Close this bug because the issue is inactivated. Feel free to ask here if you still have question/issue, we will reopen the issue.
