### ISSUE TITLE
[new] discord channel for tensorrt

### ISSUE THREAD

**Issue by geraldstanje** [NVIDIA/TensorRT-LLM#1943]
### System Info

Hi,

I noticed there is no slack, discord or irc channel for tensorrt - which could offload some future tickets by discussing things in the channel - so I created one.
I hope its ok to advertise the discord channel to discuss nvidia tensorrt, tensorrt-llm, triton inference server here: https://discord.gg/hrARsZjJ

Thanks,
Gerald

### Who can help?

@juney-nvidia
@kaiyux - could you help to pin this somewhere so people can see it better? this might also help nvidia team to offload some tickets...

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

-

### Expected behavior

-

### actual behavior

-

### additional notes

-

**Comment by anubhav-agrawal-mu-sigma** [comment]
server invite seems to have been expired

**Comment by imihic** [comment]
@geraldstanje please recreate server invite, thanks

**Comment by geraldstanje** [comment]
@anubhav-agrawal-mu-sigma @imihic here: https://discord.gg/xUEggt5xqn
