### ISSUE TITLE
How to quantize customed models, such as LVM?

### ISSUE THREAD

**Issue by XA23i** [NVIDIA/TensorRT-LLM#1945]
Accodring to https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/quantization,  Can I define my model and calibration process and then simply use modelopt.torch.quantization.quantize() ?

**Comment by QiJune** [comment]
@Tracin could you please have a look? Thanks

**Comment by Tracin** [comment]
I am not sure. Can we do that? @RalphMao

**Comment by XA23i** [comment]
By the way, what else can we do to quantize pytorch models besides modelopt.torch.quantization.quantize() function?

**Comment by RalphMao** [comment]
Yes we can quantize VLM, the only difference is that you need to prepare your calibration dataset to include both visual tokens and language tokens.

**Comment by RalphMao** [comment]
According to our experience, calibration VLM with language token only also gives decent results
