### ISSUE TITLE
[Question] accelerating groupwise weightOnlyGemm on v100 using double buffering?

### ISSUE THREAD

**Issue by foricee** [NVIDIA/TensorRT-LLM#1951]
Since TRT-LLM doesn't support groupwise weightOnlyGemm on V100, due to some PTX commands requiring SM>=75 or higher, such as ```cp.async``` ```ldmatrix```, my question is, is it possible to accelerate weightOnlyGemm on V100 using double buffering by myself?

**Comment by QiJune** [comment]
@Tracin  could you please have a look? Thanks

**Comment by Tracin** [comment]
I am not sure about that, maybe you can find something here https://github.com/NVIDIA/TensorRT-LLM/blob/main/cpp/tensorrt_llm/kernels/weightOnlyBatchedGemv/kernel.h
