### ISSUE TITLE
Whisper example crashes with English-only models

### ISSUE THREAD

**Issue by mrdrprofuroboros** [NVIDIA/TensorRT-LLM#1960]
### System Info

just a simple python bug, system agnostic

### Who can help?

@byshiue 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

follow the official whisper tensorrt guide, but use small.en model

### Expected behavior

inference work

### actual behavior

Traceback (most recent call last):
  File "/home/jovyan/whisper/run.py", line 363, in <module>
    model = WhisperTRTLLM(args.engine_dir, args.debug, args.assets_dir)
  File "/home/jovyan/whisper/run.py", line 236, in __init__
    tokenizer_name == "gpt2"
UnboundLocalError: local variable 'tokenizer_name' referenced before assignment

### additional notes

Here's the fix https://github.com/NVIDIA/TensorRT-LLM/pull/1958

**Comment by yuekaizhang** [comment]
> ### System Info
> just a simple python bug, system agnostic
> 
> ### Who can help?
> @byshiue
> 
> ### Information
> * [x]  The official example scripts
> * [ ]  My own modified scripts
> 
> ### Tasks
> * [x]  An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
> * [ ]  My own task or dataset (give details below)
> 
> ### Reproduction
> follow the official whisper tensorrt guide, but use small.en model
> 
> ### Expected behavior
> inference work
> 
> ### actual behavior
> Traceback (most recent call last): File "/home/jovyan/whisper/run.py", line 363, in model = WhisperTRTLLM(args.engine_dir, args.debug, args.assets_dir) File "/home/jovyan/whisper/run.py", line 236, in **init** tokenizer_name == "gpt2" UnboundLocalError: local variable 'tokenizer_name' referenced before assignment
> 
> ### additional notes
> Here's the fix #1958

@mrdrprofuroboros  Would you mind changing the '==' to '=' please?
We have fixed the typo and would update to github later.

**Comment by mrdrprofuroboros** [comment]
What do you mean? I’ve created a PR doing exactly this
