### ISSUE TITLE
how to use tensorrt_llm backend in tritonserver

### ISSUE THREAD

**Issue by AndreWanga** [NVIDIA/TensorRT-LLM#1986]
### System Info

None

### Who can help?

@juney-nvidia

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Please tell me how to use tensorrt_llm in tritonserver, do you have docs for this issue? FYI

### Expected behavior

None

### actual behavior

None

### additional notes

None

**Comment by QiJune** [comment]
Hi @AndreWanga , please refer to this doc: https://github.com/triton-inference-server/tensorrtllm_backend/blob/main/docs/llama.md
