### ISSUE TITLE
[Question] Does FMHA in context phase support custom alibi slopes?

### ISSUE THREAD

**Issue by xTayEx** [NVIDIA/TensorRT-LLM#1997]
Hi TensorRT-LLM teams! Thank you for this amazing project! I wonder whether we can use custom alibi slopes with FMHA kernels in context phase. I find that the `linear_bias_slopes` variable is only used when `mEnableContextFMHA` is false.
https://github.com/NVIDIA/TensorRT-LLM/blob/5ddb6bf218ed16a2dcf0058f20c59a247e180fd2/cpp/tensorrt_llm/plugins/gptAttentionCommon/gptAttentionCommon.cpp#L1164

I also find that there is a class named `AlibiParams`, but seems that there is not alibi slopes related variables in this class.
https://github.com/NVIDIA/TensorRT-LLM/blob/5ddb6bf218ed16a2dcf0058f20c59a247e180fd2/cpp/tensorrt_llm/kernels/contextFusedMultiHeadAttention/fused_multihead_attention_common.h#L46-L82
Can we use custom alibi slopes by this class? Or it's unsupported to use custom alibi slopes for FMHA kernels?

**Comment by djns99** [comment]
Hi @xTayEx, currently the context FMHA implementation computes the alibi slopes directly instead of loading from memory, so it does not support custom slopes.

**Comment by xTayEx** [comment]
> Hi @xTayEx, currently the context FMHA implementation computes the alibi slopes directly instead of loading from memory, so it does not support custom slopes.

Thanks!
