### ISSUE TITLE
make -C docker release_run LOCAL_USER=1 is failing

### ISSUE THREAD

**Issue by jayakommuru** [NVIDIA/TensorRT-LLM#1998]
I have cloned the tensorRT-LLM repo and have tried `make -C docker release_run LOCAL_USER=1` 

but getting the following error: 
`pull access denied for tensorrt_llm/release, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

Full logs: 
```make: Entering directory '/home/jaya_kommuru/TensorRT-LLM/docker'
docker build --progress auto --build-arg BASE_IMAGE_WITH_TAG=tensorrt_llm/release:latest --build-arg USER_ID=0 --build-arg USER_NAME=root --build-arg GROUP_ID=0 --build-arg GROUP_NAME=root --file Dockerfile.user --tag tensorrt_llm/release:latest-root ..
Sending build context to Docker daemon  1.567GB
Step 1/9 : ARG BASE_IMAGE_WITH_TAG
Step 2/9 : FROM ${BASE_IMAGE_WITH_TAG} as base
pull access denied for tensorrt_llm/release, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
make: *** [Makefile:118: release_run] Error 1
make: Leaving directory '/home/jaya_kommuru/TensorRT-LLM/docker'
```

**Comment by QiJune** [comment]
Hi @jayakommuru , you need to generate the docker image `tensorrt_llm/release:latest` first, please try:

```
make -C docker release_build LOCAL_USER=1
make -C docker release_run LOCAL_USER=1
```

**Comment by jayakommuru** [comment]
@QiJune Ok, now `make -C docker release_build LOCAL_USER=1` is throwing the following error. Any idea? 
``` => ERROR [wheel 10/10] RUN --mount=type=cache,target=/root/.cache/pip --mount=type=cache,target=/root/.cache/ccache     python3 scripts/build_wheel.py --clean --trt_root /usr/local/tensorrt --python_binding  0.5s
------
 > [wheel 10/10] RUN --mount=type=cache,target=/root/.cache/pip --mount=type=cache,target=/root/.cache/ccache     python3 scripts/build_wheel.py --clean --trt_root /usr/local/tensorrt --python_bindings --benchmarks:
#33 0.474 fatal: not a git repository (or any of the parent directories): .git
#33 0.475 Traceback (most recent call last):
#33 0.475   File "/src/tensorrt_llm/scripts/build_wheel.py", line 387, in <module>
#33 0.475     main(**vars(args))
#33 0.475   File "/src/tensorrt_llm/scripts/build_wheel.py", line 84, in main
#33 0.476     build_run('git submodule update --init --recursive')
#33 0.476   File "/usr/lib/python3.10/subprocess.py", line 526, in run
#33 0.477     raise CalledProcessError(retcode, process.args,
#33 0.477 subprocess.CalledProcessError: Command 'git submodule update --init --recursive' returned non-zero exit status 128.
------
executor failed running [/bin/bash -c python3 scripts/build_wheel.py ${BUILD_WHEEL_ARGS}]: exit code: 1
make: *** [Makefile:64: release_build] Error 1
```

**Comment by jayakommuru** [comment]
This is resolved, I had to initialise and update the submodules before building. Thanks

**Comment by SouthWest7** [comment]
> [@QiJune](https://github.com/QiJune) Ok, now `make -C docker release_build LOCAL_USER=1` is throwing the following error. Any idea?
> 
> ```
> ------
>  > [wheel 10/10] RUN --mount=type=cache,target=/root/.cache/pip --mount=type=cache,target=/root/.cache/ccache     python3 scripts/build_wheel.py --clean --trt_root /usr/local/tensorrt --python_bindings --benchmarks:
> #33 0.474 fatal: not a git repository (or any of the parent directories): .git
> #33 0.475 Traceback (most recent call last):
> #33 0.475   File "/src/tensorrt_llm/scripts/build_wheel.py", line 387, in <module>
> #33 0.475     main(**vars(args))
> #33 0.475   File "/src/tensorrt_llm/scripts/build_wheel.py", line 84, in main
> #33 0.476     build_run('git submodule update --init --recursive')
> #33 0.476   File "/usr/lib/python3.10/subprocess.py", line 526, in run
> #33 0.477     raise CalledProcessError(retcode, process.args,
> #33 0.477 subprocess.CalledProcessError: Command 'git submodule update --init --recursive' returned non-zero exit status 128.
> ------
> executor failed running [/bin/bash -c python3 scripts/build_wheel.py ${BUILD_WHEEL_ARGS}]: exit code: 1
> make: *** [Makefile:64: release_build] Error 1
> ```

Hi, how can I solve this problem? @jayakommuru

**Comment by Superjomn** [comment]
> #33 0.477 subprocess.CalledProcessError: Command 'git submodule update --init --recursive' returned non-zero exit status 128.

The git command failed, it seems to be a network issue when running the docker script.

**Comment by SouthWest7** [comment]
The submodule cmd did't work, so I clone the submodules manually.
