### ISSUE TITLE
4bit GPTQ Llama2 yields "Assertion failed: No valid SQ GEMM tactic" on Volta

### ISSUE THREAD

**Issue by jfolz** [NVIDIA/TensorRT-LLM#200]
I'm following the llama example to build 4bit quantized Llama2 engines for V100.
If I'm reading the precision chart in the README correctly, this is a supported config.
My environment is a Docker image (enroot actually, but that should not really be relevant) built from TensorRT-LLM release/0.5.0 branch, commit d0b56df.

The quantization seems to work as intended. Below is the command I used. `$size` is either 7B or 13B. I haven't bothered with 70B yet.
I run this step in a separate container, as installing GPTQ-for-LLaMa overwrites packages already present in the TensorRT-LLM image.
```
python llama.py $OUTDIR/hf-$size/ c4 --wbits 4 --true-sequential --groupsize 128 --save_safetensors $OUTDIR/gptq-4bit-${size}.safetensors
```

I then use the following command to build the engines. It should be identical with the command given in the llama example, except I removed the `--enable_context_fmha` option, as the operation is not supported on Volta.
```
python build.py --model_dir $OUTDIR/hf-$size/ \
                --quant_ckpt_path $OUTDIR/gptq-4bit-${size}.safetensors \
                --output_dir $OUTDIR/tensorrt-${size}-4bit-${num_gpus}V100 \
                --dtype float16 \
                --remove_input_padding \
                --use_gpt_attention_plugin float16 \
                --use_gemm_plugin float16 \
                --use_weight_only \
                --weight_only_precision int4_gptq \
                --per_group \
                --world_size $num_gpus \
                --tp_size $num_gpus
```

I've tried `$num_gpus` 1, 2, and 4 so far, but it makes no difference, as I always get numerous of these warnings:
```
[TensorRT-LLM][WARNING] Cannot profile configuration 1 (for m=1, n=768, k=4096). Skipped
[TensorRT-LLM][WARNING] Cannot profile configuration 0 (for m=1, n=768, k=4096). Skipped
[TensorRT-LLM][WARNING] Cannot profile configuration 0 (for m=2, n=768, k=4096). Skipped
[TensorRT-LLM][WARNING] Have not found any valid GEMM config for shape (m=1, n=768, k=4096). Will try to use default or fail at runtime
```

And indeed, when I try to run these engines, an assertion is triggered:
```
[TensorRT-LLM][ERROR] Assertion failed: No valid SQ GEMM tactic (/src/tensorrt_llm/cpp/tensorrt_llm/plugins/weightOnlyGroupwiseQuantMatmulPlugin/weightOnlyGroupwiseQuantMatmulPlugin.cpp:329)
```

The same setup with `--enable_context_fmha` reinstated works on RTXA6000 and A100.

**Comment by byshiue** [comment]
Hi, @jfolz . GPTQ is not supported on V100.

**Comment by jfolz** [comment]
In that case, it would be good to have that documented somewhere. Since the README just says int4 is supported on Volta, I assumed there was no distinction to be made between the different int4 modes.

**Comment by BaiStone2017** [comment]
> Hi, @jfolz . GPTQ is not supported on V100.

AWQ, SmoothQuant and INT8_KV_cahce are also not supported on V100. It will occur same error as GPTQ.
