### ISSUE TITLE
Question: Can Context FMHA be used to implement Transformer in a vision encoder for multimodal models?

### ISSUE THREAD

**Issue by lmcl90** [NVIDIA/TensorRT-LLM#2001]
I see that the multi-model models in the example all use TensorRT directly to deploy vision encoders, why not use TensorRT-LLM? Are there known issues or challenges associated with integrating Context FMHA into visual encoders?

**Comment by QiJune** [comment]
Yes, you can try to use TensorRT-LLM for the vision encoders. We have [Bert example](https://github.com/NVIDIA/TensorRT-LLM/tree/main/tensorrt_llm/models/bert),  [DiT example](https://github.com/NVIDIA/TensorRT-LLM/tree/main/tensorrt_llm/models/dit), and community also contribute a [SDXL model](https://github.com/NVIDIA/TensorRT-LLM/pull/1514). I think it's not hard to develop a ViT model.

**Comment by lmcl90** [comment]
@QiJune Thanks for your replay. I will have a try.
