### ISSUE TITLE
[Usage]: Does Prefix Caching currently support offloading to the CPU?

### ISSUE THREAD

**Issue by wjj19950828** [NVIDIA/TensorRT-LLM#2003]
### Usage

Does Prefix Caching currently support offloading to the CPU?

 If not, is there a plan to support it? Thanks～

**Comment by Funatiq** [comment]
Yes, it does. Please see [here](https://github.com/NVIDIA/TensorRT-LLM/blob/0d5ffae9a79d70e45c7e03e52756476dd6645560/docs/source/kv_cache_reuse.md#offloading-to-host-memory).
