### ISSUE TITLE
INFLIGHT_FUSED is no longer available in executor?

### ISSUE THREAD

**Issue by sxyu** [NVIDIA/TensorRT-LLM#2006]
In 0.9.0, it was possible to use `TrtGptModelType::InflightFusedBatching` instead of `TrtGptModelType::InflightBatching` which seemed a bit faster. Now I upgraded to 0.11.0 and the executor bindings seems to go through another wrapping layer which does not expose the fused version:
https://github.com/NVIDIA/TensorRT-LLM/blob/5ddb6bf218ed16a2dcf0058f20c59a247e180fd2/cpp/tensorrt_llm/pybind/executor/bindings.cpp#L55

original:
https://github.com/NVIDIA/TensorRT-LLM/blob/5ddb6bf218ed16a2dcf0058f20c59a247e180fd2/cpp/tensorrt_llm/pybind/bindings.cpp#L365

I tried to add it there directly as 2 but it appears to not recognize the option.

**Comment by Funatiq** [comment]
The option to switch between `InflightFusedBatching` and `InflightBatching` is not exposed for the executor API. Instead it will automatically select `InflightFusedBatching` for all models that support it. Some models don't support fused batching and fall back to `InflightBatching`.
