### ISSUE TITLE
[Feature request] Support for LLama3.1

### ISSUE THREAD

**Issue by nguyenhoangthuan99** [NVIDIA/TensorRT-LLM#2015]
Llama 3.1 has been released, and it includes a small change in the model's forward part that makes the current version of TensorRT-LLM unable to run it.

I'm a member of [homebrew/jan](https://github.com/janhq). Currently, we support the Llama 3 model, and now I'm planning to update the model execution part of TensorRT-LLM to support Llama 3.1 for integration into our project at  [cortex.tensorrt-llm](https://github.com/janhq/cortex.tensorrt-llm).

**Comment by QiJune** [comment]
Hi @nguyenhoangthuan99 , llama 3.1 is supported. Please check the latest news: https://github.com/NVIDIA/TensorRT-LLM?tab=readme-ov-file#latest-news
