### ISSUE TITLE
GenerationSession crashes if `stream` keyword argument is not `None`

### ISSUE THREAD

**Issue by cody-moveworks** [NVIDIA/TensorRT-LLM#202]
https://github.com/NVIDIA/TensorRT-LLM/blob/11e14500f35dd781b535ba009c906f55ecfee3b5/tensorrt_llm/runtime/generation.py#L311-L313

If the `stream` keyword argument is specified when creating the `GenerationSession`, `self.stream` will not be initialized and the code will crash on L313.

**Comment by jdemouth-nvidia** [comment]
Can you share a way to reproduce the issue, please?

**Comment by cody-moveworks** [comment]
@jdemouth-nvidia Just create a GenerationSession and pass anything that is not `None` as the value for `stream` keyword argument. It will result in error`AttributeError: 'GenerationSession' object has no attribute 'stream'`

**Comment by juney-nvidia** [comment]
@cody-moveworks  we already have the fix for this bug internally, and it will get pushed to the main branch later.

June
