### ISSUE TITLE
[Feature request] Mistral Large 2 support

### ISSUE THREAD

**Issue by aikitoria** [NVIDIA/TensorRT-LLM#2024]
Would be great to support this model in the sample scripts:

https://mistral.ai/news/mistral-large-2407/

https://huggingface.co/mistralai/Mistral-Large-Instruct-2407

**Comment by ShadowTeamCN** [comment]
I have successfully converted and built the Mistral Large 2 model using TensorRT-LLM. However, unfortunately, the model's output quality has significantly decreased.

**Comment by aikitoria** [comment]
This seems to already work with the llama sample script. Not sure if it works 100% correctly though

**Comment by AdamzNV** [comment]
As more and more new models enter the market, we have prepared comprehensive instructions for TRT-LLM developers on adapting to new models of interest. We encourage our community developers to expand the range of supported models, fostering an open ecosystem with rapid iterations.

Please try following these [instructions ](https://github.com/NVIDIA/TensorRT-LLM/tree/main/docs/source/architecture)and let us know if you encounter any issues during the adaptation process. We greatly appreciate your dedication.
