### ISSUE TITLE
H20 infer Qwen14B fp8 results in a divide-by-zero error.

### ISSUE THREAD

**Issue by menggeliu1205** [NVIDIA/TensorRT-LLM#2031]
**System Info**
Device: H20
Driver: 550.90.07

**python env:**
nvidia-cublas-cu12 12.1.3.1
nvidia-cuda-nvrtc-cu12 12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12 8.9.2.26
tensorrt 10.0.1
tensorrt-cu12-bindings 10.0.1
tensorrt-cu12-libs 10.0.1
tensorrt-llm 0.12.0.dev2024071600

**model**
Qwen14B: https://huggingface.co/Qwen/Qwen-14B
**expected behavior**
Expect to print performance and eval data normally.
**actual behavior**
<img width="1511" alt="截屏2024-07-26 15 01 33" src="https://github.com/user-attachments/assets/210dc33d-4731-4792-9288-9ee0ff0ec65e">
<img width="1509" alt="截屏2024-07-26 15 01 42" src="https://github.com/user-attachments/assets/f466a22d-a7cc-4c11-a6a4-efcb14861af4">

**Comment by qiaoxj07** [comment]
pip install nvidia-cublas-cu12==12.3.4.1
