### ISSUE TITLE
tag0.11: 

### ISSUE THREAD

**Issue by ZhangChuann** [NVIDIA/TensorRT-LLM#2037]
### System Info

- system: 
Sat Jul 27 14:44:50 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA L20                     On  |   00000000:23:00.0 Off |                    0 |
| N/A   30C    P8             35W /  350W |       0MiB /  46068MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA L20                     On  |   00000000:33:00.0 Off |                    0 |
| N/A   28C    P8             33W /  350W |       0MiB /  46068MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

make -C docker release_build CUDA_ARCHS="89-real;90-real"

### Expected behavior

build finish and gen docker image

### actual behavior

1086.1 error in tensorrt_llm setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
1086.1 
1086.1 ERROR Backend subprocess exited when trying to invoke build_wheel
1086.1 Traceback (most recent call last):
1086.1   File "/src/tensorrt_llm/scripts/build_wheel.py", line 387, in <module>
1086.1     main(**vars(args))
1086.1   File "/src/tensorrt_llm/scripts/build_wheel.py", line 300, in main
1086.1     build_run(
1086.1   File "/usr/lib/python3.10/subprocess.py", line 526, in run
1086.1     raise CalledProcessError(retcode, process.args,
1086.1 subprocess.CalledProcessError: Command '"/usr/bin/python3" -m build /src/tensorrt_llm --skip-dependency-check --no-isolation --wheel --outdir "/src/tensorrt_llm/build"' returned non-zero exit status 1.
------
Dockerfile.multi:72
--------------------
  71 |     ARG BUILD_WHEEL_ARGS="--clean --trt_root /usr/local/tensorrt --python_bindings --benchmarks"
  72 | >>> RUN --mount=type=cache,target=/root/.cache/pip --mount=type=cache,target=/root/.cache/ccache \
  73 | >>>     python3 scripts/build_wheel.py ${BUILD_WHEEL_ARGS}
  74 |     
--------------------
ERROR: failed to solve: process "/bin/bash -c python3 scripts/build_wheel.py ${BUILD_WHEEL_ARGS}" did not complete successfully: exit code: 1
make: *** [Makefile:64: release_build] Error 1

### additional notes

no

**Comment by ZhangChuann** [comment]
I have found the reason of my error. I add three line to the "requirements.txt" and "requirements-dev.txt".
--index-url https://mirrors.tencent.com/pypi/simple/
--extra-index-url https://pypi.ngc.nvidia.com/
--extra-index-url https://pypi.org/simple

Because the "https://pypi.ngc.nvidia.com" and the "https://pypi.org/simple" are too slow to access, I suggest if there is a convenient configuration to configure the download source？
Thank you very much.

**Comment by Shixiaowei02** [comment]
@ZhangChuann Hi, if you have an alternative mirror address, I suggest you to modify the relevant fields directly in the code. Thanks!
