### ISSUE TITLE
Alternative way to specify max capacity for paged KV cache models

### ISSUE THREAD

**Issue by yunfeng-scale** [NVIDIA/TensorRT-LLM#204]
It seem `engine.device_memory_size` is decided the same way between paged/non-paged KV cache models, using some combinations of batch size, max sequence length etc. This is less ideal given the high variance of input sizes. Is it possible to specify this in some alternative ways like max # of blocks?

**Comment by byshiue** [comment]
Hi, @yunfeng-scale . Thank you for the report. The workspace of TensorRT engine is pre-allocated during initialization, so it is hard to apply the technique of page kv cache to these buffer for TensorRT. We know memory consumption is a very important topic and we are investigating more way to optimize the memory usage. 

Close this bug. Feel free to open the bug if needed.
