### ISSUE TITLE
Tensorrt llm support in Jetson Orion Nano

### ISSUE THREAD

**Issue by krishnarajk** [NVIDIA/TensorRT-LLM#2041]
Hi,

The nvidia jetson orin nano supports jetpack 6 and a´has cuda 12.
I would like to know if it supports running TensorRT-LLM on the NVIDIA Jetson Orin Nano Developer Kit.

Thankk you

**Comment by ReturnToFirst** [comment]
You can try TensorRT-LLM with [dev-sm87-trt101](https://github.com/NVIDIA/TensorRT-LLM/tree/dev-sm87-trt101) branch.
Before you build TensorRT-LLM, you should upgrade TensorRT version to 10.1.0.
