### ISSUE TITLE
can i add images embedding to llm input? How can i do it？

### ISSUE THREAD

**Issue by Onwaydbh** [NVIDIA/TensorRT-LLM#2055]
such as，i want to use a Visual Pretrained Language Models to take the image embedding,and add it to llm input to get the output

**Comment by Popsicle0-0** [comment]
Same problem

**Comment by amukkara** [comment]
We support several popular multimodal models in `examples/multimodal/`.

For these models, we pass image embedding input to LLM via `prompt_table` argument (this extends the embedding table of LLM) and modify `input_ids` with indices into `prompt_table`.

You can check `tensorrt_llm/runtime/multimodal_model_runner.py` for how this mechanism is used for different models.

**Comment by Onwaydbh** [comment]
您发给我的信件已收到

**Comment by Onwaydbh** [comment]
您发给我的信件已收到
