### ISSUE TITLE
Configuring total context size

### ISSUE THREAD

**Issue by LanceB57** [NVIDIA/TensorRT-LLM#2064]
### System Info

- TensorRT-LLM v0.10.0
- Llama 3 8B Instruct

### Who can help?

@juney-nvidia @kaiyux @by

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

Try to build a Llama 3 8B Instruct engine using `trtllm-build`

### Expected behavior

Should be able to configure entire context size

### actual behavior

I'm trying to build a Llama 3 8B Instruct engine that allows 8K tokens for its entire context (input and output included). However, it's not clear how I can do so -- do I set `max_input_len`, `max_output_len`, and `max_num_tokens` to 8K? 

### additional notes

N/A

**Comment by nv-guomingz** [comment]
Several ref doc links:

https://nvidia.github.io/TensorRT-LLM/performance/perf-best-practices.html#build-options-to-optimize-the-performance-of-tensorrt-llm-models

https://nvidia.github.io/TensorRT-LLM/reference/memory.html

**Comment by LanceB57** [comment]
Thanks -- for anyone referring to this in the future, it seems that starting from v0.11.0, there's a `max_seq_len` that can be used to define the overarching context length.
