### ISSUE TITLE
Which source file contains the code for loading the model?

### ISSUE THREAD

**Issue by HongfengDu** [NVIDIA/TensorRT-LLM#2068]
I want to customize the model loading process and modify the logic for loading the model

**Comment by nv-guomingz** [comment]
https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/llama/convert_checkpoint.py#L414

**Comment by HongfengDu** [comment]
> https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/llama/convert_checkpoint.py#L414
Thank you, I would like to modify the CPP file.  Another issue， Executor(std::vector<uint8_t> const& engineBuffer, std::string const& jsonConfigStr, ModelType modelType, ExecutorConfig const& executorConfig);     the interface how call
