### ISSUE TITLE
How to invoke the constructor interface of Executor"

### ISSUE THREAD

**Issue by HongfengDu** [NVIDIA/TensorRT-LLM#2073]
![Snipaste_2024-08-01_10-48-09](https://github.com/user-attachments/assets/8f212054-baed-451c-be67-50a86bc9927f)
How to invoke the constructor interface of Executor"

**Comment by lfr-0531** [comment]
You can refer to the gptManagerBenchmark implementation to learn how to use the executor API: https://github.com/NVIDIA/TensorRT-LLM/blob/main/benchmarks/cpp/gptManagerBenchmark.cpp
