### ISSUE TITLE
How suport llama3.1 ropo scaling with smoothquant ?

### ISSUE THREAD

**Issue by fan-niu** [NVIDIA/TensorRT-LLM#2076]
### System Info

A100
NVIDIA-SMI 535.154.05
Driver Version: 535.154.05
CUDA Version: 12.4 
Python 3.10.12

### Who can help?

@Tracin @byshiue 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

The latest version of the code does not support converting llama3.1-8b to smoothquant. The rope scaling of llama3.1 is different from that of llama3, resulting in conversion errors.

### Expected behavior

Support llama3.1-8b to smoothquant

### actual behavior

Does not support converting llama3.1-8b to smoothquant

### additional notes

You can use the huggingface format model of the open source llama3.1-8b to reproduce it.

**Comment by byshiue** [comment]
duplicated issue to https://github.com/NVIDIA/TensorRT-LLM/issues/2025. Close this one.
