### ISSUE TITLE
The convert_checkpoint.py script doesn't work for llama3.1 405b

### ISSUE THREAD

**Issue by hanyunfan** [NVIDIA/TensorRT-LLM#2080]
### System Info

CPU x86-64
NVIDIA H200
Ubuntu 22.04
TRT-LLM commit (a681853d3803ee5893307e812530b5e7004bb6e1)

### Who can help?

@Tracin 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

This example doesn't work with llama3.1 405b model, [[TensorRT-LLM](https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/llama/convert_checkpoint.py)](https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/llama/convert_checkpoint.py)

Followed this guide: https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/llama#run-llama-31-405b-model, in the first step to covert the HF checkpoint to FP8 with TP8 by:

# Run FP8 model by FP8
python examples/llama/convert_checkpoint.py --model_dir llama_3.1_405B_HF_FP8_model/ \
                            --output_dir llama_3.1_405B_HF_FP8_model/trt_ckpts/tp8-pp1/ \
                            --dtype bfloat16 \
                            --tp_size 8 \
                            --pp_size 1 \
                            --load_by_shard \
                            --workers 8 \
                            --remove_duplicated_kv_heads

### Expected behavior

script run through

### actual behavior

![image](https://github.com/user-attachments/assets/4016a844-a018-459b-9699-4cda94316585)

### additional notes

I also tried the HF BF16 model, with below command, got the same error, believe the examples/llama/convert_checkpoint.py script need to be updated for llama3.1's rope_scaling feature.

# Run BF16 model by FP8
python examples/llama/convert_checkpoint.py --model_dir llama_3.1_405B_HF_model/ \
                            --output_dir llama_3.1_405B_HF_model/trt_ckpts/tp8-pp1/ \
                            --dtype bfloat16 \
                            --use_fp8_rowwise \
                            --tp_size 8 \
                            --pp_size 1 \
                            --load_by_shard \
                            --workers 8 \
                            --remove_duplicated_kv_heads

**Comment by PeterWang1986** [comment]
I think you need to upgrade transformers: `pip install --upgrade transformers`

**Comment by hanyunfan** [comment]
I did, but I will try it again. thank you.

**Comment by hanyunfan** [comment]
It was the latest version.

 pip install --upgrade transformers
Requirement already satisfied: transformers in /usr/local/lib/python3.10/dist-packages (4.43.3)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.19.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.24.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/lib/python3/dist-packages (from transformers) (5.4.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (2024.7.24)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.4.3)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (1.26.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers) (3.15.4)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers) (4.66.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers) (24.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers) (2024.5.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.3.2)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->transformers) (2020.6.20)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2.2.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests->transformers) (3.3)

**Comment by hanyunfan** [comment]
I tried from scratch and it looks like the TensorRT-LLM got updated from 0.12.0.dev2024072301 to 0.12.0.dev2024073000, which fixed this issue.
