### ISSUE TITLE
InternVL2 Support ?

### ISSUE THREAD

**Issue by Jeremy-J-J** [NVIDIA/TensorRT-LLM#2083]
### System Info

a6000

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

InternVL2 Supportted now ?

### Expected behavior

InternVL2 Supportted now ?

### actual behavior

InternVL2 Supportted now ?

### additional notes

InternVL2 Supportted now ?

**Comment by lfr-0531** [comment]
Similar issue: https://github.com/NVIDIA/TensorRT-LLM/issues/1934
