### ISSUE TITLE
All tokens incorrectly utilized the same positional encoding during the filling phase.

### ISSUE THREAD

**Issue by BestAnHongjun** [NVIDIA/TensorRT-LLM#2084]
## System Info:
This issue is unrelated to the system architecture.

## Who can help?
@byshiue 

## Detail:

I tracked the behavior of the MMHA kernel function, specifically the `masked_multihead_attention_kernel` (MMAK) function in `cpp/tensorrt_llm/kernels/decoderMaskedMultiheadAttention/decoderMaskedMultiheadAttentionTemplate.h`.

In this function, a variable `current_pos_idx` is defined to represent the current timestep and is used to calculate the `kROPE_GPT_NEOX` positional encoding. I tracked the behavior of this variable during the model generation process and found:

* **During the input (pre-filling) phase**: if the model receives N tokens, `current_pos_idx` becomes N on the first call to MMAK. This causes all N tokens to use positional encoding N, whereas it should normally be [0, 1, 2, ..., N-1]. This critical issue leads to poor performance in long-text inference.
* **During the generation phase**: `current_pos_idx` correctly increments to N+1, N+2, ..., as expected.

I suspect this is a critical bug that affects all models using RoPE. I would appreciate your assistance with the following:

* **If this is not a bug**, and another kernel is used to compute RoPE during the pre-filling phase, please inform me of the location of this call, as I need to further develop positional encoding for the model I am adapting.
* **If this is indeed a bug**, please inform me how to obtain the correct timestep for positional encoding within the MMAK function.

Thank you very much for your help.

**Comment by cavedweller509** [comment]
I  have found the indeed pre-filling function `applyBiasRopeUpdateKVCache` in the `cpp/tensorrt_llm/kernels/unfusedAttentionKernels/unfusedAttentionKernels_2_template.h`, thanks .
