### ISSUE TITLE
Add support for Nougat model

### ISSUE THREAD

**Issue by sherlcok314159** [NVIDIA/TensorRT-LLM#2098]
### System Info

...

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [x] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [x] My own task or dataset (give details below)

### Reproduction

The nougat source code is here: https://github.com/facebookresearch/nougat.

### Expected behavior

Hope we can use TensorRTLLM with Nougat.

### actual behavior

Nougat is not in support.

### additional notes

Thanks for your contribution!

**Comment by lfr-0531** [comment]
TensorRT-LLM can support Nougat model, please refer to the multimodal examples: https://gitlab-master.nvidia.com/ftp/tekit/-/tree/main/examples/multimodal?ref_type=heads#nougat

**Comment by lfr-0531** [comment]
TensorRT-LLM can support Nougat model, please refer to the multimodal examples: https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/multimodal#nougat
