### ISSUE TITLE
How to add a new quantization method?

### ISSUE THREAD

**Issue by Davids048** [NVIDIA/TensorRT-LLM#2102]
I have developed a new KV cache quantization scheme. I am now interested in testing its performance within TensorRT-LLM.

I'm new to this project, so I am trying to understand the current implementation of quantization. I see that INT8 KV cache quantization is already supported. Could you please guide me to the relevant parts of the codebase where this is implemented? Specifically: Where can I find the implementation of the INT8 KV cache quantization? And are there any tests or examples that demonstrate its usage?

Also, I noticed the QuantMode definition in `cpp/include/tensorrt_llm/common/quantization.h` and the quantization kernels in `cpp/tensorrt_llm/kernels/quantization.cu`. How are these CUDA kernels integrated with the Python bindings?

Any pointers or documentation that can help me get started with integrating and testing my quantization scheme would be greatly appreciated.

**Comment by Tracin** [comment]
I am afraid those part is not fully open-sourced.

**Comment by nv-guomingz** [comment]
@Davids048 please re-open this issue if you have further questions
