### ISSUE TITLE
How to test the real memory usage?

### ISSUE THREAD

**Issue by sleepwalker2017** [NVIDIA/TensorRT-LLM#211]
I'm testing trt-llm without paged attention.

But the memory usage is always much higher than FT, no matter how small the batch is.

Seems the GPU memory usage is related to the max batch size when building the engine.

How can I test the real memory usage?

For example, I'm using kv-int8, but I can't confirm that this feature is enabled. Because the memory usage is nearly the same as fp16.

**Comment by jdemouth-nvidia** [comment]
TensorRT will allocate memory for the “worst” case so the memory is constrained by the max batch size, indeed.

**Comment by sleepwalker2017** [comment]
> TensorRT will allocate memory for the “worst” case so the memory is constrained by the max batch size, indeed.

Can you give more details?

For llama without paged attention, it allocates 2048 or 4096 for each batch, is that right?

What if I enabled paged attention? Will it allocate buffer as a memory pool?

**Comment by yunfeng-scale** [comment]
> TensorRT will allocate memory for the “worst” case so the memory is constrained by the max batch size, indeed.

does this include space for paged KV cache as well, or paged KV cache is allocated in addition to this chunk of memory? Asking since I'm seeing params like `max_tokens_in_paged_kv_cache`

**Comment by MartinMarciniszyn** [comment]
Please see the discussion in [issue 401](https://github.com/NVIDIA/TensorRT-LLM/issues/401) regarding the allocation of memory for the paged kv cache. We are also using memory pools for allocating internal buffers, which might not release memory immediately to the driver. To get full clarity on the memory usage of the runtime, you can inspect the internal instance of [MemoryCounters](https://github.com/NVIDIA/TensorRT-LLM/blob/main/cpp/include/tensorrt_llm/runtime/memoryCounters.h#L121) and query the memory pools in [BufferManager](https://github.com/NVIDIA/TensorRT-LLM/blob/main/cpp/include/tensorrt_llm/runtime/bufferManager.h#L151).
