### ISSUE TITLE
`--use_fp8_context_fmha` is broken with Llama models

### ISSUE THREAD

**Issue by ttim** [NVIDIA/TensorRT-LLM#2112]
### System Info

- 1x H100 SXM
- tensorrt-llm 0.12.0.dev2024080600

### Who can help?
@Tracin 

_No response_

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1a. Build FP8 quantized checkpoint using `LLaMAForCausalLM.quantize` API, by passing `QuantConfig(quant_algo=QuantAlgo.FP8)` as an argument
1b. Same but with `QuantConfig(quant_algo=QuantAlgo.FP8, kv_cache_quant_algo=QuantAlgo.FP8)` (are there any difference expected in practice?)
2. Try building engine with `--use_fp8_context_fmha`

### Expected behavior

Engine is successfully built and performs better

### actual behavior

for 1a engine build fails with:
```
terminate called after throwing an instance of 'tensorrt_llm::common::TllmException'
  what():  [TensorRT-LLM][ERROR] Assertion failed: getIdx() should not be used with entry 17
 (/home/jenkins/agent/workspace/LLM/main/L0_MergeRequest/tensorrt_llm/cpp/tensorrt_llm/plugins/gptAttentionPlugin/gptAttentionPlugin.cpp:131)
1       0x7b2f125ba395 /usr/local/lib/python3.10/dist-packages/tensorrt_llm/libs/libnvinfer_plugin_tensorrt_llm.so(+0x51395) [0x7b2f125ba395]
2       0x7b2f1260481b tensorrt_llm::plugins::GPTAttentionPlugin::getIdx(tensorrt_llm::plugins::GPTAttentionPlugin::IdxEntry const&) const + 107
3       0x7b2f12604ad4 tensorrt_llm::plugins::GPTAttentionPlugin::supportsFormatCombination(int, nvinfer1::PluginTensorDesc const*, int, int) + 660
4       0x7b338e7ddae4 /usr/local/lib/python3.10/dist-packages/tensorrt_libs/libnvinfer.so.10(+0xb8aae4) [0x7b338e7ddae4]
```

for 1b it fails fails with:
```
RuntimeError: Paged Context FMHA doesn't work with int8 kv cache currently.
```
which seems to be set in `config.json`:
```
...
"producer": {
        "name": "modelopt",
        "version": "0.15.1"
    },
...
    "quantization": {
        "quant_algo": "FP8",
        "kv_cache_quant_algo": "INT8"
    },
```
After manually fixing `kv_cache_quant_algo` to `FP8` it started working, but not sure if it's correct fix.

### additional notes

Is `LlamaModel.quantize` recommended way to build checkpoints? Should I use something else instead?

**Comment by Kefeng-Duan** [comment]
please use https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/quantization/quantize.py for fp8 quant

**Comment by Superjomn** [comment]
Can you also show us some code or the specific TRT-LLM example you are using to help clarify the related APIs?

**Comment by ttim** [comment]
@Superjomn I'm using `LlamaModel.quantize` API, to be precise this:
```
LLaMAForCausalLM.quantize(model_dir, dtype="float16", QuantConfig(quant_algo=QuantAlgo.FP8, kv_cache_quant_algo=QuantAlgo.FP8), mapping, output_dir)
```
And then use `trtllm-build` command with `output_dir`.

It's not clear to me when/if I should be using https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/quantization/quantize.py vs this method. Should I use  `quantize_and_export` method directly then?

Thanks!

**Comment by syuoni** [comment]
Hi @ttim `LLaMAForCausalLM.quantize` should work in your case. 

I tried the below code snippet on the latest main branch, and everything went well.
```python
from tensorrt_llm.models import LLaMAForCausalLM
from tensorrt_llm.models.modeling_utils import QuantConfig, QuantAlgo

hf_model_dir = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
ckpt_dir = "/tmp/ckpt-tinyllama"
LLaMAForCausalLM.quantize(hf_model_dir, ckpt_dir, quant_config=QuantConfig(quant_algo=QuantAlgo.FP8, kv_cache_quant_algo=QuantAlgo.FP8))
```

The quantization field of exported checkpoint config is 
```json
"quantization": {
        "quant_algo": "FP8",
        "kv_cache_quant_algo": "FP8"
    }
```

---

Could you please try with the latest main branch? Also, I noticed that the parameter order of your use of `LLaMAForCausalLM.quantize` is not exactly correct, would you also check that?

**Comment by ttim** [comment]
@syuoni seems like it got fixed in the last release! - it works with main branch, thank you!
