### ISSUE TITLE
multi_block_mode has been removed in the current version?

### ISSUE THREAD

**Issue by GGBond8488** [NVIDIA/TensorRT-LLM#2119]
### System Info

NVIDIA -A100

### Who can help?

@juney-nvidia

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

trtllm-build --checkpoint_dir ./c-model/gpt2/fp16/4-gpu \
        --gpt_attention_plugin float16 \
        --remove_input_padding enable \
        --paged_kv_cache enable \
        --multi_block_mode enable \
        --gemm_plugin float16 \
        --output_dir engines/fp16/4-gpu
 

### Expected behavior

engine build successfully

### actual behavior

trtllm-build: error: unrecognized arguments: --multi_block_mode enable

### additional notes

https://nvidia.github.io/TensorRT-LLM/performance/perf-best-practices.html#multi-block-mode the best practices docs show s this param but it not work in current

**Comment by kaiyux** [comment]
It has been moved to the runtime, so that you don't need to rebuild the engine if you want to switch the option. You can take this as an example: https://github.com/NVIDIA/TensorRT-LLM/blob/main/benchmarks/cpp/gptManagerBenchmark.cpp#L1893

**Comment by GGBond8488** [comment]
> It has been moved to the runtime, so that you don't need to rebuild the engine if you want to switch the option. You can take this as an example: https://github.com/NVIDIA/TensorRT-LLM/blob/main/benchmarks/cpp/gptManagerBenchmark.cpp#L1893

got it, thank you
