### ISSUE TITLE
Sampling diversity

### ISSUE THREAD

**Issue by Selimonder** [NVIDIA/TensorRT-LLM#212]
Hey,

Given an input prompt [**1**, **n_tokens**] I am trying to get alternatives to the output by repeating my input prompt as [**8**, **n_tokens**], 8 being the _batch size_. Although I am not sure whether this is a right way to achieve my goal (which is generating alternative outputs for a fixed prompt), on outputs I observe something rather interesting.

When I inspect the outputs, the first sample is different from the second one, as expected(?). However, starting from the third sample, all the outputs are identical to the second sample in the batch. To clarify, here is what the outputs look like:

| Sample | Output        | Description                  |
|--------|---------------|------------------------------|
| 1      | Output 1      | Unique                       |
| 2      | Output 2      | Unique                       |
| 3      | Output 2      | Identical to second output   |
| 4      | Output 2      | Identical to second output   |
| 5      | Output 2      | Identical to second output   |
| 6      | Output 2      | Identical to second output   |
| 7      | Output 2      | Identical to second output   |
| 8      | Output 2      | Identical to second output   |

Alternative to my approach, I've tried `n_beams` > `1` but couldn't achieve diverse outputs there as well.

Is there something I might be missing or doing wrong in my approach? Any insights or suggestions would be greatly appreciated!

**Comment by uppalutkarsh** [comment]
If I understand correctly, you want to generate different outputs for same input and output seq len, you can look at sampling config class [here](https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/tensorrt_llm/runtime/generation.py#L258) in tensorrt_llm runtime to set `top_k`, `top_p`, `temperature`, etc. 

Let us know if it helps : )
Utkarsh

**Comment by Linzecong** [comment]
same, but when i set random_seed, everything become ok.

**Comment by Selimonder** [comment]
Hey, likewise, random seed helped.

**Comment by shatealaboxiaowang** [comment]
Inference process Which calculations use random_seed ??

**Comment by yecphaha** [comment]
> Inference process Which calculations use random_seed ??

Hey bro, did you finally get the answer?
