### ISSUE TITLE
Max Forward Passes Support

### ISSUE THREAD

**Issue by xingdiyou** [NVIDIA/TensorRT-LLM#2127]
### System Info

A100
Tensorrt-LLM-verison:0.11.0

### Who can help?

@ncomly-nvidia @kaiyux

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

When Medusa heads predict too many error tokens, setting big `maxNewTokens` in `tensorrt_llm::executor::Request` can lead to high latency. 

### Expected behavior

Introducing support for maxForwardPasses could help mitigate this issue."

### actual behavior

When Medusa heads predict too many error tokens, setting big `maxNewTokens` in `tensorrt_llm::executor::Request` can lead to high latency. 

### additional notes

Introducing support for maxForwardPasses could help mitigate this issue."

**Comment by lfr-0531** [comment]
Can you provide more details that can help us reproduce? 

As for the `maxForwardPasses`, what's the functionality of this parameter. I am not sure if setting a proper `--max_num_tokens` when building engine can help or not.

**Comment by xingdiyou** [comment]
> Can you provide more details that can help us reproduce?
> 
> As for the `maxForwardPasses`, what's the functionality of this parameter. I am not sure if setting a proper `--max_num_tokens` when building engine can help or not.

"In my small batch scenario, request latency is correlated with the number of new tokens generated. To ensure low latency, I set the `maxNewTokens` parameter in `tensorrt_llm::executor::Request`. However, with Medusa's speculative decoding, each forward pass may generate multiple tokens, increasing latency due to additional verification steps, as shown in the figure.

In the worst-case scenario, all tokens generated by Medusa heads could be incorrect, meaning each forward pass yields only one correct token with extra verification, leading to higher latency. Could you add support for a `maxForwardPasses` parameter to limit the number of forward passes during inference?"

![Image](https://github.com/user-attachments/assets/42d4eeea-2125-46e6-931f-c497c92c900f)
[https://arxiv.org/pdf/2401.10774](url)

**Comment by dongxuy04** [comment]
@xingdiyou Could you please explain more on what `maxForwardPasses` means?

I am not sure if I understand your idea correctly, literally I guess it means the number for forward run by the engine. For Medusa, each run will take `1+num_draft_tokens` tokens as input tokens and the engine also compute additional Medusa Heads so each forward step take longer than base model. When there are some correct prediction, it will generate more than one token for a single forward step(maybe pass?), I believe the possible speed up of Medusa comes from here. When very unfortunately there is only one correct token, Medusa will have higher latency. I guess one possible way to reduce latency in this case is reduce `num_draft_tokens`?

For `maxNewTokens`, I think it controls the maximum numbers of generated tokens, for example, when using base model, it will be same as the number of generation steps + 1 (maybe `maxForwardPasses` you mentioned), and for Medusa, since it is possible to output more than one token per step, so number of new tokens can be larger than number of forward steps. I guess if we use `maxForwardPasses`, Medusa will output more tokens than base model with same step count, thus more latency.

It might be great if you can provide more details to help us understand. Thanks.

**Comment by xingdiyou** [comment]
> [@xingdiyou](https://github.com/xingdiyou) Could you please explain more on what `maxForwardPasses` means?
> 
> I am not sure if I understand your idea correctly, literally I guess it means the number for forward run by the engine. For Medusa, each run will take `1+num_draft_tokens` tokens as input tokens and the engine also compute additional Medusa Heads so each forward step take longer than base model. When there are some correct prediction, it will generate more than one token for a single forward step(maybe pass?), I believe the possible speed up of Medusa comes from here. When very unfortunately there is only one correct token, Medusa will have higher latency. I guess one possible way to reduce latency in this case is reduce `num_draft_tokens`?
> 
> For `maxNewTokens`, I think it controls the maximum numbers of generated tokens, for example, when using base model, it will be same as the number of generation steps + 1 (maybe `maxForwardPasses` you mentioned), and for Medusa, since it is possible to output more than one token per step, so number of new tokens can be larger than number of forward steps. I guess if we use `maxForwardPasses`, Medusa will output more tokens than base model with same step count, thus more latency.
> 
> It might be great if you can provide more details to help us understand. Thanks.

Let me provide an example. Suppose the base model takes 10 ms to generate one token, while the Medusa model with 4 heads takes 20 ms to generate between 1 and 5 tokens. To generate 10 tokens, the base model requires 100 ms. In the best-case scenario, the Medusa model would take 40 ms, but in the worst-case scenario, it could take up to 200 ms. In my situation, I only have 100 ms available, so I need to limit the number of forward steps to ensure the latency remains within this time constraint. Thank you for your consideration. @dongxuy04

**Comment by dongxuy04** [comment]
Thanks for your nice example @xingdiyou . I think it is much clear now. So if I understand correctly, I guess your requirement is to wait request for a limited time, and would like to get the output tokens (maybe not finished) at that time. And the setting of `maxForwardPasses` is to help you achieve that, is that correct?

If that is the case, I think for now, our Executor API has `cancel_request` interface, which can cancel one processing request, so the current outputs can be got by `await_responses`. Maybe like this: Please let me know if that may help, thanks.

```
req_id = executor.enqueue_request(request)  # enqueue request and get request id
sleep(0.8)                                  # wait the response for some time
executor.cancel_request(req_id)             # going to be time out, cancel that to get request
res=executor.await_responses(req_id)        # wait that request id(wait cancel done)
print(res[0].result.output_token_ids)       # got the result
```

**Comment by xingdiyou** [comment]
It appears that the C++ runtime is not functioning as expected. With the following code, each request incurs a minimum latency of 100ms:
```
auto request_id = executor_->enqueueRequest(request);
std::this_thread::sleep_for(std::chrono::milliseconds(100)); // Minimum latency of 100ms per request
executor_->cancelRequest(request_id); 
auto responses = executor_->awaitResponses(request_id);
```
When moving the code below to a background thread, the latency remains over 100ms:
```
std::this_thread::sleep_for(std::chrono::milliseconds(100));
executor_->cancelRequest(request_id);
```
Looking forward to your additional testing.
Thank you! @dongxuy04

**Comment by dongxuy04** [comment]
@xingdiyou I think minimum latency of 100ms is as expected. Since after we `enqueueRequest`, we use `std::this_thread::sleep_for` to wait 100ms, then we use `cancelRequest` to send cancel signal to executor_ to cancel the request. However, it usually don't cancel immediately since executor will wait for the current step finish to real do the cancellation. So, it may be needed to added some buffer for that, maybe 2 times of single step time. For example, if single step time is 4ms, maybe we should use `std::this_thread::sleep_for(std::chrono::milliseconds(92));` where `92` is `100 - 2 * 4`. And also to be noted, I think it is not designed as a real time system, so latencies are not guaranteed. But in this way, I think you can get current generated tokens after a fixed time.

Please let us know if this make senses to you, thanks.

**Comment by dongxuy04** [comment]
And for the `sleep_for`, it might be better replaced with `executor_->awaitResponses(request_id, std::chrono::milliseconds(92));` Then if it returns the responses in time, you can just use the response, if not, cancel it and get current outputs.

**Comment by xingdiyou** [comment]
@dongxuy04 Thank you for your insights! I'm not entirely sure if the following code is correct. There's a possibility that awaitResponses could block indefinitely. Also, is the executor thread-safe?
```
auto request_id = executor_->enqueueRequest(request);
auto responses = executor_->awaitResponses(request_id, std::chrono::milliseconds(92));  // Potential risk of blocking indefinitely
auto result = responses.at(0).getResult();
if (!result.isFinal) {
  executor_->cancelRequest(request_id); 
}
```

**Comment by dongxuy04** [comment]
@xingdiyou most of the code seems good to me expect that `auto result = responses.at(0).getResult();` may need to check if `responses` actually has any elements since if timed out, response for the `request_id` may not be there.

The executor should be thread-safe, could you please try with latest main branch on that to see if still blocking?

**Comment by xingdiyou** [comment]
After upgrading to the latest main branch (commit ID: 31ac30e928a2db795799fdcab6be446bfa3a3998), the line `auto responses = executor_->awaitResponses(request_id, std::chrono::milliseconds(92));` still has the potential to cause blocking. I couldn't find any usage of `std::vector<Response> awaitResponses(IdType const& requestId, std::optional<std::chrono::milliseconds> const& timeout = std::nullopt);` in the TensorRT-LLM repository. Has this function been fully tested? @dongxuy04

**Comment by dongxuy04** [comment]
@xingdiyou I think it should be tested, it would be great if you could provide a short reproduce code for this. Thanks.

**Comment by xingdiyou** [comment]
It appears that there is an issue with the awaitResponses function when using shorter timeouts. 
Specifically:
- When the timeout is set to 1000 ms, the request completes successfully and returns the expected response:
```
auto request_id = executor_->enqueueRequest(request);
auto responses = executor_->awaitResponses(request_id, std::chrono::milliseconds(1000)); // Works as expected
```
- However, when the timeout is reduced to 10 ms, the request seems to block or hang:
```
auto request_id = executor_->enqueueRequest(request);
auto responses = executor_->awaitResponses(request_id, std::chrono::milliseconds(10)); // Blocks or hangs
```
From my observations, the request itself takes around 100 ms to execute. It seems that the shorter timeout (10 ms) doesn't allow enough time for the request to process, leading to the blocking behavior.
Could you please investigate whether this behavior is expected, and if there are any workarounds or potential fixes for handling shorter timeout values gracefully? Thanks. @dongxuy04

**Comment by dongxuy04** [comment]
@xingdiyou I tried to add a test case in Executor UnitTest like the following, change between 10 ms and 1 ms for wait time, and run multiple times for different beamWidth, streaming/non-streaming mode. But didn't see blocking behavior. It would be great if you could provide a minimum reproduce file to help demonstrate this bug. And if you think this is not related to Medusa but the Executor API, you can file a new bug to avoid confusion. Thanks.

```
    auto requestId = executor.enqueueRequest(std::move(request));

    std::chrono::milliseconds waitTime(10);
    auto responses = executor.awaitResponses(requestId, waitTime);
```

**Comment by xingdiyou** [comment]
> It appears that there is an issue with the awaitResponses function when using shorter timeouts. Specifically:
> 
> * When the timeout is set to 1000 ms, the request completes successfully and returns the expected response:
> 
> ```
> auto request_id = executor_->enqueueRequest(request);
> auto responses = executor_->awaitResponses(request_id, std::chrono::milliseconds(1000)); // Works as expected
> ```
> 
> * However, when the timeout is reduced to 10 ms, the request seems to block or hang:
> 
> ```
> auto request_id = executor_->enqueueRequest(request);
> auto responses = executor_->awaitResponses(request_id, std::chrono::milliseconds(10)); // Blocks or hangs
> ```
> 
> From my observations, the request itself takes around 100 ms to execute. It seems that the shorter timeout (10 ms) doesn't allow enough time for the request to process, leading to the blocking behavior. Could you please investigate whether this behavior is expected, and if there are any workarounds or potential fixes for handling shorter timeout values gracefully? Thanks. [@dongxuy04](https://github.com/dongxuy04)

@dongxuy04 Thank you for your investigation. I believe I’ve identified the root cause of the issue.

In the TensorRT-LLM unit test, the following code results in an exception and crashes:
```
auto request_id = executor_->enqueueRequest(request);
auto responses = executor_->awaitResponses(request_id, std::chrono::milliseconds(10));
auto result = responses.at(0).getResult(); // throw exception and crash
```
However, in my program that links to libtensorrt_llm.so, the same code behaves differently, resulting in a blocking call:
```
auto request_id = executor_->enqueueRequest(request);
auto responses = executor_->awaitResponses(request_id, std::chrono::milliseconds(10));
auto result = responses.at(0).getResult(); // blocking
```
I'm unsure why this discrepancy occurs but will proceed to close this issue.
