### ISSUE TITLE
 How to deploy this model（Qwen/Qwen2-1.5B-Instruct-AWQ · Hugging Face.） on TensorRT-LLM?

### ISSUE THREAD

**Issue by shaoyanguo** [NVIDIA/TensorRT-LLM#2128]
because TensorRT-LLM only support fp16 transformer models. Thank you!
I advise https://github.com/NVIDIA/TensorRT-LLM/blob/main/tensorrt_llm/models/llama/convert.py#L1714,but inference result is wrong,
can you help me?

**Comment by lfr-0531** [comment]
Please refer to the Qwen examples: https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/qwen#int4-awq

You can use `Qwen/Qwen2-1.5B-Instruct` from HF and use TensorRT-LLM for AWQ quantization and deployment.
