### ISSUE TITLE
https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/hf_lora_convert.py

### ISSUE THREAD

**Issue by Jeevi10** [NVIDIA/TensorRT-LLM#2132]
### System Info

I am trying to convert Dora adapters that was trained use hugging face peft, however I have got stuck when I encounter layer "encoder.layers.9.self_attn.v_proj.lora_magnitude_vector". Can someone explain how to convert hf trained dora adapters for whisper models. 

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

[TensorRT-LLM] TensorRT-LLM version: 0.13.0.dev2024081300

!python3 ./TensorRT-LLM/examples/hf_lora_convert.py --out-dir whisper_lora --verbose --in-file ./whisper-medium-argus_CT_augment_oct/checkpoint-500/adapter_model/

### Expected behavior

base_model.model.model.encoder.layers.9.self_attn.q_proj.lora_magnitude_vector

### actual behavior

no match base_model.model.model.encoder.layers.9.self_attn.q_proj.lora_magnitude_vector

### additional notes

Please guide me

**Comment by lfr-0531** [comment]
TensorRT-LLM cannot support DoRA now and will support it soon.
