### ISSUE TITLE
[Question]:  engine build hyper-paramters for llama-3-70B sample

### ISSUE THREAD

**Issue by ZJLi2013** [NVIDIA/TensorRT-LLM#2139]
when to use the model config and `max_num_tokens`,  `max_batch_size` from [meta-llama-3-70B](https://nvidia.github.io/TensorRT-LLM/performance/perf-overview.html) to build engine, while I am facing oom when runing the engine: 

I am building engine like this:  

|tp | max_num_tokens|max_bs|
|---|---|---|
|8 | 16384 | 8192 | 

```sh           
 trtllm-build --model_config $model_cfg \
                --use_fused_mlp enable \
                --gpt_attention_plugin float16 \
                --output_dir $engine_dir \
                --workers 8 \
                --max_batch_size $max_batch_size \
                --max_num_tokens $max_num_tokens \
                --max_input_len 2048 \
                --max_seq_len 4096 \
                --use_paged_context_fmha enable \
                --multiple_profiles enable     
``` 
it can build done, while it reports oom when run gptManagerBench with inputlen 128, output 128 case.

also tried to small  num_tokens=4094, and  max_bs from 1024 to 256, but all these configs give runtime oom.

so wonder what's the workable hyper-parameters used in this sample ?  

Thanks

**Comment by ZJLi2013** [comment]
ok, looks the latest 0.13 is bugy, downgrade to 0.12, runs well.

**Comment by ZJLi2013** [comment]
looks [llama-3.1 feature support](https://github.com/NVIDIA/TensorRT-LLM/pull/2008),  only merged in main branch,  so can't work with trtllm 0.12.0 branch for llama-3.1 models ？  can the expert teams help to check out ?

**Comment by lfr-0531** [comment]
TensorRT-LLM v0.12.0 can support llama-3.1 models, please refer to the llama examples: https://github.com/NVIDIA/TensorRT-LLM/tree/v0.12.0/examples/llama#run-llama-31-405b-model
