### ISSUE TITLE
trtllm-build the Qwen2 checkpoint yields KeyError: 'Qwen2ForCausalLM'

### ISSUE THREAD

**Issue by sdecoder** [NVIDIA/TensorRT-LLM#2141]
Greetings, everyone. First of all, some specifications here:
1. docker version: nvcr.io/nvidia/tritonserver:24.07-trtllm-python-py3 
2. trtllm-build --version: [TensorRT-LLM] TensorRT-LLM version: 0.11.0
3. CPU:  Intel(R) Xeon(R) Gold 6342 CPU @ 2.80GHz
4. GPU: A30[24G] X4
5. Memory: General modern memory
6. Storage: General modern storage

1. trying to generate the Qwen2 TensorRT checkpoint first, the checkpoint is downloaded from the Huggingface using git:
'''
python convert_checkpoint.py --model_dir /projects/Qwen2-7B --output_dir  /projects/trt_ckpts/  --dtype float16 --use_weight_only --smoothquant 0.8 --per_channel --per_token 
'''
This step finished successfully.
7. trying to build the TensorRT engine using:
'''
trtllm-build --checkpoint_dir /projects/trt_ckpts/ \
            --remove_input_padding enable \
            --gpt_attention_plugin float16 \
            --context_fmha enable \
            --gemm_plugin float16 \
            --output_dir /engines \
            --paged_kv_cache enable \
            --max_batch_size 4
'''
8. error output:
Traceback (most recent call last):
  File "/usr/local/bin/trtllm-build", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/commands/build.py", line 437, in main
    model_config = PretrainedConfig.from_json_file(config_path)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/modeling_utils.py", line 260, in from_json_file
    return cls.from_dict(config)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/modeling_utils.py", line 242, in from_dict
    model_cls = MODEL_MAP[config['architecture']]
KeyError: 'Qwen2ForCausalLM'
9. config.json:
'''
 cat /root/trt_ckpts/config.json
{
    "mlp_bias": false,
    "attn_bias": true,
    "rotary_base": 1000000.0,
    "rotary_scaling": null,
    "disable_weight_only_quant_plugin": false,
    "moe": {
        "num_experts": 0,
        "top_k": 0,
        "normalization_mode": 0,
        "tp_mode": 0
    },
    "architecture": "Qwen2ForCausalLM",
    "dtype": "float16",
    "vocab_size": 152064,
    "hidden_size": 3584,
    "num_hidden_layers": 28,
    "num_attention_heads": 28,
    "hidden_act": "silu",
    "logits_dtype": "float32",
    "norm_epsilon": 1e-06,
    "position_embedding_type": "rope_gpt_neox",
    "max_position_embeddings": 131072,
    "num_key_value_heads": 4,
    "intermediate_size": 18944,
    "mapping": {
        "world_size": 1,
        "gpus_per_node": 8,
        "cp_size": 1,
        "tp_size": 1,
        "pp_size": 1,
        "moe_tp_size": 1,
        "moe_ep_size": 1
    },
    "quantization": {
        "quant_algo": "W8A16",
        "kv_cache_quant_algo": null,
        "group_size": 128,
        "smoothquant_val": 0.5,
        "clamp_val": null,
        "has_zero_point": false,
        "pre_quant_scale": false,
        "exclude_modules": null
    },
    "use_parallel_embedding": false,
    "embedding_sharding_dim": 0,
    "share_embedding_table": false,
    "head_size": 128,
    "qk_layernorm": false,
    "qwen_type": "qwen2",
    "moe_intermediate_size": 0,
    "moe_shared_expert_intermediate_size": 0
'''

Any help/hint is highly appreciated.

**Comment by lfr-0531** [comment]
Can you have a try on v0.12.0 version or the main branch?

**Comment by sdecoder** [comment]
> Can you have a try on v0.12.0 version or the main branch?
I will have a try. Thank you for pointing out that.

**Comment by Aasthaengg** [comment]
I'm facing same issue, with  :

> trtllm-build --version:  TensorRT-LLM version: 0.17.0.post1

I am following the README instructions - 

```
python3 ../qwen/convert_checkpoint.py \
    --model_dir=tmp/hf_models/${MODEL_NAME} \
    --output_dir=tmp/trt_models/${MODEL_NAME}/fp16/1-gpu \
    --dtype float16

trtllm-build --checkpoint_dir tmp/trt_models/${MODEL_NAME}/fp16/1-gpu \
    --output_dir tmp/trt_engines/${MODEL_NAME}/fp16/1-gpu/llm \
    --gemm_plugin=float16 \
    --gpt_attention_plugin=float16 \
    --max_batch_size=4 \
    --max_input_len=2048 --max_seq_len=3072 \
    --max_multimodal_len=1296 #(max_batch_size) * 324 (num_visual_features), this's for image_shape=[504,504]

```

This is the config that I am using inside the path :

>  `tmp/trt_models/Qwen2-VL-7B-Instruct/fp16/1-gpu/`

`{
  "architectures": [
    "Qwen2VLForConditionalGeneration"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "eos_token_id": 151645,
  "vision_start_token_id": 151652,
  "vision_end_token_id": 151653,
  "vision_token_id": 151654,
  "image_token_id": 151655,
  "video_token_id": 151656,
  "hidden_act": "silu",
  "hidden_size": 3584,
  "initializer_range": 0.02,
  "intermediate_size": 18944,
  "max_position_embeddings": 32768,
  "max_window_layers": 28,
  "model_type": "qwen2_vl",
  "num_attention_heads": 28,
  "num_hidden_layers": 28,
  "num_key_value_heads": 4,
  "rms_norm_eps": 1e-06,
  "rope_theta": 1000000.0,
  "sliding_window": 32768,
  "tie_word_embeddings": false,
  "torch_dtype": "bfloat16",
  "transformers_version": "4.41.2",
  "use_cache": true,
  "use_sliding_window": false,
  "vision_config": {
    "depth": 32,
    "embed_dim": 1280,
    "mlp_ratio": 4,
    "num_heads": 16,
    "in_chans": 3,
    "hidden_size": 3584,
    "patch_size": 14,
    "spatial_merge_size": 2,
    "spatial_patch_size": 14,
    "temporal_patch_size": 2
  },
  "rope_scaling": {
    "type": "mrope",
    "mrope_section": [
      16,
      24,
      24
    ]
  },
  "vocab_size": 152064
}`
