### ISSUE TITLE
C++ example code for GPT model inference

### ISSUE THREAD

**Issue by AmazDeng** [NVIDIA/TensorRT-LLM#2142]
Could tensorrt-llm provide a C++ example code for GPT model inference? I noticed that the official examples are all in Python. Could you provide a C++ version?
@kaiyux  @Shixiaowei02  @nv-guomingz

**Comment by zhangts20** [comment]
@AmazDeng You can find them in https://github.com/NVIDIA/TensorRT-LLM/tree/v0.11.0/examples/cpp/executor

**Comment by AmazDeng** [comment]
> [@AmazDeng](https://github.com/AmazDeng) You can find them in https://github.com/NVIDIA/TensorRT-LLM/tree/v0.11.0/examples/cpp/executor

Thank you. I'll check it out later.

**Comment by AmazDeng** [comment]
> > [@AmazDeng](https://github.com/AmazDeng) You can find them in https://github.com/NVIDIA/TensorRT-LLM/tree/v0.11.0/examples/cpp/executor
> 
> Thank you. I'll check it out later.

@zhangts20 
Sorry, I may not have clearly expressed my needs. What I am looking for is the cpp code for a multimodal model, one that takes both image and text inputs, like llava, blip2. What you provided was the cpp code for a GPT model that only takes text input.

**Comment by zhangts20** [comment]
> > > [@AmazDeng](https://github.com/AmazDeng) You can find them in https://github.com/NVIDIA/TensorRT-LLM/tree/v0.11.0/examples/cpp/executor
> > 
> > 
> > Thank you. I'll check it out later.
> 
> [@zhangts20](https://github.com/zhangts20) Sorry, I may not have clearly expressed my needs. What I am looking for is the cpp code for a multimodal model, one that takes both image and text inputs, like llava, blip2. What you provided was the cpp code for a GPT model that only takes text input.

I am also seeking for this, but there has been no progress

**Comment by lfr-0531** [comment]
> What you provided was the cpp code for a GPT model that only takes text input.

@zhangts20 @AmazDeng Now TensorRT-LLM can only support multimodal models with Python runtime and will have cpp runtime support later.
