### ISSUE TITLE
Does the current tensorrt-llm support two images as input？

### ISSUE THREAD

**Issue by AmazDeng** [NVIDIA/TensorRT-LLM#2144]
I am using the llava-onevision model (https://llava-vl.github.io/blog/2024-08-05-llava-onevision/),  which can accept two images as input and then ask questions about the two images. Does the current tensorrt-llm support this type of model?
@kaiyux @Shixiaowei02 @nv-guomingz

**Comment by amukkara** [comment]
We support multiple images for VILA. See batching mode 1 in [README](https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/multimodal#llava-llava-next-and-vila).

The embeddings for each image are concatenated together before passing to LLM.  https://github.com/NVIDIA/TensorRT-LLM/blob/78f5c2936b7bdaa56859075a3f2fcc5a63952134/tensorrt_llm/runtime/multimodal_model_runner.py#L723

**Comment by AmazDeng** [comment]
> We support multiple images for VILA. See batching mode 1 in [README](https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/multimodal#llava-llava-next-and-vila).
> 
> The embeddings for each image are concatenated together before passing to LLM.
> 
> [TensorRT-LLM/tensorrt_llm/runtime/multimodal_model_runner.py](https://github.com/NVIDIA/TensorRT-LLM/blob/78f5c2936b7bdaa56859075a3f2fcc5a63952134/tensorrt_llm/runtime/multimodal_model_runner.py#L723)
> 
> Line 723 in [78f5c29](/NVIDIA/TensorRT-LLM/commit/78f5c2936b7bdaa56859075a3f2fcc5a63952134)
> 
>  def setup_fake_prompts_vila(self, batch_size, visual_features,



@amukkara @kaiyux @Shixiaowei02 @nv-guomingz @lfr-0531
Does tensorrt-llm support separate input of embeddings for multiple images? Something like this prompt:`Image-1: <image>\nImage-2: <image>\nAre these two T-shirts exactly the same? Answer Yes or No in one word.`

**Comment by amukkara** [comment]
@AmazDeng Yes, it is supported but only for VILA model.

**Comment by AmazDeng** [comment]
> [@AmazDeng](https://github.com/AmazDeng) Yes, it is supported but only for VILA model.


@amukkara
Is there a plan to support the InternVL2 multimodal model? This is currently the best open-source multimodal model.(https://rank.opencompass.org.cn/leaderboard-multimodal/?m=REALTIME)

**Comment by amukkara** [comment]
@AmazDeng We are working on adding InternVL2 model.

**Comment by AmazDeng** [comment]
> [@AmazDeng](https://github.com/AmazDeng) We are working on adding InternVL2 model.

@amukkara 
Thank you. If there's any progress and it's convenient, please let me know.
