### ISSUE TITLE
The engine generated by each build has different results for the same input.

### ISSUE THREAD

**Issue by 1096125073** [NVIDIA/TensorRT-LLM#2148]
### System Info

trt-llm v0.9.0

### Who can help?

@byshiue 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. build the engine for test 1
2. build the engine for test 2
3. run above 2 engine use the same input

### Expected behavior

the ouputs is same

### actual behavior

the ouputs is not same

### additional notes

I tried to use the model cache when building, but it didn't work.

**Comment by 1096125073** [comment]
Is there any way to ensure that the engine generated by build is identical?This is important for engineering deployment.

**Comment by lfr-0531** [comment]
Can you provide more details, i.e the cmds, which can help us reproduce this issue?

**Comment by qiancheng99** [comment]
> Can you provide more details, i.e the cmds, which can help us reproduce this issue?

I encountered same issue. I trtllm-build 2 times with everything identical, but the inference results are slightly different between 2 models for the same input. Also I found a similar problem post by others. [https://github.com/NVIDIA/TensorRT-LLM/issues/2196](url)
