### ISSUE TITLE
Bug for fp8 PTQ and AWQ with AMMO quantization

### ISSUE THREAD

**Issue by HaoWuSR** [NVIDIA/TensorRT-LLM#216]
I use the examples in examples/llama to test the quantization performance. Everything is ok except FP8 PTQ and AWQ. The bug is shown below: 

<img width="1103" alt="image" src="https://github.com/NVIDIA/TensorRT-LLM/assets/25154834/ba426ca1-5b94-42f1-962a-c4de775bc9b0">
<img width="1088" alt="image" src="https://github.com/NVIDIA/TensorRT-LLM/assets/25154834/0a518de6-1f99-45b9-a3e7-41c79bca8b2f">
Here is the script to run :
python quantize.py --model_dir /workspace/suri/model/model/llama/llama/llama-7b-hf \
                   --dtype float16 \
                   --qformat fp8 \
                    --export_path ./quantized_fp8 \
                    --calib_size 512 \

And I have tried to use the ammo directly to quantize them, but still get the same error.
Thanks for your time!

**Comment by jdemouth-nvidia** [comment]
Hi @HaoWuSR ,

What is your environment, please? 

Also, can you share the build and run commands, please?

Thanks,
Julien

**Comment by byshiue** [comment]
@HaoWuSR I’ve tried to reproduce on H100 but I have not been able to do it so far. The followings are my scripts:
```bash
cd examples/llama/
cuda_version=$(nvcc --version | grep 'release' | awk '{print $6}' | awk -F'[V.]' '{print $2$3}')
python_version=$(python3 --version 2>&1 | awk '{print $2}' | awk -F. '{print $1$2}')
wget https://developer.nvidia.com/downloads/assets/cuda/files/nvidia-ammo/nvidia_ammo-0.3.0.tar.gz
pip install nvidia_ammo-0.3.0/nvidia_ammo-0.3.0+cu$cuda_version-cp$python_version-cp$python_version-linux_x86_64.whl
cd ../../examples/quantization/
pip install -r requirements.txt 
cd -
python3 quantize.py --model_dir /home/scratch.trt_llm_data/llm-models/llama-models/llama-7b-hf/ --dtype float16 --qformat fp8 --export_path /tmp --calib_size 512
```

and the results of my side
```
bhsueh@c45d72399ef9:/home/scratch.bhsueh_sw_1/workspace/TensorRT-LLM/tllm/examples/llama$ python3 quantize.py --model_dir /home/scratch.trt_llm_data/llm-models/llama-models/llama-7b-hf/ --dtype float16 --qformat fp8 --export_path /tmp --calib_size 512
[NeMo W 2023-10-31 08:03:13 nemo_logging:349] /home/bhsueh/.local/lib/python3.10/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
      warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
    
Using pad_token, but it is not set yet.
WARNING: Logging before flag parsing goes to stderr.
W1031 08:03:15.066031 139757021590656 modeling.py:706] The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████| 2/2 [01:04<00:00, 32.09s/it]
Loading calibration dataset
Downloading builder script: 100%|██████████████████████████████████████████████████████| 8.33k/8.33k [00:00<00:00, 23.1MB/s]
Downloading metadata: 100%|████████████████████████████████████████████████████████████| 9.88k/9.88k [00:00<00:00, 32.6MB/s]
Downloading readme: 100%|██████████████████████████████████████████████████████████████| 15.1k/15.1k [00:00<00:00, 34.3MB/s]
Downloading data: 100%|███████████████████████████████████████████████████████████████████| 159M/159M [00:01<00:00, 100MB/s]
Downloading data: 100%|███████████████████████████████████████████████████████████████████| 376M/376M [00:02<00:00, 131MB/s]
Downloading data: 46.4MB [00:00, 111MB/s]██████████████                                       | 2/5 [00:05<00:08,  2.99s/it]
Downloading data: 2.43MB [00:00, 43.5MB/s]                                                                                  
Downloading data: 2.11MB [00:00, 35.1MB/s]                                                                                  
Downloading data files: 100%|█████████████████████████████████████████████████████████████████| 5/5 [00:07<00:00,  1.49s/it]
Generating train split: 100%|██████████████████████████████████████████████| 287113/287113 [00:59<00:00, 4862.10 examples/s]
Generating validation split: 100%|████████████████████████████████████████████| 13368/13368 [00:28<00:00, 467.39 examples/s]
Generating test split: 100%|██████████████████████████████████████████████████| 11490/11490 [00:28<00:00, 404.60 examples/s]
[NeMo W 2023-10-31 08:06:26 nemo_logging:349] /home/bhsueh/.local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:2436: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
      warnings.warn(
    
Replaced 675 modules to quantized modules
torch.distributed not initialized, assuming single world_size.
torch.distributed not initialized, assuming single world_size.
torch.distributed not initialized, assuming single world_size.
torch.distributed not initialized, assuming single world_size.
torch.distributed not initialized, assuming single world_size.
torch.distributed not initialized, assuming single world_size.
bhsueh@c45d72399ef9:/home/scratch.bhsueh_sw_1/workspace/TensorRT-LLM/tllm/examples/llama$ 
```

**Comment by 77h2l** [comment]
> @HaoWuSR I’ve tried to reproduce on H100 but I have not been able to do it so far. The followings are my scripts:
> 
> ```shell
> cd examples/llama/
> cuda_version=$(nvcc --version | grep 'release' | awk '{print $6}' | awk -F'[V.]' '{print $2$3}')
> python_version=$(python3 --version 2>&1 | awk '{print $2}' | awk -F. '{print $1$2}')
> wget https://developer.nvidia.com/downloads/assets/cuda/files/nvidia-ammo/nvidia_ammo-0.3.0.tar.gz
> pip install nvidia_ammo-0.3.0/nvidia_ammo-0.3.0+cu$cuda_version-cp$python_version-cp$python_version-linux_x86_64.whl
> cd ../../examples/quantization/
> pip install -r requirements.txt 
> cd -
> python3 quantize.py --model_dir /home/scratch.trt_llm_data/llm-models/llama-models/llama-7b-hf/ --dtype float16 --qformat fp8 --export_path /tmp --calib_size 512
> ```
> 
> and the results of my side
> 
> ```
> bhsueh@c45d72399ef9:/home/scratch.bhsueh_sw_1/workspace/TensorRT-LLM/tllm/examples/llama$ python3 quantize.py --model_dir /home/scratch.trt_llm_data/llm-models/llama-models/llama-7b-hf/ --dtype float16 --qformat fp8 --export_path /tmp --calib_size 512
> [NeMo W 2023-10-31 08:03:13 nemo_logging:349] /home/bhsueh/.local/lib/python3.10/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
>       warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
>     
> Using pad_token, but it is not set yet.
> WARNING: Logging before flag parsing goes to stderr.
> W1031 08:03:15.066031 139757021590656 modeling.py:706] The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
> Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████| 2/2 [01:04<00:00, 32.09s/it]
> Loading calibration dataset
> Downloading builder script: 100%|██████████████████████████████████████████████████████| 8.33k/8.33k [00:00<00:00, 23.1MB/s]
> Downloading metadata: 100%|████████████████████████████████████████████████████████████| 9.88k/9.88k [00:00<00:00, 32.6MB/s]
> Downloading readme: 100%|██████████████████████████████████████████████████████████████| 15.1k/15.1k [00:00<00:00, 34.3MB/s]
> Downloading data: 100%|███████████████████████████████████████████████████████████████████| 159M/159M [00:01<00:00, 100MB/s]
> Downloading data: 100%|███████████████████████████████████████████████████████████████████| 376M/376M [00:02<00:00, 131MB/s]
> Downloading data: 46.4MB [00:00, 111MB/s]██████████████                                       | 2/5 [00:05<00:08,  2.99s/it]
> Downloading data: 2.43MB [00:00, 43.5MB/s]                                                                                  
> Downloading data: 2.11MB [00:00, 35.1MB/s]                                                                                  
> Downloading data files: 100%|█████████████████████████████████████████████████████████████████| 5/5 [00:07<00:00,  1.49s/it]
> Generating train split: 100%|██████████████████████████████████████████████| 287113/287113 [00:59<00:00, 4862.10 examples/s]
> Generating validation split: 100%|████████████████████████████████████████████| 13368/13368 [00:28<00:00, 467.39 examples/s]
> Generating test split: 100%|██████████████████████████████████████████████████| 11490/11490 [00:28<00:00, 404.60 examples/s]
> [NeMo W 2023-10-31 08:06:26 nemo_logging:349] /home/bhsueh/.local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:2436: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
>       warnings.warn(
>     
> Replaced 675 modules to quantized modules
> torch.distributed not initialized, assuming single world_size.
> torch.distributed not initialized, assuming single world_size.
> torch.distributed not initialized, assuming single world_size.
> torch.distributed not initialized, assuming single world_size.
> torch.distributed not initialized, assuming single world_size.
> torch.distributed not initialized, assuming single world_size.
> bhsueh@c45d72399ef9:/home/scratch.bhsueh_sw_1/workspace/TensorRT-LLM/tllm/examples/llama$ 
> ```

@byshiue how many memory cost when running this script, I am running on a single A10, and returns oom,here is my command: 
python3 quantize.py --model_dir ./llama-7b-hf/ --dtype float16 --qformat fp8 --export_path /tmp --calib_size 512 2>&1 | tee run.log

**Comment by byshiue** [comment]
> Replaced 675 modules to quantized modules

`calib_size 512` requires 76 GBs. You can use small size to reduce memory usage like `calib_size 1` but it may requires longer time to do calibration.

**Comment by HaoWuSR** [comment]
> @HaoWuSR I’ve tried to reproduce on H100 but I have not been able to do it so far. The followings are my scripts:
> 
> ```shell
> cd examples/llama/
> cuda_version=$(nvcc --version | grep 'release' | awk '{print $6}' | awk -F'[V.]' '{print $2$3}')
> python_version=$(python3 --version 2>&1 | awk '{print $2}' | awk -F. '{print $1$2}')
> wget https://developer.nvidia.com/downloads/assets/cuda/files/nvidia-ammo/nvidia_ammo-0.3.0.tar.gz
> pip install nvidia_ammo-0.3.0/nvidia_ammo-0.3.0+cu$cuda_version-cp$python_version-cp$python_version-linux_x86_64.whl
> cd ../../examples/quantization/
> pip install -r requirements.txt 
> cd -
> python3 quantize.py --model_dir /home/scratch.trt_llm_data/llm-models/llama-models/llama-7b-hf/ --dtype float16 --qformat fp8 --export_path /tmp --calib_size 512
> ```
> 
> and the results of my side
> 
> ```
> bhsueh@c45d72399ef9:/home/scratch.bhsueh_sw_1/workspace/TensorRT-LLM/tllm/examples/llama$ python3 quantize.py --model_dir /home/scratch.trt_llm_data/llm-models/llama-models/llama-7b-hf/ --dtype float16 --qformat fp8 --export_path /tmp --calib_size 512
> [NeMo W 2023-10-31 08:03:13 nemo_logging:349] /home/bhsueh/.local/lib/python3.10/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
>       warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
>     
> Using pad_token, but it is not set yet.
> WARNING: Logging before flag parsing goes to stderr.
> W1031 08:03:15.066031 139757021590656 modeling.py:706] The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
> Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████| 2/2 [01:04<00:00, 32.09s/it]
> Loading calibration dataset
> Downloading builder script: 100%|██████████████████████████████████████████████████████| 8.33k/8.33k [00:00<00:00, 23.1MB/s]
> Downloading metadata: 100%|████████████████████████████████████████████████████████████| 9.88k/9.88k [00:00<00:00, 32.6MB/s]
> Downloading readme: 100%|██████████████████████████████████████████████████████████████| 15.1k/15.1k [00:00<00:00, 34.3MB/s]
> Downloading data: 100%|███████████████████████████████████████████████████████████████████| 159M/159M [00:01<00:00, 100MB/s]
> Downloading data: 100%|███████████████████████████████████████████████████████████████████| 376M/376M [00:02<00:00, 131MB/s]
> Downloading data: 46.4MB [00:00, 111MB/s]██████████████                                       | 2/5 [00:05<00:08,  2.99s/it]
> Downloading data: 2.43MB [00:00, 43.5MB/s]                                                                                  
> Downloading data: 2.11MB [00:00, 35.1MB/s]                                                                                  
> Downloading data files: 100%|█████████████████████████████████████████████████████████████████| 5/5 [00:07<00:00,  1.49s/it]
> Generating train split: 100%|██████████████████████████████████████████████| 287113/287113 [00:59<00:00, 4862.10 examples/s]
> Generating validation split: 100%|████████████████████████████████████████████| 13368/13368 [00:28<00:00, 467.39 examples/s]
> Generating test split: 100%|██████████████████████████████████████████████████| 11490/11490 [00:28<00:00, 404.60 examples/s]
> [NeMo W 2023-10-31 08:06:26 nemo_logging:349] /home/bhsueh/.local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:2436: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
>       warnings.warn(
>     
> Replaced 675 modules to quantized modules
> torch.distributed not initialized, assuming single world_size.
> torch.distributed not initialized, assuming single world_size.
> torch.distributed not initialized, assuming single world_size.
> torch.distributed not initialized, assuming single world_size.
> torch.distributed not initialized, assuming single world_size.
> torch.distributed not initialized, assuming single world_size.
> bhsueh@c45d72399ef9:/home/scratch.bhsueh_sw_1/workspace/TensorRT-LLM/tllm/examples/llama$ 
> ```

I found that I can install ammo successfully. But the Nemo from 
```
cd ../../examples/quantization/
pip install -r requirements.txt
```
can't be installed. Maybe this is the key point. I am not sure I get the exact environment for all the thing though I have installed tensorRT-LLM and ammo already.

**Comment by 77h2l** [comment]
> python3 quantize.py --model_dir ./llama-7b-hf/ --dtype float16 --qformat fp8 --export_path /tmp --calib_size 512 2>&1 | tee run.log

seems not work. Even when I set the calib_size to 1, it will also cause oom, is there any offload ways? I am running on A10
python3 quantize.py --model_dir ./llama-7b-hf/ --dtype float16 --qformat fp8 --export_path ./tmp --calib_size 1

**Comment by byshiue** [comment]
> > python3 quantize.py --model_dir ./llama-7b-hf/ --dtype float16 --qformat fp8 --export_path /tmp --calib_size 512 2>&1 | tee run.log
> 
> seems not work. Even when I set the calib_size to 1, it will also cause oom, is there any offload ways? I am running on A10 python3 quantize.py --model_dir ./llama-7b-hf/ --dtype float16 --qformat fp8 --export_path ./tmp --calib_size 1

Can you share the full log?

**Comment by HaoWuSR** [comment]
> > > python3 quantize.py --model_dir ./llama-7b-hf/ --dtype float16 --qformat fp8 --export_path /tmp --calib_size 512 2>&1 | tee run.log
> > 
> > 
> > seems not work. Even when I set the calib_size to 1, it will also cause oom, is there any offload ways? I am running on A10 python3 quantize.py --model_dir ./llama-7b-hf/ --dtype float16 --qformat fp8 --export_path ./tmp --calib_size 1
> 
> Can you share the full log?
I have solved my problem. 
Including reinstalling the ammo, Nemo, and changing another docker image. 
Thanks for your time !

**Comment by 77h2l** [comment]
> > > python3 quantize.py --model_dir ./llama-7b-hf/ --dtype float16 --qformat fp8 --export_path /tmp --calib_size 512 2>&1 | tee run.log
> > 
> > 
> > seems not work. Even when I set the calib_size to 1, it will also cause oom, is there any offload ways? I am running on A10 python3 quantize.py --model_dir ./llama-7b-hf/ --dtype float16 --qformat fp8 --export_path ./tmp --calib_size 1
> 
> Can you share the full log?

ok, the full log is as follows:
[qnt.log](https://github.com/NVIDIA/TensorRT-LLM/files/13261491/qnt.log)
