### ISSUE TITLE
setup.py need tensorrt_llm/bindings path but not exists

### ISSUE THREAD

**Issue by dwahaa** [NVIDIA/TensorRT-LLM#2162]
### System Info

-CPU: aarch64

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I just install TensorRT-LLM from source, but when run python setup.py there is a error. Setup.py need bindings path like below, but the main branch of the git has no such path, what should I do?

```
def sanity_check():
    bindings_path = Path(
        __file__).resolve().parent / "tensorrt_llm" / "bindings"
    if not bindings_path.exists():
        raise ImportError(
            'The `bindings` module does not exist. Please check the package integrity. '
            'If you are attempting to use the pip development mode (editable installation), '
            'please execute `build_wheels.py` first, and then run `pip install -e .`.'
        )

```

### Expected behavior

fix this problem

### actual behavior

bugfix

### additional notes

release the v0.13.0 becase some dependency has changed to v0.13.0

**Comment by WGS-note** [comment]
@dwahaa Hi, may I ask how you resolved it?
