### ISSUE TITLE
Documentation links are dead

### ISSUE THREAD

**Issue by aikitoria** [NVIDIA/TensorRT-LLM#2173]
Since the last release was posted, all documentation links on the readme such as https://nvidia.github.io/TensorRT-LLM/quick-start-guide.html redirect to https://www.nvidia.com/en-us/ .

@byshiue

**Comment by lfr-0531** [comment]
Just checked, it works now. This may be caused by network issues. Can you try again?

**Comment by aikitoria** [comment]
Yes, looks like it has been fixed.
