### ISSUE TITLE
When will the batch_manager and executor of the cpp code be open sourced?

### ISSUE THREAD

**Issue by w066650** [NVIDIA/TensorRT-LLM#2174]
When will the batch_manager and executor of the cpp code be open sourced?

code:

TensorRT-LLM\cpp\tensorrt_llm\batch_manager\x86_64-linux-gnu
TensorRT-LLM\cpp\tensorrt_llm\executor\x86_64-linux-gnu

**Comment by lfr-0531** [comment]
We don't have a plan for now.
