### ISSUE TITLE
building tensorRT-llm, TensorRt issue

### ISSUE THREAD

**Issue by arjunanand13** [NVIDIA/TensorRT-LLM#218]
Out of all tensorrt-9.1.0.post12.dev4 only one wheel is downloading in colab , that is "TensorRT-9.1.0.4/python/tensorrt-9.1.0.post12.dev4-cp310-none-linux_x86_64.whl". But after downloading ,I'm facing this error while importing it
"ImportError                               Traceback (most recent call last)
[<ipython-input-5-8dfd087091e3>](https://localhost:8080/#) in <cell line: 1>()
----> 1 import tensorrt

[/usr/local/lib/python3.10/dist-packages/tensorrt/__init__.py](https://localhost:8080/#) in <module>
     69 del _libs_wheel_imported
     70 
---> 71 from .tensorrt import *
     72 
     73 __version__ = "9.1.0.post12.dev4"

ImportError: libnvinfer.so.9: cannot open shared object file: No such file or directory"

**Comment by byshiue** [comment]
Have you export the new TensorRT libs path into `LD_LIBRARY_PATH`?

**Comment by arjunanand13** [comment]
Yeah like this
!export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/content/TensorRT-9.1.0.4/lib

**Comment by arjunanand13** [comment]
Is their any sample documentation code

**Comment by juney-nvidia** [comment]
@arjunanand13  Hi, it is suggested to build TensorRT-LLM by following the installation guide with using the docker based workflow. Have you tried with the docker based build flow before?

June

**Comment by zmsunnyday** [comment]
Hi, I got the same issue when using vscode, but it worked well in shell without vscode. So weird.

**Comment by byshiue** [comment]
It might the environment setting of using vscode.

**Comment by nv-guomingz** [comment]
do u still have further issue or question now? If not, we'll close it soon.
