### ISSUE TITLE
Executor thread safe guarantee

### ISSUE THREAD

**Issue by akhoroshev** [NVIDIA/TensorRT-LLM#2185]
Are these [public](https://github.com/NVIDIA/TensorRT-LLM/blob/main/cpp/include/tensorrt_llm/executor/executor.h#L915) functions thread safe?

* enqueueRequest
* awaitResponses
* cancelRequest
* shutdown
* getLatestIterationStats
* getNumResponsesReady

What happens if you call cancelRequest on a request that has already been canceled (or completed) (calling awaitResponses at the same time).

**Comment by pcastonguay** [comment]
Calling `cancelRequest` with a `requestId` that already has already completed will return right away and a log message should get printed saying that the provided `requestId` has already terminated. Calling `cancelRequest` with a `requestId` that's in flight, and for which another thread is waiting for the responses using `awaitResponses` should cause `awaitResponses` to eventually return a response with `result.isFinal = true`.

**Comment by akhoroshev** [comment]
> Calling `cancelRequest` with a `requestId` that already has already completed will return right away and a log message should get printed saying that the provided `requestId` has already terminated. Calling `cancelRequest` with a `requestId` that's in flight, and for which another thread is waiting for the responses using `awaitResponses` should cause `awaitResponses` to eventually return a response with `result.isFinal = true`.

Thanks!

**Comment by binhtranmcs** [comment]
@pcastonguay same question, is `enqueueRequest` thread safe. What if I have 2 or more threads calling `enqueueRequest` concurrently?
