### ISSUE TITLE
--ulimit memlock=-1 --ulimit stack=67108864  Are these two parameters required to be set?

### ISSUE THREAD

**Issue by Midcc** [NVIDIA/TensorRT-LLM#219]
What would be the consequences if these two parameters are not set? Currently, I have not set them, and the program appears to freeze up when it runs.

![029cbf7dfa0946eaa72a9abc0cadb12c](https://github.com/NVIDIA/TensorRT-LLM/assets/41425444/9f93e676-1124-42e0-9b68-956aa6299c00)

![198fbe72a99b402aae071a4530ffe291](https://github.com/NVIDIA/TensorRT-LLM/assets/41425444/9ce10256-5e38-406d-af0a-d72a5f3e3b12)

Are these two parameters required to be set?

**Comment by jdemouth-nvidia** [comment]
Hi @Midcc ,

Which parameters are you talking about, please? It’s not very clear to me. 

Thanks,
Julien

**Comment by juney-nvidia** [comment]
@Midcc 
For the `--ulimit memlock=-1`, you can refer [here](https://github.com/NVIDIA/TensorRT-LLM/blob/1c4a0ee24cb0480c20a721c4bc6a77fc51644a22/README.md#troubleshooting) for some background. It is mainly for avoiding some potential NCCL issue.

**Comment by byshiue** [comment]
Close this bug because the issue is inactivated. Feel free to ask here if you still have question/issue, we will reopen the issue.
