### ISSUE TITLE
[bug] Executor api excludes endId from output

### ISSUE THREAD

**Issue by akhoroshev** [NVIDIA/TensorRT-LLM#2190]
I added `request.setEndId(endId);` to the [example](https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/cpp/executor/executorExampleBasic.cpp) and generation stopped.

But I don't see endId token in output. Executor api excludes it.

My version is https://github.com/NVIDIA/TensorRT-LLM/tree/5fa9436e17c2f9aeace070f49aa645d2577f676b

**Comment by Funatiq** [comment]
This is expected behavior. The generation will stop at the `endId`, but not include it in the output.

**Comment by akhoroshev** [comment]
@Funatiq 
How to distinguish that the finish reason is endId and not the generation limit (maxTokens)

**Comment by Funatiq** [comment]
We have recently added a field for the finish reason to the executor results. It currently only supports sampling. We will add support for beam search soon.

**Comment by akhoroshev** [comment]
@Funatiq I am need for last logProbs for endId token. How to get to them?
