### ISSUE TITLE
Failed to run convert_checkpoint.py for Qwen2-7B using TRTLLM  0.12.0.dev2024080600

### ISSUE THREAD

**Issue by sdecoder** [NVIDIA/TensorRT-LLM#2198]
1. Version info:
image tag of triton server:  24.08-trtllm-python-py3
the version of trt-llm: 0.12.0.dev2024080600
2. LLM spec: Qwen2-7B, downloaded from: https://huggingface.co/Qwen/Qwen2-7B
3. command from here: https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/qwen
/tensorrtllm_backend/examples/qwen# python3 /tensorrtllm_backend/examples/qwen/convert_checkpoint.py 	--model_dir /qwen2-7b 	--output_dir /engines/tllm_checkpoint_8gpu 	--dtype float16 	--tp_size 8
4. Hardware spec: L20 X 8, this is why I specified the tp_size = 8, for I want to fully utilize the 8 gpu;
5. error output:

Traceback (most recent call last):
  File "/tensorrtllm_backend/examples/qwen/convert_checkpoint.py", line 308, in <module>
	main()
  File "/tensorrtllm_backend/examples/qwen/convert_checkpoint.py", line 300, in main
	convert_and_save_hf(args)
  File "/tensorrtllm_backend/examples/qwen/convert_checkpoint.py", line 256, in convert_and_save_hf
	execute(args.workers, [convert_and_save_rank] * world_size, args)
  File "/tensorrtllm_backend/examples/qwen/convert_checkpoint.py", line 263, in execute
	f(args, rank)
  File "/tensorrtllm_backend/examples/qwen/convert_checkpoint.py", line 246, in convert_and_save_rank
	qwen = QWenForCausalLM.from_hugging_face(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/qwen/model.py", line 315, in from_hugging_face
	weights = load_weights_from_hf_model(hf_model, config)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/qwen/convert.py", line 1221, in load_weights_from_hf_model
	weights = convert_hf_qwen(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/qwen/convert.py", line 756, in convert_hf_qwen
	k_bias = dup_kv_weight(k_bias, num_key_value_heads,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/qwen/convert.py", line 526, in dup_kv_weight
	v.shape[1])
IndexError: tuple index out of range

However, if I use tp_size=4, the error is gone. 
Can anyone explain why I can't use tp_size=8 here?

Thank you.

**Comment by jershi425** [comment]
Hi @sdecoder , thank you for the feedback. Due to the TP split logic, currently we don't support the situation when `num_attention_heads % tp_size != 0`. Since qwen2-7B's `num_attention_heads` is 28, I would recommend using TP=4 or TP=2.

**Comment by sdecoder** [comment]
> Hi [@sdecoder](https://github.com/sdecoder) , thank you for the feedback. Due to the TP split logic, currently we don't support the situation when `num_attention_heads % tp_size != 0`. Since qwen2-7B's `num_attention_heads` is 28, I would recommend using TP=4 or TP=2.

Sure, thank you so much for your answer. 
However, could you please give me a hint if I want to fully leverage all my 8 L20 GPUs?
For example, if I use TP=4, what data-parallelism size is recommended in such case?

Thanks again for any hint here.

**Comment by jershi425** [comment]
Hi @sdecoder, since you have 8 GPUs, I would recommend you trying a bigger Qwen2 model like the 72B one for better quality. But if you just want to maximize the throughput with the 7B model, I think the best way is to deploy multiple instances to avoid extra TP communication. You can refer to [this doc](https://github.com/triton-inference-server/tensorrtllm_backend/blob/main/docs/llama_multi_instance.md) for multi instance deployment guide.

**Comment by sdecoder** [comment]
> Hi [@sdecoder](https://github.com/sdecoder), since you have 8 GPUs, I would recommend you trying a bigger Qwen2 model like the 72B one for better quality. But if you just want to maximize the throughput with the 7B model, I think the best way is to deploy multiple instances to avoid extra TP communication. You can refer to [this doc](https://github.com/triton-inference-server/tensorrtllm_backend/blob/main/docs/llama_multi_instance.md) for multi instance deployment guide.

I am going to exam the doc you provided. 
Thank you so much for your help! 👍
