### ISSUE TITLE
Qwen-VL-Chat has an error

### ISSUE THREAD

**Issue by xiangxinhello** [NVIDIA/TensorRT-LLM#2206]
### System Info

A100-PCIe-40GB
Tensorrt-LLM-verison:0.12.0

### Who can help?

@sunnyqgg 

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [x] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

The effects of using trt-llm-0.12.0 with fp16 and fp32 precision are significantly different from those of Qwen-VL found at https://github.com/QwenLM/Qwen-VL.
trt-llm-0.12.0 with fp16：
![Image](https://github.com/user-attachments/assets/6d269465-b7d4-43ac-9ec0-6f7a1c9c19eb)

trt-llm-0.12.0 with fp32：

![Image](https://github.com/user-attachments/assets/41775720-287e-4fe3-8b7d-d53189345988)

https://github.com/QwenLM/Qwen-VL:

![Image](https://github.com/user-attachments/assets/37e51288-1369-457c-85cc-2680b28f0014)

### Expected behavior

The reasoning results should be consistent with https://github.com/QwenLM/Qwen-VL.

### actual behavior

tensorrt-llm not support

### additional notes

no

**Comment by xiangxinhello** [comment]
Hi, @lfr-0531 , can you help me solve this problem? thanks！

**Comment by lfr-0531** [comment]
Similar issue to https://github.com/NVIDIA/TensorRT-LLM/issues/2241
