### ISSUE TITLE
Can we directly pass the input_embeds to the `generate` function

### ISSUE THREAD

**Issue by OswaldoBornemann** [NVIDIA/TensorRT-LLM#2211]
Can we directly pass the input_embeds to the `generate` function? Just like the following used in the pytorch transformers

```
generated_ids = self.model.generate(
            inputs_embeds=input_token_embedding,
            do_sample=True,
            max_length=max_length,
            pad_token_id=self.pad_token_id,
            eos_token_id=self.eos_target_id,
            temperature=temperature,
            top_k=top_k,
            top_p=top_p,
            repetition_penalty=repeat_penalty,
            min_new_tokens=50,
        )
```

**Comment by lfr-0531** [comment]
Please refer to https://github.com/NVIDIA/TensorRT-LLM/issues/2104#issuecomment-2330427204.

> input_embeds can not be accessed directly.  prompt_table should be used to pass visual features as input.
The specific position of visual features within prompt changes from one model to another.

**Comment by OswaldoBornemann** [comment]
@lfr-0531 Yeah I got that. However, in my case, I used `Llama` and my input is `input_embeds` instead of `tokens`. Is there any solution or hack way?

**Comment by lfr-0531** [comment]
IIUC, you want to remove the `vocab_embedding` and directly input the `hidden_states` to the decoder layers, right? TensorRT-LLM can not support it now. To support it, you need to make some changes to both model and runtime parts.
- Model part: remove the `vocab_embedding` and change the input tensor shape
- Runtime part: set the correct input tensor

**Comment by OswaldoBornemann** [comment]
@lfr-0531 Yeah, I just found that the `transformers` support that `input_embeds` in the `model.generate` function. Then I wonder whether TensorRT-LLM supports it or not. But for now, It seems the answer is not.
