### ISSUE TITLE
Build engine for a different architecture than the current device

### ISSUE THREAD

**Issue by yunfeng-scale** [NVIDIA/TensorRT-LLM#222]
Hi, I'm getting error `[TensorRT-LLM][ERROR] 6: The engine plan file is generated on an incompatible device, expecting compute 8.6 got compute 8.0, please rebuild.` supposedly due to that I built the engine from A100 and try to use on A10. Is it possible to provide the capability to build a engine from a device with different CUDA compatibility?

**Comment by juney-nvidia** [comment]
@yunfeng-scale 

Unfortunately no. 
It is the current by-design choice for TensorRT since TensorRT will do the offline tuning/running to select the best combination of kernels for the GPU on which the TensorRT engine is being built. 

Here are some background docs:
- https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#build_engine_c
- https://github.com/NVIDIA/TensorRT/issues/1562#issuecomment-983281368

Thanks
June

**Comment by yunfeng-scale** [comment]
Okay thanks. feel free to close the issue

**Comment by byshiue** [comment]
@yunfeng-scale It looks TensorRT supports hardware compatibility after Ampere and TRT 8.6. You can refer this example 
https://github.com/NVIDIA/trt-samples-for-hackathon-cn/tree/master/cookbook/08-Advance/HardwareCompatibility.

**Comment by hchoi-moveworks** [comment]
@juney-nvidia 
@byshiue 

Does TRT LLM engine building work across different GPU devices if the compute version and GPU architecture is the same?

For example NVIDIA T4 and RTX8000 both has Turing architecture and has 7.5 compute versions

Can TRT engine built on T4 be used on RTX 8000 and vice versa?

**Comment by yunfeng-scale** [comment]
looks like `hardware_compatibility_level` can be set in config used for `build_serialized_network()`, but performance is less ideal

**Comment by yunfeng-scale** [comment]
> Can TRT engine built on T4 be used on RTX 8000 and vice versa?

based on above information only Ampere (8.0+) and later architectures are supported, so probably not Turing

**Comment by jdemouth-nvidia** [comment]
I think you are correct. Let me add @ncomly-nvidia our Product Manager for TensorRT (and TensorRT-LLM) :)

**Comment by yunfeng-scale** [comment]
> @yunfeng-scale It looks TensorRT supports hardware compatibility after Ampere and TRT 8.6. You can refer this example https://github.com/NVIDIA/trt-samples-for-hackathon-cn/tree/master/cookbook/08-Advance/HardwareCompatibility.

although there's some performance loss, people may still want to do this? possible to add this feature and add some warning messages?

**Comment by xiaoFine** [comment]
![image](https://github.com/user-attachments/assets/7a11c396-556d-4f3a-ab53-2fbd69bdc705)
same error for me
just find A10 has higher CC than A100

**Comment by ShuaiShao93** [comment]
Any updates? This feature is useful even if there is performance loss. For example, we can use a cheaper GPU just for running tests.
