### ISSUE TITLE
nccl ops from TRT-LLM

### ISSUE THREAD

**Issue by apbose** [NVIDIA/TensorRT-LLM#2220]
Hi, I have a use case in which I would like to use nccl ops plugin from TRT-LLM in my project. I see that there is a code snippet in `tensorrt_llm/plugin/plugin.py ` which loads the `"libnvinfer_plugin_tensorrt_llm.so"` file, and also this shared lib gets created when I do python scripts/build_wheel.py  in the `tensorrt_llm/lib`  folder. I was wondering that say if I do` import tensorrt_llm` , where should I get access to the shared library? Is it shipped with the releases, so that I can directly do _load_plugin_lib()  and use it in my python code?

**Comment by apbose** [comment]
When I do something like 
```
try:
    ctypes.CDLL("/root/.pyenv/versions/3.10.14/lib/python3.10/site-packages/tensorrt_llm/libs/libnvinfer_plugin_tensorrt_llm.so")
    print("plugin loaded sucessfully####")
except OSError as e:
    print(f"unsuccessful load : {e}")
logger = trt.Logger(trt.Logger.VERBOSE)
trt.init_libnvinfer_plugins(logger, '')
plugin_registry = trt.get_plugin_registry()
for plugin_creator in plugin_registry.plugin_creator_list:
    print(f"Plugin Name: {plugin_creator.name}, Namespace: {plugin_creator.plugin_namespace}, Version: {plugin_creator.plugin_version}")
```
It does not print the TRT-LLM plugins. But  `nm -D /root/.pyenv/versions/3.10.14/lib/python3.10/site-packages/tensorrt_llm/libs/libnvinfer_plugin_tensorrt_llm.so| grep PluginCreator` it shows me the plugin symbols. Why is it not getting loaded then?

**Comment by litaotju** [comment]
@apbose 
This is not the primary way to use TRT-LLM.  The plugin was created with intention to be used in TRT-LLM runtime in mind.

Though, you could reference these lines on how plugins can be intialized
.
https://github.com/NVIDIA/TensorRT-LLM/blob/main/tensorrt_llm/plugin/plugin.py#L54C1-L55C1\

        assert handle.initTrtLlmPlugins(
