### ISSUE TITLE
whisper-medium decoder Compile blocking

### ISSUE THREAD

**Issue by skyCreateXian** [NVIDIA/TensorRT-LLM#2227]
### System Info

GPU： L20
Tensorrt-llm：v0.11.0
model：https://hf-mirror.com/openai/whisper-medium/tree/main

### Who can help?

@Tracin 
INT8 weight quantization Whisper decoder model compilation blocking, FP16 normal

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1、donwload whisper-medium https://hf-mirror.com/openai/whisper-medium/tree/main
2、convert_from_distil_whisper.py insert in 60 lines 
    model = model.half()  # compatible with openai's checkpoint
3、whisper huggingface convert pytorch
python3 distil_whisper/convert_from_distil_whisper.py \
    --model_name whisper-medium \
    --output_name medium
4、build whisper encoder and decoder
`
### pip install -r requirements.txt
set -x 
set -e

INFERENCE_PRECISION=float16
WEIGHT_ONLY_PRECISION=int8
MAX_BEAM_WIDTH=4
MAX_BATCH_SIZE=8
checkpoint_dir=whisper_medium_weights_${WEIGHT_ONLY_PRECISION}
output_dir=whisper_medium_${WEIGHT_ONLY_PRECISION}

### Convert the medium model weights into TensorRT-LLM format.
python3 convert_checkpoint.py \
                --use_weight_only \
                --model_name medium \
                --output_dir $checkpoint_dir

trtllm-build  --checkpoint_dir ${checkpoint_dir}/encoder \
              --output_dir ${output_dir}/encoder \
              --paged_kv_cache disable \
              --moe_plugin disable \
              --enable_xqa disable \
              --use_custom_all_reduce disable \
              --max_batch_size ${MAX_BATCH_SIZE} \
              --gemm_plugin disable \
              --bert_attention_plugin ${INFERENCE_PRECISION} \
              --remove_input_padding disable \
              --max_input_len 1500
              
trtllm-build  --checkpoint_dir ${checkpoint_dir}/decoder \
              --output_dir ${output_dir}/decoder \
              --paged_kv_cache disable \
              --moe_plugin disable \
              --enable_xqa disable \
              --use_custom_all_reduce disable \
              --max_beam_width ${MAX_BEAM_WIDTH} \
              --max_batch_size ${MAX_BATCH_SIZE} \
              --max_seq_len 114 \
              --max_input_len 14 \
              --max_encoder_input_len 1500 \
              --gemm_plugin ${INFERENCE_PRECISION} \
              --bert_attention_plugin ${INFERENCE_PRECISION} \
              --gpt_attention_plugin ${INFERENCE_PRECISION} \
              --remove_input_padding disable
`
If dtype is float16, it can be compiled normally

The final log：
`
[09/14/2024-14:51:39] [TRT] [I] Total Scratch Memory: 297855744
[09/14/2024-14:51:39] [TRT] [I] [BlockAssignment] Started assigning block shifts. This will take 685 steps to complete.
[09/14/2024-14:51:39] [TRT] [I] [BlockAssignment] Algorithm ShiftNTopDown took 61.3872ms to assign 16 blocks to 685 nodes requiring 600113152 bytes.
[09/14/2024-14:51:39] [TRT] [I] Total Activation Memory: 600111616
[09/14/2024-14:51:39] [TRT] [I] Total Weights Memory: 617656320
[TensorRT-LLM][WARNING] Have not found any valid GEMM config for shape (m=0, n=3072, k=1024). Will try to use default or fail at runtime

`

### Expected behavior

decoder model Compile blocking

### actual behavior

Complete compilation

### additional notes

nothing

**Comment by yuekaizhang** [comment]
@skyCreateXian  Could you try the lateset release trt-llm version? Also, can official whisper-medium (rather then distill or huggingface version) work for int8 weight only quant on L20?
