### ISSUE TITLE
why do ouput include <|im_end|>

### ISSUE THREAD

**Issue by w066650** [NVIDIA/TensorRT-LLM#2228]
run:
python ../run.py --input_text "推荐一首刘德华的歌曲" --max_output_len 100 --tokenizer_dir /root/Qwen1.5-7B-sft --engine_dir trt_engines --stop_words "<|im_end|>"

result:
[TensorRT-LLM][INFO] Engine version 0.13.0.dev2024082000 found in the config file, assuming engine(s) built by new builder API.
[TensorRT-LLM][INFO] MPI size: 1, MPI local size: 1, rank: 0
[TensorRT-LLM][INFO] Engine version 0.13.0.dev2024082000 found in the config file, assuming engine(s) built by new builder API.
[TensorRT-LLM][INFO] Refreshed the MPI local session
[TensorRT-LLM][INFO] MPI size: 1, MPI local size: 1, rank: 0
[TensorRT-LLM][INFO] Rank 0 is using GPU 0
[TensorRT-LLM][INFO] TRTGptModel maxNumSequences: 64
[TensorRT-LLM][INFO] TRTGptModel maxBatchSize: 64
[TensorRT-LLM][INFO] TRTGptModel maxBeamWidth: 1
[TensorRT-LLM][INFO] TRTGptModel maxSequenceLen: 32768
[TensorRT-LLM][INFO] TRTGptModel maxDraftLen: 0
[TensorRT-LLM][INFO] TRTGptModel mMaxAttentionWindowSize: (32768) * 32
[TensorRT-LLM][INFO] TRTGptModel enableTrtOverlap: 0
[TensorRT-LLM][INFO] TRTGptModel normalizeLogProbs: 1
[TensorRT-LLM][INFO] TRTGptModel maxNumTokens: 32000
[TensorRT-LLM][INFO] TRTGptModel maxInputLen: 32000 = min(maxSequenceLen - 1, maxNumTokens) since context FMHA and usePackedInput are enabled
[TensorRT-LLM][INFO] TRTGptModel If model type is encoder, maxInputLen would be reset in trtEncoderModel to maxInputLen: min(maxSequenceLen, maxNumTokens).
[TensorRT-LLM][INFO] Capacity Scheduler Policy: GUARANTEED_NO_EVICT
[TensorRT-LLM][INFO] Context Chunking Scheduler Policy: None
[TensorRT-LLM][INFO] Loaded engine size: 14748 MiB
[TensorRT-LLM][INFO] [MemUsageChange] Allocated 2594.25 MiB for execution context memory.
[TensorRT-LLM][INFO] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 14743 (MiB)
[TensorRT-LLM][INFO] [MemUsageChange] Allocated 85.22 MB GPU memory for runtime buffers.
[TensorRT-LLM][INFO] [MemUsageChange] Allocated 221.48 MB GPU memory for decoder.
[TensorRT-LLM][INFO] Memory usage when calculating max tokens in paged kv cache: total: 39.39 GiB, available: 21.70 GiB
[TensorRT-LLM][INFO] Number of blocks in KV cache primary pool: 626
[TensorRT-LLM][INFO] Number of blocks in KV cache secondary pool: 0, onboard blocks to primary memory before reuse: true
[TensorRT-LLM][INFO] Max KV cache pages per sequence: 512
[TensorRT-LLM][INFO] Number of tokens per block: 64.
[TensorRT-LLM][INFO] [MemUsageChange] Allocated 19.56 GiB for max tokens in paged KV cache (40064).
[09/13/2024-20:31:05] [TRT-LLM] [I] Load engine takes: 15.98058032989502 sec
****************************************************
-----req: [[151645]]
Input [Text 0]: "<|im_start|>system
You are a helpful assistant.<|im_end|>
<|im_start|>user
推荐一首刘德华的歌曲<|im_end|>
<|im_start|>assistant
"
Output [Text 0 Beam 0]: "《忘情水》<|im_end|>"
[TensorRT-LLM][INFO] Refreshed the MPI local session

why output include <|im_end|>?

**Comment by jershi425** [comment]
Hi @w066650 , in `run.py` we do not automatically skip special tokens during decoding. If you want to skip them, you can pass `--skip_special_tokens=True` when calling `tokenzier.decode()` [here](https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/run.py#L225).
