### ISSUE TITLE
FP8 rowwise support possible for SM89?

### ISSUE THREAD

**Issue by aikitoria** [NVIDIA/TensorRT-LLM#2229]
Attempting to build an engine using fp8_rowwise fails on 4090 GPUs with the message:
`[TensorRT-LLM Error][CutlassFp8RowwiseGemmRunner][GEMM Dispatch] Arch unsupported for CUTLASS gated GEMM`. 

I've traced this message back to here: https://github.com/NVIDIA/TensorRT-LLM/blob/31ac30e928a2db795799fdcab6be446bfa3a3998/cpp/tensorrt_llm/kernels/cutlass_kernels/fp8_rowwise_gemm/fp8_rowwise_gemm_template.h#L346

Is there a particular reason fp8 rowwise requires SM90? All the other kernels seem to have fallbacks for SM89.

**Comment by gonggqing** [comment]
same error when try to build llama2 using --use_fp8_rowwise on RTX 4090
try

    python examples/llama/convert_checkpoint.py --model_dir /data/model/llama-2-13b-chat-hf-fp16 --output_dir /data/model/llama-2-13b-chat-hf-fp8-ckpt --use_fp8_rowwise --fp8_kv_cache --load_model_on_cpu
    
    trtllm-build --checkpoint_dir /data/model/llama-2-13b-chat-hf-fp8-ckpt
    	--gemm_plugin fp8 \
            --output_dir /data/trtllm_build/llama-2-13b-chat-hf-fp8-trtllm-build \
            --max_batch_size 6 \
            --max_input_len 4096 \
            --max_seq_len 5120 \
    	--max_num_tokens 24576 
got

    [TensorRT-LLM Error][CutlassFp8RowwiseGemmRunner][GEMM Dispatch] Arch unsupported for CUTLASS gated GEMM

**Comment by aikitoria** [comment]
It was actually implemented in https://github.com/NVIDIA/TensorRT-LLM/pull/2413
