### ISSUE TITLE
Smaller available space for paged KV cache compared with vLLM

### ISSUE THREAD

**Issue by yunfeng-scale** [NVIDIA/TensorRT-LLM#224]
Built an engine with
```
python /code/tensorrt_llm/examples/llama/build.py --model_dir /model_weights/llama-2-7b                 --dtype float16                 --remove_input_padding                 --use_gpt_attention_plugin float16                 --enable_context_fmha                 --use_gemm_plugin float16                 --output_dir /model_weights/llama-2-7b-trt-llm                 --max_batch_size 25                 --max_output_len 4096                 --use_inflight_batching                 --tokens_per_block 16
```
and use 0.95 for `kv_cache_free_gpu_mem_fraction`.

Running on an A10 with TRT-LLM Triton backend, I'm seeing the paged KV cache size to be 10718 tokens from logs
```
[TensorRT-LLM][INFO] Using 10718 tokens in paged KV cache.
```
Is `10718 tokens` actually `10718 blocks` since 10718 does not divide 16?
Using vLLM I'm getting GPU block of 8348 out of the box (0.9 free memory ratio), and block size is 16 by default.

**Comment by schetlur-nv** [comment]
Hey, thanks for the question. That is indeed the number of tokens calculated based on user provided-constaints, but it gets rounded up to the next multiple of block size during allocation in the KV cache. We will fix the log message to be more accurate.

**Comment by jdemouth-nvidia** [comment]
Hi @yunfeng-scale ,

Thanks for your question. As @schetlur-nv explained, that's indeed the number of tokens. However, we are wondering why the difference between TensorRT-LLM and vLLM is that large. The weights should occupy around 14GB so we think there must be space for TensorRT-LLM to allocate a bigger KV cache. Do you have the log that was produced by TensorRT-LLM during the compilation, please? If not, we'll generate one ourselves.

Thanks,
Julien

**Comment by kaiyux** [comment]
Hi @yunfeng-scale , we pushed an update to the [main](https://github.com/NVIDIA/TensorRT-LLM/tree/main) branch, the log messages on KV cache are more accurate now. Feel free to let us know if there are further questions, thank you.

**Comment by yunfeng-scale** [comment]
> Hi @yunfeng-scale ,
> 
> Thanks for your question. As @schetlur-nv explained, that's indeed the number of tokens. However, we are wondering why the difference between TensorRT-LLM and vLLM is that large. The weights should occupy around 14GB so we think there must be space for TensorRT-LLM to allocate a bigger KV cache. Do you have the log that was produced by TensorRT-LLM during the compilation, please? If not, we'll generate one ourselves.
> 
> Thanks, Julien

Sorry I can't reproduce the numbers with vLLM and 7b model. Tried again today and I'm getting 868 blocks on vLLM and that's 13888 tokens. That's still larger that TRT-LLM. It would be nice to match the size of kv cache

**Comment by schetlur-nv** [comment]
Hey @yunfeng-scale can you confirm if you still see this issue? We have made several updates to optimize memory savings in the past month or so.

**Comment by schetlur-nv** [comment]
@yunfeng-scale I will close this issue now. Please feel free to leave a comment or open a new issue if you have more questions.

**Comment by achartier** [comment]
@yunfeng-scale We were able to reproduce your numbers but found they are likely due to different default values for the number of input tokens. Using the following values to build the TRT-LLM engine would match the vLLM default values:
`--max_batch_size 256 --max_num_tokens 2048`

With that engine, TRT-LLM is able to allocate a larger KV cache size.
