### ISSUE TITLE
Linear increase in latency with batch size

### ISSUE THREAD

**Issue by mkserge** [NVIDIA/TensorRT-LLM#2240]
Hello,

I am running some latency benchmarks using TensorRT-LLM on a Mistral 7B Instruct v0.3 model. My hope was that at small batch sizes the overall inference latency should not be impacted as much, so I am trying to shorted output length of the model and parallelize inference through batching instead. However, I am observing the opposite -- the latency increases linearly with the batch size, especially at smaller batch sizes.

Below is the average runtime of 100 runs (after warmup) as a function of batch size for different input lengths and fixed output length of 2 tokens.

/![Image](https://github.com/user-attachments/assets/99be1a43-73b1-4caf-a091-a9312c845064)

Any intuition if I am doing something wrong here in conversion/profiling? My steps are following

* I simply pulled the latest Mistral 7B Instruct v0.3 checkpoint from HF [here](https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.3/tree/main), and (inside the `nvidia/cuda:12.5.1-devel-ubuntu22.04` docker image) converted it with 
```
cd /tensorrt-llm/examples/llama
python3 convert_checkpoint.py \
    --model_dir /mistral-models/mistral-7b-instruct-v0.3-hf \
    --output_dir /mistral-models/mistral-7b-instruct-v0.3-trt
```

* Then built the engine with
```
trtllm-build \
  --checkpoint_dir /mistral-models/mistral-7b-instruct-v0.3-trt \
  --output_dir /mistral-models/mistral-7b-instruct-v0.3-trt-engines/fp16/1-gpu/ \
  --gemm_plugin auto \
  --max_input_len 1024
```

* For benchmarking I use the [run script](https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/run.py) with some slight modifications (for logging and generating a batch by appending `input_ids` batch_size times [here](https://github.com/NVIDIA/TensorRT-LLM/blob/a65dba7aaf7e2d8bb0120eea8f8f04deff145d6a/examples/run.py#L128C17-L128C32) ). I am using the CPP runtime. Example run
```
# Input length = 64, output length = 2
python3 ../run.py \
	--tokenizer_dir /mistral-models/mistral-7b-instruct-v0.3-hf \
	--engine_dir /mistral-models/mistral-7b-instruct-v0.3-trt-engines/fp16/1-gpu \
	--max_input_length 1024 \
	--max_output_len 2 \
	--max_attention_window_size 1024 \
	--run_profiling \
	--input_text "(CNN) -- Beef from Brazil is on Iranian dinner tables. An Iranian-built hospital treats patients near Bolivia's capital. Iranian-funded factories dot the Venezuelan countryside. Iran has forged hundreds of agreements with Latin American nations and pledged billions of"
```
I do this for varying `input_text` inputs to get the plot above.

Any insights would be appreciated.

Hardware: A100 GPU (`p4d.24xlarge` on AWS), using a single GPU.
TensorRT-LLM version: 0.14.0.dev2024091000
Conversion/benchmarking run in `nvidia/cuda:12.5.1-devel-ubuntu22.04` docker image following the setup described [here](https://nvidia.github.io/TensorRT-LLM/installation/linux.html)

Here's also the output of the profiling script if it's helpful
```
[TensorRT-LLM] TensorRT-LLM version: 0.14.0.dev2024091000
[TensorRT-LLM][INFO] Engine version 0.14.0.dev2024091000 found in the config file, assuming engine(s) built by new builder API.
[TensorRT-LLM][INFO] MPI size: 1, MPI local size: 1, rank: 0
[TensorRT-LLM][INFO] Engine version 0.14.0.dev2024091000 found in the config file, assuming engine(s) built by new builder API.
[TensorRT-LLM][INFO] Refreshed the MPI local session
[TensorRT-LLM][INFO] MPI size: 1, MPI local size: 1, rank: 0
[TensorRT-LLM][INFO] Rank 0 is using GPU 0
[TensorRT-LLM][INFO] TRTGptModel maxNumSequences: 256
[TensorRT-LLM][INFO] TRTGptModel maxBatchSize: 256
[TensorRT-LLM][INFO] TRTGptModel maxBeamWidth: 1
[TensorRT-LLM][INFO] TRTGptModel maxSequenceLen: 32768
[TensorRT-LLM][INFO] TRTGptModel maxDraftLen: 0
[TensorRT-LLM][INFO] TRTGptModel mMaxAttentionWindowSize: (1024) * 32
[TensorRT-LLM][INFO] TRTGptModel enableTrtOverlap: 0
[TensorRT-LLM][INFO] TRTGptModel normalizeLogProbs: 1
[TensorRT-LLM][INFO] TRTGptModel maxNumTokens: 8192
[TensorRT-LLM][INFO] TRTGptModel maxInputLen: 8192 = min(maxSequenceLen - 1, maxNumTokens) since context FMHA and usePackedInput are enabled
[TensorRT-LLM][INFO] TRTGptModel If model type is encoder, maxInputLen would be reset in trtEncoderModel to maxInputLen: min(maxSequenceLen, maxNumTokens).
[TensorRT-LLM][INFO] Capacity Scheduler Policy: GUARANTEED_NO_EVICT
[TensorRT-LLM][INFO] Context Chunking Scheduler Policy: None
[TensorRT-LLM][INFO] Loaded engine size: 13847 MiB
[TensorRT-LLM][INFO] [MemUsageChange] Allocated 802.00 MiB for execution context memory.
[TensorRT-LLM][INFO] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 13840 (MiB)
[TensorRT-LLM][INFO] [MemUsageChange] Allocated 131.05 MB GPU memory for runtime buffers.
[TensorRT-LLM][INFO] [MemUsageChange] Allocated 304.06 MB GPU memory for decoder.
[TensorRT-LLM][INFO] Memory usage when calculating max tokens in paged kv cache: total: 39.39 GiB, available: 24.21 GiB
[TensorRT-LLM][INFO] Number of blocks in KV cache primary pool: 2789
[TensorRT-LLM][INFO] Number of blocks in KV cache secondary pool: 0, onboard blocks to primary memory before reuse: true
[TensorRT-LLM][INFO] Max KV cache pages per sequence: 16
[TensorRT-LLM][INFO] Number of tokens per block: 64.
[TensorRT-LLM][INFO] [MemUsageChange] Allocated 21.79 GiB for max tokens in paged KV cache (178496).
[09/19/2024-01:33:58] [TRT-LLM] [I] Load engine takes: 13.982300043106079 sec
Sergey: Batch Input Lengths: [256]
Warming up for 10 iterations...
batch_size: 1, avg latency of 100 iterations: 0.03277613162994385 sec
```

Edit: I am happy to provide exact steps/scripts to reproduce if the above is not sufficient.

**Comment by lfr-0531** [comment]
We recommand to use our proposed benchmark to evaluate the performance: https://github.com/NVIDIA/TensorRT-LLM/tree/main/benchmarks/cpp#emulated-static-batching

But as the batch size increases, the latency also increases, which seems to make sense.

**Comment by mkserge** [comment]
I will try out the recommended benchmarking tool and report back, thank you.

> But as the batch size increases, the latency also increases, which seems to make sense.

But we don't really expect time-to-first-token to double going from batch size 1 to batch size 2 on an input length of 128 tokens, no? (on a A100 GPU) That seems to go against the idea of opportunistic batching and implies that executing the queries sequentially is almost the same as done through batching.
