### ISSUE TITLE
Does tensorrt llm support llama3.1 sequence classification?

### ISSUE THREAD

**Issue by fan-niu** [NVIDIA/TensorRT-LLM#2242]
@byshiue @ncomly-nvidia  I need to use llama3.1 sequence classification based on tensorrtllm. Is this currently supported? If I modify the code to add this feature, will there be any obstacles that prevent me from adding this feature? Looking forward to reply, thanks

**Comment by lfr-0531** [comment]
Do you mean you want to use the llama3.1 as a backbone and add a classifier for sequence classification task?

**Comment by fan-niu** [comment]
> Do you mean you want to use the llama3.1 as a backbone and add a classifier for sequence classification task?

@lfr-0531 Thank you for your reply. You are right. I am using the llama3.1-8b regression model trained by LlamaForSequenceClassification of transformers, https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/modeling_llama.py #L1332

I have some questions and would like your help. Does tensorrtllm support this usage? If it is not currently supported, how can I add it so that it can be used normally? If tensorrtllm_backend is used to start the service, will the ifb code have any impact on adding this feature and make it impossible to add this feature?

**Comment by lfr-0531** [comment]
TensorRT-LLM cannot directly support it, and you need to make some changes to the llama model in TensorRT-LLM, change the lm_head to the score layer in LlamaForSequenceClassification: https://github.com/NVIDIA/TensorRT-LLM/blob/a65dba7aaf7e2d8bb0120eea8f8f04deff145d6a/tensorrt_llm/models/llama/model.py#L272

Then you also need to change the corresponding convert checkpoint part for llama model and the runtime.

If you want to support this model, I recommand to use the python runtime first to make sure your changes work well. But for IFB support, I think you need to make some change to the batch manager, which is hard since it is not open sourced.

**Comment by fan-niu** [comment]
@lfr-0531 Thank you for your help. I have changed the code according to your method, but I encountered a problem because the input shapes of tensorrt are all variable types, such as the modified lm_head (-1, 1)   (num_labels=1). What should I do with these lines of code https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/modeling_llama.py#L1384-L1402 to translated into the forward code supported in DecoderModelForCausalLM.forward()?

Another question, if ifb is not used when deploying this feature in tensorrtllm_backend, can this feature serve normally? Thanks a lot.

**Comment by lfr-0531** [comment]
> What should I do with these lines of code https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/modeling_llama.py#L1384-L1402 to translated into the forward code supported in DecoderModelForCausalLM.forward()?

These codes can be viewed as the post-process, and you can add it to the runtime part.

> Another question, if ifb is not used when deploying this feature in tensorrtllm_backend, can this feature serve normally? Thanks a lot.

Yes, the backend can support different type of models: https://github.com/triton-inference-server/tensorrtllm_backend/tree/main#prepare-the-model-repository

**Comment by fan-niu** [comment]
@lfr-0531 Thanks so much, I will try to add this feature, thank you

**Comment by lfr-0531** [comment]
Closing this issue, feel free to reopen it if there are any questions.

**Comment by fan-niu** [comment]
> Closing this issue, feel free to reopen it if there are any questions.

@lfr-0531 Hello, I have finished converting the model stage code, but when building the engine stage code, I have been trying to convert the following two lines of pytorch code to tensorrtllm supported code but have been unsuccessful. Can you help me check what's wrong with the code?  Can you reopen is issue ? Thanks

pytorch:
```
batch_size = input_ids.size()[0]
sequence_lengths = torch.eq(input_ids, self.config.pad_token_id).int().argmax(-1) - 1
new_logits = logits[torch.arange(batch_size, device=logits.device), sequence_lengths]
```

tensorrtllm:
```
pad_value = constant_to_tensor_(self.config.pad_token_id)                                     
pad_tensor = expand(pad_value, input_ids.shape)                                               
sequence_mask = cast((input_ids == pad_tensor), dtype=input_ids.dtype)
sequence_lengths = argmax(sequence_mask, dim=1) - 1                                           
batch_indices = arange(batch_size)  # [batch_size]
batch_indices = cast(batch_indices, dtype=input_ids.dtype)
gather_indices = stack([batch_indices, sequence_lengths], axis=1)  
new_logits = gather_nd(lm_logits, gather_indices)
```

**Comment by fan-niu** [comment]
@lfr-0531 Can you help look into this issue? Thank you so much

**Comment by lfr-0531** [comment]
Sorry for the late response.

I recommand to add these calculations to the runtime part, then you can directly use the torch code for implementation.

If you really want to add to the model part, for the expand op, you need to unsqueeze the input tensor. You can refer to https://github.com/NVIDIA/TensorRT-LLM/blob/e15337275966ee9dea22aba8a6dba138354f6027/tensorrt_llm/layers/attention.py#L61-L62

**Comment by fan-niu** [comment]
@lfr-0531 thanks for your reply, If I have any questions, I will come back to ask you. Thank you.

**Comment by ShuaiShao93** [comment]
We also want this, is it possible to add this feature?
