### ISSUE TITLE
Question regarding Executor(BufferView, ...) constructor

### ISSUE THREAD

**Issue by muscowite** [NVIDIA/TensorRT-LLM#2252]
Hi everyone, I have a question regarding `Executer(BufferView engineBuffer,...)` constructor -- could you please confirm that my code should be responsible for the correct lifetime of the object I pass into the constructor? Or is it being copied somewhere inside the constructor? Thanks in advance

**Comment by lfr-0531** [comment]
@Funatiq could you help take a look at this question?

**Comment by Funatiq** [comment]
Hi @muscowite !
The engine in deserialized in the constructor and the `engineBuffer` can be released after that.
