### ISSUE TITLE
CUDA 12.2 and would like to know the highest version？

### ISSUE THREAD

**Issue by GuangyanZhang** [NVIDIA/TensorRT-LLM#2256]
**Description**
I am using CUDA 12.2 and would like to know the highest version of TensorRT-LLM that I can install. Can you please provide information on compatibility?

**My Environment:**
- CUDA Version: 12.2
- TensorRT-LLM Version (if any): [your current version, if applicable]

* official installation documentatio: https://nvidia.github.io/TensorRT-LLM/installation/linux.html , "But here it only shows CUDA 12.5, not CUDA 12.2."

**Comment by Superjomn** [comment]
You can try installing the latest TensorRT-LLM, since CUDA 12.x keeps compatible.
