### ISSUE TITLE
built tensorrt_llm-0.14.0.dev2024092401-cp310-cp310-linux_aarch64.whl on Jetson AGX Orin Developer Kit 32gb

### ISSUE THREAD

**Issue by whitesscott** [NVIDIA/TensorRT-LLM#2266]
### System Info

Here is the environment in which  _tensorrt_llm-0.14.0.dev2024092401-cp310-cp310-linux_aarch64.whl_  was built.

**Now I've got a problem in that pynvml does not work much on Jetson. So if anyone has a tensorrt_llm profiler.py that's works on Jetson or is more conversant with and could modify it I'll be able to test this. If not I'll try to make a version of profiler.py that works without pynvml.**

If you would like a copy of the wheel let me know where to upload.

It would not build when I set  --extra-cmake-vars "ENABLE_MULTI_DEVICE=0" because of undefined references to ompi_mpi_* and MPI_* when linking to  libtensorrt_llm.so.  

Then tried with following command line. and computer os configuration.

export LD_LIBRARY_PATH=/usr/lib/aarch64-linux-gnu/openmpi/lib:$LD_LIBRARY_PATH

python3 ./scripts/build_wheel.py --cuda_architectures "native" \
--nccl_root "/usr/lib/aarch64-linux-gnu" \
--extra-cmake-vars "USE_CUDNN=1;USE_CUSPARSELT=1" \
--python_bindings 

- JetPack 6.1 Jetson Linux 36.4 Linux Kernel 5.15 and Ubuntu 22.04 based root file system. 
- CUDA 12.6 
- Python 3.10.12
- torch-2.4.0a0%2Bc469d14-cp310-cp310-linux_aarch64.whl  Pytorch compiled on Jetson 36.3 os with same versions cuda cudnn.
- nv-tensorrt-local-tegra-repo-ubuntu2204-10.4.0-cuda-12.6_1.0-1_arm64.deb
- cuDNN 9.4.0-1 
- libnccl2, libnccl-dev 23.4-1+cuda12.6 arm64
- Added these ubuntu packages libopenmpi-dev libopenmpi3 libcaf-openmpi-3 openmpi-bin openmpi-common 
- Editited build_wheel.py to change job_count=8

[tensorrt-llm-compilation.txt](https://github.com/user-attachments/files/17177442/tensorrt-llm-compilation.txt)
[python_packages.txt](https://github.com/user-attachments/files/17177443/python_packages.txt)

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

successful build_wheel.py on Nvidia Jetson Orin AGX Developer kit

[pynvml doesn't work on nvidia jetson ](https://forums.developer.nvidia.com/t/does-nvml-work-with-jetson/189608)

### Expected behavior

profiler.py will need to be modified to get tensorrt_llm operational on Jetson.

### actual behavior

import tensorrt_llm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/scott/.local/lib/python3.10/site-packages/tensorrt_llm/__init__.py", line 35, in <module>
    import tensorrt_llm.runtime as runtime
  File "/home/scott/.local/lib/python3.10/site-packages/tensorrt_llm/runtime/__init__.py", line 22, in <module>
    from .model_runner import ModelRunner
  File "/home/scott/.local/lib/python3.10/site-packages/tensorrt_llm/runtime/model_runner.py", line 30, in <module>
    from ..builder import Engine, EngineConfig, get_engine_version
  File "/home/scott/.local/lib/python3.10/site-packages/tensorrt_llm/builder.py", line 30, in <module>
    from .auto_parallel import auto_parallel
  File "/home/scott/.local/lib/python3.10/site-packages/tensorrt_llm/auto_parallel/__init__.py", line 1, in <module>
    from .auto_parallel import auto_parallel
  File "/home/scott/.local/lib/python3.10/site-packages/tensorrt_llm/auto_parallel/auto_parallel.py", line 14, in <module>
    from .config import AutoParallelConfig
  File "/home/scott/.local/lib/python3.10/site-packages/tensorrt_llm/auto_parallel/config.py", line 9, in <module>
    from .cluster_info import ClusterInfo, cluster_infos
  File "/home/scott/.local/lib/python3.10/site-packages/tensorrt_llm/auto_parallel/cluster_info.py", line 12, in <module>
    from tensorrt_llm.profiler import PyNVMLContext, _device_get_memory_info_fn
ImportError: cannot import name '_device_get_memory_info_fn' from 'tensorrt_llm.profiler' (/home/scott/.local/lib/python3.10/site-packages/tensorrt_llm/profiler.py)

### additional notes

import pynvml

print(pynvml.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pynvml' has no attribute '__version__'

**Comment by whitesscott** [comment]
There are two pynvml based packages.
 

1. pip install pynvml  that I uninstalled and kept the following one 
2. pip install nvidia-ml-py  that installs pynvml.py and is the correct package .

I'll work with Tensorrt_llm more tomorrow but with this _slightly modified_ **profiler.py** I got rid of the instant  errors.
[profiler.py.txt](https://github.com/user-attachments/files/17177840/profiler.py.txt)

**Comment by whitesscott** [comment]
If I can figure out the method to create the many cpp/tensorrt_llm/kernels/decoderMaskedMultiheadAttention/cubin/*.cubin.cpp and other cubin.cpp files for sm87 will do so to see if Tensorrt-LLM will work on Jetson Orin. 
 _If anyone would point me in the right direction I'll attempt this._

Tried branch dev-sm87-trt101 and 
https://github.com/sunnyqgg/TensorRT-LLM but it wouldn't build in my Jetson os configuration.

**Comment by whitesscott** [comment]
Will need sm87 modifications to *.cubin.cpp files.

**Comment by Fatemehkiasaveh** [comment]
@whitesscott 
Hi, can you please guide me on how to install tensorrt-llm 0.14 on jetson orin?

**Comment by whitesscott** [comment]
Hello. 14 ended not fully working.  But nvidia built a tensorrt_llm 12 wheel for jetson agx orin with Jetpack 6.1  in November 2024.    https://forums.developer.nvidia.com/t/tensorrt-llm-for-jetson/313227

Here are the installation directions https://github.com/NVIDIA/TensorRT-LLM/blob/v0.12.0-jetson/README4Jetson.md

Instead of building the wheel as directed in paragraph 1.3 line 5 "python3 scripts/build_wheel.py  ...)   you can download and then pip install these two wheels
wget https://pypi.jetson-ai-lab.dev/jp6/cu126/+f/686/ed9ebac0d6e0f/tensorrt_llm-0.12.0-cp310-cp310-linux_aarch64.whl#sha256=686ed9ebac0d6e0feec1086e8223cf4ebb9293b48a69abf660c505e07cb92d1a

wget https://pypi.jetson-ai-lab.dev/jp6/cu126/+f/976/6ddc53291b78b/auto_gptq-0.8.0.dev0+cu126-cp310-cp310-linux_aarch64.whl#sha256=9766ddc53291b78bef42a8a0778c725654fdf58a573c22947ac418663f9ddc9a

I was then able to build and run the example in paragraph 2 of the README4Jetson.md.  I've tried to build other tensorrt_llm engines of Huggingface.co models that I had previously downloaded and used; but have not had much success as my Jetson agx orin 32gb runs out of memory. I'll keep hacking at it and hopefully will have better luck learning more about tensorrt_llm.
