### ISSUE TITLE
issues using Lora adaptors with Mistral Nemo

### ISSUE THREAD

**Issue by kristoffer-bernhem** [NVIDIA/TensorRT-LLM#2283]
Hi,

I am attempting to transfer our training from llama3.1 tuning to Mistral Nemo (lora). Using the same core training scripts, producing the lora adaptors, I get the following error when trying to apply them for Mistral Nemo (llama3.1 works fine):

```
Failed to load lora adaptor. [500] Executor failed process requestId 106 due to the following error: Encountered an error when fetching new request: [TensorRT-LLM][ERROR] Assertion failed: lora_weights has to few values for attn_q (/app/tensorrt_llm/cpp/tensorrt_llm/runtime/loraUtils.cpp:84)
1       0x78620aa88276 tensorrt_llm::common::throwRuntimeError(char const*, int, std::string const&) + 102
2       0x78620c8f948a tensorrt_llm::runtime::lora::loraValidateRequestTensors(std::optional<unsigned long> const&, std::optional<std::shared_ptr<tensorrt_llm::runtime::ITensor> > const&, std::optional<std::shared_ptr<tensorrt_llm::runtime::ITensor> > const&, tensorrt_llm::runtime::ModelConfig const&, tensorrt_llm::runtime::WorldConfig const&) + 2106
3       0x78620cd71b86 tensorrt_llm::batch_manager::PeftCacheManager::addRequestPeft(std::shared_ptr<tensorrt_llm::batch_manager::LlmRequest>, bool) + 246
4       0x78620cd92370 tensorrt_llm::batch_manager::TrtGptModelInflightBatching::updatePeftCache(std::shared_ptr<tensorrt_llm::batch_manager::LlmRequest> const&) + 64
5       0x78620cdcf6e7 tensorrt_llm::executor::Executor::Impl::fetchNewRequests(int, std::optional<float>, double&) + 3239
6       0x78620cdd0dc3 tensorrt_llm::executor::Executor::Impl::executionLoop() + 915
7       0x7862e8bd7253 /lib/x86_64-linux-gnu/libstdc++.so.6(+0xdc253) [0x7862e8bd7253]
8       0x7862e8966ac3 /lib/x86_64-linux-gnu/libc.so.6(+0x94ac3) [0x7862e8966ac3]
9       0x7862e89f7a04 clone + 68
```

As part of the training I generate a merged model in torch for testing and that works well, but not once I apply it to TRT-LLM (on triton server). I have the latest transformer lib version available for both building the engine and training the model (4.45.1). The issue is the same for both  v0.12.0 and v0.13.0

**Comment by DanBlanaru** [comment]
Hello Kristoffer, could you please share some repro steps? It could happen for multiple reasons.
Please include the following info:

```
CPU architecture (e.g., x86_64, aarch64)
CPU/Host memory size (if known)
GPU properties
GPU name (e.g., NVIDIA H100, NVIDIA A100, NVIDIA L40S)
Libraries
TensorRT-LLM branch or tag TensorRT-LLM commit
Versions of TensorRT, AMMO, CUDA, cuBLAS, etc. used
Container used (if running TensorRT-LLM in a container)
NVIDIA driver version
OS (Ubuntu 22.04, CentOS 7, Windows 10)
Any other information that may be useful in reproducing the bug
```

Thank you!

**Comment by kristoffer-bernhem** [comment]
Hi,

I ran some more tests during the weekend and apperantly the issue was from PEFT's side, not tensortLLM, as I could get it to work as desired. For others finding this issue, if you specify which modules you target during training using PEFT and trl, in some cases the framework won't warn you that some are not available, but will handle the issue somehow internally, this does however mean that the output cant be used. The workaround was to use all modules (or rather let the framework decide by not specifying any restrictions)
