### ISSUE TITLE
various mpi4py issues and solutions

### ISSUE THREAD

**Issue by stas00** [NVIDIA/TensorRT-LLM#2286]
https://github.com/NVIDIA/TensorRT-LLM/blob/48686bca3a34c6d323086e540c1c5245ac8eaef5/requirements.txt#L8

needs to be pinned

```
- mpi4py
+ mpi4py>=4.0.0
```

trt is linked against v4 of mpi4py, and if a user happened to have mpi4py v3 loading tensorrt_llm hangs, see https://github.com/NVIDIA/TensorRT-LLM/issues/2172

inside docker image:
```
$ python -c "import mpi4py; print(mpi4py.__version__)"
4.0.0
```

**Comment by stas00** [comment]
actually there is another problem here. if I install `mpi4py` from pypi:

```
pip install mpi4py>=4.0.0
```

trt-llm fails to load:

```
python -c "import tensorrt_llm"
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[a3-ghpc-12:3066184] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
```
only if I reinstall from conda:
```
conda install -c conda-forge mpi4py openmpi
```
it then works.

So automatic dependencies resolving via pip will most likely result in a not working setup.

edit: this worked for a single gpu, but would hang for 2 gpus plus.

I discovered that with this conda package install, it can't see the gpus:
```
# conda view:
$ conda activate ctx-shared-trt-stable
$ hwloc-ls | grep CoProc

# switch to system view
$ conda deactivate
$ hwloc-ls | grep CoProc
              CoProc(OpenCL) "opencl0d0"
              CoProc(OpenCL) "opencl0d1"
              CoProc(OpenCL) "opencl0d2"
              CoProc(OpenCL) "opencl0d3"
              CoProc(OpenCL) "opencl0d4"
              CoProc(OpenCL) "opencl0d5"
              CoProc(OpenCL) "opencl0d6"
              CoProc(OpenCL) "opencl0d7"
```
so unfortunately this solution doesn't work.

**Comment by stas00** [comment]
after debugging this - as I'm running in a SLURM env it appear to be something triggered by `SLURM_NODELIST` being present - pip version of `mpi4py` relies on system-wide mpi packages and something gets messed up there on load.

Whereas `conda install -c conda-forge mpi4py openmpi` leads to a self-contained environment, bypassing the system one and thus everything works. Obviously, the problem with using conda packages is that you can't do `pip install -r requirements`.

one more note - when installing with pip you may run into a bunch of undefined reference errors like shown in this SO: https://stackoverflow.com/questions/72400810/fails-to-build-mpi4py-while-installing-stanfords-gibson

```  
/usr/bin/mpicc -pthread -B /home/$USER/anaconda3/envs/py35/compiler_compat _configtest.o -Lbuild/temp.linux-x86_64-3.5 -o _configtest
  /home/$USER/anaconda3/envs/py35/compiler_compat/ld: warning: libopen-rte.so.20, needed by /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so, not found (try using -rpath or -rpath-link)
  /home/$USER/anaconda3/envs/py35/compiler_compat/ld: warning: libopen-pal.so.20, needed by /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so, not found (try using -rpath or -rpath-link)
  /home/$USER/anaconda3/envs/py35/compiler_compat/ld: warning: librt.so.1, needed by /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so, not found (try using -rpath or -rpath-link)
  /home/$USER/anaconda3/envs/py35/compiler_compat/ld: warning: libm.so.6, needed by /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so, not found (try using -rpath or -rpath-link)
  /home/$USER/anaconda3/envs/py35/compiler_compat/ld: warning: libhwloc.so.5, needed by /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so, not found (try using -rpath or -rpath-link)
  /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so: undefined reference to `mca_base_framework_components_close'
  /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so: undefined reference to `opal_list_sort'
  /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so: undefined reference to `opal_hwloc_base_get_topology'
  /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so: undefined reference to `opal_datatype_get_element_count'
  /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so: undefined reference to `opal_convertor_t_class'
  /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so: undefined reference to `opal_namelist_t_class'

```
As proposed by the solution there:
```
rm $CONDA_PREFIX/compiler_compat/ld
```
this overcome this problem and `pip install mpi4py` succeeds.

Moreover since I have been messing with this conda env installing packages back-n-forth other things started breaking. So I created a new conda environment, discarding the old one and just installed `tensorrt_llm` and everything just worked out of the box.

This thread is also useful for various other mpi4py installing issues: https://github.com/mpi4py/mpi4py/issues/335

**Comment by Superjomn** [comment]
Thanks for your suggestions and work notes, I think this will be helpful for others meeting similar issues.

**Comment by Superjomn** [comment]
We will try to pin the mpi4py version.
Thanks.
