### ISSUE TITLE
cpu memory need in build.py

### ISSUE THREAD

**Issue by foocker** [NVIDIA/TensorRT-LLM#229]
i have test baichuan v2 7b and 13b(all killed). because all the model only support on cpu:
```
device_map={
                "model": "cpu",
                "lm_head": "cpu"
            },  # Load to CPU memory
```
when you set some submodule to cuda, you may get:
```
[11/01/2023-06:10:41] [TRT-LLM] [I] Loading weights from HF Baichuan v2_7b...
Traceback (most recent call last):
  File "/code/tensorrt_llm/examples/baichuan/build.py", line 477, in <module>
    build(0, args)
  File "/code/tensorrt_llm/examples/baichuan/build.py", line 447, in build
    engine = build_rank_engine(builder, builder_config, engine_name,
  File "/code/tensorrt_llm/examples/baichuan/build.py", line 347, in build_rank_engine
    load_from_hf_baichuan(tensorrt_llm_baichuan,
  File "/code/tensorrt_llm/examples/baichuan/weight.py", line 63, in load_from_hf_baichuan
    v = torch_to_numpy(v.to(torch_dtype).detach().cpu())
NotImplementedError: Cannot copy out of meta tensor; no data!
```
but my question as the title:
## 7b and 13b model, to get trt fp16 or int8 engine, the lowest memory we need is?
my mem is 48G...

**Comment by juney-nvidia** [comment]
@foocker  can you elaborate your question a little bit? So you want to run TensorRT-LLM models on a machine without GPU?

June

**Comment by foocker** [comment]
> @foocker can you elaborate your question a little bit? So you want to run TensorRT-LLM models on a machine without GPU?
> 
> June

no only run cpu, just build engine, and run on gpu.
 my env: two 3090ti, and cpu mem is 48G. 
but i run build.py in baichuan, 7b, or 13b, fp16, int8, or int4, **its all killed.** (memory is not enough)my question is the lowest memory list(7, 13, 34) sholud i prepare for building the models above.

**Comment by Minami-su** [comment]
I have the same question,
[11/02/2023-12:40:16] [TRT-LLM] [I] HF Baichuan v2_13b loaded. Total time: 00:04:33
[11/02/2023-12:40:16] [TRT-LLM] [I] Loading weights from HF Baichuan v2_13b...
Traceback (most recent call last):
  File "/app/tensorrt_llm/examples/baichuan/build.py", line 478, in <module>
    build(0, args)
  File "/app/tensorrt_llm/examples/baichuan/build.py", line 448, in build
    engine = build_rank_engine(builder, builder_config, engine_name,
  File "/app/tensorrt_llm/examples/baichuan/build.py", line 348, in build_rank_engine
    load_from_hf_baichuan(tensorrt_llm_baichuan,
  File "/app/tensorrt_llm/examples/baichuan/weight.py", line 63, in load_from_hf_baichuan
    v = torch_to_numpy(v.to(torch_dtype).detach().cpu())
NotImplementedError: Cannot copy out of meta tensor; no data!

**Comment by jdemouth-nvidia** [comment]
Hi @foocker , @Minami-su ,

Can you share the command you are using, please?

Thanks,
Julien

**Comment by matt-psaltis** [comment]
I hit the no data error if you have the model and heads on separate devices. E. G. Model on cuda, lm_head on CPU. At this stage it only works if the device map is consistent for both.

**Comment by Minami-su** [comment]
> I hit the no data error if you have the model and heads on separate devices. E. G. Model on cuda, lm_head on CPU. At this stage it only works if the device map is consistent for both.

https://github.com/NVIDIA/TensorRT-LLM/issues/102#issuecomment-1780354199

**Comment by Minami-su** [comment]
> Hi @foocker , @Minami-su ,
> 
> Can you share the command you are using, please?
> 
> Thanks, Julien

```
python build.py --model_version v2_13b \
                --model_dir Baichuan2-13B-Chat \
                --dtype float16 \
                --use_gemm_plugin float16 \
                --use_gpt_attention_plugin float16 \
                --use_weight_only \
                --weight_only_precision int4 \
		--max_batch_size 1 \
		--use_inflight_batching \
                --output_dir baichuan_v2_13b_int4_weight
```
Thank you. I see the problem, I modified the code according to the following url, and then he produced this error
https://github.com/NVIDIA/TensorRT-LLM/issues/102#issuecomment-1780354199

**Comment by byshiue** [comment]
Since the issue https://github.com/NVIDIA/TensorRT-LLM/issues/102 is resolved, it looks this issue is also resolved and I will close this bug. Feel free to ask here if you still have question/issue, we will reopen the issue.

**Comment by Burning-XX** [comment]
> Since the issue #102 is resolved, it looks this issue is also resolved and I will close this bug. Feel free to ask here if you still have question/issue, we will reopen the issue.

so how to solve this memory problem? I also met this with release-1.5.0 branch and 32G CPU memory。
