### ISSUE TITLE
[Question] Support Async Senc/Recv?

### ISSUE THREAD

**Issue by jiahy0825** [NVIDIA/TensorRT-LLM#2296]
Since AllReduce is already an asynchronous kernel (as mentioned in [this issue](https://github.com/NVIDIA/TensorRT-LLM/issues/1389)), I assume AllGather is also asynchronous.

I would also like to know if the Send/Recv kernel is asynchronous as well?

**Comment by byshiue** [comment]
Yes. They all are aysn kernels.
