### ISSUE TITLE
ERROR: This container was built for NVIDIA Driver Release 535.86 or later, compatibility mode is UNAVAILABLE.

### ISSUE THREAD

**Issue by sleepwalker2017** [NVIDIA/TensorRT-LLM#23]
```text
ERROR: This container was built for NVIDIA Driver Release 535.86 or later, but
       version 510.85.02 was detected and compatibility mode is UNAVAILABLE.
```

I build docker image on this machine:
```
 NVIDIA-SMI 510.85.02    Driver Version: 510.85.02    CUDA Version: 11.6
```

When I run container it complains this, what does this mean? Can I still run TRT-LLM on this container? 

Seems FT can still run ok in this container.

**Comment by jdemouth** [comment]
TensorRT-LLM uses CUDA 12.2 and requires a recent driver. Is it possible for you to upgrade the CUDA driver to >= 535.86?

**Comment by sleepwalker2017** [comment]
> TensorRT-LLM uses CUDA 12.2 and requires a recent driver. Is it possible for you to upgrade the CUDA driver to >= 535.86?

OK, I'll try that.

But I wonder if that is a must? seems the 12.1 container can run in a compatibility mode. 

Even if not in a compatibility mode, FasterTransformer can run ok, why is that?

**Comment by jdemouth** [comment]
FT was developed using CUDA 10.x/11.x - we have moved to a more recent version of CUDA for TensorRT-LLM.
