### ISSUE TITLE
 How to set up tensorRT environment on coalb

### ISSUE THREAD

**Issue by NGshad0w** [NVIDIA/TensorRT-LLM#230]
The problem currently encountered is that tensorrt_llm cannot be installed. I am not sure if it is an environmental problem in colab (cannot be installed using pip),just want to try quick start example[bloom-560M]
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/149561699/e8e27d2f-bd9d-4a3c-afe3-1006edecf544)

code:https://colab.research.google.com/drive/1sZaXPwoXq7NS9642WzlWVWHOtgT3sQHz?usp=sharing

**Comment by juney-nvidia** [comment]
@NGshad0w can you share more concrete steps of meeting this issue? e.g., are you doing the installation on Windows or Linux? Did you follow [the installation guide](https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/docs/source/installation.md) by building the TensorRT-LLM from the source?

June

**Comment by Tlntin** [comment]
I see you colab, it's cpu memory is too low, I think it may not success.
But you can try build in AutoDL, I success!
[link](https://zhuanlan.zhihu.com/p/663915644)

**Comment by byshiue** [comment]
Close this bug because the issue is resolved. Feel free to ask here if you still have question/issue, we will reopen the issue.

**Comment by nhduong1203** [comment]
hi, how to fix this problem?
