### ISSUE TITLE
How can I implement and use a customized kernel, or how can I transfer kv_cache from one GPU to another GPU efficiently？

### ISSUE THREAD

**Issue by GGBond8488** [NVIDIA/TensorRT-LLM#2304]
like the https://github.com/microsoft/mscclpp

**Comment by Superjomn** [comment]
This is a large topic. 
Currently, we use TensorRT as the runtime, so you can add a TensorRT [plugin](https://github.com/NVIDIA/TensorRT-LLM/tree/main/cpp/tensorrt_llm/plugins) for a kernel, and build TensorRT-LLM models using that plugin, the [functional.py](https://github.com/NVIDIA/TensorRT-LLM/blob/main/tensorrt_llm/functional.py) contains all the plugins used in the models, you can track the usages in the codebase.

To transfer kv cache, the traditional way is to utilize NCCL, but you are free to customize the traffic in your plugin.

**Comment by GGBond8488** [comment]
thanks for your advice, plugins should be a good solution
