### ISSUE TITLE
kv cache quant lead to model accuracy loss serious?

### ISSUE THREAD

**Issue by liguodongiot** [NVIDIA/TensorRT-LLM#2309]
hi, I found trt-llm kv cache quant lead to model accuracy loss serious,  but vllm and lmdeploy only less loss.

- model: qwen1.5-7b
- evalset: cmmlu

![Image](https://github.com/user-attachments/assets/f308b17e-7bf5-468d-81bb-ed37e083e9b2)

**Comment by Tracin** [comment]
Per-tensor quantization on kv cache can cause large error. Do you have cmmlu results without kv cache quantized?
