### ISSUE TITLE
C++ Executor Leader Mode

### ISSUE THREAD

**Issue by Guangjun-A** [NVIDIA/TensorRT-LLM#2322]
Is it possible to have one process with multiple Executors with Leader mode inside if i have one gpu device?

**Comment by pcastonguay** [comment]
It is possible, but not officially supported. You need to be careful when setting the `KvCacheConfig` `maxTokens` or `freeGpuMemoryFraction` and there could be performance implications when sharing a single gpu between multiple executor instances.

**Comment by Guangjun-A** [comment]
> It is possible, but not officially supported. You need to be careful when setting the `KvCacheConfig` `maxTokens` or `freeGpuMemoryFraction` and there could be performance implications when sharing a single gpu between multiple executor instances.

get it, thanks.
