### ISSUE TITLE
Are there any ways to get QK scores from attention?

### ISSUE THREAD

**Issue by ttim** [NVIDIA/TensorRT-LLM#2326]
Hi!

I'm wondering if there is a way to get attention scores from the engine in TRT-LLM? Are there any plans to make it available?

Thank you!

**Comment by syuoni** [comment]
Hi @ttim , TRT-LLM does not support returning attention scores.

In addition, TRT-LLM by default uses fused MHA, which avoids writing the attention scores to global memory. This improves computation efficiency and reduces memory consumption. Returning attention scores significantly damages these features. Currently, we don't have any plans for returning attention scores.

**Comment by ttim** [comment]
@syuoni got it, thanks for the reply!
