### ISSUE TITLE
GptManager vs Executorl: Why using an Executor instead of a GptManager the release version?

### ISSUE THREAD

**Issue by Guangjun-A** [NVIDIA/TensorRT-LLM#2328]
Why using an Executor instead of a GptManager the release version?

**Comment by Superjomn** [comment]
This may not be sufficient to answer your question, the GptManager is deprecated, and the Executor API is the official API now, it is available both in C++ API and Python API.

**Comment by Guangjun-A** [comment]
> This may not be sufficient to answer your question, the GptManager is deprecated, and the Executor API is the official API now, it is available both in C++ API and Python API.

SO, what reasons was deprecated for GptManager?

**Comment by MartinMarciniszyn** [comment]
`Executor` API is a refined and generalized version of `GptManager`. It adds another layer of abstraction. To avoid duplicating APIs, the `GptManager` API is not going to be supported beyond 0.14.
