### ISSUE TITLE
How to compile the cpp version of benchmarks

### ISSUE THREAD

**Issue by wrfgup** [NVIDIA/TensorRT-LLM#233]
I build the docker image following the Readme, run the docker but find no executable file of benchmarks.
when I look to the Readme in Tensorrt_llm/benchmarks/cpp:
<img width="466" alt="2770542c62ca4bffb827945040f45a83" src="https://github.com/NVIDIA/TensorRT-LLM/assets/31720555/0a953854-9834-44b3-a78f-db07f6dc2ea1">
I find that there is only CMakeList.txt in this directory but no Makeflie.
So how can I get the  executable file of benchmarks of cpp version

**Comment by juney-nvidia** [comment]
@wrfgup 
I think you are not executing the T[ensorRT-LLM building command](https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/docs/source/installation.md#build-tensorrt-llm) before?

After invoking it, you can see the `cpp/build` directory under which there is Makefile.

**Comment by wrfgup** [comment]
@juney-nvidia yes i just run build tensorrt-llm in one step(https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/docs/source/installation.md#build-tensorrt-llm-in-one-step).should i run https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/docs/source/installation.md#build-tensorrt-llm after builded tensorrt-llm in one step

**Comment by juney-nvidia** [comment]
> https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/docs/source/installation.md#build-tensorrt-llm

After invoking `python3 ./scripts/build_wheel.py --trt_root /usr/local/tensorrt`, you should be able to see the `cpp/build` directory. Does it work for you now?

June

**Comment by 77h2l** [comment]
nope.as long as we were in the docker, after run python3 ./scripts/build_wheel.py --trt_root /usr/local/tensorrt 
there is still no build dir under the benchmarks/cpp directory

**Comment by byshiue** [comment]
> ython3 ./scripts/build_wheel.py --trt_root /usr/local/tensorrt
> there is still no build dir under the benchmarks/cpp directory

Please trying
```bash
cd cpp/build
make -j12
```

By default, the `build_wheel.py` only build packages for python.

**Comment by 77h2l** [comment]
actually, I mean no matter how compiles in the docker container, there will never be Makefile file under the benchmark/cpp/build directory even no build dir under cpp, pls confirms.

**Comment by byshiue** [comment]
> actually, I mean no matter how compiles in the docker container, there will never be Makefile file under the benchmark/cpp/build directory even no build dir under cpp, pls confirms.

They should be put in `cpp/build/benchmarks` instead of `benchmark/cpp/build`.
