### ISSUE TITLE
MoE TP vs. EP

### ISSUE THREAD

**Issue by Mutinifni** [NVIDIA/TensorRT-LLM#2331]
I am profiling Mixtral-8x7B performance to find the best parallelism configuration between Expert Parallelism (EP) and Tensor Parallelism (TP).

To control for the impact of load balancing,  I explicitly override router expert selection criteria in two cases:
1. Balanced: Experts are chosen uniformly at random
2. Skewed: Only expert-ID 0 and 1 are chosen

My results show that with the existing implementation, TP always outperforms EP.

![Image](https://github.com/user-attachments/assets/ad11823c-ff49-4b3c-ab02-865123edaa1a)
![Image](https://github.com/user-attachments/assets/a7bc9734-1668-4381-b1c0-2bfba2884081)

This result makes sense because TensorRT-LLM currently uses a [common allreduce code path](https://github.com/NVIDIA/TensorRT-LLM/blob/main/tensorrt_llm/layers/moe.py#L516) during both TP and EP for convenience, as mentioned by @djns99 in https://github.com/NVIDIA/TensorRT-LLM/issues/989#issuecomment-1975330676. However, as also mentioned in the issue, I suspect that a dedicated all-to-all EP implementation could yield higher performance than TP in some cases.

I am curious whether there is any existing analysis doing this comparison? Alternatively, is there any all-to-all EP implementation available that I could benchmark? Thanks!

**Comment by djns99** [comment]
Hi @Mutinifni,  thanks for sharing. I wonder what is your benchmarking command to generate these numbers?

The skewed numbers makes sense, though I would expect a bit more of a performance uplift for TP over balanced in this case.
However in the case of a balanced routing distribution, we expect that EP is more performant than TP in most cases. The communication cost for both should be the same, and EP should on average have more efficient GEMM operations.

With regard to all-to-all EP (or more precisely it would be an AllGatherV in TRT-LLM), our internal evaluations suggest that this gets worse performance than allreduce, except in the certain multi-node configurations with large token counts.

**Comment by mutinifni** [comment]
Thank you for the reply, @djns99! 

Here is my benchmarking approach. First, I make the following code changes in `topkGatingSoftmax()` in `moe_kernels.cu`.

1. Balanced ([source](https://github.com/Mutinifni/TensorRT-LLM/blob/expert-skew/cpp/tensorrt_llm/kernels/mixtureOfExperts/moe_kernels.cu#L401C1-L409C14)):
```C++
// Always select two random experts
if (k_idx < 2)
{
    expert = curand(&state) % NUM_EXPERTS; // Select a random expert
}
else
{
    expert = -1; // For other k_idx values, set expert to -1
}
```

2. Skewed ([source](https://github.com/Mutinifni/TensorRT-LLM/blob/expert-skew/cpp/tensorrt_llm/kernels/mixtureOfExperts/moe_kernels.cu#L398)):
```C++
// Always select the first two experts
expert = k_idx < 2 ? k_idx : -1; // Select expert 0 for k_idx 0, expert 1 for k_idx 1, and -1 for others
```

Then, I create a dataset using `prepare_dataset.py`:
```bash
model_name="examples/mixtral/mixtral"
num_requests=1000
input_mean=128
input_stdev=0
output_mean=1
output_stdev=0
dataset_file=${num_requests}_token-norm-dist.json

python benchmarks/cpp/prepare_dataset.py \
        --output=$dataset_file \
        --tokenizer=$model_name \
        token-norm-dist \
        --num-requests=$num_requests \
        --input-mean=$input_mean \
        --output-mean=$output_mean \
        --input-stdev=$input_stdev \
        --output-stdev=$output_stdev
```

Finally, run using `gptManagerBenchmark`:
```bash
mpirun -n $num_proc \
        ./cpp/build/benchmarks/gptManagerBenchmark \
        --engine_dir $engine_dir \
        --dataset $dataset_file 
```
I plot the token/second result printed by the gptManagerBenchmark.

My guess for why EP performance is lower was because the computation kernels may be less efficient than TP. If that's not the case, what you said makes sense. Follow up questions: 
- Would you suggest a different benchmarking approach?
- Is there a plan to release the AllGatherV implementation? Is the main reason for the slowness because the data wrangling is inefficient?

**Comment by djns99** [comment]
Your benchmark methodology makes sense. Thanks for sharing, we will definitely continue to work on improving the performance.

We do have a single-GPU microbenchmark for MOE layer (i.e. not the full model) under https://github.com/NVIDIA/TensorRT-LLM/blob/main/cpp/micro_benchmarks/README.md. It's a bit difficult to use, but it supports testing different distributions without needing to modify the implementation.  
This would allow you to experiment with different configurations much easier, though it obviously ignores a number of important factors to overall model performance.  

When building TRT-LLM you will need to specify the `--micro_benchmarks` flag for `build_wheel.py` to compile them.

I have provided a sample JSON file that you can pass to the benchmark as follows:

`./cpp/build/micro_benchmarks/mixtureOfExpertsBackendBenchmark --input_file <json file name>`



```
[
{
  "num_experts": 8,
  "k": 2,
  "hidden_size": 4096,
  "inter_size": 14336,
  "tp_size": 1,
  "ep_size": 8,
  "world_rank": 0,
  "num_tokens": 128,
  "act_fn": 3,
  "norm_mode": 1,
  "dtypes": ["bfloat16"],
  "routing_distribution": "uniform",
  "tactic_id1": "auto",
  "tactic_id2": "auto",
  "bias": 0
},
{
  "num_experts": 8,
  "k": 2,
  "hidden_size": 4096,
  "inter_size": 14336,
  "tp_size": 1,
  "ep_size": 8,
  "world_rank": 0,
  "num_tokens": 2048,
  "act_fn": 3,
  "norm_mode": 1,
  "dtypes": ["bfloat16"],
  "routing_distribution": "uniform",
  "tactic_id1": "auto",
  "tactic_id2": "auto",
  "bias": 0
},
{
  "num_experts": 8,
  "k": 2,
  "hidden_size": 4096,
  "inter_size": 14336,
  "tp_size": 8,
  "ep_size": 1,
  "world_rank": 0,
  "num_tokens": 128,
  "act_fn": 3,
  "norm_mode": 1,
  "dtypes": ["bfloat16"],
  "routing_distribution": "uniform",
  "tactic_id1": "auto",
  "tactic_id2": "auto",
  "bias": 0
},
{
  "num_experts": 8,
  "k": 2,
  "hidden_size": 4096,
  "inter_size": 14336,
  "tp_size": 8,
  "ep_size": 1,
  "world_rank": 0,
  "num_tokens": 2048,
  "act_fn": 3,
  "norm_mode": 1,
  "dtypes": ["bfloat16"],
  "routing_distribution": "uniform",
  "tactic_id1": "auto",
  "tactic_id2": "auto",
  "bias": 0
},
{
  "num_experts": 8,
  "k": 2,
  "hidden_size": 4096,
  "inter_size": 14336,
  "tp_size": 1,
  "ep_size": 8,
  "world_rank": 0,
  "num_tokens": 128,
  "act_fn": 3,
  "norm_mode": 1,
  "dtypes": ["bfloat16"],
  "routing_values": [1,1,0,0,0,0,0,0],
  "tactic_id1": "auto",
  "tactic_id2": "auto",
  "bias": 0
},
{
  "num_experts": 8,
  "k": 2,
  "hidden_size": 4096,
  "inter_size": 14336,
  "tp_size": 1,
  "ep_size": 8,
  "world_rank": 0,
  "num_tokens": 2048,
  "act_fn": 3,
  "norm_mode": 1,
  "dtypes": ["bfloat16"],
  "routing_values": [1,1,0,0,0,0,0,0],
  "tactic_id1": "auto",
  "tactic_id2": "auto",
  "bias": 0
},
{
  "num_experts": 8,
  "k": 2,
  "hidden_size": 4096,
  "inter_size": 14336,
  "tp_size": 8,
  "ep_size": 1,
  "world_rank": 0,
  "num_tokens": 128,
  "act_fn": 3,
  "norm_mode": 1,
  "dtypes": ["bfloat16"],
  "routing_values": [1,1,0,0,0,0,0,0],
  "tactic_id1": "auto",
  "tactic_id2": "auto",
  "bias": 0
},
{
  "num_experts": 8,
  "k": 2,
  "hidden_size": 4096,
  "inter_size": 14336,
  "tp_size": 8,
  "ep_size": 1,
  "world_rank": 0,
  "num_tokens": 2048,
  "act_fn": 3,
  "norm_mode": 1,
  "dtypes": ["bfloat16"],
  "routing_values": [1,1,0,0,0,0,0,0],
  "tactic_id1": "auto",
  "tactic_id2": "auto",
  "bias": 0
}
]
```


With regard to support for the AllGatherV, this is not currently on the roadmap. 
The performance concerns are primarily due to the higher cost incurred for doing a variable sized transfer, though there may be ways to mitigate this that we have not explored yet.


I will mark this issue as closed for now, but please continue to share any interesting findings.

**Comment by mutinifni** [comment]
Thanks for the info -- it is very helpful 😄 

I ran the micro benchmark and it looks like the EP computation is indeed always slower than TP. Weirdly, it is even slower in the balanced scenario than skewed...

Here are the microbenchmark results with num_tokens=128 (similar trend for num_tokens=2048).

Balanced
- TP=1, EP=8: 421.918k/s
- TP=8, EP=1: 472.019k/s

Skewed:
- TP=1, EP=8: 447.353k/s
- TP=8, EP=1: 466.658k/s

I'm curious if you have any hypothesis as to why EP computation might be slower. I'll also investigate further. More generally, it might be useful to extend this microbenchmark to multiple GPUs and include communication operations.

Here's the full output just in case
```
2024-10-15T04:26:57+00:00
Running ./cpp/build/micro_benchmarks/mixtureOfExpertsBackendBenchmark
Run on (96 X 2445.44 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x96)
  L1 Instruction 32 KiB (x96)
  L2 Unified 512 KiB (x96)
  L3 Unified 16384 KiB (x24)
Load Average: 1.43, 1.50, 4.54
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Benchmark                                                                                                                                                                                                                                                                                                                     Time             CPU   Iterations UserCounters...
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
MixtureOfExpertsBenchmark<WeightParams<nv_bfloat16, nv_bfloat16, nv_bfloat16>>/Basic_nv_bfloat16_nv_bfloat16/Num Experts:8/K:2/Hidden Size:4096/Inter Size:14336/TP Size:1/EP Size:8/World Rank:0/Num Tokens:128/Use Bias:0/Activation Function:3/Norm Mode:1/Tactic ID 1:-1/Tactic ID 2:-1/Routing ID:1/manual_time     303377 ns       343041 ns        10000 act_fn=3 dtype=7 ep_size=8 hidden_size=4.096k inter_size=14.336k items_per_second=421.918k/s norm_mode=1 num_experts=8 num_tokens=128 routing_config=1 tactic_idx1=4 tactic_idx2=11 top_k=2 tp_size=1 use_bias=0 world_rank=0 uniform
MixtureOfExpertsBenchmark<WeightParams<nv_bfloat16, nv_bfloat16, nv_bfloat16>>/Basic_nv_bfloat16_nv_bfloat16/Num Experts:8/K:2/Hidden Size:4096/Inter Size:14336/TP Size:8/EP Size:1/World Rank:0/Num Tokens:128/Use Bias:0/Activation Function:3/Norm Mode:1/Tactic ID 1:-1/Tactic ID 2:-1/Routing ID:1/manual_time     271176 ns       310636 ns        10000 act_fn=3 dtype=7 ep_size=1 hidden_size=4.096k inter_size=14.336k items_per_second=472.019k/s norm_mode=1 num_experts=8 num_tokens=128 routing_config=1 tactic_idx1=11 tactic_idx2=1 top_k=2 tp_size=8 use_bias=0 world_rank=0 uniform
MixtureOfExpertsBenchmark<WeightParams<nv_bfloat16, nv_bfloat16, nv_bfloat16>>/Basic_nv_bfloat16_nv_bfloat16/Num Experts:8/K:2/Hidden Size:4096/Inter Size:14336/TP Size:1/EP Size:8/World Rank:0/Num Tokens:128/Use Bias:0/Activation Function:3/Norm Mode:1/Tactic ID 1:-1/Tactic ID 2:-1/Routing ID:2/manual_time     286128 ns       301087 ns        10000 act_fn=3 dtype=7 ep_size=8 hidden_size=4.096k inter_size=14.336k items_per_second=447.353k/s norm_mode=1 num_experts=8 num_tokens=128 routing_config=2 tactic_idx1=14 tactic_idx2=2 top_k=2 tp_size=1 use_bias=0 world_rank=0 config_2
MixtureOfExpertsBenchmark<WeightParams<nv_bfloat16, nv_bfloat16, nv_bfloat16>>/Basic_nv_bfloat16_nv_bfloat16/Num Experts:8/K:2/Hidden Size:4096/Inter Size:14336/TP Size:8/EP Size:1/World Rank:0/Num Tokens:128/Use Bias:0/Activation Function:3/Norm Mode:1/Tactic ID 1:-1/Tactic ID 2:-1/Routing ID:3/manual_time     274291 ns       289326 ns        10000 act_fn=3 dtype=7 ep_size=1 hidden_size=4.096k inter_size=14.336k items_per_second=466.658k/s norm_mode=1 num_experts=8 num_tokens=128 routing_config=3 tactic_idx1=11 tactic_idx2=10 top_k=2 tp_size=8 use_bias=0 world_rank=0 config_3
```

**Comment by djns99** [comment]
I would expect skewed to be faster than non-skewed for TP because it only needs to load 1/4 of the weights into smem (i.e. just expert 1&2). There is definitely something strange going on here, what GPU are you using? 
I have seen some strange behaviour for Ampere with gated functions, perhaps if you try changing the activation function in the benchmark to silu instead of swiglu (i.e. `"act_fn": 2,` in JSON)?

**Comment by mutinifni** [comment]
Weight loading point makes sense for TP.

I'm using the A100 SXM4 GPU. I switched to `"act_fn": 2` and the results are still strange:
```
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Benchmark                                                                                                                                                                                                                                                                                                                     Time             CPU   Iterations UserCounters...
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
MixtureOfExpertsBenchmark<WeightParams<nv_bfloat16, nv_bfloat16, nv_bfloat16>>/Basic_nv_bfloat16_nv_bfloat16/Num Experts:8/K:2/Hidden Size:4096/Inter Size:14336/TP Size:1/EP Size:8/World Rank:0/Num Tokens:128/Use Bias:0/Activation Function:2/Norm Mode:1/Tactic ID 1:-1/Tactic ID 2:-1/Routing ID:1/manual_time     218731 ns       258393 ns        10000 act_fn=2 dtype=7 ep_size=8 hidden_size=4.096k inter_size=14.336k items_per_second=585.195k/s norm_mode=1 num_experts=8 num_tokens=128 routing_config=1 tactic_idx1=4 tactic_idx2=11 top_k=2 tp_size=1 use_bias=0 world_rank=0 uniform
MixtureOfExpertsBenchmark<WeightParams<nv_bfloat16, nv_bfloat16, nv_bfloat16>>/Basic_nv_bfloat16_nv_bfloat16/Num Experts:8/K:2/Hidden Size:4096/Inter Size:14336/TP Size:8/EP Size:1/World Rank:0/Num Tokens:128/Use Bias:0/Activation Function:2/Norm Mode:1/Tactic ID 1:-1/Tactic ID 2:-1/Routing ID:1/manual_time     192198 ns       231829 ns        10000 act_fn=2 dtype=7 ep_size=1 hidden_size=4.096k inter_size=14.336k items_per_second=665.981k/s norm_mode=1 num_experts=8 num_tokens=128 routing_config=1 tactic_idx1=1 tactic_idx2=10 top_k=2 tp_size=8 use_bias=0 world_rank=0 uniform
MixtureOfExpertsBenchmark<WeightParams<nv_bfloat16, nv_bfloat16, nv_bfloat16>>/Basic_nv_bfloat16_nv_bfloat16/Num Experts:8/K:2/Hidden Size:4096/Inter Size:14336/TP Size:1/EP Size:8/World Rank:0/Num Tokens:128/Use Bias:0/Activation Function:2/Norm Mode:1/Tactic ID 1:-1/Tactic ID 2:-1/Routing ID:2/manual_time     216981 ns       231944 ns        10000 act_fn=2 dtype=7 ep_size=8 hidden_size=4.096k inter_size=14.336k items_per_second=589.914k/s norm_mode=1 num_experts=8 num_tokens=128 routing_config=2 tactic_idx1=4 tactic_idx2=11 top_k=2 tp_size=1 use_bias=0 world_rank=0 config_2
MixtureOfExpertsBenchmark<WeightParams<nv_bfloat16, nv_bfloat16, nv_bfloat16>>/Basic_nv_bfloat16_nv_bfloat16/Num Experts:8/K:2/Hidden Size:4096/Inter Size:14336/TP Size:8/EP Size:1/World Rank:0/Num Tokens:128/Use Bias:0/Activation Function:2/Norm Mode:1/Tactic ID 1:-1/Tactic ID 2:-1/Routing ID:3/manual_time     191164 ns       206053 ns        10000 act_fn=2 dtype=7 ep_size=1 hidden_size=4.096k inter_size=14.336k items_per_second=669.583k/s norm_mode=1 num_experts=8 num_tokens=128 routing_config=3 tactic_idx1=10 tactic_idx2=10 top_k=2 tp_size=8 use_bias=0 world_rank=0 config_3
```

**Comment by djns99** [comment]
We have a couple of internal bugs tracking weird performance behaviour on Ampere, I will raise this behaviour with the relevant people internally. 
Thank you for raising this!

**Comment by mutinifni** [comment]
I realized that ran this with my previous benchmarking code modifications which caused incorrect results. My bad, sorry.

Performance is closer to expected after deleting those changes. 

act_fn: 2
```
MixtureOfExpertsBenchmark<WeightParams<nv_bfloat16, nv_bfloat16, nv_bfloat16>>/Basic_nv_bfloat16_nv_bfloat16/Num Experts:8/K:2/Hidden Size:4096/Inter Size:14336/TP Size:1/EP Size:8/World Rank:0/Num Tokens:128/Use Bias:0/Activation Function:2/Norm Mode:1/Tactic ID 1:-1/Tactic ID 2:-1/Routing ID:1/manual_time     219129 ns       258991 ns        10000 act_fn=2 dtype=7 ep_size=8 hidden_size=4.096k inter_size=14.336k items_per_second=584.132k/s norm_mode=1 num_experts=8 num_tokens=128 routing_config=1 tactic_idx1=4 tactic_idx2=11 top_k=2 tp_size=1 use_bias=0 world_rank=0 uniform
MixtureOfExpertsBenchmark<WeightParams<nv_bfloat16, nv_bfloat16, nv_bfloat16>>/Basic_nv_bfloat16_nv_bfloat16/Num Experts:8/K:2/Hidden Size:4096/Inter Size:14336/TP Size:8/EP Size:1/World Rank:0/Num Tokens:128/Use Bias:0/Activation Function:2/Norm Mode:1/Tactic ID 1:-1/Tactic ID 2:-1/Routing ID:1/manual_time     191600 ns       231446 ns        10000 act_fn=2 dtype=7 ep_size=1 hidden_size=4.096k inter_size=14.336k items_per_second=668.059k/s norm_mode=1 num_experts=8 num_tokens=128 routing_config=1 tactic_idx1=10 tactic_idx2=1 top_k=2 tp_size=8 use_bias=0 world_rank=0 uniform
MixtureOfExpertsBenchmark<WeightParams<nv_bfloat16, nv_bfloat16, nv_bfloat16>>/Basic_nv_bfloat16_nv_bfloat16/Num Experts:8/K:2/Hidden Size:4096/Inter Size:14336/TP Size:1/EP Size:8/World Rank:0/Num Tokens:128/Use Bias:0/Activation Function:2/Norm Mode:1/Tactic ID 1:-1/Tactic ID 2:-1/Routing ID:2/manual_time     348266 ns       363563 ns        10000 act_fn=2 dtype=7 ep_size=8 hidden_size=4.096k inter_size=14.336k items_per_second=367.536k/s norm_mode=1 num_experts=8 num_tokens=128 routing_config=2 tactic_idx1=13 tactic_idx2=2 top_k=2 tp_size=1 use_bias=0 world_rank=0 config_2
MixtureOfExpertsBenchmark<WeightParams<nv_bfloat16, nv_bfloat16, nv_bfloat16>>/Basic_nv_bfloat16_nv_bfloat16/Num Experts:8/K:2/Hidden Size:4096/Inter Size:14336/TP Size:8/EP Size:1/World Rank:0/Num Tokens:128/Use Bias:0/Activation Function:2/Norm Mode:1/Tactic ID 1:-1/Tactic ID 2:-1/Routing ID:3/manual_time     121963 ns       136899 ns        10000 act_fn=2 dtype=7 ep_size=1 hidden_size=4.096k inter_size=14.336k items_per_second=1.0495M/s norm_mode=1 num_experts=8 num_tokens=128 routing_config=3 tactic_idx1=1 tactic_idx2=1 top_k=2 tp_size=8 use_bias=0 world_rank=0 config_3
```

act_fn: 3
```
MixtureOfExpertsBenchmark<WeightParams<nv_bfloat16, nv_bfloat16, nv_bfloat16>>/Basic_nv_bfloat16_nv_bfloat16/Num Experts:8/K:2/Hidden Size:4096/Inter Size:14336/TP Size:1/EP Size:8/World Rank:0/Num Tokens:128/Use Bias:0/Activation Function:3/Norm Mode:1/Tactic ID 1:-1/Tactic ID 2:-1/Routing ID:1/manual_time     304028 ns       343841 ns        10000 act_fn=3 dtype=7 ep_size=8 hidden_size=4.096k inter_size=14.336k items_per_second=421.014k/s norm_mode=1 num_experts=8 num_tokens=128 routing_config=1 tactic_idx1=13 tactic_idx2=11 top_k=2 tp_size=1 use_bias=0 world_rank=0 uniform
MixtureOfExpertsBenchmark<WeightParams<nv_bfloat16, nv_bfloat16, nv_bfloat16>>/Basic_nv_bfloat16_nv_bfloat16/Num Experts:8/K:2/Hidden Size:4096/Inter Size:14336/TP Size:8/EP Size:1/World Rank:0/Num Tokens:128/Use Bias:0/Activation Function:3/Norm Mode:1/Tactic ID 1:-1/Tactic ID 2:-1/Routing ID:1/manual_time     278081 ns       317745 ns        10000 act_fn=3 dtype=7 ep_size=1 hidden_size=4.096k inter_size=14.336k items_per_second=460.298k/s norm_mode=1 num_experts=8 num_tokens=128 routing_config=1 tactic_idx1=11 tactic_idx2=10 top_k=2 tp_size=8 use_bias=0 world_rank=0 uniform
MixtureOfExpertsBenchmark<WeightParams<nv_bfloat16, nv_bfloat16, nv_bfloat16>>/Basic_nv_bfloat16_nv_bfloat16/Num Experts:8/K:2/Hidden Size:4096/Inter Size:14336/TP Size:1/EP Size:8/World Rank:0/Num Tokens:128/Use Bias:0/Activation Function:3/Norm Mode:1/Tactic ID 1:-1/Tactic ID 2:-1/Routing ID:2/manual_time     536411 ns       551543 ns        10000 act_fn=3 dtype=7 ep_size=8 hidden_size=4.096k inter_size=14.336k items_per_second=238.623k/s norm_mode=1 num_experts=8 num_tokens=128 routing_config=2 tactic_idx1=5 tactic_idx2=2 top_k=2 tp_size=1 use_bias=0 world_rank=0 config_2
MixtureOfExpertsBenchmark<WeightParams<nv_bfloat16, nv_bfloat16, nv_bfloat16>>/Basic_nv_bfloat16_nv_bfloat16/Num Experts:8/K:2/Hidden Size:4096/Inter Size:14336/TP Size:8/EP Size:1/World Rank:0/Num Tokens:128/Use Bias:0/Activation Function:3/Norm Mode:1/Tactic ID 1:-1/Tactic ID 2:-1/Routing ID:3/manual_time     177048 ns       192084 ns        10000 act_fn=3 dtype=7 ep_size=1 hidden_size=4.096k inter_size=14.336k items_per_second=722.967k/s norm_mode=1 num_experts=8 num_tokens=128 routing_config=3 tactic_idx1=2 tactic_idx2=1 top_k=2 tp_size=8 use_bias=0 world_rank=0 config_3
```

However, EP still significantly trails TP in balanced scenario.

**Comment by YJHMITWEB** [comment]
@Mutinifni Hi, I am quite interested in the EP implementation, it is using TensorRT right now, so kinda hard to see what really happens there. But I am curious how EP could use a common Allreduce code path with TP. And also I think TP has more communication than EP, because in TP, we are doing allreduce across all GPUs.

> I am profiling Mixtral-8x7B performance to find the best parallelism configuration between Expert Parallelism (EP) and Tensor Parallelism (TP).
> 
> To control for the impact of load balancing, I explicitly override router expert selection criteria in two cases:
> 
> 1. Balanced: Experts are chosen uniformly at random
> 2. Skewed: Only expert-ID 0 and 1 are chosen
> 
> My results show that with the existing implementation, TP always outperforms EP.
> 
> ![Image](https://github.com/user-attachments/assets/ad11823c-ff49-4b3c-ab02-865123edaa1a) ![Image](https://github.com/user-attachments/assets/a7bc9734-1668-4381-b1c0-2bfba2884081)
> 
> This result makes sense because TensorRT-LLM currently uses a [common allreduce code path](https://github.com/NVIDIA/TensorRT-LLM/blob/main/tensorrt_llm/layers/moe.py#L516) during both TP and EP for convenience, as mentioned by [@djns99](https://github.com/djns99) in [#989 (comment)](https://github.com/NVIDIA/TensorRT-LLM/issues/989#issuecomment-1975330676). However, as also mentioned in the issue, I suspect that a dedicated all-to-all EP implementation could yield higher performance than TP in some cases.
> 
> I am curious whether there is any existing analysis doing this comparison? Alternatively, is there any all-to-all EP implementation available that I could benchmark? Thanks!

**Comment by djns99** [comment]
Hi @YJHMITWEB, 
The first point to note is, in the current TRT-LLM implementation the tokens are replicated on all GPUs for the input and output (i.e. we do not use any sort of data parallelism).
This means we do not need any communication on the input for EP or TP, since we can just ignore the tokens we don't need for EP.
For the output, we need to send all computed tokens to all nodes (this would actually be a variable sized all-gather operation, not a full all-to-all).
Alternatively, we choose to insert zero padding into the output result of EP and do a fixed size AllReduce. This fixed size includes one entry for each token, so it is the same for both EP and TP.

Our internal analysis indicates that for most model configs AllReduce is actually more efficient than existing all-gather implementations. It would require a configuration with a large amount of zero-padding before the trade-off no longer makes sense, e.g. high `total num experts`/`moe top k` ratio, combined with high `EP` value
