### ISSUE TITLE
hang up  using mpirun -n 2

### ISSUE THREAD

**Issue by Hukongtao** [NVIDIA/TensorRT-LLM#2337]
### System Info

- A800-SXM4-40GB
- Driver Version: 535.129.03
- CUDA Version: 12.4
- tensorrt-llm==0.15.0.dev2024101500

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```shell



set -ex

pip3 install --no-cache-dir tensorrt_llm -U --pre --extra-index-url https://pypi.nvidia.com

filename=$(basename ${HDFS_MODEL_PATH})
num_devices_per_group=${NUM_DEVICES_PER_GROUP}


python3 convert_checkpoint.py \
    --model_dir ./${filename}/ \
    --output_dir ./tllm_checkpoint_gptq \
    --dtype float16 \
    --use_weight_only \
    --weight_only_precision int4_gptq \
    --per_group \
    --tp_size ${num_devices_per_group}


# max_batch_size:       Maximum number of requests that the engine can schedule
# max_input_len:        Maximum input length of one request
# max_seq_len:          Maximum total length of one request, including prompt and outputs
# max_beam_width:       Maximum number of beams for beam search decoding
# max_num_tokens:       Maximum number of batched input tokens after padding is removed in each batch
python3 build_engine.py \
    --checkpoint_dir ./tllm_checkpoint_gptq \
    --output_dir ./tmp/trt_engines/int4_GPTQ/ \
    --gemm_plugin float16 \
    --max_batch_size 1 \
    --max_input_len 8196 \
    --max_seq_len 8197 \
    --max_beam_width 1 \
    --max_num_tokens 8197 \
    --kv_cache_type disabled


mpirun -n 2 python3 handler_trt.py
```

![Image](https://github.com/user-attachments/assets/9ac93447-91fa-422f-b001-133b34928492)

The problem occurs in this sentence: MpiComm.local_init()

### Expected behavior

run successfully

### actual behavior

hang up

### additional notes

xxx

**Comment by Superjomn** [comment]
Can you provide the content of the `handler_trt.py`? Please give a simple code sample related to TensorRT-LLM for reproduction.

**Comment by Hukongtao** [comment]
> Can you provide the content of the `handler_trt.py`? Please give a simple code sample related to TensorRT-LLM for reproduction.

I found that this error has nothing to do with handler_trt.py.  I installed trt-llm in the following way and got the error.

```shell
pip3 install --no-cache-dir tensorrt_llm -U --pre --extra-index-url https://pypi.nvidia.com
```

But when I installed trt-llm from source, the error disappeared
```shell
git clone https://github.com/NVIDIA/TensorRT-LLM TensorRT-LLM-py39
git checkout 75057cd036af25e288c004d8ac9e52fd2d6224aa
git submodule update --init --recursive
git lfs install --force
git lfs pull
python3 ./scripts/build_wheel.py --trt_root /usr/local/tensorrt/ -c
```

**Comment by Superjomn** [comment]
I queried the information for the commit `75057cd036af25e288c004d8ac9e52fd2d6224aa`, it has the following information:
```
commit 75057cd036af25e288c004d8ac9e52fd2d6224aa (HEAD -> main, origin/main, origin/HEAD)
Author: Kaiyu Xie <26294424+kaiyux@users.noreply.github.com>
Date:   Tue Oct 15 15:28:40 2024 +0800
```
So it is the latest bi-weekly release.

Can you share the version of the tensorrt_llm pip installed? Just get the input of `import tensorrt_llm; print(tensorrt_llm.__version__)`.

cc @kaiyux for viz.
