### ISSUE TITLE
[Bug]An error occurs when running llama2 70b tp=2 cpp benchmark

### ISSUE THREAD

**Issue by wjj19950828** [NVIDIA/TensorRT-LLM#234]
Currently I am measuring the benchmark data of llama2 70b(TP=2)

The config configuration corresponding to trt engine is as follows：
```python
{
  "builder_config": {
    "fp8": false,
    "hidden_act": "silu",
    "hidden_size": 8192,
    "int8": false,
    "max_batch_size": 24,
    "max_input_len": 2048,
    "max_num_tokens": 8192,
    "max_output_len": 512,
    "max_position_embeddings": 8192,
    "name": "llama",
    "num_heads": 64,
    "num_kv_heads": 8,
    "num_layers": 80,
    "parallel_build": false,
    "pipeline_parallel": 1,
    "precision": "float16",
    "quant_mode": 0,
    "tensor_parallel": 2,
    "use_refit": false,
  },
  "plugin_config": {
    "attention_qk_half_accumulation": false,
    "bert_attention_plugin": false,
    "context_fmha_type": 1,
    "gemm_plugin": "float16",
    "gpt_attention_plugin": "float16",
    "identity_plugin": false,
    "layernorm_plugin": false,
    "layernorm_quantization_plugin": false,
    "lookup_plugin": false,
    "nccl_plugin": "float16",
    "paged_kv_cache": true,
    "quantize_per_token_plugin": false,
    "quantize_tensor_plugin": false,
    "remove_input_padding": true,
    "rmsnorm_plugin": false,
    "rmsnorm_quantization_plugin": false,
    "smooth_quant_gemm_plugin": false,
    "tokens_per_block": 64,
    "use_custom_all_reduce": false,
    "weight_only_groupwise_quant_matmul_plugin": false,
    "weight_only_quant_matmul_plugin": false
  }
}
```

The benchmark command is as follows：

```shell
mpirun --allow-run-as-root -n 2 ./benchmarks/gptSessionBenchmark \
    --model llama \
    --engine_dir $ENGINE_PATH \
    --batch_size "1;2;4;8;16" \
    --input_output_len "1536,512"
```

when bs = 8, will get the following error
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/19977378/31bdbab5-62ed-4af6-85ad-9c078cd804f9)

I have set max_bs to 24. This is because max_num_tokens(8k) is too large and the actual maximum bs cannot be greater than 4?

But on the actual service side, if the number of concurrency is very large (>=24), OOM will not occur. Is it because there are restrictions on scheduling? It is similar to implementing a waiting queue?

Thanks~

**Comment by juney-nvidia** [comment]
@wjj19950828 so there are two issues here:

- For bs=8, there is a "Parameter check error"
- For some concrete setting, there is OOM issue?
Or there is only the OOM issue?

BTW, which GPU are you using to run the cpp benchmark? 

June

**Comment by wjj19950828** [comment]
@juney-nvidia 
I am using the A100 card(80G). I am not sure if it is an OOM problem. How should I troubleshoot this problem, including "Parameter check error" errors?

Thanks~

**Comment by wjj19950828** [comment]
[test.log](https://github.com/NVIDIA/TensorRT-LLM/files/13227163/test.log)

This is the log output when I turn on verbose. Do you have any good solutions? Thanks ~

**Comment by wjj19950828** [comment]
UPDATE:
The above problem is mainly because build.py has ```max_num_tokens```. This value is best equal to ```max_batch_size``` * ```max_input_len```. When you test the benchmark, if the number of input tokens is greater than ```max_num_tokens```, the above error will be reported.

**Comment by juney-nvidia** [comment]
@wjj19950828  thanks for your efforts of trying to figure out the reason. 
The current logic of allocating memory for activation while building TensorRT engine is:

- When `max_num_tokens` is specified, it will be used as the max input token length.
- When `max_num_tokens` is not specified, `max_batch_size * max_input_len` will be used as the max input token length.

The consideration is to save some unnecessary memory allocation. For your scenario, if your input tokens are usually close to the `max_batch_size * max_input_len`, then yes, you should set the `max_num_tokens` correspondingly.

June
