### ISSUE TITLE
Status of TensorRT-LLM Eagle Implementation

### ISSUE THREAD

**Issue by avianion** [NVIDIA/TensorRT-LLM#2345]
@puneeshkhanna @ethnzhng @kaiyux 

Hello.

I notice there has been some commits related to Eagle Speculative decoding in the latest version of TensorRT-LLM.

However, there is no runtime code for Py Runtime or CPP runtime that I can see (in generation.py etc).

Is this speculative decoding mode planned for support soon? When I look at the comments in the model.py for EAGLE, it still looks like it is quite far away.

Tip: in TensorRT framework, for the context phase you may have to use Conditional Branches due to the way the EAGLE algorithm works differently between context and generation phase (we have implement successfully eagle algorithm in tensorrtllm framework independently)

**Comment by laikhtewari** [comment]
Thanks for the question, @avianion ! Development on eagle is in progress and will be made available in an upcoming release
