### ISSUE TITLE
Is there any extra demo for in-flight batch strategy？

### ISSUE THREAD

**Issue by Noblezhong** [NVIDIA/TensorRT-LLM#2349]
Hi I am a graduate students who majored in the **bubble optimazation for Pipeline parallelism in LLM Inference**. I see this repo decribe a inference requests schedule strategy, named 'in-flight batching'. I have great interests in studying purpose. So I follow the tutorial mentioned in tensorrt-backend repo. But there are no article teach me the implemention for this strategy. It's hard to comprehend this technology without better tutorial.

So, is there any addition implemention or evaluation for this strategy? Or just tell me which part of source code correspond to this function? In my opinion, it's maybe a C++ source code integrated in TensorRT dependency library.

Thank u！

**Comment by MartinMarciniszyn** [comment]
Hi @Noblezhong, unfortunately, the inflight batching strategy is closed source at the moment. Please consult the [documentation for batch manager](https://nvidia.github.io/TensorRT-LLM/advanced/batch-manager.html) for further details.

**Comment by Noblezhong** [comment]
I see that, hoping for open this source code in some day
