### ISSUE TITLE
Building engines using the `nvcr.io/nvidia/tritonserver:23.10-trtllm-python-py3` image

### ISSUE THREAD

**Issue by harryjulian** [NVIDIA/TensorRT-LLM#235]
Hi there,

I'm trying to build an engine for `falcon-7b-instruct` using the aformentioned image. 

I spun up the container with this command

```
docker run --gpus all -v $(pwd)/trtllm-docker:/opt/model -it nvcr.io/nvidia/tritonserver:23.10-trtllm-python-py3 /bin/bash
```

Where the `trtllm-docker` directory is mounted and contains the weights for falcon as well as a clone of the present repo so I can access the example scripts.

After install the Falcon's dependencies, I can't run the `build.py` script.

Errors installing the dependencies:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torch 2.1.0 requires nvidia-cublas-cu12==12.1.3.1; platform_system == "Linux" and platform_machine == "x86_64", which is not installed.
torch 2.1.0 requires nvidia-cuda-cupti-cu12==12.1.105; platform_system == "Linux" and platform_machine == "x86_64", which is not installed.
torch 2.1.0 requires nvidia-cuda-nvrtc-cu12==12.1.105; platform_system == "Linux" and platform_machine == "x86_64", which is not installed.
torch 2.1.0 requires nvidia-cuda-runtime-cu12==12.1.105; platform_system == "Linux" and platform_machine == "x86_64", which is not installed.
torch 2.1.0 requires nvidia-cudnn-cu12==8.9.2.26; platform_system == "Linux" and platform_machine == "x86_64", which is not installed.
torch 2.1.0 requires nvidia-cufft-cu12==11.0.2.54; platform_system == "Linux" and platform_machine == "x86_64", which is not installed.
torch 2.1.0 requires nvidia-curand-cu12==10.3.2.106; platform_system == "Linux" and platform_machine == "x86_64", which is not installed.
torch 2.1.0 requires nvidia-cusolver-cu12==11.4.5.107; platform_system == "Linux" and platform_machine == "x86_64", which is not installed.
torch 2.1.0 requires nvidia-cusparse-cu12==12.1.0.106; platform_system == "Linux" and platform_machine == "x86_64", which is not installed.
torch 2.1.0 requires nvidia-nccl-cu12==2.18.1; platform_system == "Linux" and platform_machine == "x86_64", which is not installed.
torch 2.1.0 requires nvidia-nvtx-cu12==12.1.105; platform_system == "Linux" and platform_machine == "x86_64", which is not installed.
Successfully installed absl-py-2.0.0 aiohttp-3.8.6 aiosignal-1.3.1 async-timeout-4.0.3 attrs-23.1.0 click-8.1.7 datasets-2.3.2 dill-0.3.5.1 frozenlist-1.4.0 joblib-1.3.2 multidict-6.0.4 multiprocess-0.70.13 nltk-3.8.1 pandas-2.1.2 pyarrow-13.0.0 python-dateutil-2.8.2 pytz-2023.3.post1 responses-0.18.0 rouge_score-0.1.2 sentencepiece-0.1.99 typing-extensions-4.5.0 tzdata-2023.3 xxhash-3.4.1 yarl-1.9.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```

Error when running the script:

1. Initially that `onnx` isn't installed, so I installed `onnx`.
2. `tensorrt_llm` isn't installed. Attempted to do this but received a `metadata-generation-failed` error. Same occured when trying to install via `pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com tensorrt-llm`

Full Error:

```
/opt/model/TensorRT-LLM/examples/falcon# pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com tensorrt-llm
Looking in indexes: https://pypi.org/simple, https://pypi.nvidia.com
Collecting tensorrt-llm
  Downloading tensorrt-llm-0.5.0.tar.gz (6.8 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-6vg4h7ep/tensorrt-llm_d4a21046e1d44ab8898e9832fb7d80f3/setup.py", line 137, in <module>
          raise RuntimeError(open("ERROR.txt", "r").read())
      RuntimeError:
      ###########################################################################################
      The package you are trying to install is only a placeholder project on PyPI.org repository.
      This package is hosted on NVIDIA Python Package Index.
      
      This package can be installed as:
      ```
      $ pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com tensorrt-llm
      ```
      ###########################################################################################
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

I thought that this particular image would be the most 'batteries-included' way of getting an engine up and running behind on the Triton Inference Server.

**Comment by juney-nvidia** [comment]
Currently it is suggested to still use [the Option3 ](https://github.com/triton-inference-server/tensorrtllm_backend#option-3-build-via-docker)to run TensorRT-LLM Triton backend.

Since TensorRT-LLM just got released two weeks ago, we are working with Triton team to integrate TensorRT-LLM(including the backend) into the Triton image with thorough validation.

Thanks
June

**Comment by harryjulian** [comment]
Hi @juney-nvidia thanks for getting back so quickly. I've previously tried to build the docker image using option 3, but the build was taking >6 hours on my machine and eventually crashing at the final stages (EC2 g5.xlarge).

Are these lengthy builds expected?

**Comment by harryjulian** [comment]
Manged to fix this so closing.

**Comment by tanmayv25** [comment]
@harryjulian  Can you describe how you were able to fix the issue? I am more interested into the original issue that you posted.

`nvcr.io/nvidia/tritonserver:23.10-trtllm-python-py3` image does not include python bindings for tensorrtllm and onnx. The image is expected to be used as a runtime container image for deploying TensorRTLLM engine models hence only contains runtime dependency. The generation and development libraries/dependencies are intentionally removed to keep the container size small.
For generating engines, we would recommend installing these dependencies within/without the container image with the matching tensorrtllm version. Refer to the following llama2 deployment tutorial [here](https://github.com/triton-inference-server/tutorials/blob/main/Popular_Models_Guide/Llama2/trtllm_guide.md#create-engines-for-each-model-skip-this-step-if-you-already-have-an-engine).

**Comment by harryjulian** [comment]
@tanmayv25 Makes sense! 

Fixing it was just a matter of pip installing the repo, as specified in the llama instructions you linked.
