### ISSUE TITLE
free_gpu_memory_fraction not working for examples/apps/openai_server.py

### ISSUE THREAD

**Issue by anaivebird** [NVIDIA/TensorRT-LLM#2350]
### System Info

- GPU： NVIDIA H100 80G
- TensorRT-LLM branch main
- TensorRT-LLM commit: 8681b3a4c0ccc1028bb48d83aacbb690af8f55e7

### Who can help?

@byshiue 

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [x] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

```
cd examples/apps
python3 ./openai_server.py  /tmp/engine/qwen-trt-engine-fusion-1gpu --tokenizer /tmp/qwen-7b
```

### Expected behavior

gpu free memory will be more when free_gpu_memory_fraction set to lower in  examples/apps/openai_server.py

### actual behavior

gpu free memory does not change

### additional notes

no

**Comment by syuoni** [comment]
HI @anaivebird ,

You are right. We should pass the kv_cache_config to the `LLM` constructor here: https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/apps/openai_server.py#L468-L474. Let me fix it.

**Comment by imilli** [comment]
@syuoni The size of the 8-bit model I quantified is 9.95G. However, during inference, the 24G video memory is fully occupied. Is this caused by the parameter "free_gpu_memory_fraction"? If so, when will this problem be fixed? I am also stuck here.

**Comment by imilli** [comment]
The size of my quantized 8-bit model is 9.95G, but during inference, it fills up the 24G gpu memory. Is this caused by the free_gpu_memory_fraction parameter? If so, when will this problem be fixed? I'm also stuck here.

**Comment by imilli** [comment]
@syuoni The size of my quantized 8-bit model is 9.95G, but during inference, it fills up the 24G video memory. Is this caused by the free_gpu_memory_fraction parameter? If so, when will this problem be fixed? I'm also stuck here.

**Comment by imilli** [comment]
@syuoni The size of my quantized 8-bit model is 9.95G, but during inference, it fills up the 24G GPU memory. Is this caused by the free_gpu_memory_fraction parameter? If so, when will this problem be fixed? I'm also stuck here.

**Comment by syuoni** [comment]
The fix has been on the main branch. I'm closing this issue. Thanks!
