### ISSUE TITLE
qwen, tensorrt-llm=0.12.0

### ISSUE THREAD

**Issue by yanglongbiao** [NVIDIA/TensorRT-LLM#2353]
### System Info

Where can I see the enqueue_requests function implementations in Qwen inference in tensorrt-llm.
Where can I see the input header code of the qwen model in tensorRT-llm. 
Where can I view the entry function executed by trtllm-build?

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [x] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

not

### Expected behavior

Find the code implementation

### actual behavior

not

### additional notes

not

**Comment by Superjomn** [comment]
Do you mean the this [enqueue_requests](https://github.com/NVIDIA/TensorRT-LLM/blob/3c46c2794e7f6df48250a68de6240994a77a26a7/examples/bindings/executor/example_advanced.py#L26)? It is based on the C++ runtime's APIs based on pybinding, but the C++ code is close-sourced.

**Comment by nv-guomingz** [comment]
@yanglongbiao  please re-open this issue if you have further questions
