### ISSUE TITLE
test_cpp.py

### ISSUE THREAD

**Issue by weizhi-wang** [NVIDIA/TensorRT-LLM#2354]
run  cpp/tests/resources/scripts/test_cpp.py
          subprocess.CalledProcessError: Command '['cmake', '--build', '/media/data/wwz/TensorRT-LLM/cpp/build', '--config', 'Release', '-j', '--target', 'modelSpec']' returned non-zero exit status 2.
          
          
          
          If there is an issue finding model_spec.so in engine building, manually build model_spec.so by

make -C cpp/build/ modelSpec
error:
      make: Entering directory '/media/data/wwz/TensorRT-LLM/cpp/build'
      make: *** No rule to make target 'modelSpec'.  Stop.
      make: Leaving directory '/media/data/wwz/TensorRT-LLM/cpp/build'

**Comment by Superjomn** [comment]
Thanks for sharing the issue. 
If you are trying to install from source code, please follow the [build-from-source-linux](https://nvidia.github.io/TensorRT-LLM/installation/build-from-source-linux.html) instructions. If not, please offer more information by following [issue template](https://github.com/NVIDIA/TensorRT-LLM/issues/783).

**Comment by weizhi-wang** [comment]
@Superjomn ,I build tensorrt llm completely according to the source code( [build-from-source-linux](https://nvidia.github.io/TensorRT-LLM/installation/build-from-source-linux.html) ), but there is no target modelSpec' in the generated cpp/build/makefile

**Comment by weizhi-wang** [comment]
@Superjomn Thank you. In addition, my other functions can be used normally, but the modelSpec function does not work.
