### ISSUE TITLE
How to rewrite this kernel without referencing the implementation of cutlass

### ISSUE THREAD

**Issue by zhink** [NVIDIA/TensorRT-LLM#2396]
In this kernel     [cpp/tensorrt_llm/kernels/weightOnlyBatchedGemv/cudaCoreGemm.cu](https://github.com/NVIDIA/TensorRT-LLM/blob/f6821ee393be6ec92234f9bb47a4b09f6738050b/cpp/tensorrt_llm/kernels/weightOnlyBatchedGemv/cudaCoreGemm.cu#L43)

How to rewrite this kernel without referencing the implementation of cutlass

**Comment by hello-11** [comment]
@zhink Thanks for your interest in rewriting the kernel. Could you provide more details on why you want to rewrite it and what function you want to implement?

**Comment by zhink** [comment]
Beacuse the project is not easy to reference cutlass3；intput is fp8 e4m3 or e5m2,output is bf16 of float16. If cutlass is not necessary, please provide guidance on how to rewrite it.

**Comment by hello-11** [comment]
@zhink I think this kernel does not use cutlass.

**Comment by zhink** [comment]
but use cutlass::NumericArrayConverter and  Converter::convert

**Comment by chuangz0** [comment]
You can implement numericArrayConverter yourself with reference to cutlass, which is not complicated.
