### ISSUE TITLE
Flag indicate end of stream

### ISSUE THREAD

**Issue by yunfeng-scale** [NVIDIA/TensorRT-LLM#240]
Hi, during request streaming it'll be helpful to have a flag to indicate end of generation. Can you help with this feature request?

**Comment by jdemouth-nvidia** [comment]
Hi @yunfeng-scale ,

Are you asking for a boolean flag as we in the `SendResponseCallback` of the `BatchManager` ([doc](https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/docs/source/batch_manager.md#get-and-send-callbacks))?

Thanks,
Julien

**Comment by yunfeng-scale** [comment]
That's right, looks like the flag is already there in `SendResponseCallback `, then I guess what I'm asking is to include it in the Triton backend implementation https://github.com/triton-inference-server/tensorrtllm_backend/blob/release/0.5.0/inflight_batcher_llm/src/libtensorrtllm.cc#L892

let me know if I should reopen a ticket there

**Comment by jdemouth-nvidia** [comment]
It'd be nice if you could do that. Thanks!

**Comment by nv-guomingz** [comment]
do u still have further issue or question now? If not, we'll close it soon.
