### ISSUE TITLE
Exporting Finetuned Llama models to TensorRT-LLM

### ISSUE THREAD

**Issue by DeekshithaDPrakash** [NVIDIA/TensorRT-LLM#2412]
I have Finetuned Llama2 model with LORA for QA task and now for inference/ streaming I would like to use Triton-llm which requires TensorRT model format. 
Is there any source code/ resources that I can refer to achieve this?
Sadly, there is very little information on this topic.

**Comment by hello-11** [comment]
@DeekshithaDPrakash Thanks for your interest in TrtLLM. You can refer to this repo: https://github.com/triton-inference-server/tensorrtllm_backend.

**Comment by DeekshithaDPrakash** [comment]
> [@DeekshithaDPrakash](https://github.com/DeekshithaDPrakash) Thanks for your interest in TrtLLM. You can refer to this repo: https://github.com/triton-inference-server/tensorrtllm_backend.

Thank you. I have used TRT_LLM for llama2 successfully
