### ISSUE TITLE
[TensorRT-LLM][INFO] Initializing MPI with thread mode 3

### ISSUE THREAD

**Issue by Rumeysakeskin** [NVIDIA/TensorRT-LLM#2426]
### System Info

`!apt-get update && apt-get -y install python3.10 python3-pip openmpi-bin libopenmpi-dev git git-lfs`

`!pip install tensorrt_llm -U --pre --extra-index-url https://pypi.nvidia.com`

`!python -c "import tensorrt_llm"`

### Who can help?

when run these commands ı get below:

`[TensorRT-LLM][INFO] Initializing MPI with thread mode 3`

could you help me fix this issue? 
I want to import tensorrt_llm successfully.

### Information

- [x] The official example scripts
- [ ] My own modified scripts

### Tasks

- [x] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

`!apt-get update && apt-get -y install python3.10 python3-pip openmpi-bin libopenmpi-dev git git-lfs`

`!pip install tensorrt_llm -U --pre --extra-index-url https://pypi.nvidia.com`

`!python -c "import tensorrt_llm"`

### Expected behavior

 import tensorrt_llm successfully

### actual behavior

`[TensorRT-LLM][INFO] Initializing MPI with thread mode 3`

### additional notes

.

**Comment by hello-11** [comment]
@Rumeysakeskin, you can follow this guide: https://nvidia.github.io/TensorRT-LLM/installation/linux.html. Did you install it in the Docker container?

**Comment by Rumeysakeskin** [comment]
> [@Rumeysakeskin](https://github.com/Rumeysakeskin), you can follow this guide: https://nvidia.github.io/TensorRT-LLM/installation/linux.html. Did you install it in the Docker container?

@hello-11 , 
I used `FROM nvidia/cuda:12.1.1-cudnn8-devel-ubuntu22.04` in my own Dockerfile since  my machine has CUDA 12.1.
Do I need to use exactly `nvidia/cuda:12.5.1-devel-ubuntu22.04` instead?

**Comment by hello-11** [comment]
@Rumeysakeskin  Would you mind trying the newer Dockerfile?

**Comment by janelu9** [comment]
> [@Rumeysakeskin](https://github.com/Rumeysakeskin) Would you mind trying the newer Dockerfile?

same . what's your solution？

**Comment by Rumeysakeskin** [comment]
> > [@Rumeysakeskin](https://github.com/Rumeysakeskin) Would you mind trying the newer Dockerfile?
> 
> same . what's your solution？


#### Pull and Run the Docker Image

```
$ docker pull nvcr.io/nvidia/tritonserver:23.10-trtllm-python-py3

$ docker run -it --rm \
    --name triton2 \
    --shm-size=64g \
    --ulimit memlock=-1 \
    --ulimit stack=134217728 \
    -p 2222:8888 \
    --gpus all \
    nvcr.io/nvidia/tritonserver:23.10-trtllm-python-py3
```

This Docker image worked well for me.

---

#### Install Dependencies After Running the Docker Container

Once the Docker container is running, you need to install the following dependencies:
Important Note: TensorRT-LLM depends on TensorRT. In earlier versions that include TensorRT 8, overwriting an upgraded to a new version may require explicitly running: `pip uninstall tensorrt`  to uninstall the old version.

```
# Install dependencies, TensorRT-LLM requires Python 3.10
!apt-get update && apt-get -y install python3.10 python3-pip openmpi-bin libopenmpi-dev git git-lfs

# Install the latest preview version (corresponding to the main branch) of TensorRT-LLM.
# If you want to install the stable version (corresponding to the release branch), please
# remove the `--pre` option.
!conda install mpi4py -y
!pip uninstall torch -y
!pip uninstall tensorrt -y

# !pip3 install tensorrt_llm -U --pre --extra-index-url https://pypi.nvidia.com
!pip3 install tensorrt_llm==0.15.0.dev2024111200 --extra-index-url https://pypi.nvidia.com

```
---

#### Check TensorRT-LLM Installation

After installing TensorRT-LLM, you can check if it is installed correctly by running the following command:
`!python -c "import tensorrt_llm"`

If the installation was successful, you should see an output similar to this:

`[TensorRT-LLM] TensorRT-LLM version: 0.15.0.dev2024111200
`

**Comment by janelu9** [comment]
Thanks , I have installed the latest version successful based on this image `nvcr.io/nvidia/tritonserver:23.10-trtllm-python-py3`

**Comment by janelu9** [comment]
`nvcr.io/nvidia/cuda:12.5.1-cudnn-devel-ubuntu22.04` this image is available too, if `mpi4py` was installed successful at first.
