### ISSUE TITLE
Performance differs on different V100

### ISSUE THREAD

**Issue by sleepwalker2017** [NVIDIA/TensorRT-LLM#246]
Hello, I'm testing llama-13B on two different machines.
The two machines are both with 4*V100.

When I benchmark performance on 2*v100, the TRT-LLM performance differs a lot. While I run FT, the performance is the same.

On the first machine, I get the following benchmarks(the numbers are tokes/sec):
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/26128514/ceb742bd-9650-4dff-a8e5-d82f621aa252)

While on the 2nd machine, FT performs close on most batches, but TRT-LLM differs a lot.
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/26128514/b5acaac4-18e4-45dc-92e1-be868349ec1d)

When I check the kernels, I see the main difference comes from cutlass kernels.
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/26128514/adab0e82-ad55-4fa1-9bee-8c2b5e1b55b4)
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/26128514/d7570cb5-cdd9-4b5e-aed6-8a65abca576f)

Do you have any advice?

**Comment by sleepwalker2017** [comment]
This is the convert script
```shell
python build.py --model_dir $1 \
                --dtype float16 \
                --use_gpt_attention_plugin float16 \
                --use_gemm_plugin float16 \
                --output_dir ./tmp/llama/13B/trt_engines/fp16/2-gpu/ \
                --max_batch_size 24 \
                --world_size 2 \
                --tp_size 2
```

**Comment by jdemouth-nvidia** [comment]
Hi @sleepwalker2017 ,

Are there differences between those two machines or are they supposed to be rigorously the same? One thing to check is the software stack, another is the hardware configuration as well as where they are located. For example, are they running in the same thermal conditions?

Thanks,
Julien

**Comment by sleepwalker2017** [comment]
> Hi @sleepwalker2017 ,
> 
> Are there differences between those two machines or are they supposed to be rigorously the same? One thing to check is the software stack, another is the hardware configuration as well as where they are located. For example, are they running in the same thermal conditions?
> 
> Thanks, Julien

I checked the temperature of the GPU, it's close to each other. 
As far as I can see, the GPU power on the second machine seems a little lower that the 1st one, and the performance is worse.
That's weird. Could this be seen as individual difference？

![image](https://github.com/NVIDIA/TensorRT-LLM/assets/26128514/97491d93-5c91-46c6-9a86-b4641de93492)
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/26128514/ec47d304-f12b-4b31-8999-030c0ea9e97b)

**Comment by juney-nvidia** [comment]
@sleepwalker2017  Another small details to be confirmed: did you invoke the `build.py` script for these two machines correspondingly, or you invoke the `build.py` on one machine, and then use the same built TRT engine on these two machines.

June

**Comment by sleepwalker2017** [comment]
> @sleepwalker2017 Another small details to be confirmed: did you invoke the `build.py` script for these two machines correspondingly, or you invoke the `build.py` on one machine, and then use the same built TRT engine on these two machines.
> 
> June

I build engines for two separate machines. And also, I run the faster engine on the lower machine, the result also gets lower.

**Comment by vicwer** [comment]
@sleepwalker2017 hi,
when I inference gpt2-xl-1.5B[https://huggingface.co/gpt2-large] int8 model, the performance of trt-llm is slower than ft in V100-1GPU...
performance:
```
trt-llm: 60+token/s
ft: 100+token/s
```
prompt:
```
input: Born in north-east France, Soyer trained as a
max out len: 128
t:0.7
```

can you test it? we can compare the performance.

**Comment by nv-guomingz** [comment]
do u still have further issue or question now? If not, we'll close it soon.
