### ISSUE TITLE
llama-7b benchmark batch_size=1 is slower than batch_size=2, what causes this?

### ISSUE THREAD

**Issue by xiaocaoxu** [NVIDIA/TensorRT-LLM#248]
![20231102-155432](https://github.com/NVIDIA/TensorRT-LLM/assets/42837678/062bd542-07f7-43f4-8c65-1f4777b45a3b)
batch_size=2 is 115 tokens, 115/2=57.5, batch_size=1 is 54 tokens
-------------------------------------------------------------------------------------------------------------------------------
python benchmark.py     -m llama_7b     --mode plugin     --batch_size "1;2;4;8;16;32;64"     --input_output_len "13,26"     --engine_dir /models/trt_engines/vicuna-7b/fp16/1-gpu/ --dtype float16 --max_batch_size 64

**Comment by xiaocaoxu** [comment]
dtype is fp16, input_len:13 output_len:25

**Comment by byshiue** [comment]
In general, larger batch size can increase the GPU utilization and hence larger throughput. Do you have any concern?

**Comment by byshiue** [comment]
In general, larger batch size can increase the GPU utilization and hence larger throughput. Do you have any concern?

**Comment by byshiue** [comment]
In general, larger batch size can increase the GPU utilization and hence larger throughput. Do you have any concern?

**Comment by byshiue** [comment]
In general, larger batch size can increase the GPU utilization and hence larger throughput. Do you have any concern?

**Comment by xiaocaoxu** [comment]
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/42837678/1a4d755b-2421-46ff-88f4-f7a781d0405c)
In FasterTransformer result, batch_size=1 is 56, batch_size=2 is 94(94//2=47), batch_size=4 is 185(185//4=46), 56 > 47 > 46, but in TensorRT-LLM result,batch_size=1 is 54, batch_size=2 is 115(115//2=57), batch_size=4 is 226(226//4=56),54 < 57 >56, batch_size=1 expected result should be greater than 57?

**Comment by byshiue** [comment]
In fact, the difference is small (the relative difference of 54 v.s. 56 is about 4%), we often see it as noise unless we ensure the environment of benchmarking is highly stable because there are many factors to affect the performances, including locking clock rate, number of iteration of warmup, and of iteration we run, ...

**Comment by xiaocaoxu** [comment]
Okay, thank you for your reply，I will close this issue.
