### ISSUE TITLE
Generation cannot properly stops at EOS and only stops at max output length

### ISSUE THREAD

**Issue by npuichigo** [NVIDIA/TensorRT-LLM#250]
For baichuan model, both python test script and triton-llm backend cannot properly stop at EOS and only stop at max output length.

For example:
```
python build.py --model_version v2_7b \
                --model_dir ./Baichuan2-7B-Chat \
                --dtype float16 \
                --use_gemm_plugin float16 \
                --use_gpt_attention_plugin float16 \
                --output_dir ./7B_fp16

python run.py --model_version v2_7b --max_output_len=500 --tokenizer_dir ./Baichuan2-7B-Chat --engine_dir=./7B_fp16/
Input: "世界上第二高的山峰是哪座？"
Output: "
珠穆朗玛峰（Mount Everest）是地球上最高的山峰，海拔高度为8,848米（29,029英尺）。排名第二的山峰是喀喇昆仑山脉的乔戈里峰（K2），海拔高度为8,611米（28,251英尺） 。</s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s>"
```

I checked the runtime code and find end_ids passing to `FasterTransformer` dynamic decoder is ignored and always return False for `should_stop`.
https://github.com/NVIDIA/TensorRT-LLM/blob/4de32a86ae92bc49a7ec17c00ec2f2d03663c198/tensorrt_llm/runtime/generation.py#L1597-L1610

**Comment by jdemouth-nvidia** [comment]
Thanks @npuichigo for reporting that issue. I'll ask @byshiue to take a closer look at the issue and keep you posted.

**Comment by npuichigo** [comment]
Just FYI, the error occurs on both release/0.5.0 and main branch.

**Comment by haojiwei** [comment]
> Just FYI, the error occurs on both release/0.5.0 and main branch.

According to [#121](https://github.com/NVIDIA/TensorRT-LLM/issues/121) the buffer set by decode.setup() is prefilled with \<\/s\>.

**Comment by npuichigo** [comment]
@byshiue kindly ask if there's any update on this?

**Comment by byshiue** [comment]
As mentioned above, the buffer set by decode.setup() is prefilled with </s>.

**Comment by npuichigo** [comment]
@byshiue So why the generation don't stop when the first </s> occurs until max length?

**Comment by byshiue** [comment]
The generation would stop when the end_token is generated. But you will see many end_token when you decode the full sentence because the buffer is filled by end_id. 

You can pass `output_sequence_lengths=True` (defined in `generation.py`) to see the real sequence lengths.

**Comment by npuichigo** [comment]
@byshiue you can see my another example here https://github.com/NVIDIA/TensorRT-LLM/issues/90#issuecomment-1784882325

Notice after many `</s>` the LLM starts to generate python codes!
```
"text_output":" System: You are a helpful AI bot. Your name is Bob.\nHuman:  你是谁?\nAI: 我是Bob，一个有用的AI机器人。请问有什么我可以帮助您的？</s></s></s></s></s></s></s></s>\n#!/usr/bin/env python\n# -*- coding: utf-8 -*-\n#"}
```

It's the output of llm triton backend, I never use buffer with `</s>`. Also, if it has stopped, It should not generate other things after `</s>`. Also the request is very slow, it must not early stop at the first `</s>`

**Comment by forrestjgq** [comment]
same problem here

**Comment by byshiue** [comment]
You could check the output ids (before post processing) and the stop ids you get (in pre processing). 

It is possible that the encoded stop words (namely, stop ids) are different to the output ids and hence the generation would not stop.

**Comment by npuichigo** [comment]
1. The grpc request of stop word looks like this and `</s>` is used as stop words.
    ```
    stop_words = ModelInferRequest.InferInputTensor(
        name="stop_words", datatype="BYTES", shape=[1, 1], contents=InferTensorContents(bytes_contents=[b"</s>"]))
    ```
2. Output of preprocessing of stop words https://github.com/triton-inference-server/tensorrtllm_backend/blob/47b609b670d6bb33a5ff113d98ad8a44d961c5c6/all_models/inflight_batcher_llm/preprocessing/1/model.py#L133 shows:
    ```
    [[[2]
      [1]]]
    ```
    Here `2` is the id of `</s>`, it's correct.
3. Output of postprocessing before de-tokenization (https://github.com/triton-inference-server/tensorrtllm_backend/blob/47b609b670d6bb33a5ff113d98ad8a44d961c5c6/all_models/inflight_batcher_llm/postprocessing/1/model.py#L151) shows:
    ```
    [92067    68 92361 92311 66262  7293 92499    70 92360  6461  2193 28846
     66 92361 92311     5     5 92360 93612    65  3050 93122    68 92361
     92430 15725 66145    65 92360 92623  8225  2305  6257 92774  4931 93150
     68 92361     5     5 92360 92392 10329  2602    65  1995 92746 20256
     9320 92481  5034    66 92361 28846  7293 92499    65 92360  3036 92430
     20172 11082 92364    65 35903 92948 20172 27197 92515    66 92361     5
     5 92360 92623 24232  1543  2965  5817  2381 93122    68 92361 92430
     2781 92614    66     5     5 92360  1543  2965  4976  8592  6795    65
     92430  8981 44777  4648 15049    65 35903 93038 42152 27197 92364 35050
     66 92361 28846  7293 92499    65 92360  2026    65  1543  1945  2193
     2062    65 92430 11590    66 92361     5     5 92360 92623 24232  1543
     2965  5817 82993 93122    68 92361 92430  2781 92614    66     5     5
     92360  1543  3160 15236  9320    65 15236  3422    65 15236  6973    66
     92361 28846  7293 92499    65 92360  1543  5332  8592  3036 31663 14368
     3759    65 92492  7205  1543    65  1945 20256  9320 18232    66 92361
     5     5 92360 92623 24232  1543  2965  5817  4264 11538 93122    68
     92361 92430  2781 92614    66     5     5 92360 10991 92569  8176  5650
     26813    65  2350 10849  3854  1576    65  2350 10849  3181  1576    66
     92361 28846  7293 92499    65 92360  1543  6290 92569  3912  5650 26813
     65 34834  5506 29027    65  2848  1937  4139 92385  5160    66 92361
     5     5 92360 23900    65  2762 28846    66 92361 92430 19088 10575
     65 92360 87918  3491  1583 10849  9231    65 69161    66 92361     5
     5 92360 12765 93066  5400    65  1819 20453 20256  9320 18232    66
     92361 28846  7293 92499    65 92360 50696  8176  9482    65  8176  3854
     65  1543  3875  3294  3633  6392  6236    65 69161    66 92361     2
     2     2     2     2     2     2     2     2     2     2     2     2
     2     2 92335 92362 92381 92336 92338 92443 92338 92358 92420     5
     92338 92335 92335 92362 92381 92336 92338 92443 92338 92358 92420 92311
     37557 92311 94361 92311 23747 19264    65 92347 10587 28550  8022    65
     1995 69862 94018 10146 18458 17228]
    ```
    You can see after many `2`s, the generation continues and stop until `max_tokens`.

Maybe stop words should not be specified as what I do? or maybe there's some bug? @byshiue @kaiyux

**Comment by byshiue** [comment]
Can you reproduce this issue on TensorRT-LLM python runtime?

**Comment by npuichigo** [comment]
@byshiue python runtime works as expected. trtllm backend (c++ runtime with all_models/inflight_batcher_llm) seems to have the issue I mentioned above.

**Comment by npuichigo** [comment]
Update: @byshiue it works for grpc if manually set end_id like 
```
end_id = ModelInferRequest.InferInputTensor(
        name="end_id", datatype="UINT32", shape=[1, 1], contents=InferTensorContents(uint_contents=[2]))
```
but what's the different of end_id and stop_words? Only specify stop_words doesn't work
```
stop_words = ModelInferRequest.InferInputTensor(
    name="stop_words", datatype="BYTES", shape=[1, 1], contents=InferTensorContents(bytes_contents=[b"</s>"]))
```
In my understanding, stop_words are converted to end_id and used as that if no end_id is specified. Do I misunderstand the usage of stop_words?

Or you can see this curl example
```
root@50c1d08eb250:/opt/tritonserver# curl -X POST localhost:8000/v2/models/ensemble/generate -d '{"text_input": "System: You are a helpful AI bot. Your name is Bob.\nHuman:  你是谁?\nAI:", "max_tokens": 50, "bad_words": "", "stop_words": "</s>"}'
{"model_name":"ensemble","model_version":"1","sequence_end":false,"sequence_id":0,"sequence_start":false,"text_output":" System: You are a helpful AI bot. Your name is Bob.\nHuman:  你是谁?\nAI: 我是Bob，一个有用的AI机器人。请问有什么我可以帮助您的？</s></s></s></s></s></s></s></s>\n#!/usr/bin/env python\n# -*- coding: utf-8 -*-\n"}
```
`stop_words: </s>` does not work here.

**Comment by byshiue** [comment]
Do you use the `all_models/inflight_batcher_llm/`? We don't support stop_words_list in `all_models/gpt` because it is a python backend and we focus on triton c++ backend.

**Comment by byshiue** [comment]
I cannot reproduce your issue on latest main branch. Do you run on latest main branch? 

If you still have issue, can you fork the repo to prepare the reproduced codes to help debugging?

**Comment by wrfgup** [comment]
> Update: @byshiue it works for grpc if manually set end_id like
> 
> ```
> end_id = ModelInferRequest.InferInputTensor(
>         name="end_id", datatype="UINT32", shape=[1, 1], contents=InferTensorContents(uint_contents=[2]))
> ```
> 
> but what's the different of end_id and stop_words? Only specify stop_words doesn't work
> 
> ```
> stop_words = ModelInferRequest.InferInputTensor(
>     name="stop_words", datatype="BYTES", shape=[1, 1], contents=InferTensorContents(bytes_contents=[b"</s>"]))
> ```
> 
> In my understanding, stop_words are converted to end_id and used as that if no end_id is specified. Do I misunderstand the usage of stop_words?
> 
> Or you can see this curl example
> 
> ```
> root@50c1d08eb250:/opt/tritonserver# curl -X POST localhost:8000/v2/models/ensemble/generate -d '{"text_input": "System: You are a helpful AI bot. Your name is Bob.\nHuman:  你是谁?\nAI:", "max_tokens": 50, "bad_words": "", "stop_words": "</s>"}'
> {"model_name":"ensemble","model_version":"1","sequence_end":false,"sequence_id":0,"sequence_start":false,"text_output":" System: You are a helpful AI bot. Your name is Bob.\nHuman:  你是谁?\nAI: 我是Bob，一个有用的AI机器人。请问有什么我可以帮助您的？</s></s></s></s></s></s></s></s>\n#!/usr/bin/env python\n# -*- coding: utf-8 -*-\n"}
> ```
> 
> `stop_words: </s>` does not work here.

@npuichigo could you please explain how did you solve this problem, which files did you edit. I meet the same problem when using the code on branch release-0.5

**Comment by npuichigo** [comment]
@wrfgup I'm trying to repro that on main branch. To work around this, just pass `end_id` like https://github.com/npuichigo/openai_trtllm/blob/faa6105ea8e1650264b79a95c34d7f6f550b7c65/src/routes/completions.rs#L187

**Comment by npuichigo** [comment]
Works on main branch. Close it.
