### ISSUE TITLE
Cuda OOM when summary llama-2-7b-chat inflight model

### ISSUE THREAD

**Issue by wrfgup** [NVIDIA/TensorRT-LLM#253]
I use the commend below to build the llama-2-7b-chat engine which support inflight_batches

python build.py --model_dir /home/jovyan/LLM_Model/llama-2-7b-chat-hf \
                --dtype float16 \
                --remove_input_padding \
		--use_inflight_batching \
		--paged_kv_cache \
                --use_gpt_attention_plugin float16 \
                --enable_context_fmha \
                --use_gemm_plugin float16 \
                --use_weight_only \
                --output_dir /home/jovyan/LLM_Models/llama-2-7b-chat-trt_engines/weight_only_inflight/1-gpu

after that , I use the command below to run summary

HF_DATASETS_OFFLINE=1 TRANSFORMERS_OFFLINE=1 python summarize.py --test_trt_llm \
                    --hf_model_location /home/jovyan/LLM_Model/llama-2-7b-chat-hf \
                    --data_type fp16 \
                    --engine_dir /home/jovyan/LLM_Models/llama-2-7b-chat-trt_engines/weight_only_inflight/1-gpu \
                    --batch_size 4

and then error occured:

│ /usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py:832 in setup          │
│                                                                                                  │
│    829 │   │   │   else:                                                                         │
│    830 │   │   │   │   kv_cache_type = self.dtype if self.paged_kv_cache else self._tensor_dtyp  │
│    831 │   │   │   │   │   f'present_key_value_{i}')                                             │
│ ❱  832 │   │   │   self.buffer[f'present_key_value_{i}'] = torch.empty(                          │
│    833 │   │   │   │   cache_shape, dtype=kv_cache_type, device=self.device)                     │
│    834 │   │   │   if self.cross_attention:                                                      │
│    835 │   │   │   │   self.buffer[f'cross_present_key_value_{i}'] = torch.empty(                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
OutOfMemoryError: CUDA out of memory. Tried to allocate 64.00 MiB. GPU 0 has a total capacty of 39.39 GiB of which 13.94 MiB is free. Process 223547 has 39.37 GiB memory in use. 
Of the allocated memory 30.94 GiB is allocated by PyTorch, and 19.48 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting 
max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

It seems like paged_kv_cache is incresing without any limit.

My computor is A100 with 40GB cuda memory

**Comment by juney-nvidia** [comment]
@wrfgup Thanks for reporting this. Currently inflight batching hasn't been officially supported in Python runtime(it is on our roadmap and will be shared to the community when ready), to enable it please switch to C++ runtime.

June

**Comment by wrfgup** [comment]
@juney-nvidia Thanks for reply. I want to write a api server with tensorrt-llm to test its cabability, is there any c++ demo(including source code and how to compile)

**Comment by jdemouth-nvidia** [comment]
The code of the TensorRT-LLM Triton backend should be a good starting point. It's here: https://github.com/triton-inference-server/tensorrtllm_backend/tree/release/0.5.0/inflight_batcher_llm

**Comment by jdemouth-nvidia** [comment]
I'm closing that Issue - feel free to re-open it if needed.
