### ISSUE TITLE
Docker Build: Python installs not working?

### ISSUE THREAD

**Issue by atyshka** [NVIDIA/TensorRT-LLM#256]
I am trying to use the docker setup for this repo. The strange behavior I am noticing is that the tensorrt_llm wheel and its dependencies like `transformers` appear to install cleanly while the container is building, but they do not seem to be there when I run the container.

Steps to reproduce:
`make -C docker release_build CUDA_ARCHS="86-real"`
In the output I see:
`#28 11.98 Successfully installed accelerate-0.20.3 build-1.0.3 colored-2.2.3 cuda-python-12.2.0 diffusers-0.15.0 huggingface-hub-0.18.0 lark-1.1.8 pyproject_hooks-1.0.0 safetensors-0.4.0 sentencepiece-0.1.99 tensorrt-llm-0.5.0 tokenizers-0.13.3 transformers-4.33.1`

But when I start the container with `make -C docker run` and execute this ` python -c "import transformers"` I get the following error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'transformers'
```
If I run `pip freeze`, these packages are missing from the output:
```
...
tblib @ file:///rapids/tblib-2.0.0-py3-none-any.whl#sha256=9100bfa016b047d5b980d66e7efed952fbd20bd85b56110aaf473cb97d18709a
tensorboard==2.9.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorrt @ file:///usr/local/tensorrt/python/tensorrt-9.1.0.post12.dev4-cp310-none-linux_x86_64.whl#sha256=efdcd7d365732499f7c0fa3103138fd769f90bb02cf0ee9ed31b7da178897f16
terminado==0.17.1
thinc==8.1.10
threadpoolctl==3.2.0
thriftpy2 @ file:///rapids/thriftpy2-0.4.16-cp310-cp310-linux_x86_64.whl#sha256=879265d504b99a5acd5ee479d58ac4e82d8debb151037b4f488e3d01f092e00b
tinycss2==1.2.1
toml==0.10.2
tomli==2.0.1
toolz @ file:///rapids/toolz-0.12.0-py3-none-any.whl#sha256=2059bd4148deb1884bb0eb770a3cde70e7f954cfbbdc2285f1f2de01fd21eb6f
torch==2.1.0a0+29c30b1
torch-tensorrt @ file:///opt/pytorch/torch_tensorrt/py/dist/torch_tensorrt-2.0.0.dev0-cp310-cp310-linux_x86_64.whl#sha256=1220e0e3b3d67f2536abc547ecdfa1f0c859dea438e4333e4f3daf1672787757
torchdata @ file:///opt/pytorch/data
torchtext @ file:///opt/pytorch/text
torchvision @ file:///opt/pytorch/vision
tornado==6.3.2
tqdm==4.65.0
traitlets==5.9.0
transformer-engine @ git+https://github.com/NVIDIA/TransformerEngine.git@3f01b4f812e0e501257278ec269499ea02b2d4f3
treelite @ file:///rapids/treelite-3.2.0-cp310-cp310-linux_x86_64.whl#sha256=e7b18d6b4e678bac634c620f7ec2075bcf342c58dcd03c827d38f64a82f22b7d
treelite-runtime @ file:///rapids/treelite_runtime-3.2.0-cp310-cp310-linux_x86_64.whl#sha256=5533c60f8a8f5dd4e3127dbb9f16147db7a77facc2c44361e2bd2c25467ed9b1
triton @ file:///tmp/dist/triton-2.1.0%2B440fd1b-cp310-cp310-linux_x86_64.whl#sha256=3f87412b539d21820e40a7a26791fe50d317a8883eec59958c698e267dd6d3f0
typer==0.9.0
...
```
Now everything works if I rebuild the wheel file and install it from within the container. But I shouldn't have to do this, why are the python packages disappearing after the docker build? Can anyone reproduce this behavior following my steps?

**Comment by jdemouth-nvidia** [comment]
Hi @atyshka ,

Can you use

```
make -C docker release_run
```

to run the container. If you take a look at the [Makefile](https://github.com/NVIDIA/TensorRT-LLM/blob/d8ebeee2f6fcb219e6efc541ccc914765799fa3a/docker/Makefile#L115) in the docker folder, you'll see that 

```
make -C docker run
```

maps to

```
make -C docker devel_run
```

It may explain your issue.

Thanks,
Julien

**Comment by atyshka** [comment]
Oh, my bad, thank you!
