### ISSUE TITLE
Qwen2-VL-2B-Instruct convert error

### ISSUE THREAD

**Issue by diandianliu** [NVIDIA/TensorRT-LLM#2574]
Hi, Qwen2-VL-2B-Instruct convert error 

**env:**
tritonserver:24.11-trtllm-python-py3
TensorRT-LLM: 0.15
GPU: v100

**comand:**
python3 vit_onnx_trt.py --pretrained_model_path ./Qwen2-VL-2B-Instruct

**error:**
Unrecognized keys in `rope_scaling` for 'rope_type'='default':{‘mrope_section}’

**Comment by zhangyu68** [comment]
similiar error: TypeError: Qwen2VisionTransformerPretrainedModel.forward() missing 1 required positional argument: 'grid_thw'

**Comment by lessmore991** [comment]
Please tell me how to solve this problem
