### ISSUE TITLE
Failed to install the release wheel for Windows using pip

### ISSUE THREAD

**Issue by ly337** [NVIDIA/TensorRT-LLM#261]
Hi there!

I was trying to install the release wheel for Windows using pip in Anaconda:
`pip install tensorrt_llm --extra-index-url https://pypi.nvidia.com --extra-index-url https://download.pytorch.org/whl/nightly/cu121`

And this is what I got:

> Looking in indexes: https://pypi.org/simple, https://pypi.nvidia.com, https://download.pytorch.org/whl/nightly/cu121
> Collecting tensorrt_llm
>   Using cached https://pypi.nvidia.cn/tensorrt-llm/tensorrt_llm-0.5.0.post1-cp310-cp310-win_amd64.whl (431.5 MB)
> Collecting build (from tensorrt_llm)
>   Using cached build-1.0.3-py3-none-any.whl.metadata (4.2 kB)
> INFO: pip is looking at multiple versions of tensorrt-llm to determine which version is compatible with other requirements. This could take a while.
> Collecting tensorrt_llm
>   Using cached https://pypi.nvidia.cn/tensorrt-llm/tensorrt_llm-0.5.0-0-cp310-cp310-win_amd64.whl (431.5 MB)
> ERROR: Cannot install tensorrt-llm==0.5.0 and tensorrt-llm==0.5.0.post1 because these package versions have conflicting dependencies.
> 
> The conflict is caused by:
>     tensorrt-llm 0.5.0.post1 depends on torch==2.1.0+cu121
>     tensorrt-llm 0.5.0 depends on torch==2.1.0.dev20230828+cu121
> 
> To fix this you could try to:
> 1. loosen the range of package versions you've specified
> 2. remove package versions to allow pip attempt to solve the dependency conflict
> 
> ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

Any hint would be appreciated. Thank you!

**Comment by juney-nvidia** [comment]
@ly337 Hi, thanks for reporting this. There is already an internal fix for this issue. And the fix will be propagated to the github in this week.

June

**Comment by kaiyux** [comment]
Hi @ly337 , we pushed an update to the [main](https://github.com/NVIDIA/TensorRT-LLM/tree/main) branch, including the fix to Windows release wheel installation issue. Thanks.

**Comment by ly337** [comment]
Hi @kaiyux , I tested again with the new command and the installation is successful.

Thanks!
