### ISSUE TITLE
does tensorrt-llm support arrch64?

### ISSUE THREAD

**Issue by tanjatang** [NVIDIA/TensorRT-LLM#262]
Hi,

thanks for the great work!! I'm wondering if it support arrch64?

**Comment by juney-nvidia** [comment]
@tanjatang 

Hi, we do provide the experimental aarch64 support, although with less validation for now. 
You can try with it by yourself.  
When more rigid validation for aarch64 is completed and released, the [support matrix](https://github.com/NVIDIA/TensorRT-LLM#support-matrix) will also be updated correspondingly.

Thanks
June

**Comment by byshiue** [comment]
Close this bug because the issue is inactivated. Feel free to ask here if you still have question/issue, we will reopen the issue.
