### ISSUE TITLE
How to confirm the paged attention is enabled?

### ISSUE THREAD

**Issue by sleepwalker2017** [NVIDIA/TensorRT-LLM#268]
I build the engine using `--paged_kv_cache`, how can I check it's effect?

Using `./benchmarks/gptSessionBenchmark`, I can't see any difference.

**Comment by juney-nvidia** [comment]
When `paged_kv_cache` is enabled, you are expected to see some logging message like

> [TensorRT-LLM][INFO] Using xxx tokens in paged KV cache.

June

**Comment by sleepwalker2017** [comment]
> When `paged_kv_cache` is enabled, you are expected to see some logging message like
> 
> > [TensorRT-LLM][INFO] Using xxx tokens in paged KV cache.
> 
> June

What is the effect of paged attention? For larger batches? I don't know how to see the effect of this feature. Because the memory usage of TRT-LLM is always higher than it really needs.

**Comment by byshiue** [comment]
You could try running inflight batching example because paged attention is necessary in inflight batching. It is hard to see obvious difference in standard workflow (run a request, wait until it finishes, and run a new request)

**Comment by nv-guomingz** [comment]
Hi @sleepwalker2017 please feel free to reopen this ticket if needed.
