### ISSUE TITLE
Does weight only quantization of llama in tensorrt-llm change maximum allowed input length?

### ISSUE THREAD

**Issue by Bhuvanesh09** [NVIDIA/TensorRT-LLM#272]
Got the error:
`ValueError: Couldn't assign past_key_value_0 with shape torch.Size([1, 2, 32, 2747, 128]), engine supports [min, opt, max] = [(1, 2, 32, 0, 128), (4, 2, 32, 1280, 128), (8, 2, 32, 2560, 128)]`

When inputting a text with token length around 2236, and max_output_length = 512. Even though llama's max output length is 4096.

**Comment by juney-nvidia** [comment]
@Bhuvanesh09 
Hi, 

Can you share the concrete steps to reproduce the errors?
We will firstly reproduce it in our environment.

Thanks
June

**Comment by Lzhang-hub** [comment]
@Bhuvanesh09 I have same error, and I chang the  `max_input_len` args in the `build.py` from 1024 to 4096, it solved.

**Comment by byshiue** [comment]
@Bhuvanesh09 You should set the correct `max_input_len` and `max_output_len` during building engine.
