### ISSUE TITLE
Support for combining `repetition_penalty`, `presence_penalty`

### ISSUE THREAD

**Issue by richardliaw** [NVIDIA/TensorRT-LLM#274]
Currently support for these parameters are mutually exclusive. This makes it hard to create an OpenAI compatible API.

cc @akshay-anyscale @Yard1

**Comment by kaiyux** [comment]
The support is included in the latest main branch, please see https://github.com/NVIDIA/TensorRT-LLM/pull/754.

Closing. Please feel free to comment if you have any question, thanks!
