### ISSUE TITLE
The hardware specifications of the GPUs used in the Performance Table.

### ISSUE THREAD

**Issue by Kevin0624** [NVIDIA/TensorRT-LLM#281]
Hello, first of all, thank you for your wonderful work.
In the Performance Table, what interface is used for the H100 and A100 GPUs, respectively (PCIe or SXM)?
What is the VRAM capacity for each (40GB or 80GB)?

Thanks.

**Comment by juney-nvidia** [comment]
Thanks for your interest with our work.

The perf data collected is based on SXM and 80GB memory. 

We will update our documentation to make it more explicit in the future.

Thanks
June

**Comment by whkuo269** [comment]
@juney-nvidia Thank you for your quick response.

**Comment by byshiue** [comment]
Close this bug because the issue is resolved. Feel free to ask here if you still have question/issue, we will reopen the issue.
