### ISSUE TITLE
Quantization preference hierarchy?

### ISSUE THREAD

**Issue by 0xymoro** [NVIDIA/TensorRT-LLM#284]
Hi - wanted to ask a question. I think most folks are familiar with GPTQ & AWQ and relative speeds & quality losses, but int8 weight only (and variants of int8/int4 including with/without smoothquant) as well as fp8 I understand less about and see less in practice.

Would like to verify what I think is true which is fp8 is the best when supported and is the closest to fp16, doubles throughput and halves memory, while other options like int8 with smoothquant/weight only are lesser preferred and only good if fp8 is not available, and even less so is GPTQ/AWQ which introduce much more significant artifacts and quality loss for reduced memory. Is this true always/most of the time? The benchmarks for Llama especially are for fp8 which suggests to me it's the recommended/standard way to serve them with no real loss of quality from fp16 to fp8?

**Comment by 0xymoro** [comment]
Also as a note, it seems like a lot of great optimizations like flash attention and in flight batching aren't enabled by default & users have to dig a bit. Is this intentional? For example the code to quantize & build a 70b llama2:


python quantize.py --model_dir ./tmp/llama/70B \
                   --dtype float16 \
                   --qformat fp8 \
                   --export_path ./quantized_fp8 \
                   --calib_size 512 \

python build.py --model_dir ./tmp/llama/70B \
                --quantized_fp8_model_path ./quantized_fp8/llama_tp1_rank0.npz \
                --dtype float16 \
                --use_gpt_attention_plugin float16 \
                --use_gemm_plugin float16 \
                --output_dir ./tmp/llama/70B/trt_engines/fp8/2-gpu/ \
                --remove_input_padding \
                --enable_fp8 \
                --fp8_kv_cache \
                --world_size 2 \
                --tp_size 2


It doesn't seem to be building a production-ready one, which would rather be:

python build.py --model_dir ./tmp/llama/70B \
                --quantized_fp8_model_path ./quantized_fp8/llama_tp1_rank0.npz \
                --dtype float16 \
                --use_gpt_attention_plugin float16 \
                --use_gemm_plugin float16 \
                --output_dir ./tmp/llama/70B/trt_engines/fp8/2-gpu/ \
                --remove_input_padding \
                --use_inflight_batching \    <-----------------------------here
                --paged_kv_cache \ <-----------------------------here 
                --enable_context_fmha \ <-----------------------------here
                --strongly_typed \ <-----------------------------here
                --enable_fp8 \
                --fp8_kv_cache \
                --world_size 2 \
                --tp_size 2

Is there a reason why the example fp8 build doesn't include these 4 I added? Are there drawbacks, since flash attention seems critical for memory constrained environments that would best use fp8?

**Comment by byshiue** [comment]
For different quantization methods, they have different cons and pros, so users should consider which one is better for their use case. 

For fp8 example, that's only because it is an example, so we only provide the simplest script to run fp8 example successfully.
