### ISSUE TITLE
Cross-attention returns wrong results

### ISSUE THREAD

**Issue by robosina** [NVIDIA/TensorRT-LLM#285]
I wanted to check if the cross-attention mechanism similar to BART's is compatible with tensorrt-llm.

https://github.com/huggingface/transformers/blob/main/src/transformers/models/bart/modeling_bart.py#L132

I assumed it would work when the flag `--use_gpt_attention_plugin` is enabled, but upon looking into it, I noticed that my self-attention heads function well and yield results nearly identical to BART. However, the cross-attention layer produces entirely different values. I'm curious to know if I can utilize this repository for handling this attention mechanism from BART. My strong guess is that it should work fine since, in cross-attention, we merely swap the input with the encoder input. Yet, I can't find why I'm obtaining incorrect results only from the cross-attention layer. I have checked the output of each layer (by binding it to an output) and can confirm that the inputs received by the cross-attention layer are correct.

I'm using `enc-dec` example as the reference.

**Comment by PerkzZheng** [comment]
Are you running on top of the `release/0.5.0` branch or `main` branch ? we have a bug introduced in the main branch. we will fix it soon. 
Please try `release/0.5.0` branch and see if that works.

**Comment by robosina** [comment]
@PerkzZheng, thanks for replying back. I'm currently on the release/0.5.0 branch, and the latest commit is at https://github.com/NVIDIA/TensorRT-LLM/commit/d0b56df751c78d24bf79624ac5633c3988044e8c. I noticed there have been some updates to the batch manager, but they seem unrelated to the issue I'm facing. Should I go ahead and pull the latest commits?

**Comment by PerkzZheng** [comment]
Then, it might not be the same issue as I described. I will loop in someone else who implemented this feature.

**Comment by robosina** [comment]
@PerkzZheng , Thanks, that would be awesome; I've been stuck on this for three days.

**Comment by symphonylyh** [comment]
Hi @robosina, BART and T5 have several structure differences, such as embedding offset, position of the layernorms, relative attention bias, weight names, hidden states scaling at the end of decoder model, etc.. But based on your description, it looks weird. BART's cross attention shouldn't be different from T5's cross attention, as cross attention doesn't involve relative attention bias in both cases, so there is no code change needed to enable BART's cross attn. Are the weights set correctly, i.e. attention weights, layernorm weights, etc.

BTW, we also started on enabling BART and expect it to be supported soon. Stay tuned once it comes out, if you can't succeed for now.

**Comment by robosina** [comment]
@symphonylyh , Thank you for getting back to me and for your assistance. It's definitely puzzling. I've gone through the documentation and adjusted my model, but it's still odd that self-attention works fine while cross-attention doesn't, despite the inputs and layer weights matching those in Hugging Face's models. Is there anything else you think I might need to look into? 

Also, I think a debugging feature in the gpt-attention plugin would be extremely beneficial, like being able to inspect the q, k, v values inside of the attention. I attempted to find the C++ code or CUDA kernels to see where I can see the q,k,v values without success, but maybe in fused mode it would be extremely hard to see those values (If you could help me about this I can somehow fix this). It might be beyond the Python scope( I couldn't find a  `forward` method for it as it's a plugin) and I guess maybe adding a CMAKE option to enable the debugging as a feature inside of the c++ codes would be great, perhaps. My understanding of the architecture is limited, so I could be mistaken, but if it's doable, it would surely make debugging easier for us.

Looking forward for the new features thanks.

**Comment by robosina** [comment]
@symphonylyh @PerkzZheng, could you please take a look at this, my specific question is identifying the point where the encoder's output is input into the model. Shouldn't we provide the encoder output to the model in the lines below?

https://github.com/NVIDIA/TensorRT-LLM/blob/71a5b97b9c588bd2b9688facd5e82307cad98026/tensorrt_llm/runtime/generation.py#L1405-L1415

Upon inspection, I've noticed that the encoder output being received by the TensorRT layer seems incorrect, despite providing the correct PyTorch tensor, so I checked and couldn't find where we are using encoder outputs as the input to the model. I'm examining the tensor outputs at the following location in the code:

https://github.com/NVIDIA/TensorRT-LLM/blob/71a5b97b9c588bd2b9688facd5e82307cad98026/tensorrt_llm/runtime/generation.py#L1452-L1454

**Comment by robosina** [comment]
It fixed Thanks

**Comment by afaghfouri** [comment]
Hi team, is there any updates on this issue? We're also blocked on this atm. Any updates would be appreciated :)

**Comment by symphonylyh** [comment]
@afaghfouri @robosina cheers, BART & mBART are supported now in latest main. Annoucement: https://github.com/NVIDIA/TensorRT-LLM/discussions/670

Please have a try and let us know, thanks!

**Comment by robosina** [comment]
@symphonylyh Sounds great, thanks for informing us and many thanks for the great support
