### ISSUE TITLE
[dev guide] How to see the log print added in python runtime ?

### ISSUE THREAD

**Issue by xorange** [NVIDIA/TensorRT-LLM#289]
### What's this issue about
Asking for some guide for development. 

### the Problem
I'm trying to add some log print inside `tensorrt_llm.runtime.generation`, and expects to see them during 
```
decoder = tensorrt_llm.runtime.GenerationSession(...)
decoder.setup()
decoder.decode()
```

But I can't.

### What I did
the sequence of what I did:
```
vim tensorrt_llm/runtime/generation.py     # add some print(), or logger.error()
python3 ./scripts/build_wheel.py --trt_root /usr/local/TensorRT-9.1.0.4    # incremental rebuild
pip install ./build/tensorrt_llm*.whl    # reinstall
cd examples/baichuan && python run.py --model_version v2_7b --max_output_len=50 --tokenizer_dir /data/services/inner-tts-chinese/data/Baichuan2-7B-Chat --engine_dir=/data/services/inner-tts-chinese/data/Baichuan2-7B-Chat/tensorrt_llm
```

The example run succeeded, but without the logs I added in python runtime.

### the Question
1. How to see the logs I added in python runtime ?
2. Does TensorRT-LLM python backend/runtime support any kinds of `pip install -e` editable install ?
3. Does TensorRT-LLM support stream-line return, i.e. per-token decoding and return during LLM infer ?

**Comment by byshiue** [comment]
Do you reinstall the tensorrt llm again after changing the code?

**Comment by xorange** [comment]
> Do you reinstall the tensorrt llm again after changing the code?

I think I did, hopefully. I use these commands:

> ```
> vim tensorrt_llm/runtime/generation.py     # add some print(), or logger.error()
> python3 ./scripts/build_wheel.py --trt_root /usr/local/TensorRT-9.1.0.4    # incremental rebuild
> pip install ./build/tensorrt_llm*.whl    # reinstall
> cd examples/baichuan && python run.py --model_version v2_7b --max_output_len=50 --tokenizer_dir /data/services/inner-tts-chinese/data/Baichuan2-7B-Chat --engine_dir=/data/services/inner-tts-chinese/data/Baichuan2-7B-Chat/tensorrt_llm
> ```
> 
> The example run succeeded, but without the logs I added in python runtime.
>

**Comment by xorange** [comment]
The added log snippet:

```
diff --git a/tensorrt_llm/runtime/generation.py b/tensorrt_llm/runtime/generation.py
index d20832f..7fbae79 100755
--- a/tensorrt_llm/runtime/generation.py
+++ b/tensorrt_llm/runtime/generation.py
@@ -1795,6 +1795,7 @@ class GenerationSession(object):
    # As dynamic_decoder uses torch's current stream, we must ensure it runs on the same stream that
    # dynamic_decoder was set up with
    @cuda_stream_guard
    def decode(self,
               input_ids: torch.Tensor,
               context_lengths: torch.Tensor,
               sampling_config: SamplingConfig,
               prompt_embedding_table: torch.Tensor = None,
               tasks: torch.Tensor = None,
               prompt_vocab_size: torch.Tensor = None,
               stop_words_list=None,
               bad_words_list=None,
               no_repeat_ngram_size=None,
               streaming: bool = False,
               output_sequence_lengths: bool = False,
               return_dict: bool = False,
               encoder_output: torch.Tensor = None,
               encoder_input_lengths: torch.Tensor = None):
+        logger.error('some print')
         scfg = sampling_config
         batch_size = context_lengths.size(0)
         beam_width = scfg.num_beams
```

**Comment by byshiue** [comment]
Can you try adding some debug code to make sure you really enter the line you change? For example, adding `exit` directly.

**Comment by xorange** [comment]
> Can you try adding some debug code to make sure you really enter the line you change? For example, adding `exit` directly.

I've tried `assert False, ''`. I'll give `exit()` a try.

Is it correct that after `pip install ./build/tensorrt_llm*.whl`, it is **expected** to run the modified code in TensorRT-LLM/ dir ?

**Comment by byshiue** [comment]
Yes. You can also uninstall tensorrt_llm first before installing the new one.

**Comment by xorange** [comment]
Thanks for your kindly reply. And what about my last question ?

> 3. Does TensorRT-LLM support stream-line return, i.e. per-token decoding and return during LLM infer ?

**Comment by xorange** [comment]
Confirmed workflow:

```
vim tensorrt_llm/runtime/generation.py     # add some print(), or logger.error()
python3 ./scripts/build_wheel.py --trt_root /usr/local/TensorRT-9.1.0.4    # incremental rebuild, rebuild logs confirms tensorrt_llm/* are packed in wheel
pip uninstall tensorrt-llm    # otherwise install would be skipped
pip install ./build/tensorrt_llm*.whl    # reinstall. --force-reinstall is much slower and did not work for me
cd examples/baichuan && python run.py ...
```

**Comment by xorange** [comment]
> Thanks for your kindly reply. And what about my last question ?
> 
> > 3. Does TensorRT-LLM support stream-line return, i.e. per-token decoding and return during LLM infer ?

I see GenerationSession.decode( streaming= ). Closing issue, thanks.
