### ISSUE TITLE
How to convert W8A8 engine for ChatGLM2-6b?

### ISSUE THREAD

**Issue by jianyuheng** [NVIDIA/TensorRT-LLM#312]
There seems to be no way to convert huggface to fastertransformer like other models.

**Comment by juney-nvidia** [comment]
@jianyuheng Hi, can you try firstly to follow the other model examples which can convert HuggingFace model to TRT-LLM？

Thanks
June

**Comment by wenqf11** [comment]
Is there any plan to support SmoothQuant for ChatGLM2,3? @juney-nvidia

**Comment by shiqingzhangCSU** [comment]
> Is there any plan to support SmoothQuant for ChatGLM2,3? @juney-nvidia

You may implement SmoothQuant for ChatGLM2, 3 refer to Llama，cause Llama already support SmoothQuant. It only takes a few days to implement.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Please reopen it if needed.
Note that chatGLM should support SQ on latest main branch.
