### ISSUE TITLE
Triton server failed

### ISSUE THREAD

**Issue by konakov-ds** [NVIDIA/TensorRT-LLM#316]
1. Compiled the model with TensorRT-LLM. Everything is fine at this stage
2. Moved the files (lama_float16_tp2_rank0.engine, lama_float16_tp2_rank1.engine, config.json, model.cashe) to the tensorrtllm_backend repository in the folder tensorrtllm_backend/all_models/inflight_batcher_llm/tensorrt_llm/1/, also moved the tokenizer to the folder tensorrtllm_backend/tensorrt_llm/tokenizer
3. Specified settings preprocessing/config.pbtxt - path to tokenizer, the rest as in the manual
4. Started the container - everything is ok
5. Start server python /opt/scripts/launch_triton_server.py --model_repo /all_models/inflight_batcher_llm --world_size 2 I get errors

<img width="871" alt="err1" src="https://github.com/NVIDIA/TensorRT-LLM/assets/67256924/7b44cdb8-f877-4c58-83d8-a8e4e50b1c66">
[
<img width="862" alt="err2" src="https://github.com/NVIDIA/TensorRT-LLM/assets/67256924/541b3a52-cfeb-4c2b-abe7-84426ddffb5e">
](url)

**Comment by byshiue** [comment]
You should ask this question in https://github.com/triton-inference-server/tensorrtllm_backend
