### ISSUE TITLE
memory leak happens on running llama-7b-hf with int8 kv cache + weight only quantization

### ISSUE THREAD

**Issue by forrestjgq** [NVIDIA/TensorRT-LLM#318]
When converting and building llama-7b-hf with int8 kv cache and weight, there might be a memory leaking in running, each time a batch is submitted, about 2~3GB memory growing could be observed by nvidia-smi

Here is my test:

Model building:
```
python /data/jgq/trtllm/examples/llama/hf_llama_convert.py \
-i /data/jgq/lmmodels/7b \
-o /data/jgq/tmpfs \
-t fp16 \
--calibrate-kv-cache \
--tensor-parallelism 1




python /data/jgq/trtllm/examples/llama/build.py --dtype float16 \
--output_dir /data/jgq/tmpfs/int8kv_b8_i1024_o2048/tp1_pp1 \
--max_batch_size 8 --max_input_len 1024 --max_output_len 2048 --world_size 1 \
--tp_size 1 --pp_size 1 \
--remove_input_padding --use_gpt_attention_plugin float16 --use_gemm_plugin float16 \
--enable_context_fmha  --ft_model_dir /data/jgq/tmpfs/1-gpu \
--int8_kv_cache --use_weight_only
```

Test:
```
python chat.py --name int8kv --join \
--engine_dir /data/jgq/tmpfs/int8kv_b8_i1024_o2048/tp1_pp1 \
--tokenizer_dir /data/jgq/lmmodels --output_file int8.json \
--input_tokens /data/jgq/trtllm/samples_1024.json --log_level info
```

the [chat.py](https://github.com/NVIDIA/TensorRT-LLM/files/13294133/chat.py.zip) is attached, and `samples_1024.json` is downloaded from [ppl project](https://github.com/openppl-public/ppl.llm.serving/blob/master/tools/samples_1024.json)

**Comment by byshiue** [comment]
Could you try on latest main branch again?

**Comment by nv-guomingz** [comment]
do u still have further issue or question now? If not, we'll close it soon.
