### ISSUE TITLE
Build failures

### ISSUE THREAD

**Issue by divchenko** [NVIDIA/TensorRT-LLM#32]
Trying to build from source following instructions in 
https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/docs/source/installation.md
via docker. Getting this https://gist.github.com/divchenko/4bcd575954f3a6b5e3350fd2d2762002 

Switched to C++ only build:
python3 ./scripts/build_wheel.py --cuda_architectures "80-real;90-real" --cpp_only --clean
but then building benchmarks fails w/ C++ 11 ABI linking issues... Looking at symbols - looks like only pre-c++11 are built.
Something's serious wrong w/ the setup here.

**Comment by Shixiaowei02** [comment]
Could you please provide more detailed logs? 

```
CMake Error at CMakeLists.txt:268 (message):
  PyTorch >= 1.5.0 is needed for TorchScript mode.


-- Configuring incomplete, errors occurred!
See also "/code/tensorrt_llm/cpp/build/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "/code/tensorrt_llm/./scripts/build_wheel.py", line 248, in <module>
    main(**vars(args))
  File "/code/tensorrt_llm/./scripts/build_wheel.py", line 149, in main
    build_run(
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cmake -DCMAKE_BUILD_TYPE="Release" -DBUILD_PYT="ON" "-DCMAKE_CUDA_ARCHITECTURES=80-real;90-real" -DTRT_LIB_DIR=/usr/local/tensorrt/targets/x86_64-linux-gnu/lib -DTRT_INCLUDE_DIR=/usr/local/tensorrt/include -S "/code/tensorrt_llm/cpp"' returned non-zero exit status 1.
```

Judging from the logs, you are compiling in your own environment, which may encounter some problems that are difficult to solve. We hope you follow these instructions in the documentation:

```
# TensorRT-LLM uses git-lfs, which needs to be installed in advance.
apt-get update && apt-get -y install git git-lfs

git clone https://github.com/NVIDIA/TensorRT-LLM.git
cd TensorRT-LLM
git submodule update --init --recursive
git lfs install
git lfs pull

make -C docker release_build
```

**Comment by divchenko** [comment]
I'm not using my own environment. I was just running build_wheel from inside container.
Following your exact instructions produces same error. Full docker log: https://gist.github.com/divchenko/28f15e4b5ac760b1744d124ffd70d967

**Comment by divchenko** [comment]
I'm running on Amazon Linux, so it uses yum not apt-get , but it should not really matter for the container build.

**Comment by Shixiaowei02** [comment]
If it is a special environment instead of official docker image, this will indeed encounter some difficulties. You may have to refer to [this file](https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/docker/Makefile), with custom `BASE_IMAGE`, `IMAGE_TAG` and try again.

**Comment by divchenko** [comment]
What do you mean by 'special environment' ? My host OS running docker is Amazon linux. I'm running your exact commands. Looks like it picks up nvcr.io/nvidia/pytorch:23.08-py3 image to start building from.

**Comment by Shixiaowei02** [comment]
> make -C docker release_build

If you use `nvcr.io/nvidia/pytorch:23.08-py3`, please provide the complete terminal log from running the first command to the error occured and please do not add custom operations midway. Thanks!

**Comment by divchenko** [comment]
There you go: https://gist.github.com/divchenko/a6b7760738056b44e87ecd638003248b

**Comment by Shixiaowei02** [comment]
Looks like there is no torch installed. What is the console output after running command `pip install torch==2.1.0`? I think you can try this command to build docker. Thanks!
`make -C docker release_build TORCH_INSTALL_TYPE=src_non_cxx11_abi`

**Comment by Shixiaowei02** [comment]
I guess there exists some errors in your PyTorch. Please use the command `make -C docker devel_build` to build the docker firstly. After entering the docker, please show the console output of 

`python -c "import torch; print(torch.__version__,end='\n');"`

Thanks!

**Comment by divchenko** [comment]
Alright, installing torch==2.1.0 inside container fixed it!

**Comment by divchenko** [comment]
To

> I guess there exists some errors in your PyTorch. Please use the command `make -C docker devel_build` to build the docker firstly. After entering the docker, please show the console output of
> 
> `python -c "import torch; print(torch.__version__,end='\n');"`
> 
> Thanks!

2.1.0a0+29c30b1

That's the one, which comes w/ nvcr.io/nvidia/pytorch:23.08-py3

**Comment by Shixiaowei02** [comment]
> To
> 
> > I guess there exists some errors in your PyTorch. Please use the command `make -C docker devel_build` to build the docker firstly. After entering the docker, please show the console output of
> > `python -c "import torch; print(torch.__version__,end='\n');"`
> > Thanks!
> 
> 2.1.0a0+29c30b1
> 
> That's the one, which comes w/ nvcr.io/nvidia/pytorch:23.08-py3

I think this maybe a bug inside CMake other than PyTorch. Thanks for the support and we will report back on this issue.

**Comment by Bhuvanesh09** [comment]
@Shixiaowei02 Any updates on this?

**Comment by jdemouth-nvidia** [comment]
@Bhuvanesh09 , @Shixiaowei02 is working on it but there was a weekend and a day where @Shixiaowei02 was busy with a special event. He’ll update this issue when he has an update or additional question. Thanks.

**Comment by BasicCoder** [comment]
You can add a line of code `message(STATUS "${TORCH_VERSION}")` before this line [CMakeLists.txt](https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/cpp/CMakeLists.txt#L267) to view the actual TORCH_VERSION variable value. Other python output may affect the version judgment.

**Comment by ryxli** [comment]
If using the provided docker container and image, this might occur from inotify watcher limit. 
Pytorch is correctly installed, but the string parse from

```
  execute_process(
    COMMAND
      ${Python3_EXECUTABLE} "-c"
      "from __future__ import print_function; import torch; print(torch.__version__,end='');"
    RESULT_VARIABLE _PYTHON_SUCCESS
    OUTPUT_VARIABLE TORCH_VERSION)
```
could get intercepted by the error log before:
```
>>> import torch
[1698196166.485896] [b0f2772d98f3:4615 :f]        vfs_fuse.c:281  UCX  ERROR inotify_add_watch(/tmp) failed: No space left on device
```
Which makes the version check fail:
```
  if(TORCH_VERSION VERSION_LESS "1.5.0")
    message(FATAL_ERROR "PyTorch >= 1.5.0 is needed for TorchScript mode.")
  endif()
```


To resolve on the host machine just increase the number, it will reflect in the container:
```
$ sudo sh -c "echo fs.inotify.max_user_watches=524288 >> /etc/sysctl.conf"
$ sudo sysctl -p
```

**Comment by Bhuvanesh09** [comment]
@ryxli , 
Thank you. It was indeed the issue. Increasing the max_user_watches solved the issue. Could you please shed some light on how you could debug this?

**Comment by jdemouth-nvidia** [comment]
Thanks for the great help. I’m closing the issue. Reopen if needed.
