### ISSUE TITLE
int8 + vicuna-7b  in T4 output wrong

### ISSUE THREAD

**Issue by AInkCode** [NVIDIA/TensorRT-LLM#322]
build and run below:
python3 examples/llama/build.py --model_dir /code/vicuna-7b-v1.5 \
                --dtype float16 \
                --remove_input_padding \
                --use_gpt_attention_plugin float16 \
                --use_gemm_plugin float16 \
                --use_weight_only \
                --output_dir ./tmp/llama/7B/trt_engines/weight_only/1-gpu/

python3 examples/llama/run.py --max_output_len=10 \
               --engine_dir=./tmp/llama/7B/trt_engines/weight_only/1-gpu/ \
               --tokenizer_dir /code/vicuna-7b-v1.5
               
 output:
 :/code/tensorrt_llm# python3 examples/llama/run.py --max_output_len 10 --engine_dir /tmp/llama/7B/trt_engines/weight_only/1-gpu/ --tokenizer_dir /code/vicuna-7b-v1.5
Running the float16 engine ...
Input: "Born in north-east France, Soyer trained as a"
Output: "san, a, b, both, both,"

How should I solve this problem？Thanks！

**Comment by nv-guomingz** [comment]
Hi @AInkCode ,

I tried to reproduce your issue with our internal main branch but it seems the output is ok

<img width="917" alt="image" src="https://github.com/NVIDIA/TensorRT-LLM/assets/137257613/31c15d29-a512-46c0-af0a-29e9a4266923">.

Would u please share more details for reproducing such issue, like the commit id of tensorrt llm, cuda version?

And I suggest you rebuild the tensorrt with below command.
```python
python scripts/build_wheel.py -a "75-real"  --clean --trt_root /usr/local/tensorrt  -s
```

Thanks,
Guoming

**Comment by AInkCode** [comment]
T4:  NVIDIA-SMI 450.102.04   Driver Version: 450.102.04   CUDA Version: 12.2 
model: https://huggingface.co/lmsys/vicuna-7b-v1.5

Execute the following commands in order:
git clone https://github.com/NVIDIA/TensorRT-LLM.git
cd TensorRT-LLM
git submodule update --init --recursive
git lfs install
git lfs pull
make -C docker release_build
make -C docker release_run
python ./scripts/build_wheel.py -a "75-real"  --clean --trt_root /usr/local/tensorrt  -s
python3 examples/llama/build.py --model_dir /code/vicuna-7b-v1.5 \
                --dtype float16 \
                --remove_input_padding \
                --use_gpt_attention_plugin float16 \
                --use_gemm_plugin float16 \
                --use_weight_only \
                --output_dir ./tmp/llama/7B/trt_engines/weight_only/1-gpu/
python3 examples/llama/run.py --max_output_len=50 \
               --tokenizer_dir /code/vicuna-7b-v1.5 \
               --engine_dir=./tmp/llama/7B/trt_engines/weight_only/1-gpu/
               
output:
:/code/tensorrt_llm# python3 examples/llama/run.py --max_output_len=50                --tokenizer_dir /code/vicuna-7b-v1.5                --engine_dir=./tmp/llama/7B/trt_engines/weight_only/1-gpu/
Running the float16 engine ...
Input: "Born in north-east France, Soyer trained as a"
Output: "san, a, b, both, both, both, both, both, both, both, both, both, both, both, both, both, both, both, both, both, both, both, both, both, both,"

Outputs the same error as before. How should I solve this problem？Thanks！

**Comment by AInkCode** [comment]
@nv-guomingz Hi，

T4: NVIDIA-SMI 450.102.04 Driver Version: 450.102.04 CUDA Version: 12.2
model: https://huggingface.co/lmsys/vicuna-7b-v1.5

Execute the following commands in order:
git clone https://github.com/NVIDIA/TensorRT-LLM.git
cd TensorRT-LLM
git submodule update --init --recursive
git lfs install
git lfs pull
make -C docker release_build
make -C docker release_run
python ./scripts/build_wheel.py -a "75-real" --clean --trt_root /usr/local/tensorrt -s
python3 examples/llama/build.py --model_dir /code/vicuna-7b-v1.5
--dtype float16
--remove_input_padding
--use_gpt_attention_plugin float16
--use_gemm_plugin float16
--use_weight_only
--output_dir ./tmp/llama/7B/trt_engines/weight_only/1-gpu/
python3 examples/llama/run.py --max_output_len=50
--tokenizer_dir /code/vicuna-7b-v1.5
--engine_dir=./tmp/llama/7B/trt_engines/weight_only/1-gpu/

output:
:/code/tensorrt_llm# python3 examples/llama/run.py --max_output_len=50 --tokenizer_dir /code/vicuna-7b-v1.5 --engine_dir=./tmp/llama/7B/trt_engines/weight_only/1-gpu/
Running the float16 engine ...
Input: "Born in north-east France, Soyer trained as a"
Output: "san, a, b, both, both, both, both, both, both, both, both, both, both, both, both, both, both, both, both, both, both, both, both, both, both,"

Outputs the same error as before. How should I solve this problem？Thanks！

**Comment by nv-guomingz** [comment]
Hi @AInkCode 

It seems that I still can't reproduce your issue again by following your steps exactly.

<img width="1241" alt="image" src="https://github.com/NVIDIA/TensorRT-LLM/assets/137257613/abbff381-2fa1-41b3-b86d-77498f214837">

Thanks,
Guoming

**Comment by nv-guomingz** [comment]
Hi @AInkCode 

It seems that I still can't reproduce the issue by following your instructions exactly.

<img width="1241" alt="image" src="https://github.com/NVIDIA/TensorRT-LLM/assets/137257613/07baa2d3-69fd-4a82-abf4-5acfe9b77549">

Would u please try our main branch to see if the issue still exists or not? (B.T.W, I also verified this model on T4 w/ main branch).

Thanks,
Guoming

**Comment by nv-guomingz** [comment]
And May I know your docker version? I saw your're using 450.102.04 and it'd be better to update it to 535.104.05.

**Comment by AInkCode** [comment]
@nv-guomingz hi, my docker image is built by the commands: make -C docker release_build, make -C docker release_run

**Comment by nv-guomingz** [comment]
No, I mean u may need to update the host cuda from 450.102.04 to 535.104.05

**Comment by byshiue** [comment]
Close this bug because the issue is inactivated. Feel free to ask here if you still have question/issue, we will reopen the issue.
