### ISSUE TITLE
Support non LLM transformer networks

### ISSUE THREAD

**Issue by ttim** [NVIDIA/TensorRT-LLM#323]
It would be great to have support for other non LLM, but transformers, use cases in TensorRT-LLM, such as Whisper and/or Stable Diffusion. These networks would benefit tremendously from optimized CUDA kernels/TRT plugins implemented as part of TRT-LLM.

Is it planned?

**Comment by HKAB** [comment]
Agree! Whisper has encoder-decoder architecture, so I think [enc_dec](https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/examples/enc_dec/README.md) would be useful. But it would be great if Whisper is supported officially.

**Comment by ncomly-nvidia** [comment]
Hey @ttim thanks for the ask!! 

Yes, non-LLM transformers may some day be part of TRT-LLM. Right now we are continuing to focus on LLMs, but we will likely expand in the medium term. Whisper (3) & SD are good candidates.

Any other models you are interested in?

**Comment by klvnptr** [comment]
+1 for whisper

**Comment by ncomly-nvidia** [comment]
Whisper support has been [added](https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/whisper)
