### ISSUE TITLE
Is it still necessary to generate gemm_config.in for TensorRT-LLM?

### ISSUE THREAD

**Issue by ehuaa** [NVIDIA/TensorRT-LLM#325]
Is it still necessary to generate gemm_config.in for TensorRT-LLM? 
In the instruction of Bert and other models, there is no steps to generate gemm_config.in like FasterTransformer, 
does TensorRT-LLM choose the best GEMM algorithm automatically？Thanks

**Comment by byshiue** [comment]
You don't need to generate gemm_config in TensorRT-LLM now.
