### ISSUE TITLE
Manually free GPU memory after unloading model?

### ISSUE THREAD

**Issue by eycheung** [NVIDIA/TensorRT-LLM#327]
Is there a way to free the GPU memory in Python without killing the Python process?

For context, I wanted to write a Python function to do several benchmark tasks that would loop over several models. I have a workaround where I can write a bash script instead to call each model in a separate process, but it would be nice if we could dynamically load or unload the models directly from Python.

Thanks!

**Comment by byshiue** [comment]
In python runtime, there are two parts of memory management. The first one is the TensorRT engine, you should be able to delete the engine to free the memory used by TensorRT engine. 

Another part is managed by PyTorch, you could use the method to free PyTorch memory to release them.

**Comment by eycheung** [comment]
Thanks @byshiue , to clarify, is this what you had in mind?
```python
# decoder is a GenerationSession, https://github.com/NVIDIA/TensorRT-LLM/blob/71a5b97b9c588bd2b9688facd5e82307cad98026/tensorrt_llm/runtime/generation.py#L281
del decoder.runtime.engine
gc.collect()
torch.cuda.empty_cache()
```

It seems like GPU memory is not freed after this still (using `nvidia-smi`), so I'm wondering if there is another step I'm missing.

**Comment by byshiue** [comment]
You can try this simple test. 
```python3
    for i in range(3):
        with open(serialize_path, 'rb') as f:
            engine_buffer = f.read()
        decoder = tensorrt_llm.runtime.GenerationSession(model_config,
                                                        engine_buffer,
                                                        runtime_mapping,
                                                        debug_mode=False)
        decoders.append(decoder)
        os.system("nvidia-smi")
        # del decoders[-1]
        os.system("nvidia-smi")
```
When you create the `GenerationSession` three times without `del`, the memory usage increases. If you `del` the decoder, you will see the memory usage increases first time, and keep at the same level in next few iterations. That should be because the cuda memory pool. 

Similar situation in torch side.

**Comment by eycheung** [comment]
Ahh gotcha, ok that makes sense! it works for me, thank you @byshiue
