### ISSUE TITLE
tritonserver lanuched need more gpu-memory than summarize.py scripts test

### ISSUE THREAD

**Issue by hubble-bubble** [NVIDIA/TensorRT-LLM#328]
I test chatglm2-6b,trionserver lanuched the engine model need 30G memory,but summarize.py scripts test the same model need only 16G memory,why?

**Comment by litaotju** [comment]
@hubble-bubble how you build the engine (the build commands/flags)?
triton is using C++ runtime, it has different memory behavior than the python runtime used by summerize.py. 
And the summerize.py is targeted to be an one off example script to demo the API usage, triton and C++ runtime may reserve some memory for better perf.

See the memory usage doc here https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/memory.md, hopes it can help you. 

If you still have question after reading the doc, pls reopen the issue. Thx
