### ISSUE TITLE
can't reach claimed performance on LLaMA 7b

### ISSUE THREAD

**Issue by HikariTJU** [NVIDIA/TensorRT-LLM#329]
Hi I'm running LLaMA 7b using python script in benchmark folder on H100-SXM and got the following result:

> [BENCHMARK] model_name llama_7b world_size 1 num_heads 32 num_kv_heads 32 num_layers 32 hidden_size 4096 vocab_size 32000 precision float16 batch_size 64 input_length 2048 output_length 128 gpu_peak_mem(gb) 74.34 build_time(s) 208.28 tokens_per_sec 1857.9 percentile95(ms) 4412.048 percentile99(ms) 4412.048 latency(ms) 4409.291 compute_cap sm90

throughput is 1857.9, but in performance.md, it's 2,058 tokens/s.  about 10% gap

My running command is:
`python benchmark.py  --enable_fp8 --fp8_kv_cache --max_input_len 2048 --output_dir engines/llama_7b \
    -m llama_7b \
    --mode plugin \
    --batch_size "64" \
    --input_output_len  "2048,128"
`

GPU utilization:
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/30501451/703634ea-c051-4788-a8eb-0fd223e9e9f6)

**Comment by juney-nvidia** [comment]
Thanks for reporting this, and we are confirming with our internal team doing the benchmark for the reported perf number.
When we get more details, we will reply here. 

June

**Comment by ncomly-nvidia** [comment]
Hi @HikariTJU we have published explicit doc / repro for our benchmarks [here](https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/performance.md#reproducing-benchmarked-results). Can you please take a look at those & give them a try?

Note that the python runtime currently isn't up to par with C++ performance. We are working on a "best practices" doc to help with benchmarking.

**Comment by HikariTJU** [comment]
Hi @ncomly-nvidia @juney-nvidia  
 I noticed build args in the doc doesn't use gemm plugin, could you please explain what that is and why it's enabled [here](https://github.com/NVIDIA/TensorRT-LLM/tree/release/0.5.0/examples/llama#fp8-post-training-quantization)?
In my test it will make a lot difference on final perf

**Comment by ncomly-nvidia** [comment]
TensorRT-LLM is built on TensorRT, which is a general purpose compiler that supports arbitrary layers. It also allows users to specify a kernel to execute for a given layer - these are called plugins. TensorRT-LLM lets the user choose if they want to use a plugin or the default TRT implementation for a layer based on these flag. In general, we only provide a plugin if it is faster than TRT's default, but TRT is constantly improving performance. 

Script above is an explicit reproduction for our results, & a general best practice. You're welcome to experiment with the plugins & see for yourself which implementation is faster for your networks!


Closing this for now - feel free to reopen if you'd like!
