### ISSUE TITLE
Will it be integrated into tritonserver-inference?

### ISSUE THREAD

**Issue by coderchem** [NVIDIA/TensorRT-LLM#33]
Hi, I was wondering if there is any plan to integrate into triton-inference-server? flash-attention is not supported in the current release, will it be supported in the future?

**Comment by byshiue** [comment]
TensorRT-LLM is integrated in triton, please refer [tensorrtllm_backend](https://github.com/triton-inference-server/tensorrtllm_backend).

TensorRT-LLM also supports flash-attention like this kernel [fmha_v2_flash_attention_bf16_128_128_S_16_sm80.cubin.cpp](https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/cpp/tensorrt_llm/kernels/contextFusedMultiHeadAttention/cubin/fmha_v2_flash_attention_bf16_128_128_S_16_sm80.cubin.cpp)

**Comment by StarrickLiu** [comment]
> TensorRT-LLM is integrated in triton, please refer [tensorrtllm_backend](https://github.com/triton-inference-server/tensorrtllm_backend).
> 
> TensorRT-LLM also supports flash-attention like this kernel [fmha_v2_flash_attention_bf16_128_128_S_16_sm80.cubin.cpp](https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/cpp/tensorrt_llm/kernels/contextFusedMultiHeadAttention/cubin/fmha_v2_flash_attention_bf16_128_128_S_16_sm80.cubin.cpp)


Hello, I'd like to ask whether the TensorRT-LLM integration includes the latest Flash Decoder introduced in Flash Attention 2?

**Comment by jdemouth-nvidia** [comment]
hi @StarWorkXc , TensorRT-LLM includes an implementation of Flash Attention that is comparable to Flash Attention v2. We implemented some of the tricks mentioned in Tri Dao's awesome work (https://tridao.me/publications/flash2/flash2.pdf). In our benchmarks, our implementation delivers a very good performance. So, long story short, I think the answer could be "yes" :) Thanks.

**Comment by StarrickLiu** [comment]
> hi @StarWorkXc , TensorRT-LLM includes an implementation of Flash Attention that is comparable to Flash Attention v2. We implemented some of the tricks mentioned in Tri Dao's awesome work (https://tridao.me/publications/flash2/flash2.pdf). In our benchmarks, our implementation delivers a very good performance. So, long story short, I think the answer could be "yes" :) Thanks.


Thank you for your hard work and dedication to the project. It's great to see that TensorRT-LLM includes an implementation of Flash Attention that is comparable to Flash Attention v2.

I currently see that the Kernel of TensorRT-LLM's Flash Attention appears to be presented in hexadecimal. Is it possible for us to access its source code? XD
