### ISSUE TITLE
How to profile engine using trtexec

### ISSUE THREAD

**Issue by haojiwei** [NVIDIA/TensorRT-LLM#336]
When I use trtexec to profile engine using command

```
trtexec --loadEngine=<llm.engine> --dynamicPlugins=TensorRT-LLM/cpp/build/tensorrt_llm/plugins/libnvinfer_plugin_tensorrt_llm.so
```

I got coredump error

<img width="738" alt="屏幕截图 2023-11-09 212545" src="https://github.com/NVIDIA/TensorRT-LLM/assets/47234697/c02897b8-dd07-4b22-afee-1639682b8701">

I'm sad I cannot download any file including nsys, ncu profile file from the server. So I can only use the profiler like trtexec or nvprof. Also be glad for providing me with other suggestions for performance analysis.

**Comment by nv-guomingz** [comment]
If you use the docker image by following the [doc](https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/docs/source/installation.md#on-systems-with-gnu-make) , the nsys/ncu are shipped with that container.
You don't need to download nsys/ncu any more.

**Comment by haojiwei** [comment]
> If you use the docker image by following the [doc](https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/docs/source/installation.md#on-systems-with-gnu-make) , the nsys/ncu are shipped with that container. You don't need to download nsys/ncu any more.

I mean I cannot download the profiling  output file like nsys-rep from server to local pc, where download behavior is blocked.

**Comment by juney-nvidia** [comment]
@haojiwei 
Sorry, but it is suggested to use nsys/ncu to do the profiling for TensorRT-LLM. 

June

**Comment by haojiwei** [comment]
> @haojiwei Sorry, but it is suggested to use nsys/ncu to do the profiling for TensorRT-LLM.
> 
> June

I wonder what causes the segfault

**Comment by wm2012011492** [comment]
Could try real shapes by `trtexec  --shapes=...` based on your bs and sequence length? Otherwise, the dynamic shape will be set 1 as default.

**Comment by haojiwei** [comment]
> Could try real shapes by `trtexec --shapes=...` based on your bs and sequence length? Otherwise, the dynamic shape will be set 1 as default.

I profile for the LLamaForCausalLM, and tried 
`--shapes=input_ids:1x1 --exportProfile=./profile.json --exportOutput=./output.json --exportTimes=./times.json`.

There is no more output after starting inference and none of ./profile.json or ./output.json or ./times.json

**Comment by byshiue** [comment]
Close this bug because the issue is inactivated. Feel free to ask here if you still have question/issue, we will reopen the issue.
