### ISSUE TITLE
Attribute issue while executing build.py file

### ISSUE THREAD

**Issue by atharvnagrikar** [NVIDIA/TensorRT-LLM#34]
I installed all the dependencies and tried to run build.py file for llama2, but the following issue

Traceback (most recent call last):
  File "/home/shavak/wk-atharv/WebScrappingChatBot/llm/udemy/TensorRT-LLM/examples/llama/build.py", line 25, in <module>
    from weight import (get_scaling_factors, load_from_awq_llama, load_from_binary,
  File "/home/shavak/wk-atharv/WebScrappingChatBot/llm/udemy/TensorRT-LLM/examples/llama/weight.py", line 25, in <module>
    import tensorrt_llm
  File "/home/shavak/wk-atharv/WebScrappingChatBot/llm/udemy/TensorRT-LLM/examples/llama/tensorrt_llm/__init__.py", line 15, in <module>
    import tensorrt_llm.functional as functional
  File "/home/shavak/wk-atharv/WebScrappingChatBot/llm/udemy/TensorRT-LLM/examples/llama/tensorrt_llm/functional.py", line 25, in <module>
    from . import graph_rewriting as gw
  File "/home/shavak/wk-atharv/WebScrappingChatBot/llm/udemy/TensorRT-LLM/examples/llama/tensorrt_llm/graph_rewriting.py", line 11, in <module>
    from .network import Network
  File "/home/shavak/wk-atharv/WebScrappingChatBot/llm/udemy/TensorRT-LLM/examples/llama/tensorrt_llm/network.py", line 26, in <module>
    from ._common import set_network
  File "/home/shavak/wk-atharv/WebScrappingChatBot/llm/udemy/TensorRT-LLM/examples/llama/tensorrt_llm/_common.py", line 21, in <module>
    from ._utils import str_dtype_to_trt
  File "/home/shavak/wk-atharv/WebScrappingChatBot/llm/udemy/TensorRT-LLM/examples/llama/tensorrt_llm/_utils.py", line 81, in <module>
    int64=trt.int64,
AttributeError: module 'tensorrt' has no attribute 'int64'
'

Can anayone please help

**Comment by byshiue** [comment]
Can you check your tensorrt version? TensorRT-LLM requires TensorRT 9.1.

**Comment by atharvnagrikar** [comment]
tensorrt version:- 8.6.1.post1 with python version of 3.9

**Comment by atharvnagrikar** [comment]
is there any command using pip or conda for the upgrading the tensorrt

**Comment by byshiue** [comment]
Sorry for inconvenience. TRT 9 is not updated to pypi. 

You can download on https://developer.nvidia.com/downloads/compute/machine-learning/tensorrt/secure/9.1.0/tars/tensorrt-9.1.0.4.linux.x86_64-gnu.cuda-12.2.tar.gz, and install the `.whl` file in `TensorRT-9.1.0.4/python/` after extraction.

**Comment by atharvnagrikar** [comment]
ok thanks, do I  need to uninstall the previous version of tensorrt

**Comment by byshiue** [comment]
> ok thanks, do I need to uninstall the previous version of tensorrt

I think it is fine. But you can uninstall it first.

**Comment by atharvnagrikar** [comment]
tensorrt-9.1.0.post11.dev4-cp310-none-linux_x86_64.whl
tensorrt-9.1.0.post11.dev4-cp311-none-linux_x86_64.whl
tensorrt-9.1.0.post11.dev4-cp36-none-linux_x86_64.whl
tensorrt-9.1.0.post11.dev4-cp37-none-linux_x86_64.whl
tensorrt-9.1.0.post11.dev4-cp38-none-linux_x86_64.whl
tensorrt-9.1.0.post11.dev4-cp39-none-linux_x86_64.whl
tensorrt_dispatch-9.1.0.post11.dev4-cp310-none-linux_x86_64.whl
tensorrt_dispatch-9.1.0.post11.dev4-cp311-none-linux_x86_64.whl
tensorrt_dispatch-9.1.0.post11.dev4-cp36-none-linux_x86_64.whl
tensorrt_dispatch-9.1.0.post11.dev4-cp37-none-linux_x86_64.whl
tensorrt_dispatch-9.1.0.post11.dev4-cp38-none-linux_x86_64.whl
tensorrt_dispatch-9.1.0.post11.dev4-cp39-none-linux_x86_64.whl
tensorrt_lean-9.1.0.post11.dev4-cp310-none-linux_x86_64.whl
tensorrt_lean-9.1.0.post11.dev4-cp311-none-linux_x86_64.whl
tensorrt_lean-9.1.0.post11.dev4-cp36-none-linux_x86_64.whl
tensorrt_lean-9.1.0.post11.dev4-cp37-none-linux_x86_64.whl
tensorrt_lean-9.1.0.post11.dev4-cp38-none-linux_x86_64.whl
tensorrt_lean-9.1.0.post11.dev4-cp39-none-linux_x86_64.whl


There multiple files provided which .whl file do i need to install

**Comment by byshiue** [comment]
You can install `tensorrt-9.1.0.post11.dev4-*` and choose the python version you use.

**Comment by atharvnagrikar** [comment]
also after installation do i need to export path

**Comment by atharvnagrikar** [comment]
As  I install .whl file but still encountered the following error

  File "/home/shavak/wk-atharv/WebScrappingChatBot/llm/udemy/TensorRT-LLM/examples/llama/build.py", line 21, in <module>
    import tensorrt as trt
  File "/home/shavak/wk-atharv/WebScrappingChatBot/llm/udemy/TensorRT-LLM/anaconda/lib/python3.9/site-packages/tensorrt/__init__.py", line 71, in <module>
    from .tensorrt import *
ImportError: libnvinfer.so.9: cannot open shared object file: No such file or directory

**Comment by byshiue** [comment]
Do you export `TensorRT-9.1.0.4/lib/` into `LD_LIBRARY_PATH`?

**Comment by atharvnagrikar** [comment]
yes, and the error is resolved. I encountered another error regarding lib file for tensorrt-llm. I git pull the files, but able to see any lib file

    self._handle = _dlopen(self._name, mode)
OSError: /home/shavak/wk-atharv/WebScrappingChatBot/llm/udemy/TensorRT-LLM/examples/llama/tensorrt_llm/libs/libnvinfer_plugin_tensorrt_llm.so: cannot open shared object file: No such file or directory

**Comment by byshiue** [comment]
It looks you don't install tensorrt_llm successfully. You can refer the document https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/docs/source/installation.md to install tensorrt_llm.

**Comment by atharvnagrikar** [comment]
ok, thanks for the help. Really appreciate for your patience

**Comment by arjunanand13** [comment]
I GET THIS ERROR WHILE INSTALLING LATEST TENSOR RT

Collecting tensorrt==9.1.0.post11.dev4
  Downloading tensorrt-9.1.0.post11.dev4.tar.gz (6.8 kB)
  error: subprocess-exited-with-error
× python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by jdemouth-nvidia** [comment]
Hi @arjunanand13 ,

First, it might not be needed to use uppercase to report issues. The members of the TensorRT-LLM team are trying their best to help.

Regarding the issue, can you tell us which command leads to such a result, please? I suspect it's not coming from `build.py` but I may be wrong.

Thanks,
Julien

**Comment by arjunanand13** [comment]
I get this error while installing the package 
pip install tensorrt-dispatch-bindings==9.1.0.post12.dev4

**Comment by byshiue** [comment]
> I get this error while installing the package pip install tensorrt-dispatch-bindings==9.1.0.post12.dev4

Why do you want to install the package? You can install tensorrt by 
```
pip install tensorrt-9.1.0.post12.dev4-cp311-none-linux_x86_64.whl
```
