### ISSUE TITLE
Inflight batching freezes whole server when using end_id or when input has \" (and sometimes without known trigger) at moderate batchsizes

### ISSUE THREAD

**Issue by 0xymoro** [NVIDIA/TensorRT-LLM#340]
This is a critical issue as it's not just the one request being frozen, it effectively shuts down the entire Triton server so all other concurrent requests are frozen and all future requests too. Been finding it really hard to work around an issue where specifying end_id or even having escaped double quotes will make the runtime freeze. 

To replicate - I'm using 2x H100 SXM, with TP=2, CUDA 12.2:
1. Build a Llama fp8 engine using latest in main branch (I used 70b)
2. Build latest in Triton backend using its main branch
3. Run it using curl command, set batchsize to 8 or above and specify end_id = 2, or have escaped quotes \\" in the input string

printf '%s\n' {1..10} | xargs -I % -P 10 curl -X POST https://endpoint/v2/models/ensemble/generate -d @temp.txt

The server will then freeze, and no additional requests will give any responses in the http server. Those above are reliable triggers in my case but the conditions don't seem exhaustive so there's likely some underlying issue (but the greater issues are that 1.) there is no error logging, and 2.) it halts the entire server)

There are no error logs to note even on highest verbosity, other than the last of these:
I1110 01:48:09.388102 11292 libtensorrtllm.cc:1061] {"Active Request Count":16,"Context Requests per Iteration":0,"Free KV cache blocks":785,"Generation Requests per Iteration":3,"Iteration Counter":170,"Max KV cache blocks":1313,"Max Request Count":256,"MicroBatch ID":0,"Runtime CPU Memory Usage":440,"Runtime GPU Memory Usage":35742688,"Runtime Pinned Memory Usage":256,"Scheduled Requests per Iteration":3,"Timestamp":"11-10-2023 01:48:09","Tokens per KV cache block":64,"Total Context Tokens per Iteration":0,"Used KV cache blocks":32}

Being stuck forever.

**Comment by 0xymoro** [comment]
Build engine command:

python build.py --model_dir /mnt/pvc/v2.1 --quantized_fp8_model_path /mnt/pvc/v2.1-fp8-npz/llama_tp1_rank0.npz --dtype float16 --use_gpt_attention_plugin float16 --use_gemm_plugin float16 --output_dir /mnt/pvc/v2.1-trtllm-fp8-tp2 --remove_input_padding --use_inflight_batching --paged_kv_cache --enable_context_fmha --max_input_len 4096 --max_batch_size 128 --strongly_typed --enable_fp8 --fp8_kv_cache --world_size 2 --tp_size 2

TRTLLM main branch, Triton backend main branch (not 0.5.0 release due to stop_words fix in main), both built from source into docker image.

Query itself: it's ~9000 characters of prompt to simulate long context queries.

**Comment by 0xymoro** [comment]
Hi @Shixiaowei02, thanks for triaging the issue. I saw the main was updated, let me know if you think I should try again and will do another build, or if this needs more time to resolve. If I can do more logging of any sort that might be helpful please advise too, thanks.

**Comment by byshiue** [comment]
Do you still encounter the issue on latest main branch?

**Comment by nv-guomingz** [comment]
do u still have further issue or question now? If not, we'll close it soon.
