### ISSUE TITLE
Why does the llama-13b model take up 72G after loading into GPU memory

### ISSUE THREAD

**Issue by shatealaboxiaowang** [NVIDIA/TensorRT-LLM#343]
I really hope to get your reply. thank you

**Comment by byshiue** [comment]
Please share more details. Where do you encounter your issue (converting model, building engine or runtime) and what script do you use?

**Comment by byshiue** [comment]
Close this bug because the issue is inactivated. Feel free to ask here if you still have question/issue, we will reopen the issue.
