### ISSUE TITLE
How to build a gpu kernel debug version ?

### ISSUE THREAD

**Issue by hudengjunai** [NVIDIA/TensorRT-LLM#344]
How to **debug kernel**
I have compile a debug version with following comands
```
python3 scripts/build_wheel.py  --build_type RelWithDebInfo --clean --trt_root /usr/local/tensorrt
```
but failed to debug into the kernel. When I debug some c++ example with cuda-gdb, I cannot step into the kernel thread.

Then I insert compile opts '-G' to nvcc compile in order to add device debug ability, but failed to build the libnvinfer_tensorrt_llm.so library. the link bug show 
```
ld: failed to convert GOTPCREL relocation; relink with --no-relax
```
After add the no-relax flag to link, there still have link error.

So. How can I compile a debug version and stepInto the kernel function to check some logic

**Comment by Shixiaowei02** [comment]
We will take a look at this issue and thanks for your attention!

**Comment by ZhiqiJiang** [comment]
I have the same requirement and is there any update?

**Comment by butterluo** [comment]
+1. 
Still can NOT build a debug version, 
When add a -G to CMAKE_CUDA_FLAGS_DEBUG, it cause a bug: 'PC-relative offset overflow in PLT entry'.
And add -mcmodel=large did not help.

**Comment by avianion** [comment]
@butterluo the kernel is proprietary, so makes sense they wouldn't allow it to be debugged

**Comment by nv-guomingz** [comment]
please feel free to reopen this ticket if needed.
