### ISSUE TITLE
[Feature request] AutoAWQ support

### ISSUE THREAD

**Issue by Sanster** [NVIDIA/TensorRT-LLM#345]
Compared to nvidia_ammo, [AutoAWQ](https://github.com/casper-hansen/AutoAWQ) supports more models and it is also relatively easy to add new models.

**Comment by ncomly-nvidia** [comment]
ACK! AMMO is a new, experimental tool we are working on that support *many* quantization techniques which we are constantly improving. Thanks for the pointer to AutoAWQ & its easy of use!

Are there any models X precisions in particular you're looking for?

**Comment by Sanster** [comment]
I want to try awq on the [QWen](https://github.com/QwenLM/Qwen) model. I am now able to use ammo and TensorRT-LLM for int4 quantization and inference on qwen, referencing this project: https://github.com/Tlntin/Qwen-7B-Chat-TensorRT-LLM#%E8%BF%90%E8%A1%8C%E6%8C%87%E5%8D%97int4-awq%E7%AF%87

**Comment by ncomly-nvidia** [comment]
Glad you were able to get QWen with AWQ working! I'll leave close this for now, but the AMMO team is looking into the ease-of-use differences to AutoAWQ. Feel free to re-open or file a new issue if you'd like.

**Comment by Hongbosherlock** [comment]
> Glad you were able to get QWen with AWQ working! I'll leave close this for now, but the AMMO team is looking into the ease-of-use differences to AutoAWQ. Feel free to re-open or file a new issue if you'd like.

Hi, I have question about calib data  before using AMMO for AWQ Quantization

Please see https://github.com/NVIDIA/TensorRT-LLM/issues/565

**Comment by Hongbosherlock** [comment]
> ACK! AMMO is a new, experimental tool we are working on that support _many_ quantization techniques which we are constantly improving. Thanks for the pointer to AutoAWQ & its easy of use!
> 
> Are there any models X precisions in particular you're looking for?

Sorry to bother you again. I encountered an issue when using AMMO to quantize my model in `int4_awq` , while it worked fine with AutoAWQ. The reason is that AMMO does not support llama custom models with `bias`. Please take a look here:https://github.com/NVIDIA/TensorRT-LLM/issues/885
