### ISSUE TITLE
TensorRT 9 not available

### ISSUE THREAD

**Issue by david-PHR** [NVIDIA/TensorRT-LLM#35]
Hello,

The release notes said that TensorRT-LLM requires TensorRT 9.1.0.4 and 23.08 containers. 
Where can I find TensorRT 9.1.0.4? This version seems not available yet unfortunately

Thanks

**Comment by Shixiaowei02** [comment]
You can find TensorRT 9 on https://github.com/NVIDIA/TensorRT/releases/tag/v9.1.0 or https://developer.nvidia.com/downloads/compute/machine-learning/tensorrt/secure/9.1.0/tars/tensorrt-9.1.0.4.linux.x86_64-gnu.cuda-12.2.tar.gz

What's more, we suggest to build TensorRT-LLM by the method described in the [Installation Documentation](https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/docs/source/installation.md).

**Comment by ralbertazzi** [comment]
When is the documentation of TensorRT 9 coming out?

**Comment by jdemouth-nvidia** [comment]
Let me ask the TensorRT team and get back to you.

**Comment by david-PHR** [comment]
Hello, any news regarding the documentation?

**Comment by maxmelichov** [comment]
Hey, when we can expect TensorRT 9 to come to windows?
