### ISSUE TITLE
inflight_batching

### ISSUE THREAD

**Issue by wm901115nwpu** [NVIDIA/TensorRT-LLM#354]
1. where the source code about infight_batching?
2. What's the difference between the batch mannager and infight_batching. 
3. Will you open source about batch mannager?

**Comment by byshiue** [comment]
1/2. inflight_batching is put in batch_manager and it is part of batch_manager. 
3. We cannot claim anything.

**Comment by byshiue** [comment]
Close this bug because the issue is resolved. Feel free to ask here if you still have question/issue, we will reopen the issue.
