### ISSUE TITLE
Understanding the Role of `encoder_input_lengths` in enc_dec example

### ISSUE THREAD

**Issue by robosina** [NVIDIA/TensorRT-LLM#356]
I'm curious about the role of `encoder_input_lengths` in the decoder's auto-regressive generation, as referenced in the following code snippet:

https://github.com/NVIDIA/TensorRT-LLM/blob/71a5b97b9c588bd2b9688facd5e82307cad98026/examples/enc_dec/run.py#L246

My understanding is that the primary connection between the decoder and the encoder should be the encoder's output, which is used in the decoder's cross-attention mechanism. However, I noticed that changing the `encoder_input_lengths` variable leads to different outputs from the cross-attention layers. Could you explain why `encoder_input_lengths` is being passed as an input here? and what it is exactly!

Thanks

**Comment by byshiue** [comment]
In cross attention, we need to know the lengths from encoder output to skip the padding in encoder output.

**Comment by robosina** [comment]
@byshiue 

> we need to know the lengths from encoder output to skip

So it's the encoder output length not input length? thanks

**Comment by byshiue** [comment]
What do you mean for input length?

**Comment by robosina** [comment]
@byshiue, I'm trying to clarify(maybe I need to investigate this myself and questioning in here is not correct due to my lack of knowledge), so this parameter(`encoder_input_lengths`) isn't about the data inputted into the encoder, is it? We input data into the encoder and receive an output. So, is this parameter about the length of that output? I'm confused because of how the variable is named; it seems like it refers to the length of the data we input into the encoder, which I'm not quite understanding. Thanks for any clarification.

**Comment by byshiue** [comment]
The lengths of encoder_input and encouder_output are same, so we use it in decoder directly.
