### ISSUE TITLE
Command 'cmake --build . --config Release --parallel 64 --target tensorrt_llm tensorrt_llm_static nvinfer_plugin_tensorrt_llm th_common ' returned non-zero exit status 1

### ISSUE THREAD

**Issue by GeneralJing** [NVIDIA/TensorRT-LLM#359]
when i executed "python3 ./scripts/build_wheel.py --trt_root /usr/local/tensorrt", I met the errors below.

[notice] A new release of pip is available: 23.3 -> 23.3.1
[notice] To update, run: python3 -m pip install --upgrade pip
Error: could not load cache
Traceback (most recent call last):
  File "/home/jingzy/temp/TensorRT-LLM/./scripts/build_wheel.py", line 248, in <module>
    main(**vars(args))
  File "/home/jingzy/temp/TensorRT-LLM/./scripts/build_wheel.py", line 152, in main
    build_run(
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cmake --build . --config Release --parallel 64 --target tensorrt_llm tensorrt_llm_static nvinfer_plugin_tensorrt_llm th_common ' returned non-zero exit status 1.

my gpu is NVIDIA GeForce RTX 3090.

**Comment by Shixiaowei02** [comment]
Please refer to https://github.com/NVIDIA/TensorRT-LLM/issues/297, thanks!

**Comment by Shixiaowei02** [comment]
I'm closing that issue. Feel free to reopen if needed.
