### ISSUE TITLE
[Feature request] Support MBartForCausalLM Request!!!

### ISSUE THREAD

**Issue by sjtu-cz** [NVIDIA/TensorRT-LLM#360]
Can you provide an example for MBartForCausalLM?

**Comment by byshiue** [comment]
This model is not supported in TensorRT-LLM now. You can create/change an issue to request this feature.

**Comment by sjtu-cz** [comment]
> This model is not supported in TensorRT-LLM now. You can create/change an issue to request this feature.

Could you please give an estimate of when MBartForCausalLM will be supported?

**Comment by sjtu-cz** [comment]
<img width="977" alt="image" src="https://github.com/NVIDIA/TensorRT-LLM/assets/20858982/6ac769b4-a655-45ae-8d2b-a1ce826327a5">
so, according to the code, the position_embedding is not well support yet?

**Comment by byshiue** [comment]
`position_embedding` is defined in line 51 if needed.

**Comment by sjtu-cz** [comment]
sorry，I want to know What are the unsupported features in MBartForCausalLM?

**Comment by sjtu-cz** [comment]
Besides, does tensorrt-llm currently support Swin-Transformer well now?

**Comment by byshiue** [comment]
Sorry, I am not familiar with MBartForCausalLM, so I don't know what features are missed now. 

TensorRT-LLM does not support Swin Transformer now.

**Comment by sjtu-cz** [comment]
Will I be notified after support?

**Comment by byshiue** [comment]
Yes.

**Comment by sjtu-cz** [comment]
您好，你的邮件我已经收到~

**Comment by symphonylyh** [comment]
@sjtu-cz BART and mBART support are in progress. But current plan is to support `MBartForConditionalGeneration`. After that is supported, can you please customize based on that and adapt to your `MBartForCausalLM` use case?

**Comment by sjtu-cz** [comment]
> @sjtu-cz BART and mBART support are in progress. But current plan is to support `MBartForConditionalGeneration`. After that is supported, can you please customize based on that and adapt to your `MBartForCausalLM` use case?

OK，Can you guarantee that it is fully supported for MBartForCausalLM?
I will try and if there are any problems, I will submit the corresponding issue.

**Comment by symphonylyh** [comment]
@sjtu-cz yes, we verified mBART internally and will be released soon. Stay tuned!

**Comment by sjtu-cz** [comment]
> @sjtu-cz yes, we verified mBART internally and will be released soon. Stay tuned!

OK, looking forward to it！

**Comment by symphonylyh** [comment]
@sjtu-cz BART and mBART are both done in the dev main branch! https://github.com/NVIDIA/TensorRT-LLM/discussions/670

Closing the issue for now. Please feel free to reopen if you have follow-up questions!

**Comment by sjtu-cz** [comment]
Great work！

**Comment by sjtu-cz** [comment]
<img width="1593" alt="image" src="https://github.com/NVIDIA/TensorRT-LLM/assets/20858982/a45f9c1e-1229-4bc5-b9e1-25fa9163438d">
when I adapt to your MBartForCausalLM，I meet the above err，i need some help.

**Comment by sjtu-cz** [comment]
> @sjtu-cz yes, we verified mBART internally and will be released soon. Stay tuned!

Could you please help reopen the issue?

**Comment by sjtu-cz** [comment]
Could you please help reopen the issue? @symphonylyh

**Comment by symphonylyh** [comment]
@sjtu-cz did you say you encountered some issue? But I couldn't find your comment. Is it resolved?

**Comment by sjtu-cz** [comment]
I found the Nougat model is supported,  can u add the support for Donut, for example naver-clova-ix/donut-base-finetuned-cord-v2?

**Comment by sjtu-cz** [comment]
I I successfully ran through nougat's demo, and successfully converted and built naver-clova-ix/donut-base-finetuned-cord-v2, but it only output a token during the decoding process. What's going on? thing? args.max_new_tokens I set to 768

**Comment by sjtu-cz** [comment]
<img width="1604" alt="image" src="https://github.com/NVIDIA/TensorRT-LLM/assets/20858982/82b61e71-12c3-4158-9f28-7e63e0fdb708">

**Comment by sjtu-cz** [comment]
by the way, the right output is 
<img width="1562" alt="image" src="https://github.com/NVIDIA/TensorRT-LLM/assets/20858982/ec9c1ead-33ab-4e46-939f-800d538a7d22">
https://huggingface.co/docs/transformers/main/model_doc/donut
<img width="1366" alt="image" src="https://github.com/NVIDIA/TensorRT-LLM/assets/20858982/b72fcd04-3baf-41f3-9864-3cc7c215c281">

**Comment by sjtu-cz** [comment]
export MODEL_NAME="donut-base-finetuned-cord-v2"
git clone https://huggingface.co/naver-clova-ix/${MODEL_NAME} tmp/hf_models/${MODEL_NAME}
python3 ../enc_dec/bart/convert.py -i tmp/hf_models/${MODEL_NAME} \
    -o tmp/trt_models/${MODEL_NAME} --weight_data_type float32 \
    --inference_tensor_para_size 1 --nougat

**Comment by sjtu-cz** [comment]
python3 ../enc_dec/build.py \
    --model_type bart \
    --weight_dir tmp/trt_models/${MODEL_NAME}/tp1 \
    -o trt_engines/${MODEL_NAME}/1-gpu \
    --engine_name $MODEL_NAME \
    --remove_input_padding \
    --use_bert_attention_plugin \
    --use_gpt_attention_plugin \
    --use_gemm_plugin \
    --dtype float16 \
    --max_beam_width 1 \
    --max_batch_size 1 \
    --nougat \
    --max_encoder_input_len 1200 \
    --max_output_len 768 \
    --max_prompt_embedding_table_size 1200

**Comment by sjtu-cz** [comment]
I need some help, thanks a lot! @symphonylyh

**Comment by sjtu-cz** [comment]
I found the output of encoder is wrong, after I replaced the output of the encoder with the output of hf-model, the result was correct.  there is something wrong in the TensorRT-LLM/examples/multimodal/build_visual_engine.py

**Comment by sjtu-cz** [comment]
solved!
