### ISSUE TITLE
RuntimeError: Tensor names (host_max_kv_cache_length) in engine are not the same as expected on main branch

### ISSUE THREAD

**Issue by learninmou** [NVIDIA/TensorRT-LLM#369]
Hi,
Today I pulled the latest main branch and found the runtime error below while running examples/llama, with pipeline_parallel_size=4. (tensor_parallel_size=4, pipeline_parallel_size=1 is OK).

![image](https://github.com/NVIDIA/TensorRT-LLM/assets/142368437/7c0a0b07-c5af-4b6d-a014-4504dcc79de9)

also the build and run command:
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/142368437/b166a915-5d92-4b0f-bd63-2c105b5cd7e3)

![image](https://github.com/NVIDIA/TensorRT-LLM/assets/142368437/33c9cd3c-f87a-4da2-8757-b84ca051f2c6)

**Comment by PerkzZheng** [comment]
thanks. we will fix that. currently, you can just comment out the checks in `generation.py`.
