### ISSUE TITLE
groupwise_qweight_safetensors in load_from_gptq_llama for pt weights

### ISSUE THREAD

**Issue by foocker** [NVIDIA/TensorRT-LLM#371]
exmaples/llama/weight.py
only support gptq-int4 for .safetensors,  not .pt ?
because groupwise_qweight_safetensors must exist.

**Comment by byshiue** [comment]
Do you encounter real error on `.pt` file? In document, we use `.pt` file to demonstrate https://github.com/NVIDIA/TensorRT-LLM/tree/release/0.5.0/examples/llama#groupwise-quantization-awqgptq.

**Comment by foocker** [comment]
> Do you encounter real error on `.pt` file? In document, we use `.pt` file to demonstrate https://github.com/NVIDIA/TensorRT-LLM/tree/release/0.5.0/examples/llama#groupwise-quantization-awqgptq. 

see the code, the bug is obviously.  if u must need the error, as follows:
```
Traceback (most recent call last):
  File "/code/tensorrt_llm/examples/llama/build.py", line 735, in <module>
    build(0, args)
  File "/code/tensorrt_llm/examples/llama/build.py", line 706, in build
    engine = build_rank_engine(builder, builder_config, engine_name,
  File "/code/tensorrt_llm/examples/llama/build.py", line 544, in build_rank_engine
    load_func(tensorrt_llm_llama=tensorrt_llm_llama,
  File "/code/tensorrt_llm/examples/llama/weight.py", line 903, in load_from_gptq_llama
    extract_layer_idx(key) for key in groupwise_qweight_safetensors.keys()
UnboundLocalError: local variable 'groupwise_qweight_safetensors' referenced before assignment
```

**Comment by byshiue** [comment]
Can you try the latest main branch?

**Comment by foocker** [comment]
> Can you try the latest main branch?

maybe later, i will try.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Please reopen it if needed.
