### ISSUE TITLE
Can I directly build an HF format model such as CodeLlama-13B-AWQ that has been quantified using AWQ as tensorrt's engine?

### ISSUE THREAD

**Issue by shatealaboxiaowang** [NVIDIA/TensorRT-LLM#377]
Thank you very much for your reply!

**Comment by byshiue** [comment]
No. It is not supported now.

**Comment by byshiue** [comment]
Close this bug because the issue is resolved. Feel free to ask here if you still have question/issue, we will reopen the issue.
