### ISSUE TITLE
Build Engine failed when built engine for Chatglm3-6b.

### ISSUE THREAD

**Issue by hellopahe** [NVIDIA/TensorRT-LLM#381]
Great work ! but got some issues when run code from main branch, example/chatglm/build.py
~~~
python3 build.py -m 3 --model_dir /<model_dir> --output_dir /<output_dir> --dtype float16 --use_gpt_attention_plugin float16  --use_gemm_plugin float16
~~~
The process hang on start, and didnt show any output. When I press ctrl+c, it still hang on there. I have to `kill pid` to terminate the `build.py` process.

My nvidia env (There is no process running when I ran build.py):
~~~
Tue Nov 14 18:11:18 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100S-PCI...  On   | 00000000:00:0C.0 Off |                  Off |
| N/A   32C    P0    36W / 250W |  12664MiB / 32768MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
~~~

The `build.py` code is from https://github.com/NVIDIA/TensorRT-LLM/blob/ab7b4614b8499e6ef4f0087ad47a70a851f1c6b3/examples/chatglm/build.py

The package tensorrt_llm is from https://github.com/NVIDIA/TensorRT-LLM/tree/ab7b4614b8499e6ef4f0087ad47a70a851f1c6b3/tensorrt_llm

And version of tensorrt is :
~~~
tensorrt                 9.1.0.post11.dev4
tensorrt-bindings        9.1.0.post11.dev4
tensorrt-libs            9.1.0.post11.dev4
~~~

Thanks a lot.

**Comment by byshiue** [comment]
Can you try adding `TLLM_LOG_LEVEL=DEBUG` and `--log_level verbose` for your building scripts? For example, 
```
TLLM_LOG_LEVEL=DEBUG python3 build.py -m 3 --model_dir /<model_dir> --output_dir /<output_dir> --dtype float16 --use_gpt_attention_plugin float16  --use_gemm_plugin float16 --log_level verbose
```

**Comment by hellopahe** [comment]
I tried add `TLLM_LOG_LEVEL=DEBUG` and `--log_level verbose`, but still stuck in the same situation, with nothing printed in terminal. 
I also tried import the module from main branch directly by `import tensorrt_llm` in python console, and the progress dead as expected...
I doubt if it's a proper way to import directly from TensorRT-LLM/tensorrt_llm/, or I have to use `tensorrt_llm` package in docker fashion?

Thx

**Comment by byshiue** [comment]
Do you mean you encounter error when you only run `import tensorrt_llm`? It might mean you don't install tensorrt_llm successfully.

**Comment by hellopahe** [comment]
Thank you for your patience!
Problem solved by following docker building instructions. 
:)
