### ISSUE TITLE
ValueError: cannot reshape array of size 83886080 into shape (8192,3,3413)

### ISSUE THREAD

**Issue by tohaowu** [NVIDIA/TensorRT-LLM#383]
Int8 weight
https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/examples/llama/README.md#int8-weight-only--int8-kv-cache
`python3 examples/llama/hf_llama_convert.py -i /scratch/llama2-70b-hf -o /scratch/llama2_70b_int8_kv_cache/ --calibrate-kv-cache -t fp16 --tensor-parallelism 4 --processes 8` reports ValueError: cannot reshape array of size 83886080 into shape (8192,3,3413)

**Comment by Tracin** [comment]
https://github.com/NVIDIA/TensorRT-LLM/issues/358

**Comment by tohaowu** [comment]
Thanks
