### ISSUE TITLE
transformers version

### ISSUE THREAD

**Issue by sihanwang41** [NVIDIA/TensorRT-LLM#385]
I see the requirements pin to `transformers==4.33.1`, is there any plans for using latest version? Or is there any limitations that we have to pin specific version in TensorRT-LLM?

Thank you

**Comment by byshiue** [comment]
We pin the version of most packages to prevent the unkown issues when version is updated. We will update the version periodically.  You can als try the latest transformers by yourself.

**Comment by byshiue** [comment]
Close this bug because the issue is resolved. Feel free to ask here if you still have question/issue, we will reopen the issue.
