### ISSUE TITLE
When is libtensorrt_llm.so loaded?

### ISSUE THREAD

**Issue by wangkuiyi** [NVIDIA/TensorRT-LLM#388]
After building TensorRT-LLM inside an Nvidia Docker container, I obtained `libtensorrt_llm.so` and `libtensorrt_llm.a` files. When importing `tensorrt_llm` in Python, I expected the interpreter to load `libtensorrt_llm.so`. Surprisingly, this shared library wasn't loaded according to my observations. Instead, I noticed the loading of `libnvinfer_plugin_tensorrt_llm.so`.

```shell
root@2ff5b13e2c00:/code/tensorrt_llm# LD_DEBUG=libs python3 -c 'import tensorrt_llm; tensorrt_llm.mpi_rank()' 2>&1 | grep tensorrt_llm
       448:	calling init: /code/tensorrt_llm/tensorrt_llm/libs/libnvinfer_plugin_tensorrt_llm.so
       448:	calling init: /code/tensorrt_llm/tensorrt_llm/libs/libth_common.so
       448:	calling fini: /code/tensorrt_llm/tensorrt_llm/libs/libnvinfer_plugin_tensorrt_llm.so [0]
       448:	calling fini: /code/tensorrt_llm/tensorrt_llm/libs/libth_common.so [0]
```

I'm curious about the mechanism and timing of the `libtensorrt_llm.so` library loading.

**Comment by Shixiaowei02** [comment]
Hi @wangkuiyi , `libtensorrt_llm` is currently a required dependency of [nvidia-triton-backend](https://github.com/triton-inference-server/tensorrtllm_backend/blob/release/0.5.0/inflight_batcher_llm/CMakeLists.txt#L248-L252).

**Comment by wangkuiyi** [comment]
Thanks @Shixiaowei02 !

I see. [`libtensorrt_llm.so`](https://github.com/NVIDIA/TensorRT-LLM/blob/6837c8141acd036b8884330f4eadb50e097163f7/cpp/tensorrt_llm/CMakeLists.txt#L101-L113) is what the runtime, say, Triton backend, needs to run the TensorRT-LLM engine built from its Python source code. So, it is not a dependency of the Python package `tensorrt_llm`.

On the contrary, [`libnvinfer_plugin_tensorrt_llm.so`](https://github.com/NVIDIA/TensorRT-LLM/blob/6837c8141acd036b8884330f4eadb50e097163f7/cpp/tensorrt_llm/CMakeLists.txt#L153) defines the plugins, which will be used by the Python package `tensorrt_llm` to define models.
