### ISSUE TITLE
using trt-llm run bloom, tensor parallelism (built with --world_size =8 ) slower seriously than  single gpu  (GPU is 8X V100)

### ISSUE THREAD

**Issue by yank666** [NVIDIA/TensorRT-LLM#389]
single gpu total latency: 9.276402950286865 sec, world_size =8 tensor parallelism  total latency: 115sec,  it shouldn't be faster?

**Comment by wm2012011492** [comment]
Agreed with @0xymoro . It's recommended to use nsight system to analyze the timeline (maybe the communication overhead becomes too large). Besides, could you try  `--use_parallel_embedding` for engine building?

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Please reopen it if needed.
