### ISSUE TITLE
ensorRT acceleration is now available for Stable Diffusion in the popular Web UI by Automatic1111 distribution

### ISSUE THREAD

**Issue by henbucuoshanghai** [NVIDIA/TensorRT-LLM#397]
where is the code?tks

**Comment by byshiue** [comment]
Sorry, I don't get your point.

**Comment by foocker** [comment]
> where is the code?tks
here 
[Stable-Diffusion-WebUI-TensorRT](https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT)

**Comment by henbucuoshanghai** [comment]
sdxl  is coming soon?
