### ISSUE TITLE
Multistage Dockerfile question

### ISSUE THREAD

**Issue by mtaron** [NVIDIA/TensorRT-LLM#399]
Hello,

I notice that the final stage derives from `devel` and not `base`.

https://github.com/NVIDIA/TensorRT-LLM/blob/ab7b4614b8499e6ef4f0087ad47a70a851f1c6b3/docker/Dockerfile.multi#L51

Is that intentional? This means that the final release image contains all the build-time dependencies.

**Comment by Shixiaowei02** [comment]
Yes, this eliminates the need to keep temporary files during the build stage.
