### ISSUE TITLE
Is cuda graph enabled for inflight batching?

### ISSUE THREAD

**Issue by iycheng** [NVIDIA/TensorRT-LLM#402]
I'm evaluating the TRT-LLM. In the GptSessionBenchmark, there is a flag to enable the cuda graph so I know this is enabled.
While with the batch manager, there is no such flag. I notice the latacy for 8GPU A100 Llama 2 70b is really high for 1QPS testing. (7-8s). This seems much higher than my expectation.
Since this part is closed source, it's hard to check. Any one know whether the cuda graph is enabled with the batched manager?

**Comment by nv-samcheng** [comment]
Hi @iycheng ,
We don't support CUDA graph with in-flight batching.

**Comment by fishbone** [comment]
@nv-samcheng  thank you for the replying!

Since this part is closed sourced and I can't check the implementation, may I ask why it's not supported with IFB? Do we have future plan to enable it?

**Comment by ghsshou** [comment]
I set the flag but no corresponding information outputs.
Here is how I to build the engine:
```
python build.py --model_dir /home/models/13b/ \
                --dtype float16 \
                --remove_input_padding \
                --use_gpt_attention_plugin float16 \
                --use_gemm_plugin float16 \
                --output_dir /home/workspace/trtModel/llama13b-tp4-bs100-inflight/ \
                --max_input_len 10 \
                --max_output_len 1024 \
                --max_batch_size 100 \
                --world_size 4 \
                --tp_size 4 \
                --use_inflight_batching \
                --parallel_build
```
and here is how I run the inference engine:
```
nsys profile -o /home/workspace/reports/result3 --export json mpirun -n 4 --allow-run-as-root ./gptManagerBenchmark \
    --model llama_13b \
    --engine_dir /home/workspace/trtModel/llama13b-tp4-bs100-inflight/ \
    --type IFB \
    --dataset /home/workspace/dataset/preprocessed_dataset-sample100.json \
    --log_level info
```
Are there any other settings I should modify?
Moreover, in the nsight system, I didn't catch anything related to paged kv cache or paged attention or inflight attention.

**Comment by jdemouth-nvidia** [comment]
@iycheng our goal is to maximise the performance of TensorRT-LLM. We try to work on the features that have the biggest impact on performance. For now, our focus is not on CUDA graph (because we are working on features that will help performance more) but we'll definitely work on CUDA graph at one point.

**Comment by jdemouth-nvidia** [comment]
> I set the flag but no corresponding information outputs. Here is how I to build the engine:
> 
> ```
> python build.py --model_dir /home/models/13b/ \
>                 --dtype float16 \
>                 --remove_input_padding \
>                 --use_gpt_attention_plugin float16 \
>                 --use_gemm_plugin float16 \
>                 --output_dir /home/workspace/trtModel/llama13b-tp4-bs100-inflight/ \
>                 --max_input_len 10 \
>                 --max_output_len 1024 \
>                 --max_batch_size 100 \
>                 --world_size 4 \
>                 --tp_size 4 \
>                 --use_inflight_batching \
>                 --parallel_build
> ```
> 
> and here is how I run the inference engine:
> 
> ```
> nsys profile -o /home/workspace/reports/result3 --export json mpirun -n 4 --allow-run-as-root ./gptManagerBenchmark \
>     --model llama_13b \
>     --engine_dir /home/workspace/trtModel/llama13b-tp4-bs100-inflight/ \
>     --type IFB \
>     --dataset /home/workspace/dataset/preprocessed_dataset-sample100.json \
>     --log_level info
> ```
> 
> Are there any other settings I should modify? Moreover, in the nsight system, I didn't catch anything related to paged kv cache or paged attention or inflight attention.

I'm not sure your question is related to that issue. Can you create a separate issue if you are not asking about CUDA graphs, please? Or, can you explain what the issue is, please?
