### ISSUE TITLE
Any best practice to get 1st token latency?

### ISSUE THREAD

**Issue by yangulei** [NVIDIA/TensorRT-LLM#406]
As title, thanks!

**Comment by Tracin** [comment]
Try using smoothquant

**Comment by wm2012011492** [comment]
@yangulei do you mean how to get the latency of context phase which generates the first token?

**Comment by yangulei** [comment]
I want to get the 1st token latency for my own model as the perf data shown in https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/docs/source/performance.md#low-latency . I didn't notice 1st token latency in the benchmark results from https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/benchmarks/python/benchmark.py.

**Comment by wm2012011492** [comment]
@yangulei Please refer to https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/performance.md#first-token-latency-benchmark which describes how to reproduce the first token latency in detail

**Comment by uppalutkarsh** [comment]
Hi @yangulei,

Basically you need to set the output_len as 1 in `input_output_len`

Let us know if you are able to compute it.

Thanks,
Utkarsh

**Comment by yangulei** [comment]
Thank you @wm2012011492 @uppalutkarsh !
Close as solved.
