### ISSUE TITLE
[CUDA kernel performance about MQA & GQA]

### ISSUE THREAD

**Issue by beginlner** [NVIDIA/TensorRT-LLM#407]
It seems that the custom attention kernel will load kv-cache `num_heads / num_heads_kv` times from the global memory, is this the optimal solution or is there a plan to optimize it?

**Comment by byshiue** [comment]
We are still investigating further optimization opportunity.

**Comment by jdemouth-nvidia** [comment]
It’s not necessarily clear what the best approach is. Even if the code gives the impression that the data is loaded from Global Memory, it may actually come from the L2 cache. We are actively working on this kernel and we might change that in the future if we find that doing things differently helps. For now, I’m closing that issue but feel free to reopen it if needed.
