### ISSUE TITLE
[TensorRT-LLM][ERROR] Failed, NCCL error when I python run.py to test

### ISSUE THREAD

**Issue by cheney369** [NVIDIA/TensorRT-LLM#408]
I create the container by using:
`docker run -it --ipc=host --shm-size=1g --ulimit memlock=-1  ulimit stack 67108864 \
--gpus=all \
-v /data/crc/data:/data \
-n trtllm_dev \
-h trtllm_dev \
tensorrt_llm/devel:latest  /bin/bash`

And  I run the build.py file to change model is OK.

After that, T run the run.py by:
`python run.py --max_output_len=256 \
 --tokenizer_dir ../../zoellm-7b \
 --engine_dir=./trtModel/zoellm-7b-weight_only-bs8/`

I got the error: 
`root@trtllm_dev:/data/llama/TensorRT-LLM/examples/llama# ./run.sh 
[TensorRT-LLM][ERROR] Failed, NCCL error /src/tensorrt_llm/cpp/tensorrt_llm/runtime/ncclCommunicator.cpp:122 'internal error - please report this issue to the NCCL developers'
`

GPU--two T4 with 16G.

**Comment by byshiue** [comment]
Can you try setting larger `--shm-size` and run nccl test first?

**Comment by cheney369** [comment]
@byshiue I recreate the container with --shm-size=8g and  run iccl test. I got the same error.

` root@trtllm_dev:/data/llama/nccl-tests# ./build/all_reduce_perf -b 8 -e 128M -f 2 -g 2
nThread 1 nGpus 2 minBytes 8 maxBytes 134217728 step: 2(factor) warmup iters: 5 iters: 20 agg iters: 1 validation: 1 graph: 0
Using devices
Rank  0 Group  0 Pid    358 on trtllm_dev device  0 [0x00] Tesla T4
Rank  1 Group  0 Pid    358 on trtllm_dev device  1 [0x00] Tesla T4
                                                             out-of-place                       in-place          
      size         count      type   redop    root     time   algbw   busbw #wrong     time   algbw   busbw #53 
        (B)    (elements)                               (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)       
           8             2     float     sum      -1    16.41    0.00    0.00      0    16.50    0.00    0.00      0
          16             4     float     sum      -1    16.17    0.00    0.00      0    16.63    0.00    0.00      0
          32             8     float     sum      -1    16.43    0.00    0.00      0    16.83    0.00    0.00      0
          64            16     float     sum      -1    16.46    0.00    0.00      0    15.82    0.00    0.00      0
         128            32     float     sum      -1    16.14    0.01    0.01      0    16.36    0.01    0.01      0
         256            64     float     sum      -1    16.60    0.02    0.02      0    16.34    0.02    0.02      0
         512           128     float     sum      -1    16.65    0.03    0.03      0    16.47    0.03    0.03      0
        1024           256     float     sum      -1    17.43    0.06    0.06      0    17.07    0.06    0.06      0
        2048           512     float     sum      -1    17.86    0.11    0.11      0    17.57    0.12    0.12      0
        4096          1024     float     sum      -1    19.01    0.22    0.22      0    18.74    0.22    0.22      0
        8192          2048     float     sum      -1    22.73    0.36    0.36      0    22.38    0.37    0.37      0
       16384          4096     float     sum      -1    25.68    0.64    0.64      0    25.53    0.64    0.64      0
       32768          8192     float     sum      -1    32.41    1.01    1.01      0    32.36    1.01    1.01      0
       65536         16384     float     sum      -1    60.44    1.08    1.08      0    51.27    1.28    1.28      0
      131072         32768     float     sum      -1    64.81    2.02    2.02      0    63.90    2.05    2.05      0
      262144         65536     float     sum      -1    94.96    2.76    2.76      0    93.16    2.81    2.81      0
      524288        131072     float     sum      -1    155.2    3.38    3.38      0    155.0    3.38    3.38      0
     1048576        262144     float     sum      -1    284.7    3.68    3.68      0    281.5    3.73    3.73      0
     2097152        524288     float     sum      -1    543.9    3.86    3.86      0    536.2    3.91    3.91      0
     4194304       1048576     float     sum      -1   1063.3    3.94    3.94      0   1059.7    3.96    3.96      0
     8388608       2097152     float     sum      -1   2098.7    4.00    4.00      0   2099.0    4.00    4.00      0
    16777216       4194304     float     sum      -1   4194.5    4.00    4.00      0   4175.2    4.02    4.02      0
    33554432       8388608     float     sum      -1   8331.8    4.03    4.03      0   8332.5    4.03    4.03      0
    67108864      16777216     float     sum      -1    16646    4.03    4.03      0    16639    4.03    4.03      0
   134217728      33554432     float     sum      -1    33268    4.03    4.03      0    33256    4.04    4.04      0
 Out of bounds values : 0 OK
 Avg bus bandwidth    : 1.73972 
`

`root@trtllm_dev:/data/llama/TensorRT-LLM/examples/llama# ./run.sh 
[TensorRT-LLM][ERROR] Failed, NCCL error /src/tensorrt_llm/cpp/tensorrt_llm/runtime/ncclCommunicator.cpp:122 'internal error - please report this issue to the NCCL developers'
`

**Comment by PerkzZheng** [comment]
@cheney369 Can you run with NCCL_DEBUG=INFO ? let us see if we get more useful information. BTW, can you try removing `--net host` when launching containers and see if there is anything different ?

**Comment by cheney369** [comment]
@PerkzZheng  I add the NCCL_DEBUG=INFO and get the result. And removing --net host I got same error.

root@trtllm_dev:/data/llama/nccl-tests# ./build/all_reduce_perf -b 8 -e 128M -f 2 -g 2
 nThread 1 nGpus 2 minBytes 8 maxBytes 134217728 step: 2(factor) warmup iters: 5 iters: 20 agg iters: 1 validation: 1 graph: 0

 Using devices
  Rank  0 Group  0 Pid    398 on trtllm_dev device  0 [0x00] Tesla T4
  Rank  1 Group  0 Pid    398 on trtllm_dev device  1 [0x00] Tesla T4
trtllm_dev:398:398 [0] NCCL INFO Bootstrap : Using eth0:172.17.0.2<0>
trtllm_dev:398:398 [1] NCCL INFO cudaDriverVersion 12020
NCCL version 2.18.3+cuda12.2
trtllm_dev:398:412 [0] NCCL INFO Plugin Path : /opt/hpcx/nccl_rdma_sharp_plugin/lib/libnccl-net.so
trtllm_dev:398:412 [0] NCCL INFO P2P plugin IBext
trtllm_dev:398:412 [0] NCCL INFO NET/IB : No device found.
trtllm_dev:398:412 [0] NCCL INFO NET/IB : No device found.
trtllm_dev:398:412 [0] NCCL INFO NET/Socket : Using [0]eth0:172.17.0.2<0>
trtllm_dev:398:412 [0] NCCL INFO Using network Socket
trtllm_dev:398:413 [1] NCCL INFO Using network Socket
trtllm_dev:398:413 [1] NCCL INFO comm 0x5624253c6cb0 rank 1 nranks 2 cudaDev 1 nvmlDev 1 busId e0 commId 0xb76f387dbd6e648e - Init START
trtllm_dev:398:412 [0] NCCL INFO comm 0x5624253c2320 rank 0 nranks 2 cudaDev 0 nvmlDev 0 busId d0 commId 0xb76f387dbd6e648e - Init START
trtllm_dev:398:412 [0] NCCL INFO Channel 00/02 :    0   1
trtllm_dev:398:412 [0] NCCL INFO Channel 01/02 :    0   1
trtllm_dev:398:412 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] 1/-1/-1->0->-1
trtllm_dev:398:412 [0] NCCL INFO P2P Chunksize set to 131072
trtllm_dev:398:413 [1] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] -1/-1/-1->1->0
trtllm_dev:398:413 [1] NCCL INFO P2P Chunksize set to 131072
trtllm_dev:398:412 [0] NCCL INFO Channel 00 : 0[0] -> 1[1] via SHM/direct/direct
trtllm_dev:398:413 [1] NCCL INFO Channel 00 : 1[1] -> 0[0] via SHM/direct/direct
trtllm_dev:398:412 [0] NCCL INFO Channel 01 : 0[0] -> 1[1] via SHM/direct/direct
trtllm_dev:398:413 [1] NCCL INFO Channel 01 : 1[1] -> 0[0] via SHM/direct/direct
trtllm_dev:398:413 [1] NCCL INFO Connected all rings
trtllm_dev:398:413 [1] NCCL INFO Connected all trees
trtllm_dev:398:412 [0] NCCL INFO Connected all rings
trtllm_dev:398:413 [1] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 512 | 512
trtllm_dev:398:413 [1] NCCL INFO 2 coll channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer
trtllm_dev:398:412 [0] NCCL INFO Connected all trees
trtllm_dev:398:412 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 512 | 512
trtllm_dev:398:412 [0] NCCL INFO 2 coll channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer
trtllm_dev:398:413 [1] NCCL INFO comm 0x5624253c6cb0 rank 1 nranks 2 cudaDev 1 nvmlDev 1 busId e0 commId 0xb76f387dbd6e648e - Init COMPLETE
trtllm_dev:398:412 [0] NCCL INFO comm 0x5624253c2320 rank 0 nranks 2 cudaDev 0 nvmlDev 0 busId d0 commId 0xb76f387dbd6e648e - Init COMPLETE

                                                              out-of-place                       in-place          
         size         count      type   redop    root     time   algbw   busbw #wrong     time   algbw   busbw #wrong
         (B)    (elements)                               (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)       
           8             2     float     sum      -1    16.13    0.00    0.00      0    16.37    0.00    0.00      0
          16             4     float     sum      -1    16.56    0.00    0.00      0    16.09    0.00    0.00      0
          32             8     float     sum      -1    16.07    0.00    0.00      0    16.21    0.00    0.00      0
          64            16     float     sum      -1    16.29    0.00    0.00      0    16.15    0.00    0.00      0
         128            32     float     sum      -1    16.79    0.01    0.01      0    16.56    0.01    0.01      0
         256            64     float     sum      -1    16.76    0.02    0.02      0    16.53    0.02    0.02      0
         512           128     float     sum      -1    16.87    0.03    0.03      0    16.93    0.03    0.03      0
        1024           256     float     sum      -1    17.23    0.06    0.06      0    16.64    0.06    0.06      0
        2048           512     float     sum      -1    17.60    0.12    0.12      0    17.11    0.12    0.12      0
        4096          1024     float     sum      -1    19.33    0.21    0.21      0    18.90    0.22    0.22      0
        8192          2048     float     sum      -1    22.16    0.37    0.37      0    22.10    0.37    0.37      0
       16384          4096     float     sum      -1    26.61    0.62    0.62      0    26.41    0.62    0.62      0
       32768          8192     float     sum      -1    33.75    0.97    0.97      0    33.64    0.97    0.97      0
       65536         16384     float     sum      -1    60.93    1.08    1.08      0    59.55    1.10    1.10      0
      131072         32768     float     sum      -1    73.80    1.78    1.78      0    74.69    1.75    1.75      0
      262144         65536     float     sum      -1    103.0    2.55    2.55      0    98.97    2.65    2.65      0
      524288        131072     float     sum      -1    163.1    3.21    3.21      0    167.1    3.14    3.14      0
     1048576        262144     float     sum      -1    290.6    3.61    3.61      0    291.7    3.59    3.59      0
     2097152        524288     float     sum      -1    544.6    3.85    3.85      0    545.9    3.84    3.84      0
     4194304       1048576     float     sum      -1   1069.2    3.92    3.92      0   1068.7    3.92    3.92      0
     8388608       2097152     float     sum      -1   2107.7    3.98    3.98      0   2129.9    3.94    3.94      0
    16777216       4194304     float     sum      -1   4199.1    4.00    4.00      0   4200.3    3.99    3.99      0
    33554432       8388608     float     sum      -1   8381.6    4.00    4.00      0   8383.1    4.00    4.00      0
    67108864      16777216     float     sum      -1    16744    4.01    4.01      0    16739    4.01    4.01      0
   134217728      33554432     float     sum      -1    33476    4.01    4.01      0    33455    4.01    4.01      0
trtllm_dev:398:398 [1] NCCL INFO comm 0x5624253c2320 rank 0 nranks 2 cudaDev 0 busId d0 - Destroy COMPLETE
trtllm_dev:398:398 [1] NCCL INFO comm 0x5624253c6cb0 rank 1 nranks 2 cudaDev 1 busId e0 - Destroy COMPLETE
 Out of bounds values : 0 OK
 Avg bus bandwidth    : 1.69556

**Comment by PerkzZheng** [comment]
> @PerkzZheng I add the NCCL_DEBUG=INFO and get the result. And removing --net host I got same error.
> 
> root@trtllm_dev:/data/llama/nccl-tests# ./build/all_reduce_perf -b 8 -e 128M -f 2 -g 2 nThread 1 nGpus 2 minBytes 8 maxBytes 134217728 step: 2(factor) warmup iters: 5 iters: 20 agg iters: 1 validation: 1 graph: 0
> 
> Using devices Rank 0 Group 0 Pid 398 on trtllm_dev device 0 [0x00] Tesla T4 Rank 1 Group 0 Pid 398 on trtllm_dev device 1 [0x00] Tesla T4 trtllm_dev:398:398 [0] NCCL INFO Bootstrap : Using eth0:172.17.0.2<0> trtllm_dev:398:398 [1] NCCL INFO cudaDriverVersion 12020 NCCL version 2.18.3+cuda12.2 trtllm_dev:398:412 [0] NCCL INFO Plugin Path : /opt/hpcx/nccl_rdma_sharp_plugin/lib/libnccl-net.so trtllm_dev:398:412 [0] NCCL INFO P2P plugin IBext trtllm_dev:398:412 [0] NCCL INFO NET/IB : No device found. trtllm_dev:398:412 [0] NCCL INFO NET/IB : No device found. trtllm_dev:398:412 [0] NCCL INFO NET/Socket : Using [0]eth0:172.17.0.2<0> trtllm_dev:398:412 [0] NCCL INFO Using network Socket trtllm_dev:398:413 [1] NCCL INFO Using network Socket trtllm_dev:398:413 [1] NCCL INFO comm 0x5624253c6cb0 rank 1 nranks 2 cudaDev 1 nvmlDev 1 busId e0 commId 0xb76f387dbd6e648e - Init START trtllm_dev:398:412 [0] NCCL INFO comm 0x5624253c2320 rank 0 nranks 2 cudaDev 0 nvmlDev 0 busId d0 commId 0xb76f387dbd6e648e - Init START trtllm_dev:398:412 [0] NCCL INFO Channel 00/02 : 0 1 trtllm_dev:398:412 [0] NCCL INFO Channel 01/02 : 0 1 trtllm_dev:398:412 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] 1/-1/-1->0->-1 trtllm_dev:398:412 [0] NCCL INFO P2P Chunksize set to 131072 trtllm_dev:398:413 [1] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] -1/-1/-1->1->0 trtllm_dev:398:413 [1] NCCL INFO P2P Chunksize set to 131072 trtllm_dev:398:412 [0] NCCL INFO Channel 00 : 0[0] -> 1[1] via SHM/direct/direct trtllm_dev:398:413 [1] NCCL INFO Channel 00 : 1[1] -> 0[0] via SHM/direct/direct trtllm_dev:398:412 [0] NCCL INFO Channel 01 : 0[0] -> 1[1] via SHM/direct/direct trtllm_dev:398:413 [1] NCCL INFO Channel 01 : 1[1] -> 0[0] via SHM/direct/direct trtllm_dev:398:413 [1] NCCL INFO Connected all rings trtllm_dev:398:413 [1] NCCL INFO Connected all trees trtllm_dev:398:412 [0] NCCL INFO Connected all rings trtllm_dev:398:413 [1] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 512 | 512 trtllm_dev:398:413 [1] NCCL INFO 2 coll channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer trtllm_dev:398:412 [0] NCCL INFO Connected all trees trtllm_dev:398:412 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 512 | 512 trtllm_dev:398:412 [0] NCCL INFO 2 coll channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer trtllm_dev:398:413 [1] NCCL INFO comm 0x5624253c6cb0 rank 1 nranks 2 cudaDev 1 nvmlDev 1 busId e0 commId 0xb76f387dbd6e648e - Init COMPLETE trtllm_dev:398:412 [0] NCCL INFO comm 0x5624253c2320 rank 0 nranks 2 cudaDev 0 nvmlDev 0 busId d0 commId 0xb76f387dbd6e648e - Init COMPLETE
> 
> ```
>                                                           out-of-place                       in-place          
>      size         count      type   redop    root     time   algbw   busbw #wrong     time   algbw   busbw #wrong
>      (B)    (elements)                               (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)       
>        8             2     float     sum      -1    16.13    0.00    0.00      0    16.37    0.00    0.00      0
>       16             4     float     sum      -1    16.56    0.00    0.00      0    16.09    0.00    0.00      0
>       32             8     float     sum      -1    16.07    0.00    0.00      0    16.21    0.00    0.00      0
>       64            16     float     sum      -1    16.29    0.00    0.00      0    16.15    0.00    0.00      0
>      128            32     float     sum      -1    16.79    0.01    0.01      0    16.56    0.01    0.01      0
>      256            64     float     sum      -1    16.76    0.02    0.02      0    16.53    0.02    0.02      0
>      512           128     float     sum      -1    16.87    0.03    0.03      0    16.93    0.03    0.03      0
>     1024           256     float     sum      -1    17.23    0.06    0.06      0    16.64    0.06    0.06      0
>     2048           512     float     sum      -1    17.60    0.12    0.12      0    17.11    0.12    0.12      0
>     4096          1024     float     sum      -1    19.33    0.21    0.21      0    18.90    0.22    0.22      0
>     8192          2048     float     sum      -1    22.16    0.37    0.37      0    22.10    0.37    0.37      0
>    16384          4096     float     sum      -1    26.61    0.62    0.62      0    26.41    0.62    0.62      0
>    32768          8192     float     sum      -1    33.75    0.97    0.97      0    33.64    0.97    0.97      0
>    65536         16384     float     sum      -1    60.93    1.08    1.08      0    59.55    1.10    1.10      0
>   131072         32768     float     sum      -1    73.80    1.78    1.78      0    74.69    1.75    1.75      0
>   262144         65536     float     sum      -1    103.0    2.55    2.55      0    98.97    2.65    2.65      0
>   524288        131072     float     sum      -1    163.1    3.21    3.21      0    167.1    3.14    3.14      0
>  1048576        262144     float     sum      -1    290.6    3.61    3.61      0    291.7    3.59    3.59      0
>  2097152        524288     float     sum      -1    544.6    3.85    3.85      0    545.9    3.84    3.84      0
>  4194304       1048576     float     sum      -1   1069.2    3.92    3.92      0   1068.7    3.92    3.92      0
>  8388608       2097152     float     sum      -1   2107.7    3.98    3.98      0   2129.9    3.94    3.94      0
> 16777216       4194304     float     sum      -1   4199.1    4.00    4.00      0   4200.3    3.99    3.99      0
> 33554432       8388608     float     sum      -1   8381.6    4.00    4.00      0   8383.1    4.00    4.00      0
> 67108864      16777216     float     sum      -1    16744    4.01    4.01      0    16739    4.01    4.01      0
> ```
> 
> 134217728 33554432 float sum -1 33476 4.01 4.01 0 33455 4.01 4.01 0 trtllm_dev:398:398 [1] NCCL INFO comm 0x5624253c2320 rank 0 nranks 2 cudaDev 0 busId d0 - Destroy COMPLETE trtllm_dev:398:398 [1] NCCL INFO comm 0x5624253c6cb0 rank 1 nranks 2 cudaDev 1 busId e0 - Destroy COMPLETE Out of bounds values : 0 OK Avg bus bandwidth : 1.69556

Thanks. Can you also collect the nccl logs with TRT-LLM ?

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Please reopen it if needed.
