### ISSUE TITLE
Data Parallel or Multiprocessing support 

### ISSUE THREAD

**Issue by JosephChenHub** [NVIDIA/TensorRT-LLM#420]
does tensorrt-llm support data parallel or multiprocessing inference? for example,  we have 4 A100 (80G) GPUs,  and each processing occupies one GPU and one tensorrt instance to do inference.  To covert the model as follows,
```
# Build the LLaMA 7B model using a single GPU and BF16.
python build.py --model_dir ./tmp/llama/7B/ \
                --dtype bfloat16 \
                --remove_input_padding \
                --use_gpt_attention_plugin bfloat16 \
                --enable_context_fmha \
                --use_gemm_plugin bfloat16 \
                --output_dir ./tmp/llama/7B/trt_engines/bf16/1-gpu/
```
the instance does work on one GPU (80G, memory enough), but  it cannot be applied in such command due to incorrect device mapping of tensorrt instances:  
```
# in run.py, we split ``data'' into multiple parts, each part will be handled  by a unique processing (one GPU) 
accelerate launch --num_processes=4  run.py --max_output_len=50 \
               --tokenizer_dir ./tmp/llama/7B/ \
               --engine_dir=./tmp/llama/7B/trt_engines/bf16/1-gpu/
```

how can we handle this ?

**Comment by JosephChenHub** [comment]
well, it seems work by these changes:
1. comment ``set_device'' at https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/tensorrt_llm/runtime/generation.py#L156
2. add a variable ``device''  to initialise  **GenerationSession**  https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/tensorrt_llm/runtime/generation.py#L299

then we can set **tensorrt_llm.runtime.GenerationSession** a specified device for each instance. But it is unknown whether there exist latent dangers for other settings.

**Comment by byshiue** [comment]
You can also use the environment variable `CUDA_VISIBLE_DEVICES` to assing the GPU you want to use when you launch the program.

**Comment by JosephChenHub** [comment]
> You can also use the environment variable `CUDA_VISIBLE_DEVICES` to assing the GPU you want to use when you launch the program.

No, it cannot .  original code will call ``set_device'' . if tp=1 and pp=1, the device will always be **cuda:0**

**Comment by byshiue** [comment]
Have you tried? When you setup the `CUDA_VISIBLE_DEVICES=1` to run the program, the `cuda:0` of this program is the second GPU instead of the first GPU because the program can only see the second GPU.

**Comment by jdemouth-nvidia** [comment]
> > You can also use the environment variable `CUDA_VISIBLE_DEVICES` to assing the GPU you want to use when you launch the program.
> 
> No, it cannot . original code will call ``set_device'' . if tp=1 and pp=1, the device will always be **cuda:0**

That should work even if the device is 0 in both cases.

**Comment by jdemouth-nvidia** [comment]
I’m closing that issue as the main question has been answered already. Note that we may be able to do something more efficient in the future but it has not been implemented yet. Thanks.
