### ISSUE TITLE
Clarification of H100 FP8 performance numbers

### ISSUE THREAD

**Issue by jfolz** [NVIDIA/TensorRT-LLM#421]
I'm currently testing Llama2 70B on DGX-A100 and DGX-H100. I'm running the gptManagerBenchmark as described [here](https://github.com/NVIDIA/TensorRT-LLM/tree/release/0.5.0/benchmarks/cpp) and comparing my numbers to those given on the [performance page](https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/docs/source/performance.md#h100-gpus-fp8) for TP4 and batch size 64.

To build fp8 engines for H100, I followed the [instructions](
https://github.com/NVIDIA/TensorRT-LLM/tree/release/0.5.0/examples/llama#fp8-post-training-quantization) from the llama example + fixes to `quantize.py` from #293.
```
python quantize.py --model_dir ./tmp/llama/70B \
                   --dtype float16 \
                   --qformat fp8 \
                   --export_path /tmp/70B-chat_quantized_fp8 \
                   --calib_size 512 \
python build.py --model_dir "/tmp/hf-70B-chat/" \
                --quantized_fp8_model_path "/tmp/70B-chat_quantized_fp8/llama_tp1_rank0.npz" \
                --output_dir "/tmp/tensorrt-70B-chat-H100-fp8-tp4-bs64/" \
                --remove_input_padding \
                --max_input_len 4096 \
                --max_output_len 4096 \
                --max_batch_size 64 \
                --dtype float16 \
                --enable_context_fmha \
                --enable_fp8 \
                --fp8_kv_cache \
                --use_gemm_plugin float16 \
                --use_gpt_attention_plugin float16 \
                --use_inflight_batching \
                --paged_kv_cache \
                --world_size 4 \
                --tp_size 4 \
                --pp_size 1 \
                --parallel_build
```
I used the same command for A100, minus the fp8 related options.

My custom subset of OpenOrca has various input and output lengths, so I elected to take the mean of the througputs given on the performance page.
For A100 fp16 this yields $(1,237 + 1,181 + 272 + 738) / 4 = 857$ tokens/s.
For H100 fp8 $(3,317 + 2,616 + 843 + 1,583) / 4 = 2089.75$ tokens/s.

My own benchmarks yield $854$ tokens/s for A100 fp16, which is spot on, but only $1734.09$ for H100 fp8. Retesting H100 with fp16 yields $1526.25$ tokens/s, so fp8 is hardly any faster here. This has me wondering if I'm doing something wrong, e.g. if there is a different fp8 mode that I should be using.

**Comment by Tracin** [comment]
@jfolz Hi, I think there are two parts when we talk about the throughput here. One is the model inference speed and the other is inflight batching serving strategy. I would suggest that firstly run cpp/build/benchmarks/ to verify the model inference improvements of FP8 vs FP16, it should be 40%~50% under this condition. If this is matched, then we will move on to the inflight batching parts.

**Comment by jfolz** [comment]
Thanks for getting back to me @Tracin.
Sorry if this wasn't clear, but I believe that's what I did. The performance page simply states:
> The different performance numbers below were collected using the methodology described in the benchmarks [folder](https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/benchmarks).

So I ran the gptManagerBenchmark like so:
```
mpirun --allow-run-as-root --oversubscribe -n 4 /app/cpp/build/benchmarks/gptManagerBenchmark \
     --model gpt \
     --engine_dir /tmp/tensorrt-70B-chat-H100-fp8-tp4-bs64/ \
     --type IFB \
     --dataset /netscratch/folz/openorca/sample10k_tensorrt.json
```

As I wrote before, this got me to exactly what I expected with my [OpenOrca subset](https://github.com/NVIDIA/TensorRT-LLM/files/13471376/sample10k_tensorrt.json.gz) running on A100 in fp16. For H100 going from fp16 to fp8 yields only a 13% increase in throughput ($1526.25 \rightarrow 1734.09$). An increase of 40% would bring this to over 2100, which is roughly where I expected it to be. Hence, why I'm asking whether I did something wrong to get worse numbers.

I forgot to mention this before, but I'm using a container built from 71a5b97.
Please let me know if you need any additional information.

**Comment by Tracin** [comment]
@jfolz Sorry, I mean you can run `gptSessionBenchmark` on FP8 and FP16 to get an result of raw model inference speed, then we can infer which part might be wrong. For example you can run bs=64 input-len=128 output-len=2048 to see if throughput is around 2616.

**Comment by jfolz** [comment]
OK, got it now :)

I built new engines without the `--use_inflight_batching` option, and max lengths 128/2048 and 4096/4096, then ran the gptSessionBenchmark with `--batch_size "64" --input_output_len "128,2048"`. Note that I also wanted to test engines without `--fp8_kv_cache` in case there are some extra conversions happening, but the build failed.

<details>
  <summary>traceback</summary>

  ```
  Traceback (most recent call last):
    File "/app/examples/llama/build.py", line 714, in <module>
      mp.spawn(build, nprocs=args.world_size, args=(args, ))
    File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 239, in spawn
      return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
    File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 197, in start_processes
      while not context.join():
    File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 160, in join
      raise ProcessRaisedException(msg, error_index, failed_process.pid)
  torch.multiprocessing.spawn.ProcessRaisedException:
  
  -- Process 1 terminated with the following error:
  Traceback (most recent call last):
    File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
      fn(i, *args)
    File "/app/examples/llama/build.py", line 689, in build
      engine = build_rank_engine(builder, builder_config, engine_name,
    File "/app/examples/llama/build.py", line 535, in build_rank_engine
      quant_scales = get_scaling_factors(args.quantized_fp8_model_path,
    File "/app/examples/llama/weight.py", line 115, in get_scaling_factors
      assert len(v) == num_layers, \
  AssertionError: Expect scaling factor qkv_output of length 80, got 0
  ```
</details>


Anyways, here are the benchmark results I got:

| GPU  | dtype | engine max lengths | benchmark lengths | latency (ms) |
|------|-------|---------------:|------------------:|-------------:|
| H100 | fp8   |       128/2048 |          128/2048 |     50580.01 |
| H100 | fp8   |      4096/4096 |          128/2048 |     50528.98 |
| H100 | fp16  |       128/2048 |          128/2048 |     64163.21 |
| H100 | fp16  |      4096/4096 |          128/2048 |     64292.82 |
| A100 | fp16  |      128/2048 |          128/2048 |     114020.42 |
| A100 | fp16  |      4096/4096 |          128/2048 |     113856.38 |

I'm not entirely sure how to interpret those numbers, but latency seems about 21% lower with fp8 compared to fp16.
On a positive note, there appears to be no appreciable difference with engines built to support longer input/output lengths.

I thought it might be interesting to look at power draw during these tests (it goes fp8, fp16, fp8, fp16):
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/3245870/e1e0adec-4bff-4221-b260-98c9978bd0e3)
It's a bit lower with fp8, about 475W per GPU on average. With fp16 it's 525W. ~I checked back what I got for my previous A100 tests, and they drew close to the power limit.~
Edit: It was about 310W for A100, so also quite a bit less than the power limit.

~I've also queued up fp16 tests for A100, but they're all busy right now.~
Edit: A100 benchmarks added.

**Comment by Tracin** [comment]
@jfolz Great job! You can multiply batch size and output length to get total token number generated. `64 * 2048`
Then divided by the total seconds used (50.580 for example of FP8) You will get (64 * 2048) / 50.580 = 2591 which is about 2616 so they are all matched! 
So the situation right now is inflight batching serving decrease the throughput, am I right?
BTW, Could you measure with 32-2048-128 setting so I can compared with my results please? I do have 40% increment with FP8.

**Comment by jfolz** [comment]
I see, that makes sense. So the raw performance of the built engines is fine, and my initial gptManagerBenchmark runs for A100 matching exactly was just pure coincidence, presumably because my dataset has slightly shorter sequences on average. That leaves IFB or the specific implementation of the gptManagerBenchmark.
For A100 we're looking at 857 / 1151.2 = 0.76, so about 24% loss.
For H100 it's 1734 / 2591.4 = 0.669 or 33% loss.
I'm curious if this is expected because it seems quite high.

I can try to get some more benchmarks in, though it might take some time. But what do you mean by "32-2048-128"?

**Comment by Tracin** [comment]
@jfolz Yes, I think you are right, I will check if this 24% and 33% degradation make sense, it is mostly influenced by input length and output length.
And 32-2048-128 means batch_size - input_length - output_length.

**Comment by jfolz** [comment]
I could not fit building new engines in this time, so I used ones configured with 64-4096-4096. Hope that's OK.

| GPU  | TP | dtype |   engine cfg | benchmark cfg | latency (ms) | output tokens/s |
|------|----|-------|-------------:|--------------:|-------------:|----------------:|
| H100 | 4  | fp8   | 64-4096/4096 |   32-2048-128 |      8122.35 |          504.29 |
| H100 | 4  | fp16  | 64-4096-4096 |   32-2048-128 |      8301.62 |          493.40 |
| A100 | 4  | fp16  | 64-4096-4096 |   32-2048-128 |     16347.88 |          250.55 |

**Comment by Tracin** [comment]
@jfolz Thanks a lot, the results shows nearly no improvement with FP8, that does not match my result, Mine is 774 tokens/s, 539 tokens/s and 246 tokens/s. The only difference between is `--paged_kv_cache`, I did not add it.
@kaiyux Could there be anything wrong to produce this results?

**Comment by jfpichlme** [comment]
Any updates on the previously discussed results, specifically concerning the lack of improvements between FP8 and FP16?

**Comment by avianion** [comment]
@jfolz can you redo this benchmark with batch size 1? thanks

**Comment by nv-guomingz** [comment]
Hi @jfolz  Could u please try the latest code base to see if the issue still exists?

And do u still have further issue or question now? If not, we'll close it soon.

**Comment by jfolz** [comment]
@nv-guomingz probably not, as we're now primarily using vLLM. I'll close.
