### ISSUE TITLE
Methods to evaluate Throughput (tokens/s)

### ISSUE THREAD

**Issue by tiandiao123** [NVIDIA/TensorRT-LLM#43]
Hello: 
   I am wondering how do you evaluate throughput (tokens/s). Like as for Throughput you calculated, did you only count token Throughput (or including the context process)? 
Thank you!

**Comment by jdemouth-nvidia** [comment]
I suppose you are asking about the throughputs reported on the [performance.md](https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/docs/source/performance.md) page?

The numbers on that page are obtained using the following formula: 

```
Throughput = Output Tokens x Batch Size / Total Runtime
```

So, for example, the 1st row of the H100 FP8 table shows a throughput of 10,907 for GPT-J, BS = 64 and 128 output tokens. It corresponds to 751ms of end-to-end latency to produce those 128 output tokens. 

I hope it answers your question. I'm closing that issue but feel free to re-open it if needed.
