### ISSUE TITLE
Support for distributed inference using multiple nodes?

### ISSUE THREAD

**Issue by sleepwalker2017** [NVIDIA/TensorRT-LLM#433]
Hi, is there any document for using trt-llm to run inference on multiple machines?

For example, we may use pipeline parallel within 2 machines and use tensor parallel within multiple gpus in one machine.

Is this supported by trt-llm or the triton backend? 

Thank you.

**Comment by byshiue** [comment]
We have not verified that. But you could take a try like because it should be similar to multi-GPU in single node under MPI.

**Comment by jdemouth-nvidia** [comment]
I’m closing that issue. Feel free to reopen it if you run into issues and we can help debug. Thanks
