### ISSUE TITLE
failing inference of llama-2 engine on V100 DGX

### ISSUE THREAD

**Issue by abhinav-vimal13** [NVIDIA/TensorRT-LLM#435]
I have created tensorrt engine of llama-2 using smooth quant way via below two comds

1. create smooth quant model
python3 hf_llama_convert.py -i /llama-models/llama-7b-hf -o /llama/smooth_llama_7B/sq0.8/ -sq 0.8 --tensor-parallelism 1 --storage-type fp16
2. building engine
python3 build.py --ft_model_dir=/llama/smooth_llama_7B/sq0.8/1-gpu/  --use_smooth_quant

but facing issue when running inference via python3 run.py --max_output_len=50 --tokenizer_dir ./tmp/llama/7B/ --engine_dir=./tmp/llama/7B/trt_engines/fp16/1-gpu/

(venv) root@e8c9d86cc3cb:/workspace/TensorRT-LLM/examples/llama# python3 run.py --max_output_len=50 --tokenizer_dir ./hf-llama-2-7b Running the float16 engine .../workspace/TensorRT-LLM/examples/llama/run.py:118: UserWarning: The PyTorch API of nested tensors is in prototype stage and will change in the near future. (Triggered internally at ../aten/src/ATen/NestedTensorImpl.cpp:178.)
torch.nested.nested_tensor(input_tokens, dtype=torch.int32),
terminate called after throwing an instance of 'tensorrt_llm::common::TllmException'
what(): [TensorRT-LLM][ERROR] Assertion failed: No valid SQ GEMM tactic (/workspace/TensorRT-LLM/cpp/tensorrt_llm/plugins/smoothQuantGemmPlugin/smoothQuantGemmPlugin.cpp:242)
1 0x7f5211200e0b /workspace/TensorRT-LLM/venv/lib/python3.10/site-packages/tensorrt_llm/libs/libnvinfer_plugin_tensorrt_llm.so(+0x34e0b) [0x7f5211200e0b]
2 0x7f521120235c /workspace/TensorRT-LLM/venv/lib/python3.10/site-packages/tensorrt_llm/libs/libnvinfer_plugin_tensorrt_llm.so(+0x3635c) [0x7f521120235c]
3 0x7f5279d39fc9 /usr/local/tensorrt/lib/libnvinfer.so.9(+0x10aefc9) [0x7f5279d39fc9]
4 0x7f5279cfce04 /usr/local/tensorrt/lib/libnvinfer.so.9(+0x1071e04) [0x7f5279cfce04]
5 0x7f5279cfe9a0 /usr/local/tensorrt/lib/libnvinfer.so.9(+0x10739a0) [0x7f5279cfe9a0]
6 0x7f528869dc60 /workspace/TensorRT-LLM/venv/lib/python3.10/site-packages/tensorrt/tensorrt.so(+0x9dc60) [0x7f528869dc60]
7 0x7f5288642ea3 /workspace/TensorRT-LLM/venv/lib/python3.10/site-packages/tensorrt/tensorrt.so(+0x42ea3) [0x7f5288642ea3]
8 0x55b248fc099e python3(+0x15c99e) [0x55b248fc099e]
9 0x55b248fb74ab _PyObject_MakeTpCall + 603
10 0x55b248fcef0b python3(+0x16af0b) [0x55b248fcef0b]
11 0x55b248faf462 _PyEval_EvalFrameDefault + 25522
12 0x55b248fc11ec _PyFunction_Vectorcall + 124
13 0x55b248fa98cb _PyEval_EvalFrameDefault + 2075
14 0x55b248fc11ec _PyFunction_Vectorcall + 124
15 0x55b248fa98cb _PyEval_EvalFrameDefault + 2075
16 0x55b248fc11ec _PyFunction_Vectorcall + 124
17 0x55b248fa98cb _PyEval_EvalFrameDefault + 2075
18 0x55b248fc11ec _PyFunction_Vectorcall + 124
19 0x55b248fcf8e2 PyObject_Call + 290
20 0x55b248fabaf0 _PyEval_EvalFrameDefault + 10816
21 0x55b248fcec31 python3(+0x16ac31) [0x55b248fcec31]
22 0x55b248faaadf _PyEval_EvalFrameDefault + 6703
23 0x55b248fc11ec _PyFunction_Vectorcall + 124
24 0x55b248fcf8e2 PyObject_Call + 290
25 0x55b248fabaf0 _PyEval_EvalFrameDefault + 10816
26 0x55b248fa5ed6 python3(+0x141ed6) [0x55b248fa5ed6]
27 0x55b24909c366 PyEval_EvalCode + 134
28 0x55b2490c9108 python3(+0x265108) [0x55b2490c9108]
29 0x55b2490c1f5b python3(+0x25df5b) [0x55b2490c1f5b]
30 0x55b2490c8e55 python3(+0x264e55) [0x55b2490c8e55]
31 0x55b2490c8338 _PyRun_SimpleFileObject + 424
32 0x55b2490c8033 _PyRun_AnyFileObject + 67
33 0x55b2490b92de Py_RunMain + 702
34 0x55b24908f32d Py_BytesMain + 45
35 0x7f53d9dc1d90 /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f53d9dc1d90]
36 0x7f53d9dc1e40 __libc_start_main + 128
37 0x55b24908f225 _start + 37
[e8c9d86cc3cb:93976] *** Process received signal ***
[e8c9d86cc3cb:93976] Signal: Aborted (6)
[e8c9d86cc3cb:93976] Signal code: (-6)
[e8c9d86cc3cb:93976] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7f53d9dda520]
[e8c9d86cc3cb:93976] [ 1] /lib/x86_64-linux-gnu/libc.so.6(pthread_kill+0x12c)[0x7f53d9e2ea7c]
[e8c9d86cc3cb:93976] [ 2] /lib/x86_64-linux-gnu/libc.so.6(raise+0x16)[0x7f53d9dda476]
[e8c9d86cc3cb:93976] [ 3] /lib/x86_64-linux-gnu/libc.so.6(abort+0xd3)[0x7f53d9dc07f3]
[e8c9d86cc3cb:93976] [ 4] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xa2bbe)[0x7f52fca78bbe]
[e8c9d86cc3cb:93976] [ 5] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xae24c)[0x7f52fca8424c]
[e8c9d86cc3cb:93976] [ 6] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xad229)[0x7f52fca83229]
[e8c9d86cc3cb:93976] [ 7] /lib/x86_64-linux-gnu/libstdc++.so.6(__gxx_personality_v0+0x99)[0x7f52fca83999]
[e8c9d86cc3cb:93976] [ 8] /lib/x86_64-linux-gnu/libgcc_s.so.1(+0x16c64)[0x7f53d7110c64]
[e8c9d86cc3cb:93976] [ 9] /lib/x86_64-linux-gnu/libgcc_s.so.1(_Unwind_RaiseException+0x311)[0x7f53d7111321]
[e8c9d86cc3cb:93976] [10] /lib/x86_64-linux-gnu/libstdc++.so.6(__cxa_throw+0x3b)[0x7f52fca8450b]
[e8c9d86cc3cb:93976] [11] /workspace/TensorRT-LLM/venv/lib/python3.10/site-packages/tensorrt_llm/libs/libnvinfer_plugin_tensorrt_llm.so(+0x34e39)[0x7f5211200e39]
[e8c9d86cc3cb:93976] [12] /workspace/TensorRT-LLM/venv/lib/python3.10/site-packages/tensorrt_llm/libs/libnvinfer_plugin_tensorrt_llm.so(+0x3635c)[0x7f521120235c]
[e8c9d86cc3cb:93976] [13] /usr/local/tensorrt/lib/libnvinfer.so.9(+0x10aefc9)[0x7f5279d39fc9]
[e8c9d86cc3cb:93976] [14] /usr/local/tensorrt/lib/libnvinfer.so.9(+0x1071e04)[0x7f5279cfce04]
[e8c9d86cc3cb:93976] [15] /usr/local/tensorrt/lib/libnvinfer.so.9(+0x10739a0)[0x7f5279cfe9a0]
[e8c9d86cc3cb:93976] [16] /workspace/TensorRT-LLM/venv/lib/python3.10/site-packages/tensorrt/tensorrt.so(+0x9dc60)[0x7f528869dc60]
[e8c9d86cc3cb:93976] [17] /workspace/TensorRT-LLM/venv/lib/python3.10/site-packages/tensorrt/tensorrt.so(+0x42ea3)[0x7f5288642ea3]
[e8c9d86cc3cb:93976] [18] python3(+0x15c99e)[0x55b248fc099e]
[e8c9d86cc3cb:93976] [19] python3(_PyObject_MakeTpCall+0x25b)[0x55b248fb74ab]
[e8c9d86cc3cb:93976] [20] python3(+0x16af0b)[0x55b248fcef0b]
[e8c9d86cc3cb:93976] [21] python3(_PyEval_EvalFrameDefault+0x63b2)[0x55b248faf462]
[e8c9d86cc3cb:93976] [22] python3(_PyFunction_Vectorcall+0x7c)[0x55b248fc11ec]
[e8c9d86cc3cb:93976] [23] python3(_PyEval_EvalFrameDefault+0x81b)[0x55b248fa98cb]
[e8c9d86cc3cb:93976] [24] python3(_PyFunction_Vectorcall+0x7c)[0x55b248fc11ec]
[e8c9d86cc3cb:93976] [25] python3(_PyEval_EvalFrameDefault+0x81b)[0x55b248fa98cb]
[e8c9d86cc3cb:93976] [26] python3(_PyFunction_Vectorcall+0x7c)[0x55b248fc11ec]
[e8c9d86cc3cb:93976] [27] python3(_PyEval_EvalFrameDefault+0x81b)[0x55b248fa98cb]
[e8c9d86cc3cb:93976] [28] python3(_PyFunction_Vectorcall+0x7c)[0x55b248fc11ec]
[e8c9d86cc3cb:93976] [29] python3(PyObject_Call+0x122)[0x55b248fcf8e2]
[e8c9d86cc3cb:93976] *** End of error message ***
Aborted (core dumped)

**Comment by byshiue** [comment]
V100 does not support SQ because SQ requires INT8 tensor core and V100 does not hav INT8 tensor core.
