### ISSUE TITLE
Error when building TensorRT-LLM in the docker from main branch

### ISSUE THREAD

**Issue by shainisan** [NVIDIA/TensorRT-LLM#438]
After changing the git branch from "release/0.5.0" to "main" I'm not able to rebuild the TensorRT-LLM from source.

Steps:

1. 
`apt-get update && apt-get -y install git git-lfs

git clone https://github.com/NVIDIA/TensorRT-LLM.git
cd TensorRT-LLM
git submodule update --init --recursive
git lfs install
git lfs pull` 

2. `make -C docker build`

3. `git checkout main`

4. `make -C docker run`

5. `python3 ./scripts/build_wheel.py --trt_root /usr/local/tensorrt`

The error output:
tensorrt_llm/kernels/CMakeFiles/kernels_src.dir/cutlass_kernels/fpA_intB_gemm/fp16_int8_gemm_fg_scalebias.cu.o
[ 76%] Building CUDA object tensorrt_llm/kernels/CMakeFiles/kernels_src.dir/cutlass_kernels/fpA_intB_gemm/fp16_int8_gemm_fg_scaleonly.cu.o
[ 78%] Building CUDA object tensorrt_llm/kernels/CMakeFiles/kernels_src.dir/cutlass_kernels/fpA_intB_gemm/fp16_int8_gemm_per_col.cu.o
[ 78%] Building CUDA object tensorrt_llm/kernels/CMakeFiles/kernels_src.dir/cutlass_kernels/int8_gemm/int8_gemm_bf16.cu.o
[ 78%] Built target layers_src
[ 78%] Building CUDA object tensorrt_llm/kernels/CMakeFiles/kernels_src.dir/cutlass_kernels/int8_gemm/int8_gemm_fp16.cu.o
[ 78%] Building CUDA object tensorrt_llm/kernels/CMakeFiles/kernels_src.dir/cutlass_kernels/int8_gemm/int8_gemm_fp32.cu.o
[ 79%] Building CUDA object tensorrt_llm/kernels/CMakeFiles/kernels_src.dir/cutlass_kernels/int8_gemm/int8_gemm_int32.cu.o
/code/tensorrt_llm/3rdparty/cutlass/include/cutlass/epilogue/threadblock/default_epilogue_tensor_op.h(244): error: static assertion failed with "ElementOutput needs to be 4 or 8 bit (unsigned) int."
    static_assert(platform::is_same<ElementOutput, cutlass::int4b_t>::value ||
    ^
          detected during:
            instantiation of class "cutlass::epilogue::threadblock::detail::DefaultIteratorsTensorOp<ElementOutput, int32_t, ElementsPerAccess, ThreadblockShape, WarpShape, InstructionShape, ThreadMap> [with ElementOutput=cutlass::half_t, ElementsPerAccess=8, ThreadblockShape=cutlass::gemm::GemmShape<128, 128, 64>, WarpShape=cutlass::gemm::GemmShape<64, 32, 64>, InstructionShape=cutlass::gemm::GemmShape<8, 8, 16>, ThreadMap=cutlass::epilogue::threadblock::OutputTileOptimalThreadMap<cutlass::epilogue::threadblock::OutputTileShape<128, 8, 2, 1, 1>, cutlass::epilogue::threadblock::OutputTileShape<1, 8, 1, 1, 8>, 256, 8, 16>::CompactedThreadMap]" at line 369
            instantiation of class "cutlass::epilogue::threadblock::DefaultEpilogueTensorOp<Shape_, WarpMmaTensorOp_, PartitionsK, OutputOp_, ElementsPerAccess, ScatterD, PermuteDLayout> [with Shape_=cutlass::gemm::GemmShape<128, 128, 64>, WarpMmaTensorOp_=cutlass::gemm::warp::MmaTensorOp<cutlass::gemm::GemmShape<64, 32, 64>, int8_t, cutlass::layout::RowMajorTensorOpMultiplicandCrosswise<8, 64>, int8_t, cutlass::layout::ColumnMajorTensorOpMultiplicandCrosswise<8, 64>, int32_t, cutlass::layout::RowMajor, cutlass::gemm::warp::MmaTensorOpPolicy<cutlass::arch::Mma<cutlass::gemm::GemmShape<8, 8, 16>, 32, int8_t, cutlass::layout::RowMajor, int8_t, cutlass::layout::ColumnMajor, int, cutlass::layout::RowMajor, cutlass::arch::OpMultiplyAddSaturate>, cutlass::MatrixShape<1, 1>>, 1, false, __nv_bool>, PartitionsK=1, OutputOp_=cutlass::epilogue::thread::LinearCombination<cutlass::half_t, 8, float, float, cutlass::epilogue::thread::ScaleType::Default, cutlass::FloatRoundStyle::round_to_nearest>, ElementsPerAccess=8, ScatterD=false, PermuteDLayout=cutlass::layout::NoPermute]" at line 327 of /code/tensorrt_llm/3rdparty/cutlass/include/cutlass/gemm/kernel/default_gemm.h
            instantiation of class "cutlass::gemm::kernel::DefaultGemm<ElementA, LayoutA, kAlignmentA, ElementB, LayoutB, kAlignmentB, ElementC, cutlass::layout::RowMajor, ElementAccumulator, cutlass::arch::OpClassTensorOp, cutlass::arch::Sm75, ThreadblockShape, WarpShape, InstructionShape, EpilogueOutputOp, ThreadblockSwizzle, 2, SplitKSerial, Operator, SharedMemoryClear, GatherA, GatherB, ScatterD, PermuteDLayout, void> [with ElementA=int8_t, LayoutA=cutlass::layout::RowMajor, kAlignmentA=16, ElementB=int8_t, LayoutB=cutlass::layout::ColumnMajor, kAlignmentB=16, ElementC=cutlass::half_t, ElementAccumulator=int32_t, ThreadblockShape=cutlass::gemm::GemmShape<128, 128, 64>, WarpShape=cutlass::gemm::GemmShape<64, 32, 64>, InstructionShape=cutlass::gemm::GemmShape<8, 8, 16>, EpilogueOutputOp=cutlass::epilogue::thread::LinearCombination<cutlass::half_t, 8, float, float, cutlass::epilogue::thread::ScaleType::Default, cutlass::FloatRoundStyle::round_to_nearest>, ThreadblockSwizzle=cutlass::gemm::threadblock::GemmIdentityThreadblockSwizzle<1>, SplitKSerial=true, Operator=cutlass::arch::OpMultiplyAddSaturate, SharedMemoryClear=cutlass::gemm::SharedMemoryClearOption::kNone, GatherA=false, GatherB=false, ScatterD=false, PermuteDLayout=cutlass::layout::NoPermute]" at line 98 of /code/tensorrt_llm/cpp/tensorrt_llm/kernels/cutlass_kernels/int8_gemm/int8_gemm_template.h
            instantiation of "void tensorrt_llm::kernels::cutlass_kernels::genericInt8GemmKernelLauncher<T,arch,ThreadblockShape,WarpShape,Stages>(const int8_t *, const int8_t *, tensorrt_llm::common::QuantMode, const float *, const float *, T *, int, int, int, tensorrt_llm::cutlass_extensions::CutlassGemmConfig, char *, size_t, cudaStream_t, int *) [with T=half, arch=cutlass::arch::Sm75, ThreadblockShape=cutlass::gemm::GemmShape<128, 128, 64>, WarpShape=cutlass::gemm::GemmShape<64, 32, 64>, Stages=2]" at line 197 of /code/tensorrt_llm/cpp/tensorrt_llm/kernels/cutlass_kernels/int8_gemm/int8_gemm_template.h
            instantiation of "void tensorrt_llm::kernels::cutlass_kernels::dispatchStages<T, arch, ThreadblockShape, WarpShape, 2, void>::dispatch(const int8_t *, const int8_t *, tensorrt_llm::common::QuantMode, const float *, const float *, T *, int, int, int, tensorrt_llm::cutlass_extensions::CutlassGemmConfig, char *, size_t, cudaStream_t, int *) [with T=half, arch=cutlass::arch::Sm75, ThreadblockShape=cutlass::gemm::GemmShape<128, 128, 64>, WarpShape=cutlass::gemm::GemmShape<64, 32, 64>]" at line 227 of /code/tensorrt_llm/cpp/tensorrt_llm/kernels/cutlass_kernels/int8_gemm/int8_gemm_template.h
            instantiation of "void tensorrt_llm::kernels::cutlass_kernels::dispatchGemmConfig<T,arch,ThreadblockShape,WarpShape>(const int8_t *, const int8_t *, tensorrt_llm::common::QuantMode, const float *, const float *, T *, int, int, int, tensorrt_llm::cutlass_extensions::CutlassGemmConfig, char *, size_t, cudaStream_t, int *) [with T=half, arch=cutlass::arch::Sm75, ThreadblockShape=cutlass::gemm::GemmShape<128, 128, 64>, WarpShape=cutlass::gemm::GemmShape<64, 32, 64>]" at line 269 of /code/tensorrt_llm/cpp/tensorrt_llm/kernels/cutlass_kernels/int8_gemm/int8_gemm_template.h
            instantiation of "void tensorrt_llm::kernels::cutlass_kernels::dispatchGemmToCutlass<T,arch>(const int8_t *, const int8_t *, tensorrt_llm::common::QuantMode, const float *, const float *, T *, int, int, int, char *, size_t, tensorrt_llm::cutlass_extensions::CutlassGemmConfig, cudaStream_t, int *) [with T=half, arch=cutlass::arch::Sm75]" at line 341 of /code/tensorrt_llm/cpp/tensorrt_llm/kernels/cutlass_kernels/int8_gemm/int8_gemm_template.h
            instantiation of "void tensorrt_llm::kernels::cutlass_kernels::CutlassInt8GemmRunner<T>::dispatchToArch(const int8_t *, const int8_t *, tensorrt_llm::common::QuantMode, const float *, const float *, T *, int, int, int, tensorrt_llm::cutlass_extensions::CutlassGemmConfig, char *, size_t, cudaStream_t, int *) [with T=half]" at line 361 of /code/tensorrt_llm/cpp/tensorrt_llm/kernels/cutlass_kernels/int8_gemm/int8_gemm_template.h

12 errors detected in the compilation of "/code/tensorrt_llm/cpp/tensorrt_llm/kernels/cutlass_kernels/int8_gemm/int8_gemm_fp16.cu".
gmake[3]: *** [tensorrt_llm/kernels/CMakeFiles/kernels_src.dir/build.make:2993: tensorrt_llm/kernels/CMakeFiles/kernels_src.dir/cutlass_kernels/int8_gemm/int8_gemm_fp16.cu.o] Error 1
gmake[3]: *** Waiting for unfinished jobs....
[ 79%] Built target common_src
[ 79%] Built target runtime_src
gmake[2]: *** [CMakeFiles/Makefile2:782: tensorrt_llm/kernels/CMakeFiles/kernels_src.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:708: tensorrt_llm/CMakeFiles/tensorrt_llm.dir/rule] Error 2
gmake: *** [Makefile:179: tensorrt_llm] Error 2
Traceback (most recent call last):
  File "/code/tensorrt_llm/./scripts/build_wheel.py", line 278, in <module>
    main(**vars(args))
  File "/code/tensorrt_llm/./scripts/build_wheel.py", line 158, in main
    build_run(
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cmake --build . --config Release --parallel 20 --target tensorrt_llm tensorrt_llm_static nvinfer_plugin_tensorrt_llm th_common  ' returned non-zero exit status 2.`

If I skip step (3) everything works but then I can't use the new features in the main branch.

Thank you.

**Comment by nv-guomingz** [comment]
You may miss one step `git submodule update --init --recursive` which required for updating cutlass.

**Comment by shainisan** [comment]
Thank you!
