### ISSUE TITLE
【Confuse】"Does the internal integration of FlashAttention in TensorRT-LLM use version 1 or has it been updated to the new FlashAttention 2 version?"

### ISSUE THREAD

**Issue by Astrallee** [NVIDIA/TensorRT-LLM#439]
RT,
Does the internal integration of FlashAttention in TensorRT-LLM use version 1 or has it been updated to the new FlashAttention 2 version?

<img width="805" alt="1" src="https://github.com/NVIDIA/TensorRT-LLM/assets/48097779/5fab8d4a-4d57-4858-a80e-32be6ded66eb">

This picture mentions that FlashAttention has been integrated. According to FlashAttention's GitHub, version 2 has made significant improvements.

**Comment by byshiue** [comment]
Yes, it uses idea of flash attention version 2.
