### ISSUE TITLE
libnvinfer_plugin_tensorrt_llm.so: cannot open shared object file: Not a directory

### ISSUE THREAD

**Issue by ilas-zzk** [NVIDIA/TensorRT-LLM#442]
python build.py --model_dir /home/imcp/ChatGlm3/model/ --dtype float16 --use_gemm_plugin float16 --use_gpt_attention_plugin float16 --output_dir /home/imcp/ChatGlm3/onnx/
Traceback (most recent call last):
  File "/home/imcp/TensorRT-LLM-main/examples/chatglm/build.py", line 26, in <module>
    from weight import load_from_hf
  File "/home/imcp/TensorRT-LLM-main/examples/chatglm/weight.py", line 24, in <module>
    import tensorrt_llm
  File "/home/imcp/anaconda3/envs/tensorrt/lib/python3.10/site-packages/tensorrt_llm-0.5.0-py3.10.egg/tensorrt_llm/__init__.py", line 58, in <module>
  File "/home/imcp/anaconda3/envs/tensorrt/lib/python3.10/site-packages/tensorrt_llm-0.5.0-py3.10.egg/tensorrt_llm/_common.py", line 44, in _init
  File "/home/imcp/anaconda3/envs/tensorrt/lib/python3.10/site-packages/tensorrt_llm-0.5.0-py3.10.egg/tensorrt_llm/plugin/plugin.py", line 34, in _load_plugin_lib
  File "/home/imcp/anaconda3/envs/tensorrt/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/imcp/anaconda3/envs/tensorrt/lib/python3.10/site-packages/tensorrt_llm-0.5.0-py3.10.egg/tensorrt_llm/libs/libnvinfer_plugin_tensorrt_llm.so: cannot open shared object file: Not a directory

**Comment by byshiue** [comment]
That means you don't install the tensorrt llm successfully. Can you share your scripts to build the docker image?

**Comment by ilas-zzk** [comment]
pip list
Package                      Version
---------------------------- -----------------
absl-py                      2.0.0
accelerate                   0.20.3
aiohttp                      3.9.0
aiosignal                    1.3.1
appdirs                      1.4.4
astunparse                   1.6.3
async-timeout                4.0.3
attrs                        23.1.0
build                        1.0.3
cachetools                   5.3.2
certifi                      2023.11.17
cfgv                         3.4.0
charset-normalizer           3.3.2
click                        8.1.7
colored                      2.2.3
coloredlogs                  15.0.1
coverage                     7.3.2
cuda-python                  12.2.0
Cython                       3.0.5
datasets                     2.14.7
diffusers                    0.15.0
dill                         0.3.7
distlib                      0.3.7
einops                       0.7.0
evaluate                     0.4.1
exceptiongroup               1.1.3
execnet                      2.0.2
filelock                     3.13.1
flatbuffers                  1.12
frozenlist                   1.4.0
fsspec                       2023.10.0
gast                         0.4.0
google-auth                  2.23.4
google-auth-oauthlib         0.4.6
google-pasta                 0.2.0
graphviz                     0.20.1
grpcio                       1.59.3
h5py                         3.10.0
huggingface-hub              0.19.4
humanfriendly                10.0
identify                     2.5.32
idna                         3.4
importlib-metadata           6.8.0
iniconfig                    2.0.0
Jinja2                       3.1.2
joblib                       1.3.2
keras                        2.9.0
Keras-Preprocessing          1.1.2
lark                         1.1.8
libclang                     16.0.6
Mako                         1.3.0
Markdown                     3.5.1
MarkupSafe                   2.1.3
mpi4py                       3.1.5
mpmath                       1.3.0
multidict                    6.0.4
multiprocess                 0.70.15
mypy                         1.7.0
mypy-extensions              1.0.0
networkx                     3.2.1
nltk                         3.8.1
nodeenv                      1.8.0
numpy                        1.23.1
nvidia-cublas-cu12           12.1.3.1
nvidia-cuda-cupti-cu12       12.1.105
nvidia-cuda-nvrtc-cu12       12.1.105
nvidia-cuda-runtime-cu12     12.1.105
nvidia-cudnn-cu12            8.9.2.26
nvidia-cufft-cu12            11.0.2.54
nvidia-curand-cu12           10.3.2.106
nvidia-cusolver-cu12         11.4.5.107
nvidia-cusparse-cu12         12.1.0.106
nvidia-nccl-cu12             2.18.1
nvidia-nvjitlink-cu12        12.3.101
nvidia-nvtx-cu12             12.1.105
oauthlib                     3.2.2
onnx                         1.12.0
onnx-graphsurgeon            0.3.27
onnxruntime                  1.12.1
opt-einsum                   3.3.0
packaging                    23.2
pandas                       2.1.3
parameterized                0.9.0
Pillow                       10.1.0
pip                          23.3
platformdirs                 3.11.0
pluggy                       1.3.0
polygraphy                   0.49.0
pre-commit                   3.5.0
protobuf                     3.19.6
psutil                       5.9.6
py                           1.11.0
pyarrow                      14.0.1
pyarrow-hotfix               0.5
pyasn1                       0.5.0
pyasn1-modules               0.3.0
pybind11-stubgen             2.3.7
pycuda                       2023.1
pynvml                       11.5.0
pyproject_hooks              1.0.0
pytest                       7.4.3
pytest-cov                   4.1.0
pytest-forked                1.6.0
pytest-xdist                 3.4.0
python-dateutil              2.8.2
pytools                      2023.1.1
pytz                         2023.3.post1
PyYAML                       6.0.1
regex                        2023.10.3
requests                     2.31.0
requests-oauthlib            1.3.1
responses                    0.18.0
rouge-score                  0.1.2
rsa                          4.9
safetensors                  0.4.0
sentencepiece                0.1.99
setuptools                   68.0.0
six                          1.16.0
sympy                        1.12
tensorboard                  2.9.1
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.1
tensorflow-estimator         2.9.0
tensorflow-gpu               2.9.1
tensorflow-io-gcs-filesystem 0.34.0
tensorrt                     9.1.0.post12.dev4
tensorrt-bindings            8.6.1
tensorrt-libs                8.6.1
tensorrt-llm                 0.5.0
termcolor                    2.3.0
tokenizers                   0.13.3
tomli                        2.0.1
torch                        1.11.0+cu113
torchvision                  0.12.0+cu113
tqdm                         4.66.1
transformers                 4.33.1
triton                       2.1.0
typing_extensions            4.8.0
tzdata                       2023.3
urllib3                      2.1.0
virtualenv                   20.24.6
Werkzeug                     3.0.1
wheel                        0.41.2
wrapt                        1.16.0
xxhash                       3.4.1
yarl                         1.9.2
zipp                         3.17.0

tensorrt llm successfully.version 0.5.0

**Comment by byshiue** [comment]
Can you find the path `/home/imcp/anaconda3/envs/tensorrt/lib/python3.10/site-packages/tensorrt_llm-0.5.0-py3.10.egg/`? 

Do you use the docker file to build the docker?

**Comment by ilas-zzk** [comment]
> Can you find the path `/home/imcp/anaconda3/envs/tensorrt/lib/python3.10/site-packages/tensorrt_llm-0.5.0-py3.10.egg/`?
> 
> Do you use the docker file to build the docker?
I found tensorrt in the I find/home/imcp/anaconde3/envs/tensorrt/lib/python3.10/site packages directory_ The file llm-0.5.0-py3.10.egg. I didn't install it using Docker, I installed it through setup.py.

**Comment by byshiue** [comment]
Could you find the `.so` file in the folder?

**Comment by ilas-zzk** [comment]
> Could you find the `.so` file in the folder?

I'm not sure which so file you're referring to. There are no Tensorrt related so files in the/home/imcp/anaconde3/envs/tensorrt/lib/Python 3.10/sitepackages folder, but there are related so files in the folder below this folder.

**Comment by byshiue** [comment]
I mean this folder `/home/imcp/anaconda3/envs/tensorrt/lib/python3.10/site-packages/tensorrt_llm-0.5.0-py3.10.egg/tensorrt_llm/libs/`. And make sure this folder is exported in `LD_LIBRARY_PATH`.

**Comment by ilas-zzk** [comment]
No /home/imcp/anaconde3/envs/tensorrt/lib/python3.10/site packages/tensorrt_ Llm-0.5.0-py3.10/egg/tensorrt_ Llm/libs/ This folder, /home/imcp/anaconde3/envs/tensorrt/lib/python3.10/site packages/tensorrt_ Llm-0.5.0-py3.10/egg/tensorrt_ Llm/ contains some. py files

**Comment by byshiue** [comment]
Can you share your scripts to compile tensorrt-llm?

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Please reopen it if needed.
