### ISSUE TITLE
Is there a rather-easy method to implement and apply a new plugin in tensor-llm?

### ISSUE THREAD

**Issue by xinji1** [NVIDIA/TensorRT-LLM#446]
Hi,  i'm just trying to make some code changes in Plugin-level (take `cpp/tensorrt_llm/plugins/gptAttentionPlugin` as an example). It looks like i have to Build TensorRT-LLM again (like `Build TensorRT-LLM` in `docs/source/installation.md`), after rewriting the codes. Is there another fast way for developers to check whether the new plugin works?

**Comment by byshiue** [comment]
I think the simplest way is adding some debug message in your plugin.

**Comment by jdemouth-nvidia** [comment]
You don't have to rebuild the entire TensorRT-LLM C++ code every time you make a change to the plugin. It should be able to use the incremental build and that should not take a lot of time.

Also, as long as you don't change the API of the plugin, it should not be needed to recreate the engine. The runtime will be able to load the plugin library.

**Comment by JensenFire** [comment]
thanks, i'll have a try!
