### ISSUE TITLE
Integration Support for OpenChat 3.5 with NVIDIA TensorRT: Uninitialized Weights Issue

### ISSUE THREAD

**Issue by tsathya98** [NVIDIA/TensorRT-LLM#449]
Firstly, I would like to commend the efforts that have been taken to optimize LLM performance across different models!!
I am willing to optimize the OpenChat 3.5 language model using NVIDIA TensorRT for enhanced inference performance. The model demonstrates exceptional capabilities, and I believe that TensorRT could further augment its inference speed. However, I have encountered an issue with uninitialized weights during the build process within the TensorRT environment.

### Steps to Reproduce
1. The OpenChat model came with its weights split across two binary files. To prepare for TensorRT optimization, I merged these into a single `pytorch_model.bin` file.
2. Confirmed that the combined binary file works seamlessly with the OpenChat server, producing consistent inference results as with the original split files.
3. Proceeded with the TensorRT build process as per the standard instructions provided in the TensorRT documentation.
    Used this as reference from https://github.com/NVIDIA/TensorRT-LLM/tree/release/0.5.0/examples/llama:
    ```
    # Build the LLaMA 7B model using a single GPU and FP16.
    python build.py --model_dir <model_dir> \
                    --dtype float16 \
                    --remove_input_padding \
                    --use_gpt_attention_plugin float16 \
                    --enable_context_fmha \
                    --use_gemm_plugin float16 \
                    --output_dir <output_dir>
    ```

4. During the build, I found that certain layer weights are not being initialized as expected, potentially impacting the model's performance.

The script used for combining the binary files is as follows:

```python
import os
import torch
import json

def combine_model_bins(model_dir, index_file, bin_files, output_file):
    with open(os.path.join(model_dir, index_file), 'r') as f:
        index_data = json.load(f)
    partial_state_dicts = {}
    for bin_file in bin_files:
        partial_state_dict = torch.load(os.path.join(model_dir, bin_file), map_location='cpu')
        partial_state_dicts[bin_file] = partial_state_dict
    complete_state_dict = {}
    for weight_name, bin_file in index_data['weight_map'].items():
        complete_state_dict[weight_name] = partial_state_dicts[bin_file][weight_name]
    torch.save(complete_state_dict, os.path.join(model_dir, output_file))

model_dir = '/'  
index_file = 'pytorch_model.bin.index.json' 
bin_files = ['pytorch_model-00001-of-00002.bin', 'pytorch_model-00002-of-00002.bin'] 
output_file = 'combined_pytorch_model.bin' 
combine_model_bins(model_dir, index_file, bin_files, output_file)
```

#### Current Behavior
The model initializes without errors in TensorRT, but several layer weights, specifically those associated with the self-attention mechanism, are reported as uninitialized. This issue is illustrated in the attached image.
![openchat_tensorRT](https://github.com/NVIDIA/TensorRT-LLM/assets/50142667/6e45a4f8-b572-4001-aa4a-e2c6a605bbda)

#### Expected Behavior
A successful build in TensorRT should initialize all model weights correctly, facilitating the full utilization of TensorRT's inference optimization capabilities.

#### Request for Support
Could you please confirm if OpenChat 3.5 is supported by NVIDIA TensorRT? If it is supported, I might require additional steps or resources to ensure a successful build. In the case that it is not yet supported, could you provide any information on when such support might be anticipated?

#### Your guidance on achieving TensorRT compatibility with OpenChat 3.5 or any available documentation regarding similar processes would be invaluable.
I raised a similar issue on OpenChat GitHub issues page as well [(Issue-92)](https://github.com/imoneoi/openchat/issues/92)
Thank you for your attention and assistance.

Best regards,
Sathya T

**Comment by byshiue** [comment]
The warning should happen when you try using `LlamaForCausalLM` of `transformers` to load your model. 

You can try running inference on `transformers` first to check is your model supported on `transformers` or not. 

If it is supported by `LlamaForCausalLM`, then you should be able to following steps in document to run your model on TensorRT LLM.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Please reopen it if needed.
