### ISSUE TITLE
Failed to build with CUDA 11.8 due to change in cudaGraphExecUpdate parameter

### ISSUE THREAD

**Issue by haojiwei** [NVIDIA/TensorRT-LLM#45]
In CUDA 11.8, cudaGraphExecUpdate signature is:
```
__host__​cudaError_t cudaGraphExecUpdate ( cudaGraphExec_t hGraphExec, cudaGraph_t hGraph, cudaGraphNode_t* hErrorNode_out, cudaGraphExecUpdateResult ** updateResult_out )
```

And in CUDA 12 
cudaGraphExecUpdate signature is:
```
__host__​cudaError_t cudaGraphExecUpdate ( cudaGraphExec_t hGraphExec, cudaGraph_t hGraph, cudaGraphExecUpdateResultInfo* resultInfo )
```

This change cause compiling error in `tensorrt_llm/runtime`.

**Comment by jdemouth-nvidia** [comment]
TensorRT-LLM depends on CUDA 12.2. Is it impossible for you to upgrade to CUDA 12.2?

**Comment by haojiwei** [comment]
Just changing the function signature do work, and it can execute via CUDA 11.8 by far.

**Comment by JosephChenHub** [comment]
> Just changing the function signature do work, and it can execute via CUDA 11.8 by far.

- TensorRT: 9.1.0.4
- CUDA : 11.8
- CUDNN: 8.6.0
- NCCL: 2.18.5

I changed the signature and successfully built a tensorrt engine. 
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/22444830/a73249d1-a776-4924-b0e8-60474b66fc5a)

![image](https://github.com/NVIDIA/TensorRT-LLM/assets/22444830/04f3937c-60c0-4669-a493-6fa03b984b5c)

But it throws an exception when executing: 
```
python3 examples/llama/run.py --engine_dir=./llama2-7b-trt/f16-1gpu/ --max_output_len 100 --tokenizer_dir ../llama-recipes/llama-2-7b-hf-4330/ --input_text "how do i count to nine in Frech?"
```
the error is
```
CUDA Error: CUDA_ERROR_INVALID_IMAGE: TensorRT-LLM/cpp/tensorrt_llm/kernels/contextFusedMultiHeadAttention/fused_multihead_attention_v2.h 99
CUDA Error: CUDA_ERROR_INVALID_IMAGE: TensorRT-LLM/cpp/tensorrt_llm/kernels/contextFusedMultiHeadAttention/fused_multihead_attention_v2.h 105
```
can we solve it?

@jdemouth-nvidia

**Comment by jdemouth-nvidia** [comment]
Thanks for the update @JosephChenHub - I'm afraid it's because our CUBINs for the Context FMHA are built using CUDA 12.x. I'll check with the engineer in charge of that part of the code if he can give it a try to make sure that's the problem. And, if there's a way to work around it.

**Comment by jdemouth-nvidia** [comment]
Hi @JosephChenHub , I’ve verified with our CUDA team. A CUBIN built with CUDA 12.x will not load in CUDA 11.x. CUDA 12.x is required to use TensorRT-LLM.

**Comment by a1164714** [comment]
> Hi @JosephChenHub , I’ve verified with our CUDA team. A CUBIN built with CUDA 12.x will not load in CUDA 11.x. CUDA 12.x is required to use TensorRT-LLM.

my Driver Version: 450.102.04 ,cuda version is 11.0，can i install cuda-compat-12-2 to support 12.x and install trt-llm？

**Comment by jdemouth-nvidia** [comment]
> > Hi @JosephChenHub , I’ve verified with our CUDA team. A CUBIN built with CUDA 12.x will not load in CUDA 11.x. CUDA 12.x is required to use TensorRT-LLM.
> 
> my Driver Version: 450.102.04 ,cuda version is 11.0，can i install cuda-compat-12-2 to support 12.x and install trt-llm？

You must update your CUDA toolkit and update the driver. There’s no way around it.
