### ISSUE TITLE
Can I use a A800 machine to build the engine and deploy it on a V100 machine?

### ISSUE THREAD

**Issue by Kevinddddddd** [NVIDIA/TensorRT-LLM#450]
I want to deploy a model on a V100 machine, but its cpu memory size is 32G and connot build the engine successfully. May I use a A800 machine with enough cpu mempry size to build the engine and deploy it on a V100 machine? The build.py for baichuan models has memory leak problems and 32G is not enought to build the engine successfully.

**Comment by nv-guomingz** [comment]
No, please refer to [explaination](https://github.com/onnx/onnx-tensorrt/issues/421#issuecomment-694598210).

**Comment by Kevinddddddd** [comment]
> No, please refer to [explaination](https://github.com/onnx/onnx-tensorrt/issues/421#issuecomment-694598210).

Get, thx.
