### ISSUE TITLE
what is the difference between tensorrt inflight batch and vllm continue batching tech? 

### ISSUE THREAD

**Issue by shatealaboxiaowang** [NVIDIA/TensorRT-LLM#451]
Dear:

I ran concurrent (say 20 concurrent) tests on both tensorrt and vllm, where vllm takes the same amount of time and returns almost simultaneously every request, and tensorrt, where the delay is incremental and returns incrementally.

I would like to know what scenarios to use tensorrt and what scenarios to use vllm.

Thank you very much for your reply!

**Comment by byshiue** [comment]
Can you share your end to end reproduced steps to run TensorRT LLM?

**Comment by jdemouth-nvidia** [comment]
As you may imagine, we do not want to comment about other solutions. We develop TensorRT-LLM, if you have a performance issue with TensorRT-LLM, please, share a way to reproduce the issue and we’ll investigate. Thanks!

**Comment by shatealaboxiaowang** [comment]
Thank you very much, When I compare the performance of tensorrt-llm and vllm on the same gpu resources, I find that the performance of a single batch of tensorrt-llm is stronger than that of vllm, but when the batch is larger, the performance of tensorrt-llm gradually becomes worse than that of vllm.

I ran a concurrency test with commands like the one below:
       ab -n 256 -c 128 -H "Content-Type: application/json" -p input.json -T "application/json" http://localhost:8019/v2/models/ensemble/generate

thank you!

**Comment by byshiue** [comment]
Could you share the number you get on different batch size and the build script you use to build engine?

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Please reopen it if needed.
