### ISSUE TITLE
ERROS - while building a wheel for trt_llm

### ISSUE THREAD

**Issue by pandyamarut** [NVIDIA/TensorRT-LLM#454]
<img width="1438" alt="Screenshot 2023-11-22 at 11 19 05 AM" src="https://github.com/NVIDIA/TensorRT-LLM/assets/28846178/563d8b90-ce93-4605-94b4-b2e5bfa8077a">

I have been trying to build a wheel, what dependency or anything I have been missing ?

**Comment by Shixiaowei02** [comment]
Please show me the content of `CMakeOutput.log`, thanks!

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Please reopen it if needed.
