### ISSUE TITLE
Attention kernels

### ISSUE THREAD

**Issue by rayleizhu** [NVIDIA/TensorRT-LLM#457]
As the [document](https://nvidia.github.io/TensorRT-LLM/gpt_attention.html#context-and-generation-phases) specifies, the decoding procedure involves two phases (context and generation phases). 

1. Does the context phase refer to the prefilling phase, which fills the initial KV cache with the request prompts and generates the first token? It is only called at the first generation step, right?
2. Do the context and generation phases call the same attention kernel implementation, or do they call different ones? I get a little bit confused on the document description and the structure of CUDA kernel source tree:
   - https://nvidia.github.io/TensorRT-LLM/gpt_attention.html#context-phase
   - https://github.com/NVIDIA/TensorRT-LLM/tree/release/0.5.0/cpp/tensorrt_llm/kernels/contextFusedMultiHeadAttention
   - https://github.com/NVIDIA/TensorRT-LLM/tree/release/0.5.0/cpp/tensorrt_llm/kernels/decoderMaskedMultiheadAttention
3. How are they switched in the Python front-end if they call different attention kernels?

**Comment by byshiue** [comment]
> 1. Does the context phase refer to the prefilling phase, which fills the initial KV cache with the request prompts and generates the first token? It is only called at the first generation step, right?

Correct. 

> 2. Do the context and generation phases call the same attention kernel implementation, or do they call different ones?

They call different kernels. In context phase, we use https://github.com/NVIDIA/TensorRT-LLM/tree/release/0.5.0/cpp/tensorrt_llm/kernels/contextFusedMultiHeadAttention. In generation, we use https://github.com/NVIDIA/TensorRT-LLM/tree/release/0.5.0/cpp/tensorrt_llm/kernels/decoderMaskedMultiheadAttention. 

> 3. How are they switched in the Python front-end if they call different attention kernels?

It is determined by `host_request_types` like here https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/tensorrt_llm/runtime/generation.py#L1030-L1045.

**Comment by jdemouth-nvidia** [comment]
Thanks. I’m closing that issue. Feel free to reopen if needed.

**Comment by rayleizhu** [comment]
Does the [generation-phase kernel (decoderMaskedMultiheadAttention)](https://github.com/NVIDIA/TensorRT-LLM/tree/release/0.5.0/cpp/tensorrt_llm/kernels/decoderMaskedMultiheadAttention) support query length > 1 (e.g., the query has a logical shape of  (bs=8, head=8, q_len=32, hed_dim=64))?

1. As far as I know, for the GPT inference scenario, q_len is always 1 in the generation phase.
2. However, my hacking needs to cope with q_len > 1. Is the generation-phase kernel general, like FlashDecoding, or specialized for q_len=1?
3. If the generation-phase kernel does not support q_len > 1, can you give some suggestions for my hacking?

**Comment by rayleizhu** [comment]
> Thanks. I’m closing that issue. Feel free to reopen if needed.

@jdemouth-nvidia I'm not able to reopen this issue, according to the [rule of GitHub](https://stackoverflow.com/a/21333938).
