### ISSUE TITLE
How to implement INT4 conv plugin with tensorrt and cutlass?

### ISSUE THREAD

**Issue by yuanjiechen** [NVIDIA/TensorRT-LLM#462]
Hello:
I'm try to implement a INT4 conv layer in trtllm.
I want to use these cutlass function (templete) in plugin:
https://github.com/NVIDIA/cutlass/blob/main/examples/16_ampere_tensorop_conv2dfprop/ampere_tensorop_conv2dfprop.cu https://github.com/NVIDIA/cutlass/blob/main/test/unit/conv/device/conv2d_fprop_implicit_gemm_s4nhwc_s4nhwc_s32nhwc_tensor_op_s32_sm80.cu

I meet two diffucults, the one is INT4 inputs, I have no idea how to generate INT4 inputs from trt to plugin, because trt has no this datatype INT4. 
Another is what's the tensor format need to use in plugin, the format in the above example are NHWC, but the common conv weight format is Cout, Cin, H, W, and the input is N, C, H, W. Is I need a tensor.transpose to reformat the weight or input?

Thanks !

**Comment by juney-nvidia** [comment]
Let me invite my colleague @Jackch-NV  to help with this question. 

June

**Comment by Jackch-NV** [comment]
Hi @yuanjiechen ,  
      For the int4 input, you can refer to how we deal with int4 weight in AWQ : https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/examples/llama/weight.py#L1108. You can set the data type of tensor to float, which actually stores int4 data, and you need to carefullly deal with the shape inside the plugin to use the data correctly, as in the [weightOnlyGroupwiseQuantMatmulPlugin](https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/cpp/tensorrt_llm/plugins/weightOnlyGroupwiseQuantMatmulPlugin/).
     For the layout of int4 conv, my suggestion is that, for weight, you can preprocess them into any layout with pytorch, it will not increase the latency of inference. For input, you can transpose the input into NHWC at the beginning of inference and keep the format of all activations NHWC during the whole inference pipeline. The transpose of input only happen once and can be done outside TRTLLM engine as preprocessing or you can add a transpose kernel in your plugin.

**Comment by yuanjiechen** [comment]
Hi @Jackch-NV :
Thanks for your reply, I will try for it.
I have some another question, how to add plugin to trt-llm, is some toritorial here?
And my BN fused bias is fp32 dtype, I must de-quant the conv result than add bias on it? 
Thanks !

**Comment by Jackch-NV** [comment]
Hi @yuanjiechen ,
In TensorRT-LLM, we have some docs to introduce how to add a customized plugin, maybe you can refer to them : https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/architecture.md#plugins && https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/openai_triton/manual_plugin#2-implement-a-custom-tensorrt-plugin.
For bias, we usually avoid quantizing them to avoid accuracy drop, so yes, you should de-quant te conv result and then add fp32 bias on it.

**Comment by yuanjiechen** [comment]
Hi @Jackch-NV :
Follow the document I write my plugin body and add plugin name to Cmakelist, plugins/api/tllmPlugin.cpp.
But I meet some internal error when I compile the plugin.
Here is the makefile output, could you provide some tips, maybe I missed some complie flag? (c++ 17 default enabled)
[err.txt](https://github.com/NVIDIA/TensorRT-LLM/files/13483142/err.txt)
[QuantConvPlugin.cpp.txt](https://github.com/NVIDIA/TensorRT-LLM/files/13483158/QuantConvPlugin.cpp.txt)
[QuantConvPlugin.h.txt](https://github.com/NVIDIA/TensorRT-LLM/files/13483159/QuantConvPlugin.h.txt)

Thanks

**Comment by Jackch-NV** [comment]
Hi @yuanjiechen ,
From the err.txt, I think the errors are about cutlass but not plugin. I suggest we check the usage of cutlass, for example the version of cutlass.

**Comment by yuanjiechen** [comment]
Hi @Jackch-NV ,
Thanks for your reply.
I consider it's the namespace problem, and cause the duplicate definition.
I don't know which namespace I need to put the cutlass algorithms. 
Is there some trtllm document introduce it? 
Thanks

**Comment by Jackch-NV** [comment]
Hi @yuanjiechen ,
Sorry that we don't have document to introduce how to use cutlass in TRTLLM plugin, but you can refer to [weightOnlyGroupwiseQuantMatmulPlugin](https://github.com/NVIDIA/TensorRT-LLM/tree/release/0.5.0/cpp/tensorrt_llm/plugins/weightOnlyGroupwiseQuantMatmulPlugin) or [smoothQuantGemmPlugin](https://github.com/NVIDIA/TensorRT-LLM/tree/release/0.5.0/cpp/tensorrt_llm/plugins/smoothQuantGemmPlugin), they use cutlass for gemm which is similar to your conv2d case.

**Comment by yuanjiechen** [comment]
Hi @Jackch-NV ,
Thanks for your help, I will carefully read the example and try to used in conv2d.
If I failed, I will use cutlass python interface to implement my kernel.
Thanks for your time!
