### ISSUE TITLE
When will 0.6.0 be released?

### ISSUE THREAD

**Issue by callmezhangchenchenokay** [NVIDIA/TensorRT-LLM#463]
Is there a specific time

**Comment by juney-nvidia** [comment]
@callmezhangchenchenokay 

Hi, the current plan is to release 0.6.0 in the end of November. Based on concrete execution feedback, the release date might have some adjustment though.

If you want to try the new features of TensorRT-LLM, you can also use the latest main branch to have a try.

Thanks
June
