### ISSUE TITLE
How to deal with slice when there's -1 in the dims?

### ISSUE THREAD

**Issue by AsakusaRinne** [NVIDIA/TensorRT-LLM#469]
Hi, I met a problem during the development of rwkv model support.

When building the model I have a tensor with shape `(-1, -1, 2048)` and I want to execute `x.slice[:, -1:, :]`. If I could convert the expression to using starts and lengths, which is `x.slice([0, x.size(1) - 1, 0], [x.size(0), 1, x.size(2)])`, the `-1` in the shape leads to the following error. 

```
 [TRT] [E] 9: [graphShapeAnalyzer.cpp::addVolumeCheck::879] Error Code 9: Internal Error ((Unnamed Layer* 6671) [Slice]_output: dimension 0 never exceeds -1)
```

How should I do to implement `x.slice[:, -1:, :]` in TensorRT-LLM? I'll really appreciate for any help! :)

**Comment by SanftMonster** [comment]
Another saying is that, if we just don't want to slice a dim, and this dim is `-1`, is there a way to express it?

**Comment by robosina** [comment]
@AsakusaRinne I did something similar by using `set_input`, but I'm sure there might be a better solution. By the way, I returned the `slice layer` from the `slice` function and then used `set_input` on a shape, which can have -1 in its dimensions It worked for me initially, but after some time, I decided to move the slicing out of the TensorRT network and pass it as input parameters( pass it in TensorRT context), which, in my case, is doable. However, in your case, it might not be. I hope the team have better approach.

https://docs.nvidia.com/deeplearning/tensorrt/api/python_api/infer/Graph/Layers.html?highlight=islicelayer#tensorrt.ISliceLayer.set_input

**Comment by SanftMonster** [comment]
Thank you a lot for your help! I 'm trying using `select` to replace slice. However I'm not sure if everything will go well at runtime. :)

**Comment by litaotju** [comment]
@AsakusaRinne 
could you try to replace the `x.size(1) - 1` to be  
```
s = gather(shape(x), 1) - constant(int32_array([1]))
``` 
See  https://github.com/NVIDIA/TensorRT-LLM/blob/main/tensorrt_llm/functional.py#L1504 for the shape function usage.

x.size(1) here returns the `-1`, but what you really need is a symbolic value of that shape such that the runtime could use the actual shape to do slice.

(We may enhance the syntax in the future, but now to get the dynamic dimension, you need to use the `def shape(...)` function, instead of the Tensor.size

**Comment by SanftMonster** [comment]
> @AsakusaRinne could you try to replace the `x.size(1) - 1` to be
> 
> ```
> s = gather(shape(x), 1) - constant(int32_array([1]))
> ```
> 
> See https://github.com/NVIDIA/TensorRT-LLM/blob/main/tensorrt_llm/functional.py#L1504 for the shape function usage.
> 
> x.size(1) here returns the `-1`, but what you really need is a symbolic value of that shape such that the runtime could use the actual shape to do slice.
> 
> (We may enhance the syntax in the future, but now to get the dynamic dimension, you need to use the `def shape(...)` function, instead of the Tensor.size

Thank you for the reply! May I ask why using `gather` here? And the `gather` accepts three inputs instead of two in your example.
