### ISSUE TITLE
GPTLMHeadModel error when building engine with both --use_embedding_sharing --gather_all_token_logits

### ISSUE THREAD

**Issue by dongluw** [NVIDIA/TensorRT-LLM#470]
I was able to build engine for my model with either one of these two flags on, but with both, I got the following error, please help
```
[11/24/2023-20:43:07] [TRT] [W] Tactic Device request: 50007MB Available: 40354MB. Device memory is insufficient to use tactic.
[11/24/2023-20:43:07] [TRT] [W] UNSUPPORTED_STATESkipping tactic 20 due to insufficient memory on requested size of 50007 detected for tactic 0x000000000000001f.
[11/24/2023-20:43:07] [TRT] [E] 10: Could not find any implementation for node PWN(GPTLMHeadModel/lm_head/ELEMENTWISE_SUM_0).
[11/24/2023-20:43:07] [TRT] [E] 10: [optimizer.cpp::computeCosts::4051] Error Code 10: Internal Error (Could not find any implementation for node PWN(GPTLMHeadModel/lm_head/ELEMENTWISE_SUM_0).)
[11/24/2023-20:43:07] [TRT-LLM] [E] Engine building failed, please check the error log.
[11/24/2023-20:43:07] [TRT-LLM] [I] Config saved to gpt_outputs/config.json.
Traceback (most recent call last):
  File "/tensorrtllm_backend/tensorrt_llm/examples/gpt/build.py", line 669, in <module>
    run_build()
  File "/tensorrtllm_backend/tensorrt_llm/examples/gpt/build.py", line 661, in run_build
    build(0, args)
  File "/tensorrtllm_backend/tensorrt_llm/examples/gpt/build.py", line 629, in build
    assert engine is not None, f'Failed to build engine for rank {cur_rank}'
AssertionError: Failed to build engine for rank 0
```

the command that gave this error is
```
python3 examples/gpt/build.py --model_dir=/my_model --use_gpt_attention_plugin float16 --use_gemm_plugin float16 --enable_context_fmha --alibi True --use_parallel_embedding --embedding_sharding_dim=0 --use_embedding_sharing --world_size 2 --parallel_build --gather_all_token_logits
```

**Comment by jdemouth-nvidia** [comment]
Can you share the command line that leads to the error, please?

**Comment by dongluw** [comment]
@jdemouth-nvidia updated the command, thanks for looking into this

**Comment by dontloo** [comment]
@jdemouth-nvidia think it's because the implementation of context llh takes too much memory, it worked after I set `--max_batch_size=64`

**Comment by ChristinaZ** [comment]
> @jdemouth-nvidia think it's because the implementation of context llh takes too much memory, it worked after I set `--max_batch_size=64`

Agree. I can build the gpt2-medium successfully with both "--use_embedding_sharing" and "--gather_all_token_logits".
@dongluw Can you test smaller batch size?

**Comment by dongluw** [comment]
@ChristinaZ yep, smaller batch size worked, actually dontloo is my other github account 😄  sorry for the confusion

**Comment by byshiue** [comment]
Close this bug because the issue is resolved. Feel free to ask here if you still have question/issue, we will reopen the issue.

**Comment by ML-Mr-J** [comment]
> @jdemouth-nvidia updated the command, thanks for looking into this

Hello, could you please explain how you are using the "--alibi" option for building? I noticed that the original build.py script in the PGT does not contain a "--alibi" parameter.

**Comment by byshiue** [comment]
What's the meaning of "PGT"? If you want to mean "GPT", aliib is not used in standard GPT, it is an extension. If you use GPT, you don't need to care it.

**Comment by ML-Mr-J** [comment]
> What's the meaning of "PGT"? If you want to mean "GPT", aliib is not used in standard GPT, it is an extension. If you use GPT, you don't need to care it.

Yes, it's GPT, and I also need make an extension for jais which is an arabic llm, could you please tell me how to use aliib as an extension.

**Comment by byshiue** [comment]
> > What's the meaning of "PGT"? If you want to mean "GPT", aliib is not used in standard GPT, it is an extension. If you use GPT, you don't need to care it.
> 
> Yes, it's GPT, and I also need make an extension for jais which is an arabic llm, could you please tell me how to use aliib as an extension.

You could refer the bloom model, which also uses alibi.

**Comment by ML-Mr-J** [comment]
> > > What's the meaning of "PGT"? If you want to mean "GPT", aliib is not used in standard GPT, it is an extension. If you use GPT, you don't need to care it.
> > 
> > 
> > Yes, it's GPT, and I also need make an extension for jais which is an arabic llm, could you please tell me how to use aliib as an extension.
> 
> You could refer the bloom model, which also uses alibi.

ok, thanks a lot.
