### ISSUE TITLE
How to statistic the latency of first token and next token?

### ISSUE THREAD

**Issue by Fred-cell** [NVIDIA/TensorRT-LLM#473]
FYI

**Comment by uppalutkarsh** [comment]
Hi @Fred-cell ,

You should leverage cpp benchmark to compute respective latencies. 

Once, you have build cpp benchmarks, please set `--input_output_len "60,1"`. Setting `output_len` as `1` will correspond to first token latency. To compute the average token latency, please modify `--input_output_len "60,1"` accordingly.

You can find more details [here](https://github.com/NVIDIA/TensorRT-LLM/tree/release/0.5.0/benchmarks/cpp) .

Let me know if it helps.

Utkarsh

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Please reopen it if needed.

**Comment by nv-guomingz** [comment]
please feel free to reopen this ticket if needed.
