### ISSUE TITLE
Signal 11 (Segmentation fault) in Attention layer

### ISSUE THREAD

**Issue by HKAB** [NVIDIA/TensorRT-LLM#479]
Hi guys,
I'm trying to implement Whisper based on the enc_dec examples. The encoder works fine, but the decoder is quite hard to debug when using `gpt_attention_plugin`. When running this [test code](https://colab.research.google.com/drive/1rJbk_Vp2Fs8fwY2ZoWjFfK0Ttxl8XTzI?usp=sharing), I always get  `Caught signal 11 (Segmentation fault: invalid permissions for mapped object at address 0x..)`. The backtrace of the error:

`
==== backtrace (tid:  80544) ====
 0 0x0000000000042520 __sigaction()  ???:0
 1 0x00000000000a8e27 tensorrt_llm::plugins::GPTAttentionPlugin::enqueueImpl<__half, tensorrt_llm::kernels::KVLinearBuffer>()  :0
 2 0x00000000000a3b9d tensorrt_llm::plugins::GPTAttentionPlugin::enqueue()  ???:0
 3 0x00000000010aefc9 createInferRuntime_INTERNAL()  ???:0
 4 0x0000000001071e04 getInferLibVersion()  ???:0
 5 0x00000000010739a0 getInferLibVersion()  ???:0
`

The output of Whisper's encoder is `[batch_size, 1500, hidden_size]`, so I fixed the some dims to be 1500. Since you are familiar with the parameters of `enc_dec`, could you guys help me check if there is problem with my sample input? I suspect it might be some problems with how `gpt_attention_plugin` handle my `cross_past_key_value_0` and `past_key_value_0` since `signal 11` indicate some illegal memory access.

And what should be the best way to debug a model? With `gpt_attention_plugin` enabled, if I add `hidden_states.mark_output('hidden_states_after_emb', self._dtype)` to [enc_dec/model.py#L713](https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/tensorrt_llm/models/enc_dec/model.py#L713) and run [run.py as in the `README.md`](https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/examples/enc_dec/README.md) , it logged the tensor to a text file at each step, but the tensor is all zeros except the last step, which is weird since `mark_output` work well in the encoder (all the tensor that are marked as output are exactly right), but not the decoder.

Thanks in advance!

**Comment by symphonylyh** [comment]
Hi @HKAB , from the links you referred, it seems you were on the `release/0.5.0` branch. I would highly recommend switching to the dev `main` branch as we added many fixes to enc-dec as of https://github.com/NVIDIA/TensorRT-LLM/discussions/424.

Also just FYI, we're in progress of sharing Whisper support soon. For debug mode, we're also adding a detailed debug mode for enc-dec. May I ask you to first try rebase your changes to the main branch and see if the segfault still exists? Sorry for the inconvenience but the development has been very active adding new features and improvements. And frequently rebasing onto main will help you better in sync with future release version too

**Comment by symphonylyh** [comment]
Mark as resolved for now since we just released v0.6.1 https://github.com/NVIDIA/TensorRT-LLM/releases/tag/v0.6.1 with related bug fixes.

Please don't hesitate to reopen this if you have encountered any further issue
