### ISSUE TITLE
How to pass multiple prompts to run.py llama

### ISSUE THREAD

**Issue by NarenZen** [NVIDIA/TensorRT-LLM#481]
Say I want to process 5 prompts in parallel. 
How do i do that.

**Comment by byshiue** [comment]
You could prepare the several input ids in file and pass that by `--input_file`.

**Comment by NarenZen** [comment]
but when i gave multiple prompts in csv file. 
It throws error.
It expects in numeric format

**Comment by byshiue** [comment]
Yes. I mentioned that you could put `input_ids` in the csv file. It cannot be `input_text`.

**Comment by pniyongabo** [comment]
When I sent in `input_ids` for 8 prompts, I get empty outputs except for the last prompt. Any guidance on how to address that?

**Comment by pniyongabo** [comment]
> When I sent in `input_ids` for 8 prompts, I get empty outputs except for the last prompt. Any guidance on how to address that?

This seems to occur more on long prompts (more than 150 tokens) than on short prompts.

**Comment by byshiue** [comment]
Please share your input file and your script to run inference.

**Comment by andakai** [comment]
HI, @byshiue , I want to pass multiple prompts with `--input_file`. My script is like 
```
#!/bin/bash
python3 ../run.py --max_output_len=50 \
  --tokenizer_dir /tmp/llama2-13B/ \
  --engine_dir=/app/tensorrt_llm/examples/llama/tmp/llama/13B/trt_engines/int8_kv_cache_int4_AWQ/1-gpu \
  --input_file=./scrambled_sampled_dataset.json
```
The requests are in the file `.json`. I wonder if there is already any support.

**Comment by byshiue** [comment]
For `--input_file`, you could put several sentences in `.txt` directly or put the encoded token ids in `.csv`.

**Comment by andakai** [comment]
> For `--input_file`, you could put several sentences in `.txt` directly or put the encoded token ids in `.csv`.

By doing so, it will regard multi requests as one sentence, like 
```
"Input [Text 0]: "<s> "I am Li Hua",
"I have a pen""
```
If I change the `run.py`:
```
elif input_file.endswith('.txt'):
            with open(input_file, 'r', encoding='utf-8', errors='replace') as txt_file:
                input_texts = txt_file.read().split('\n')
                for input_text in input_texts:
                    if input_text.strip():
                        input_ids = tokenizer.encode(
                            input_text,
                            add_special_tokens=add_special_tokens,
                            truncation=True,
                            max_length=max_input_length)
                        batch_input_ids.append(input_ids)
```
and then the result is as expected.

**Comment by byshiue** [comment]
Thank you for the report. We will fix it in next update.

**Comment by byshiue** [comment]
We have updated the code and the issue should be fixed in ToT.
