### ISSUE TITLE
Run Mistral-7B with release/v0.5.0 tag

### ISSUE THREAD

**Issue by leegohi04517** [NVIDIA/TensorRT-LLM#482]
Now I can run mistral-7B without --max_kv_cache_len=4096 arg on release/v0.5.0.  What's the difference with running on main tag? Does it only with FasterTransformer accelerate not KV cache？ I'm very confused and looking for your kindly help.

**Comment by PerkzZheng** [comment]
without `--max_kv_cache_len` flags, it would not enable sliding_window_attention or rolling buffer kv cache when the actual sequence length exceeds 4096. 

It is not fixed as a model parameter because we may have other models that need rolling buffer kv cache features, but want a flexible max kv cache length depending on different cases.

**Comment by leegohi04517** [comment]
Thanks a lot. By the way, what's the suggested way to accelerate mistral-7B on release/v0.5.0 tag. I can't quantize it into fp8 neither with --max_kv_cache_len flags. Is that correct '--max_kv_cache_len' only works when input tokens exceeds 4096?

**Comment by PerkzZheng** [comment]
> Thanks a lot. By the way, what's the suggested way to accelerate mistral-7B on release/v0.5.0 tag. I can't quantize it into fp8 neither with --max_kv_cache_len flags. Is that correct '--max_kv_cache_len' only works when input tokens exceeds 4096?

do you mean fp8 kv cache + rolling buffer kv cache ? 
and if set `--max_kv_cache_len 4096`, it means that we will limit the kv cache capacity to 4096. when the sequence length is below 4096, it will just work as normal cases. max_kv_cache_len only makes sense if the sequence length exceeds 4096.
it will automatically set back to the max sequence length if max_kv_cache_length >= max_sequence_length when we allocate the kv cache.

**Comment by leegohi04517** [comment]
I attempted 'python quantize.py --model_dir ./Mistral-7B/ \
                   --dtype float16 \
                   --qformat fp8 \
                   --export_path ./quantized_fp8 \
                   --calib_size 512 ' at ./example/llama folder on  release/v0.5.0 tag. It failed with the error message: unknown key 'Mistral'.    Doesn't support fp8 kv cache for mistral yet?

**Comment by PerkzZheng** [comment]
> I attempted 'python quantize.py --model_dir ./Mistral-7B/ --dtype float16 --qformat fp8 --export_path ./quantized_fp8 --calib_size 512 ' at ./example/llama folder on release/v0.5.0 tag. It failed with the error message: unknown key 'Mistral'. Doesn't support fp8 kv cache for mistral yet?

can you try with main branch, and share the detailed error logs ?

**Comment by leegohi04517** [comment]
> > I attempted 'python quantize.py --model_dir ./Mistral-7B/ --dtype float16 --qformat fp8 --export_path ./quantized_fp8 --calib_size 512 ' at ./example/llama folder on release/v0.5.0 tag. It failed with the error message: unknown key 'Mistral'. Doesn't support fp8 kv cache for mistral yet?
> 
> can you try with main branch, and share the detailed error logs ?

ok i will try it.  By the way, does the main branch and release branch build the same docker image? I am not sure whether it required rebuild image when i change branch from release to main.

**Comment by PerkzZheng** [comment]
> > > I attempted 'python quantize.py --model_dir ./Mistral-7B/ --dtype float16 --qformat fp8 --export_path ./quantized_fp8 --calib_size 512 ' at ./example/llama folder on release/v0.5.0 tag. It failed with the error message: unknown key 'Mistral'. Doesn't support fp8 kv cache for mistral yet?
> > 
> > 
> > can you try with main branch, and share the detailed error logs ?
> 
> ok i will try it. By the way, does the main branch and release branch build the same docker image? I am not sure whether it required rebuild image when i change branch from release to main.

I would suggest to rebuild the image as we may have some features/bugs needed by the latest trt or something like that. it makes sure we are on the same page.

**Comment by leegohi04517** [comment]
> > > > I attempted 'python quantize.py --model_dir ./Mistral-7B/ --dtype float16 --qformat fp8 --export_path ./quantized_fp8 --calib_size 512 ' at ./example/llama folder on release/v0.5.0 tag. It failed with the error message: unknown key 'Mistral'. Doesn't support fp8 kv cache for mistral yet?
> > > 
> > > 
> > > can you try with main branch, and share the detailed error logs ?
> > 
> > 
> > ok i will try it. By the way, does the main branch and release branch build the same docker image? I am not sure whether it required rebuild image when i change branch from release to main.
> 
> I would suggest to rebuild the image as we may have some features/bugs needed by the latest trt or something like that. it makes sure we are on the same page.

the latest main branch build image failed with command: ' make -C docker release_build IMAGE_WITH_TAG=xxx'

#0 83.71 12 errors detected in the compilation of "/src/tensorrt_llm/cpp/tensorrt_llm/kernels/cutlass_kernels/int8_gemm/int8_gemm_fp16.cu".
#0 83.75 gmake[3]: *** [tensorrt_llm/kernels/CMakeFiles/kernels_src.dir/build.make:2993: tensorrt_llm/kernels/CMakeFiles/kernels_src.dir/cutlass_kernels/int8_gemm/int8_gemm_fp16.cu.o] Error 1
#0 83.75 gmake[3]: *** Waiting for unfinished jobs....
#0 86.53 [ 77%] Built target layers_src
#0 93.74 [ 77%] Built target common_src
#0 95.76 [ 77%] Built target runtime_src
#0 724.7 gmake[2]: *** [CMakeFiles/Makefile2:784: tensorrt_llm/kernels/CMakeFiles/kernels_src.dir/all] Error 2
#0 724.7 gmake[1]: *** [CMakeFiles/Makefile2:710: tensorrt_llm/CMakeFiles/tensorrt_llm.dir/rule] Error 2
#0 724.7 gmake: *** [Makefile:179: tensorrt_llm] Error 2
#0 724.7 Traceback (most recent call last):
#0 724.7   File "/src/tensorrt_llm/scripts/build_wheel.py", line 287, in <module>
#0 724.7     main(**vars(args))
#0 724.7   File "/src/tensorrt_llm/scripts/build_wheel.py", line 158, in main
#0 724.7     build_run(
#0 724.7   File "/usr/lib/python3.10/subprocess.py", line 526, in run
#0 724.8     raise CalledProcessError(retcode, process.args,
#0 724.8 subprocess.CalledProcessError: Command 'cmake --build . --config Release --parallel 26 --target tensorrt_llm tensorrt_llm_static nvinfer_plugin_tensorrt_llm th_common  ' returned non-zero exit status 2.
------
Dockerfile.multi:56
--------------------
  54 |
  55 |     ARG BUILD_WHEEL_ARGS="--clean --trt_root /usr/local/tensorrt"
  56 | >>> RUN python3 scripts/build_wheel.py ${BUILD_WHEEL_ARGS}
  57 |
  58 |     FROM devel as release
--------------------
ERROR: failed to solve: process "/bin/bash -c python3 scripts/build_wheel.py ${BUILD_WHEEL_ARGS}" did not complete successfully: exit code: 1

**Comment by PerkzZheng** [comment]
try to add `git submodule update` before `python3 scripts/build_wheel.py`.
similar issues can be found in https://github.com/NVIDIA/TensorRT-LLM/issues/438

**Comment by leegohi04517** [comment]
ok. my fault. I forget update submodules when change branch

**Comment by leegohi04517** [comment]
> > I attempted 'python quantize.py --model_dir ./Mistral-7B/ --dtype float16 --qformat fp8 --export_path ./quantized_fp8 --calib_size 512 ' at ./example/llama folder on release/v0.5.0 tag. It failed with the error message: unknown key 'Mistral'. Doesn't support fp8 kv cache for mistral yet?
> 
> can you try with main branch, and share the detailed error logs ?

[NeMo W 2023-11-28 11:29:27 nemo_logging:349] /usr/local/lib/python3.10/dist-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
      warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /code/tensorrt_llm/examples/llama/quantize.py:146 in <module>                                    │
│                                                                                                  │
│   143                                                                                            │
│   144                                                                                            │
│   145 if __name__ == "__main__":                                                                 │
│ ❱ 146 │   main()                                                                                 │
│   147                                                                                            │
│                                                                                                  │
│ /code/tensorrt_llm/examples/llama/quantize.py:134 in main                                        │
│                                                                                                  │
│   131 │   │   np.random.seed(args.seed)                                                          │
│   132 │                                                                                          │
│   133 │   tokenizer = get_tokenizer(args.model_dir, cache_dir=args.cache_dir)                    │
│ ❱ 134 │   model = get_model(args.model_dir, args.dtype, cache_dir=args.cache_dir)                │
│   135 │                                                                                          │
│   136 │   calib_dataloader = get_calib_dataloader(tokenizer=tokenizer,                           │
│   137 │   │   │   │   │   │   │   │   │   │   │   calib_size=args.calib_size,                    │
│                                                                                                  │
│ /code/tensorrt_llm/examples/llama/quantize.py:83 in get_model                                    │
│                                                                                                  │
│    80 def get_model(ckpt_path, dtype="float16", cache_dir=None):                                 │
│    81 │   logger.info(f"Loading model from {ckpt_path}")                                         │
│    82 │   torch_dtype = str_dtype_to_torch(dtype)                                                │
│ ❱  83 │   model = AutoModelForCausalLM.from_pretrained(                                          │
│    84 │   │   ckpt_path,                                                                         │
│    85 │   │   device_map="auto",                                                                 │
│    86 │   │   cache_dir=cache_dir,                                                               │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py:527 in          │
│ from_pretrained                                                                                  │
│                                                                                                  │
│   524 │   │   │   if kwargs.get("quantization_config", None) is not None:                        │
│   525 │   │   │   │   _ = kwargs.pop("quantization_config")                                      │
│   526 │   │   │                                                                                  │
│ ❱ 527 │   │   │   config, kwargs = AutoConfig.from_pretrained(                                   │
│   528 │   │   │   │   pretrained_model_name_or_path,                                             │
│   529 │   │   │   │   return_unused_kwargs=True,                                                 │
│   530 │   │   │   │   trust_remote_code=trust_remote_code,                                       │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py:1039 in   │
│ from_pretrained                                                                                  │
│                                                                                                  │
│   1036 │   │   │   │   config_class.register_for_auto_class()                                    │
│   1037 │   │   │   return config_class.from_pretrained(pretrained_model_name_or_path, **kwargs)  │
│   1038 │   │   elif "model_type" in config_dict:                                                 │
│ ❱ 1039 │   │   │   config_class = CONFIG_MAPPING[config_dict["model_type"]]                      │
│   1040 │   │   │   return config_class.from_dict(config_dict, **unused_kwargs)                   │
│   1041 │   │   else:                                                                             │
│   1042 │   │   │   # Fallback: use pattern matching on the string.                               │
│                                                                                                  │
│ /usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py:734 in    │
│ __getitem__                                                                                      │
│                                                                                                  │
│    731 │   │   if key in self._extra_content:                                                    │
│    732 │   │   │   return self._extra_content[key]                                               │
│    733 │   │   if key not in self._mapping:                                                      │
│ ❱  734 │   │   │   raise KeyError(key)                                                           │
│    735 │   │   value = self._mapping[key]                                                        │
│    736 │   │   module_name = model_type_to_module_name(key)                                      │
│    737 │   │   if module_name not in self._modules:                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
KeyError: 'mistral'

**Comment by PerkzZheng** [comment]
try to upgrade transformers to 4.34.1. 
https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/llama#mistral-v01

**Comment by guialfaro053** [comment]
> try to upgrade transformers to 3.34.1. https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/llama#mistral-v01

I got this error when trying that approach `tensorrt-llm 0.6.0 requires transformers==4.33.1, but you have transformers 4.34.1 which is incompatible.`

Is there any way to fix it?

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Please reopen it if needed.
