### ISSUE TITLE
stop_words Invalid problem and infilling function

### ISSUE THREAD

**Issue by shatealaboxiaowang** [NVIDIA/TensorRT-LLM#485]
Hi，Dear：

When can latest release version be released to completely solve the problem that stop_words does not take effect ?

Another question is, does the current version support infilling ？

Looking forward to your reply！
thank you！

**Comment by byshiue** [comment]
> When can latest release version be released to completely solve the problem that stop_words does not take effect ?

Could you explain what problem do you encounter? It works well on our testing. 

> Another question is, does the current version support infilling ？

Can you explain more about `infilling`?

**Comment by shatealaboxiaowang** [comment]
> > When can latest release version be released to completely solve the problem that stop_words does not take effect ?
> 
> Could you explain what problem do you encounter? It works well on our testing.
> The problem with stop_words is that it only works on the main branch?
> > Another question is, does the current version support infilling ？
> 
> Can you explain more about `infilling`?
infilling: Fill in the code in the middle，such as input="import numpy\n<FILL_ME>\nc=a+b", output="import numpy\na=np.array([0,1]);b=np.array([2,3])\nc=a+b"

thank you!

**Comment by byshiue** [comment]
I feel the infilling is a capability of model but not inference framework.

**Comment by shatealaboxiaowang** [comment]
> I feel the infilling is a capability of model but not inference framework.
You're right, codellama already has this capability, but tensorrt or triton should have some pre-processing and post-processing capability for this type of scene, so that I can input "import numpy\n<FILL_ME>\nc=a+b" and output "import numpy\na=np.array([0,1]);b=np.array([2,3])\nc=a+b". Because this is a very general scenario, like vllm has implemented it

**Comment by byshiue** [comment]
Shouldn't the input is `"import numpy\n<FILL_ME>\nc=a+b"`, and the full output (`input+generate_tokens`) is like
```
import numpy\n<FILL_ME>\nc=a+b import numpy\na=np.array([0,1]);b=np.array([2,3])\nc=a+b
```

Besides, please notify your format to prevent fuse the content you want to refer and your content for reply.

**Comment by shatealaboxiaowang** [comment]
> Shouldn't the input is `"import numpy\n<FILL_ME>\nc=a+b"`, and the full output (`input+generate_tokens`) is like
> 
> ```
> import numpy\n<FILL_ME>\nc=a+b import numpy\na=np.array([0,1]);b=np.array([2,3])\nc=a+b
> ```
> 
> Besides, please notify your format to prevent fuse the content you want to refer and your content for reply.

Thank you for your reply, you can take a look at codellama's concept of infilling, format is： prefix-code  infilling code suffix-code. The model-codellama does realize this function, but it also needs inference framework for pre - and post-processing and output.

**Comment by byshiue** [comment]
Then it does not supported in TensorRT-LLM now. But you could try modifying the pre/post processing because all of them are python codes.

**Comment by shatealaboxiaowang** [comment]
> Then it does not supported in TensorRT-LLM now. But you could try modifying the pre/post processing because all of them are python codes.

I got it, thank you!
Another thing is that I have updated tensorrt-llm to the latest version, stop_words has been solved when stop_words is plain string, but it is invalid when stop_words is ’\n‘, is there a solution?

**Comment by byshiue** [comment]
related to https://github.com/triton-inference-server/tensorrtllm_backend/issues/128
