### ISSUE TITLE
How to compile the cpp version benchmarks?

### ISSUE THREAD

**Issue by leizhao1234** [NVIDIA/TensorRT-LLM#487]
I flow the installation.md[https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/docs/source/installation.md#build-tensorrt-llm-in-one-step](url) to build the docker image, but cpp/build cannot be found anywhere. 

And the installation document in Build TensorRT-LLM and benchmarking source code[https://github.com/NVIDIA/TensorRT-LLM/tree/release/0.5.0/benchmarks/cpp#1-build-tensorrt-llm-and-benchmarking-source-code](url) is 404.

**Comment by byshiue** [comment]
We suggest referring the latest main branch and here are steps and document to build cpp codes https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/installation.md#link-with-the-tensorrt-llm-c-runtime

**Comment by leizhao1234** [comment]
But the default branch is release/0..5.0, it took me a long time to compile it. I suggest that you should fix it, because a lot of people will use the default branch, and they may open a same issue.

**Comment by byshiue** [comment]
Thank you for the suggestion, we will discuss and consider that.

**Comment by byshiue** [comment]
We have changed the default branch to main branch. Close this bug.
