### ISSUE TITLE
How can I running successful  on jetson orin NX?

### ISSUE THREAD

**Issue by huyin92** [NVIDIA/TensorRT-LLM#488]
I use  One Step method to build TensorRT-LLM，don't modify the version of cuda、trt  etc，I can build succeed but running failed，error show my NVIDIA driver is too old，but my jetpack version is 5.1.1，latest version is 5.1.2，I find that jetpack 5.1.1 seems to support cuda11 at most，so I think 5.1.2 is the same.
Then I use NVIDIA official docker image( https://catalog.ngc.nvidia.com/orgs/nvidia/containers/l4t-jetpack) r35.4.1，Although it contains   the cuda cudnn tensorrt etc，But installing other environments is also quite difficult with a large number of errors
So I want to ask, How can I running successful  on jetson orin NX  now? Is there a docker image?
![03f438f57e38f42cb56f41f7d43551f](https://github.com/NVIDIA/TensorRT-LLM/assets/21241531/c6cddeca-1307-421f-8c4a-cad8fdd86946)

**Comment by juney-nvidia** [comment]
We haven't verified TensorRT-LLM on Jetson platform thoroughly before and there isn't docker image provided for this platform yet.

I will pass this message to our prod team to let them be aware of it. 

Thanks
June

**Comment by jjhw** [comment]
JetPack 6.0 Developer Preview is now out, that has CUDA 12 and the latest version of  TensorRT, try that.

**Comment by nv-guomingz** [comment]
please feel free to reopen this ticket if needed.
