### ISSUE TITLE
Mistral 7B support

### ISSUE THREAD

**Issue by casper-hansen** [NVIDIA/TensorRT-LLM#49]
Hi Nvidia, great work with this release. As you may be aware of, Mistral is a new Apache 2.0-licensed model that beats most Llama-2 models. The architecture and names of layers are nearly identical except for the usage of SWA. 

Please add support for their models, it would be greatly appreciated as they are MUCH better than Llama models.

**Comment by jdemouth-nvidia** [comment]
Hi @casper-hansen , thanks for your message. We are working on adding support for Mistral 7B and their attention with shifted window. We hope to publish a first implementation in the `main` branch in a week or two. We will keep you posted.

**Comment by jagan-mathematics** [comment]
Hi @casper-hansen, when we will get update on this. Kindly let us know once it is avialable.

**Comment by jdemouth-nvidia** [comment]
Hi @jagan-mathematics , we plan to release an implementation of Mistral 7B in a week or two (we have an internal MR and a few bugs left to be fixed). We’ll update that issue when it’s available.

**Comment by lebronjamesking** [comment]
Looking forward to hear the support coming out very soon

**Comment by TheodorosGalanos** [comment]
This is awesome! Do you have a rough idea of when this will come?

**Comment by PerkzZheng** [comment]
@lebronjamesking @casper-hansen @jagan-mathematics @TheodorosGalanos try with the latest main branch (for both TRT-LLM and its backend).  Take a look at [here ](https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/llama#mistral-v10)and start with Mistral 7B.

**Comment by ncomly-nvidia** [comment]
Good news! Mistral has been added to main! https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/llama#mistral-v01

Take a look & let us know if you have any feedback!
