### ISSUE TITLE
[TRT] [W] UNSUPPORTED_STATESkipping tactic 4 due to insufficient memory on requested size of 66048 detected for tactic 0x000000000000001f.

### ISSUE THREAD

**Issue by NarenZen** [NVIDIA/TensorRT-LLM#493]
while running build.py

I'm getting this warning

`[11/28/2023-15:47:38] [TRT] [W] UNSUPPORTED_STATESkipping tactic 4 due to insufficient memory on requested size of 66048 detected for tactic 0x000000000000001f.`

Is it safe to skip

**Comment by jdemouth-nvidia** [comment]
Yes, it is a warning. As long as the TensorRT engine is built successfully, it's not a problem. I'm closing that issue but re-open if you have more questions.
