### ISSUE TITLE
is the built model trasferrable

### ISSUE THREAD

**Issue by NarenZen** [NVIDIA/TensorRT-LLM#495]
Say I build the model on an a40 machine .
Can I run the same model on a a10g machine.

Is the models transferrable to different GPU's or should i build different models for different GPU's

**Comment by robosina** [comment]
@NarenZen TensorRT models, at their core, are not movable across different GPUs because the plan for each operation is selected based on the GPU architecture, and you need to build the engine file again for any new gpu.

**Comment by byshiue** [comment]
Please refer this discussion https://github.com/NVIDIA/TensorRT-LLM/issues/222. 

Close this issue because it is duplicated.
