### ISSUE TITLE
TensorRT LLM Docker Issues

### ISSUE THREAD

**Issue by ashish007git** [NVIDIA/TensorRT-LLM#499]
I am facing multiple issues while trying to build the docker container by following the steps in [here](https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/docs/source/installation.md#create-the-container) 

## No internet in the docker container. 

Running the following commands

```
make -C docker build
```
or 
```
make -C docker run
```
gave errors relating to internet connection failures. The docker container did not have an active internet connection. I was able to fix them using the following fix below:

```
@@ -22,7 +23,7 @@ STAGE              ?=
 # Set this to define a custom image name and tag
 IMAGE_WITH_TAG     ?= $(IMAGE_NAME)$(if $(STAGE),/$(STAGE)):$(IMAGE_TAG)
 DOCKER_BUILD_OPTS  ?= --pull
-DOCKER_BUILD_ARGS  ?=
+DOCKER_BUILD_ARGS  ?= --network host
 DOCKER_PROGRESS    ?= auto
 CUDA_ARCHS         ?=
 BUILD_WHEEL_ARGS   ?= $(shell grep 'ARG BUILD_WHEEL_ARGS=' Dockerfile.multi | grep -o '=.*' | tr -d '="')$(if $(CUDA_ARCHS), --cuda_architectures $(CUDA_ARCHS))
@@ -63,7 +64,7 @@ endef
        docker push $(IMAGE_WITH_TAG)$(IMAGE_TAG_SUFFIX)
 
 DOCKER_RUN_OPTS   ?= --rm -it --ipc=host --ulimit memlock=-1 --ulimit stack=67108864
-DOCKER_RUN_ARGS   ?=
+DOCKER_RUN_ARGS   ?= --net host
 GPU_OPTS          ?= --gpus=all
 SOURCE_DIR        ?= $(shell readlink -f ..)
 CODE_DIR          ?= /code/tensorrt_llm

```

I suspected that this could be an error pertaining to my VM instance, or issue with docker installation. However, I was able to install and build other docker images without any problems. 

## Building docker image fails 

Creating the docker image with the previous internet fix gave me the error shown in the image below:

![image](https://github.com/NVIDIA/TensorRT-LLM/assets/14234526/f773fdb1-722d-404c-ad82-500fc2e5e8a8)

The build command fails to build mpi4py. 

Any leads on how to resolve these issues are appreciated!

**Comment by robosina** [comment]
@ashish007git  I believe your problem has been fixed in https://github.com/NVIDIA/TensorRT-LLM/issues/447

you just need to use 

```
pip install git+https://github.com/Shixiaowei02/mpi4py.git@fix-setuptools-version
```
instead of `pip install mpi4py` in `docker/common/install_base.sh`
