### ISSUE TITLE
 x86_64-conda_cos6-linux-gnu-cc: command not found

### ISSUE THREAD

**Issue by JiushengChen** [NVIDIA/TensorRT-LLM#50]
Trying to install TensorRT-LLM on my owner docker, met this problem:

`$ python3 scripts/build_wheel.py --trt_root="${TRT_ROOT}" -i -c && cd ..`
...
      building 'mpi4py.dl' extension
      /opt/conda/envs/llama-trt/bin/x86_64-conda-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /opt/conda/envs/llama-trt/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /opt/conda/envs/llama-trt/include -fPIC -DHAVE_DLFCN_H=1 -DHAVE_DLOPEN=1 -I/opt/conda/envs/llama-trt/include/python3.8 -c src/dynload.c -o build/temp.linux-x86_64-cpython-38/src/dynload.o
      /opt/conda/envs/llama-trt/bin/x86_64-conda-linux-gnu-cc -shared -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-rpath,/opt/conda/envs/llama-trt/lib -L/opt/conda/envs/llama-trt/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-rpath,/opt/conda/envs/llama-trt/lib -L/opt/conda/envs/llama-trt/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/opt/conda/envs/llama-trt/lib -Wl,-rpath-link,/opt/conda/envs/llama-trt/lib -L/opt/conda/envs/llama-trt/lib -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /opt/conda/envs/llama-trt/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /opt/conda/envs/llama-trt/include build/temp.linux-x86_64-cpython-38/src/dynload.o -Lbuild/temp.linux-x86_64-cpython-38 -ldl -o build/lib.linux-x86_64-cpython-38/mpi4py/dl.cpython-38-x86_64-linux-gnu.so
      checking for MPI compile and link ...
      /opt/conda/bin/mpicc -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /opt/conda/envs/llama-trt/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /opt/conda/envs/llama-trt/include -fPIC -I/opt/conda/envs/llama-trt/include/python3.8 -c _configtest.c -o _configtest.o
      /opt/conda/bin/mpicc: line 301: x86_64-conda_cos6-linux-gnu-cc: command not found
      failure.
      removing: _configtest.c _configtest.o
      error: Cannot compile MPI programs. Check your configuration!!!
      [end of output]

`which x86_64-conda_cos6-linux-gnu-cc` output nothting
`which x86_64-conda_cos7-linux-gnu-cc`
/opt/conda/envs/llama-trt/bin/x86_64-conda_cos7-linux-gnu-cc

**Comment by juney-nvidia** [comment]
Can you successfully run through the process by following the building steps described [here](https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/docs/source/installation.md)?

**Comment by monkeyerKong** [comment]
# fix issue 1  not found `x86_64-conda_cos6-linux-gnu-cc `
conda install  gcc_linux-64 
conda install  gxx_linux-64
conda install  gfortran_linux-64

**Comment by nv-guomingz** [comment]
do u still have further issue or question now? If not, we'll close it soon.
