### ISSUE TITLE
Zombie Processes Remaining After Running GPT Example Scripts on Kubernetes

### ISSUE THREAD

**Issue by xiyuecangxin** [NVIDIA/TensorRT-LLM#501]
### Issue Description
I noticed some zombie processes are left behind when running `example/gpt/build.py` or `example/gpt/hf_gpt_convert.py` in a Kubernetes (K8s) environment. However, this issue does not occur when running the same scripts in a Docker environment.

### Processes That Turned Into Zombies
![img_v3_025m_46c4cee9-7503-4bf0-ae95-e195c57f646g](https://github.com/NVIDIA/TensorRT-LLM/assets/58159320/667347e6-ee9d-4598-9eb7-d6ec9fc777cf)
<img width="754" alt="image" src="https://github.com/NVIDIA/TensorRT-LLM/assets/58159320/e3394244-9157-4fa6-975a-7c66961d4c71">

### Environment Information
- Kubernetes version: 
```
{
  "clientVersion": {
    "major": "1",
    "minor": "26",
    "gitVersion": "v1.26.1",
    "gitCommit": "8f94681cd294aa8cfd3407b8191f6c70214973a4",
    "gitTreeState": "clean",
    "buildDate": "2023-01-18T15:58:16Z",
    "goVersion": "go1.19.5",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "kustomizeVersion": "v4.5.7",
  "serverVersion": {
    "major": "1",
    "minor": "26",
    "gitVersion": "v1.26.1",
    "gitCommit": "8f94681cd294aa8cfd3407b8191f6c70214973a4",
    "gitTreeState": "clean",
    "buildDate": "2023-01-18T15:51:25Z",
    "goVersion": "go1.19.5",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}
```
- Docker version: 
```
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:07:58 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:07:58 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.24
  GitCommit:        61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc:
  Version:          1.1.9
  GitCommit:        v1.1.9-0-gccaecfc
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by juney-nvidia** [comment]
@xiyuecangxin 

Hi, we haven't done any validation in the K8S environment.  Sorry for that we don't have much clue on this.

Have you tried to start other commands in the same K8S environment to see whether they will generate the zombie processes? 

June

**Comment by nv-guomingz** [comment]
do u still have further issue or question now? If not, we'll close it soon.
