### ISSUE TITLE
The same input, the original model and the compiled model have different outputs

### ISSUE THREAD

**Issue by wodeqiansuihan** [NVIDIA/TensorRT-LLM#502]
temperature is 0 .1 ,  same input, the original model and the compiled model have different outputs . After several rounds of dialogue, no matter how I ask, the compiled model outputs the same content，But the original model wouldn't .

**Comment by byshiue** [comment]
Can you explain what's the original model and what's the compiled model? 

If the original model means the HF and the the compiled model means the TRT LLM, they are expected to be different when you enable sampling. And if you want to get different results on TRT LLM, please setup different random seed.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Please reopen it if needed.
