### ISSUE TITLE
cannot convert vicuna-13b with smooth quant

### ISSUE THREAD

**Issue by WeiboXu** [NVIDIA/TensorRT-LLM#505]
command：
python3 hf_llama_convert.py -i /workspace/models/vicuna-13b-v1.5 -o /workspace/models/llama/smooth_llama_13B/sq0.8/ -sq 0.8 --tensor-parallelism 1 --storage-type fp16

log:
  File "/workspace/TensorRT-LLM/examples/llama/hf_llama_convert.py", line 362, in <module>
    hf_gpt_converter(args)
  File "/workspace/TensorRT-LLM/examples/llama/hf_llama_convert.py", line 208, in hf_gpt_converter
    smooth_llama_model(model, act_range, args.smoothquant,
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/TensorRT-LLM/examples/llama/hf_llama_convert.py", line 77, in smooth_llama_model
    smoother = smooth_gemm(weight, scales[layer_name_q]["x"],
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/TensorRT-LLM/examples/llama/smoothquant.py", line 65, in smooth_gemm
    assert gemm.shape[1] == act_scales.numel()
AttributeError: 'NoneType' object has no attribute 'numel'

after debug we can see act_range is empty{}:
act_range = capture_activation_range(
            model,
            LlamaTokenizer.from_pretrained(args.in_file, padding_side='left'),
            dataset)

act_range:
defaultdict(<function capture_activation_range.<locals>.<lambda> at 0x7f4abbfe97e0>, {})

**Comment by Tracin** [comment]
@WeiboXu Hi, I think vicuna is identical to llama, can llama-13b work?

**Comment by Tracin** [comment]
@WeiboXu Hi, I can not reproduce with branch `0.6.1` and `llama-13b`, please try to use my settings.

**Comment by WeiboXu** [comment]
I have used the TensorRT-LLM branch 0.6.1, it works for vicuna-13b-v1.5-16k, but not for vicuna-13b-v1.5. In the file smoothquant.py, the function capture_activation_range(): ...
if isinstance(m, nn.Linear) or isinstance(m, Conv1D):
            hooks.append(
                m.register_forward_hook(
                    functools.partial(stat_input_hook, name=name)))
...

**stat_input_hook** will not be called, after that, act_scales will be empty.

**Comment by Tracin** [comment]
@WeiboXu Sorry, I still could not reproduce the error with model vicuna-13b-v1.5.
