### ISSUE TITLE
Cpp benchmark success but python benchmark failed

### ISSUE THREAD

**Issue by leizhao1234** [NVIDIA/TensorRT-LLM#507]
I run the cpp benchmark with 
`./gptSessionBenchmark --model llama --engine_dir /app/tensorrt_llm/examples/llama/tmp/llama/70B/trt_engines/int4_GPTQ/1-gpu/ --batch_size 1 --input_output_len 128,128`.
 and run python benchmark with 
`python benchmark.py -m llama_70b --mode plugin --batch_size 1 --input_output_len 128,128 --engine_dir /app/tensorrt_llm/examples/llama/tmp/llama/70B/trt_engines/int4_GPTQ/1-gpu/`，then got an error:
`File "/code/tensorrt_llm/benchmarks/python/benchmark.py", line 322, in <module>
    main(args)
  File "/code/tensorrt_llm/benchmarks/python/benchmark.py", line 219, in main
    benchmarker = GPTBenchmark(
  File "/code/tensorrt_llm/benchmarks/python/gpt_benchmark.py", line 173, in __init__
    self.decoder = tensorrt_llm.runtime.GenerationSession(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 430, in __init__
    raise RuntimeError(
RuntimeError: Tensor names in engine are not the same as expected, to use this GenerationSession, you need to use GPTLMHeadModel.prepare_inputs to create TRT Network inputs.`

**Comment by Hukongtao** [comment]
Have you solved this problem? I encountered the same error as you

**Comment by nv-guomingz** [comment]
Could u plz try the latest code base to see if the issue still exists or not?
And do u still have further issue or question now? If not, we'll close it soon.
