### ISSUE TITLE
can't build llama2-7b-chat model in Windows

### ISSUE THREAD

**Issue by JimmyTea1026** [NVIDIA/TensorRT-LLM#508]
I followed the installation guide [here](https://github.com/NVIDIA/TensorRT-LLM/tree/release/0.5.0/windows). And  TensorRT and TensorRT-LLM are installed correctly.
<img width="857" alt="image" src="https://github.com/NVIDIA/TensorRT-LLM/assets/59228524/c7a293f7-44e6-4c48-97a7-e11be746018d">

When I try to build [Llama2-7b-chat ](https://huggingface.co/meta-llama/Llama-2-7b-chat-hf), it ends unexpectedly.
<img width="762" alt="image" src="https://github.com/NVIDIA/TensorRT-LLM/assets/59228524/58b858f6-46dd-4b3e-a101-d186709c7ab0">

CPU : i9-14900HX
GPU : RTX4070 8G Laptop 
Driver : 536.68 CUDA:12.2

here are files in Llama2-7b-chat, did I miss something?
<img width="594" alt="image" src="https://github.com/NVIDIA/TensorRT-LLM/assets/59228524/84234328-9c69-4b20-8c4b-f98139a73cab">

I was wondering if the GPU memory is too small, so I try GPTQ model.
First I try to download [TheBloke/Llama-2-7B-Chat-GPTQ](https://huggingface.co/TheBloke/Llama-2-7B-Chat-GPTQ), but still failed.
<img width="766" alt="image" src="https://github.com/NVIDIA/TensorRT-LLM/assets/59228524/18efc59b-89a0-482f-afa6-0b8cbba11ef6">

Then I build a docker container to do weight quantization on [Llama2-7b-chat ](https://huggingface.co/meta-llama/Llama-2-7b-chat-hf), but after 32 layer process, it showed "killed" and ended unexpectedly.

Even if I try to build the docker image with Dockerfile.multi, it still failed. 
Error message:'cicc' died due to signal 9

**Comment by byshiue** [comment]
Could you try on a small model like GPT first to make sure it is not caused by your hardware limitation?

**Comment by JimmyTea1026** [comment]
> Could you try on a small model like GPT first to make sure it is not caused by your hardware limitation?

Thx, I'll try.

**Comment by JimmyTea1026** [comment]
I tried Bloom, gpt2, but still the same. It will end unexpectedly without any error message.
My Ram and GPU usage didn't run out, I have no idea what the bug is.
<img width="851" alt="image" src="https://github.com/NVIDIA/TensorRT-LLM/assets/59228524/147a2095-c1b9-47e0-b40e-e5df40d7a56e">
<img width="704" alt="image" src="https://github.com/NVIDIA/TensorRT-LLM/assets/59228524/d5fbe8af-40ef-428d-8f2c-335f8b012347">

**Comment by byshiue** [comment]
Could you try on latest main branch or 0.6.1 release branch first? It seems that you still use the 0.5.0.

**Comment by JimmyTea1026** [comment]
> Could you try on latest main branch or 0.6.1 release branch first? It seems that you still use the 0.5.0.

I think it's because memory limitation? I try it on the computer with larger RAM and GRAM, this problem doesn't occur.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Please reopen it if needed.
