### ISSUE TITLE
How to set sampling params in gptManagerBenchmark

### ISSUE THREAD

**Issue by sleepwalker2017** [NVIDIA/TensorRT-LLM#510]
For example, I want to set the topk topp params, how to set this?

**Comment by MartinMarciniszyn** [comment]
You would need to add this parameters onto the `InferenceRequest` [here](https://github.com/NVIDIA/TensorRT-LLM/blob/main/benchmarks/cpp/gptManagerBenchmark.cpp#L459). Place the parameters in tensors and call the methods `setRuntimeTopP()` and `setRuntimeTopK()`, respectively.
