### ISSUE TITLE
Why --max_num_tokens  must be associated with enable_context_fmha?

### ISSUE THREAD

**Issue by sleepwalker2017** [NVIDIA/TensorRT-LLM#511]
I'm using V100 which is Volta architecture. On this platform, --enable_context_fmha is not supported.

I want to change the max_num_tokens to generate longer sequences. How can I set this?

```python
   if args.max_num_tokens is not None:
        assert args.enable_context_fmha
```

**Comment by byshiue** [comment]
`max_num_tokens` is only used in fused mha case to determine the workspace size. For unfused case, the workspace size is determined by batch size and context_length directly.

**Comment by sleepwalker2017** [comment]
> `max_num_tokens` is only used in fused mha case to determine the workspace size. For unfused case, the workspace size is determined by batch size and context_length directly.

Hi, what I'm confused is : How to enable longer sequence generation on V100.

How can I disable the following info:

```
[TensorRT-LLM][WARNING] Number of requested output tokens (513) exceeds maximum output length (512). Number of requested output tokens is changed to 512
```

**Comment by byshiue** [comment]
This should be related to the input length you setup when you build engine.
