### ISSUE TITLE
How to know the utility of paged kv cache ?

### ISSUE THREAD

**Issue by sleepwalker2017** [NVIDIA/TensorRT-LLM#512]
I think it's necessary to show the percentage of the paged kv cache usage. It's useful to know how large the batch can be supported.

**Comment by byshiue** [comment]
This should be supported in 0.6.1. Please refer the change log https://github.com/NVIDIA/TensorRT-LLM/discussions/547.

**Comment by ncomly-nvidia** [comment]
Closing for now. Please re-open if you have issues with the implementation!
