### ISSUE TITLE
Package Version Mismatch Between GPTQ Tool and Docker Image

### ISSUE THREAD

**Issue by taozhang9527** [NVIDIA/TensorRT-LLM#515]
Following the [instructions](https://github.com/NVIDIA/TensorRT-LLM/tree/release/0.5.0/examples/llama#gptq) for GPTQ experiments. Running the following command:
`pip install -r requirements.txt`
Give the following errors:
`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cudf 23.6.0 requires protobuf<4.22,>=4.21.6, but you have protobuf 3.20.2 which is incompatible.
tensorrt-llm 0.5.0 requires transformers==4.31.0, but you have transformers 4.36.0.dev0 which is incompatible.
Successfully installed datasets-2.10.1 dill-0.3.6 lit-17.0.6 multiprocess-0.70.14 protobuf-3.20.2 responses-0.18.0 safetensors-0.3.1 texttable-1.7.0 tokenizers-0.15.0 transformers-4.36.0.dev0 triton-2.0.0`

It is asking for protobuf upgrade and transformers downgrade to proceed. This means that we have to use a special version for GPTQ, and reverse back for other experiments with the docker. Do we have common versions of protobuf and transformers to avoid the hassle?

**Comment by Tracin** [comment]
I think this mismatch will not lead to program break, do you met any bugs related to this?
