### ISSUE TITLE
A10 Support

### ISSUE THREAD

**Issue by robosina** [NVIDIA/TensorRT-LLM#516]
I wanted to inquire whether the A10 graphics card is compatible with TensorRT-LLM. It's not listed, and during my tests, it produces unusual results in fp32 mode, while fp16 mode seems nearly correct. If it's not compatible, can this graphics card be added to the list of compatible graphics cards for future releases?

**Comment by jdemouth-nvidia** [comment]
Hi @robosina,

TensorRT-LLM should work on A10. We do not list it because our CI/QA tests do not include A10.

Can you share the command-line to reproduce the issue on A10, please?

Thanks,
Julien

**Comment by shiqingzhangCSU** [comment]
I test some models on A10 include baichuan, Llama, chatglm2. And they work well. 

> I wanted to inquire whether the A10 graphics card is compatible with TensorRT-LLM. It's not listed, and during my tests, it produces unusual results in fp32 mode, while fp16 mode seems nearly correct. If it's not compatible, can this graphics card be added to the list of compatible graphics cards for future releases?

**Comment by robosina** [comment]
@shiqingzhangCSU @jdemouth-nvidia Thanks for the help
