### ISSUE TITLE
How to find first token latency on TensorRT LLM for llama model?

### ISSUE THREAD

**Issue by apbose** [NVIDIA/TensorRT-LLM#517]
Hi, I have a use case where I want to report the first token latency on Jetson ORIN for different set of context length and generation for benchmarking. I am working on the `release/0.5.0`  branch for TRT-LLM with GPTQ, and I wanted to know how to report first token latency. I am using two ways-

- In `runtime/generation.py`   measuring the latency of the step `self.runtime._run(context, stream)`  which I assume would be the GPU compute time
- In `runtime/generation.py`   measuring the latency of `self.handle_per_step`  measuring the latency per step.

Questions-

1. I see the numbers for 2 is greater than 1. Which would be the correct to report?
2.  Apart from the above two steps, the `decoder.decode` has steps like setting up buffer, the KV cache, setting up generation sequence. Should these also be included in the first token latency?
3.  Also on ORIN in TRT-LLM with GPTQ, I see setting up the decoder in `benchmarks/python/gpt_benchmark.py`  in `decoder=tensorrt_llm.runtime.GenerationSession ` with prebuilt engine takes around 20-25 mins which I did not see in TRT-LLM weight only quantization. Is this expected?

**Comment by sleepwalker2017** [comment]
Also interested in this.

**Comment by yangulei** [comment]
You can refer to https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/performance.md#first-token-latency-benchmark-1

**Comment by apbose** [comment]
Thanks for the pointer. I had a doubt. My understanding is that the latency would be the whole end to end generating steps time taken, which would include TRT engine inference + decoding + cache setup. So would not the time taken for TRT engine inference or the cache setup be dependent on the generation length sequence? i.e. it would be different for inlen, outlen 2048x1 vs 2048x2048? So for generation length of 2048, would setting outlen as 1 be the right thing to do?

**Comment by byshiue** [comment]
cache setup is only related to memory allocation, which would be covered in warmup and it does not affect generation. So, the output len will not affect the perf. In short, setting output len as 1 is a correct setting.
