### ISSUE TITLE
Llama-2-70b - Tensor Dimension Mismatch Error for GPTQ Engine Build for 1GPU and 4GPUs

### ISSUE THREAD

**Issue by taozhang9527** [NVIDIA/TensorRT-LLM#518]
Model under test is Llama-2-70b-chat-hf.
Follow the GPTQ instructions [here](https://github.com/NVIDIA/TensorRT-LLM/tree/release/0.5.0/examples/llama#gptq). Was able to generate safetensors file successfully with the following command:
` python GPTQ-for-LLaMa/llama.py ./Llama-2-70b-chat-hf c4 --wbits 4 --true-sequential --groupsize 128 --save_safetensors ./Llama-2-70b-chat-hf_gptq/llama-70b-4bit-gs128.safetensors`

However, build engine failed because of the tensor dimension mismatch.
Command:
 ` python examples/llama/build.py --model_dir ./Llama-2-70b-chat-hf --quant_ckpt_path ./Llama-2-70b-chat-hf_gptq/llama-70b-4bit-gs128.safetensors  --dtype float16 --remove_input_padding --use_gpt_attention_plugin float16              --enable_context_fmha  --use_gemm_plugin float16  --use_weight_only  --weight_only_precision int4_gptq --per_group                 --enable_context_fmha  --output_dir ./examples/llama/out/70b/gptq_1gpu`

 ` python examples/llama/build.py --model_dir ./Llama-2-70b-chat-hf --quant_ckpt_path ./Llama-2-70b-chat-hf_gptq/llama-70b-4bit-gs128.safetensors  --dtype float16 --remove_input_padding --use_gpt_attention_plugin float16              --enable_context_fmha  --use_gemm_plugin float16  --use_weight_only  --weight_only_precision int4_gptq --per_group                 --enable_context_fmha   --world_size 4  --tp_size 4  --output_dir ./examples/llama/out/70b/gptq_1gpu`
Error message:
`[11/30/2023-22:01:59] [TRT-LLM] [I] Serially build TensorRT engines.
[11/30/2023-22:01:59] [TRT] [I] [MemUsageChange] Init CUDA: CPU +13, GPU +0, now: CPU 119, GPU 436 (MiB)
[11/30/2023-22:02:01] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +1809, GPU +316, now: CPU 2063, GPU 752 (MiB)
[11/30/2023-22:02:01] [TRT-LLM] [W] Invalid timing cache, using freshly created one
[11/30/2023-22:03:53] [TRT-LLM] [I] Loading weights from groupwise GPTQ LLaMA safetensors...
Traceback (most recent call last):
  File "/code/tensorrt_llm/examples/llama/build.py", line 718, in <module>
    build(0, args)
  File "/code/tensorrt_llm/examples/llama/build.py", line 689, in build
    engine = build_rank_engine(builder, builder_config, engine_name,
  File "/code/tensorrt_llm/examples/llama/build.py", line 543, in build_rank_engine
    load_func(tensorrt_llm_llama=tensorrt_llm_llama,
  File "/code/tensorrt_llm/examples/llama/weight.py", line 923, in load_from_gptq_llama
    qkv_part = torch.cat([q_part, k_part, v_part], dim=0)
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 8192 but got size 1024 for tensor number 1 in the list.`

**Comment by tanklandry** [comment]
same problem，any solution？

**Comment by taozhang9527** [comment]
UPDATE: with the latest code (0.6.1), I was able to successfully build GPTQ engine for different GPU numbers.

**Comment by mahaddad** [comment]
Curious how the latency and throughput is for a GPTQ model if you have any figures handy?

**Comment by taozhang9527** [comment]
I have not gotten the results for 70b yet, but for 7b, it is 1.5~3x boost (vs fp16) for throughput depending on batch size. Don't have latency data for now.

**Comment by Tracin** [comment]
@taozhang9527 Hi, since it works so I will close this issue. If there is any further problems, you can update here (and I will reopen it) or open an new issue.
