### ISSUE TITLE
Unable to build enc-dec engine w/o gpt_attention_plugin

### ISSUE THREAD

**Issue by yuting-wang-1000** [NVIDIA/TensorRT-LLM#519]
My enc-dec model is not using `relative attention bias`, so I m trying to build engine with plain TRT mode. 

However, when building the engine w/o gpt_attention_plugin, I got the following error:

```
Traceback (most recent call last):
  File "/code/tensorrt_llm/examples/enc_dec/build.py", line 539, in <module>
    run_build(component='decoder')
  File "/code/tensorrt_llm/examples/enc_dec/build.py", line 530, in run_build
    build(0, args)
  File "/code/tensorrt_llm/examples/enc_dec/build.py", line 488, in build
    engine = build_rank_engine(builder, builder_config, engine_name,
  File "/code/tensorrt_llm/examples/enc_dec/build.py", line 421, in build_rank_engine
    inputs = tllm_model.prepare_inputs(
  File "/code/tensorrt_llm/tensorrt_llm/models/enc_dec/model.py", line 1291, in prepare_inputs
    host_max_kv_cache_lengths=host_max_kv_cache_lengths,
UnboundLocalError: local variable 'host_max_kv_cache_lengths' referenced before assignment

```
host_max_kv_cache_lengths in initialized only when use_gpt_attention_plugin is set https://github.com/NVIDIA/TensorRT-LLM/blob/711a28d9bf80a0e8a8be1e597bf809b55db981c8/tensorrt_llm/models/enc_dec/model.py#L1191C13-L1191C38

**Comment by YT-WWW** [comment]
The previous issue can be  fixed by setting `host_max_kv_cache_lengths = None`. 

After fixing it, there is another 'cross_past_key_value_0' not founding issue. 
```
  File "/code/tensorrt_llm/tensorrt_llm/runtime/generation.py", line 1734, in handle_per_step
    self.runtime._set_shape(next_context, next_step_shape)
  File "/code/tensorrt_llm/tensorrt_llm/runtime/generation.py", line 203, in _set_shape
    ok = context.set_input_shape(name, shape_dict[name])
KeyError: 'cross_past_key_value_0'
```
I currently by-pass it by initializing cross_cache_shape for not use_gpt_attention_plugin path too. https://github.com/NVIDIA/TensorRT-LLM/blob/711a28d9bf80a0e8a8be1e597bf809b55db981c8/tensorrt_llm/runtime/generation.py#L1365C22-L1365C22

**Comment by symphonylyh** [comment]
@yuting-wang-1000 @YT-WWW that's correct, for the current development we mostly focused on the plugin approach rather than the plain mode, as attention performance is better with plugin. Even for models without `relative_attention_bias`, using plugin is faster than plain mode. May I know why you prefer the plain mode?

**Comment by YT-WWW** [comment]
@symphonylyh I m getting garbage output while using both bert and gpt plugin. Trying to disable all plugins to debug. 
For encoder part, when use_bert_attention_plugin, attention output is totally off. It only works w/o bert plugin.

**Comment by symphonylyh** [comment]
> I m getting garbage output while using both bert and gpt plugin

@YT-WWW were you using the dev `main` branch when you saw this? FYI, there are several bug fixes and perf fixes for enc-dec on 11/19 dev [release](https://github.com/NVIDIA/TensorRT-LLM/discussions/424) and one small bug fix in today's 12/1 dev [release](https://github.com/NVIDIA/TensorRT-LLM/discussions/527). With these, there should be no known issue running the plugin path (except batched ragged input + beam search) on T5 and Flan-T5.

Can you provide the information on the model you're running? (1) did you verify the same input on provided T5/Flan-T5 example first, and were they correct against HF? (2) what is your model architecture, a custom one or very similar to BART? or what makes your model different from T5 family, like does it use position_ids/token_type_ids? I didn't see you or @yuting-wang-1000 describing a clear failing pattern of the plugin path, I think we need some reproducer to triage the problem. But if it's similar to BART, internal verification has completed and we'll be release that soon. Do you think BART support will help your model too?

**Comment by YT-WWW** [comment]
T5 example works fine for me.  Code wise, I seen this issue on Nov 27th dev release. Will try today's release too. 

Mode side, I m using transformer.wmt14.en-fr model from https://pytorch.org/hub/pytorch_fairseq_translation/. Other than scale, it has the following difference w/ current T5 example, 
```
has_position_embedding = True
has_embedding_scale = True
has_attention_qkvo_bias = True
has_mlp_bias = True
has_model_final_layernorm = False
layernorm_position = post_layernorm
layernorm_type = LayerNorm
```
It uses `position_ids` but not `token_type_ids`.

**Comment by symphonylyh** [comment]
@yuting-wang-1000 @YT-WWW we have internally aligned and recognized this request from our project collaboration. Let's investigate this offline to avoid disclosing your model details. Closed for now.
