### ISSUE TITLE
Difference performance when setting max_batch_size

### ISSUE THREAD

**Issue by sleepwalker2017** [NVIDIA/TensorRT-LLM#526]
I found that I can use max_batch_size to specify the maximum batch size during build phase, and use max_sequence_num to specify the maximum number of concurrency during inference. Is this understanding correct?

When I did this, I noticed a difference in performance. Using batch 16 for inference, when using different max_batch_size when building model, the performance is also different. 

Here is the token throughput for different engines on different max_num_sequences.

![image](https://github.com/NVIDIA/TensorRT-LLM/assets/26128514/b604416a-a16a-43ce-a6b5-c99e6f335fe2)

How should I find the parameters with the best performance? I mean max_batch_size and max_sequence_num.

Also, the performance get worse when the batch is larger than 16.

**Comment by byshiue** [comment]
We will choose a specific batch size as opt setting by giving batch size. TensorRT will select best kernel by this specific batch size.

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Please reopen it if needed.
