### ISSUE TITLE
Issue in python binding for InferenceRequest for GptMananger

### ISSUE THREAD

**Issue by bfontain** [NVIDIA/TensorRT-LLM#528]
Hi,

Currently streaming with the python bindings for GptManager doesn't work as there is a bug in the python binding for InferenceRequest: [toTrtLlm()](https://github.com/NVIDIA/TensorRT-LLM/blob/71f60f6df09b29ab33861f98ac8d97cbe5417e45/cpp/tensorrt_llm/pybind/batch_manager/inferenceRequest.cpp#L41) is missing copying the streaming property from the binding object to the native InferenceRequest object.

**Comment by MartinMarciniszyn** [comment]
Thank you for reporting this. It will be fixed in the next update, probably by the end of this week.

**Comment by juney-nvidia** [comment]
Close it since it has already been fixed in the main branch. In case there are still things missing, pls open a new issue to track it.

June
