### ISSUE TITLE
Is GatedMLP the same as using swiglu as the ACT2FN of a normal MLP? 

### ISSUE THREAD

**Issue by chenho74** [NVIDIA/TensorRT-LLM#529]
If so, why are there two equivalent implementations instead of merging to one? It seems a bit confusing if they are identical.

**Comment by byshiue** [comment]
ACT2FN is only the activation, while GatedMLP is MLP layer. They are different level.

**Comment by symphonylyh** [comment]
@chenho74 , the mechanism is also different. For normal MLP you usually don't use swiglu. When you use swiglu, MLP will automatically be GatedMLP and the activation func becomes silu.

Normal MLP only have one projection layer. If you apply swiglu in normal MLP, you're doing gated activation on the output after the FC projection. Whereas in GatedMLP, you have FC and Gate projection layers, you're doing projection on the same hidden_states and then apply element-wise gate operation between them
