### ISSUE TITLE
build docker failed

### ISSUE THREAD

**Issue by Lzhang-hub** [NVIDIA/TensorRT-LLM#530]
I build docker with command:

```
# TensorRT-LLM uses git-lfs, which needs to be installed in advance.
apt-get update && apt-get -y install git git-lfs

git clone https://github.com/NVIDIA/TensorRT-LLM.git
cd TensorRT-LLM
git submodule update --init --recursive
git lfs install
git lfs pull

```

get the error:
```
failed to solve with frontend dockerfile.v0: failed to create LLB definition: Dockerfile parse error line 23: ARG requires exactly one argument
```
In the `Dockerfile.multi`, the trt version、cudnn version and so on is pass with `ARG TRT_VER CUDA_VER CUDNN_VER NCCL_VER CUBLAS_VER`

Where can I get this pkg version?

**Comment by hailuoS** [comment]
I meet the same problem, how did you solve it?

**Comment by Lzhang-hub** [comment]
I comment the line 25 in dockerfile.

https://github.com/NVIDIA/TensorRT-LLM/blob/6cc5e177ff2fb60b1aab3b03fa0534b5181cf0f1/docker/Dockerfile.multi#L25C5-L25C12
