### ISSUE TITLE
Try using an embedding as input

### ISSUE THREAD

**Issue by hill2hill** [NVIDIA/TensorRT-LLM#534]
Thanks for your excellent TensorRT-LLM!
I'm trying to deploy the LLaVa model with tensorrt_llm, but currently found that only input_ids are supported in run.py. In the inference script of LLaVa model, it looks like to hack the input for language model, which just input an embedding tensor into the LM.
Can you give me some idea to accomplish this?

**Comment by yuanjiechen** [comment]
I have try that by update runtime/generation.py.
To avoid modify the cpp code, I move the embedding layer after the decoder op.
Some buffer shape needs to be updated.
You can referance my code, but sorry for it's ugly and write besed on old version of trt-llm.
https://github.com/yuanjiechen/trt_final/blob/master/tensorrt_llm/runtime/generation.py

**Comment by hill2hill** [comment]
> I have try that by update runtime/generation.py. To avoid modify the cpp code, I move the embedding layer after the decoder op. Some buffer shape needs to be updated. You can referance my code, but sorry for it's ugly and write besed on old version of trt-llm. https://github.com/yuanjiechen/trt_final/blob/master/tensorrt_llm/runtime/generation.py

Thank you so much!

**Comment by Iven2132** [comment]
Hey @hill2hill Did you deploy your LLaVa model with tensorrt_llm? I need some help, Can you please help me out :)
