### ISSUE TITLE
No such file or directory: '/code/tensorrt_llm/cpp/build/tensorrt_llm/thop/libth_common.so'

### ISSUE THREAD

**Issue by zhanglv0209** [NVIDIA/TensorRT-LLM#535]
tag:[v0.6.0](https://github.com/NVIDIA/TensorRT-LLM/releases/tag/v0.6.0)

I exec cmd:
# 1
docker build --pull  \
             --target devel \
             --file docker/Dockerfile.multi \
             --tag tensorrt_llm/devel:latest \
             .
# 2
docker run --rm -it \
           --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 --gpus=all \
           --volume ${PWD}:/code/tensorrt_llm \
           --workdir /code/tensorrt_llm \
           tensorrt_llm/devel:latest

# 3 , in docker ,exec
python3 ./scripts/build_wheel.py --clean  --trt_root /usr/local/tensorrt

# error

-- CUDAToolkit_VERSION 12.2 is greater or equal than 11.0, enable -DENABLE_BF16 flag
-- CUDAToolkit_VERSION 12.2 is greater or equal than 11.8, enable -DENABLE_FP8 flag
-- Found MPI_CXX: /opt/hpcx/ompi/lib/libmpi.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- COMMON_HEADER_DIRS: /code/tensorrt_llm/cpp;/usr/local/cuda/include
-- TORCH_CUDA_ARCH_LIST: 7.0;8.0;8.6;8.9;9.0
CMake Warning at CMakeLists.txt:248 (message):
  Ignoring environment variable TORCH_CUDA_ARCH_LIST=5.2 6.0 6.1 7.0 7.5 8.0
  8.6 9.0+PTX

-- Found Python3: /usr/bin/python3.10 (found version "3.10.12") found components: Interpreter Development Development.Module Development.Embed 
-- Found Python executable at /usr/bin/python3.10
-- Found Python libraries at /usr/lib/x86_64-linux-gnu
-- Found CUDA: /usr/local/cuda (found version "12.2") 
-- Found CUDAToolkit: /usr/local/cuda/include (found version "12.2.128") 
-- Caffe2: CUDA detected: 12.2
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 12.2
-- /usr/local/cuda/lib64/libnvrtc.so shorthash is eaa826f0
-- USE_CUDNN is set to 0. Compiling without cuDNN support
-- Added CUDA NVCC flags for: -gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_89,code=sm_89;-gencode;arch=compute_90,code=sm_90
CMake Warning at /usr/local/lib/python3.10/dist-packages/torch/share/cmake/Torch/TorchConfig.cmake:22 (message):
  static library kineto_LIBRARY-NOTFOUND not found.
Call Stack (most recent call first):
  /usr/local/lib/python3.10/dist-packages/torch/share/cmake/Torch/TorchConfig.cmake:127 (append_torchlib_if_found)
  CMakeLists.txt:281 (find_package)

-- Found Torch: /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch.so  
-- TORCH_CXX_FLAGS: -D_GLIBCXX_USE_CXX11_ABI=1
-- Building for TensorRT version: 9.1.0, library version: 9
-- Using MPI_CXX_INCLUDE_DIRS: /opt/hpcx/ompi/include;/opt/hpcx/ompi/include/openmpi;/opt/hpcx/ompi/include/openmpi/opal/mca/hwloc/hwloc201/hwloc/include;/opt/hpcx/ompi/include/openmpi/opal/mca/event/libevent2022/libevent;/opt/hpcx/ompi/include/openmpi/opal/mca/event/libevent2022/libevent/include
-- Using MPI_CXX_LIBRARIES: /opt/hpcx/ompi/lib/libmpi.so
-- CMAKE_SYSTEM_PROCESSOR: x86_64
-- USE_CXX11_ABI: True
-- The C compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Python: /usr/bin/python3.10 (found version "3.10.12") found components: Interpreter 
-- ========================= Importing and creating target nvonnxparser ==========================
-- Looking for library nvonnxparser
-- Library that was found /usr/local/tensorrt/targets/x86_64-linux-gnu/lib/libnvonnxparser.so
-- ==========================================================================================
CMake Error at /code/tensorrt_llm/benchmarks/cpp/CMakeLists.txt:23 (add_subdirectory):
  The source directory

    /code/tensorrt_llm/3rdparty/cxxopts

  does not contain a CMakeLists.txt file.

-- Configuring incomplete, errors occurred!
See also "/code/tensorrt_llm/cpp/build/CMakeFiles/CMakeOutput.log".
gmake: Makefile: No such file or directory
gmake: *** No rule to make target 'Makefile'.  Stop.
Traceback (most recent call last):
  File "/code/tensorrt_llm/./scripts/build_wheel.py", line 248, in <module>
    main(**vars(args))
  File "/code/tensorrt_llm/./scripts/build_wheel.py", line 172, in main
    copy(build_dir / "tensorrt_llm/thop/libth_common.so",
  File "/usr/lib/python3.10/shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/code/tensorrt_llm/cpp/build/tensorrt_llm/thop/libth_common.so'

# how to process?

**Comment by Shixiaowei02** [comment]
Please use the command `make -C docker release_build` instead, thanks!

**Comment by zhanglv0209** [comment]
> Please use the command `make -C docker release_build` instead, thanks!

# error

-- Found Torch: /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch.so  
-- TORCH_CXX_FLAGS: -D_GLIBCXX_USE_CXX11_ABI=1
-- Building for TensorRT version: 9.2.0, library version: 9
-- Using MPI_CXX_INCLUDE_DIRS: /opt/hpcx/ompi/include;/opt/hpcx/ompi/include/openmpi;/opt/hpcx/ompi/include/openmpi/opal/mca/hwloc/hwloc201/hwloc/include;/opt/hpcx/ompi/include/openmpi/opal/mca/event/libevent2022/libevent;/opt/hpcx/ompi/include/openmpi/opal/mca/event/libevent2022/libevent/include
-- Using MPI_CXX_LIBRARIES: /opt/hpcx/ompi/lib/libmpi.so
-- CMAKE_SYSTEM_PROCESSOR: x86_64
-- Operating System: ubuntu, 22.04
-- The C compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Python: /usr/bin/python3.10 (found version "3.10.12") found components: Interpreter 
-- ========================= Importing and creating target nvonnxparser ==========================
-- Looking for library nvonnxparser
-- Library that was found /usr/local/tensorrt/targets/x86_64-linux-gnu/lib/libnvonnxparser.so
-- ==========================================================================================
**CMake Error at /code/tensorrt_llm/benchmarks/cpp/CMakeLists.txt:23 (add_subdirectory):
  The source directory

    /code/tensorrt_llm/3rdparty/cxxopts

  does not contain a CMakeLists.txt file.**


-- Configuring incomplete, errors occurred!
See also "/code/tensorrt_llm/cpp/build/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "/code/tensorrt_llm/./scripts/build_wheel.py", line 278, in <module>
    main(**vars(args))
  File "/code/tensorrt_llm/./scripts/build_wheel.py", line 154, in main
    build_run(
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cmake -DCMAKE_BUILD_TYPE="Release" -DBUILD_PYT="ON" -DBUILD_PYBIND="OFF"  -DTRT_LIB_DIR=/usr/local/tensorrt/targets/x86_64-linux-gnu/lib -DTRT_INCLUDE_DIR=/usr/local/tensorrt/include -S "/code/tensorrt_llm/cpp"' returned non-zero exit status 1.

**Comment by Shixiaowei02** [comment]
Please follow the instructions described in [docs/source/installation.md](https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/installation.md) , thanks!

**Comment by zhanglv0209** [comment]
> Please follow the instructions described in [docs/source/installation.md](https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/installation.md) , thanks!

Before the release of 0.6.1, there were indeed issues with version 0.6. Packaging and compilation were both problematic. However, today's 0.6.1 version passed smoothly.  thanks

**Comment by Shixiaowei02** [comment]
> > Please follow the instructions described in [docs/source/installation.md](https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/installation.md) , thanks!
> 
> Before the release of 0.6.1, there were indeed issues with version 0.6. Packaging and compilation were both problematic. However, today's 0.6.1 version passed smoothly. thanks

Thanks for your support to TensorRT-LLM!
