### ISSUE TITLE
Question about model performance

### ISSUE THREAD

**Issue by RussellRao** [NVIDIA/TensorRT-LLM#536]
Hi @juney-nvidia ，I have a question here https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/docs/source/performance.md#:~:text=2%2C980-,LLaMA%207B,-64，the model ”LLaMA“ in this page means Llama2 or just Lalma1? Becausu in this page https://github.com/NVIDIA/TensorRT-LLM/blob/a21e2f85178111fed9812bb88c2cc7411b25f0ba/docs/source/blogs/H200launch.md, the title says llama2-13B, but the content is about llama-13B.

Looking forward to your reply, thanks!

**Comment by juney-nvidia** [comment]
@RussellRao 

Hi , thanks for bringing this question.
From model inference perspective, my understanding is that the LLaMA-13B in V1 and V2 share the exact same model architecture:

- hidden dimension: 5120 
- hidden activation: silu
- num of layers: 40
- num of attention heads: 40 (LLaMA2-70B does uses GQA which is different from 13B)

So sometimes for inference scenarios, they are used interchangeably.

Hope this can answer your question.

Thanks
June

**Comment by russ-spec** [comment]
Hi @juney-nvidia ，
Thanks for your reply, I understood.
