### ISSUE TITLE
chatglm model configuration file name can not be recognized by triton backend

### ISSUE THREAD

**Issue by forrestjgq** [NVIDIA/TensorRT-LLM#537]
Hi:

Usually we expect engine takes a `config.json` file, but `examples/chatglm` makes an exception, using file name like `chatglm3xxx-config.json`. It's ok for tensorrt-llm to `run.py`, but can not be deployed in triton with tensorrt-llm backend(will report an error says [ or { is expected but not found, actually it is the missing config.json file)

If there is no special consideration, would you please follow the common rules and just name  it `config.json`? 

ps:
I could change the filename myself, but it will be ugly in our automatic deployment.

**Comment by wili-65535** [comment]
Thank you for your suggestion! We have fixed this ugly behaviour in the new main branch, and now all configuration files are named as "config.json"
https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/chatglm/build.py#L658

**Comment by byshiue** [comment]
Close this bug because it is inactivated. Please reopen it if needed.
