### ISSUE TITLE
Is sliding window attention available?

### ISSUE THREAD

**Issue by FrankLeeeee** [NVIDIA/TensorRT-LLM#543]
According to this [documentation](https://nvidia.github.io/TensorRT-LLM/gpt_attention.html#sliding-window-attention-cyclic-rolling-buffer-kv-cache), there is support for sliding window attention in TRT-LLM. However, it seems to be disabled based on the [code search](https://github.com/search?q=repo%3ANVIDIA%2FTensorRT-LLM+sliding&type=code).

**Comment by PerkzZheng** [comment]
you have to set `max_kv_cache_length` to `sliding_window_size`, and sliding window attention will be automatically enabled when the context length exceeds the `max_kv_cache_length` or we say `sliding_window_size`.

**Comment by FrankLeeeee** [comment]
Got it, thank you for your prompt response! :)
