### ISSUE TITLE
Memory utilization

### ISSUE THREAD

**Issue by sitabulaixizawaluduo** [NVIDIA/TensorRT-LLM#548]
model: Llama-2-13b-hf
GPU: A100 40g
cuda version: 12.2
when I build  the engine, I use "cuda_engine.device_memory_size" found the memory of activation is about 208M. The engine memory utilization is 24825M. kv cache takes up about 3200M. But when I check the total memory usage with the command "nvidia-smi", I find that the memory usage is 28791M. What takes up the rest of the 500M of cuda memory? How do I calculate them?

**Comment by byshiue** [comment]
Have you checked the memory pool of pytorch? 
Also, pytorch may require some memory to put the workspace and handles.

**Comment by sitabulaixizawaluduo** [comment]
> Have you checked the memory pool of pytorch? Also, pytorch may require some memory to put the workspace and handles.

I used c++ runtime, and I found the rest of cuda memory is related to tensor_parallel

**Comment by byshiue** [comment]
Have you got the answer? Or do you still investigate the reason?

**Comment by sitabulaixizawaluduo** [comment]
> Have you got the answer? Or do you still investigate the reason?

I have no idea to find what occupy the memory? I can not see all code which is related to allocate buffer.
