### ISSUE TITLE
Available precision options for GPTj (bfloat16)

### ISSUE THREAD

**Issue by mosalov** [NVIDIA/TensorRT-LLM#553]
I have noticed that the build.py script for GPTj allows using only two precision options:
`choices=['float16', 'float32']`
as mentioned at [source](https://github.com/NVIDIA/TensorRT-LLM/blob/a21e2f85178111fed9812bb88c2cc7411b25f0ba/examples/gptj/build.py#L69C25-L69C55).

Whereas for Llama, for example, it is `choices=['float32', 'bfloat16', 'float16']` at [source](https://github.com/NVIDIA/TensorRT-LLM/blob/a21e2f85178111fed9812bb88c2cc7411b25f0ba/examples/llama/build.py#L138C25-L138C67).

At the same time I do not see any specific precision limitations in the GPTj model here: [source](tensorrt_llm/models/gptj/model.py).

So, can you please clarify, if it is anyhow possible to use bfloat16 for a GPTj TensorRT-LLM engine?

**Comment by byshiue** [comment]
GPT-J only supports FP16, FP32 now. It requires few modification to support BF16.

**Comment by mosalov** [comment]
Is it planned in upcoming minor or major revisions?

**Comment by byshiue** [comment]
It is not in our raodmap now. You could create a issue to ask it if it is necessary in your case.
