### ISSUE TITLE
Question about a Mojo Integration

### ISSUE THREAD

**Issue by aramfaghfouri** [NVIDIA/TensorRT-LLM#556]
Hi,

Are there any plans for integration and working with Mojo in the future?

Thanks!

**Comment by ncomly-nvidia** [comment]
Hi @aramfaghfouri can you help us understand your goals a little more? Are you already using Mojo & want better performance? Do you need HW agonistic support? Different workflow out of TensorRT-LLM? etc.

Currently we aren't working on a Mojo integration, but are always interesting in collaborating with other open source projects!
