### ISSUE TITLE
compile error on windows, file not found: x86_64-windows-msvc/tensorrt_llm_batch_manager_static.lib

### ISSUE THREAD

**Issue by HuChundong** [NVIDIA/TensorRT-LLM#557]
CMake Error at tensorrt_llm/CMakeLists.txt:103 (file):
  file SIZE requested of path that is not readable:

    D:/AI/TensorRT-LLM/cpp/tensorrt_llm/batch_manager/x86_64-windows-msvc/tensorrt_llm_batch_manager_static.lib

**Comment by Shixiaowei02** [comment]
Hello! I think that TensorRT-LLM 0.6.1 for windows is coming soon. Please stay tuned. Thanks!

**Comment by juney-nvidia** [comment]
It is already fixed in the "rel" branch, pls have a try @HuChundong 

June
