### ISSUE TITLE
pip install on windows does not install latest version (0.6.1)

### ISSUE THREAD

**Issue by ToddThomson** [NVIDIA/TensorRT-LLM#558]
I've updated all the required components for Windows 11 (CuDNN and TensorRT since the 0.5 release of TRT-LLM).

Running the pip install command does not update tensorrt-llm. It still is at 0.5.

Thanks in advance for your help! An update on when 9.2.0 GA of TensorRT is planned would be nice too.

**Comment by Shixiaowei02** [comment]
Hello! I think that TensorRT-LLM 0.6.1 for windows is coming soon. Please stay tuned. Thanks!

**Comment by ToddThomson** [comment]
Thanks. I see that the 0.6.1 tensorrt-llm python package has now been added. 

This worked for me:

PS C:\Users\ToddT> pip install tensorrt_llm~=0.6.1 --extra-index-url https://pypi.nvidia.com --extra-index-url https://download.pytorch.org/whl/cu121
