### ISSUE TITLE
How to distribute inference using multi-nodes via MPI?

### ISSUE THREAD

**Issue by delsiiin** [NVIDIA/TensorRT-LLM#563]
Hi! How do I need to set up the MPI commands and cluster environment configuration for distributed inference use among multiple nodes?

For example, I want to implement pipeline and/or tensor parallelism on two machines with only one gpu each.

Thanks!

**Comment by byshiue** [comment]
It should be same to single node.

**Comment by Jeffwan** [comment]
@byshiue for the multi node inference. could you explains whether TP or PP used? Is there a way to use TP and PP together?

**Comment by byshiue** [comment]
It depends on your hardwares, network bandwidth, model size and problem size. So, I cannot give a simple answer. 

The high level ideas are: 
1. TP requires more communication. So, it requires higher network bandwidht. 
2. PP requires larger batch size to separate into micro batches. 

Some extreme case:
1. If you use nvlink and the batch size is 1, TP should be better than PP.
2. If you use pcie and the batch size is 1024, input length is 512, output length is 10, PP should be better than PP.

**Comment by Jeffwan** [comment]
@byshiue Thanks for the reply. I do have two follow up questions. 

1. Let's say if I have a scenarios requires TP=2, PP=4, the model needs to be split into 8 GPUs. I only have nodes with 4 * A100-40G GPUs. In that case, I see TensorRT-LLM uses MPI for communication. I am new to TensorRT, just curious whether the GPU on the same node (TP part) will communicate with nvLink. and GPUs cross node will fall back to MPI (PP part) cpu communication automatically? 


2. Why not use `torch.distributed` package to manage the distributed inference? I kind of feel the orchestration is much easier in that case comparing to use MPI directly? `mpi` can be the `torch.distributed` backend as well.

**Comment by byshiue** [comment]
1. It depends on your hardware. Across nodes, the data can go through infiniband, Roce or pcie. But they called by nccl directly, we don't go through mpi. 
2. We don't want the dependency of torch.
