### ISSUE TITLE
Incorrect results using TensorRT-LLM to infer llama-7b-hf

### ISSUE THREAD

**Issue by yanz0920** [NVIDIA/TensorRT-LLM#564]
I followed the steps below to use TensorRT-LLM to infer llama-7b：
1. build model,  no errors reported during the process
```
python build.py --model_dir ./tmp/llama/7B/ \
                --dtype float16 \
                --enable_debug_output \
                --remove_input_padding \
                --use_gpt_attention_plugin float16 \
                --enable_context_fmha \
                --use_gemm_plugin float16 \
                --output_dir ./tmp/llama/7B/trt_engines/fp16/1-gpu
```
2. run model 
```
python3 ../run.py --max_output_len=50 \
                  --tokenizer_dir ./tmp/llama/7B/ \
                  --engine_dir=./tmp/llama/7B/trt_engines/fp16/1-gpu/
```

But, the results are incorrect and numbers in embd-step*.txt are zeros!!!

The following are some environment configurations:
TensorRT-LLM: release/0.5.0
TensorRT: 9.1.0
torch: 2.1.0
transformers: 4.31.0
Driver: 535.54.03    
CUDA: 12.2
GPU: A100

**Comment by JensenFire** [comment]
Same question for the zero elements in embd-step*.txt. You have to move the `save` code ahead, otherwise the `next_step_buffer` will overwrite `self.debug_buffer`. (it's a little bug)

**Comment by byshiue** [comment]
Please take a try on latest main branch or 0.6.1

**Comment by yanz0920** [comment]
> Please take a try on latest main branch or 0.6.1

I've tried on latest main branch and 0.6.1 but the problem is still not solved.

**Comment by yanz0920** [comment]
> debug_buffer

I try to move "save" just after _run() and torch.cuda.synchronize(), but the problem is still not solved. 

There seems to be something wrong with the model because the output is not normal!

**Comment by QiJune** [comment]
Here is my command:

```bash
python build.py --model_dir ./llama-7b-hf/ \
                --dtype float16 \
                --remove_input_padding \
                --use_gpt_attention_plugin float16 \
                --enable_context_fmha \
                --use_gemm_plugin float16 \
                --output_dir ./tmp/llama/7B/trt_engines/fp16/1-gpu


python3 ../run.py --max_output_len=50 \
                  --tokenizer_dir ./llama-7b-hf/  \
                  --engine_dir=./tmp/llama/7B/trt_engines/fp16/1-gpu/
```


Here is the output:

```log
Input [Text 0]: "<s> Born in north-east France, Soyer trained as a"
Output [Text 0 Beam 0]: "chef in Paris and London before moving to New York in 1850. He was the first chef to be hired by the newly opened Delmonico’s restaura, where he worked for 10 years. He then opened his"
```

It seems that you open `enable_debug_output ` flag, it's only for debug purpose.
