### ISSUE TITLE
[BUG] BLOCK_SIZE doesn't take effect before quantization

### ISSUE THREAD

**Issue by Hongbosherlock** [NVIDIA/TensorRT-LLM#565]
When I using NVIDIA AMMO toolkit for AWQ weight quantization.
I run 
```
# Quantize HF LLaMA 7B checkpoint into INT4 AWQ format
python quantize.py --model_dir ./tmp/llama/7B \
                --dtype float16 \
                --qformat int4_awq \
                --export_path ./quantized_int4-awq \
                --calib_size 32
```
then in https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/llama/quantize.py#L61C5-L61C18
```
print(batch_encoded.shape)
```
I got `torch.Size([32, 1195])`

I found that the maximum length of these 32 samples after applying 'tokenizer.encode()' is 1195. All samples have been padded to a length of 1195 instead of being truncated to 512.

So, It seems that the `block_size=512` here didn't take effect.
https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/llama/quantize.py#L37

**Comment by Hongbosherlock** [comment]
[llm-awq](https://github.com/mit-han-lab/llm-awq/blob/main/awq/utils/calib_data.py) re-organize the calib data so that every batch has the same sequence length and there's no need for padding. 
see here：https://github.com/mit-han-lab/llm-awq/blob/main/awq/utils/calib_data.py
I don't know if it will affect the positional_embedding and further affect the data distribution during calibration.

**Comment by Tracin** [comment]
I do not think this may lead to accuracy problem, but this will consume larger GPU memory. https://github.com/NVIDIA/TensorRT-LLM/pull/293 I will make this merged ASAP.

**Comment by Tracin** [comment]
I will close this issue, if you have any further problems I will reopen.
