### ISSUE TITLE
[Question v0.6.1]Confused about the decoding batch_size

### ISSUE THREAD

**Issue by kimbaol** [NVIDIA/TensorRT-LLM#566]
Hi, I tried to run benchmark gptManagerBenchmark with v0.6.1, and confused about the batch_size of generate phase.

I add a print function in ReturnBatchManagerStatsCallback，and also add print function in GptServer::sendResponse() to print more information after each gpt forward step.

I built the trt-llm engine with max batch_size 8, and I want to run batch_size=8 in generate phase.
If I set --max_num_sequences to 8 in gptManagerBenchmark, the decoding batch in generate phase will be 4.
And it seems trt-llm will devide batch 8 into 2 * batch4.
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/5410381/e566a780-eacb-491b-a6ce-37ebb5428787)

My question is How to set decoding batch to 8 without splitting it into 2 batch * 4 ?

**Comment by qiaoxj07** [comment]
There is a flag "mManyMicroBatches" in BatchScheduler，maybe this flag controls whether to the split the batch. 
Is there any way to disable this "microbatch" schedule?

**Comment by Funatiq** [comment]
By default the manager will use two batches so preparation and execution can be overlapped. This is why `max_num_sequences` will be divided by 2. You can disable this in the benchmark using `--enable_trt_overlap=false`.
