### ISSUE TITLE
Docker build failed with v0.6.1

### ISSUE THREAD

**Issue by sihanwang41** [NVIDIA/TensorRT-LLM#573]
I am using ubuntu 22.04 and run  `make -C docker release_build`
It is failing in the `pip install mpi4py` step. 

```
54.13       checking for library 'lmpe' ...
54.13       /usr/local/mpi/bin/mpicc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -c _configtest.c -o _configtest.o
54.13       /usr/local/mpi/bin/mpicc _configtest.o -llmpe -o _configtest
54.13       /usr/bin/ld: cannot find -llmpe: No such file or directory
54.13       collect2: error: ld returned 1 exit status
54.13       failure.
```

**Comment by Slyne** [comment]
I managed to skip this error by replacing the `pip install mpi4py` in `tensorrt_llm/docker/common/install_base.sh`  with:
`python -m pip install https://github.com/Shixiaowei02/mpi4py/tarball/fix-setuptools-version`.

**Comment by sihanwang41** [comment]
> I managed to skip this error by replacing the `pip install mpi4py` in `tensorrt_llm/docker/common/install_base.sh` with: `python -m pip install https://github.com/Shixiaowei02/mpi4py/tarball/fix-setuptools-version`.

Hi @Slyne , do you mind sharing what is the fix in your tarball file? if it is a issue in the v0.6.0, it would be ideal to fix it in the master.

**Comment by Slyne** [comment]
> > I managed to skip this error by replacing the `pip install mpi4py` in `tensorrt_llm/docker/common/install_base.sh` with: `python -m pip install https://github.com/Shixiaowei02/mpi4py/tarball/fix-setuptools-version`.
> 
> Hi @Slyne , do you mind sharing what is the fix in your tarball file? if it is a issue in the v0.6.0, it would be ideal to fix it in the master.

It's not from my repo. It belongs to one of the TRTLLM developer @Shixiaowei02 . I think this issue is related to mpi4py and I remember they've already sent the pr.

**Comment by Shixiaowei02** [comment]
Thanks everyone for your helpful answers!
