### ISSUE TITLE
[Encoder-Decoder] Issues related to using t5, which has bias parameter and an embedding size that is not divisible by TP size

### ISSUE THREAD

**Issue by wlsghks4043** [NVIDIA/TensorRT-LLM#575]
Hi,

I verified fast inference by applying TensorRT-LLM based on the t5 model without bias parameter.

However, it still seems difficult to apply TensorRT-LLM if there is a bias parameter.

Also, there seems to be an issue where it cannot be built properly if the embedding size cannot be divided by the TP size.

**Comment by symphonylyh** [comment]
Hi @wlsghks4043 , we have internally verified and will soon release bias version (i.e. BART family, FairSeq NMT family), stay tuned and hope that can help.

On the second question, by embedding size do you mean vocab size? On the common T5 and BART family we mostly tested on TP=4 and TP=8, so we haven't enabled vocab padding yet. However, if you want some quick fix, you can apply the same padding from LLaMA example: https://github.com/NVIDIA/TensorRT-LLM/blob/f7eca56161d496cbd28e8e7689dbd90003594bd2/examples/llama/weight.py#L262. You can search for `pad` in this file.

**Comment by wlsghks4043** [comment]
Hi, @symphonylyh, 

The embedding size I mentioned meant vocab size, and I will proceed by referring to the LLaMA example you shared.

I look forward to the bias version being released soon.
Thank you for your kind reply.

**Comment by symphonylyh** [comment]
@wlsghks4043 BART and mBART are supported now on latest main! Annoucement: https://github.com/NVIDIA/TensorRT-LLM/discussions/670

Please have a try and let us know! Closing the issue for now, but feel free to reopen if there are further questions
