### ISSUE TITLE
Broken link to C++ benchmarking 

### ISSUE THREAD

**Issue by jinish1991** [NVIDIA/TensorRT-LLM#576]
On C++ benchmarking, it mentions to go to a link on steps to build TensorRTLLM  -- it points to this link which is broken 
https://github.com/NVIDIA/TensorRT-LLM/blob/release/README.md
How can I get access to this information?

**Comment by Slyne** [comment]
Installation:  https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/installation.md
C++ benchmark: https://github.com/NVIDIA/TensorRT-LLM/blob/main/benchmarks/cpp/README.md

**Comment by byshiue** [comment]
Could you share the broken link? We will fix is ASAP.

**Comment by Slyne** [comment]
> Could you share the broken link? We will fix is ASAP.

It's probably this:
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/6286804/ec3622f5-7266-46b8-9722-92a05777f532)

**Comment by byshiue** [comment]
Thank you. This is a known issue in 0.5.0 and it is fixed in 0.6.1 and main branch.
