### ISSUE TITLE
[Issue]PTQ INT8 calibration OOM

### ISSUE THREAD

**Issue by wjj19950828** [NVIDIA/TensorRT-LLM#587]
I refer to this [Issue](https://github.com/NVIDIA/TensorRT-LLM/issues/394) and want to use my own data set to obtain the scale value of SQ.

The scenario is 70b tp=2, the length of input_ids is not limited, instead of the default 923 in the [script](https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/examples/llama/smoothquant.py#L153)

But currently OOM occurs when the model is forwarded. I guess it is using the HF interface that causes OOM.

Is there any solution for this? Thanks~

Specific orders：
```shell
python3 hf_llama_convert.py -i $IN_MODEL -o $OUT_MODEL -sq 0.8 --tensor-parallelism 2 --storage-type fp16 -p 1
```

**Comment by wjj19950828** [comment]
@wm2012011492 

Do you have any suggestions? Thanks~

**Comment by Tracin** [comment]
Hi, which branch did you use?

**Comment by wjj19950828** [comment]
@Tracin 

I use the release/0.5.0 branch. Is there any update for 0.6.1?

**Comment by Tracin** [comment]
@wjj19950828 Please try with version 0.6.0 or later.
