### ISSUE TITLE
Can't use tensor_parrallel with chatglm2-6B

### ISSUE THREAD

**Issue by THU-mjx** [NVIDIA/TensorRT-LLM#588]
when i try to test tensor_parrallel with chatglm2-6B, something went wrong.
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/83857604/737df276-cbd6-49d0-938f-2d2ba594cc6c)

**Comment by byshiue** [comment]
Please share the branch you use. If you don't use the latest main branch, please take a try.
