### ISSUE TITLE
Building engines for Baichuan and Qwen failed

### ISSUE THREAD

**Issue by MIrandaStock** [NVIDIA/TensorRT-LLM#592]
```
python3 build.py --model_version v2_7b \
    --model_dir ./model_files/Baichuan2-7B-Chat \
    --dtype float16 \
    --use_gemm_plugin float16 \
    --use_gpt_attention_plugin float16 \
    --output_dir ./baichuan_v2_7b/trt_engines/fp16/1-gpu/
```
and
```
python3 build.py --hf_model_dir $model_path \
    --dtype bfloat16 \
    --remove_input_padding \
    --use_gpt_attention_plugin bfloat16 \
    --enable_context_fmha \
    --use_gemm_plugin bfloat16 \
    --output_dir $engine_dir \
```
have the same error:
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/45962405/fdd5e05c-c23d-4edc-befa-79d905ddba8a)

**Comment by byshiue** [comment]
What branch do you use? If you don't use latest main branch, can you take a try?

**Comment by Luis-xu** [comment]
Hi @MIrandaStock, I encountered a similar problem, how did you solve it?

**Comment by nghuyong** [comment]
I try the Baichuan7B(v1), and checkout to release/0.5.0 branch is OK, but the main branch has the same problem

**Comment by hello-11** [comment]
@MIrandaStock Do you still have the problem? If not, we will close it soon.
