### ISSUE TITLE
Access to context hidden states

### ISSUE THREAD

**Issue by akhoroshev** [NVIDIA/TensorRT-LLM#595]
Is there a way to access to context hidden states? I mean tensor with shape `[batch_size, max_input_token_num, hidden_size]`? In FasterTransformers it was easy. At [this](https://github.com/NVIDIA/FasterTransformer/blob/main/src/fastertransformer/models/multi_gpu_gpt/ParallelGpt.cc#L1092) point (after context decoding phase) I just access the tensor (`decoder_output_tensors["decoder_output"]`).

**Comment by byshiue** [comment]
You could mark it as output when you build the engine. Use GPT as example, you could mark the hidden_states [here](https://github.com/NVIDIA/TensorRT-LLM/blob/main/tensorrt_llm/models/gpt/model.py#L490-L492) as output.

**Comment by akhoroshev** [comment]
HI @byshiue !

For experiment I added line [here](https://github.com/NVIDIA/TensorRT-LLM/blob/main/tensorrt_llm/models/llama/model.py#L412)
```python
hidden_states.mark_output('hidden_states_output_test', self.dtype)
```

After that I created engine and run `gptManagerBenchmark`.

Also I modified [gptManagerBenchmark](https://github.com/NVIDIA/TensorRT-LLM/blob/main/benchmarks/cpp/gptManagerBenchmark.cpp#L398) to see output tensors
```c++
        for (auto& tensor: response_tensors) {
            TLLM_LOG_INFO(tensor.name);
            auto shape = tensor.tensor->getShape();
            TLLM_LOG_INFO("shape");
            std::cout << "[";
            for (auto i = 0; i < shape.nbDims; i++)
              std::cout << shape.d[i] << ", ";
            std::cout << "]" << std::endl;
            TLLM_LOG_INFO("type");
            auto type = tensor.tensor->getMemoryType();
            std::cout << static_cast<int32_t>(type) << std::endl;
        }
```

And I only can see "default" output tensors in output
```bash
[TensorRT-LLM][INFO] output_ids
[TensorRT-LLM][INFO] shape
[1, 1, 1213, ]
[TensorRT-LLM][INFO] type
1
[TensorRT-LLM][INFO] sequence_length
[TensorRT-LLM][INFO] shape
[1, 1, ]
[TensorRT-LLM][INFO] type
1
[TensorRT-LLM][INFO] output_log_probs
[TensorRT-LLM][INFO] shape
[1, 1, 1024, ]
[TensorRT-LLM][INFO] type
1
[TensorRT-LLM][INFO] cum_log_probs
[TensorRT-LLM][INFO] shape
[1, 1, ]
[TensorRT-LLM][INFO] type
1
```

Is it possible to forward "custom" output tensor for GptManager?

**Comment by byshiue** [comment]
It might be hard to add in c++ runtime, you could try adding on python runtime first.

**Comment by deidaraho** [comment]
> It might be hard to add in c++ runtime, you could try adding on python runtime first.

I have the same question. If the python code get modified as your above suggestion, then I build the gpt model by trtllm. Can the hidden_states get passed into postprocessing part?

**Comment by hello-11** [comment]
@akhoroshev Do you still have the problem? If not, we will close it soon.

**Comment by akhoroshev** [comment]
you still don't provide access to hidden states with executor
