### ISSUE TITLE
Struggling to get Yi-34B-200K-Llamafied-GPTQ to build

### ISSUE THREAD

**Issue by sigma-andex** [NVIDIA/TensorRT-LLM#604]
I'm trying to get it to build but struggling. My command is:
```
python build.py --model_dir /models/TheBloke_Yi-34B-200K-Llamafied-GPTQ/ \
                --quant_ckpt_path /models/TheBloke_Yi-34B-200K-Llamafied-GPTQ/model.safetensors \
                --dtype float16 \
                --remove_input_padding \
                --vocab_size 64000 \
                --n_head 56 \
                --use_gpt_attention_plugin float16 \
                --enable_context_fmha \
                --use_gemm_plugin float16 \
                --use_weight_only \
                --weight_only_precision int4_gptq \
                --per_group \
                --group_size 128 \
                --output_dir /triton-models/TheBloke_Yi-34B-200K-Llamafied-GPTQ/
```
But I'm getting the following error:
```
[12/07/2023-13:02:17] [TRT-LLM] [I] Process weights in layer: 0
Traceback (most recent call last):
  File "/home/triton/tensorrtllm_backend/tensorrt_llm/examples/llama/build.py", line 782, in <module>
    build(0, args)
  File "/home/triton/tensorrtllm_backend/tensorrt_llm/examples/llama/build.py", line 726, in build
    engine = build_rank_engine(builder, builder_config, engine_name,
  File "/home/triton/tensorrtllm_backend/tensorrt_llm/examples/llama/build.py", line 554, in build_rank_engine
    load_func(tensorrt_llm_llama=tensorrt_llm_llama,
  File "/home/triton/tensorrtllm_backend/tensorrt_llm/examples/llama/weight.py", line 1146, in load_from_gptq_llama
    process_and_assign_weight(layer.attention.qkv, qkv_weight_list)
  File "/home/triton/tensorrtllm_backend/tensorrt_llm/examples/llama/weight.py", line 1101, in process_and_assign_weight
    mOp.scale.value = scales_fp16.cpu().numpy()
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/parameter.py", line 84, in value
    assert v.shape == self._value.shape, \
AssertionError: The value updated is not the same shape as the original. Updated: (1, 9216), original: (56, 9216)
```

What am I missing? 
Also if I leave out group_size I get `got an unexpected keyword argument 'group_size'`. Why is that and why doesn't it pick the parameters automatically from the config.json?

Thanks in advance for any help!

**Comment by sigma-andex** [comment]
Related issue: #567

**Comment by Tracin** [comment]
@sigma-andex Hi, Which branch did you use, could you try with `0.6.1`? And can you show me the instruction to generate `model.safetensors` file please?

**Comment by sigma-andex** [comment]
Hi, I don’t have the instructions for creating the mode.safetensors, as I just downloaded these from [here](https://huggingface.co/TheBloke/Yi-34B-200K-Llamafied-GPTQ/tree/main). I built and tried the main branch with the latest changes from 8th of december.

**Comment by Tracin** [comment]
> Hi, I don’t have the instructions for creating the mode.safetensors, as I just downloaded these from [here](https://huggingface.co/TheBloke/Yi-34B-200K-Llamafied-GPTQ/tree/main). I built and tried the main branch with the latest changes from 8th of december.

I think there might be slightly different between this GPTQ model with the one we support, could you please try quantize the model using instructions we supplied?

**Comment by Tracin** [comment]
Another solution is try with `--group_size=7168`
