### ISSUE TITLE
Llama-2-7b TRT-LLM AWQ quantization gives error

### ISSUE THREAD

**Issue by apbose** [NVIDIA/TensorRT-LLM#607]
Hi Team, I am currently working on TRT-LLM AWQ quantization on llama model on the branch `release/0.5.0 `, and I am facing error in building the engine -
`python3 build.py --model_dir ${path_model} --quant_ckpt_path ${path_quant_awq} --dtype float16 --remove_input_padding --use_gpt_attention_plugin float16 --enable_context_fmha --use_gemm_plugin float16 --use_weight_only --weight_only_precision int4_awq --output_dir ${path_engine_awq}`

I am facing error- 
```
Traceback (most recent call last):
  File "build.py", line 719, in <module>
    build(0, args)
  File "build.py", line 690, in build
    engine = build_rank_engine(builder, builder_config, engine_name,
  File "build.py", line 564, in build_rank_engine
    load_from_hf_llama(tensorrt_llm_llama,
  File "/home/nvidia/workspace/abose/zoox_llama/trt_llm_main_ORIN/TensorRT-LLM/examples/llama/weight.py", line 279, in load_from_hf_llama
    dst = tensorrt_llm_llama.layers[idx].attention.dense.weight
  File "/home/nvidia/.local/lib/python3.8/site-packages/tensorrt_llm/module.py", line 51, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'WeightOnlyGroupwiseQuantRowLinear' object has no attribute 'weight'
```

This comes in` load_from_hf_llama` . Would anyone know why this error is coming. Also why do we need to call both load_from_awq_llama  and load_from_hf_llama  for this?
Thanks!

**Comment by Tracin** [comment]
@apbose  Hi, can you try with code of v0.6.1? It works from my side. And please add `--per_group` option for int4_awq or you will meet another error.

**Comment by apbose** [comment]
Thanks for the suggestion. I tried with TRT 0.6.1. I get the following error by using the command line
` python3 build.py --model_dir ${path_model} --quant_ckpt_path ${path_quant_awq} --per_group --dtype float16 --remove_input_padding --use_gpt_attention_plugin float16 --enable_context_fmha --use_gemm_plugin float16 --use_weight_only --weight_only_precision int4_awq --output_dir ${path_engine_awq}`

Error
```
[02/21/2024-20:45:17] [TRT] [E] 3: getPluginCreator could not find plugin: WeightOnlyGroupwiseQuantMatmultensorrt_llm version: 1
 File "/home/nvidia/.local/lib/python3.8/site-packages/tensorrt_llm/quantization/layers.py", line 500, in forward
    x = weight_only_groupwise_quant_matmul(x, pre_quant_scale,
  File "/home/nvidia/.local/lib/python3.8/site-packages/tensorrt_llm/quantization/functional.py", line 105, in weight_only_groupwise_quant_matmul
    assert plg_creator is not None
AssertionError
```
I see that there is a WeightOnlyGroupwiseQuantMatmul plugin in the cpp files, so why is the registry throwing an error? Is there some issue with the version or namespace?

**Comment by Tracin** [comment]
@apbose Please try rebuild the code with `--clean` options. `python3 ./scripts/build_wheel.py --clean  --trt_root /usr/local/tensorrt`

**Comment by apbose** [comment]
Yes the issue was that it had two versions of TensorRT conflicting with each other.  The wheel was built with TRT9 while the installed python TRT8.6. I could get over the above, I face this error on ORIN
`[qdqGraphOptimizer.cpp::matchInt8ConstantDQ::3781] Error Code 4: Internal Error (: Int8 constant usage is restricted to explicit precision mode)`
I however do not face this on x86. Any idea what might be the error?

**Comment by apbose** [comment]
I could get over this. The issue was the TRT version. It works with TRT 9.2.0.0 with TRT-LLM 0.6.1. Thanks for the help!
