### ISSUE TITLE
Mixtral 8x 7B - MoE by Mistral AI

### ISSUE THREAD

**Issue by casper-hansen** [NVIDIA/TensorRT-LLM#616]
Mistral AI released their new model called `Mixtral` which is an MoE architecture based on MegaBlocks. It includes 8 experts with the size being 7 billion parameters each.

Here is the model configuration:

- dim: 4096
- n_layers: 32
- head_dim: 128
- hidden_dim: 14336
- n_heads: 32
- n_kv_heads: 8
- norm_eps: 1e-05
- vocab_size: 32000
- moe:
  - num_experts_per_tok: 2
  - num_experts: 8

Weights: https://twitter.com/MistralAI/status/1733150512395038967
Paper: https://arxiv.org/pdf/2211.15841.pdf
Code: https://github.com/stanford-futuredata/megablocks

**Comment by ncomly-nvidia** [comment]
Keep an eye out - we have been working on this model & it will be available shortly.

**Comment by jdemouth-nvidia** [comment]
As you’ll see on Mistral’s website, we’ve been working with the team on integrating their model to TensorRT-LLM (https://mistral.ai/news/la-plateforme/)

**Comment by heianzero** [comment]
Will AWQ int4 quantization be supported？

**Comment by snippetzero** [comment]
Will TensorRT-LLM Mixtral 8x7B support awq int4 quantization?

**Comment by wang90063** [comment]
Set mark here. Expecting mixtral supported by trtllm:)

**Comment by ncomly-nvidia** [comment]
Mixtral is supported in [main](https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/mixtral)! Take a look!

**Comment by eycheung** [comment]
Awesome news @ncomly-nvidia ! Do you know if this has been tested with any quantization? In Hugging Face, they have a (slightly modified) GPTQ version you can load https://huggingface.co/blog/mixtral#load-mixtral-with-gptq

**Comment by wangyubo111** [comment]
@ncomly-nvidia , how about the Mixtral-8x7B-Instruct-v0.1? Is this also planned to support soon?

**Comment by antonpolishko** [comment]
> @ncomly-nvidia , how about the Mixtral-8x7B-Instruct-v0.1? Is this also planned to support soon?

What's prevent you from running it already? Mixtral is part of the main for a few weeks now

**Comment by enochlev** [comment]
any t/s or tfs benchmarks?
