### ISSUE TITLE
Development Updates on Main/Rel Branch: Bare Metal Building with Windows 11

### ISSUE THREAD

**Issue by ToddThomson** [NVIDIA/TensorRT-LLM#618]
To build the cpp runtime on Win 11 requires either the source files or the static lib for the batch manager. I am not sure why the source files are not provided for the batch manager, but okay. However, please add the #569 to the main branch as it seems that the main branch is being used for new (latest) code changes before an actual release. #569 is part of the "rel" branch (not sure now what the rel branch is for.. latest release/0.6.1?).

Thanks in advance.

**Comment by ToddThomson** [comment]
Additionally.. Can the debug version of the batch manager static lib be included in the main branch?

**Comment by ToddThomson** [comment]
I saw that the rel branch was just updated. Unfortunately the batch manager static lib for Windows is not included. This means that we cannot build from source for Windows.

Is the Windows cpp bare metal build not a priority?

**Comment by ToddThomson** [comment]
If you can't beat 'em then join 'em... WSL 2 Ubuntu on Win 11 + VS Code + docker works remarkably well.
I'd still like to work with Win 11 and a cpp build with VS though. Just need the batch manager static lib for Win with each release.

**Comment by hello-11** [comment]
@ToddThomson Do you still have the problem? If not, we will close it soon.
