### ISSUE TITLE
Add automatic reuse of common key value cache blocks between requests

### ISSUE THREAD

**Issue by ttim** [NVIDIA/TensorRT-LLM#620]
Imagine two requests sharing same prefix comes to the trt-llm generation runtime, it would be awesome if those requests can share key value cache blocks between each other.

During generation with paged attention in fact each block corresponds to particular prefix of the input, so all of the blocks can be made prefix addressable (i.e. it should be possible to keep a map from prefix to block, or from additional prefix and previous block to a new block). This way automatic reuse of blocks between generation requests with shared prefixes will be done "out of box".

This potentially can be beneficial for speculative execution as well.

**Comment by ncomly-nvidia** [comment]
Hi @ttim, great suggestion & definitely can help save compute & memory! We are already working on this which will help with both system prompts, & interactive / chat based generation. It should be out in the next few weeks.

**Comment by ncomly-nvidia** [comment]
Hey @kamalkraj, Interactive generation can be achieved via system prompt caching added in v0.7.1!

**Comment by ttim** [comment]
@ncomly-nvidia Are there documentation available for this feature?

**Comment by atyshka** [comment]
+1 on documentation for this feature

**Comment by littletomatodonkey** [comment]
@ncomly-nvidia Hi, any docs for the reuse of common k-v cache? Thanks!

**Comment by littletomatodonkey** [comment]
> Hey @kamalkraj, Interactive generation can be achieved via system prompt caching added in v0.7.1!

Hi @ncomly-nvidia Is there any docs for system prompt caching?

**Comment by vinhngx** [comment]
Document on kv-cache reuse feature: https://nvidia.github.io/TensorRT-LLM/advanced/kv-cache-reuse.html
