### ISSUE TITLE
Segmentation fault when building trt engine

### ISSUE THREAD

**Issue by BirdChristopher** [NVIDIA/TensorRT-LLM#621]
Hi,!

I tried to test the BLOOM example. However, when I run `python build.py  --dtype float16 --use_gemm_plugin float16 --use_gpt_attention_plugin float16 --output_dir ./trt_engines/` , it show the error message below:

```
[12/10/2023-18:49:03] [TRT-LLM] [I] Serially build TensorRT engines.
[12/10/2023-18:49:03] [TRT] [I] [MemUsageChange] Init CUDA: CPU +12, GPU +0, now: CPU 132, GPU 386 (MiB)
[12/10/2023-18:49:06] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +446, GPU +118, now: CPU 633, GPU 504 (MiB)
[12/10/2023-18:49:06] [TRT] [E] 3: [builderConfig.cpp::setPreviewFeature::562] Error Code 3: API Usage Error (Parameter check failed at: optimizer/api/builderConfig.cpp::setPreviewFeature::562, condition: int(feature) >= 0 && int(feature) < EnumMax<PreviewFeature>()
)
[12/10/2023-18:49:06] [TRT-LLM] [W] Invalid timing cache, using freshly created one
[daim216:884464:0:884464] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))
==== backtrace (tid: 884464) ====
 0 0x0000000000014420 __funlockfile()  ???:0
=================================
[daim216:884464] *** Process received signal ***
[daim216:884464] Signal: Segmentation fault (11)
[daim216:884464] Signal code:  (-6)
[daim216:884464] Failing at address: 0xd7ef0
[daim216:884464] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x14420)[0x7f7c56d51420]
[daim216:884464] *** End of error message ***
Segmentation fault (core dumped)
```
Here's some revision info about my operating environment:
```
ubuntu 20.04
gcc 9.4.0
glibc 2.31
TensorRT-LLM 0.6.1
TensorRT 9.1.0.4
Python 3.11.5
cuda 12.1
GPU RTX4090
```
Can any body help me solve this problem?

**Comment by QiJune** [comment]
It seems that the issue is related to https://github.com/NVIDIA/TensorRT-LLM/blob/f7eca56161d496cbd28e8e7689dbd90003594bd2/tensorrt_llm/builder.py#L156-L157

@litaotju  Could you please take a look? Thanks!

**Comment by litaotju** [comment]
@BirdChristopher  does it work when you remove the line suggested by @QiJune  above?
And which container are you using?

**Comment by BirdChristopher** [comment]
> @BirdChristopher does it work when you remove the line suggested by @QiJune above? And which container are you using?

@litaotju 
Nope，the error message do not change...

Since I can only access a docker container offered by the HPC admin, I cannot follow the "docker installation method".

**Comment by BirdChristopher** [comment]
@litaotju 
So sorry for bothering you since I still can‘t find any related solution...
Could you please offer some further help at your convenience? Thank you!

**Comment by litaotju** [comment]
@BirdChristopher ,
No worry. Pls try these:

1. can you try to turn on verbose log by setting "--log_level verbose" such that more error msg can be printed?

2. And could you try another env which you have the right to follow the docker usage flow?

3. Besides, TRT-LLM 0.6.1 should work with TRT 9.2, not TRT 9.1. We QA tested with the latest TRT version when we relesae, which is 9.2.   Older version is not guaranteed to work.

**Comment by litaotju** [comment]
See this https://github.com/NVIDIA/TensorRT-LLM/blob/v0.6.1/docker/common/install_tensorrt.sh#L66 to install 9.2 TRT

**Comment by BirdChristopher** [comment]
> @BirdChristopher , No worry. Pls try these:
> 
> 1. can you try to turn on verbose log by setting "--log_level verbose" such that more error msg can be printed?
> 2. And could you try another env which you have the right to follow the docker usage flow?
> 3. Besides, TRT-LLM 0.6.1 should work with TRT 9.2, not TRT 9.1. We QA tested with the latest TRT version when we relesae, which is 9.2.   Older version is not guaranteed to work.

@litaotju  
1. The error msg after adding "--log_level verbose" and remove:
> https://github.com/NVIDIA/TensorRT-LLM/blob/f7eca56161d496cbd28e8e7689dbd90003594bd2/tensorrt_llm/builder.py#L156-L157
> 
is: (Remove this line of code only make the "API Usage Error" disappear)
```
python build.py  --dtype float16 --use_gemm_plugin float16 --use_gpt_attention_plugin float16 --output_dir ./trt_engines/ --log_level verbose
[1702614078.462893] [daim216:1461574:f]        vfs_fuse.c:281  UCX  ERROR inotify_add_watch(/tmp) failed: No space left on device
[12/15/2023-12:21:25] [TRT-LLM] [I] Serially build TensorRT engines.
[12/15/2023-12:21:25] [TRT] [I] [MemUsageChange] Init CUDA: CPU +11, GPU +0, now: CPU 139, GPU 386 (MiB)
[12/15/2023-12:21:25] [TRT] [V] Trying to load shared library libnvinfer_builder_resource.so.8.5.3
[12/15/2023-12:21:25] [TRT] [V] Loaded shared library libnvinfer_builder_resource.so.8.5.3
[12/15/2023-12:21:28] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +446, GPU +118, now: CPU 640, GPU 504 (MiB)
[12/15/2023-12:21:28] [TRT] [V] CUDA lazy loading is enabled.
[12/15/2023-12:21:28] [TRT-LLM] [W] Invalid timing cache, using freshly created one
[12/15/2023-12:21:28] [TRT-LLM] [I] [MemUsage] Rank 0 Engine build starts - Allocated Memory: Host 1.2190 (GiB) Device 0.4929 (GiB)
[12/15/2023-12:21:38] [TRT-LLM] [I] [MemUsage] Rank 0 model weight loaded. - Allocated Memory: Host 17.0797 (GiB) Device 4.3855 (GiB)
[daim216:1461574:0:1461574] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))
==== backtrace (tid:1461574) ====
 0 0x0000000000014420 __funlockfile()  ???:0
=================================
[daim216:1461574] *** Process received signal ***
[daim216:1461574] Signal: Segmentation fault (11)
[daim216:1461574] Signal code:  (-6)
[daim216:1461574] Failing at address: 0x164d46
[daim216:1461574] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x14420)[0x7fc63eba7420]
[daim216:1461574] *** End of error message ***
Segmentation fault (core dumped)
```
(Last time I tried to remove this line in another `builder.py` which is not in use.  Sorry for my negligence)

2. I prefer keep using current container since it will be badly troublesome for me to apply for a new container from HPC admin and prepare all dev environment again.....sorry

3. I have switched to trt 9.2(also reinstall trt-llm based on new trt) and run the same command again, error message is above.

**Comment by litaotju** [comment]
@BirdChristopher , 

From the log, I can not find much info.

The last msg `[MemUsage] Rank 0 model weight loaded. - Allocated Memory: Host 17.0797 (GiB) Device 4.3855 (GiB)`
is from this line https://github.com/NVIDIA/TensorRT-LLM/blob/v0.6.1/examples/bloom/build.py#L415

could you try to add some more print inside the build.py to figure out which line caused the crash?

**Comment by BirdChristopher** [comment]
> @BirdChristopher ,
> 
> From the log, I can not find much info.
> 
> The last msg `[MemUsage] Rank 0 model weight loaded. - Allocated Memory: Host 17.0797 (GiB) Device 4.3855 (GiB)` is from this line https://github.com/NVIDIA/TensorRT-LLM/blob/v0.6.1/examples/bloom/build.py#L415
> 
> could you try to add some more print inside the build.py to figure out which line caused the crash?

@litaotju 
Program crash in this funtion call:

https://github.com/NVIDIA/TensorRT-LLM/blob/9b3e12dbc820a8b72bcd7d712a8c9a54facf97df/tensorrt_llm/network.py#L72

I can't find the exact implementation of this `NetworkDefinitionCreationFlag.get_flag` and I am not able to trace deeper.

**Comment by BirdChristopher** [comment]
Finally I found that there is another `libnvinfer.so.8.5.1` in `/usr/lib/x86_64-linux-gnu` on my machine, which is chosen by cmake to do the linking when I built trt. (This trt lib seems to exist ever since the creation of my docker container)

So my final solution is replacing those "fake" libs with TensorRT 9.2 GA  lib. Really appreciate your help! @litaotju
