### ISSUE TITLE
Issues with importing LoraConfig

### ISSUE THREAD

**Issue by Gerard235** [NVIDIA/TensorRT-LLM#627]
On a Windows 11 pc, in a virtual environment with tensorrt version 9.2.0.post12.dev5 and tensorrt_llm version 0.6.1, when using the build.py script in the examples/llama folder of this main branch I am getting error messages indicating issues importing LoraConfig.

On the same pc, in a separate virtual environment with tensorrt version 9.1.0.post12.dev4 and tensorrt_llm version 0.5.0.post1, I have not had any issues with using the build.py script in the examples/llama folder of the release/0.5.0 branch (that branch does not have the loraconfig/loramanager bits of code).

Thanks!

**Comment by Gerard235** [comment]
This commit (ebc77c2) with additions to tensorrt_llm/runtime/lora_manager.py including the LoraConfig class has not been added to the main branch.

https://github.com/NVIDIA/TensorRT-LLM/commit/ebc77c2894248009ac7b17f1ec7c3fbf4d804f7c#diff-11bfbf4b4a0f4a041261938975c0130d3d5497d387538ca7d23876a6800f1f3b

**Comment by byshiue** [comment]
Sorry, I don't get you point. You can find `LoraConfig` in main branch https://github.com/NVIDIA/TensorRT-LLM/blob/main/tensorrt_llm/runtime/lora_manager.py#L10-L32.

**Comment by Gerard235** [comment]
Hi

After creating a new environment and running
pip install --no-cache-dir tensorrt_llm --extra-index-url https://pypi.nvidia.com --extra-index-url https://download.pytorch.org/whl/cu121

If I then navigate to the lora_manager.py file, I find that it is only 75 lines of code long and does not have the LoraConfig class.

Grateful for your response!

**Comment by byshiue** [comment]
0.6.1 does not have it. This feature is only supported in main branch now.

**Comment by sestephens-nv** [comment]
The Windows beta release is only supported on the `rel` branch at this time. The wheel you've installed for `tensorrt_llm version 0.6.1` won't be compatible with all changes on `main`. Checking out `rel` should solve your issue.
