### ISSUE TITLE
building with cuda11.7

### ISSUE THREAD

**Issue by Celeste-cj** [NVIDIA/TensorRT-LLM#628]
I'm trying to install tensorrt out of docker, and my cuda version is 11.7. 
The environment in install_tensorrt.sh is as follows:
```
TRT_VER="9.2.0.5"
CUDA_VER="11.7"
CUDNN_VER="8.5.0.96-1+cuda11.7"
NCCL_VER="2.13.4-1+cuda11.7"
CUBLAS_VER="12.2.5.6-1"
```

When installing libnccl2, I run into the following error: 

```
The following packages have unmet dependencies:
 libnccl2 : Depends: libc6 (>= 2.34) but 2.31-13+deb11u6 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by byshiue** [comment]
Hi! TensorRT-LLM is only compatible with CUDA-12.2 now.

**Comment by Celeste-cj** [comment]
> Hi! TensorRT-LLM is only compatible with CUDA-12.2 now.

Hi! Switched to cuda-12.2 but still got this error:

```
The following packages have unmet dependencies:
 libnccl2 : Depends: libc6 (>= 2.34) but 2.31-13+deb11u6 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by byshiue** [comment]
It it related to other packages and I am not familiar with them. We suggest using the docker we provide first to prevent such environment setting issue.
