### ISSUE TITLE
maximum recursion depth exceeded?

### ISSUE THREAD

**Issue by THU-mjx** [NVIDIA/TensorRT-LLM#630]
tensorrt_llm  version 0.6.0
I built the engines through this command:
`python3 build.py --model_dir=/temp_data/LLM_test/llama/skyline2006/llama-7b --enable_context_fmha --remove_input_padding --world_size=4 --pp_size=2 --tp_size=2 --dtype=float16 --use_gpt_attention_plugin=float16 --use_gemm_plugin=float16 --output_dir=/temp_data/LLM_test/llama/skyline2006/llama-7b/trt_engines/fp16/1-gpu/`
 when i run the run.py with this command:
`python3 ../run.py --max_output_len=50 --tokenizer_dir=/temp_data/LLM_test/llama/skyline2006/llama-7b/ --engine_dir=/temp_data/LLM_test/llama/skyline2006/llama-7b/trt_engines/fp16/1-gpu/ --input_text="In Bash, how do I list all text files?"`
an error occurred
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/83857604/5015f487-03ba-473c-9616-d1d5f6d4820f)

**Comment by byshiue** [comment]
Could you try on main branch or 0.6.1?

**Comment by THU-mjx** [comment]
I am using the main branch.

**Comment by byshiue** [comment]
You mentioned you use trt llm 0.6.0, is it a typo? 

Also, do you build the docker image by the docker file?

**Comment by byshiue** [comment]
You mentioned you use trt llm 0.6.0, is it a typo? 

Also, do you build the docker image by the docker file?

**Comment by THU-mjx** [comment]
I use the `nvcr.io/nvidia/tritonserver:23.10-trtllm-python-py3` image to build docker.
The build engine processes are successful.
 I test trt llm 0.6.0 and 0.6.1, when i run the python file 'run.py', both result in the same error.

**Comment by THU-mjx** [comment]
this issue was solved by replacing the tokenizer_config.json by
```
{
  "add_bos_token": true,
  "add_eos_token": false,
  "bos_token": {
    "__type": "AddedToken",
    "content": "<s>",
    "lstrip": false,
    "normalized": true,
    "rstrip": false,
    "single_word": false
  },
  "clean_up_tokenization_spaces": false,
  "eos_token": {
    "__type": "AddedToken",
    "content": "</s>",
    "lstrip": false,
    "normalized": true,
    "rstrip": false,
    "single_word": false
  },
  "model_max_length": 2048,
  "pad_token": null,
  "sp_model_kwargs": {},
  "tokenizer_class": "LlamaTokenizer",
  "unk_token": {
    "__type": "AddedToken",
    "content": "<unk>",
    "lstrip": false,
    "normalized": true,
    "rstrip": false,
    "single_word": false
  }
}
```
