### ISSUE TITLE
Pipeline parallelism doesn't seem to be supported with continuous batching

### ISSUE THREAD

**Issue by ttim** [NVIDIA/TensorRT-LLM#633]
While running experiments with Llama 7B with and without pipeline parallelism (A100x1 & A100x2) I discovered no difference in either latency or throughput between pp=1 and pp=2 configurations, which made me think it's not supported with continous batching. Did I misconfigure something? Or it's not supported, and then is it going to be supported?

**Comment by MartinMarciniszyn** [comment]
Pipeline parallelism is supported with continuous batching. Did you observe any activity on the second device with `pp = 2`? If not, there might be some configuration issue.

**Comment by MartinMarciniszyn** [comment]
Closing for now. Please re-open if the problem persists.
