### ISSUE TITLE
Any plans to support Stable Diffusion models?

### ISSUE THREAD

**Issue by ttim** [NVIDIA/TensorRT-LLM#634]
I understand SD models aren't LLMs, neither they are autoregressive. However given the existence of the all main blocks (i.e. cross attention kernels, pytorch-like tensor abstraction) in TRT-LLM it seems reasonable to support it in TRT-LLM, just outside of GPT Runtime. Are there any plans for that?

**Comment by ncomly-nvidia** [comment]
Hi @ttim they absolutely _could_ be supported in TRT-LLM, but as of now it is the goal to make LLMs great. We may evaluate diffusion models in the future.

FYI check out a super fast stable diffusion implementation with [demoDiffusion](https://github.com/NVIDIA/TensorRT/blob/release/8.6/demo/Diffusion/utilities.py).
