### ISSUE TITLE
INT8 KV cache + per-channel weight-only quantization leading to wired result

### ISSUE THREAD

**Issue by wjueyao** [NVIDIA/TensorRT-LLM#644]
I followed the step in this issue https://github.com/triton-inference-server/tensorrtllm_backend/issues/211 to build INT8 KV cache + per-channel weight-only quantization engine.

However the result is wired. I used the prompt from human-eval
`"from typing import List\n\n\ndef has_close_elements(numbers: List[float], threshold: float) -> bool:\n    \"\"\" Check if in given list of numbers, are any two numbers closer to each other than\n    given threshold.\n    >>> has_close_elements([1.0, 2.0, 3.0], 0.5)\n    False\n    >>> has_close_elements([1.0, 2.8, 3.0, 4.0, 5.0, 2.0], 0.3)\n    True\n    \"\"\"\n"`

But getting all `\n`s
`"text": "\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"`

**Comment by Tracin** [comment]
Hi, please let me know your model type, your branch can your building instructions. Thanks!

**Comment by wjueyao** [comment]
> Hi, please let me know your model type, your branch can your building instructions. Thanks!

@Tracin Sure. I build and run the model with the following steps:
First I build the backend using main branch
```
git clone -b main  https://github.com/triton-inference-server/tensorrtllm_backend.git
# Update the submodules
cd tensorrtllm_backend
git lfs install
git submodule update --init --recursive
# Use the Dockerfile to build the backend in a container
# For x86_64
DOCKER_BUILDKIT=1 docker build -t triton_trt_llm -f dockerfile/Dockerfile.trt_llm_backend .
```
Then I build engine files
```
python3 hf_llama_convert.py -i /weights/huggingface/codellama/CodeLlama-7b-hf    \
                -o /weights/trt_llm/2023.12.12/llama_7B_int8_kv_cache \
                --calibrate-kv-cache \
                -t fp16 \
                --tensor-parallelism 4


# Build model with both INT8 weight-only and INT8 KV cache enabled
python build.py --ft_model_dir=/weights/trt_llm/2023.12.12/llama_7B_int8_kv_cache/4-gpu/ \
                --dtype float16 \
                --remove_input_padding \
                --use_gpt_attention_plugin float16 \
                --paged_kv_cache \
                --use_inflight_batching \
                --enable_context_fmha \
                --use_gemm_plugin float16 \
                --max_batch_size 64  \
                --vocab_size 32016  \
                --output_dir /weights/trt_llm/2023.12.12/convert/4-gpu \
                --int8_kv_cache \
                --use_weight_only \
                --world_size 4 \
                --tp_size 4
```

**Comment by Tracin** [comment]
@wjueyao Thanks! Please use tag v0.6.1 to build the engine, we do find bad accuracy with main branch before.

**Comment by wjueyao** [comment]
> @wjueyao Thanks! Please use tag v0.6.1 to build the engine, we do find bad accuracy with main branch before.

@Tracin ok got it. I'll try to build the engine on v0.6.1. and see if it works

**Comment by wjueyao** [comment]
@Tracin I use v0.6.1 to run the above steps, and got the following error when I run hf_llama_convert.py

```
Traceback (most recent call last):
  File "/tensorrtllm_backend/tensorrt_llm/examples/llama/hf_llama_convert.py", line 359, in <module>
    hf_gpt_converter(args)
  File "/tensorrtllm_backend/tensorrt_llm/examples/llama/hf_llama_convert.py", line 253, in hf_gpt_converter
    param = param.detach().cpu().numpy().astype(storage_type)
TypeError: Got unsupported ScalarType BFloat16
```

**Comment by Tracin** [comment]
@wjueyao Sorry, this will be fixed in 0.7.0 in recent days.
please delete this [line](https://github.com/NVIDIA/TensorRT-LLM/blob/v0.6.1/examples/llama/hf_llama_convert.py#L177) for now.

**Comment by wjueyao** [comment]
> @wjueyao Sorry, this will be fixed in 0.7.0 in recent days. please delete this [line](https://github.com/NVIDIA/TensorRT-LLM/blob/v0.6.1/examples/llama/hf_llama_convert.py#L177) for now.

@Tracin I delete the line and build the engine successfully.

However, the result I got is still all`\n` s with the same prompt I post above

**Comment by Tracin** [comment]
@wjueyao I think you forget to add this option `--rotary_base 1000000` for codellama. This can be found in Readme.

**Comment by wjueyao** [comment]
> @wjueyao I think you forget to add this option `--rotary_base 1000000` for codellama. This can be found in Readme.

@Tracin Thanks! The result looks much better now! I'll run through the whole human-eval test suites, and post the result later

**Comment by Tracin** [comment]
Great job! I will close this issue, if there is any further problem please @ me.
