### ISSUE TITLE
Build error: ARG requires exactly one argument

### ISSUE THREAD

**Issue by xuwei6** [NVIDIA/TensorRT-LLM#645]
I followed the [installation.md](https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/installation.md),   but got an error. It prompts me need to configure this parameter {DOCKER_BUILD_ARGS}, how should i do? thank you so much！
![ScreenShot_20231212205119](https://github.com/NVIDIA/TensorRT-LLM/assets/46132452/62e1c351-9cb7-4c53-ba0c-a8b7f8392c86)

**Comment by Shixiaowei02** [comment]
Please upgrade Docker to [version >= 20.10](https://github.com/moby/buildkit/pull/1692) and this issue will be solved. Thanks!
