### ISSUE TITLE
[Question]How should I use greedy sample

### ISSUE THREAD

**Issue by wjj19950828** [NVIDIA/TensorRT-LLM#646]
I see some greedy sample [testcase](https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/tests/model/test_bloom.py#L361). 

Set topk/topp to 0 and temperature to 1. 

After I set it up like this, the final result will not produce eos tokens. This is reasonable? 

Thank you~

**Comment by byshiue** [comment]
It is possible and depends on the model capability and prompt input.

**Comment by byshiue** [comment]
For greedy search, the best way is setting topk 1 and topp 0. 

When both topk and topp are 0, TRT LLM will set it to greedy search automatically.

**Comment by wjj19950828** [comment]
> It is possible and depends on the model capability and prompt input.

@byshiue The specific phenomena are as follows:

With the same prompts, the random sample can generate eos token normally and terminate, but the greedy sample does not generate eos token. Is this reasonable?

**Comment by byshiue** [comment]
It is expected.

**Comment by wjj19950828** [comment]
> It is expected.

@byshiue 
But when I send a request using the service method, I use the above greedy sample parameter and use streaming return. When the last character is received, the last character will be output twice instead of eos token. 

Random sample will not have this phenomenon. Is this a known issue?

![image](https://github.com/NVIDIA/TensorRT-LLM/assets/19977378/93e30501-5943-4c77-a146-a52a95ed2ee3)

**Comment by byshiue** [comment]
Do you use latest main branch?

**Comment by wjj19950828** [comment]
@byshiue use 0.5.0，I run the TRT_LLM runtime locally and the related problem did not recur. I only encountered it in trtion inference server. Is this a known issue?

**Comment by wjj19950828** [comment]
> @byshiue use 0.5.0，I run the TRT_LLM runtime locally and the related problem did not recur. I only encountered it in trtion inference server. Is this a known issue?

0.6.1 meet same question.

**Comment by wjj19950828** [comment]
@byshiue Do you have some suggestions?

**Comment by byshiue** [comment]
I don't have suggestion now because we cannot reproduce your issue. You could try adding some debug message in plugin to make sure you have rebuilt the tensorrtllm and engine successfully because we see many missing on rebuiding.
