### ISSUE TITLE
Issues when running gptSessionBenchmark with --enable_cuda_graph

### ISSUE THREAD

**Issue by sleepwalker2017** [NVIDIA/TensorRT-LLM#650]
# Seems it takes too much memory:

When I run test for batch 16
```
mpirun -n 2 --allow-run-as-root benchmarks/gptSessionBenchmark --model llama --engine_dir /data/weilong.yu/TRT-LLM-0.6/examples/llama/tmp/llama/13B/trt_engines/fp16/2-gpu/ --batch_size 16 --input_output_len "512,96" --warm_up 10
```
It runs ok. 

When I add `--enable_cuda_graph`, it reports error:
```
sh run.sh 8
Failed, NCCL error /data/weilong.yu/TRT-LLM-0.6/cpp/tensorrt_llm/plugins/ncclPlugin/allreducePlugin.cpp:186 'unhandled cuda error (run with NCCL_DEBUG=INFO for details)'
Failed, NCCL error /data/weilong.yu/TRT-LLM-0.6/cpp/tensorrt_llm/plugins/ncclPlugin/allreducePlugin.cpp:186 'unhandled cuda error (run with NCCL_DEBUG=INFO for details)'
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[58523,1],0]
  Exit code:    1
```

# performance issue

when I set batch_size to 1, the test runs ok.
But seems the performance is much lower when enabling cuda graph.
`44.57 token/sec no cuda graph` VS  `9.92 token/sec with cuda graph`

**Comment by MartinMarciniszyn** [comment]
Cuda graphs may not be supported in a multi-device setup. Does it work on a single device? Please enable `NCCL_DEBUG=INFO` in your environment as suggest by the error message and add the full error log here.

**Comment by sleepwalker2017** [comment]
> Cuda graphs may not be supported in a multi-device setup. Does it work on a single device? Please enable `NCCL_DEBUG=INFO` in your environment as suggest by the error message and add the full error log here.

cuda graph works on single GPU, but the benefit is very small, I think there is no need for LLM inference to enable cudaGraph since there is no kernel launch bound issue.

**Comment by MartinMarciniszyn** [comment]
OK. Closing this issue.
