### ISSUE TITLE
unknow error in A800 in main branch

### ISSUE THREAD

**Issue by yoyopdc** [NVIDIA/TensorRT-LLM#654]
Hi , I had some problem in A800 when I ran the main branch  and it can work in A10, when I ran it in A800, the error come up 
<img width="851" alt="Screenshot 2023-12-13 at 9 47 47 PM" src="https://github.com/NVIDIA/TensorRT-LLM/assets/21274462/710bba58-824d-4e2c-bd5f-f855b75a1fb4">
cuda version: 12.2.   driver:535.129.03
here is my shell command,  
python3 build.py --model_dir /workspace/models/Llama-2-13b-hf/ --dtype float16 --remove_input_padding --use_gpt_attention_plugin float16 --enable_context_fmha --use_gemm_plugin float16 --max_batch_size 512 --max_input_len 1024 --max_output_len 512 --output_dir /workspace/models/trt-engine/llama2-13b-tp1 --world_size 1
The A800 have no problem in release branch.
And I found the main branch can't work in nvidia dirver 470 , So I must let the driver > 530?

**Comment by hello-11** [comment]
@yoyopdc Do you still have the problem? If not, we will close it soon.
