### ISSUE TITLE
An error when deploy trt engine with tritonserver/tensorrt-llm-backend: Serialization assertion stdVersionRead == kSERIALIZATION_VERSION failed.Version tag does not match

### ISSUE THREAD

**Issue by yangelaboy** [NVIDIA/TensorRT-LLM#660]
1. build docker image for tensorrt-llm v0.6.1
2. build llama-7b into trt engine
3. deploy the trt engine with tritonserver & tensorrt-llm-bakcend, but failed with error:
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/16263873/73834389-2dc6-44ac-b1a6-18889b3d918a)

**tritonserver image:** `nvcr.io/nvidia/tritonserver:23.10-trtllm-python-py3`

**start cmd**:  `docker run --gpus '"device=7"' --rm -p8000:8000 -p8001:8001 -p8002:8002  -v /home/work/models/triton_models:/tensorrtllm_backend nvcr.io/nvidia/tritonserver:23.10-trtllm-python-py3  tritonserver --model-repository=/tensorrtllm_backend --disable-auto-complete-config`

**Comment by byshiue** [comment]
That's because the TRT version of docker image of tensorrt-llm v0.6.1 and `nvcr.io/nvidia/tritonserver:23.10-trtllm-python-py3` are different. Please try building engine and run inference in same docker image first.

**Comment by byshiue** [comment]
Same to issue https://github.com/triton-inference-server/tensorrtllm_backend/issues/190. Close this one.
