### ISSUE TITLE
"output_ids" is missing in the returned dict.

### ISSUE THREAD

**Issue by sihanwang41** [NVIDIA/TensorRT-LLM#661]
Hi,
is the output_ids guaranteed to be exist in the returned dict?
I sometimes see
{'sequence_length': tensor([[1]], dtype=torch.int32), 'output_log_probs': tensor([[[0.]]]), 'cum_log_probs': tensor([[0.]])}

This is from v0.6.1. (I haven't got a chance to reproduce, but it sometimes happen with streaming, and always happen at the beginning of the output prompt.)

Thanks

**Comment by liuy-2019** [comment]
The same question. When I use fp8 quantiztion,I run the summarize.py.There is the traceback

Traceback (most recent call last):
  File "/workspace/TensorRT-LLM/examples/llama/../summarize.py", line 702, in <module>
    main(args)
  File "/workspace/TensorRT-LLM/examples/llama/../summarize.py", line 382, in main
    output, *_ = eval_trt_llm(datapoint,
  File "/workspace/TensorRT-LLM/examples/llama/../summarize.py", line 193, in eval_trt_llm
    outputs = runner.generate(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/model_runner_cpp.py", line 355, in generate
    return self._fill_output(multi_responses, output_ids, end_id,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/model_runner_cpp.py", line 411, in _fill_output
    output_ids = torch.tensor(output_ids,
TypeError: 'NoneType' object cannot be interpreted as an integer
--------------------------------------------------------------------------

**Comment by liuy-2019** [comment]
The same question. When I use fp8 quantiztion,I run the summarize.py.There is the traceback

```
Traceback (most recent call last):
File "/workspace/TensorRT-LLM/examples/llama/../summarize.py", line 702, in 
main(args)
File "/workspace/TensorRT-LLM/examples/llama/../summarize.py", line 382, in main
output, *_ = eval_trt_llm(datapoint,
File "/workspace/TensorRT-LLM/examples/llama/../summarize.py", line 193, in eval_trt_llm
outputs = runner.generate(
File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/model_runner_cpp.py", line 355, in generate
return self._fill_output(multi_responses, output_ids, end_id,
File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/model_runner_cpp.py", line 411, in _fill_output
output_ids = torch.tensor(output_ids,
TypeError: 'NoneType' object cannot be interpreted as an integer
```

**Comment by pupumao** [comment]
> The same question. When I use fp8 quantiztion,I run the summarize.py.There is the traceback
> 
> ```
> Traceback (most recent call last):
> File "/workspace/TensorRT-LLM/examples/llama/../summarize.py", line 702, in 
> main(args)
> File "/workspace/TensorRT-LLM/examples/llama/../summarize.py", line 382, in main
> output, *_ = eval_trt_llm(datapoint,
> File "/workspace/TensorRT-LLM/examples/llama/../summarize.py", line 193, in eval_trt_llm
> outputs = runner.generate(
> File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/model_runner_cpp.py", line 355, in generate
> return self._fill_output(multi_responses, output_ids, end_id,
> File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/model_runner_cpp.py", line 411, in _fill_output
> output_ids = torch.tensor(output_ids,
> TypeError: 'NoneType' object cannot be interpreted as an integer
> ```

@liuy-2019 any solution for this problem, i also met it

**Comment by hello-11** [comment]
@sihanwang41 Do you still have the problem? If not, we will close it soon.

**Comment by Slyne** [comment]
> > The same question. When I use fp8 quantiztion,I run the summarize.py.There is the traceback
> > ```
> > Traceback (most recent call last):
> > File "/workspace/TensorRT-LLM/examples/llama/../summarize.py", line 702, in 
> > main(args)
> > File "/workspace/TensorRT-LLM/examples/llama/../summarize.py", line 382, in main
> > output, *_ = eval_trt_llm(datapoint,
> > File "/workspace/TensorRT-LLM/examples/llama/../summarize.py", line 193, in eval_trt_llm
> > outputs = runner.generate(
> > File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/model_runner_cpp.py", line 355, in generate
> > return self._fill_output(multi_responses, output_ids, end_id,
> > File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/model_runner_cpp.py", line 411, in _fill_output
> > output_ids = torch.tensor(output_ids,
> > TypeError: 'NoneType' object cannot be interpreted as an integer
> > ```
> 
> [@liuy-2019](https://github.com/liuy-2019) any solution for this problem, i also met it

You probably need to set `end_id`. If you don't, the `end_id` would be None. The codeblock before the error line.
```
for beams in output_ids:
    for token_ids in beams:
        token_ids += [end_id] * (self.max_seq_len - len(token_ids))
```
