### ISSUE TITLE
Unable  to use AWQ 4-bit  with 4 A6000(LLama 70B)

### ISSUE THREAD

**Issue by busishengui** [NVIDIA/TensorRT-LLM#662]
```bash
python quantize.py --model_dir ./LLama 70B/ --dtype float16 --qformat int4_awq --export_path ./quantized_int4-awq --calib_size 32
```
ERROR LOG：
```log
OutOfMemoryError: CUDA out of memory. Tried to allocate 77.08 GiB. GPU 0 has a total capacty of 47.54
GiB of which 12.47 GiB is free. Process 906063 has 35.06 GiB memory in use. Of the allocated memory
34.64 GiB is allocated by PyTorch, and 127.84 MiB is reserved by PyTorch but unallocated. If reserved
but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation
for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
version:0.6.1

**Comment by Tracin** [comment]
Could you paste more error info? Like which line of code causes this error?

**Comment by busishengui** [comment]
> Could you paste more error info? Like which line of code causes this error?

f __name__ == "__main__":
    main()
search hit BOTTOM, continuing at TOP                                                                                                                 
│   1528 │   │                                                                                     │                                                                            
│   1529 │   │   try:                                                                              │                                                                            
│   1530 │   │   │   result = None                                                                 │                                                                            
│                                                                                                  │                                                                            
│ /usr/local/lib/python3.10/dist-packages/transformers/models/llama/modeling_llama.py:668 in       │                                                                            
│ forward                                                                                          │                                                                            
│                                                                                                  │                                                                            
│    665 │   │   │   attention_mask = torch.ones(                                                  │                                                                            
│    666 │   │   │   │   (batch_size, seq_length_with_past), dtype=torch.bool, device=inputs_embe  │                                                                            
│    667 │   │   │   )                                                                             │                                                                            
│ ❱  668 │   │   attention_mask = self._prepare_decoder_attention_mask(                            │                                                                            
│    669 │   │   │   attention_mask, (batch_size, seq_length), inputs_embeds, past_key_values_len  │                                                                            
│    670 │   │   )                                                                                 │                                                                            
│    671                                                                                           │                                                                            
│                                                                                                  │                                                                            
│ /usr/local/lib/python3.10/dist-packages/transformers/models/llama/modeling_llama.py:596 in       │                                                                            
│ _prepare_decoder_attention_mask                                                                  │                                                                            
│                                                                                                  │                                                                            
│    593 │   │   # [bsz, seq_len] -> [bsz, 1, tgt_seq_len, src_seq_len]                            │                                                                            
│    594 │   │   combined_attention_mask = None                                                    │                                                                            
│    595 │   │   if input_shape[-1] > 1:                                                           │                                                                            
│ ❱  596 │   │   │   combined_attention_mask = _make_causal_mask(                                  │                                                                            
│    597 │   │   │   │   input_shape,                                                              │                                                                            
│    598 │   │   │   │   inputs_embeds.dtype,                                                      │                                                                            
│    599 │   │   │   │   device=inputs_embeds.device,                                              │                                                                            
│                                                                                                  │                                                                            
│ /usr/local/lib/python3.10/dist-packages/transformers/models/llama/modeling_llama.py:50 in        │                                                                            
│ _make_causal_mask                                                                                │                                                                            
│                                                                                                  │                                                                            
│     47 │   Make causal mask used for bi-directional self-attention.                              │                                                                            
│     48 │   """                                                                                   │                                                                            
│     49 │   bsz, tgt_len = input_ids_shape                                                        │                                                                            
│ ❱   50 │   mask = torch.full((tgt_len, tgt_len), torch.finfo(dtype).min, device=device)          │                                                                            
│     51 │   mask_cond = torch.arange(mask.size(-1), device=device)                                │                                                                            
│     52 │   mask.masked_fill_(mask_cond < (mask_cond + 1).view(mask.size(-1), 1), 0)              │                                                                            
│     53 │   mask = mask.to(dtype)                                                                 │                                                                            
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯

**Comment by Tracin** [comment]
Please check this MR [293](https://github.com/NVIDIA/TensorRT-LLM/pull/293/files)
And also try reduce `--calib_size`.

**Comment by busishengui** [comment]
> Please check this MR [293](https://github.com/NVIDIA/TensorRT-LLM/pull/293/files) And also try reduce `--calib_size`.

Thanks for your repley，It works, but there is another problem [663](https://github.com/NVIDIA/TensorRT-LLM/issues/663),
OOM problem

**Comment by Hukongtao** [comment]
> > Please check this MR [293](https://github.com/NVIDIA/TensorRT-LLM/pull/293/files) And also try reduce `--calib_size`.
> 
> Thanks for your repley，It works, but there is another problem [663](https://github.com/NVIDIA/TensorRT-LLM/issues/663), OOM problem

I met the same problem. How do you solve it?
