### ISSUE TITLE
Tensor-LLM for BLIP-2 (ViT and Q-Former)

### ISSUE THREAD

**Issue by HaisongDing** [NVIDIA/TensorRT-LLM#664]
I notice in [here](https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/blip2/build_vit_qformer.py) that the ViT and Q-Former part do not leverage any new Tensor-LLM plugins (e.g., use_gemm_plugin and use_gpt_attention_plugin). Does it mean that the new Tensor-LLM plugins cannot be used to further speedup ViT further compared with Tensor-RT plugins?

**Comment by symphonylyh** [comment]
Hi @HaisongDing , ViT and Q-Former performance with native TensorRT should be decent already. TensorRT itself has many optimizations already, for example, BERT, native TensorRT performance is as good as --use_bert_plugin in most cases.

In BLIP2, although ViT and Q-Former are on native TensorRT, the LLM part is on TRT-LLM.

**Comment by HaisongDing** [comment]
Got it, thanks.
