### ISSUE TITLE
how to host llama 7b contineously

### ISSUE THREAD

**Issue by SDcodehub** [NVIDIA/TensorRT-LLM#668]
Hello all , working on tensorrt-llm to host the model, llama 7b-hf

At present, with run.py I can send input and get the output back

However, I want it to be permanently hosted

At present can see the memory usage only goes up during the inference, I am assuming the model will be loaded and inferencing is done.

I want the model to be loaded continuously,
Any suggestions?

**Comment by MrD005** [comment]
You can go through these 2 links that would be helpful to you to understand the process of how to use tensorRT compiled model with triton inference server
https://github.com/hamelsmu/llama-inference/tree/master/triton-tensorRT
https://developer.nvidia.com/blog/optimizing-inference-on-llms-with-tensorrt-llm-now-publicly-available/

**Comment by sagarsdesai** [comment]
Appreciate the help, yes it solves my problem, 
with triton I can keep the model loaded and using tensorrt-llm as backend.

need help with stress testing triton and  tensorrt-llm pair, will open new issue.

thanks
