### ISSUE TITLE
Speculative decoding

### ISSUE THREAD

**Issue by MrD005** [NVIDIA/TensorRT-LLM#671]
how to use speculative decoding?
is there any document for understanding it better?

added support in latest update

**Comment by jdemouth-nvidia** [comment]
We are working on the documentation - it should be published soon.

**Comment by MrD005** [comment]
@jdemouth-nvidia is there any ETA for that? in latest commit preview speculative decoding is showing but not able to understand the steps to run it

**Comment by schetlur-nv** [comment]
@MrD005 we please consider looking over https://github.com/triton-inference-server/tensorrtllm_backend/blob/main/inflight_batcher_llm/client/e2e_grpc_speculative_decoding_client.py which has an example of how to orchestrate between the draft and target models in a speculative decoding setup.
The broad idea here is that the draft and target models are decoupled and the generation is orchestrated by the client. There are more efficient ways of doing this we are working on, but this is probably the clearest/most flexible example we have.

**Comment by jxchenus** [comment]
Any update on this?  Can you share an ETA?

Any plan to support EAGLE speculative decoding?

**Comment by schetlur-nv** [comment]
BLS backend referred to in https://github.com/triton-inference-server/tensorrtllm_backend/blob/75b0964792fdc2a9e620b7a1edd71657d0d5cf62/inflight_batcher_llm/client/end_to_end_grpc_client.py#L227 and https://github.com/triton-inference-server/tensorrtllm_backend/blob/main/README.md#tensorrt_llm_bls is the optimized version. We have no immediate plan for EAGLE speculative decoding.

**Comment by jxchenus** [comment]
Thank you @schetlur-nv !  May I know which is the first release of TRT-LLM backend that includes this support?
