### ISSUE TITLE
Failed to build Llama-2-13b-hf engine with Lora adapter

### ISSUE THREAD

**Issue by manarshehadeh** [NVIDIA/TensorRT-LLM#673]
Running with release 0.6.1.

hitting assertion error:
`AssertionError: The value updated is not the same shape as the original. Updated: (32000, 5120), original: (0, 5120)`

Build command:
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/65428013/8d1dc06c-4c4f-4f77-8ac4-036837e77e2f)

Callstack:
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/65428013/ea203633-50cc-4691-bc71-e6353b6a848e)

**Comment by byshiue** [comment]
It looks the vocab size does not be passed in model successfully, you could check the vocab size in build.py before passing in model. 

Do you use the checkpoint we use in document?

**Comment by manarshehadeh** [comment]
Indeed, the vocab size is overridden by LoraConfig vocab size, value is 0 since the adapter config file doesn't contain a value for vocab size.
Can you give more clarity over what you mean with checkpoint in document?

**Comment by byshiue** [comment]
> Indeed, the vocab size is overridden by LoraConfig vocab size, value is 0 since the adapter config file doesn't contain a value for vocab size. Can you give more clarity over what you mean with checkpoint in document?

I mentioned 
```
https://huggingface.co/meta-llama/Llama-2-13b-hf
https://huggingface.co/hfl/chinese-llama-2-lora-13b
```

For different checkpoint, we don't verifiy and it might not work because they have different settings. 

You could try removing 
```python
args.vocab_size = lora_config.vocab_size
```

in `llama/build.py`.

**Comment by kaiyux** [comment]
The issue should be fixed in the latest main branch, please see https://github.com/NVIDIA/TensorRT-LLM/pull/754.

Closing. Please feel free to comment if you have any question, thanks!
