### ISSUE TITLE
libnvinfer_plugin_tensorrt_llm.so: cannot open shared object file: Not a directory

### ISSUE THREAD

**Issue by weedge** [NVIDIA/TensorRT-LLM#676]
run on colab A100
```shell
!git clone https://github.com/NVIDIA/TensorRT-LLM.git 

!cd TensorRT-LLM && git lfs install && python setup.py install \
  && pip install -r examples/bloom/requirements.txt

!pip uninstall -y tensorrt
!pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com tensorrt==9.2.0.post12.dev5

!cd TensorRT-LLM/examples/bloom \
  && rm -rf ./bloom/560M \
  && mkdir -p ./bloom/560M && git clone https://huggingface.co/bigscience/bloom-560m ./bloom/560M

# Single GPU on BLOOM 560M
!cd TensorRT-LLM/examples/bloom \
  && python convert_checkpoint.py --model_dir ./bloom/560M/ \
                --dtype float16 \
                --output_dir ./bloom/560M/trt_ckpt/fp16/1-gpu/

Traceback (most recent call last):
  File "/content/TensorRT-LLM/examples/bloom/convert_checkpoint.py", line 17, in <module>
    import tensorrt_llm
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm-0.6.1-py3.10-linux-x86_64.egg/tensorrt_llm/__init__.py", line 61, in <module>
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm-0.6.1-py3.10-linux-x86_64.egg/tensorrt_llm/_common.py", line 47, in _init
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm-0.6.1-py3.10-linux-x86_64.egg/tensorrt_llm/plugin/plugin.py", line 34, in _load_plugin_lib
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.10/dist-packages/tensorrt_llm-0.6.1-py3.10-linux-x86_64.egg/tensorrt_llm/libs/libnvinfer_plugin_tensorrt_llm.so: cannot open shared object file: Not a directory

```

**Comment by byshiue** [comment]
Do you use docker image built on latest codes? If yes, could you share how do you build the docker?

**Comment by weedge** [comment]
@byshiue  don't use docker, just run on google-colab ... colab maybe don't run dockerd

**Comment by byshiue** [comment]
I don't see you build the tensorrt_llm repo in your scripts (like `python3 build_wheel.py && pip install xxx.whl`. Please refer the document here https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/installation.md#build-tensorrt-llm-1.

**Comment by weedge** [comment]
run this scripts
```
%%bash
cd TensorRT-LLM && \
  python3 ./scripts/build_wheel.py --python_bindings --trt_root /usr/local/lib/python3.10/dist-packages/tensorrt_libs/ --clean \
  && pip install ./build/tensorrt_llm*.whl

```shell

```
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com/
Requirement already satisfied: accelerate==0.20.3 in /usr/local/lib/python3.10/dist-packages/accelerate-0.20.3-py3.10.egg (from -r requirements.txt (line 1)) (0.20.3)
Requirement already satisfied: build in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 2)) (1.0.3)
Requirement already satisfied: colored in /usr/local/lib/python3.10/dist-packages/colored-2.2.3-py3.10.egg (from -r requirements.txt (line 3)) (2.2.3)
Requirement already satisfied: cuda-python==12.2.0 in /usr/local/lib/python3.10/dist-packages/cuda_python-12.2.0-py3.10-linux-x86_64.egg (from -r requirements.txt (line 4)) (12.2.0)
Requirement already satisfied: diffusers==0.15.0 in /usr/local/lib/python3.10/dist-packages/diffusers-0.15.0-py3.10.egg (from -r requirements.txt (line 5)) (0.15.0)
Requirement already satisfied: lark in /usr/local/lib/python3.10/dist-packages/lark-1.1.8-py3.10.egg (from -r requirements.txt (line 6)) (1.1.8)
Requirement already satisfied: mpi4py in /usr/local/lib/python3.10/dist-packages/mpi4py-3.1.5-py3.10-linux-x86_64.egg (from -r requirements.txt (line 7)) (3.1.5)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 8)) (1.23.5)
Requirement already satisfied: onnx>=1.12.0 in /usr/local/lib/python3.10/dist-packages/onnx-1.15.0-py3.10-linux-x86_64.egg (from -r requirements.txt (line 9)) (1.15.0)
Requirement already satisfied: polygraphy in /usr/local/lib/python3.10/dist-packages/polygraphy-0.49.0-py3.10.egg (from -r requirements.txt (line 10)) (0.49.0)
Requirement already satisfied: sentencepiece>=0.1.99 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 11)) (0.1.99)
Requirement already satisfied: tensorrt>=8.6.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 12)) (9.2.0.post12.dev5)
Requirement already satisfied: torch in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 13)) (2.1.0+cu121)
Requirement already satisfied: transformers==4.33.1 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 14)) (4.33.1)
Requirement already satisfied: wheel in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 15)) (0.42.0)
Requirement already satisfied: optimum in /usr/local/lib/python3.10/dist-packages/optimum-1.16.1-py3.10.egg (from -r requirements.txt (line 16)) (1.16.1)
Requirement already satisfied: evaluate in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 17)) (0.4.1)
Requirement already satisfied: datasets in /usr/local/lib/python3.10/dist-packages (from -r requirements-dev.txt (line 2)) (2.14.7)
Requirement already satisfied: einops in /usr/local/lib/python3.10/dist-packages (from -r requirements-dev.txt (line 3)) (0.7.0)
Requirement already satisfied: graphviz in /usr/local/lib/python3.10/dist-packages (from -r requirements-dev.txt (line 5)) (0.20.1)
Requirement already satisfied: mypy in /usr/local/lib/python3.10/dist-packages (from -r requirements-dev.txt (line 6)) (1.7.1)
Requirement already satisfied: parameterized in /usr/local/lib/python3.10/dist-packages (from -r requirements-dev.txt (line 7)) (0.9.0)
Requirement already satisfied: pre-commit in /usr/local/lib/python3.10/dist-packages (from -r requirements-dev.txt (line 8)) (3.6.0)
Requirement already satisfied: pybind11-stubgen in /usr/local/lib/python3.10/dist-packages (from -r requirements-dev.txt (line 9)) (2.4.2)
Requirement already satisfied: pynvml>=11.5.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements-dev.txt (line 10)) (11.5.0)
Requirement already satisfied: pytest-cov in /usr/local/lib/python3.10/dist-packages (from -r requirements-dev.txt (line 11)) (4.1.0)
Requirement already satisfied: pytest-forked in /usr/local/lib/python3.10/dist-packages (from -r requirements-dev.txt (line 12)) (1.6.0)
Requirement already satisfied: pytest-xdist in /usr/local/lib/python3.10/dist-packages (from -r requirements-dev.txt (line 13)) (3.5.0)
Requirement already satisfied: rouge_score in /usr/local/lib/python3.10/dist-packages (from -r requirements-dev.txt (line 14)) (0.1.2)
Requirement already satisfied: typing-extensions==4.8.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements-dev.txt (line 16)) (4.8.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from accelerate==0.20.3->-r requirements.txt (line 1)) (23.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from accelerate==0.20.3->-r requirements.txt (line 1)) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.10/dist-packages (from accelerate==0.20.3->-r requirements.txt (line 1)) (6.0.1)
Requirement already satisfied: cython in /usr/local/lib/python3.10/dist-packages (from cuda-python==12.2.0->-r requirements.txt (line 4)) (3.0.6)
Requirement already satisfied: Pillow in /usr/local/lib/python3.10/dist-packages (from diffusers==0.15.0->-r requirements.txt (line 5)) (9.4.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from diffusers==0.15.0->-r requirements.txt (line 5)) (3.13.1)
Requirement already satisfied: huggingface-hub>=0.13.2 in /usr/local/lib/python3.10/dist-packages (from diffusers==0.15.0->-r requirements.txt (line 5)) (0.19.4)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.10/dist-packages (from diffusers==0.15.0->-r requirements.txt (line 5)) (7.0.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from diffusers==0.15.0->-r requirements.txt (line 5)) (2023.6.3)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from diffusers==0.15.0->-r requirements.txt (line 5)) (2.31.0)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in /usr/local/lib/python3.10/dist-packages (from transformers==4.33.1->-r requirements.txt (line 14)) (0.13.3)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from transformers==4.33.1->-r requirements.txt (line 14)) (0.4.1)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers==4.33.1->-r requirements.txt (line 14)) (4.66.1)
Requirement already satisfied: pyproject_hooks in /usr/local/lib/python3.10/dist-packages (from build->-r requirements.txt (line 2)) (1.0.0)
Requirement already satisfied: tomli>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from build->-r requirements.txt (line 2)) (2.0.1)
Requirement already satisfied: protobuf>=3.20.2 in /usr/local/lib/python3.10/dist-packages (from onnx>=1.12.0->-r requirements.txt (line 9)) (4.23.4)
Requirement already satisfied: tensorrt-libs==9.2.0.post12.dev5 in /usr/local/lib/python3.10/dist-packages (from tensorrt>=8.6.0->-r requirements.txt (line 12)) (9.2.0.post12.dev5)
Requirement already satisfied: tensorrt-bindings==9.2.0.post12.dev5 in /usr/local/lib/python3.10/dist-packages (from tensorrt>=8.6.0->-r requirements.txt (line 12)) (9.2.0.post12.dev5)
Requirement already satisfied: nvidia-cuda-runtime-cu12 in /usr/local/lib/python3.10/dist-packages (from tensorrt-libs==9.2.0.post12.dev5->tensorrt>=8.6.0->-r requirements.txt (line 12)) (12.3.101)
Requirement already satisfied: nvidia-cudnn-cu12 in /usr/local/lib/python3.10/dist-packages (from tensorrt-libs==9.2.0.post12.dev5->tensorrt>=8.6.0->-r requirements.txt (line 12)) (8.9.7.29)
Requirement already satisfied: nvidia-cublas-cu12 in /usr/local/lib/python3.10/dist-packages (from tensorrt-libs==9.2.0.post12.dev5->tensorrt>=8.6.0->-r requirements.txt (line 12)) (12.3.4.1)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch->-r requirements.txt (line 13)) (1.12)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch->-r requirements.txt (line 13)) (3.2.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch->-r requirements.txt (line 13)) (3.1.2)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch->-r requirements.txt (line 13)) (2023.6.0)
Requirement already satisfied: triton==2.1.0 in /usr/local/lib/python3.10/dist-packages (from torch->-r requirements.txt (line 13)) (2.1.0)
Requirement already satisfied: coloredlogs in /usr/local/lib/python3.10/dist-packages/coloredlogs-15.0.1-py3.10.egg (from optimum->-r requirements.txt (line 16)) (15.0.1)
Requirement already satisfied: dill in /usr/local/lib/python3.10/dist-packages (from evaluate->-r requirements.txt (line 17)) (0.3.7)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from evaluate->-r requirements.txt (line 17)) (1.5.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.10/dist-packages (from evaluate->-r requirements.txt (line 17)) (3.4.1)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.10/dist-packages (from evaluate->-r requirements.txt (line 17)) (0.70.15)
Requirement already satisfied: responses<0.19 in /usr/local/lib/python3.10/dist-packages (from evaluate->-r requirements.txt (line 17)) (0.18.0)
Requirement already satisfied: pyarrow>=8.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets->-r requirements-dev.txt (line 2)) (10.0.1)
Requirement already satisfied: pyarrow-hotfix in /usr/local/lib/python3.10/dist-packages (from datasets->-r requirements-dev.txt (line 2)) (0.6)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets->-r requirements-dev.txt (line 2)) (3.9.1)
Requirement already satisfied: mypy-extensions>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from mypy->-r requirements-dev.txt (line 6)) (1.0.0)
Requirement already satisfied: cfgv>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from pre-commit->-r requirements-dev.txt (line 8)) (3.4.0)
Requirement already satisfied: identify>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from pre-commit->-r requirements-dev.txt (line 8)) (2.5.33)
Requirement already satisfied: nodeenv>=0.11.1 in /usr/local/lib/python3.10/dist-packages (from pre-commit->-r requirements-dev.txt (line 8)) (1.8.0)
Requirement already satisfied: virtualenv>=20.10.0 in /usr/local/lib/python3.10/dist-packages (from pre-commit->-r requirements-dev.txt (line 8)) (20.25.0)
Requirement already satisfied: pytest>=4.6 in /usr/local/lib/python3.10/dist-packages (from pytest-cov->-r requirements-dev.txt (line 11)) (7.4.3)
Requirement already satisfied: coverage[toml]>=5.2.1 in /usr/local/lib/python3.10/dist-packages (from pytest-cov->-r requirements-dev.txt (line 11)) (7.3.3)
Requirement already satisfied: py in /usr/local/lib/python3.10/dist-packages (from pytest-forked->-r requirements-dev.txt (line 12)) (1.11.0)
Requirement already satisfied: execnet>=1.1 in /usr/local/lib/python3.10/dist-packages (from pytest-xdist->-r requirements-dev.txt (line 13)) (2.0.2)
Requirement already satisfied: absl-py in /usr/local/lib/python3.10/dist-packages (from rouge_score->-r requirements-dev.txt (line 14)) (1.4.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (from rouge_score->-r requirements-dev.txt (line 14)) (3.8.1)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.10/dist-packages (from rouge_score->-r requirements-dev.txt (line 14)) (1.16.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->-r requirements-dev.txt (line 2)) (23.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->-r requirements-dev.txt (line 2)) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->-r requirements-dev.txt (line 2)) (1.9.4)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->-r requirements-dev.txt (line 2)) (1.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->-r requirements-dev.txt (line 2)) (1.3.1)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->-r requirements-dev.txt (line 2)) (4.0.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from nodeenv>=0.11.1->pre-commit->-r requirements-dev.txt (line 8)) (67.7.2)
Requirement already satisfied: iniconfig in /usr/local/lib/python3.10/dist-packages (from pytest>=4.6->pytest-cov->-r requirements-dev.txt (line 11)) (2.0.0)
Requirement already satisfied: pluggy<2.0,>=0.12 in /usr/local/lib/python3.10/dist-packages (from pytest>=4.6->pytest-cov->-r requirements-dev.txt (line 11)) (1.3.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc8 in /usr/local/lib/python3.10/dist-packages (from pytest>=4.6->pytest-cov->-r requirements-dev.txt (line 11)) (1.2.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->diffusers==0.15.0->-r requirements.txt (line 5)) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->diffusers==0.15.0->-r requirements.txt (line 5)) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->diffusers==0.15.0->-r requirements.txt (line 5)) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->diffusers==0.15.0->-r requirements.txt (line 5)) (2023.11.17)
Requirement already satisfied: distlib<1,>=0.3.7 in /usr/local/lib/python3.10/dist-packages (from virtualenv>=20.10.0->pre-commit->-r requirements-dev.txt (line 8)) (0.3.8)
Requirement already satisfied: platformdirs<5,>=3.9.1 in /usr/local/lib/python3.10/dist-packages (from virtualenv>=20.10.0->pre-commit->-r requirements-dev.txt (line 8)) (4.1.0)
Requirement already satisfied: humanfriendly>=9.1 in /usr/local/lib/python3.10/dist-packages/humanfriendly-10.0-py3.10.egg (from coloredlogs->optimum->-r requirements.txt (line 16)) (10.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.10/dist-packages (from importlib-metadata->diffusers==0.15.0->-r requirements.txt (line 5)) (3.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch->-r requirements.txt (line 13)) (2.1.3)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk->rouge_score->-r requirements-dev.txt (line 14)) (8.1.7)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk->rouge_score->-r requirements-dev.txt (line 14)) (1.3.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas->evaluate->-r requirements.txt (line 17)) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->evaluate->-r requirements.txt (line 17)) (2023.3.post1)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch->-r requirements.txt (line 13)) (1.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12 in /usr/local/lib/python3.10/dist-packages (from nvidia-cudnn-cu12->tensorrt-libs==9.2.0.post12.dev5->tensorrt>=8.6.0->-r requirements.txt (line 12)) (12.3.103)
-- The CXX compiler identification is GNU 11.4.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- NVTX is disabled
-- Importing batch manager
-- Building PyTorch
-- Building Google tests
-- Building benchmarks
-- Looking for a CUDA compiler
-- Looking for a CUDA compiler - /usr/local/cuda/bin/nvcc
-- CUDA compiler: /usr/local/cuda/bin/nvcc
-- GPU architectures: 70-real;80-real;86-real;89-real;90-real
-- The C compiler identification is GNU 11.4.0
-- The CUDA compiler identification is NVIDIA 12.2.140
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Found CUDAToolkit: /usr/local/cuda/include (found version "12.2.140") 
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- CUDA library status:
--     version: 12.2.140
--     libraries: /usr/local/cuda/lib64
--     include path: /usr/local/cuda/targets/x86_64-linux/include
-- ========================= Importing and creating target nvinfer ==========================
-- Looking for library nvinfer
-- Library that was found nvinfer_LIB_PATH-NOTFOUND
-- ==========================================================================================
-- CUDAToolkit_VERSION 12.2 is greater or equal than 11.0, enable -DENABLE_BF16 flag
-- CUDAToolkit_VERSION 12.2 is greater or equal than 11.8, enable -DENABLE_FP8 flag
-- Found MPI_C: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so (found version "3.1") 
-- Found MPI_CXX: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- COMMON_HEADER_DIRS: /content/TensorRT-LLM/cpp;/usr/local/cuda/include
-- Found Python3: /usr/local/bin/python (found version "3.10.12") found components: Interpreter Development Development.Module Development.Embed 
-- USE_CXX11_ABI is set by python Torch to 0
-- TORCH_CUDA_ARCH_LIST: 7.0;8.0;8.6;8.9;9.0
-- Found Python executable at /usr/local/bin/python
-- Found Python libraries at /usr/lib/x86_64-linux-gnu
-- Found CUDA: /usr/local/cuda (found version "12.2") 
-- Found CUDAToolkit: /usr/local/cuda/include (found version "12.2.140") 
-- Caffe2: CUDA detected: 12.2
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 12.2
-- /usr/local/cuda-12.2/targets/x86_64-linux/lib/libnvrtc.so shorthash is 000ca627
-- USE_CUDNN is set to 0. Compiling without cuDNN support
-- USE_CUSPARSELT is set to 0. Compiling without cuSPARSELt support
-- Added CUDA NVCC flags for: -gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_89,code=sm_89;-gencode;arch=compute_90,code=sm_90
CMake Warning at /usr/local/lib/python3.10/dist-packages/torch/share/cmake/Torch/TorchConfig.cmake:22 (message):
  static library kineto_LIBRARY-NOTFOUND not found.
Call Stack (most recent call first):
  /usr/local/lib/python3.10/dist-packages/torch/share/cmake/Torch/TorchConfig.cmake:127 (append_torchlib_if_found)
  CMakeLists.txt:337 (find_package)


-- Found Torch: /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch.so  
-- TORCH_CXX_FLAGS: -D_GLIBCXX_USE_CXX11_ABI=0
CMake Error at CMakeLists.txt:362 (file):
  file STRINGS file
  "/usr/local/lib/python3.10/dist-packages/tensorrt_libs//include/NvInferVersion.h"
  cannot be read.


CMake Error at CMakeLists.txt:365 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.


CMake Error at CMakeLists.txt:367 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.


CMake Error at CMakeLists.txt:365 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.


CMake Error at CMakeLists.txt:367 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.


CMake Error at CMakeLists.txt:365 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.


CMake Error at CMakeLists.txt:367 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.


CMake Error at CMakeLists.txt:365 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.


CMake Error at CMakeLists.txt:367 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.


-- Building for TensorRT version: .., library version: 
-- Using MPI_C_INCLUDE_DIRS: /usr/lib/x86_64-linux-gnu/openmpi/include;/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi
-- Using MPI_C_LIBRARIES: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so
-- CMAKE_SYSTEM_PROCESSOR: x86_64
-- Operating System: ubuntu, 22.04
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pybind11'
ERRORpybind11 CMake directory not found.
CMake Error at tensorrt_llm/pybind/CMakeLists.txt:25 (find_package):
  By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "pybind11",
  but CMake did not find one.

  Could not find a package configuration file provided by "pybind11" with any
  of the following names:

    pybind11Config.cmake
    pybind11-config.cmake

  Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
  "pybind11_DIR" to a directory containing one of the above files.  If
  "pybind11" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "/content/TensorRT-LLM/./scripts/build_wheel.py", line 306, in <module>
    main(**vars(args))
  File "/content/TensorRT-LLM/./scripts/build_wheel.py", line 160, in main
    build_run(
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cmake -DCMAKE_BUILD_TYPE="Release" -DBUILD_PYT="ON" -DBUILD_PYBIND="ON"  -DTRT_LIB_DIR=/usr/local/lib/python3.10/dist-packages/tensorrt_libs//targets/x86_64-linux-gnu/lib -DTRT_INCLUDE_DIR=/usr/local/lib/python3.10/dist-packages/tensorrt_libs//include  -S "/content/TensorRT-LLM/cpp"' returned non-zero exit status 1.
```

env:
Linux 9988c5cb9588 6.1.58+ #1 SMP PREEMPT_DYNAMIC Sat Nov 18 15:31:17 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Aug_15_22:02:13_PDT_2023
Cuda compilation tools, release 12.2, V12.2.140
Build cuda_12.2.r12.2/compiler.33191640_0

**Comment by weedge** [comment]
use tensorrt 9.2.0
!pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com tensorrt==9.2.0.post12.dev5

**Comment by byshiue** [comment]
It is a dependent packages issues, we will try to help but we might not able to provide too many help. That's why we suggest using the docker image at the beginning, it is helpful to align the environment after that.

**Comment by riyaj8888** [comment]
i am using docker image but i am also facing the same issue duiring the above scripts to build.

/bin/bash: line 1: cmake: command not found
Traceback (most recent call last):
  File "/app/TensorRT-LLM/./scripts/build_wheel.py", line 306, in <module>
    main(**vars(args))
  File "/app/TensorRT-LLM/./scripts/build_wheel.py", line 160, in main
    build_run(
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cmake -DCMAKE_BUILD_TYPE="Release" -DBUILD_PYT="ON" -DBUILD_PYBIND="OFF"  -DTRT_LIB_DIR=/usr/local/tensorrt/targets/x86_64-linux-gnu/lib -DTRT_INCLUDE_DIR=/usr/local/tensorrt/include  -S "/app/TensorRT-LLM/cpp"' returned non-zero exit status 127.

**Comment by riyaj8888** [comment]
following exact steps from here

https://github.com/triton-inference-server/tensorrtllm_backend

**Comment by byshiue** [comment]
Please share your scripts directly. There are many scripts in the document and we are not sure which do you follow.
