### ISSUE TITLE
Processing MPT-30B fails.

### ISSUE THREAD

**Issue by Borell1** [NVIDIA/TensorRT-LLM#678]
Hi,

Using the exact examples given for MPT-30B results in an exception.

Execution of the following:
> python3 build.py --world_size=4 --parallel_build --max_batch_size 64 --max_input_len 512 --max_output_len 64 --use_gpt_attention_plugin --use_gemm_plugin --model_dir=.cache/tensorrt/ft_ckpts/mpt-30b/fp16/4-gpu/ --output_dir .cache/tensorrt/models/mpt-30b/fp16/4-gpu

Results in:
[12/16/2023-17:48:53] [TRT-LLM] [I] Serializing engine to .cache/tensorrt/models/mpt-30b/fp16/4-gpu/gpt_float16_tp4_rank3.engine...
Traceback (most recent call last):
  File "/root/TensorRT-LLM/examples/mpt/build.py", line 615, in <module>
    run_build()
  File "/root/TensorRT-LLM/examples/mpt/build.py", line 603, in run_build
    mp.spawn(build, nprocs=args.world_size, args=(args, ))
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 197, in start_processes
    while not context.join():
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 140, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with signal SIGKILL

The following 4 files are created in the output directory:
-rw-rw----  1 root root       1379 Dec 16 17:48 config.json
-rw-rw----  1 root root          0 Dec 16 17:48 gpt_float16_tp4_rank0.engine
-rw-rw----  1 root root  283009024 Dec 16 17:49 gpt_float16_tp4_rank1.engine
-rw-rw----  1 root root 2719207424 Dec 16 17:49 gpt_float16_tp4_rank2.engine
-rw-rw----  1 root root 5135630336 Dec 16 17:49 gpt_float16_tp4_rank3.engine

Please also note that while the process shows "Total time of building gpt_float16_tp4_rank0.engine: 00:01:22", bytes for rank 0 engine are 0.

Can anyone help? 

Thanks

**Comment by byshiue** [comment]
What CPU RAM do you have? Also, could you try removing `--parallel_build`?

**Comment by Borell1** [comment]
byshiue thanks for the reply.

The process is running on a DGX Workstation with 263818780 kB RAM, 20 cores, and 4 V100s (each with 32GB).

I can remove parallel_build, but can you please explain its purpose and why should I remove it? Instructions at https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/mpt, which I followed, includes that parameter.

**Comment by Borell1** [comment]
Under examples/falcon I found the explanation for parallel_build as:
"Normally build.py only requires a single GPU, but if you've already got all the GPUs needed while inferencing, you could enable parallel building to make the engine building process faster by adding --parallel_build argument. Please note that currently parallel_build feature only supports single node."
I will attempt build.py without --paralell_build, hopefully will resolve the mutiprocessing issue by running on a single GPU. Loading into memory however may become an issue.

**Comment by jdemouth-nvidia** [comment]
Thanks for trying other options. Please, keep us posted.

**Comment by Borell1** [comment]
Removing --paralell_build parameter as suggested for build.py allows the process to complete without error. The following 5 files are created: config.json 1383 bytes, gpt_float16_tp4_rank0.engine, gpt_float16_tp4_rank1.engine, gpt_float16_tp4_rank2.engine, and gpt_float16_tp4_rank3.engine 15712964060 bytes each.
The process used checkpoints converted by:
python convert_hf_mpt_to_ft.py -i mosaicml/mpt-30b-instruct -o /root/tensorrt_llm/ft_ckpts/mpt-30b-instruct/fp16 --tensor_parallelism 4 -t float16

Currently I am running "run.py" to determine if the tensorrt conversion was correct. Seems to take a very large amount of time.

In the meantime and in order to understand better TensorRT-LLM, I would like to present some questions/issues:
1. Removal of --paralell_build parameter seems to solve the original reported problem. Is this an issue to be resolved in future code, or it is a platform issue with multiprocessing on the DGX workstation?
2. Using --tensor_parallelism 4 for "convert_hf_mpt_to_ft.py" works as presented in the MPT example. Setting --tensor_parallelism to 2 or to 1 results in engine files built for 2 and 1 GPU respectively, but results in error during the build.py process:
	Traceback (most recent call last):
	  File "/root/tensorrt_llm/TensorRT-LLM/examples/mpt/build.py", line 615, in <module>
	    run_build()
	  File "/root/tensorrt_llm/TensorRT-LLM/examples/mpt/build.py", line 607, in run_build
	    build(0, args)
	  File "/root/tensorrt_llm/TensorRT-LLM/examples/mpt/build.py", line 573, in build
	    engine = build_rank_engine(builder, builder_config, engine_name,
	  File "/root/tensorrt_llm/TensorRT-LLM/examples/mpt/build.py", line 451, in build_rank_engine
	    load_from_ft(tensorrt_llm_gpt,
	  File "/root/tensorrt_llm/TensorRT-LLM/examples/mpt/weight.py", line 234, in load_from_ft
	    t = fromfile(
	  File "/root/tensorrt_llm/TensorRT-LLM/examples/mpt/weight.py", line 113, in fromfile
	    t = t.reshape(shape)
	ValueError: cannot reshape array of size 77070336 into shape (7168,5376)
Is there a manner to build for 1 or 2 GPUs?
3. The tensorrt container created is loaded with NVIDIA_VISIBLE_DEVICES=2,3 on DGX Workstation with 4 V100s. The build.py process while it shows loaded on GPU 2, it does not seem to run there (as attested by nvidia-smi). It appears to execute off CPU. Is this as expected, i.e., build.py process executes all in CPU?

**Comment by hello-11** [comment]
@Borell1 Do you still have the problem? If not, we will close it soon.
