### ISSUE TITLE
llama-3b: Size per head is not a multiple of X

### ISSUE THREAD

**Issue by shixianc** [NVIDIA/TensorRT-LLM#679]
I met an error: "Size per head is not a multiple of X" for openllama-3b model with TP=4 (pp=1).

build.py commands include:
```
"--enable_context_fmha",
"--paged_kv_cache",
"--remove_input_padding",
"--use_gemm_plugin", "bfloat16",
"--use_gpt_attention_plugin", "bfloat16"
```

Searching the error in the code base, seems related to [kv cache setup](https://github.com/NVIDIA/TensorRT-LLM/blob/a75618df24e97ecf92b8899ca3c229c4b8097dda/cpp/tensorrt_llm/plugins/gptAttentionCommon/gptAttentionCommon.cpp#L800). 

The model hidden_size is 3200, and has 32 heads, so size_per_head should be 100. From the code X can be 4 or 8, so X must be 8 which can't divide 100. But what does X mean in this context?

**Comment by byshiue** [comment]
head size 100 is not supported. You can see supported head size in https://github.com/NVIDIA/TensorRT-LLM/tree/main/cpp/tensorrt_llm/kernels/decoderMaskedMultiheadAttention.
