### ISSUE TITLE
Llama 2 with LoRA

### ISSUE THREAD

**Issue by JosephChenHub** [NVIDIA/TensorRT-LLM#68]
is there any example to convert llama2  model fine-tuned with LoRA to TensorRT-LLM ?

**Comment by jdemouth-nvidia** [comment]
Hi @JosephChenHub ,

We do not have such an example. I'm marking it as a request for a future release of TensorRT-LLM. We will keep you posted.

Thanks,
Julien

**Comment by GayHub1010** [comment]
is the current inference framework support loading multiple lora modules and could change for each request?

**Comment by juney-nvidia** [comment]
@GayHub1010  if my understanding is correct, loading different lora modules means for different request, the same model structure is used, but with different model weights?  If so, there are multiple ways of doing this:

- Using the "[refit](https://github.com/NVIDIA/TensorRT-LLM/blob/1c4a0ee24cb0480c20a721c4bc6a77fc51644a22/docs/source/architecture.md#L134)" functionality (under-the-hood supported by TensorRT) to use the same TRT engine, with different model weights.
- In case the "refit" time is longer than your expectation, you can wrap some weight refreshing logics in TensorRT plugin and integrate into TensorRT-LLM runtime. 

June

**Comment by GayHub1010** [comment]
> @GayHub1010 if my understanding is correct, loading different lora modules means for different request, the same model structure is used, but with different model weights? If so, there are multiple ways of doing this:
> 
> * Using the "[refit](https://github.com/NVIDIA/TensorRT-LLM/blob/1c4a0ee24cb0480c20a721c4bc6a77fc51644a22/docs/source/architecture.md#L134)" functionality (under-the-hood supported by TensorRT) to use the same TRT engine, with different model weights.
> * In case the "refit" time is longer than your expectation, you can wrap some weight refreshing logics in TensorRT plugin and integrate into TensorRT-LLM runtime.
> 
> June

we have multiple small lora module(low rank matrix multiply，each with about 0.1% parameters of base model) and one large base model to reduce gpu memory cost。when inference, the weight should be is W + a*b(lora module, a, b are lora weights with low rank matrix multiplication) for gate_proj, up_proj, down_proj, qkv_proj or other layers, the inference result for these layers is y=Wx+a*bx, it is difficult to change the weights because it is stored with low_rank, also if some layer is fused, it can be difficult to work. It seems that  we should pass which lora module to compute for requests, is it possible?  Maybe many plugins should be written and the choice of which lora module to compute should be written in the kernel? The tensorrt may have many fusions to make lora not work

**Comment by jdemouth-nvidia** [comment]
Lora will essentially update the weights of the GEMMs (Matmuls). It should not be a hard problem to update those weights. However, one challenge is indeed to make sure it works well with kernel/GEMM fusion. 

Today, TensorRT-LLM uses a plugin for FP16/BF16 as well as INT8 and INT4 Matmuls so for those cases, there's no real problem, it'll be sufficient to update the weights of those plugins. If that's your use case, I'm pretty sure you can change the plugin for GEMM to read the weights from an input tensor.

The only case where TensorRT-LLM relies on Matmul fusions in TensorRT is for FP8. For that as well, I think it should be possible to use a "dynamic" tensor to pass weights to the engine but I would take that with a grain of salt. 

@juney-nvidia and I will assign the task to someone in our team and see what can be done to enable LoRA as quickly as possible.

**Comment by GayHub1010** [comment]
> Lora will essentially update the weights of the GEMMs (Matmuls). It should not be a hard problem to update those weights. However, one challenge is indeed to make sure it works well with kernel/GEMM fusion.
> 
> Today, TensorRT-LLM uses a plugin for FP16/BF16 as well as INT8 and INT4 Matmuls so for those cases, there's no real problem, it'll be sufficient to update the weights of those plugins. If that's your use case, I'm pretty sure you can change the plugin for GEMM to read the weights from an input tensor.
> 
> The only case where TensorRT-LLM relies on Matmul fusions in TensorRT is for FP8. For that as well, I think it should be possible to use a "dynamic" tensor to pass weights to the engine but I would take that with a grain of salt.
> 
> @juney-nvidia and I will assign the task to someone in our team and see what can be done to enable LoRA as quickly as possible.

Thanks for answering, Lora will essentially update the weights of the GEMMs，however，in order to merge weights，we should compute a*b or store the result in gpu, the gpu memory cost is high, losting the advantage of lora. could we pass single a,b(different lora has different a b) and do the computation inside the layer? https://github.com/triton-inference-server/server/issues/5968

**Comment by jdemouth-nvidia** [comment]
Nothing prevents us from doing that in a plugin. We could have a kernel that updates the GEMM weights by computing the low-rank product. Then, run the GEMM and “clean up” the weights immediately or later. Does that make sense?

**Comment by GayHub1010** [comment]
> Nothing prevents us from doing that in a plugin. We could have a kernel that updates the GEMM weights by computing the low-rank product. Then, run the GEMM and “clean up” the weights immediately or later. Does that make sense?

Yes, Plugin will ok if multiple lora weights are loaded and decisions about which lora to compute is in the plugin, hope to see examples for that, thanks

**Comment by sanfuyee** [comment]
I also want the lora support

**Comment by kfswain** [comment]
Hey all! I see this marked as completed, is there a PR or different issue I could use to track this support? Thanks!

**Comment by byshiue** [comment]
LoRA is supported since v0.6.1, and continuing improving the feature in many MRs. You can see the release notes in https://github.com/NVIDIA/TensorRT-LLM/discussions?discussions_q=is%3Aopen+lora
