### ISSUE TITLE
GPU Memory Persistence Post-Model Deletion

### ISSUE THREAD

**Issue by robosina** [NVIDIA/TensorRT-LLM#681]
I'm setting up a benchmark like the one below:

```python

for config in tqdm(model_configs, desc="Benchmarking"):
    args.batch_size = config.batch_size
    args.num_beams = config.beam_width
    model = WhisperTRTLLM(config.model_path, args.debug, args.assets_dir)

    # Some benchmarking here

    model = None
    del model
    gc.collect()
```

As you can see, I create a model, then delete it and create another one. However, it looks like the deleted model leaves some undeleted gpu memory. When I check with `nvidia-smi`, there's still some memory in use. This might be due to leftover intermediate tensors or KV cache values from the generation step. Just wanted to flag this issue.

**Comment by byshiue** [comment]
This is a known case becuase the memory is managed by pytorch memory pool. You should check the memory usage by pytorch api, instead of nvidia-smi.
