### ISSUE TITLE
Question regarding using 8 bit gptq quantized models

### ISSUE THREAD

**Issue by AbhinavDutta** [NVIDIA/TensorRT-LLM#683]
I built the quantized weights using 8 bit GPTQ ( python llama.py ./tmp/llama/7B/ c4 --wbits 8 --true-sequential --groupsize 128 --save_safetensors ./llama-7b-4bit-gs128.safetensors )

Now, in order to build engines from checkpoints, I need to use the tags --use_weight_only --weight_only_precision XXXX. I am required to choose from 'int8', 'int4', 'int4_awq', 'int4_gptq' . Can you let me know if int8 is the right option to use ? What is the difference between using int4 int4_gptq int4_awq ? Does the absence of int8_gptq mean that using 8 bit gptq will lead to poor results ?

**Comment by byshiue** [comment]
For int8, we only support pure int8 only because the accuracy is good enough in our experiement. You couldn't run int8 gptq model by int8 directly. 

int4, int4_gptq and int4_awq are different quantization methods.
