### ISSUE TITLE
is there any plan to support int64 in 'tensorrt_llm/cpp/tensorrt_llm/kernels/kvCacheUtils.h'?

### ISSUE THREAD

**Issue by xinji1** [NVIDIA/TensorRT-LLM#686]
Hi TensorRT-LLM guys,
I just found that you make a check condition here : 

https://github.com/NVIDIA/TensorRT-LLM/blob/a75618df24e97ecf92b8899ca3c229c4b8097dda/cpp/tensorrt_llm/kernels/kvCacheUtils.h#L153

<img width="1066" alt="image" src="https://github.com/NVIDIA/TensorRT-LLM/assets/147899933/54656d38-22ad-4e08-8aac-57762e19ed2b">

is there any plan we can change all `int32_t` variables in  `KVLinearBuffer` to some other types (int64, for example), so that we can apply a bigger batch_size/seq_length in `KVLinearBuffer` ? Now we will meet error in MMHA kernel because `seqIdx * mBytesPerSeq * 2 + static_cast<int32_t>(kvIdx) * mBytesPerSeq > std::numeric_limits<int32_t>::max()`

**Comment by jdemouth-nvidia** [comment]
Hi @xinji1 , we want to switch to `int64_t` wherever it makes sense, indeed. That will allow us to use bigger tensors.

**Comment by MartinMarciniszyn** [comment]
That is a limitation of TensorRT at the moment. Unfortunately, tensor dimensions are restricted to `int32_t` for the moment. Once this restriction is lifted, we shall make the appropriate adjustments in TRT-LLM.
