### ISSUE TITLE
How should I use the engine in triton-inference-server?

### ISSUE THREAD

**Issue by liuao743** [NVIDIA/TensorRT-LLM#689]
I use TensortRT-0.6.1 and get the engine, but I can't use it in triton-inference-server 23.10.
Using bloom as an example, I get three files:
bloom_float16_tp1_rank0.engine	config.json  model.cache
but when I put it in model_repository and start the server, I got error:UNAVAILABLE: Internal: unable to load plan file to auto complete config.

**Comment by jdemouth-nvidia** [comment]
Could you re-open that issue on [tensorrtllm_backend](https://github.com/triton-inference-server/tensorrtllm_backend), please? You'll need to provide us with the command-lines and outputs. And have you followed the steps described [here](https://github.com/triton-inference-server/tensorrtllm_backend#using-the-tensorrt-llm-backend)?
