### ISSUE TITLE
CMake Error at CMakeLists.txt:288 (file):   file STRINGS file "/usr/local/tensorrt/include/NvInferVersion.h" cannot be   read.

### ISSUE THREAD

**Issue by tlogn** [NVIDIA/TensorRT-LLM#69]
Hi, there. I encountered an error while running `python3 ./scripts/build_wheel.py --clean  --trt_root /usr/local/tensorrt`. The error message reads "CMake Error at CMakeLists.txt:288 (file): file STRINGS file "/usr/local/tensorrt/include/NvInferVersion.h" cannot be read.".
I have installed TensorRT using `pip3`. It appears that TensorRT was installed in the directory  ".local/lib/python3.9/site-packages", and the file "/include/NvInferVersion.h" is missing. Should I install TensorRT through source code building ? Can you please suggest a solution to fix this error?

```
tensorrt==9.1.0.post12.dev4
tensorrt-bindings==9.1.0.post12.dev4
tensorrt-libs==9.1.0.post12.dev4
```

**Comment by kaiyux** [comment]
Hi @tlogn , that file should be located in `/usr/local/tensorrt/include`, as you specified for `--trt_root`. 

Please check if that directory is existed. If not, please follow the doc [here](https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/docs/source/installation.md) to build TRTLLM in docker, or manually execute [install_tensorrt.sh](https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/docker/common/install_tensorrt.sh) to install TensorRT to that directory.

**Comment by iloveai8086** [comment]
Hello!
In the docker environment, I have met the same problem,and I'm sure Tensorrt9 is already installed.
```
CMake Error at CMakeLists.txt:288 (file):
  file STRINGS file "/usr/include/x86_64-linux-gnu/NvInferVersion.h" cannot
  be read.
```
and then I  use the following command:
```
cmake -DTRT_LIB_DIR=/usr/local/tensorrt/lib -DTRT_INCLUDE_DIR=/usr/local/tensorrt/include/ ..
```
The error above has disappeared.
But I have encountered a new error
```
CMake Error at tensorrt_llm/plugins/CMakeLists.txt:106 (set_target_properties):
  set_target_properties called with incorrect number of arguments.
```
I think there may be an error in reading `TRT_VERSION\TRT_SOVERSION` related variables related to Tensorrt in cmakelists, so I deleted the `set above_ Target_ Properties` and can be compiled

**Comment by jdemouth-nvidia** [comment]
Hi, 

If we want to make progress and help you resolve the issue, we need to know how you create the Docker that you are using to build TensorRT-LLM. Otherwise, we can only speculate and there's a risk that we don't make a lot of progress this way.

Thanks,
Julien

**Comment by byshiue** [comment]
Close this bug because the issue is inactivated. Feel free to ask here if you still have question/issue, we will reopen the issue.
