### ISSUE TITLE
Set num_beams of run.py is 4, the result has 4 outputs , but transfromers has 1 output

### ISSUE THREAD

**Issue by chenpinganan** [NVIDIA/TensorRT-LLM#691]
【TensorRT LLM:】

1. use chatglm2-6b models
2. build.py --max_beam_width=4
3. run.py --num_beams=4
4. result has 4 outputs， and output[0] is not the best output

Output [Text 0 Beam 0]: xxxxx
Output [Text 0 Beam 1]:  xxxxx
Output [Text 0 Beam 2]:  xxxxx
Output [Text 0 Beam 3]:  xxxxx

【Hugging Hace Transformers】
But transformer ony has one output.
Output [Text 0 Beam 0]: xxxxx

Is it a bug for TensorRT LLM?

**Comment by chenpinganan** [comment]
TensorRT-LLM/examples/run.py
TensorRT-LLM/examples/chatglm/build.py
version:0.6.0

**Comment by chenpinganan** [comment]
try fix bug: set beam_width is 1, not use 4

main/tensorrt_llm/runtime/generation.py



 def finalize_decoder(self,
                         context_lengths,
                         batch_size,
                         beam_width,
                         scfg,
                         in_progress=False):
        final_output_ids = None
        if self.mapping.is_last_pp_rank():
            # output shape of self.gather_tree: [batch_size, beam_width, output_len]
            beam_hyps_args = [
                self.beam_hyps_output_ids_tgt,
                self.beam_hyps_sequence_lengths_tgt,
                self.beam_hyps_cum_log_probs, self.beam_hyps_normed_scores,
                self.beam_hyps_log_probs, self.beam_hyps_min_normed_scores,
                self.beam_hyps_num_beams, self.beam_hyps_is_done
            ]
            if scfg.use_beam_hyps and in_progress:
                # self.gather_tree modifies these args.
                # In streaming mode, this results in incorrect decoding in the following steps.
                beam_hyps_args = copy.deepcopy(beam_hyps_args)
			##################################################
			#################### start test bug ##############
			beam_width = 1 # if set beam_width to 1, the final result has 1 output, and the output[0] is the best output
			#################### end test bug ##############
			##################################################
            final_output_ids = self.gather_tree(
                self.sequence_length_buffer, self.output_ids, self.parent_ids,
                self.end_ids, context_lengths, self.cum_log_probs,
                *beam_hyps_args, self.finished, self.length_penalty, batch_size,
                beam_width, self.max_seq_length, scfg.use_beam_hyps)

        # Communicate ranks in Pipeline Parallelism
        if self.mapping.has_pp():
            final_output_ids = self.pp_communicate_final_output_ids(
                final_output_ids, batch_size, beam_width)

        return final_output_ids

**Comment by byshiue** [comment]
If you don't set `num_return_sequences` in HF, it will only return the first one sentence although it will generate `beam_width` sentences in beam search. You could see more details on HF document.

**Comment by chenpinganan** [comment]
Excuse me, may I ask： Which parameter has the same function in TensorRT-LLM? 

I want to need the same result when use TensorRT-LLM and  HF transfomers

When I set num_beams to 4, TensorRT-LLM has 4 output, but I only need one output. 

And sometimes，the output[0] of TensorRT-LLM  is  correct, but sometimes the output[3] is correct.

I thank the result is not in descending orderd， so I can not always get the correct output by use the output[0]

**Comment by byshiue** [comment]
The results are ordered. Sometimes, the outputs[0] of HF and TRT LLM are different because precision issue, it is expected and not a bug.
