### ISSUE TITLE
Custom generation loop and In-flight Batching

### ISSUE THREAD

**Issue by akhoroshev** [NVIDIA/TensorRT-LLM#692]
According to the [documentation](https://nvidia.github.io/TensorRT-LLM/gpt_runtime.html#internal-components)
```
The GptDecoder can be used directly to implement very custom generation loop and for use cases that cannot be satisfied by the implementation in GptSession.
```

Is it possible to implement custom sampling layers for In-flight Batching?

**Comment by byshiue** [comment]
GptDeocder implementation is here https://github.com/NVIDIA/TensorRT-LLM/blob/main/cpp/tensorrt_llm/runtime/gptDecoder.cpp.

**Comment by akhoroshev** [comment]
@byshiue
How [GptManager](https://github.com/NVIDIA/TensorRT-LLM/blob/main/cpp/include/tensorrt_llm/batch_manager/GptManager.h) is connected to [gptDecoder.cpp](https://github.com/NVIDIA/TensorRT-LLM/blob/main/cpp/tensorrt_llm/runtime/gptDecoder.cpp)?

**Comment by byshiue** [comment]
Please refer https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/gpt_runtime.md and https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/batch_manager.md.

**Comment by akhoroshev** [comment]
Hmm, ok, I can add some changes to the gptDecoder.cpp and GptManager will see them.

But what if i want to add **new** runtime options like top_p/top_k, how can I pass this new tensor to the gptDecoder.cpp if I use GptManager?

It looks impossible because we don't have sources of the GptManager, right?

**Comment by byshiue** [comment]
Yes.

**Comment by ilyaonoff** [comment]
@akhoroshev @byshiue 

Can you please help me understand through what c++ feature are [GptManager](https://github.com/NVIDIA/TensorRT-LLM/blob/main/cpp/include/tensorrt_llm/batch_manager/GptManager.h) is connected to [gptDecoder.cpp](https://github.com/NVIDIA/TensorRT-LLM/blob/main/cpp/tensorrt_llm/runtime/gptDecoder.cpp)? How to track this connection using code in this repository?

**Comment by akhoroshev** [comment]
> Can you please help me understand through what c++ feature are [GptManager](https://github.com/NVIDIA/TensorRT-LLM/blob/main/cpp/include/tensorrt_llm/batch_manager/GptManager.h) is connected to [gptDecoder.cpp](https://github.com/NVIDIA/TensorRT-LLM/blob/main/cpp/tensorrt_llm/runtime/gptDecoder.cpp)? How to track this connection using code in this repository?

GptManager is closed sourced static lib that links to the gptDecoder.cpp

**Comment by hello-11** [comment]
@akhoroshev Do you still have the problem? If not, we will close it soon.
