### ISSUE TITLE
The performance of main branch on llama model is slightly lower than that of 0.5.0, is it expected?

### ISSUE THREAD

**Issue by xinji1** [NVIDIA/TensorRT-LLM#696]
Device: single A100-80G
Input length: 2200 tokens
Output: 100 tokens

I tested the time cost of different trt-llm versions with different batch_size, found that the main branch is slightly lower that 0.5.0

![image](https://github.com/NVIDIA/TensorRT-LLM/assets/147899933/afeeb0cb-5f67-4c9f-834d-7c62a22a5a54)

is it expected? 

My engine building: 

```bash

python build.py --model_dir /llama_hf_13B/ \
                --dtype float16 \
                --max_batch_size 24 \
                --max_input_len 2200 \
                --max_output_len 100 \
                --use_gpt_attention_plugin float16 \
                --use_gemm_plugin float16 \
                --output_dir /OUTBUT/
```

**Comment by JensenFire** [comment]
Just found a bug in my code. Sorry for that. Now 0.5.0 and latest main branch are aligned
