### ISSUE TITLE
Why TRT-LLM engine's loading memory size can be much larger than the original model size? 

### ISSUE THREAD

**Issue by xinji1** [NVIDIA/TensorRT-LLM#698]
Hi Trt-llm guys,

I just made a llama-2-13b-chat test on TRT-LLM. For the original model, the weight-size is around: 

13Billon * 2(sizeof(half) ==2)  / 1073741824(PER GB) ~= 26GB

and `25417MiB` from nvidia-smi showing result.

However, when loading the engine with python code `tensorrt_llm.runtime.GenerationSession`, the number could be ~60000MiB. 
Specifically, in `tensorrt_llm/runtime/generation.py` , after:

`self.engine = self.runtime.deserialize_cuda_engine(engine_buffer)`

https://github.com/NVIDIA/TensorRT-LLM/blob/a75618df24e97ecf92b8899ca3c229c4b8097dda/tensorrt_llm/runtime/generation.py#L167C9-L167C74

the gpu memory increases from 0 -> 25267MiB

and after :

`address = CUASSERT(cudart.cudaMalloc(self.engine.device_memory_size))[0]`

`https://github.com/NVIDIA/TensorRT-LLM/blob/a75618df24e97ecf92b8899ca3c229c4b8097dda/tensorrt_llm/runtime/generation.py#L170C10-L170C81

the gpu memory increases from 25267MiB ->59395MiB.

My build cmd : 

```bash
python build.py --model_dir /code/all/hf_llama13B/ \
                --dtype float16 \
                --max_batch_size 24 \
                --max_input_len 2200 \
                --max_output_len 100 \
                --use_gpt_attention_plugin float16 \
                --use_gemm_plugin float16 \
                --output_dir /save_path/
```

I'm just curious about:
1. whether the code `address = CUASSERT(cudart.cudaMalloc(self.engine.device_memory_size))[0]` is necessary for the geneartion process?
2. Is there any way through which we can reduce the gpu memory occupying? 60GB is a big number~

**Comment by JensenFire** [comment]
Just found the answer in https://github.com/NVIDIA/TensorRT-LLM/blob/a75618df24e97ecf92b8899ca3c229c4b8097dda/docs/source/memory.md
