### ISSUE TITLE
How to build Tensorrt-LLM without docker?

### ISSUE THREAD

**Issue by beginlner** [NVIDIA/TensorRT-LLM#70]

**Comment by juney-nvidia** [comment]
In theory, as long as you have the required dependency(CUDA, Python, TRT, etc) properly set up, you can build TensorRT-LLM without docker. However, it is still suggested to build TensorRT-LLM with the docker-based approach to reduce the potential tricky environment issue. 

In our daily development, we mainly build TensorRT-LLM inside docker. 

June
