### ISSUE TITLE
Benchmarking perf not meeting expectation

### ISSUE THREAD

**Issue by jinish1991** [NVIDIA/TensorRT-LLM#703]
I am trying to benchmark GPTJ-6B by following instructions here [https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/performance.md#gpt-j-6b]
But The result I get on H100 with no freq cap setting is 

BS: 64, ISL/OSL: 2048,128
Benchmarking done. Iteration: 5, duration: 18.13 sec.
[BENCHMARK] batch_size 64 input_length 2048 output_length 128 latency(ms) 3626.00 tokensPerSec 2259.24
BS: 64, ISL/OSL: 2048,2048
Benchmarking done. Iteration: 5, duration: 250.00 sec.
[BENCHMARK] batch_size 64 input_length 2048 output_length 2048 latency(ms) 50000.91 tokensPerSec 2621.39

Quoted numbers are 2251 and 3327 respectively.

Also, I had issue with this flag "--enable_two_optimization_profiles" gave me an error that this flag is not recognized. 
Can the perf delta be due to this?

**Comment by hello-11** [comment]
@jinish1991 Do you still have the problem? If not, we will close it soon.
