### ISSUE TITLE
Is the `activation size` equal to `workspace` in c++ plugin?

### ISSUE THREAD

**Issue by xinji1** [NVIDIA/TensorRT-LLM#704]
Hi TRT-LLM guys, 

I just have two quick questions about the `activation size` in `https://github.com/NVIDIA/TensorRT-LLM/blob/a75618df24e97ecf92b8899ca3c229c4b8097dda/docs/source/memory.md#activation-size`.

1. Is the `activation size` equal to `workspace` in c++ plugin? Or it will be a little larger than the value of `getWorkspaceSize()` ?
2. Take llama-13b as an example, it looks like trt-llm creates a gpt attention plugin for each single layer right ? If so , will the workspace be released in the former layers after  the calculation done so that the latter layers could re-use the space? Otherwise the workspace size of 40 layers (llama-13b) could be an extremely large.

**Comment by kaiyux** [comment]
1. activation size contains the workspace of plugin, the intermediate buffer, and so on. 

2. TRT will allocate a large workspace, and reuse them in plugins.

**Comment by JensenFire** [comment]
thanks, will close the issue
