### ISSUE TITLE
[TensorRT-LLM 0.6.1] Running benchmark error

### ISSUE THREAD

**Issue by dominicshanshan** [NVIDIA/TensorRT-LLM#706]
Running benchmark.py, following error appeared, it seems pynvml version is too low cause it.

Successfully built tensorrt_llm-0.6.1-py3-none-any.whl   
![2023-12-20 at 08 50](https://github.com/NVIDIA/TensorRT-LLM/assets/30051912/e6bac024-ad07-4816-9942-e96f2a3b0660)

**Comment by dominicshanshan** [comment]
[update] After upgrade pynvml via pip to v11.5, the benchmark can run successfully

**Comment by byshiue** [comment]
Thank you for the update. Close this bug.
