### ISSUE TITLE
nvcc warning : The -std=c++17 flag is not supported with the configured host compiler

### ISSUE THREAD

**Issue by jschenxiaoyu** [NVIDIA/TensorRT-LLM#714]
My CUDA version is 11.8. When installing tensorrt-llm, I encountered the warning：
`nvcc warning : The -std=c++17 flag is not supported with the configured host compiler. Flag will be ignored.`
How can I resolve this issue? Thank you.
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/3395123/7a72ff98-8d13-4a5b-b8a7-246830e6b116)

**Comment by kaiyux** [comment]
Do you use the docker file to build docker image?
