### ISSUE TITLE
container build error

### ISSUE THREAD

**Issue by Burning-XX** [NVIDIA/TensorRT-LLM#715]
First pull the docker image
docker pull nvcr.io/nvidia/tritonserver:23.10-trtllm-python-py3

run the docker container
docker run -it -d --cap-add=SYS_PTRACE --cap-add=SYS_ADMIN --security-opt seccomp=unconfined --gpus=all --shm-size=16g --privileged --ulimit memlock=-1 --name=develop nvcr.io/nvidia/tritonserver:23.10-trtllm-python-py3 bash 
then

apt-get update && apt-get -y install git git-lfs

git clone https://github.com/NVIDIA/TensorRT-LLM.git
cd TensorRT-LLM
git submodule update --init --recursive
git lfs install
git lfs pull

when execute python3 ./scripts/build_wheel.py --trt_root /usr/local/tensorrt ：

-- Found Torch: /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch.so
-- TORCH_CXX_FLAGS: -D_GLIBCXX_USE_CXX11_ABI=0
-- Building for TensorRT version: 9.1.0, library version: 9
-- Using MPI_C_INCLUDE_DIRS: /opt/hpcx/ompi/include;/opt/hpcx/ompi/include/openmpi;/opt/hpcx/ompi/include/openmpi/opal/mca/hwloc/hwloc201/hwloc/include;/opt/hpcx/ompi/include/openmpi/opal/mca/event/libevent2022/libevent;/opt/hpcx/ompi/include/openmpi/opal/mca/event/libevent2022/libevent/include
-- Using MPI_C_LIBRARIES: /opt/hpcx/ompi/lib/libmpi.so
-- CMAKE_SYSTEM_PROCESSOR: x86_64
-- Operating System: ubuntu, 22.04
[ 11%] Creating directories for 'googletest-populate'
[ 22%] Performing download step (git clone) for 'googletest-populate'
Cloning into 'googletest-src'...
fatal: unable to access 'https://github.com/google/googletest.git/': GnuTLS recv error (-110): The TLS connection was non-properly terminated.
Cloning into 'googletest-src'...
error: RPC failed; curl 16 Error in the HTTP2 framing layer
fatal: expected flush after ref listing
Cloning into 'googletest-src'...
fatal: unable to access 'https://github.com/google/googletest.git/': Failed to connect to github.com port 443 after 130087 ms: Connection timed out
-- Had to git clone more than once:
          3 times.
CMake Error at googletest-subbuild/googletest-populate-prefix/tmp/googletest-populate-gitclone.cmake:31 (message):
  Failed to clone repository: 'https://github.com/google/googletest.git'

gmake[2]: *** [CMakeFiles/googletest-populate.dir/build.make:102: googletest-populate-prefix/src/googletest-populate-stamp/googletest-populate-download] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/googletest-populate.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2

CMake Error at /usr/share/cmake-3.22/Modules/FetchContent.cmake:1087 (message):
  Build step for googletest failed: 2
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FetchContent.cmake:1216:EVAL:2 (__FetchContent_directPopulate)
  /usr/share/cmake-3.22/Modules/FetchContent.cmake:1216 (cmake_language)
  /usr/share/cmake-3.22/Modules/FetchContent.cmake:1259 (FetchContent_Populate)
  tests/CMakeLists.txt:21 (FetchContent_MakeAvailable)

-- Configuring incomplete, errors occurred!
See also "/opt/tensorrt_llm/TensorRT-LLM/cpp/build/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "/opt/tensorrt_llm/TensorRT-LLM/./scripts/build_wheel.py", line 306, in <module>
    main(**vars(args))
  File "/opt/tensorrt_llm/TensorRT-LLM/./scripts/build_wheel.py", line 160, in main
    build_run(
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cmake -DCMAKE_BUILD_TYPE="Release" -DBUILD_PYT="ON" -DBUILD_PYBIND="OFF"  -DTRT_LIB_DIR=/usr/local/tensorrt/targets/x86_64-linux-gnu/lib -DTRT_INCLUDE_DIR=/usr/local/tensorrt/include  -S "/opt/tensorrt_llm/TensorRT-LLM/cpp"' returned non-zero exit status 1.
<img width="1779" alt="image" src="https://github.com/NVIDIA/TensorRT-LLM/assets/29428601/b20b1eac-e8e2-4844-a9a9-bbac0f73c732">

**Comment by Burning-XX** [comment]
somebody help me

**Comment by Tlntin** [comment]
network seems not ok

**Comment by kaiyux** [comment]
Could you try cloning the google-test locally? It looks you cannot access them.

**Comment by miangangzhen** [comment]
> Could you try cloning the google-test locally? It looks you cannot access them.

Excuse-me, where should I put the google-test repo in? 
./TensorRT-LLM 
./TensorRT-LLM/cpp
./TensorRT-LLM/cpp/build

**Comment by byshiue** [comment]
By default, it will put in `cpp/build/_deps/googletest-src/` by the cmake.

**Comment by WilliamEricCheung** [comment]
> By default, it will put in `cpp/build/_deps/googletest-src/` by the cmake.

I have a question, if I put googletest repo in `cpp/build/_deps/googletest-src/`, then re-run `python3 ./scripts/build_wheel.py --trt_root /usr/local/tensorrt`, error will occur again. From https://github.com/NVIDIA/TensorRT-LLM/issues/297#issuecomment-1805144118, it suggests to clean cpp/build/, and seems contradictory

**Comment by byshiue** [comment]
> > By default, it will put in `cpp/build/_deps/googletest-src/` by the cmake.
> 
> I have a question, if I put googletest repo in `cpp/build/_deps/googletest-src/`, then re-run `python3 ./scripts/build_wheel.py --trt_root /usr/local/tensorrt`, error will occur again. From [#297 (comment)](https://github.com/NVIDIA/TensorRT-LLM/issues/297#issuecomment-1805144118), it suggests to clean cpp/build/, and seems contradictory

The error in this issue is because they cannot clone the googletest-src successfully, the error of the 297 comment is because they try building the repo after upgrading the codes.
