### ISSUE TITLE
request failed when max batch size > 8 

### ISSUE THREAD

**Issue by yangelaboy** [NVIDIA/TensorRT-LLM#718]
- version: 0.5.0

- model: llama-7b

![image](https://github.com/NVIDIA/TensorRT-LLM/assets/16263873/3bc96931-a787-4f3a-8f13-1c59894773c6)

**Comment by kaiyux** [comment]
Can you try the latest main branch?

**Comment by yangelaboy** [comment]
@kaiyux ok，I will try with latest version, thx！

**Comment by yangelaboy** [comment]
@kaiyux hello，I run tensorrt-llm-backend with version 0.6.1, but got an error as follow:
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/16263873/eaa4557f-525b-4d7d-bf1d-2a6f7df1ab4e)

**Comment by byshiue** [comment]
Have you rebuilt the engine on trt llm 0.6.1?

**Comment by yangelaboy** [comment]
@byshiue yes，rebuilt the engine on trt llm 0.6.1

**Comment by byshiue** [comment]
Could you try 0.7.1 tag, which is released yesterday?

**Comment by yangelaboy** [comment]
@byshiue ok

**Comment by yangelaboy** [comment]
v0.7.1 is ok with bath size > 8

**Comment by byshiue** [comment]
Thank you for the update. Close this bug since the issue is fixed in v0.7.1.
