### ISSUE TITLE
Build Failure: libtensorrt_llm_batch_manager_static.a:1: syntax error

### ISSUE THREAD

**Issue by CarsonSo** [NVIDIA/TensorRT-LLM#72]
Hi guys, I am trying to install TensorRT-LLM following the instructions [Build Step-by-step](https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/docs/source/installation.md#build-step-by-step).

I have successfully built docker image and run container on my machine using:
```
make -C docker build
make -C docker run
```
<img width="1239" alt="image" src="https://github.com/NVIDIA/TensorRT-LLM/assets/46796905/ddad87e9-5215-4d9e-96ad-a37f7271bcdf">

 After running `python3 ./scripts/build_wheel.py --clean  --trt_root /usr/local/tensorrt`, I have:
```
[ 98%] Built target kernels_src
[ 98%] Linking CXX static library libtensorrt_llm_static.a
[ 98%] Built target tensorrt_llm_static
[100%] Linking CXX shared library libtensorrt_llm.so
/usr/bin/ld:/code/tensorrt_llm/cpp/tensorrt_llm/batch_manager/x86_64-linux-gnu/libtensorrt_llm_batch_manager_static.a: file format not recognized; treating as linker script
/usr/bin/ld:/code/tensorrt_llm/cpp/tensorrt_llm/batch_manager/x86_64-linux-gnu/libtensorrt_llm_batch_manager_static.a:1: syntax error
collect2: error: ld returned 1 exit status
gmake[3]: *** [tensorrt_llm/CMakeFiles/tensorrt_llm.dir/build.make:714: tensorrt_llm/libtensorrt_llm.so] Error 1
gmake[2]: *** [CMakeFiles/Makefile2:677: tensorrt_llm/CMakeFiles/tensorrt_llm.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:684: tensorrt_llm/CMakeFiles/tensorrt_llm.dir/rule] Error 2
gmake: *** [Makefile:179: tensorrt_llm] Error 2
Traceback (most recent call last):
  File "/code/tensorrt_llm/./scripts/build_wheel.py", line 248, in <module>
    main(**vars(args))
  File "/code/tensorrt_llm/./scripts/build_wheel.py", line 152, in main
    build_run(
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cmake --build . --config Release --parallel 16 --target tensorrt_llm tensorrt_llm_static nvinfer_plugin_tensorrt_llm th_common ' returned non-zero exit status 2.
```

Could you take a look at the issue above? Thanks so much.

**Comment by juney-nvidia** [comment]
@CarsonSo can you share your Operating System version and CUDA version?  My suspect is that it may be due to some environment difference from what we validated before.

June

**Comment by CarsonSo** [comment]
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"

The CUDA version Inside the container is CUDA 12.2.

**Comment by juney-nvidia** [comment]
> PRETTY_NAME="Ubuntu 22.04.2 LTS" NAME="Ubuntu" VERSION_ID="22.04"
> 
> The CUDA version Inside the container is CUDA 12.2.

@CarsonSo  Thanks for sharing this context information. Most likely the reason is due to that **git lfs** is used to store the .a library. Can you try with 
`git lfs install`
`git lfs pull`
before invoking the make command? 

June

**Comment by CarsonSo** [comment]
Will try. Thanks.

**Comment by CarsonSo** [comment]
It works after `git lfs install` and `git lfs pull`. Thanks.
