### ISSUE TITLE
Does TensorRT-LLM support Lora / Qlora

### ISSUE THREAD

**Issue by wanghao07456** [NVIDIA/TensorRT-LLM#720]
just as title，sometimes we should use the Lora model or Qlora model, we cant't merge it with the base checkpoint

**Comment by byshiue** [comment]
TRT-LLM does not support QLora now.

**Comment by llllooong** [comment]
> TRT-LLM does not support QLora now.

Are you going to support QLora in the future?

**Comment by byshiue** [comment]
It is not in our current roadmap. If you are interested, you could create a feature request ticket.
