### ISSUE TITLE
Identical function signatures in  TensorRT-LLM and TensorRT

### ISSUE THREAD

**Issue by solrex** [NVIDIA/TensorRT-LLM#724]
TensorRT-LLM exposed 2 functions to the global namespace: `setLoggerFinder()` and `getPluginCreators()`, which are identical to these names in TensorRT. Is it a bug?

https://github.com/NVIDIA/TensorRT-LLM/blob/main/cpp/tensorrt_llm/plugins/api/tllmPlugin.h#L54

```c++
  TENSORRTAPI [[maybe_unused]] void setLoggerFinder([[maybe_unused]] nvinfer1::ILoggerFinder* finder);
  TENSORRTAPI [[maybe_unused]] nvinfer1::IPluginCreator* const* getPluginCreators(int32_t& nbCreators);
```

https://github.com/NVIDIA/TensorRT/blob/main/plugin/common/vfcCommon.h#L35

```c++
extern "C" TENSORRTAPI void setLoggerFinder(nvinfer1::ILoggerFinder* finder);

extern "C" TENSORRTAPI IPluginCreator* const* getPluginCreators(int32_t& nbCreators);
```

**Comment by Shixiaowei02** [comment]
Thanks for your support to TensorRT-LLM! I am not certain of the exact reason, but I believe that declaring a function multiple times in the header file while only implementing it once is acceptable. Perhaps we should use the header file of TensorRT directly here if it the interface public.
