### ISSUE TITLE
After testing, gptq quantization accuracy is very low

### ISSUE THREAD

**Issue by shatealaboxiaowang** [NVIDIA/TensorRT-LLM#726]
Hi, dear:

I quantized codellama-13b using gptq and tested it on huaman-eval dataset pass@1, but the accuracy is off a lot. Why? 
The operation steps to perform the quantization are as follows:
https://github.com/NVIDIA/TensorRT-LLM/tree/v0.6.1/examples/llama#gptq

**Comment by juney-nvidia** [comment]
Assign to @Tracin  who helped fix another codellama-7B related quantization accuracy [issue](https://github.com/NVIDIA/TensorRT-LLM/issues/453) before. 

Thanks
June

**Comment by Tracin** [comment]
@shatealaboxiaowang How about accuracy of INT4_AWQ? I think probably GPTQ failed on this model. What is the score you got?

**Comment by hello-11** [comment]
@shatealaboxiaowang Do you still have the problem? If not, we will close it soon.
