### ISSUE TITLE
Does the repo suport qwen-vl?

### ISSUE THREAD

**Issue by tangyipeng100** [NVIDIA/TensorRT-LLM#728]
How to build qwen-vl using TensorRT-LLM?

**Comment by juney-nvidia** [comment]
@tangyipeng100 

Hi, we do have an internal implementation supporting qwen-vl with TensorRT-LLM, it has not been published onto the github yet. 

Let me sync with the engineers working on that and go back to you later.

June

**Comment by Yang-x-Zhao** [comment]
@juney-nvidia 
Same request for me and thanks for your work!

I am also working on qwen-vl-chat. To my best understanding on TensorRT-LLM, the decoder session currently does not support embedding as an input, so I cannot modify the current qwen model to adapt to qwen-vl-chat model. I will be glad to use an official release of qwen-vl-chat.

**Comment by CN-COTER** [comment]
> @tangyipeng100
> 
> Hi, we do have an internal implementation supporting qwen-vl with TensorRT-LLM, it has not been published onto the github yet.
> 
> Let me sync with the engineers working on that and go back to you later.
> 
> June

I am looking forward to deploy Qwen-vl-chat with trt-llm.

**Comment by 77h2l** [comment]
same strong demands here .

**Comment by shikimoon** [comment]
> Same request for me and thanks for your work!
> 
> I am also working on qwen-vl-chat. To my best understanding on TensorRT-LLM, the decoder session currently does not support embedding as an input, so I cannot modify the current qwen model to adapt to qwen-vl-chat model. I will be glad to use an official release of qwen-vl-chat.

the same to me

**Comment by Tlntin** [comment]
There might be what you're looking for here
[link](https://github.com/Tlntin/Qwen-TensorRT-LLM/tree/main/examples/qwen-vl)

**Comment by tangyipeng100** [comment]
> There might be what you're looking for here [link](https://github.com/Tlntin/Qwen-TensorRT-LLM/tree/main/examples/qwen-vl)

Thanks!
