### ISSUE TITLE
Can I run an example (of LLAMA 7b) without building the engine?

### ISSUE THREAD

**Issue by ucalyptus** [NVIDIA/TensorRT-LLM#731]
I'd like to be able to do a build_wheel.py and straightaway run a benchmark for LLAMA7b.

Let me if that is possible since using docker is not feasible for my use case.

**Comment by juney-nvidia** [comment]
@ucalyptus 

For preparing the wheel package,  we have only made thorough validation in docker-based environment. 
For non-docker environment, in theory if you have the related dependency(CUDA/TRT/etc) suitably configured, it should also be okay to build the wheel package, but with less validation. 

In the upcoming weeks, pre-built wheel package will be prepared with the corresponding usage documentation, I think this may be what you want to have a try?

Thanks
June

**Comment by ucalyptus** [comment]
@juney-nvidia pre-built wheel will be a big help.

**Comment by jdemouth-nvidia** [comment]
Since you've created https://github.com/NVIDIA/TensorRT-LLM/issues/790, I guess it means that we can close this one.
