### ISSUE TITLE
Triton's gpumemory footprint is twice that of Tensorrt-LLM

### ISSUE THREAD

**Issue by lyc728** [NVIDIA/TensorRT-LLM#732]
In my test of qwen-72b, weight_only_precision int4 is used for loading with four cards, each occupying about 12G. However, when Triton conducts reasoning, each card can occupy about 28G. May I ask why the gap is so big?

**Comment by byshiue** [comment]
It might be because triton allocate some buffer for paged k/v caches.

**Comment by lyc728** [comment]
> It might be because triton allocate some buffer for paged k/v caches.

Is there any way to fix this？

**Comment by byshiue** [comment]
paged kv caches are necessary buffer and you cannot "fix" them. You can try using smaller buffer by adjusting `max_tokens_in_paged_kv_cache` and `kv_cache_free_gpu_mem_fraction`. You could see more explanation in README.md.
