### ISSUE TITLE
./cpp/build/benchmarks/gptSessionBenchmark: symbol lookup error: ./cpp/build/benchmarks/gptSessionBenchmark: undefined symbol: _ZNK12tensorrt_llm7runtime14MemoryCounters8toStringEv

### ISSUE THREAD

**Issue by rGitcy** [NVIDIA/TensorRT-LLM#733]
Hi~
 I use c++ to execyte llama2 70B benchmark test. I meet the error "./cpp/build/benchmarks/gptSessionBenchmark: symbol lookup error: ./cpp/build/benchmarks/gptSessionBenchmark: undefined symbol: _ZNK12tensorrt_llm7runtime14MemoryCounters8toStringEv"。 Why is it exist and how to fix it?
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/8943172/93f54eda-d4c8-40bb-aba9-46a3d340de18)
`in_out_sizes=("64:128,128" "64:128,2048" "64:2048,128" "64:2048,2048")
for in_out in ${in_out_sizes[@]}
do
	batch_size=$(echo $in_out | awk -F':' '{ print $1 }')
	in_out_dims=$(echo $in_out | awk -F':' '{ print $2 }')
	echo "BS: $batch_size, ISL/OSL: $in_out_dims"

	mpirun -n 8 --allow-run-as-root --oversubscribe ./cpp/build/benchmarks/gptSessionBenchmark --model llama --engine_dir ./test_engines/llama/70b --warm_up 1 --batch_size $batch_size --duration 0 --num_runs 5 --input_output_len $in_out_dims
done`

**Comment by Shixiaowei02** [comment]
The reason of this error message maybe that the library of TensorRT-LLM is inconsistent with the test binary. Please try to clean the build directory and build the binary again, thanks!

**Comment by rGitcy** [comment]
ok, i try it again!thx

**Comment by LuletterSoul** [comment]
@Shixiaowei02 Hi, I also met the same error. I have cleaned the build directory and build the binary again, but this error still exisits. Any solution about it ?

**Comment by Shixiaowei02** [comment]
> @Shixiaowei02 Hi, I also met the same error. I have cleaned the build directory and build the binary again, but this error still exisits. Any solution about it ?

Could you please build the project in the docker container? Just like `make -C docker release_build`. Thanks!

**Comment by LuletterSoul** [comment]
> > @Shixiaowei02 Hi, I also met the same error. I have cleaned the build directory and build the binary again, but this error still exisits. Any solution about it ?
> 
> Could you please build the project in the docker container? Just like `make -C docker release_build`. Thanks!

@Shixiaowei02 I build the project using the container that is from the image `nvcr.io/nvidia/tritonserver/23.10-trtllm-python-py3`, it should conatins all the dependencies that tensorrt-llm needs. And the wheel is successfully built finally. I used the followed command:

```
python3 ./scripts/build_wheel.py --python_bindings --benchmarks --clean --trt_root /usr/local/tensorrt --cuda_architectures "80-real;86-real"
```

**Comment by hello-11** [comment]
@rGitcy Do you still have the problem? If not, we will close it soon.
