### ISSUE TITLE
convert trt engine error: OutOfMemory

### ISSUE THREAD

**Issue by CaoYiwei** [NVIDIA/TensorRT-LLM#736]
I want to convert a huggingface format 70b llama to trt engine, I tried --enable_context_fmha=True  and --max_batch_size=1, but still errors occurred.

command:
cd /opt/optimum-nvidia/third-party/tensorrt-llm/examples/llama
python build.py --model_dir ./tmp/llama/70B/ \
                --dtype float16 \
                --remove_input_padding \
                --use_gpt_attention_plugin float16 \
                --enable_context_fmha \
                --use_gemm_plugin float16 \
                --output_dir ./tmp/llama/70B/trt_engines/fp16/4-gpu/
                --tp_size 2 \
               --pp_size 2 \
               --world_isze 4 \
               --load_by_shard

gpu:
a6000 48G * 4

error:
Error Code 2: OutOfMemory.

According to the warnings "Tactic Device request: 172032MB Available: 45623MB. Device memory is insufficient to use tactic.", I guess 172G gpu memory is needed. Could I convert the engine by a6000 * 4?

**Comment by ekarmazin** [comment]
try to add `--parallel_build`

**Comment by CaoYiwei** [comment]
> try to add `--parallel_build`

I tried, failed again.
