### ISSUE TITLE
INT4 support on Volta?

### ISSUE THREAD

**Issue by sleepwalker2017** [NVIDIA/TensorRT-LLM#739]
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/26128514/9eef992b-01a5-42a1-999e-cad3be0b1e64)
Seems int4 quantization is not supported on V100, but why the documentation says int4 is supported on Volta?

**Comment by juney-nvidia** [comment]
@sleepwalker2017  Thanks for reporting this, this is indeed a typo. And we will fix it soon. 

June

**Comment by juney-nvidia** [comment]
The INT4 described here means INT4 weight-only, rather than the INT4 Tensor Core. We will refine the documentation to make it clearer.

Thanks
June
