### ISSUE TITLE
awq is very slow in my test

### ISSUE THREAD

**Issue by shatealaboxiaowang** [NVIDIA/TensorRT-LLM#748]
Hi dear:

     I tried awq quantization on codellama-13b according to https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/llama. After testing, it was very slow, 1.5 times slower than the float16 model without quantization.  Have you tested the time delay of awq ?

```[tasklist]
### Tasks
```

**Comment by byshiue** [comment]
Could you share your branch, scripts and the observed performance number?

**Comment by shatealaboxiaowang** [comment]
> Could you share your branch, scripts and the observed performance number?

Thank you for your reply.
branch is v0.7.0
convert codellama-13b-hf to awq is as https://github.com/NVIDIA/TensorRT-LLM/blob/v0.7.0/examples/llama/README.md?plain=1#L387-L391
build awq to tensorrt format is as https://github.com/NVIDIA/TensorRT-LLM/blob/v0.7.0/examples/llama/README.md?plain=1#L398-L408

I took the built model for inference, batch size=1, input num is 500 tokens, ouput num is 128 tokens, which took about 3.3s, while the original unquantized codellama-13b took about 2s

**Comment by jdemouth-nvidia** [comment]
What's your GPU, please?

**Comment by shatealaboxiaowang** [comment]
> What's your GPU, please?

A100-80G

**Comment by Tracin** [comment]
What is your batch size / input len / output len? Can you benchmark your perf using this?https://github.com/NVIDIA/TensorRT-LLM/blob/v0.7.0/benchmarks/cpp/README.md

**Comment by hello-11** [comment]
@shatealaboxiaowang Do you still have the problem? If not, we will close it soon.
