### ISSUE TITLE
Support Swin transfomer Request!

### ISSUE THREAD

**Issue by sjtu-cz** [NVIDIA/TensorRT-LLM#751]
Support Swin transfomer Request!

**Comment by azhurkevich** [comment]
@sjtu-cz You can run Swin transformer with a regular TRT. Just export from PyTorch to ONNX using [torch.onnx.export()](https://pytorch.org/tutorials/advanced/super_resolution_with_onnxruntime.html). Make sure you are setting `opset_version=18` in export function. You can take resulted ONNX and build with TRT CLI tool - trtexec. Like this: `trtexec --onnx=/path_to_onnx/swin.onnx --saveEngine=/path_to_trtengine/swin.trt --fp16 --verbose`. For env I would recommend using our NGC containers, `docker pull nvcr.io/nvidia/pytorch:23.12-py3`. Please let us know if we can help with something else :blush:.

**Comment by ncomly-nvidia** [comment]
For the time being, Vision Transformers are left for native TensorRT - TensorRT-LLM is only focused on LLMs.

**Comment by sjtu-cz** [comment]
ok,thanks

**Comment by fernandoFernandeSantos** [comment]
Is there any plan to do something similar to TensorRT-LLMs for Vision Transformers?

**Comment by vodan37** [comment]
Same question from me. 
Performance of TensorRT on vision transformers was not as good as I expected.

**Comment by sjtu-cz** [comment]
您好，你的邮件我已经收到~

**Comment by demuxin** [comment]
> For the time being, Vision Transformers are left for native TensorRT - TensorRT-LLM is only focused on LLMs.

Hi @ncomly-nvidia , Do you know the difference between Vision Transformer and LLM? Their main structure both are transformers. Why not use TensorRT-LLM for Vision Transformer?

**Comment by chuong98** [comment]
Currently, we can only export `--fp16` for Vision Transformer, but not with `int8`. The TRT does not accept `int8` and return the model with `fp32`
