### ISSUE TITLE
BaiChuan: AssertionError: Engine world size (2 * 1) != Runtime world size (1)

### ISSUE THREAD

**Issue by chenpinganan** [NVIDIA/TensorRT-LLM#753]
TensorRT-LLM version 0.6.0
I build baichuan model refer to TensorRT-LLM/examples/baichuan/README.md

step1：build model

python build.py --model_version v1_13b \
                --model_dir baichuan-inc/Baichuan-13B-Chat \
                --dtype float16 \
                --use_gemm_plugin float16 \
                --use_gpt_attention_plugin float16 \
                --output_dir ./tmp/baichuan_v1_13b/trt_engines/fp16/2-gpu/ \
                --world_size 2

step2：run model
mpirun -n 2 --allow-run-as-root \
    python ../run.py --input_text "世界上第二高的山峰是哪座？" \
                     --max_output_len=50 \
                     --tokenizer_dir=baichuan-inc/Baichuan-13B-Chat \
                     --engine_dir=./tmp/baichuan_v1_13b/trt_engines/fp16/2-gpu/

The error message is as follows：

tensorrt_llm/runtime/model_runner.py", line 81, in read_config
    assert world_size == tensorrt_llm.mpi_world_size(), \
AssertionError: Engine world size (2 * 1) != Runtime world size (1)
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[5936,1],0]
  Exit code:    1

**Comment by syuoni** [comment]
Hi @chenpinganan , I tried to reproduce the issue (with TensorRT-LLM v0.6.0, on A100*2), but the code ran successfully on my side.
```
$ mpirun -n 2 --allow-run-as-root \
    python run.py --input_text "世界上第二高的山峰是哪座？" \
        --max_output_len=50 \
        --tokenizer_dir=/workspace/llm-models/Baichuan-13B-Chat \
        --engine_dir=./tmp/baichuan_v1_13b/trt_engines/fp16/2-gpu/
[12/28/2023-03:48:31] [TRT-LLM] [MPI_Rank 1] [W] Found pynvml==11.4.1. Please use pynvml>=11.5.0 to get accurate memory usage
[12/28/2023-03:48:31] [TRT-LLM] [MPI_Rank 0] [W] Found pynvml==11.4.1. Please use pynvml>=11.5.0 to get accurate memory usage
/workspace/TensorRT-LLM/examples/baichuan/run.py:98: UserWarning: The PyTorch API of nested tensors is in prototype stage and will change in the near future. (Triggered internally at /opt/pytorch/pytorch/aten/src/ATen/NestedTensorImpl.cpp:178.)
  torch.nested.nested_tensor(input_tokens, dtype=torch.int32),
/workspace/TensorRT-LLM/examples/baichuan/run.py:98: UserWarning: The PyTorch API of nested tensors is in prototype stage and will change in the near future. (Triggered internally at /opt/pytorch/pytorch/aten/src/ATen/NestedTensorImpl.cpp:178.)
  torch.nested.nested_tensor(input_tokens, dtype=torch.int32),
Input: "世界上第二高的山峰是哪座？"
Output: "

世界上第二高的山峰是喀喇昆仑山脉的乔戈里峰(K2)，海拔8,611米(28,251英尺)。它是仅次于喜马拉雅"
```

---

Could you help check the following details? 
* What is the TensorRT-LLM version you use? v0.6.0 (and also v0.6.1) only has `run.py` in `examples/baichuan`, but you use the common `../run.py`, which is unavailable until v0.7.0.
* What GPUs do you use?
* Could you double check if the engines are built successfully? There should be two engine files in `./tmp/baichuan_v1_13b/trt_engines/fp16/2-gpu/`
* Could you check if the `mpirun` works? 
    * Run `mpirun -n 2 --allow-run-as-root python -c "import tensorrt_llm; print(tensorrt_llm.mpi_world_size())"`, and you should see something like:
```
[12/28/2023-04:00:49] [TRT-LLM] [MPI_Rank 0] [W] Found pynvml==11.4.1. Please use pynvml>=11.5.0 to get accurate memory usage
[12/28/2023-04:00:49] [TRT-LLM] [MPI_Rank 1] [W] Found pynvml==11.4.1. Please use pynvml>=11.5.0 to get accurate memory usage
2
2
```

**Comment by syuoni** [comment]
I also tested on the latest `rel` branch (release branch), and everything went well:
```
$ mpirun -n 2 --allow-run-as-root \
    python ../run.py --input_text "世界上第二高的山峰是哪座？" \
        --max_output_len=50 \
        --tokenizer_dir=/workspace/llm-models/Baichuan-13B-Chat \
        --engine_dir=./tmp/baichuan_v1_13b/trt_engines/fp16/2-gpu/
......
[TensorRT-LLM][INFO] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 12963 (MiB)
[TensorRT-LLM][INFO] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +0, now: CPU 0, GPU 12963 (MiB)
Input [Text 0]: "世界上第二高的山峰是哪座？"
Output [Text 0 Beam 0]: "

世界上第二高的山峰是喀喇昆仑山脉的乔戈里峰(K2)，海拔8,611米(28,251英尺)。它是唯一一座海拔超过8"
```

**Comment by chenpinganan** [comment]
Thank you， Maybe there's a problem with my MPI install

**Comment by jdemouth-nvidia** [comment]
@chenpinganan , should we assume that the issue is with your MPI installation and close that issue?

**Comment by hello-11** [comment]
@chenpinganan Do you still have the problem? If not, we will close it soon.
