### ISSUE TITLE
Bloom example issue : https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/bloom

### ISSUE THREAD

**Issue by haic0** [NVIDIA/TensorRT-LLM#757]
When running the trt-llm example/bloom model, the following issue occurred, could you please give us a hand to check, thanks so much !

https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/bloom

The trtllm docker has been built successfully, inside the docker , and right after converting the checkpoints successfully, and then running the engine build step,
/code/tensorrt_llm/examples/bloom$   export PATH=/usr/local/bin:$PATH

/code/tensorrt_llm/examples/bloom$  trtllm-build --checkpoint_dir ./bloom/560M/trt_ckpt/fp16/1-gpu/ \
                --use_gemm_plugin float16 \
                --use_gpt_attention_plugin float16 \
                --output_dir ./bloom/560M/trt_engines/fp16/1-gpu/

It tells the following issue, 
 
**bash: trtllm-build: command not found**

Anything wrong with my steps? Thanks!

**Comment by jdemouth-nvidia** [comment]
Let me add @nv-guomingz to this discussion. He has been working on the new API for BLOOM.

**Comment by nv-guomingz** [comment]
Hi @haic0  May I know the details like the command for building the trtllm docker?
you may run `find / -name trtllm-build ` firstly since this cmd relies on the trt-llm installation path.

Another way is you could use **python3 -m tensorrt_llm.commands.build** as an alternative.
```python
python3 -m tensorrt_llm.commands.build --checkpoint_dir ./bloom/560M/trt_ckpt/fp16/1-gpu/
--use_gemm_plugin float16
--use_gpt_attention_plugin float16
--output_dir ./bloom/560M/trt_engines/fp16/1-gpu/
```

**Comment by haic0** [comment]
Hi @nv-guomingz 
Thanks for your guidance, now i can apply trtllm-build successfully, the output is shown as the following. Thanks for your support!  

[12/28/2023-08:50:06] [TRT-LLM] [I] Total time of building Unnamed Network 0: 00:00:11
[12/28/2023-08:50:06] [TRT-LLM] [I] Serializing engine to ./bloom/560M/trt_engines/fp16/1-gpu/rank0.engine...
[12/28/2023-08:50:07] [TRT-LLM] [I] Engine serialized. Total time: 00:00:01
[12/28/2023-08:50:07] [TRT-LLM] [I] Total time of building all engines: 00:01:05
