### ISSUE TITLE
Ubuntu version error in building TensorRT-LLM wheel on ORIN

### ISSUE THREAD

**Issue by apbose** [NVIDIA/TensorRT-LLM#759]
Hi I am trying to build TRT-LLM wheel on Jetson ORIN for v0.6 and I face this error-
```
CMake Error at tensorrt_llm/CMakeLists.txt:62 (message):
  The minimum system requirement for aarch64 is Ubuntu 22.04.
```
What should be done to get past this? I had earlier built the wheel for release version 0.5 on ORIN.

Thanks in advance.

**Comment by apbose** [comment]
I could get over the above by commenting line 61-65 in tensorrt_llm/CMakeLists.txt. I was wondering if undoing the OS version check would create issue.

**Comment by Shixiaowei02** [comment]
TensorRT-LLM for aarch64 only supports Ubuntu 22.04. Please switch to Ubuntu 22.04 before installing TensorRT-LLM. Thanks!

**Comment by apbose** [comment]
Thanks for the input @Shixiaowei02. Also while building on ORIN for v0.6 I see this error - 
`/home/nvidia/workspace/abose/llama/trt_llm_main_ORIN_0.6/TensorRT-LLM/cpp/tensorrt_llm/kernels/decoderMaskedMultiheadAttention/decoderMaskedMultiheadAttentionTemplate.h(1259): error: identifier "__nv_fp8_e4m3" is undefined`
I see that the lines
```
// FP8 KV Cache.
 static constexpr bool FP8_KV_CACHE = std::is_same<Tcache, __nv_fp8_e4m3>::value;
 // INT8 KV Cache.
 static constexpr bool INT8_KV_CACHE = std::is_same<Tcache, int8_t>::value;
```
Has been added for the 0.6 version and was not present in 0.5. How do I get over this?

**Comment by Shixiaowei02** [comment]
Does this issue still exist in the version 0.7 or main branch?

**Comment by apbose** [comment]
I did not check with version 0.7 or the main branch.
As for building the wheels for TRT-LLM 0.6, FP8_KV_cache, I just set it to False.
 `static constexpr bool FP8_KV_CACHE = False`
Since ORIN does not support FP8. I am not sure if this is the right way, but I could build the wheel after doing so and making additional changes

**Comment by hello-11** [comment]
@apbose Do you still have the problem? If not , we will close it soon.
