### ISSUE TITLE
tensorRT error in building TensorRT-LLM wheel on ORIN

### ISSUE THREAD

**Issue by whk6688** [NVIDIA/TensorRT-LLM#760]
my orin has updated to cuda 12.2. but when I compile tensorrt-llm, i met error, i found  requirements is : tensorrt==9.2.0.post12.dev5. 
i asked the tensorrt author, got it:
![K6SPMtUHbV](https://github.com/NVIDIA/TensorRT-LLM/assets/17873056/48886086-4481-43bc-8812-6dfac41a2137)

pls. is there any solution?  so depressed i am!  thanks!

**Comment by Shixiaowei02** [comment]
Hi @whk6688 , please use this command to build trt-llm for aarch64. It will automatically install the latest version of TensorRT. Thank you!
```
make -C docker release_build
```

**Comment by whk6688** [comment]
must docker? ok，i did it,  but get another error:
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/17873056/86962085-10be-4ed6-ab46-83997396255b)

**Comment by Shixiaowei02** [comment]
It appears that the error is related to Docker itself. Could you try building other Docker images, such as Ubuntu 22.04? Could you please try running the following command?
`apt-get install docker-buildx-plugin`

**Comment by whk6688** [comment]
yes, it is.  
But when i run: make -C docker release_build.  I found the 63th line of scripts/build_wheel.py:  f"\"{sys.executable}\" -m pip install -r {requirements_filename}.  it will get following error: 
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/17873056/5c63ee2a-bf3f-44a3-ab9d-41a2adb6b5a2)

in fact, tensorrt had been installed
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/17873056/f5047417-bfdc-43a0-b094-d4506b5b6e2b)

then, i delete tensorrt from requirements file. at last, get following error:

 Successfully installed accelerate-0.20.3 build-1.0.3 cfgv-3.4.0 colored-2.2.4 coloredlogs-15.0.1 coverage-7.4.0 cuda-python-12.2.0 datasets-2.16.0 diffusers-0.15.0 dill-0.3.7 distlib-0.3.8 evaluate-0.4.1 graphviz-0.20.1 huggingface-hub-0.20.1 humanfriendly-10.0 identify-2.5.33 lark-1.1.8 multiprocess-0.70.15 mypy-1.8.0 mypy-extensions-1.0.0 nltk-3.8.1 nodeenv-1.8.0 optimum-1.16.1 parameterized-0.9.0 pre-commit-3.6.0 py-1.11.0 pyarrow-hotfix-0.6 pybind11-stubgen-2.4.2 pynvml-11.5.0 pyproject_hooks-1.0.0 pytest-cov-4.1.0 pytest-forked-1.6.0 responses-0.18.0 rouge_score-0.1.2 safetensors-0.4.1 sentencepiece-0.1.99 tokenizers-0.13.3 transformers-4.33.1 typing-extensions-4.8.0 virtualenv-20.25.0 xxhash-3.4.1
179.7 ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
179.7 dask-cuda 23.8.0 requires pynvml<11.5,>=11.0.0, but you have pynvml 11.5.0 which is incompatible.
179.7 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
184.0
184.0 [notice] A new release of pip is available: 23.2.1 -> 23.3.2
184.0 [notice] To update, run: python3 -m pip install --upgrade pip
186.8 -- The CXX compiler identification is GNU 11.4.0
186.8 -- Detecting CXX compiler ABI info
187.0 -- Detecting CXX compiler ABI info - done
187.0 -- Check for working CXX compiler: /usr/bin/c++ - skipped
187.0 -- Detecting CXX compile features
187.0 -- Detecting CXX compile features - done
187.0 -- NVTX is disabled
187.0 -- Importing batch manager
187.0 -- Building PyTorch
187.0 -- Building Google tests
187.0 -- Building benchmarks
187.0 -- Looking for a CUDA compiler
191.8 -- Looking for a CUDA compiler - /usr/local/cuda/bin/nvcc
191.8 -- CUDA compiler: /usr/local/cuda/bin/nvcc
191.8 -- GPU architectures: 70-real;80-real;86-real;89-real;90-real
191.9 -- The C compiler identification is GNU 11.4.0
194.0 -- The CUDA compiler identification is NVIDIA 12.2.140
194.0 -- Detecting C compiler ABI info
194.2 -- Detecting C compiler ABI info - done
194.3 -- Check for working C compiler: /usr/bin/cc - skipped
194.3 -- Detecting C compile features
194.3 -- Detecting C compile features - done
194.3 -- Detecting CUDA compiler ABI info
223.9 -- Detecting CUDA compiler ABI info - done
224.0 -- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc - skipped
224.0 -- Detecting CUDA compile features
224.0 -- Detecting CUDA compile features - done
224.0 -- Found CUDAToolkit: /usr/local/cuda/include (found version "12.2.140")
224.0 -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
224.2 -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
224.2 -- Found Threads: TRUE
224.3 -- CUDA library status:
224.3 --     version: 12.2.140
224.3 --     libraries: /usr/local/cuda/lib64
224.3 --     include path: /usr/local/cuda/targets/sbsa-linux/include
224.3 -- ========================= Importing and creating target nvinfer ==========================
224.3 -- Looking for library nvinfer
224.3 -- Library that was found /usr/lib/aarch64-linux-gnu/libnvinfer.so
224.3 -- ==========================================================================================
224.3 -- CUDAToolkit_VERSION 12.2 is greater or equal than 11.0, enable -DENABLE_BF16 flag
224.3 -- CUDAToolkit_VERSION 12.2 is greater or equal than 11.8, enable -DENABLE_FP8 flag
224.7 -- Found MPI_C: /opt/hpcx/ompi/lib/libmpi.so (found version "3.1")
225.2 -- Found MPI_CXX: /opt/hpcx/ompi/lib/libmpi.so (found version "3.1")
225.2 -- Found MPI: TRUE (found version "3.1")
225.2 -- COMMON_HEADER_DIRS: /src/tensorrt_llm/cpp;/usr/local/cuda/include
225.7 -- Found Python3: /usr/bin/python3.10 (found version "3.10.12") found components: Interpreter Development Development.Module Development.Embed
230.8 -- USE_CXX11_ABI is set by python Torch to 1
230.8 -- TORCH_CUDA_ARCH_LIST: 7.0;8.0;8.6;8.9;9.0
230.8 CMake Warning at CMakeLists.txt:304 (message):
230.8   Ignoring environment variable TORCH_CUDA_ARCH_LIST=5.2 6.0 6.1 7.0 7.2 7.5
230.8   8.0 8.6 8.7 9.0+PTX
230.8
230.8
230.9 -- Found Python executable at /usr/bin/python3.10
230.9 -- Found Python libraries at /usr/lib/aarch64-linux-gnu
236.8 -- Found CUDA: /usr/local/cuda (found version "12.2")
236.8 -- Found CUDAToolkit: /usr/local/cuda/include (found version "12.2.140")
236.9 -- Caffe2: CUDA detected: 12.2
236.9 -- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
236.9 -- Caffe2: CUDA toolkit directory: /usr/local/cuda
237.1 -- Caffe2: Header version is: 12.2
237.3 -- /usr/local/cuda-12.2/targets/sbsa-linux/lib/libnvrtc.so shorthash is 0924ef55
237.3 CMake Warning (dev) at /usr/local/lib/python3.10/dist-packages/cmake/data/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
237.3   The package name passed to `find_package_handle_standard_args` (nvtx3) does
237.3   not match the name of the calling package (Caffe2).  This can lead to
237.3   problems in calling code that expects `find_package` result variables
237.3   (e.g., `_FOUND`) to follow a certain pattern.
237.3 Call Stack (most recent call first):
237.3   /usr/local/lib/python3.10/dist-packages/torch/share/cmake/Caffe2/public/cuda.cmake:216 (find_package_handle_standard_args)
237.3   /usr/local/lib/python3.10/dist-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:87 (include)
237.3   /usr/local/lib/python3.10/dist-packages/torch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
237.3   CMakeLists.txt:337 (find_package)
237.3 This warning is for project developers.  Use -Wno-dev to suppress it.
237.3
237.3 -- Found nvtx3: /usr/local/cuda/include
237.3 -- USE_CUDNN is set to 0. Compiling without cuDNN support
237.3 -- USE_CUSPARSELT is set to 0. Compiling without cuSPARSELt support
237.3 -- Added CUDA NVCC flags for: -gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_89,code=sm_89;-gencode;arch=compute_90,code=sm_90
237.3 CMake Warning at /usr/local/lib/python3.10/dist-packages/torch/share/cmake/Torch/TorchConfig.cmake:22 (message):
237.3   static library kineto_LIBRARY-NOTFOUND not found.
237.3 Call Stack (most recent call first):
237.3   /usr/local/lib/python3.10/dist-packages/torch/share/cmake/Torch/TorchConfig.cmake:127 (append_torchlib_if_found)
237.3   CMakeLists.txt:337 (find_package)
237.3
237.3
237.3 -- Found Torch: /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch.so
237.3 -- TORCH_CXX_FLAGS: -D_GLIBCXX_USE_CXX11_ABI=1
237.3 CMake Error at CMakeLists.txt:362 (file):
237.3   file STRINGS file
237.3   "/home/wanghaikuan/temp/tensorrt/include/NvInferVersion.h" cannot be read.
237.3
237.3
237.3 CMake Error at CMakeLists.txt:365 (string):
237.3   string sub-command REGEX, mode MATCH needs at least 5 arguments total to
237.3   command.
237.3
237.3
237.3 CMake Error at CMakeLists.txt:367 (string):
237.3   string sub-command REGEX, mode MATCH needs at least 5 arguments total to
237.3   command.
237.3
237.3
237.3 CMake Error at CMakeLists.txt:365 (string):
237.3   string sub-command REGEX, mode MATCH needs at least 5 arguments total to
237.3   command.
237.3
237.3
237.3 CMake Error at CMakeLists.txt:367 (string):
237.3   string sub-command REGEX, mode MATCH needs at least 5 arguments total to
237.3   command.
237.3
237.3
237.3 CMake Error at CMakeLists.txt:365 (string):
237.3   string sub-command REGEX, mode MATCH needs at least 5 arguments total to
237.3   command.
237.3
237.3
237.3 CMake Error at CMakeLists.txt:367 (string):
237.3   string sub-command REGEX, mode MATCH needs at least 5 arguments total to
237.3   command.
237.3
237.3
237.3 CMake Error at CMakeLists.txt:365 (string):
237.3   string sub-command REGEX, mode MATCH needs at least 5 arguments total to
237.3   command.
237.3
237.3
237.3 CMake Error at CMakeLists.txt:367 (string):
237.3   string sub-command REGEX, mode MATCH needs at least 5 arguments total to
237.3   command.
237.3
237.3
237.3 -- Building for TensorRT version: .., library version:
237.3 -- Using MPI_C_INCLUDE_DIRS: /opt/hpcx/ompi/include;/opt/hpcx/ompi/include/openmpi;/opt/hpcx/ompi/include/openmpi/opal/mca/hwloc/hwloc201/hwloc/include;/opt/hpcx/ompi/include/openmpi/opal/mca/event/libevent2022/libevent;/opt/hpcx/ompi/include/openmpi/opal/mca/event/libevent2022/libevent/include
237.3 -- Using MPI_C_LIBRARIES: /opt/hpcx/ompi/lib/libmpi.so
237.4 -- CMAKE_SYSTEM_PROCESSOR: aarch64
237.4 -- Operating System: ubuntu, 22.04
237.4 CMake Error at tensorrt_llm/plugins/CMakeLists.txt:108 (set_target_properties):
237.4   set_target_properties called with incorrect number of arguments.
237.4
237.4
243.3 -- Found Python: /usr/bin/python3.10 (found version "3.10.12") found components: Interpreter
243.4 -- ========================= Importing and creating target nvonnxparser ==========================
243.4 -- Looking for library nvonnxparser
243.4 -- Library that was found /usr/lib/aarch64-linux-gnu/libnvonnxparser.so
243.4 -- ==========================================================================================
243.4 -- Configuring incomplete, errors occurred!
243.5 Traceback (most recent call last):
243.5   File "/src/tensorrt_llm/scripts/build_wheel.py", line 306, in <module>
243.5     main(**vars(args))
243.5   File "/src/tensorrt_llm/scripts/build_wheel.py", line 160, in main
243.5     build_run(
243.5   File "/usr/lib/python3.10/subprocess.py", line 526, in run
243.5     raise CalledProcessError(retcode, process.args,
243.5 subprocess.CalledProcessError: Command 'cmake -DCMAKE_BUILD_TYPE="Release" -DBUILD_PYT="ON" -DBUILD_PYBIND="OFF"  -DTRT_LIB_DIR=/home/wanghaikuan/temp/tensorrt/targets/aarch64-linux-gnu/lib -DTRT_INCLUDE_DIR=/home/wanghaikuan/temp/tensorrt/include  -S "/src/tensorrt_llm/cpp"' returned non-zero exit status 1.
------
Dockerfile.multi:33
--------------------
  31 |
  32 |     ARG BUILD_WHEEL_ARGS="--clean --trt_root /home/wanghaikuan/temp/tensorrt"
  33 | >>> RUN python3 scripts/build_wheel.py ${BUILD_WHEEL_ARGS}
  34 |
  35 |     FROM devel as release
--------------------
ERROR: failed to solve: process "/bin/bash -c python3 scripts/build_wheel.py ${BUILD_WHEEL_ARGS}" did not complete successfully: exit code: 1
make: *** [Makefile:52: release_build] Error 1
make: Leaving directory '/home/wanghaikuan/code/TensorRT-LLM/docker'

pls. have a look, thanks

**Comment by whk6688** [comment]
Anyone can help me?  thanks!   @Shixiaowei02

**Comment by Shixiaowei02** [comment]
Could you please remove the line containing TensorRT in the requirements file and try again?
