### ISSUE TITLE
how to create awq for gpt-j

### ISSUE THREAD

**Issue by BaiMoHan** [NVIDIA/TensorRT-LLM#761]
In example/gptj/quantize.py, the qforma parameter only supports fp8 and does not support int4_awq. However, I found that the llama model does support it. If I want to use int4_awq, how can I do it? I have also tried autoawq, but it seems that the generated files are different from the ones required in build.py.

**Comment by byshiue** [comment]
Have you try following the guide here https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/gptj#awq-int4-weight-only-quantization?

**Comment by BaiMoHan** [comment]
> Have you try following the guide here https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/gptj#awq-int4-weight-only-quantization?
 
I have reviewed the guide, and I am trying to use GPT-J with int8 kvcache + awq. When I execute the command,
```shell
python3 build.py --dtype=float16 \
                 --log_level=verbose \
                 --enable_context_fmha \
                 --use_gpt_attention_plugin float16 \
                 --use_gemm_plugin float16 \
                 --max_batch_size=32 \
                 --max_input_len=1919 \
                 --max_output_len=128 \
                 --remove_input_padding \
                 --output_dir=gptj_engine_awq_int8_kv_cache/ \
                 --use_weight_only \
                 --per_group \
                 --weight_only_precision=int4 \
                 --model_dir=gptj_awq_int4 \
                 --int8_kv_cache \
                 --ft_model_dir=gptj_ft_model/1-gpu/
```
 I encounter the error: "No such file or directory: 'gptj_awq_int4/gptj_quantized.pth'." I am using autoAwq to process GPT-J. My confusion is whether the generation of gptj_quantized.pth is within the scope of tensorRt-llm.
 Is it possible that I misunderstood the documentation?

**Comment by perprit** [comment]
Hi, I've encountered exactly the same issue. I was looking for the script that converts a checkpoint file into `gptj_quantized.pth` format, which is needed for `build.py` script. However, I haven't been able to find the script in the repository.
Have you managed to find a solution or a workaround?

**Comment by byshiue** [comment]
Here is document https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/gptj#awq-int4-weight-only-quantization.

**Comment by perprit** [comment]
Appreciate the comment. I've gone through the documentation, which covers the required parameters for enabling AWQ int4 quantization. However, it seems to lack details on the process of obtaining the quantized weights (specifically, the [gptj_quantized.pth](https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/gptj/build.py#L260) file) from the original checkpoint.

Could you please clarify if there exists a script or a set of instructions for the purpose? Thanks!
