### ISSUE TITLE
Failed to build CodeLlama-7b：The value updated is not the same shape as the original. Updated: (32016, 4096), original: (32000, 4096)

### ISSUE THREAD

**Issue by tinacLu** [NVIDIA/TensorRT-LLM#763]
running with release v0.6.1

errorInfo：AssertionError: The value updated is not the same shape as the original. Updated: (32016, 4096), original: (32000, 4096)

build command:
python build.py  --model_dir=/root/autodl-tmp/CodeLlama-7b/  --dtype=float16  --remove_input_padding --use_gpt_attention_plugin float16  --enable_context_fmha  --use_gemm_plugin=float16 

<img width="441" alt="1" src="https://github.com/NVIDIA/TensorRT-LLM/assets/142209929/a6b2a82c-44b6-4667-b207-4e59dd64ee8d">

**Comment by juney-nvidia** [comment]
@tinacLu 
Hi, have you tried with the latest main branch or 0.7.1 release to see whether the issue still exist?

Thanks
June

**Comment by hello-11** [comment]
@tinacLu Do you still have the problem? If not, we will close it soon.
