### ISSUE TITLE
build tensorrt-llm error without docker

### ISSUE THREAD

**Issue by oreo-lp** [NVIDIA/TensorRT-LLM#764]
my env is :
A5000-24G
cuda + cudnn: 12.2 + 8.9.7
driver: 515.57

when I build tensorrt-llm without docker, there are some errors:
my scripts are below:
`export BUILD_WHEEL_ARGS="--clean --trt_root /usr/local/tensorrt"`
`python3 scripts/build_wheel.py ${BUILD_WHEEL_ARGS}`

and some errors are below:
`Killed`
`make[3]: *** [tensorrt_llm/kernels/CMakeFiles/kernels_src.dir/build.make:5867:  tensorrt_llm/kernels/CMakeFiles/kernels_src.dir/cutlass_kernels/int8_gemm/int8_gemm_bf16.cu.o] Error 137`
`make[3]: *** Waiting for unfinished jobs....`
`Killed`
`make[3]: *** [tensorrt_llm/kernels/CMakeFiles/kernels_src.dir/build.make:5880: ``tensorrt_llm/kernels/CMakeFiles/kernels_src.dir/cutlass_kernels/int8_gemm/int8_gemm_fp16.cu.o] Error 137`

all log info is below:
[log.log](https://github.com/NVIDIA/TensorRT-LLM/files/13786964/log.log)

can anybody help me? 
Thanks!

**Comment by azhurkevich** [comment]
@oreo-lp It will be not a trivial task to debug this, hence we provide the env. Most of the time issues like these are stemmed from different lib versions that can simply be upgraded. Can you please tell us why you prefer not to use docker? Thank you.

**Comment by oreo-lp** [comment]
> @oreo-lp It will be not a trivial task to debug this, hence we provide the env. Most of the time issues like these are stemmed from different lib versions that can simply be upgraded. Can you please tell us why you prefer not to use docker? Thank you.

Because I don't have access to a relevant GPU, my only option is to rent servers online. However, the servers available online use Docker containers, and it is not possible for me to install Docker within a Docker. Thank you.

**Comment by juney-nvidia** [comment]
@oreo-lp 

Hi, we haven't made thorough validation with non-Docker environment for TensorRT-LLM. 

In your environment, is it possible to use a customized docker image to start the server?

June
