### ISSUE TITLE
is it possible to apply smooth quant with pipeline parallel?

### ISSUE THREAD

**Issue by forrestjgq** [NVIDIA/TensorRT-LLM#765]
Hello,

I've got 2x24GB GPUs and expect apply smooth quant on a 13B fp16 model, but obviously it is impossible to run it on single 24GB GPU, thus the quant will fail.

Is it possible to apply pipeline parallel on this stage?

**Comment by juney-nvidia** [comment]
@forrestjgq 

Hi, have you already tried to run your 13B model with SQ + PP and hit some issues? In theory I don't see any blockers of using TensorRT-LLM to do so. If you meet any issues with doing so, pls let us know.

Thanks
June

**Comment by forrestjgq** [comment]
@juney-nvidia 
My bad. We've got a bug to specify CUDA_VISIBLE_DEVICES due to world size in building!

Thanks!
