### ISSUE TITLE
How to use TensorRT-LLM to debug 72B in multiple GPUs

### ISSUE THREAD

**Issue by byjswr** [NVIDIA/TensorRT-LLM#768]
I use the way register the intermediate tensors as the network outputs with `register_network_output` API to Debug Qwen 72B. Due to the model being too large and requiring multiple GPUs to load, I used the method of pipeline parallelism to load the model onto 2 GPUs. However, the results don't seem to be as expected.

TRT-LLM
<img width="749" alt="企业微信截图_17038172179482" src="https://github.com/NVIDIA/TensorRT-LLM/assets/53067559/9979001b-769d-4344-b4f5-46a77fe1bb93">

Torch
<img width="286" alt="企业微信截图_17038174682894" src="https://github.com/NVIDIA/TensorRT-LLM/assets/53067559/0b7872c1-5037-4629-8c2b-acffc8fdd095">

```[tasklist]
### Tasks
```

**Comment by byshiue** [comment]
You could print the shape of PyTorch to make sure you are comparing two same tensors. 

You could also print the previous tensor (like input of qkv) to find the first mismatched point.
