### ISSUE TITLE
summarize.py runs the solution

### ISSUE THREAD

**Issue by lyc728** [NVIDIA/TensorRT-LLM#769]
Hello, do you have an explanation about this score?
rouge1 
rouge2
rougeL
rougeL sum
<img width="356" alt="企业微信截图_1703814568353" src="https://github.com/NVIDIA/TensorRT-LLM/assets/88084847/d051c4b4-f54c-488e-9d3e-ae2b77914fa1">

**Comment by syuoni** [comment]
Hi @lyc728 , Rouge is a (set of) metrics for evaluating text generation tasks, e.g., summarization and machine translation. Higher rouge scores mean better generation results. 

In general, rouge evaluates the overlap between the generated text and referenced text, and 
* rouge1 evaluates the overlapping of unigrams
* rouge2 evaluates the overlapping of bigrams
* rougeL evaluates the overlapping of Longest common subsequence (LCS) 
* rougeLSum is also LCS based, but splits text using "\n"

You may refer to this page (https://huggingface.co/spaces/evaluate-metric/rouge) for more details.
