### ISSUE TITLE
build T4 int4 weight failed

### ISSUE THREAD

**Issue by wangheqi987** [NVIDIA/TensorRT-LLM#771]
[t4_trt_log.txt](https://github.com/NVIDIA/TensorRT-LLM/files/13790723/t4_trt_log.txt)
I tried to buildy int4 weight only but failed, here are the params:
python build.py -m chatglm3_6b --model_dir /home/trt_docker_home/ChatGLM3/chatglm3-6b/ --output_dir /home/trt_docker_home/ChatGLM3/chatglm3_6b_int4/engine/weight_int4_only/T4/ --use_weight_only --weight_only_precision int4 --max_input_len 512 --max_output_len 512 --max_batch 4
and the error: 
[12/29/2023-10:35:28] [TRT] [W] TensorRT was linked against cuDNN 8.9.6 but loaded cuDNN 8.9.4
static void cutlass::gemm::kernel::GemmFpAIntB<Mma_, Epilogue_, ThreadblockSwizzle_, KernelArch, SplitKSerial>::KernelRunner<B, dummy>::run_kernel(const cutlass::gemm::kernel::GemmFpAIntB<Mma_, Epilogue_, ThreadblockSwizzle_, KernelArch, SplitKSerial>::Params &, cutlass::gemm::kernel::GemmFpAIntB<Mma_, Epilogue_, ThreadblockSwizzle_, KernelArch, SplitKSerial>::SharedStorage &) [with __nv_bool B = false; dummy = void; Mma_ = cutlass::gemm::threadblock::DqMmaPipelined<cutlass::gemm::GemmShape<32, 128, 64>, cutlass::transform::threadblock::PredicatedTileIterator<cutlass::MatrixShape<32, 64>, cutlass::half_t, cutlass::layout::RowMajor, 1, cutlass::transform::PitchLinearWarpRakedThreadMap<cutlass::PitchLinearShape<64, 32>, 128, cutlass::PitchLinearShape<8, 4>, 8>, 8, false, cutlass::layout::NoPermute>, cutlass::transform::threadblock::RegularTileIterator<cutlass::MatrixShape<32, 64>, cutlass::half_t, cutlass::layout::RowMajorTensorOpMultiplicandCrosswise<16, 64>, 0, cutlass::transform::PitchLinearWarpRakedThreadMap<cutlass::PitchLinearShape<64, 32>, 128, cutlass::PitchLinearShape<8, 4>, 8>, 16>, cutlass::transform::threadblock::PredicatedTileIterator<cutlass::MatrixShape<256, 32>, cutlass::integer_subbyte<4, false>, cutlass::layout::ColumnMajor, 0, cutlass::transform::PitchLinearWarpRakedThreadMap<cutlass::PitchLinearShape<256, 32>, 128, cutlass::PitchLinearShape<8, 4>, 32>, 32, false, cutlass::layout::NoPermute>, cutlass::transform::threadblock::RegularTileIterator<cutlass::MatrixShape<64, 128>, cutlass::integer_subbyte<4, false>, cutlass::layout::ColumnMajorTensorOpMultiplicandCrosswise<4, 64>, 1, cutlass::transform::PitchLinearWarpRakedThreadMap<cutlass::PitchLinearShape<64, 128>, 128, cutlass::PitchLinearShape<2, 16>, 32>, 16>, cutlass::transform::threadblock::PredicatedTileIterator<cutlass::MatrixShape<1, 128>, cutlass::half_t, cutlass::layout::RowMajor, 0, cutlass::transform::PitchLinearStripminedThreadMap<cutlass::PitchLinearShape<128, 1>, 16, 8>, 8, false, cutlass::layout::NoPermute>, cutlass::transform::threadblock::PredicatedTileIterator<cutlass::MatrixShape<1, 128>, cutlass::half_t, cutlass::layout::RowMajor, 0, cutlass::transform::PitchLinearStripminedThreadMap<cutl%s not implemented
 not implemented

**Comment by jdemouth-nvidia** [comment]
Hi. It looks like you are trying to build an engine for INT4 Weight-only for ChatGLMv3 ; which is not listed as a valid option in this [table](https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/precision.md). It's not a bug. Can you open a feature request please?
