### ISSUE TITLE
No such operator fastertransformer::symmetric_quantize_last_axis_of_batched_matrix

### ISSUE THREAD

**Issue by yyfcc17** [NVIDIA/TensorRT-LLM#780]
i followed the installation process, entered docker, 

then, in ipython, i tried 

`import torch; torch.ops.fastertransformer.symmetric_quantize_last_axis_of_batched_matrix`

then i get the error:

`AttributeError: '_OpNamespace' 'fastertransformer' object has no attribute 'symmetric_quantize_last_axis_of_batched_matrix'`

it seems in `torch.ops.fastertransformer`, there is only a `name` filed, nothing else. what's wrong?

**Comment by juney-nvidia** [comment]
@yyfcc17 
Hi, may I know why do you invoke the `symmetric_quantize_last_axis_of_batched_matric` in such way?
It looks not typical usage of TensorRT-LLM.

June

**Comment by yyfcc17** [comment]
thanks for your quik reply.

i want to investgate the effect of this operation，and other operations  in `torch.ops.fastertransformer`, how can i do this?

**Comment by nv-guomingz** [comment]
> thanks for your quik reply.
> 
> i want to investgate the effect of this operation，and other operations in `torch.ops.fastertransformer`, how can i do this?

<img width="830" alt="image" src="https://github.com/NVIDIA/TensorRT-LLM/assets/137257613/37417cbb-8c90-4138-9d0a-7de96d992bed">

Please `import tensorrt_llm` firstly.

**Comment by yyfcc17** [comment]
@nv-guomingz niubi, it worked, thank you!
