### ISSUE TITLE
unable to launch tensorrt-llm image

### ISSUE THREAD

**Issue by riyaj8888** [NVIDIA/TensorRT-LLM#781]
I USED THE FOLLOWING COMMAD TO BUILD THE IMAGE.

make -C release_build 
Once this image is built,
I added  CMD to launch jupyter lab on top of above built image.

image build successfully on mac , even i provided the ---platform during build but when i am running it , gave below error.

exec /opt/nvidia/nvidia_entrypoint.sh: exec format error

**Comment by juney-nvidia** [comment]
@riyaj8888 
To confirm, so you are trying to build and start the docker on a Mac machine, correct?

June

**Comment by hello-11** [comment]
@riyaj8888 Do you still have the problem? If not, we will close it soon.
