### ISSUE TITLE
setup multi-gpu server got [Errno 98] error while attempting to bind on address ('0.0.0.0', 8000): address already in use

### ISSUE THREAD

**Issue by yjjiang11** [NVIDIA/TensorRT-LLM#784]
when I want to setup 4-gpu llama2-70b server
mpirun --allow-run-as-root -n 4 python examples.server.server  engine_dir tokenizer_dir 
Got [Errno 98] error while attempting to bind on address ('0.0.0.0', 8000): address already in use

**Comment by jdemouth-nvidia** [comment]
Can you give us the command lines used to reproduce the issue, please?

**Comment by yjjiang11** [comment]
docker:image:nvcr.io/nvidia/tritonserver: 23.12-trtllm-python-py3
A800
TensorRT-LLM main branch(2023.12.31)

command:  mpirun --allow-run-as-root -n 4 python examples.server.server engine_dir tokenizer_dir

**Comment by yjjiang11** [comment]
> Can you give us the command lines used to reproduce the issue, please?

I just use this server scripts to setup model server.  just 1-gpu server it works.
https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/server

**Comment by nv-guomingz** [comment]
would u please try our latest code base to see if the issue still exists?

And do u still have further issue or question now? If not, we'll close it soon.
