### ISSUE TITLE
When converting Qwen 72B to TRT, the parameter 'rotary_embedding_base' was not passed to 'gpt_attention'.

### ISSUE THREAD

**Issue by byjswr** [NVIDIA/TensorRT-LLM#785]
When I convert 72B Qwen, I set the parameter 'rotary_base' to 1000000 in build.py.
<img width="392" alt="企业微信截图_17041771436836" src="https://github.com/NVIDIA/TensorRT-LLM/assets/53067559/176c763f-ff40-4a95-9308-52ac7638f2d0">
However, the built result is incorrect. Then I found that in the 'QWenAttention' class of tensorrt_llm/models/qwen/model.py, the forward function of 'gpt_attention' with a missing 'rotary_embedding_base' parameter.
<img width="423" alt="企业微信截图_17041601794224" src="https://github.com/NVIDIA/TensorRT-LLM/assets/53067559/c55eb67f-61c8-4bea-870a-be864d5a3fc8">
<img width="414" alt="企业微信截图_17041602366912" src="https://github.com/NVIDIA/TensorRT-LLM/assets/53067559/db0170c3-80d3-45aa-b5a0-0518141139ef">

**Comment by Shuai-Xie** [comment]
@byshiue Yes. Your observation is certainly correct.

By adding this parameter 'rotary_embedding_base'  to `gpt_attention` funciton, Qwen-72B trtllm engine can generate correct results. This should be added in `forward()` function of `QWenAttention` class.

**Comment by jershi425** [comment]
@byjswr Thank you for your feedback. This issue has been fixed in the main branch. You may try again using the latest code.

**Comment by nv-guomingz** [comment]
Hi @byjswr please feel free to reopen it if needed.
