### ISSUE TITLE
waiting for pre-built wheel package

### ISSUE THREAD

**Issue by ucalyptus** [NVIDIA/TensorRT-LLM#790]
See last conversation in #731

**Comment by Shixiaowei02** [comment]
Please try following these instructions in the [documentation](https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/installation.md) to install the pre-built TensorRT-LLM. If you encounter problems please contact us to solve them, thanks!

**Comment by ncomly-nvidia** [comment]
Closing - please reopen if any issue.
