### ISSUE TITLE
Decoding Logic

### ISSUE THREAD

**Issue by riyaj8888** [NVIDIA/TensorRT-LLM#791]
Hi ,
Is there any way we can change the decoding logic?
example : like support for speculative sampling or other

**Comment by jdemouth-nvidia** [comment]
We are working on adding support for speculative decoding. There's already support for it in the `main` branch as a preview (more work is needed to make it more performant).

**Comment by riyaj8888** [comment]
thanks

**Comment by nv-guomingz** [comment]
Hi @riyaj8888  we've added several speculative decoding in the latest code base. Would u please have a try on that?
And do u still have further issue or question now? If not, we'll close it soon.
