### ISSUE TITLE
OSError: Unable to load weights from pytorch checkpoint file

### ISSUE THREAD

**Issue by isRambler** [NVIDIA/TensorRT-LLM#793]
OSError: Unable to load weights from pytorch checkpoint file for '/root/autodl-tmp/llama-2-7b/pytorch_model-00001-of-00002.bin' at '/root/autodl-tmp/llama-2-7b/pytorch_model-00001-of-00002.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint

Why do I get an error when I use TensorRT-LLM’s build.py to convert the llama-2-7b model?
<img width="199" alt="20240102214805" src="https://github.com/NVIDIA/TensorRT-LLM/assets/118053582/9ea0c519-3e66-4968-87be-f07998476a59">

**Comment by byshiue** [comment]
Please share your scripts to help analyze the issue.

**Comment by isRambler** [comment]
> Please share your scripts to help analyze the issue.

Now I add the .safetensor file and the error becomes like this
<img width="558" alt="6d6c5937150840a78e8d2c08bcb96eb" src="https://github.com/NVIDIA/TensorRT-LLM/assets/118053582/5a8e96f7-f561-4b3d-a00d-47d44714b447">
I run the initial examples/llama/build.py like this:
`python build.py --model_dir /root/autodl_tmp/llama-2-7b-hf \
                --dtype float16 \
                --remove_input_padding \
                --use_gpt_attention_plugin float16 \
                --enable_context_fmha \
                --use_gemm_plugin float16 \
                --output_dir ./tmp/llama/7B/trt_engines/fp16/1-gpu/`

The environment and hardware are as follows
mirror
NVIDIA/TensorRT-LLM/tensorrt_llm:v0.6.1
GPU
A40(48GB)*1
CPU
15 vCPU AMD EPYC 7543 32-Core Processor
Memory
80GB

**Comment by byshiue** [comment]
Could you share the full log? A related issue might be installation of pynvml. You could try installing `pynvml==11.4.1`.

**Comment by isRambler** [comment]
> Could you share the full log? A related issue might be installation of pynvml. You could try installing `pynvml==11.4.1`.

Thank you for your suggestion. After installing `pynvml`, the problem has been solved.
