### ISSUE TITLE
Compile succeed on orin. But can't use 'GPU' option. 

### ISSUE THREAD

**Issue by whk6688** [NVIDIA/TensorRT-LLM#799]
Compile succeed on orin.  but when run 'make -C docker release_run', following error happened:

make: Entering directory '/home/wanghaikuan/code/llm/TensorRT-LLM/docker'
docker run --rm -it --ipc=host --ulimit memlock=-1 --ulimit stack=67108864  \
                --gpus=all \
                --volume /home/wanghaikuan/code/llm/TensorRT-LLM:/code/tensorrt_llm \
                --env "CCACHE_DIR=/code/tensorrt_llm/cpp/.ccache" \
                --env "CCACHE_BASEDIR=/code/tensorrt_llm" \
                --workdir /code/tensorrt_llm \
                --hostname nvidia-desktop-release \
                --name tensorrt_llm-release-wanghaikuan \
                --tmpfs /tmp:exec \
                tensorrt_llm/release:latest
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'csv'
invoking the NVIDIA Container Runtime Hook directly (e.g. specifying the docker --gpus flag) is not supported. Please use the NVIDIA Container Runtime (e.g. specify the --runtime=nvidia flag) instead.: unknown.

so  i must remove 'gpus' option,  then can start up the docker.

**Comment by whk6688** [comment]
and  when run following cmd:
python build.py --hf_model_dir ./tmp/Qwen/Qwen-7B-Chat/ \
                --dtype float16 \
                --remove_input_padding \
                --use_gpt_attention_plugin float16 \
                --enable_context_fmha \
                --use_gemm_plugin float16 \
                --output_dir ./tmp/Qwen/7B/trt_engines/fp16/1-gpu/

OSError: libcuda.so.1: cannot open shared object file: No such file or directory

**Comment by whk6688** [comment]
@Shixiaowei02   pls. help me again. thanks!

**Comment by whk6688** [comment]
Never give up！

**Comment by nv-guomingz** [comment]
Hi @whk6688  we don't support orin yet. please feel free to reopen this ticket if needed.
