### ISSUE TITLE
How to output intermediate result of model?

### ISSUE THREAD

**Issue by yukavio** [NVIDIA/TensorRT-LLM#80]
I am trying to support my LLM model in TRT-LLM. However, there is a significant difference between TRT-LLM and torch. I want to output the intermediate result of TRT-LLM (e.g. gpt_attention) when running prompts to figure out which layer has the precision error.

**Comment by byshiue** [comment]
TensorRT-LLM cannot print intermediate results except the plugin (users can print the intermediates results of plugin in plugin). To print the results, you need to mark the tensor as an output, and get this output after enqueue. This [doc](https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/docs/source/2023-05-19-how-to-debug.md) demonstrates how to debug in TensorRT-LLM.

**Comment by byshiue** [comment]
Close this bug because it is in-activate. Feel free to reopen it if needed.
