### ISSUE TITLE
Why channel wise weightonly gemm do not support add biases?

### ISSUE THREAD

**Issue by MARD1NO** [NVIDIA/TensorRT-LLM#803]
I have seen trtllm annotate the previous implementation like https://github.com/NVIDIA/TensorRT-LLM/blob/main/cpp/tensorrt_llm/kernels/cutlass_kernels/fpA_intB_gemm/fpA_intB_gemm_template.h#L392-L425

and its gemm implementation is https://github.com/NVIDIA/TensorRT-LLM/blob/main/cpp/tensorrt_llm/kernels/cutlass_kernels/fpA_intB_gemm/fpA_intB_gemm_template.h#L447-L463

It set the epilogue as default, but not consider bias. Only groupwise use epilogueBias, it is a little bit confused.

**Comment by Tracin** [comment]
Hi, I think this kernel code is from the FasterTransformer project, could you please check the history commit in that project.
