### ISSUE TITLE
Could you implement the convert and build code under examples/stablediffusion folder?

### ISSUE THREAD

**Issue by felixslu** [NVIDIA/TensorRT-LLM#804]
As issues 323 and 634 mentioned, non LLM transformer model is beginning to support in your frameworks. 
We have found "tensorrt_llm/models/unet" folder in newest repo, and we have redefined SD model by tensorrt-llm api .
So We need more convert and build code which will be located in examples/stablediffusion or examples/unet.

**Comment by juney-nvidia** [comment]
Sorry, but we don't have plan to support stable diffusion models within current TensorRT-LLM yet.

And I will share this request to our prod team. 

June

**Comment by felixslu** [comment]
the value of support SD in TensorRT-LLM :,
Firstly,We can use the TensorRT-LLM Infrastructure to accelerate SD models.
Secondly,We can deplopy LLM and SD in a uniform TensorRT-LLM enviroment, such as agent application case.

**Comment by ncomly-nvidia** [comment]
check out [demo/Diffusion](https://github.com/NVIDIA/TensorRT/tree/release/9.2/demo/Diffusion) in the TensorRT github for the latest TRT accelerated SD.

We won't be adding this to TRT-LLM for the time being, unfortunately .
