### ISSUE TITLE
Why does the whisper model need 17GB of video memory?

### ISSUE THREAD

**Issue by paulxin001** [NVIDIA/TensorRT-LLM#805]
Why does the whisper model need 17GB of video memory? fast-whipser only needs 4G video memory? And I haven't found a way for whisper to quantize Int. Is it not supported now? This video memory occupies too much, is there any way to optimize it?

<img width="658" alt="微信图片_20240104110750" src="https://github.com/NVIDIA/TensorRT-LLM/assets/49224143/ec24d4a0-72cd-4b50-abb3-440b30ee8886">

**Comment by kristiankielhofner** [comment]
It's getting [worked on](https://github.com/NVIDIA/TensorRT-LLM/pull/794).

**Comment by yuekaizhang** [comment]
> It's getting [worked on](https://github.com/NVIDIA/TensorRT-LLM/pull/794).

Yeah, you could try the int8 weight only quantization branch, which greatly reduces the memory usage. 
Also, memory usage should not be a big issue, as the GPU utilization is already high, and freeing up memory would not be used for other tasks.  @paulxin001

**Comment by yuekaizhang** [comment]
@paulxin001 Would you mind trying to removal layernorm plugin and try again? Thank you.

See https://github.com/NVIDIA/TensorRT-LLM/pull/992

**Comment by nv-guomingz** [comment]
Hi @paulxin001 would u please try our latest code base to see if the issue still exists?

And do u still have further issue or question now? If not, we'll close it soon.
