### ISSUE TITLE
Run inference directly from bin/safetensors

### ISSUE THREAD

**Issue by ljayx** [NVIDIA/TensorRT-LLM#809]
Hi,

Currently, we need to build the engine via build.py and store it to disk first, then pass the stored engine to GptSession or GptManager, which increases my time to load the model.

Is it possible for GptSession or GptManager to support pytorch.bin or safetensors models as inputs in which to build the engine and do inference with it directly?

**Comment by byshiue** [comment]
No. Building engine is a necessary step for TensorRT.

**Comment by ljayx** [comment]
Thanks. Closing this issue
