### ISSUE TITLE
[Bug]After llama2 turns on smoothquant, the performance of 0.7.1 may be reduced by about 8 to 10% compared to 0.6.1

### ISSUE THREAD

**Issue by wjj19950828** [NVIDIA/TensorRT-LLM#812]
I am using llama2 for calibration, and the following error will be reported.
main branch 
commit id 6cc5e177ff2fb60b1aab3b03fa0534b5181cf0f1
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/19977378/53af640c-6539-4e96-8c9b-c497845d1b6e)

After typing out the keys of the corresponding [act_scales](https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/llama/smoothquant.py#L203C12-L203C22), I found that there is no linear of mlp, as shown below
0.7.1
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/19977378/5b80d814-8164-462a-bea0-237cd7c484ac)

normal 0.6.1 as follow(commit id:9b3e12dbc820a8b72bcd7d712a8c9a54facf97df)
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/19977378/d3e3c8ea-1666-4ae3-b05b-c0d7b18fef72)

Then when testing the benchmark, I found that the tokens/s of 0.7.1 lags behind 0.6.1 by about 8 to 10%. I don’t know if it is due to the above reasons.

Thanks~

**Comment by wjj19950828** [comment]
@kaiyux @Tracin 
The above calibration error is mainly due to the problem of HF's config and ```pretraining_tp``` parameters, which need to be changed to 1, otherwise [self.mlp](https://github.com/huggingface/transformers/blob/v4.36.1/src/transformers/models/llama/modeling_llama.py#L251) will not be used and the hook will not be hung.

However, the current measured performance is still about 8 to 10% worse than that of 0.6.1. 

Could you please check the reason~

**Comment by Tracin** [comment]
@wjj19950828 Sure, I will try to reproduce the perf.

**Comment by wjj19950828** [comment]
@Tracin build command：
```shell
python build.py --bin_model_dir $BIN_MODEL_PATH \
                --dtype float16 \
                --remove_input_padding \
		--use_gpt_attention_plugin float16 \
                --enable_context_fmha \
                --output_dir $MODEL_PATH \
                --use_inflight_batching \
                --paged_kv_cache \
                --world_size 1 \
                --tp_size 1 \
                --max_batch_size 66 \
                --max_input_len 2048 \
                --max_output_len 512 \
                --vocab_size 49968 \
                --use_smooth_quant \
                --per_token \
                --per_channel \
                --int8_kv_cache
```

**Comment by Tracin** [comment]
@wjj19950828 What is your GPU type? And batch size / input len / output len?

**Comment by wjj19950828** [comment]
> @wjj19950828 What is your GPU type? And batch size / input len / output len?

@Tracin A100，bs = 66/input len 1536/output len 512

**Comment by wjj19950828** [comment]
@Tracin Any update? Thanks~

**Comment by Tracin** [comment]
Sorry, I could not reproduce the regression.
My setting is:
Llama2-13b / bs 48 / input 1536 / output 512 / A100 80G PCIe x 1 and building command is identical to yours (except vocab_size, I use 32000)
Only less than 2% difference between v0.6.1 and v0.7.1.

**Comment by nv-guomingz** [comment]
hi do u still have further issue or question now? If not, we'll close it soon.
