### ISSUE TITLE
Context and Generation Phases

### ISSUE THREAD

**Issue by wangyubo111** [NVIDIA/TensorRT-LLM#816]
See lots of places and configurations mentioning Contenxt Phase and Generation Phase, I also check the document:  https://nvidia.github.io/TensorRT-LLM/gpt_attention.html#context-phase:~:text=in%20the%20future).-,Context%20and%20Generation%20Phases,-%EF%83%81

But still not quite sure the standard definition for these two terms, anyone can help

**Comment by byshiue** [comment]
Context phase handles the inputs and compute the k/v caches of them and generate the first token. Its GEMM sizes are often larger. 

Generation phase is the auto-regressive progress. It uses the last generated tokens and k/v caches to generate new token, and hence the GEMM sizes are often smaller.

**Comment by wangyubo111** [comment]
@byshiue appreciate your answer.
