### ISSUE TITLE
unable to build benchmark

### ISSUE THREAD

**Issue by anchorbob** [NVIDIA/TensorRT-LLM#826]
/code/tensorrt_llm$ python ./scripts/build_wheel.py --benchmarks
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com, https://pypi.ngc.nvidia.com, https://download.pytorch.org/whl/cu121, https://pypi.nvidia.com
Requirement already satisfied: accelerate==0.25.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 3)) (0.25.0)
Requirement already satisfied: build in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 4)) (1.0.3)
Requirement already satisfied: colored in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 5)) (2.2.4)
Requirement already satisfied: cuda-python==12.2.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 6)) (12.2.0)
Requirement already satisfied: diffusers==0.15.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 7)) (0.15.0)
Requirement already satisfied: lark in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 8)) (1.1.8)
Requirement already satisfied: mpi4py in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 9)) (3.1.5)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 10)) (1.22.2)
Requirement already satisfied: onnx>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 11)) (1.14.0)
Requirement already satisfied: polygraphy in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 12)) (0.48.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 13)) (5.9.4)
Requirement already satisfied: pynvml>=11.5.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 14)) (11.5.0)
Requirement already satisfied: sentencepiece>=0.1.99 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 15)) (0.1.99)
Collecting tensorrt==9.2.0.post12.dev5 (from -r requirements.txt (line 16))
  Downloading https://pypi.nvidia.com/tensorrt/tensorrt-9.2.0.post12.dev5.tar.gz (18 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torch in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 17)) (2.1.0a0+32f93b1)
Requirement already satisfied: transformers==4.36.1 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 18)) (4.36.1)
Requirement already satisfied: wheel in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 19)) (0.41.2)
Requirement already satisfied: optimum in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 20)) (1.16.1)
Requirement already satisfied: evaluate in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 21)) (0.4.1)
Requirement already satisfied: janus in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 22)) (1.0.0)
Requirement already satisfied: datasets in /usr/local/lib/python3.10/dist-packages (from -r requirements-dev.txt (line 2)) (2.16.1)
Requirement already satisfied: einops in /usr/local/lib/python3.10/dist-packages (from -r requirements-dev.txt (line 3)) (0.7.0)
Requirement already satisfied: graphviz in /home/lab/.local/lib/python3.10/site-packages (from -r requirements-dev.txt (line 5)) (0.20.1)
Requirement already satisfied: mypy in /home/lab/.local/lib/python3.10/site-packages (from -r requirements-dev.txt (line 6)) (1.8.0)
Requirement already satisfied: parameterized in /home/lab/.local/lib/python3.10/site-packages (from -r requirements-dev.txt (line 7)) (0.9.0)
Requirement already satisfied: pre-commit in /home/lab/.local/lib/python3.10/site-packages (from -r requirements-dev.txt (line 8)) (3.6.0)
Requirement already satisfied: pybind11-stubgen in /home/lab/.local/lib/python3.10/site-packages (from -r requirements-dev.txt (line 9)) (2.4.2)
Requirement already satisfied: pytest-cov in /home/lab/.local/lib/python3.10/site-packages (from -r requirements-dev.txt (line 10)) (4.1.0)
Requirement already satisfied: pytest-forked in /home/lab/.local/lib/python3.10/site-packages (from -r requirements-dev.txt (line 11)) (1.6.0)
Requirement already satisfied: pytest-xdist in /usr/local/lib/python3.10/dist-packages (from -r requirements-dev.txt (line 12)) (3.3.1)
Requirement already satisfied: rouge_score in /home/lab/.local/lib/python3.10/site-packages (from -r requirements-dev.txt (line 13)) (0.1.2)
Requirement already satisfied: typing-extensions==4.8.0 in /home/lab/.local/lib/python3.10/site-packages (from -r requirements-dev.txt (line 14)) (4.8.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from accelerate==0.25.0->-r requirements.txt (line 3)) (23.1)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.10/dist-packages (from accelerate==0.25.0->-r requirements.txt (line 3)) (6.0.1)
Requirement already satisfied: huggingface-hub in /usr/local/lib/python3.10/dist-packages (from accelerate==0.25.0->-r requirements.txt (line 3)) (0.20.2)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from accelerate==0.25.0->-r requirements.txt (line 3)) (0.4.1)
Requirement already satisfied: cython in /usr/local/lib/python3.10/dist-packages (from cuda-python==12.2.0->-r requirements.txt (line 6)) (3.0.3)
Requirement already satisfied: Pillow in /usr/local/lib/python3.10/dist-packages (from diffusers==0.15.0->-r requirements.txt (line 7)) (9.2.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from diffusers==0.15.0->-r requirements.txt (line 7)) (3.12.4)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.10/dist-packages (from diffusers==0.15.0->-r requirements.txt (line 7)) (6.8.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from diffusers==0.15.0->-r requirements.txt (line 7)) (2023.10.3)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from diffusers==0.15.0->-r requirements.txt (line 7)) (2.31.0)
Requirement already satisfied: tokenizers<0.19,>=0.14 in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.1->-r requirements.txt (line 18)) (0.15.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers==4.36.1->-r requirements.txt (line 18)) (4.66.1)
Requirement already satisfied: pyproject_hooks in /usr/local/lib/python3.10/dist-packages (from build->-r requirements.txt (line 4)) (1.0.0)
Requirement already satisfied: tomli>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from build->-r requirements.txt (line 4)) (2.0.1)
Requirement already satisfied: protobuf>=3.20.2 in /usr/local/lib/python3.10/dist-packages (from onnx>=1.12.0->-r requirements.txt (line 11)) (4.24.4)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch->-r requirements.txt (line 17)) (1.12)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch->-r requirements.txt (line 17)) (2.6.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch->-r requirements.txt (line 17)) (3.1.2)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch->-r requirements.txt (line 17)) (2023.6.0)
Requirement already satisfied: coloredlogs in /usr/local/lib/python3.10/dist-packages (from optimum->-r requirements.txt (line 20)) (15.0.1)
Requirement already satisfied: dill in /usr/local/lib/python3.10/dist-packages (from evaluate->-r requirements.txt (line 21)) (0.3.7)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from evaluate->-r requirements.txt (line 21)) (1.5.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.10/dist-packages (from evaluate->-r requirements.txt (line 21)) (3.4.1)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.10/dist-packages (from evaluate->-r requirements.txt (line 21)) (0.70.15)
Requirement already satisfied: responses<0.19 in /usr/local/lib/python3.10/dist-packages (from evaluate->-r requirements.txt (line 21)) (0.18.0)
Requirement already satisfied: pyarrow>=8.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets->-r requirements-dev.txt (line 2)) (11.0.0)
Requirement already satisfied: pyarrow-hotfix in /usr/local/lib/python3.10/dist-packages (from datasets->-r requirements-dev.txt (line 2)) (0.6)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets->-r requirements-dev.txt (line 2)) (3.8.5)
Requirement already satisfied: mypy-extensions>=1.0.0 in /home/lab/.local/lib/python3.10/site-packages (from mypy->-r requirements-dev.txt (line 6)) (1.0.0)
Requirement already satisfied: cfgv>=2.0.0 in /home/lab/.local/lib/python3.10/site-packages (from pre-commit->-r requirements-dev.txt (line 8)) (3.4.0)
Requirement already satisfied: identify>=1.0.0 in /home/lab/.local/lib/python3.10/site-packages (from pre-commit->-r requirements-dev.txt (line 8)) (2.5.33)
Requirement already satisfied: nodeenv>=0.11.1 in /home/lab/.local/lib/python3.10/site-packages (from pre-commit->-r requirements-dev.txt (line 8)) (1.8.0)
Requirement already satisfied: virtualenv>=20.10.0 in /home/lab/.local/lib/python3.10/site-packages (from pre-commit->-r requirements-dev.txt (line 8)) (20.25.0)
Requirement already satisfied: pytest>=4.6 in /usr/local/lib/python3.10/dist-packages (from pytest-cov->-r requirements-dev.txt (line 10)) (7.4.2)
Requirement already satisfied: coverage[toml]>=5.2.1 in /home/lab/.local/lib/python3.10/site-packages (from pytest-cov->-r requirements-dev.txt (line 10)) (7.4.0)
Requirement already satisfied: py in /home/lab/.local/lib/python3.10/site-packages (from pytest-forked->-r requirements-dev.txt (line 11)) (1.11.0)
Requirement already satisfied: execnet>=1.1 in /usr/local/lib/python3.10/dist-packages (from pytest-xdist->-r requirements-dev.txt (line 12)) (2.0.2)
Requirement already satisfied: absl-py in /usr/local/lib/python3.10/dist-packages (from rouge_score->-r requirements-dev.txt (line 13)) (2.0.0)
Requirement already satisfied: nltk in /home/lab/.local/lib/python3.10/site-packages (from rouge_score->-r requirements-dev.txt (line 13)) (3.8.1)
Requirement already satisfied: six>=1.14.0 in /usr/local/lib/python3.10/dist-packages (from rouge_score->-r requirements-dev.txt (line 13)) (1.16.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->-r requirements-dev.txt (line 2)) (23.1.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->-r requirements-dev.txt (line 2)) (3.2.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->-r requirements-dev.txt (line 2)) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->-r requirements-dev.txt (line 2)) (4.0.3)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->-r requirements-dev.txt (line 2)) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->-r requirements-dev.txt (line 2)) (1.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->-r requirements-dev.txt (line 2)) (1.3.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from nodeenv>=0.11.1->pre-commit->-r requirements-dev.txt (line 8)) (68.2.2)
Requirement already satisfied: iniconfig in /usr/local/lib/python3.10/dist-packages (from pytest>=4.6->pytest-cov->-r requirements-dev.txt (line 10)) (2.0.0)
Requirement already satisfied: pluggy<2.0,>=0.12 in /usr/local/lib/python3.10/dist-packages (from pytest>=4.6->pytest-cov->-r requirements-dev.txt (line 10)) (1.3.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc8 in /usr/local/lib/python3.10/dist-packages (from pytest>=4.6->pytest-cov->-r requirements-dev.txt (line 10)) (1.1.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->diffusers==0.15.0->-r requirements.txt (line 7)) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->diffusers==0.15.0->-r requirements.txt (line 7)) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->diffusers==0.15.0->-r requirements.txt (line 7)) (2023.7.22)
Requirement already satisfied: distlib<1,>=0.3.7 in /home/lab/.local/lib/python3.10/site-packages (from virtualenv>=20.10.0->pre-commit->-r requirements-dev.txt (line 8)) (0.3.8)
Requirement already satisfied: platformdirs<5,>=3.9.1 in /usr/local/lib/python3.10/dist-packages (from virtualenv>=20.10.0->pre-commit->-r requirements-dev.txt (line 8)) (3.11.0)
Requirement already satisfied: humanfriendly>=9.1 in /usr/local/lib/python3.10/dist-packages (from coloredlogs->optimum->-r requirements.txt (line 20)) (10.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.10/dist-packages (from importlib-metadata->diffusers==0.15.0->-r requirements.txt (line 7)) (3.16.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch->-r requirements.txt (line 17)) (2.1.3)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk->rouge_score->-r requirements-dev.txt (line 13)) (8.1.6)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk->rouge_score->-r requirements-dev.txt (line 13)) (1.3.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas->evaluate->-r requirements.txt (line 21)) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->evaluate->-r requirements.txt (line 21)) (2023.3)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch->-r requirements.txt (line 17)) (1.3.0)
Building wheels for collected packages: tensorrt
  Building wheel for tensorrt (setup.py) ... done
  Created wheel for tensorrt: filename=tensorrt-9.2.0.post12.dev5-py2.py3-none-any.whl size=17617 sha256=df779de21016eb68d533811e97077504bdffa36a6845d2abfc17d10f341179c9
  Stored in directory: /tmp/pip-ephem-wheel-cache-iv83z4ep/wheels/aa/96/bf/028c219d3560856a5fdb8b3aec8bf01e9d485521c092a64d02
Successfully built tensorrt
Installing collected packages: tensorrt
  Attempting uninstall: tensorrt
    Found existing installation: tensorrt 8.6.0
    Uninstalling tensorrt-8.6.0:
      Successfully uninstalled tensorrt-8.6.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torch-tensorrt 0.0.0 requires tensorrt<8.7,>=8.6, but you have tensorrt 9.2.0.post12.dev5 which is incompatible.
Successfully installed tensorrt-9.2.0.post12.dev5

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python -m pip install --upgrade pip
gmake: Makefile: No such file or directory
gmake: *** No rule to make target 'Makefile'.  Stop.
Traceback (most recent call last):
  File "/code/tensorrt_llm/./scripts/build_wheel.py", line 306, in <module>
    main(**vars(args))
  File "/code/tensorrt_llm/./scripts/build_wheel.py", line 164, in main
    build_run(
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cmake --build . --config Release --parallel 224 --target tensorrt_llm tensorrt_llm_static nvinfer_plugin_tensorrt_llm th_common  benchmarks' returned non-zero exit status 2.

**Comment by xxyux** [comment]
same with you

**Comment by anchorbob** [comment]
figured out this by myself.
I need to add --trt_root in the command to make it work.

`python ./scripts/build_wheel.py --benchmarks --trt_root=/code/tensorrt_llm`

This knob is not explicit in readme file.
