### ISSUE TITLE
Llama Build Issue

### ISSUE THREAD

**Issue by kstyagi23** [NVIDIA/TensorRT-LLM#828]
I tried to build with:

python build.py --model_dir ../../../models/Unholy-v2-13B --dtype float16 --remove_input_padding --use_gpt_attention_plugin float16 --enable_gemm_plugin float16 --enable_context_fmha --output_dir ../../../models/trt_engines/unholy13b/fp16/1-gpu/

Traceback (most recent call last):
 File "/TensorRT-LLM/examples/llama/build.py", line 47, in <module>
 from tensorrt_llm.models.llama.weight import (  # isort:skip
ModuleNotFoundError: No module named 'tensorrt_llm.models.llama.weight'

Does anyone knows potential solution for this?
Thanks.

===================================================

I installed TensorRT-LLM from the wheel

**Comment by ngoanpv** [comment]
I think there is a bug. As a solution, you could try cloning this repository and modifying the weight.py file, which is imported from the build.py file. This should fix the issue.

**Comment by ngoanpv** [comment]
I successfully built the llama using the code modifications made following my PR at https://github.com/NVIDIA/TensorRT-LLM/pull/834 .

**Comment by litaotju** [comment]
@kstyagi23 could you try latest main branch? And are you build from source?

The possible issue is that the the pre-built whl and the example code you are running are not from same commit.
We recently moved the weight.py into the tensorrt_llm/models/llama dir, the change may not be inside the whl package yet.

Pls re-open the issue if you still see the problem with latest main. Thank you

**Comment by kstyagi23** [comment]
Hey @ngoanpv, apologies for the delayed response.
Thanks for the update, I'll check it out.

Thanks @litaotju for letting me know... I'll test it out!

Cheers ✌️
