### ISSUE TITLE
What are the differences between contextFusedMultiHeadAttention and decoderMaskedMultiheadAttention?

### ISSUE THREAD

**Issue by CarkusL** [NVIDIA/TensorRT-LLM#830]
It seems that contextFusedMultiHeadAttention and decoderMaskedMultiheadAttention are both implementations of MultiHeadAttention. What are the differences between them?

**Comment by PerkzZheng** [comment]
> It seems that contextFusedMultiHeadAttention and decoderMaskedMultiheadAttention are both implementations of MultiHeadAttention. What are the differences between them?

1. `contextFusedMultiHeadAttention` is designed for the context (prefill) phase that QKV has the same sequence length. The kernels are highly optimized based on flash attention. 
2. `decoderMaskedMultiheadAttention` is designed for the generation phase where query sequence length = 1, and it has to read from kv cache .The dot product operation for this case is memory bound, and it only utilizes cuda cores in most cases. 
     - Note that we also have optimized [XQA kernels ](https://github.com/NVIDIA/TensorRT-LLM/blob/main/cpp/tensorrt_llm/kernels/decoderMaskedMultiheadAttention/decoderXQARunner.cpp) for GQA/MQA. You will need to set `TRTLLM_ENABLE_XQA=1 TRTLLM_FORCE_XQA=1` in order to use this optimized kernel. We will have more detailed documentation in the next update.

**Comment by CarkusL** [comment]
> > It seems that contextFusedMultiHeadAttention and decoderMaskedMultiheadAttention are both implementations of MultiHeadAttention. What are the differences between them?
> 
> 1. `contextFusedMultiHeadAttention` is designed for the context (prefill) phase that QKV has the same sequence length. The kernels are highly optimized based on flash attention.
> 2. `decoderMaskedMultiheadAttention` is designed for the generation phase where query sequence length = 1, and it has to read from kv cache .The dot product operation for this case is memory bound, and it only utilizes cuda cores in most cases.
>    
>    * Note that we also have optimized [XQA kernels ](https://github.com/NVIDIA/TensorRT-LLM/blob/main/cpp/tensorrt_llm/kernels/decoderMaskedMultiheadAttention/decoderXQARunner.cpp) for GQA/MQA. You will need to set `TRTLLM_ENABLE_XQA=1 TRTLLM_FORCE_XQA=1` in order to use this optimized kernel. We will have more detailed documentation in the next update.

Thank you for your reply.
