### ISSUE TITLE
What is the relationship between GptManager and GptSession？

### ISSUE THREAD

**Issue by tingkuanpei** [NVIDIA/TensorRT-LLM#833]
GptManager is used in triton for online serving, and it supports in-flight batching, system prompt caching. What is the relationship between GptManager and GptSession？Does GptManager use GptSession to manage and call the TensorRT engine?

**Comment by MartinMarciniszyn** [comment]
`GptSession` does not support in-flight batching. It can be instantiated inside `GptManager` by passing`TrtGptModelType::V1` to the constructor. However, this is only recommended for testing. Deployments with Triton are recommended to use `TrtGptModelInflightBatching`, which is the default implementation of `TrtGptModel`.
