### ISSUE TITLE
[Question]How SmoothQuant supports tp>1

### ISSUE THREAD

**Issue by wjj19950828** [NVIDIA/TensorRT-LLM#837]
Because of the ```pretraining_tp``` parameter, the linear hook of [mlp](https://github.com/huggingface/transformers/blob/v4.36.1/src/transformers/models/llama/modeling_llama.py#L368C24-L368C38) is not hung up when tp>1. If I want to run the 70b model, because a card will definitely OOM, how to support tp>1?

related issue:https://github.com/NVIDIA/TensorRT-LLM/issues/812

**Comment by Tracin** [comment]
You can just set `pretraining_tp=1` and use multi-gpus, since accelerate package will split the model in PP.
