### ISSUE TITLE
Need much more gpu mem vs vllm when large max batch size.

### ISSUE THREAD

**Issue by zhaocc1106** [NVIDIA/TensorRT-LLM#839]
# ENV
```
GPU: 2080Ti * 4（12G mem *4）
Mem：128G
CUDA: 12.2
Pytorch：2.1.0
Transformers：4.31.0
TensorRT：9.1.0.post12.dev4
TensorRT-LLM：0.5.0
Triton-trt-llm-backend：0.5.0
Triton：23.10
VLLM：0.2.7
```

# Description
When i use trt-llm to infer llama-13B vs vllm. I found trt-llm use much more gpu mem than vllm when large batch size.  In my experiment, i use 4 * 2080Ti (12G mem * 4) to deploy llama-13B with trt-llm 4 tp. I can ony set the max batch size to 8 when buiding. If use parallel requests(> 8), the throuput will not increase any more. But vllm will perform ok, and throuput will surpasses trt-llm. Even parallel requests > 32, its throuput can also increase a little. 
I know my gpu mem cannot set trt-llm max_batch_size > 8, so have above results. Will trt-llm optimize for large batch size in the future?

| parallel client count  |  1                  | 2                  | 4                  | 6                  | 8                  | 10                | 16                |
|----------|--------------------|--------------------|--------------------|--------------------|--------------------|-------------------|-------------------|
| vLLM     | 100.35637203966101 | 175.33636524799965 | 334.88131962239555 | 397.3896368771922  | 491.34020273262286 | 556.8166653073029 | 778.7324831232992 |
| TRT-LLM  | 129.26274339032346 | 225.27019417811525 | 357.43462059657065 | 450.6078057271692  | 577.647144114447   | 547.9468736633614 | 538.0739087909661 |
| vs     | +28.80%     | +28.48%            | +6.73%             | +13.39%            | +17.57%            | -1.59%             | -30.90%            |

**Comment by wang90063** [comment]
@zhaocc1106 Could you clarify more details of your test? Like the prompt input and output length and the paramters of triton backend?

We are also building test environment of  tensorrtllm infilight batching v.s. vllm. 

@byshiue @juney-nvidia Perhaps we need an official demo of infilight batching (especially for python runtime, since vllm is python runtime and very easy-to-use) ensuring we are using tensorrtllm correctly. 

Keep eye on this issue :)

**Comment by nv-guomingz** [comment]
would u please try our latest code base to see if the issue still exists?

And do u still have further issue or question now? If not, we'll close it soon.
