### ISSUE TITLE
Build Llama-2-70B AWQ in TP8 Error

### ISSUE THREAD

**Issue by lydecho** [NVIDIA/TensorRT-LLM#843]
```
python quantize.py --model_dir llama-2-70b \
                --dtype float16 \
                --qformat int4_awq \
                --export_path ./quantized_int4-awq-llama2-70b \
                --calib_size 32
```
```
export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
python build.py --model_dir llama-2-70b \
                --quant_ckpt_path ../quantization/quantized_int4-awq-llama2-70b/llama_tp1_rank0.npz \
                --dtype float16 \
                --remove_input_padding \
                --use_gpt_attention_plugin float16 \
                --enable_context_fmha \
                --use_gemm_plugin float16 \
                --use_weight_only \
                --weight_only_precision int4_awq \
                --per_group \
                --world_size 8 \
                --tp_size 8 \
                --output_dir /workdir/trt_engines/llama2-70b/int4_AWQ/8-gpu/ \
                --max_batch_size 32 \
                --max_input_len 4096
```

Error_Info:
Assertion failed: Number of bytes for rows and cols must be a multiple of 32. However, num_rows_bytes = 4096 and num_col_bytes = 2000. (/workdir/TensorRT-LLM/cpp/tensorrt_llm/kernels/cutlass_kernels/cutlass_preprocessors.cpp:255)

**Comment by dominicshanshan** [comment]
@lydecho, small update, after change TP=4 and PP=2 AWQ works

**Comment by NaNAGISaSA** [comment]
same error for v0.7.1 version.

**Comment by dominicshanshan** [comment]
@lydecho @NaNAGISaSA , in ../examples/llama/build.py , change the value to 512
![2024-02-24 at 11 12](https://github.com/NVIDIA/TensorRT-LLM/assets/30051912/ea303c98-c0e0-43a0-a8a2-15e98a9ebb12)
in ../examples/llama/weight.py, change the value to 512
![2024-02-24 at 11 13](https://github.com/NVIDIA/TensorRT-LLM/assets/30051912/d780dc83-b0ab-4e4e-bb4c-63c0eafa48fa)

**Comment by nv-guomingz** [comment]
please feel free to reopen this ticket if needed.
