### ISSUE TITLE
[Question]Smooth quant int8 gemm

### ISSUE THREAD

**Issue by enozhu** [NVIDIA/TensorRT-LLM#845]
I found trtllm process smooth quant  like this
1. smooth & quant input to int8
2. int8 gemm
3. dequant  int8 gemm output to  fp16
4. **quant** gemm output and then **dequant**  it (fake quant), like QAT

**I can't understand the 4th  operation,  why we use fake quant ?  is this op necessary？ Thanks for explaning**

**Comment by Tracin** [comment]
Yes you are right, and we will have a new version of SQ soon which is optimized by remove the 4th operation.
