### ISSUE TITLE
Failed to Run batch size larger than 8 with LLaMA 13B

### ISSUE THREAD

**Issue by CarsonSo** [NVIDIA/TensorRT-LLM#85]
Hi guys, I am trying to benchmark LLaMA 13B under different batch sizes (1, 2, 4, 8, 16, 32, 64, etc.). It works fine for bs=1,2,4,8 but error is raised when bs larger than 8. Here is the output:
```
Batch Size: 1, Setup Cost: 0.004654481075704098 seconds. All tokens: 115. Input tokens: 51. Cost: 1.50110586239025 seconds. Speed: 76.6101864507294 tokens/s.
The 0 Sample
                Inputs: <human>:今天天气大概 25度，有点小雨，吹着风，我想去户外散步，应该穿什么样的衣服 裤子鞋子搭配\n<bot>:. 
                Outputs: 建议穿轻便的外套，例如薄外套或夹克，可以保护你免受雨淋。另外，穿一件长袖衬衫和一条轻便的裤子，可以保持舒适。搭配一双轻便的运动
/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py:658: UserWarning: The PyTorch API of nested tensors is in prototype stage and will change in the near future. (Triggered internally at /opt/pytorch/pytorch/aten/src/ATen/NestedTensorImpl.cpp:178.)
  torch.nested.nested_tensor(split_ids_list,

Batch Size: 2, Setup Cost: 0.029597636312246323 seconds. All tokens: 230. Input tokens: 51. Cost: 1.5330675791949033 seconds. Speed: 150.0260021941012 tokens/s.

Batch Size: 4, Setup Cost: 0.015678859781473875 seconds. All tokens: 460. Input tokens: 51. Cost: 1.5876490180380642 seconds. Speed: 289.7365820617233 tokens/s.

Batch Size: 8, Setup Cost: 0.053842300083488226 seconds. All tokens: 920. Input tokens: 51. Cost: 1.6747497936710716 seconds. Speed: 549.335789427595 tokens/s.
[10/24/2023-04:02:38] [TRT] [E] 3: [executionContext.cpp::setInputShape::2288] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2288, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
Traceback (most recent call last):
  File "/myhome/TensorRT-LLM/examples/llama/run_batch.py", line 342, in <module>
    generate(**vars(args))
  File "/myhome/TensorRT-LLM/examples/llama/run_batch.py", line 295, in generate
    output_gen_ids = decoder.decode(input_ids,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 514, in wrapper
    ret = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 1887, in decode
    return self.decode_regular(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 1659, in decode_regular
    should_stop, next_step_buffer, tasks, context_lengths, host_context_lengths, attention_mask, logits = self.handle_per_step(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 1430, in handle_per_step
    self.runtime._set_shape(context, ctx_shape)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 202, in _set_shape
    raise ValueError(
ValueError: Couldn't assign past_key_value_0 with shape torch.Size([16, 2, 40, 114, 128]), engine supports [min, opt, max] = [(1, 2, 40, 0, 128), (4, 2, 40, 1280, 128), (8, 2, 40, 2560, 128)]
```

It seems like the optimized model cannot support batch size more than 8.

**Comment by uppalutkarsh** [comment]
Hi, you can use `--max_batch_size` arg during the build phase. By default, the value is 8 for LLaMA which means the engine supports `max_batch_size` of 8, hence you are getting this error.

https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/examples/llama/build.py#L158

**Comment by CarsonSo** [comment]
Thanks for pointing out. It works perfectly for `--max_batch_size 64`. However I still got other error for larger max_batch_size (128).

I tried using `--max_batch_size 128` during build phase. The following is part of the logging:
```
[10/24/2023-06:48:50] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +1, GPU +10, now: CPU 33310, GPU 1645 (MiB)
[10/24/2023-06:48:50] [TRT] [I] Global timing cache in use. Profiling results in this builder pass will be stored.
[10/24/2023-06:48:53] [TRT] [W] Tactic Device request: 41472MB Available: 40338MB. Device memory is insufficient to use tactic.
[10/24/2023-06:48:53] [TRT] [W] UNSUPPORTED_STATESkipping tactic 0 due to insufficient memory on requested size of 41472 detected for tactic 0x0000000000000000.
[10/24/2023-06:48:53] [TRT] [W] Tactic Device request: 41472MB Available: 40338MB. Device memory is insufficient to use tactic.
[10/24/2023-06:48:53] [TRT] [W] UNSUPPORTED_STATESkipping tactic 1 due to insufficient memory on requested size of 41472 detected for tactic 0x0000000000000001.
[10/24/2023-06:48:54] [TRT] [W] Tactic Device request: 41472MB Available: 40338MB. Device memory is insufficient to use tactic.
```

And here is the output when I benchmark the complied LLaMA 13B model (max_batch_size=128) :
```
Traceback (most recent call last):
  File "/myhome/TensorRT-LLM/examples/llama/run_batch.py", line 342, in <module>
    generate(**vars(args))
  File "/myhome/TensorRT-LLM/examples/llama/run_batch.py", line 274, in generate
    decoder = tensorrt_llm.runtime.GenerationSession(model_config,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 306, in __init__
    self.runtime = _Runtime(engine_buffer, mapping)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 143, in __init__
    self.__prepare(mapping, engine_buffer)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 163, in __prepare
    address = CUASSERT(cudart.cudaMalloc(self.engine.device_memory_size))[0]
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 92, in CUASSERT
    raise RuntimeError(
RuntimeError: CUDA ERROR: 2, error code reference: https://nvidia.github.io/cuda-python/module/cudart.html#cuda.cudart.cudaError_t
Exception ignored in: <function _Runtime.__del__ at 0x7f38a4efbd90>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 232, in __del__
    cudart.cudaFree(self.address)
AttributeError: '_Runtime' object has no attribute 'address'
```

**Comment by jdemouth-nvidia** [comment]
What’s the exact command and the GPU? Are you sure you have enough memory to run that particular case?

**Comment by CarsonSo** [comment]
I am using A100(40G). In this case, #input_token=51, #max_output_token=64, bs=1.

It works fine using the compiled model with `--max_batch_size 64` but goes wrong using the model `--max_batch_size 128`.

**Comment by byshiue** [comment]
> I am using A100(40G). In this case, #input_token=51, #max_output_token=64, bs=1.
> 
> It works fine using the compiled model with `--max_batch_size 64` but goes wrong using the model `--max_batch_size 128`.

Can you share the building script? There are many arguments related to memory usage.

**Comment by CarsonSo** [comment]
```
HF_model_path=XX
ENGINE_path=XX
python build.py --model_dir $HF_model_path \
                --dtype float16 \
                --remove_input_padding \
                --use_gpt_attention_plugin float16 \
                --enable_context_fmha \
                --use_gemm_plugin float16 \
                --max_batch_size 128 \
                --output_dir $ENGINE_path
```

**Comment by byshiue** [comment]
> HF_model_path=XX
> ENGINE_path=XX
> python build.py --model_dir $HF_model_path \
>                 --dtype float16 \
>                 --remove_input_padding \
>                 --use_gpt_attention_plugin float16 \
>                 --enable_context_fmha \
>                 --use_gemm_plugin float16 \
>                 --max_batch_size 128 \
>                 --output_dir $ENGINE_path

The default input length of llama build.pay is 2048, you can try using smaller number if you don’t really need such long length.

**Comment by litaotju** [comment]
This issue is duplicated (same root cause) with the issue https://github.com/NVIDIA/TensorRT-LLM/issues/67
Please try to change the max_batch_size and the max_input_len to be smaller one, which close to the actual batch size used in the runtime.

**Comment by suluyana** [comment]
I have met the same

**Comment by suluyana** [comment]
> Thanks for pointing out. It works perfectly for `--max_batch_size 64`. However I still got other error for larger max_batch_size (128).
> 
> I tried using `--max_batch_size 128` during build phase. The following is part of the logging:
> 
> ```
> [10/24/2023-06:48:50] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +1, GPU +10, now: CPU 33310, GPU 1645 (MiB)
> [10/24/2023-06:48:50] [TRT] [I] Global timing cache in use. Profiling results in this builder pass will be stored.
> [10/24/2023-06:48:53] [TRT] [W] Tactic Device request: 41472MB Available: 40338MB. Device memory is insufficient to use tactic.
> [10/24/2023-06:48:53] [TRT] [W] UNSUPPORTED_STATESkipping tactic 0 due to insufficient memory on requested size of 41472 detected for tactic 0x0000000000000000.
> [10/24/2023-06:48:53] [TRT] [W] Tactic Device request: 41472MB Available: 40338MB. Device memory is insufficient to use tactic.
> [10/24/2023-06:48:53] [TRT] [W] UNSUPPORTED_STATESkipping tactic 1 due to insufficient memory on requested size of 41472 detected for tactic 0x0000000000000001.
> [10/24/2023-06:48:54] [TRT] [W] Tactic Device request: 41472MB Available: 40338MB. Device memory is insufficient to use tactic.
> ```
> 
> And here is the output when I benchmark the complied LLaMA 13B model (max_batch_size=128) :
> 
> ```
> Traceback (most recent call last):
>   File "/myhome/TensorRT-LLM/examples/llama/run_batch.py", line 342, in <module>
>     generate(**vars(args))
>   File "/myhome/TensorRT-LLM/examples/llama/run_batch.py", line 274, in generate
>     decoder = tensorrt_llm.runtime.GenerationSession(model_config,
>   File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 306, in __init__
>     self.runtime = _Runtime(engine_buffer, mapping)
>   File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 143, in __init__
>     self.__prepare(mapping, engine_buffer)
>   File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 163, in __prepare
>     address = CUASSERT(cudart.cudaMalloc(self.engine.device_memory_size))[0]
>   File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 92, in CUASSERT
>     raise RuntimeError(
> RuntimeError: CUDA ERROR: 2, error code reference: https://nvidia.github.io/cuda-python/module/cudart.html#cuda.cudart.cudaError_t
> Exception ignored in: <function _Runtime.__del__ at 0x7f38a4efbd90>
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/runtime/generation.py", line 232, in __del__
>     cudart.cudaFree(self.address)
> AttributeError: '_Runtime' object has no attribute 'address'
> ```

I have met the same error. Any progress on this issue?

**Comment by obhalerao97** [comment]
I'm trying to run batches of prompts but I'm unable to find the `run_batch.py` file for **Llama**, can someone please point me to this?

**Comment by byshiue** [comment]
@obhalerao97 The script should be implemented by @CarsonSo .

**Comment by byshiue** [comment]
Close this bug because the issue is inactivated. Feel free to ask here if you still have question/issue, we will reopen the issue (recommand trying latest main branch again).
