### ISSUE TITLE
Observing a regression in FP8 performance, between versions 0.5.0 and 0.7.1

### ISSUE THREAD

**Issue by ashish007git** [NVIDIA/TensorRT-LLM#851]
I ran LLAMA_70b model on two different version (v0.5.0 and v0.7.0) with the following commands:

Building the engine:

```
export NUM_GPUS=8

python examples/llama/build.py --remove_input_padding --enable_context_fmha --parallel_build --output_dir /code/outputs/engines/llama70b_tp${NUM_GPUS}_fp8_bs32_isl8192_osl512 --dtype float16 --use_gpt_attention_plugin float16 --world_size ${NUM_GPUS} --tp_size ${NUM_GPUS} --pp_size 1 --max_batch_size 32 --max_input_len 8192 --max_output_len 512 --enable_fp8 --fp8_kv_cache --strongly_typed --n_layer 80 --n_head 64 --n_kv_head 8 --n_embd 8192 --inter_size 28672 --vocab_size 32000 --n_positions 4096 --hidden_act silu --ffn_dim_multiplier 1.3 --multiple_of 4096
```

Running the model:

```
mpirun -n ${NUM_GPUS} --allow-run-as-root ./cpp/build/benchmarks/gptSessionBenchmark --model llama --engine_dir /code/outputs/engines/llama70b_tp${NUM_GPUS}_fp8_bs32_isl8192_osl512 --warm_up 1 --batch_size "1;4;8;16" --duration 0 --num_runs 5 --input_output_len "8192,1;8192,256" 2>&1 | tee benchmark_llama70_fp8_tp${NUM_GPUS}_8192.txt
```

The performance for 8k context length is as follows:

| Batch Size| Output tokens | v0.5 Latency | v0.7 Latency |
|---|---|---|---|
| 1 | 1 | 292.48 | 308.84 |
| 4 | 1 | 1069.32  | 1103.08 |
| 8 | 1 | 2101.68  | 2179.83 |
| 16 | 1  | 3647.88  | 3889.61 | 
| 1 | 256 | 4767.70 | 5414.17 |  
| 4 | 256 | 5644.52 | 6302.31 |
| 8 | 256 | 6722.70 | 7440.15 |
| 16 | 256 | 8352.28 | 9204.05 |

I have not checked this regressions for FP16. Also, I rebuilt the docker containers from scratch for the two versions, by using the following commands

```
make -C docker build CUDA_ARCHS="90-real"

make -C docker run

python3 ./scripts/build_wheel.py --cuda_architectures="90-real" --clean  --trt_root /usr/local/tensorrt

pip install ./build/tensorrt_llm*.whl

pushd cpp/build/benchmarks

make

popd
```

Any hints on why the regression happens are appreciated.

**Comment by ashish007git** [comment]
The above issue is observed when the head (in main branch) was at commit id ` 6cc5e177ff2fb60b1aab3b03fa0534b5181cf0f1`

The current head fails to successfully run the above commands.  I was able to run everything without any regression with the head for the at `tags/v0.7.0`. 

I can close this issue, if there are no other updates.

**Comment by Tracin** [comment]
We have reproduced the regression, we are investigating on it. Thanks!

**Comment by sadreamer** [comment]
Hi @Tracin, any updates on this issue? It seems it persists in v0.9.0 as well - I'm experiencing a 10-20% performance drop compared to v0.5.0

**Comment by nv-guomingz** [comment]
Hi @ashish007git would u please try our latest code base to see if the issue still exists?

And do u still have further issue or question now? If not, we'll close it soon.
