### ISSUE TITLE
Fail to build engine for smoothquantized llama-13b

### ISSUE THREAD

**Issue by moonlightian** [NVIDIA/TensorRT-LLM#852]
With trt-llm 0.7.2 and codes from branch main: examples/llama
After calculating scales with hf_llama_checkpoint.py , it fails to build engine with output files generated with the command
```
CUDA_VISIBLE_DEVICES=4 python hf_llama_convert.py -i /home/work/models/llama2-13b/ -o /home/work/TensorRT-LLM-main/examples/llama/13B_new/sq0.5/ -sq 0.5 --tensor-parallelism 1 --storage-type fp16
```
with command
```
CUDA_VISIBLE_DEVICES=1 python3 build.py --bin_model_dir=/home/work/TensorRT-LLM-main/examples/llama/13B_new/smooth_llama_13B/sq0.5/1-gpu/1-gpu/ --use_smooth_quant --per_token --per_channel --output_dir ./13B/trt_engines/int8_sq/1-gpu/ --tp_size 1 --use_gpt_attention_plugin float16 --use_gemm_plugin float16
```
errors like:
```
Traceback (most recent call last):
  File "/home/work/TensorRT-LLM-main/examples/llama/build.py", line 934, in <module>
    build(0, args)
  File "/home/work/TensorRT-LLM-main/examples/llama/build.py", line 878, in build
    engine = build_rank_engine(builder, builder_config, engine_name,
  File "/home/work/TensorRT-LLM-main/examples/llama/build.py", line 800, in build_rank_engine
    tensorrt_llm_llama(*inputs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/module.py", line 40, in __call__
    output = self.forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/model.py", line 447, in forward
    hidden_states = super().forward(input_ids, position_ids, use_cache,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/model.py", line 294, in forward
    hidden_states = layer(
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/module.py", line 40, in __call__
    output = self.forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/llama/model.py", line 161, in forward
    hidden_states = self.mlp(hidden_states,
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/module.py", line 40, in __call__
    output = self.forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/quantization/layers.py", line 869, in forward
    smoother = cast(self.proj.smoother.value, self.dtype)
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/module.py", line 55, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'SmoothQuantGatedMLP' object has no attribute 'dtype'
```

**Comment by nv-guomingz** [comment]
Hi @moonlightian , the build cmd u mentioned `CUDA_VISIBLE_DEVICES=1 python3 build.py --bin_model_dir=/home/work/TensorRT-LLM-main/examples/llama/13B_new/smooth_llama_13B/sq0.5/1-gpu/1-gpu/ --use_smooth_quant --per_token --per_channel --output_dir ./13B/trt_engines/int8_sq/1-gpu/ --tp_size 1 --use_gpt_attention_plugin float16 --use_gemm_plugin float16
` may have typo here.

Specifically, it should be `bin_model_dir=/home/work/TensorRT-LLM-main/examples/llama/13B_new/smooth_llama_13B/sq0.5/1-gpu/ ` rather than `bin_model_dir=/home/work/TensorRT-LLM-main/examples/llama/13B_new/smooth_llama_13B/sq0.5/1-gpu/1-gpu/ `.

**Comment by moonlightian** [comment]
@nv-guomingz Hi, thank you for your kind reply. Well double sub-dir 1-gpu is not typo here as it just the output path for hf_llama_convert.py with --tensor-parallelism 1. And it may not be the reason for errors mentioned before. Could you please try to reproduce the issue for llama smoothquant?

**Comment by moonlightian** [comment]
Well，I fixed this issue by modifying the code, but, however, it still remains a bug.
tensorrt_llm/quantization/layers.py should be modified by adding self.dtype = dtype in class SmoothQuantGatedMLP which could be found in line 826
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/49636631/f515e9a3-2f5c-432c-b624-d53f3d202cfc)

**Comment by nv-guomingz** [comment]
Hi @moonlightian ,

I tried the latest commit of main branch (12e82e30b0e64b0f7ada0dc5993edd3b05385964 ) and I can't reproduce such build issue.


1. I noticed that you mentioned you're using 

> With trt-llm 0.7.2 and codes from branch main: examples/llama

trt-llm didn't release 0.7.2 yet till now.  


2. For  > Well double sub-dir 1-gpu is not typo here as it just the output path for hf_llama_convert.py with --tensor-parallelism 1

My local output folder path for sq doesn't contain double **1-gpu** . The tensor-parallelism will define the number before string -gpu. It means if you set tensor-parallelism to 2, the outout folder should be 2-gpu.

3. The latest commit(12e82e30b0e64b0f7ada0dc5993edd3b05385964)  already has such [definition](https://github.com/NVIDIA/TensorRT-LLM/blob/main/tensorrt_llm/quantization/layers.py#L600) on class SmoothquantMLP.

**Comment by moonlightian** [comment]
> 3. The latest commit([12e82e3](https://github.com/NVIDIA/TensorRT-LLM/commit/12e82e30b0e64b0f7ada0dc5993edd3b05385964))  already has such [definition](https://github.com/NVIDIA/TensorRT-LLM/blob/main/tensorrt_llm/quantization/layers.py#L600) on class SmoothquantMLP.

Thank you @nv-guomingz I would check it with latest codes

**Comment by Hukongtao** [comment]
> Well，I fixed this issue by modifying the code, but, however, it still remains a bug. tensorrt_llm/quantization/layers.py should be modified by adding self.dtype = dtype in class SmoothQuantGatedMLP which could be found in line 826 ![image](https://private-user-images.githubusercontent.com/49636631/295477218-f515e9a3-2f5c-432c-b624-d53f3d202cfc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNTE5MjcsIm5iZiI6MTcwNTA1MTYyNywicGF0aCI6Ii80OTYzNjYzMS8yOTU0NzcyMTgtZjUxNWU5YTMtMmY1Yy00MzJjLWI2MjQtZDUzZjNkMjAyY2ZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDA5MjcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3YTlhNWEyZWY5YTI2YWM2ZjI1OTM3NTBhMjQ3YmU5OGExMWY4MWVmNGYzNzU2MmY4YmYxYTRlNDdiMWUyZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D2qUqPPm8umBpYLUO0WLa1nSUDJDDnt1QVf07TsQ2TQ)

I met the same error, and it can be fix with your method. Tensorrt-llm version 0.7.1

**Comment by nv-guomingz** [comment]
> > Well，I fixed this issue by modifying the code, but, however, it still remains a bug. tensorrt_llm/quantization/layers.py should be modified by adding self.dtype = dtype in class SmoothQuantGatedMLP which could be found in line 826 ![image](https://private-user-images.githubusercontent.com/49636631/295477218-f515e9a3-2f5c-432c-b624-d53f3d202cfc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNTE5MjcsIm5iZiI6MTcwNTA1MTYyNywicGF0aCI6Ii80OTYzNjYzMS8yOTU0NzcyMTgtZjUxNWU5YTMtMmY1Yy00MzJjLWI2MjQtZDUzZjNkMjAyY2ZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDA5MjcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3YTlhNWEyZWY5YTI2YWM2ZjI1OTM3NTBhMjQ3YmU5OGExMWY4MWVmNGYzNzU2MmY4YmYxYTRlNDdiMWUyZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D2qUqPPm8umBpYLUO0WLa1nSUDJDDnt1QVf07TsQ2TQ)
> 
> I met the same error, and it can be fix with your method. Tensorrt-llm version 0.7.1

That's because 0.7.1 doesn't contain our latest fixing and improvement.

Please try our main branch.
