### ISSUE TITLE
When will deepseek models be supported ?

### ISSUE THREAD

**Issue by shatealaboxiaowang** [NVIDIA/TensorRT-LLM#856]
I recently tried to build the Magicoder-DS-6.7B model (fine-tuned on Deepseek coder). The build worked, but the output was problematic. 
request is:
curl -X POST localhost:8035/v2/models/ensemble/generate -d '{"text_input": "import numpy", "max_tokens": 20, "bad_words": "", "stop_words":""}'
output is:
{"cum_log_probs":0.0,"model_name":"ensemble","model_version":"1","output_log_probs":[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],"sequence_end":false,"sequence_id":0,"sequence_start":false,"text_output":"<｜begin▁of▁sentence｜>import numpy py py py py py py py py py py py py py py py py py py py py"}

Clearly unreasonable output,  have you encountered a similar situation? How to solve it?

**Comment by byshiue** [comment]
Please share the end to end steps to reproduce your issue.

**Comment by shatealaboxiaowang** [comment]
> Please share the end to end steps to reproduce your issue.

thx，have fixed it.

**Comment by viningz** [comment]
> > Please share the end to end steps to reproduce your issue.
> 
> thx，have fixed it.

大佬，请问你是怎么解决这个生成的乱码问题呢？deepseek我用VLLM和tensorrt-llm都遇到乱码的问题。

**Comment by thanhtung901** [comment]
> > Please share the end to end steps to reproduce your issue.
> 
> thx，have fixed it.

How did you fixed it, I had the same issue

**Comment by bowencarry** [comment]
My friend, I have the same problem, with deepseek models, the whole model conversion process is no problem, but loading and generating will keep repeating a single token, how did you solve it?

**Comment by nv-guomingz** [comment]
Hi @shatealaboxiaowang we've supported deepseek, please have a try on the latest code base.

And do u still have further issue or question now? If not, we'll close it soon.
