### ISSUE TITLE
Transformers version conflicts during running build_visual_engine.py in llava

### ISSUE THREAD

**Issue by jkl375** [NVIDIA/TensorRT-LLM#858]
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/54523287/032dc735-25ef-4da1-a435-5afa1655f5e7)
The default transformer version for tensorrt llm is 4.36.1, error will be reported during  running build_visual_engine.py
It works when I downgraded the transformers version to 4.31.0.
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/54523287/1581032d-16d5-4d0f-8cde-4cc85289db2b)

**Comment by symphonylyh** [comment]
Hi @jkl375 , yes we noticed this for both llava and blip2. It has been fixed internally by using the LLaVA model from HuggingFace directly without other dependencies, and will be released soon. In the meantime, please pip reinstall transformers to switch the transformer versions as a temporary workaround.

**Comment by symphonylyh** [comment]
@jkl375 , this version issue has been fixed, and I've seen you made good progress testing llava. Let's close this one and continue to solve the batch size issue in #928
