### ISSUE TITLE
[Feature Request] Support InternLM Model

### ISSUE THREAD

**Issue by vansin** [NVIDIA/TensorRT-LLM#86]
https://huggingface.co/internlm/internlm-7b

**Comment by jdemouth-nvidia** [comment]
Hi @vansin ; thanks for mentioning InterLM. It's not on our roadmap, right now but we welcome contributions (and can help) if you are interested :). Thanks, Julien

**Comment by wangruohui** [comment]
I made a draft version https://github.com/NVIDIA/TensorRT-LLM/pull/123 but need more tests on more features supported by TRT-LLM.

**Comment by byshiue** [comment]
The codes are update to main branch https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/internlm. Thank you for the help, @wangruohui . Close this bug. Feel free to reopen it if needed.
