### ISSUE TITLE
What are the basic environmental requirements for tensorrt llm

### ISSUE THREAD

**Issue by ArlanCooper** [NVIDIA/TensorRT-LLM#860]
i have cuda118, can i install tensorRT-llm?
or it needs cuda122?

i can't find a detailed guide to install tensorRT-llm, where can I find one?
thanks a lot.

**Comment by byshiue** [comment]
Please refer https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/installation.md#tensorrt-llm-installation to install TensorRT-LLM. 

cuda 12 is necessary. We highly suggest using the docker image we provide in the document at the beginning.

**Comment by ArlanCooper** [comment]
thanks, that's help a lot.
