### ISSUE TITLE
how to enable "enableBlockReuse" ?

### ISSUE THREAD

**Issue by yunzhongyan0** [NVIDIA/TensorRT-LLM#864]
"enableBlockReuse" in batchmanager config is false in default, how to enable enableBlockReuse True ?

**Comment by byshiue** [comment]
If you use triton backend, it is controlled by `enable_kv_cache_reuse`.

**Comment by yunzhongyan0** [comment]
I built the qwen model engine using command as fellow:
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/37043971/e0487e79-3ff6-49b4-85b0-a7a501963422)

**Comment by yunzhongyan0** [comment]
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/37043971/be4f0667-b5fd-4ba3-83ea-83d9c694098e)

**Comment by yunzhongyan0** [comment]
The following error occurred using the above method：

![image](https://github.com/NVIDIA/TensorRT-LLM/assets/37043971/6a8bd2ea-d778-40f8-ba8b-220081f4dcff)        

Model: qwen-7B
command to build tensorrt_llm engine is as follow
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/37043971/dec0cbe6-9f48-4550-9b86-99f85528cfa4)

**Comment by byshiue** [comment]
This feature is only exposed in gpt model now https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/gpt/build.py#L362-L367. For other models, it requires works to add this config to enable it.

**Comment by nv-guomingz** [comment]
Hi @yunzhongyan0 do u still have further issue or question now? If not, we'll close it soon.
