### ISSUE TITLE
[feature request] Make GptManager more configurable

### ISSUE THREAD

**Issue by akhoroshev** [NVIDIA/TensorRT-LLM#868]
Hi!

In real world production cases GptManager is a great solution because it supports continues batching (or inflight batching) and many architectures.

But due to closed source, it is not flexible enough. On the other hand GptSession is flexible (thanks to being open source) but does not support in-flight batch processing.

For example, these two problems cannot be solved right now with GptManager:
1. https://github.com/NVIDIA/TensorRT-LLM/issues/595 Accessing to "custom" outputs in SendResponseCallback
2. https://github.com/NVIDIA/TensorRT-LLM/issues/692 Forwarding new custom options to GptDecoder from GptManager for implementation of different sampling methods

It would be great if you could help fix these problems by making GptManager more flexible

**Comment by nv-guomingz** [comment]
would u please try our latest code base to see if the issue still exists?

And do u still have further issue or question now? If not, we'll close it soon.
