### ISSUE TITLE
benchmarking Mistra/Mixtral

### ISSUE THREAD

**Issue by MustafaFayez** [NVIDIA/TensorRT-LLM#875]
Hi, 
I see you have built an example for Mistral models that I could build successfully. However, when I try to benchmark such models using GPTSessionBenchmark I get errors like:
`[TensorRT-LLM][ERROR] [TensorRT-LLM][ERROR] Assertion failed: Tensor 'input_ids' has invalid shape (131072), expected (-1) (/code/tensorrt_llm/cpp/tensorrt_llm/runtime/tllmRuntime.cpp:150)`

This is how I build the model:

`python ../llama/build.py  --model_dir  /mnt/mnt/Mistral-7B-v0.1  --use_inflight_batching --enable_context_fmha  --parallel_build  --output_dir ./tmp/mistral/trt_engines/fp16/8-gpu/  --dtype float16  --world_size 8  --tp_size 8  --pp_size 1
`
This how i ran the benchmark:

```
in_out_sizes=("64:128,128" "64:128,2048" "64:2048,128" "64:2048,2048")
for in_out in ${in_out_sizes[@]}
do
        batch_size=$(echo $in_out | awk -F':' '{ print $1 }')
        in_out_dims=$(echo $in_out | awk -F':' '{ print $2 }')
        echo "BS: $batch_size, ISL/OSL: $in_out_dims"
        mpirun -n 8 --allow-run-as-root --oversubscribe ../../cpp/build/benchmarks/gptSessionBenchmark --model llama --engine_dir  ./tmp/mistral/trt_engines/fp16/8-gpu/ --warm_up 1 --batch_size $batch_size --duration 0 --num_runs 5 --input_output_len $in_out_dims
done

```

Thanks a lot!

**Comment by qingchanghan** [comment]
I got the same error on Llama model.

**Comment by MustafaFayez** [comment]
for llama, just make sure the dimensions of the built engine is the same as the ones used in the benchmark command.

**Comment by nv-guomingz** [comment]
Hi @MustafaFayez  I tried the latest code base and it works well. Would u please try again?

And do u still have further issue or question now? If not, we'll close it soon.
