### ISSUE TITLE
Is there a demo or a guide to follow for mistral 7b for tensor parallelism and  then deployment in triton inference server later for 2 A100 GPUs

### ISSUE THREAD

**Issue by PREETHAM2002** [NVIDIA/TensorRT-LLM#876]

**Comment by PerkzZheng** [comment]
Mistral and LLaMA shares the same convert, build scripts, so you can almost follow the same instructions as shown for LLaMA 7B.
See more details in https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/llama#mistral-v01.
Let me know if you observe any issues.

**Comment by nv-guomingz** [comment]
please feel free to reopen this ticket if needed.
