### ISSUE TITLE
Support for text and image embedding models 

### ISSUE THREAD

**Issue by JohnnyRacer** [NVIDIA/TensorRT-LLM#880]
Hello, are there any plans for supporting image or text embedding models such as CLIP or `sentence-transformers` models in the future? If not, is there a way to implement support for these models? It would be very helpful to be able to accelerate the embedding models for something like ChromaDB.

**Comment by byshiue** [comment]
We have BLIP2 here https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/blip2. Is it helpful?

**Comment by JohnnyRacer** [comment]
Can I apply the same process for BLIP2's ViT to export CLIP model like ViT/L-14? Also it doesn't seem like there's a way to generate text embeddings similar to `sentence-transformers`.

**Comment by byshiue** [comment]
We don't verify the workflow, so we cannot guarantee it would work. You could take a try.
