### ISSUE TITLE
use TensorRT to accelerate the Reward Model based LLM

### ISSUE THREAD

**Issue by XuJing1022** [NVIDIA/TensorRT-LLM#888]
If I want to use tensorRT to accelerate the Reward Model based on Bloom-560m, how should I modify the code?

**Comment by byshiue** [comment]
The question is too abstract. You could try running Bloom-560m by TRT-LLM first, and replace your original Bloom-560m model by TRT-LLM engine.

**Comment by taoyun951753** [comment]
@XuJing1022  I am also very puzzled about this. Has this problem been solved？
