### ISSUE TITLE
How to run gpt2 model after building the engine successfully?

### ISSUE THREAD

**Issue by SehajDxstiny** [NVIDIA/TensorRT-LLM#897]
After running this:

`!python3 TensorRT-LLM/examples/gpt/build.py --model_dir=./c-model/gpt2m/1-gpu --use_gpt_attention_plugin --remove_input_padding`

The engine gets successuly built. In the directory called "engine_outputs" I have now 2 files config.json and gpt_float16_tp1_rank0.engine. How do i now use this engine robustly in my pipeline? How do i measure the inference speed?

i tried run.py's command: `!python3 TensorRT-LLM/examples/run.py --max_output_len=8` but it doesn't seem intuitive, also if I add arguments like --no_add_special_tokens it says unrecognized. I changed files like run.py to build the engines for 0.7.1 version #871

**Comment by byshiue** [comment]
Please follow the `bug_report.yml` template to share the infomation of your issue, thanks.

**Comment by nv-guomingz** [comment]
Hi @SehajDxstiny would u please try our latest code base to see if the issue still exists?

And do u still have further issue or question now? If not, we'll close it soon.
