### ISSUE TITLE
Problems running examples/server/server.py

### ISSUE THREAD

**Issue by ly19970621** [NVIDIA/TensorRT-LLM#898]
`File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/engine.py", line 8, in <module>
    import tensorrt_llm.bindings as tllm
ModuleNotFoundError: No module named 'tensorrt_llm.bindings'`
I searched for a long time but couldn't find tensorrt_llm.bindings.

**Comment by byshiue** [comment]
Please follow the `bug_report.yml` template to share the infomation of your issue, thanks.
