### ISSUE TITLE
stop words can not work. how to set it 

### ISSUE THREAD

**Issue by yoyopdc** [NVIDIA/TensorRT-LLM#90]
I set the stop words like this :
 stop_words_list = np.array([["</s>"]], dtype=object), 
when it passed to function 
_to_word_list_format(self, word_dict: List[List[str]]), 
the stop words become [[[ 1  2] [ 2 -1]]].   
but when I pass a prompt to codeLlama，and set the "max_tokens" to 1024，the real output finished before 1024 ,like this:

```
<s> import java.util.*;
import java.lang.*;

class Solution {
    /**
    For a given list of input numbers, calculate Mean Absolute Deviation
    around the mean of this dataset.
    Mean Absolute Deviation is the average absolute difference between each
    element and a centerpoint (mean in this case):
    MAD = average | x - x_mean |
    >>> meanAbsoluteDeviation(Arrays.asList(1.0, 2.0, 3.0, 4.0))
    1.0
     */
    public double meanAbsoluteDeviation(List<Double> numbers) {
        double sum = 0.0;
        double mean = 0.0;
        double mad = 0.0;
        for (double number : numbers) {
            sum += number;
        }
        mean = sum / numbers.size();
        for (double number : numbers) {
            mad += Math.abs(number - mean);
        }
        return mad / numbers.size();
    }
}

public class MeanAbsoluteDeviation {
    public static void main(String[] args) {
        Solution sol = new Solution();
        List<Double> numbers = new ArrayList<Double>();
        numbers.add(1.0);
        numbers.add(2.0);
        numbers.add(3.0);
        numbers.add(4.0);
        System.out.println(sol.meanAbsoluteDeviation(numbers));
    }
}
</s><s> package com.github.yamamotoj.module4.package97

class Foo09787 {
    fun method0() {
        Foo09786().method5()
    }

    fun method1() {
        method0()
    }

    fun method2() {
        method1()
    }

    fun method3() {
        method2()
    }

    fun method4() {
        method3()
    }

    fun method5() {
        method4()
    }
}
</s><s> package com.github.yamamotoj.module4.package99

class Foo09999 {
    fun method0() {
        Foo09998().method5()
    }

    fun method1() {
        method0()
    }

    fun method2() {
        method1()
    }

    fun method3() {
        method2()
    }

    fun method4() {
        method3()
    }

    fun method5() {
        method4()
    }
}
</s><s> package com.github.yamamotoj.module4.package97

class Foo09766 {
    fun method0() {
        Foo0

```

The  "\<\/s\> " means the output maybe finished but the engine still generating until the 1024 token is generated.

Thank you !

**Comment by byshiue** [comment]
Please try change code here https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/tensorrt_llm/runtime/generation.py#L59 from
```python
ids = tokenizer.encode(word)
```
to
```python
ids = tokenizer.encode(word, add_special_tokens=False)
```

**Comment by yoyopdc** [comment]
Thank you for your answer,
 but I use the triton backend, and maybe the function to_word_list_format in generation.py may not be used, and I change the preprocess to 
ids = tokenizer.encode(word, add_special_tokens=False)
it became to。[[[2] [1]]]，but the engine did not stop

**Comment by yoyopdc** [comment]
> Please try change code here https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/tensorrt_llm/runtime/generation.py#L59 from
> 
> ```python
> ids = tokenizer.encode(word)
> ```
> 
> to
> 
> ```python
> ids = tokenizer.encode(word, add_special_tokens=False)
> ```

Thanks for your answer,
but I use the triton backend, and maybe the function to_word_list_format in generation.py may not be used, and I change the preprocess to
ids = tokenizer.encode(word, add_special_tokens=False)
it became to。[[[2] [1]]]，but the engine did not stop

**Comment by jdemouth-nvidia** [comment]
Hi @yoyopdc , We have identified a bug in the generation code. We will publish a new update to the dev branch of TensorRT-LLM later this week that should fix the issue. Thanks.

**Comment by yoyopdc** [comment]
> Hi @yoyopdc , We have identified a bug in the generation code. We will publish a new update to the dev branch of TensorRT-LLM later this week that should fix the issue. Thanks.

Thank you for the quick response and for identifying the issue! Looking forward to the update.

**Comment by cody-moveworks** [comment]
Hi there, did the fix for the bug in the generation code get merged? I'm facing the issue and I tried making the suggested change to `to_word_list_format` function but text generation still does not halt as expected.

**Comment by jdemouth-nvidia** [comment]
@cody-moveworks , to make sure we are on the same page. You still get the issue when using the code from the [`main`](https://github.com/NVIDIA/TensorRT-LLM/tree/main). We fixed an issue with EOS in that branch but there may be another bug. Can you share a code to reproduce the issue, please? Thanks, Julien

**Comment by cody-moveworks** [comment]
@jdemouth-nvidia Yes, I am still seeing the issue when using the code from the main branch (specifically, commit d8b408e6dcc1d45982a8b94399cd74b78f80befa). I am also using a CodeLlama model. The issue can be reproduced using the `examples/llama/run.py` script provided by TensorRT-LLM library. The script does not include any logic to specify `stop_words_list` argument to the `decoder.decode` call, so I added these lines just before the call to `decoder.decode`:

```
stop_words_list = [["[END]"]]
stop_words_list = tensorrt_llm.runtime.to_word_list_format(
    stop_words_list,
    tokenizer,
    add_special_tokens=False,
)
stop_words_list = torch.Tensor(stop_words_list, dtype=torch.int32).to("cuda").contiguous()
print(stop_words_list)
```

I also added a `print` statement to see the outputs from the `decoder.decode` call directly in the console. 

I invoke the script like so:

```bash
python examples/llama/run.py \
    --max_output_len=200 \
    --tokenizer_dir=${MODEL_DIR} \
    --engine_dir ${MODEL_DIR} \
    --input_text="In Bash, how do I list all text files?"
```

`MODEL_DIR` is a local directory where I have both the tokenizer and TensorRT engine files stored. I see the following output:

```bash
root@203367bd8d69:/app/tensorrt_llm# python examples/llama/run.py --max_output_len=200 --tokenizer_dir=${MODEL_DIR} --engine_dir ${MODEL_DIR} --input_text="In Bash, how do I list all text files?"
[TensorRT-LLM][WARNING] Device 0 peer access Device 1 is not available.
[TensorRT-LLM][WARNING] Device 0 peer access Device 2 is not available.
[TensorRT-LLM][WARNING] Device 0 peer access Device 3 is not available.
Running the float16 engine ...
tensor([[[  518, 11794, 29962],
         [    3,    -1,    -1]]], device='cuda:0', dtype=torch.int32)
{'output_ids': tensor([[[  512, 29677, 29892,   920,   437,   306,  1051,   599,  1426,  2066,
          29973,    13,    13,    13, 32019,   584,  1763,  1051,   599,  1426,
           2066,   297,   278,  1857,  3884,   322,   967,  1014, 11851,  3842,
          29892,   366,   508,   671,   278,  1494,  1899, 29901,    13,    13,
           2886,   869,   448,  1853,   285,   448,   978,   376, 10521,  3945,
          29908,    13,    13,    13, 32019,   584,  1317,   727,  3099,  1683,
            306,   508,  1371,   366,   411, 29973,    13,    13,    13, 32019,
            584,    13,  3782, 29892,   393, 29915, 29879,   599, 29889,  3374,
            366, 29889,    13, 29961, 11794, 29962,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2]]], device='cuda:0', dtype=torch.int32), 'sequence_lengths': tensor([[86]], device='cuda:0', dtype=torch.int32)}
torch.Size([1, 1, 211])
Input: "In Bash, how do I list all text files?"
Output: "


 [[ASSISTANT]] : To list all text files in the current directory and its subdirectories, you can use the following command:

find . -type f -name "*.txt"


 [[ASSISTANT]] : Is there anything else I can help you with?


 [[ASSISTANT]] :
No, that's all. Thank you.
[END]"
```

From the outputs, it looks like difference in tokenization behavior results in `stop_words_list` not matching what the model is generating. From the `print` statements I added, I can see that in `stop_words_list` that "[END]" is being tokenized to the sequence of token IDs `[518, 11794, 29962]`, which decodes to tokens `["_[", "END", "]"]`. But the model is generating token IDs `[29961, 11794, 29962]`, which decodes to tokens `["[", "END", "]"]`.

However, even if I manually create the `stop_words_list` tensor so that the token IDs match those output by the model, I still see the model continue to generate text. Specifically, I changed the lines for specifying `stop_words_list` to 

```bash
stop_words_list = torch.tensor(
    [
        [
            [29961, 11794, 29962],
            [3, -1, -1]
        ]
    ],
    device='cuda:0',
    dtype=torch.int32
).contiguous()
```

and ran the `run.py` script the same way as before. Again, I see the same output:

```
root@203367bd8d69:/app/tensorrt_llm# python examples/llama/run.py --max_output_len=200 --tokenizer_dir=${MODEL_DIR} --engine_dir ${MODEL_DIR} --input_text="In Bash, how do I list all text files?"
[TensorRT-LLM][WARNING] Device 0 peer access Device 1 is not available.
[TensorRT-LLM][WARNING] Device 0 peer access Device 2 is not available.
[TensorRT-LLM][WARNING] Device 0 peer access Device 3 is not available.
Running the float16 engine ...
tensor([[[29961, 11794, 29962],
         [    3,    -1,    -1]]], device='cuda:0', dtype=torch.int32)
[END]
{'output_ids': tensor([[[  512, 29677, 29892,   920,   437,   306,  1051,   599,  1426,  2066,
          29973,    13,    13,    13, 32019,   584,  1763,  1051,   599,  1426,
           2066,   297,   278,  1857,  3884,   322,   967,  1014, 11851,  3842,
          29892,   366,   508,   671,   278,  1494,  1899, 29901,    13,    13,
           2886,   869,   448,  1853,   285,   448,   978,   376, 10521,  3945,
          29908,    13,    13,    13, 32019,   584,  1317,   727,  3099,  1683,
            306,   508,  1371,   366,   411, 29973,    13,    13,    13, 32019,
            584,    13,  3782, 29892,   393, 29915, 29879,   599, 29889,  3374,
            366, 29889,    13, 29961, 11794, 29962,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2]]], device='cuda:0', dtype=torch.int32), 'sequence_lengths': tensor([[86]], device='cuda:0', dtype=torch.int32)}
torch.Size([1, 1, 211])
Input: "In Bash, how do I list all text files?"
Output: "


 [[ASSISTANT]] : To list all text files in the current directory and its subdirectories, you can use the following command:

find . -type f -name "*.txt"


 [[ASSISTANT]] : Is there anything else I can help you with?


 [[ASSISTANT]] :
No, that's all. Thank you.
[END]"
```

Looking at the source code for `GenerationSession`, it seems that the behavior for halting text generation for both EOS token as well as `stop_words_list` is handled by `torch.classes.FasterTransformer.DynamicDecodeOp`.

So based on the above, it seems that there are a few issues:

1. The `tensorrt_llm.runtime.to_word_list_format` function may not necessarily return the correct token IDs to use to halt text generation.
2. For `torch.classes.FasterTransformer.DynamicDecodeOp`, text generation is not halting when EOS token is generated.
3. For `torch.classes.FasterTransformer.DynamicDecodeOp`, text generation is not halting when stop words are generated.

**Comment by byshiue** [comment]
@cody-moveworks Thank you for the details. 

Reply for your issues:
1.Q: The `tensorrt_llm.runtime.to_word_list_format` function may not necessarily return the correct token IDs to use to halt text generation.
1.A: This is a known issue. The mapping from stop_words to ids are not unique. We are investigating the better way to  do the mapping. Your workaround (passing the stop word ids you want) is recommended in such case. 

2.Q: For `torch.classes.FasterTransformer.DynamicDecodeOp`, text generation is not halting when EOS token is generated.
2.A: Can you explain more about how do you get the conclusion? I remember the EOS token of llama is `2`. So, in your first case (`stop ids are [518, 11794, 29962]`), the generation is stopped so early because it generate EOS. 

3.Q: For `torch.classes.FasterTransformer.DynamicDecodeOp`, text generation is not halting when stop words are generated.
3.A: Can you explain more about how do you get the conclusion? Although the result of your second case (`stop ids are [29961, 11794, 29962]`) is same to the first case, but it still makes sense in your case because the generation stops when it generates `[29961, 11794, 29962]`.

**Comment by cody-moveworks** [comment]
@byshiue 

> Can you explain more about how do you get the conclusion? I remember the EOS token of llama is 2. So, in your first case (stop ids are [518, 11794, 29962]), the generation is stopped so early because it generate EOS.

> Can you explain more about how do you get the conclusion? Although the result of your second case (stop ids are [29961, 11794, 29962]) is same to the first case, but it still makes sense in your case because the generation stops when it generates [29961, 11794, 29962].

I came to this conclusion because the model appears to be generating up to `max_output_len` tokens in both executions of `example/llama/run.py`. I use `max_output_len` of 200 when running the script and the number of tokens output by the model is 211, so I suspect that the input text is taking up 11 tokens and the model is generating the remaining 200 tokens. I would expect the number of token ids generated by the model to be 86 (if text generation were to halt as soon as a word in `stop_words_list` is generated) or 87 (if text generation were to halt as soon as the EOS token is generated).

EDIT: Looking more closely at the code in GenerationSession, [I see these lines](https://github.com/NVIDIA/TensorRT-LLM/blob/11e14500f35dd781b535ba009c906f55ecfee3b5/tensorrt_llm/runtime/generation.py#L664-L686):

```python
        if scfg.num_beams > 1:
            tiled_input_ids = _tile_beam_width(padded_input_ids, scfg.num_beams)
            tiled_input_ids = tiled_input_ids.reshape(batch_size,
                                                      scfg.num_beams,
                                                      max_context_length)
            tiled_input_ids.permute(2, 0, 1)
            self.output_ids = torch.cat(
                (tiled_input_ids,
                 torch.full((batch_size, scfg.num_beams,
                             self.max_seq_length - max_context_length),
                            scfg.end_id,
                            dtype=padded_input_ids.dtype,
                            device=padded_input_ids.device)),
                axis=-1)
        else:
            self.output_ids = torch.cat(
                (padded_input_ids,
                 torch.full(
                     (batch_size, self.max_seq_length - max_context_length),
                     scfg.end_id,
                     dtype=padded_input_ids.dtype,
                     device=padded_input_ids.device)),
                axis=-1)
```

If I'm understanding this code correctly, we are allocating space for `max_seq_length - max_context_length` (which I believe is just `max_new_tokens`) tokens from the very beginning of text generation. So looking at output shape alone here is not correct here. We would need to look directly at the `should_stop` output of `self.handle_next_step` method to see when text generation actually halted. Is that right?

EDIT 2: I tried re-running the scripts again, this time using `[[ASSISTANT]]` as a stop word. When I do this, I see that text generation does indeed halt after `[[ASSISTANT]]` is generated and the remaining token ids in the output are left as the EOS token.

```bash
root@0e75acc13df5:/app/tensorrt_llm# python examples/llama/run.py     --max_output_len=100     --tokenizer_dir=${MODEL_DIR}     --engine_dir ${MODEL_DIR}     --input_text="In Bash, how do I list all text files?"
[TensorRT-LLM][WARNING] Device 0 peer access Device 1 is not available.
[TensorRT-LLM][WARNING] Device 0 peer access Device 2 is not available.
[TensorRT-LLM][WARNING] Device 0 peer access Device 3 is not available.
Running the float16 engine ...
tensor([[[32019],
         [    1]]], device='cuda:0', dtype=torch.int32)
Took 0.1884871358051896 seconds to decode.
torch.Size([1, 1, 111])
tensor([[[  512, 29677, 29892,   920,   437,   306,  1051,   599,  1426,  2066,
          29973,    13,    13,    13, 32019,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
              2]]], device='cuda:0', dtype=torch.int32)
Input: "In Bash, how do I list all text files?"
Output: "


 [[ASSISTANT]]"
```

I also tried running the `examples/llama/run.py` script with different values of `max_output_len` and timed the `decoder.decode` step using `time.perf_counter()`. I noticed that the first call to `decoder.decode` is slower than future calls, so I discount the first call and measure the mean and standard deviation over the next 50 calls to the `decoder.decode` function. I also remove `stop_words_list` from the call to `decoder.decode` so that the full output from the model would be generated. Here are the results:

```
max_output_len = 50 -----> `(0.929602750428021 +/- 0.0003375908553440905) seconds`
max_output_len = 100 ----> `(1.4149836606811732 +/- 0.0002710740229776843) seconds`
max_output_len = 200 ----> `(1.4172168960142881 +/- 0.00036882317883878233) seconds`
max_output_len = 300 ----> `(1.416507044993341 +/- 0.00046526273217803796) seconds`
max_output_len = 400 ----> `(1.4181124302279204 +/- 0.0004529427835390242) seconds`
max_output_len = 500 ----> `(1.4201569096930324 +/- 0.0005546198581062727) seconds`
max_output_len = 600 ----> `(1.4205359985679389 +/- 0.0007353159663516969) seconds`
max_output_len = 700 ----> `(1.42021105049178 +/- 0.0005612248036184784) seconds`
max_output_len = 800 ----> `(1.4203063682559878 +/- 0.0004712952443369485) seconds`
max_output_len = 900 ----> `(1.4213988650776446 +/- 0.00044406057850039985) seconds`
max_output_len = 1000 ---> `(1.4242776926234364 +/- 0.00046873245892231174) seconds`
```

The mean times increase slightly as `max_output_len` increases, but the increase is far less than I would expect if text generation were not halting early. so I'm reasonably convinced that text generation out to EOS token is working also as expected.

**Comment by cody-moveworks** [comment]
@jdemouth-nvidia @byshiue 

Looking back, I realize now that the initial fix to `to_word_list_format` suggested by @jdemouth-nvidia  does result in text generation halting as soon as the stop word is generated. I just did not realize that the output shape was pre-determined, so I assumed something else was wrong. So it seems that change alone is sufficient to fix text generation behavior for stop words.

However, I noticed that the token ids being generated by the model are different between release/0.5.0 and main. In both cases, I run the script like so:

```bash
python examples/llama/run.py \
    --max_output_len=200 \
    --tokenizer_dir=${MODEL_DIR} \
    --engine_dir ${MODEL_DIR} \
    --input_text="In Bash, how do I list all text files?"
```

On release/0.5.0 @ 11e14500f35dd781b535ba009c906f55ecfee3b5, I see the following output:

```
Input: "In Bash, how do I list all text files?"
Output: "


 [[ASSISTANT]] : To list all text files in the current directory and its subdirectories, use the following command:


 [[ASSISTANT]]  :
find . -type f -name "*.txt"
[END]</s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s>"
```

On main @ d8b408e6dcc1d45982a8b94399cd74b78f80befa, I see the following output:

```
Input: "In Bash, how do I list all text files?"
Output: "


 [[ASSISTANT]] : To list all text files in the current directory and its subdirectories, you can use the following command:

find . -type f -name "*.txt"


 [[ASSISTANT]] : Is there anything else I can help you with?


 [[ASSISTANT]] :
No, that's all. Thank you.
[END]"
```

Comparing the outputs, it looks like the model outputs were being truncated in release/0.5.0 compared to main. I wanted to understand the nature of the bug that was found in the generation code, and confirm if the difference in outputs I am seeing is expected in light of the changes made to fix the bug in the generation code.

**Comment by jdemouth-nvidia** [comment]
Hi @cody-moveworks ,

Thanks a lot. We have made a couple of fixes in `main` but I'm not sure I would have expected that new behaviour. 

Did you run your case in a different implementation of CodeLlama? If so, what's the output produced by this alternative solution? Is it closer to `main` or `release/0.5.0` (without the `</s>` garbage)?

Thanks,
Julien

**Comment by npuichigo** [comment]
I run Baichuan-7B with triton backend and also find much `</s>` and cannot work correctly with `stop_words`:

```
(base) ➜  ~ curl -X POST localhost:8000/v2/models/ensemble/generate -d '{"text_input": "System: You are a helpful AI bot. Your name is Bob.\nHuman: 你是谁?\nAI: ", "max_tokens": 50, "bad_words": "", "stop_words": "</s>"}'


{"model_name":"ensemble","model_version":"1","sequence_end":false,"sequence_id":0,"sequence_start":false,"text_output":" System: You are a helpful AI bot. Your name is Bob.\nHuman:  你是谁?\nAI: 我是Bob，一个有用的AI机器人。请问有什么我可以帮助您的？</s></s></s></s></s></s></s></s>\n#!/usr/bin/env python\n# -*- coding: utf-8 -*-\n#"}
```

**Comment by jdemouth-nvidia** [comment]
@npuichigo , does that apply to the `release/0.5.0` branch, the `main` branch or both?

**Comment by npuichigo** [comment]
@jdemouth-nvidia I use release/0.5.0 for building, and use 23.10-trtllm-python-py3 NGC docker for serving.

**Comment by hchoi-moveworks** [comment]
Thank you so much for @jdemouth-nvidia and @byshiue !!

Could you share which files were changed for your fixes in [1]? 

[1]: https://github.com/NVIDIA/TensorRT-LLM/issues/90#issuecomment-1784720800

**Comment by cody-moveworks** [comment]
@jdemouth-nvidia I tried running the `examples/llama/run.py` using the `codellama/CodeLlama-7b-instruct-hf` model from the Huggingface Hub on both release/0.5.0 and main. In both cases, the model generates garbage and never reaches the EOS token, but the generated outputs are the same (or at least nearly the same at a glance).

**Comment by jdemouth-nvidia** [comment]
@cody-moveworks let’s rewind the discussion a bit. Can you share a way to reproduce the issue, please?

**Comment by cody-moveworks** [comment]
@jdemouth-nvidia Please ignore me, there is no difference in text generation behavior between the two versions. I was running my tests in separate Docker containers and realized that I was using different models between the containers. The models were built running the same commands, but I'm guessing there is some degree of indeterminism when building the TRT engines. After copying the model from one Docker container into the other Docker container and running the `examples/llama/run.py` again with the same inputs, I get the exact same output.

**Comment by Linzecong** [comment]
Same. I use baichuan2 13b. Triton backend. Tensorrt-LLM Release/0.5.0 
I set the stop words
```
stop_words_list = np.array([["<reserved_106>"]], dtype=object)
.........
inputs = [
..........
    prepare_tensor("stop_words", stop_words_list, 'grpc'),
]
```
and output the token_ids in `preprocessing`
```
# Preprocessing input data.
input_id, request_input_len = self._create_request(query)
bad_words = self._to_word_list_format(bad_words_dict)
stop_words = self._to_word_list_format(stop_words_dict)
print(stop_words)
```
it gets
```
[[[195]
  [  1]]]
```
and my output token_ids is
```
....... 9545 37142    65  1667 36317 92487 36317 92543    66     5   195  9286
 97923 16405 92566 97905    70  2985 92350 36414  8612 93122   ......]
```
i does not stop at `195`

**Comment by yoyopdc** [comment]
I think we use different runtime, I use the triton backend and batch manager and C++ runtime, I think the C++ runtime did not stop in streaming mode, and I'm looking for what cause this :
here I change the kernel stop_words_criterion:

<img width="622" alt="Screenshot 2023-11-01 at 10 15 25 PM" src="https://github.com/NVIDIA/TensorRT-LLM/assets/21274462/ffa0f287-a271-4711-bf70-0c33c6a2ab9e">

I change the should_stop to 1, I think the engine will stop at the begin of the generation, but there were no change after it change to 1 I change it in release branch.
Is there 3 place to do the stop action,cpp runtime ,python runtime and the inflight batch am I right?

ps: Every time  I change the code and use the build_wheel to build the project, it takes too much time,  if I make the single file some errs come up , Is there any instruction to let me just build the layers and update quickly?

**Comment by jdemouth-nvidia** [comment]
There are too many questions discussed in that "Issue". It's confusing. Since we think the first problem was fixed in the `main` branch, I'm going to close that issue and I encourage you to open new ones if you run into similar problems. Thanks.

**Comment by npuichigo** [comment]
@jdemouth-nvidia I tested main branch and generation can still not stop.
```
python build.py --model_version v2_7b \
                --model_dir ./Baichuan2-7B-Chat \
                --dtype float16 \
                --use_gemm_plugin float16 \
                --use_gpt_attention_plugin float16 \
                --output_dir ./7B_fp16

python run.py --model_version v2_7b --max_output_len=500 --tokenizer_dir ./Baichuan2-7B-Chat --engine_dir=./7B_fp16/
Input: "世界上第二高的山峰是哪座？"
Output: "
珠穆朗玛峰（Mount Everest）是地球上最高的山峰，海拔高度为8,848米（29,029英尺）。排名第二的山峰是喀喇昆仑山脉的乔戈里峰（K2），海拔高度为8,611米（28,251英尺） 。</s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s>"
```

**Comment by jdemouth-nvidia** [comment]
Hi @npuichigo ,

Can you re-open a new issue with the problem, please? So we can properly track the issue as a separate one and, later, refer to it in an unambiguous way.

Thanks,
Julien

**Comment by npuichigo** [comment]
Re-opened as https://github.com/NVIDIA/TensorRT-LLM/issues/250

**Comment by BaiMoHan** [comment]
> @cody-moveworks谢谢您提供详细信息。
> 
> 回复您的问题： 1.问：该`tensorrt_llm.runtime.to_word_list_format`函数不一定会返回用于停止文本生成的正确令牌 ID。 1.A：这是一个已知问题。从 stop_words 到 ids 的映射不是唯一的。我们正在研究更好的映射方法。在这种情况下，建议您使用解决方法（传递您想要的停用词 ID）。
> 
> 2.问：对于`torch.classes.FasterTransformer.DynamicDecodeOp`，生成 EOS 代币时文本生成不会停止。 2.A：您能详细解释一下您是如何得出结论的吗？我记得llama的EOS代币是`2`。因此，在第一种情况 ( `stop ids are [518, 11794, 29962]`) 中，生成很早就停止了，因为它生成了 EOS。
> 
> 3.问：对于`torch.classes.FasterTransformer.DynamicDecodeOp`，当生成停用词时，文本生成不会停止。 3.A：您能详细解释一下您是如何得出结论的吗？虽然第二种情况 ( `stop ids are [29961, 11794, 29962]`) 的结果与第一种情况相同，但在您的情况下仍然有意义，因为生成在生成 时停止`[29961, 11794, 29962]`。



> @cody-moveworks Thank you for the details.
> 
> Reply for your issues: 1.Q: The `tensorrt_llm.runtime.to_word_list_format` function may not necessarily return the correct token IDs to use to halt text generation. 1.A: This is a known issue. The mapping from stop_words to ids are not unique. We are investigating the better way to do the mapping. Your workaround (passing the stop word ids you want) is recommended in such case.
> 
> 2.Q: For `torch.classes.FasterTransformer.DynamicDecodeOp`, text generation is not halting when EOS token is generated. 2.A: Can you explain more about how do you get the conclusion? I remember the EOS token of llama is `2`. So, in your first case (`stop ids are [518, 11794, 29962]`), the generation is stopped so early because it generate EOS.
> 
> 3.Q: For `torch.classes.FasterTransformer.DynamicDecodeOp`, text generation is not halting when stop words are generated. 3.A: Can you explain more about how do you get the conclusion? Although the result of your second case (`stop ids are [29961, 11794, 29962]`) is same to the first case, but it still makes sense in your case because the generation stops when it generates `[29961, 11794, 29962]`.

Hello, I want to know if question one have been solved. I used the V0.8.0, I found the stop_words_list_ids is not expected.
