### ISSUE TITLE
Error: enable KV cache block reuse

### ISSUE THREAD

**Issue by ydm-amazon** [NVIDIA/TensorRT-LLM#904]
### System Info

TRT-LLM 0.7.1
Host: g5.12xlarge ec2 instance(A10G)
Memory size: 23028MiB
CUDA: 12.2
Model: GPT2

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

I am using the build.py script in examples/gpt/

```
build.py --world_size 1 --model_dir /tmp/trtllm_gpt_ckpt/1-gpu/ --max_input_len 1024 --max_output_len 512 --max_batch_size 16 --max_beam_width 1 --use_gpt_attention_plugin float16 --use_gemm_plugin float16 --enable_context_fmha --use_paged_context_fmha --remove_input_padding --paged_kv_cache --tokens_per_block 128     --output_dir /tmp/gpt2/1 --dtype float16 --parallel_build --use_inflight_batching --max_draft_len 20
```

After the model is up, I send a request with the following details, which works:

`'{"inputs":"tell me a story of the little red riding hood","parameters":{"do_sample":false, "request_output_len":10}}'`

I then send a request with the following details, which does not work:

`'{"inputs":"tell me a story of the little red riding hood","parameters":{"do_sample":false, "request_output_len":11, "draft_input_ids":[[1,19282,393,306,18093,363,590,8750,29889,739,471]]}}'`

### Expected behavior

The first request should generate some text, for example: `"ie that I bought for my daughter. It was"`. The second request should also generate some text, for example: `"ie that I bought for my daughter. It was a"`

### actual behavior

First request works just fine

But second request produced an error:

`KV cache block reuse must be enabled for speculative decoding target model (/home/jenkins/agent/workspace/LLM/release-0.7/L0_PostMerge/llm/cpp/tensorrt_llm/batch_manager/runtimeBuffers.cpp:353)`

### additional notes

I set both --max_draft_len and --use_paged_context_fmha when building. The latter seems to enable KV cache block reuse according to the comment next to --use_paged_context_fmha in build.py, but the error still appears.

**Comment by byshiue** [comment]
Please share how do you run the request. If you use triton backend, please share the full log of triton engine, and you could also try enabling enable kv cache feature by setting `enable_kv_cache_reuse` as `True` in `config.pbtxt` of `tensorrt_llm`.

**Comment by nv-guomingz** [comment]
Hi @ydm-amazon do u still have further issue or question now? If not, we'll close it soon.
