### ISSUE TITLE
Problems running examples/server/server.py

### ISSUE THREAD

**Issue by ly19970621** [NVIDIA/TensorRT-LLM#905]
### System Info

CPU: Intel(R) Xeon(R) Gold 6342 CPU @ 2.80GHz
Linux system kernel: Linux b64d4a6d0353 5.15.0-88-generic #98-Ubuntu SMP Mon Oct 2 15:18:56 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
OS: Ubuntu 22.04.3
GPU: 4*RTX 4090 24GB
tensorrt-llm: 0.7.1
python: 3.10.12
tensorrt: 9.2.0.post12.dev5
cuda: 12.2
nvidia driver: 535.129.03
nvidia-cublas-cu12: 12.3.4.1
nvidia-cudnn-cu12: 8.9.7.29

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

When I tried to run the API service following the format of `examples/server/server.py`, after successfully building and running `run.py` for inference using `ziya2-13b-chat` model with Llama2 architecture by running `examples/llama/build.py`, I encountered the following error:

`Traceback (most recent call last):
  File "/code/liuy026/TensorRT-LLM/examples/server/trt_ziya_api.py", line 3, in <module>
    from tensorrt_llm.engine import AsyncLLMEngine
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/engine.py", line 8, in <module>
    import tensorrt_llm.bindings as tllm
ModuleNotFoundError: No module named 'tensorrt_llm.bindings'`

I searched for `tensorrt_llm.bindings` but couldn't find it. What could be the problem?

### Expected behavior

none

### actual behavior

none

### additional notes

none

**Comment by byshiue** [comment]
Please provide the e2e reproduced steps. You could try adding `--use_py_session` first to use python runtime instead of using c++ runtime with python binding.

**Comment by ly19970621** [comment]
> Please provide the e2e reproduced steps. You could try adding `--use_py_session` first to use python runtime instead of using c++ runtime with python binding.

This is the process of setting up and running my program:
1. `docker build --pull  \
             --target devel \
             --file docker/Dockerfile.multi \
             --tag tensorrt_llm/devel:latest \
             .`
2. `docker run --rm -it \
           --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 --gpus=all \
           --volume ${PWD}:/code/tensorrt_llm \
           --workdir /code/tensorrt_llm \
           tensorrt_llm/devel:latest`
3.`python3 ./scripts/build_wheel.py --trt_root /usr/local/tensorrt`
4. `pip install ./build/tensorrt_llm*.whl`
5. `CUDA_VISIBLE_DEVICES=0,1 python build.py --model_dir /code/model/Ziya2-13B-Chat                 --dtype bfloat16                 --remove_input_padding                 --use_gpt_attention_plugin bfloat16                 --enable_context_fmha                 --use_gemm_plugin bfloat16                 --output_dir /code/model/Ziya2-13B-Chat/trt_engines/bf16/2-gpu/                 --world_size 2                 --tp_size 2`
6. `CUDA_VISIBLE_DEVICES=0,1 mpirun -n 2 --allow-run-as-root python3 ../run.py --input_text "<human>: 你好，请问你叫什么？\n<bot>:"                   --max_output_len=50                   --tokenizer_dir /code/model/Ziya2-13B-Chat                   --engine_dir=/code/model/Ziya2-13B-Chat/trt_engines/bf16/2-gpu` run successfully
7. `CUDA_VISIBLE_DEVICES=0,1 python3 examples/server/trt_ziya_api.py` run failure

**How do I do the above "You could try adding --use_py_session first to use python runtime instead of using c++ runtime with python binding" ?**

**Comment by byshiue** [comment]
If you could run the `run.py` successfully, it might mean that you don't setup the environment (like loading the binding) in your script. You could refer how `use_py_session` affect the codes, it includes some logics of choosing the pybinding or python runtime.

**Comment by ly19970621** [comment]
> If you could run the `run.py` successfully, it might mean that you don't setup the environment (like loading the binding) in your script. You could refer how `use_py_session` affect the codes, it includes some logics of choosing the pybinding or python runtime.

I added "use_py_senssion" as you suggested.
```
CUDA_VISIBLE_DEVICES=0,1 mpirun -n 2 --allow-run-as-root python3 examples/server/trt_ziya_api.py
 --use_py_session
```
But the same error occurs again
```
Traceback (most recent call last):
  File "/code/liuy026/TensorRT-LLM/examples/server/trt_ziya_api.py", line 3, in <module>
    from tensorrt_llm.engine import AsyncLLMEngine
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/engine.py", line 8, in <module>
    import tensorrt_llm.bindings as tllm
ModuleNotFoundError: No module named 'tensorrt_llm.bindings'
Traceback (most recent call last):
  File "/code/liuy026/TensorRT-LLM/examples/server/trt_ziya_api.py", line 3, in <module>
    from tensorrt_llm.engine import AsyncLLMEngine
  File "/usr/local/lib/python3.10/dist-packages/tensorrt_llm/engine.py", line 8, in <module>
    import tensorrt_llm.bindings as tllm
ModuleNotFoundError: No module named 'tensorrt_llm.bindings'
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[38670,1],0]
  Exit code:    1
-------------------------------------------------------------------------
```
I did not find any information related to bindings in the path /usr/local/lib/python3.10/dist-packages/tensorrt_llm. The files under this path are:

```
__init__.py  _ipc_utils.py  commands       graph_rewriting.py  libs        models      parameter.py  quantization  top_model_mixin.py
__pycache__  _utils.py      engine.py      hlapi               logger.py   module.py   plugin        runtime       version.py
_common.py   builder.py     functional.py  layers              mapping.py  network.py  profiler.py   tools
```

Is it a problem with my environment?

**Comment by byshiue** [comment]
You should refer the `run.py` about the logic of `use_py_session` like https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/run.py#L340-L372 to change your api codes.

**Comment by lyc728** [comment]
> You should refer the `run.py` about the logic of `use_py_session` like https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/run.py#L340-L372 to change your api codes.

Hello, I found import tensorrt_llm.bindings as _tb when running tests/bindings/test_gpt_manager.py
ModuleNotFoundError: No module named 'tensorrt_llm.bindings' This package is not implemented, and my installation of tensorrt-llm 0.7.1 and 0.5.0 does not address it

**Comment by ly19970621** [comment]
> You should refer the `run.py` about the logic of `use_py_session` like https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/run.py#L340-L372 to change your api codes.

But I want to use AsyncLLMEngine in [engine.py,](https://github.com/NVIDIA/TensorRT-LLM/blob/main/tensorrt_llm/engine.py#L8) so that the API can handle concurrent requests. I hope you can help me solve this problem. Thank you.

**Comment by MartinMarciniszyn** [comment]
Please use the new [high level API](https://github.com/NVIDIA/TensorRT-LLM/blob/main/tensorrt_llm/hlapi/llm.py#L130) for that.
