### ISSUE TITLE
how to skip googletest when compile source

### ISSUE THREAD

**Issue by whk6688** [NVIDIA/TensorRT-LLM#908]
i met following error, how to skip it (how to modify cmake)

577.1 [ 11%] Creating directories for 'googletest-populate'
577.1 [ 22%] Performing download step (git clone) for 'googletest-populate'
577.1 Cloning into 'googletest-src'...
577.1 fatal: unable to access 'https://github.com/google/googletest.git/': Failed to connect to github.com port 443 after 130633 ms: Connection timed out
577.1 Cloning into 'googletest-src'...
577.1 fatal: unable to access 'https://github.com/google/googletest.git/': Failed to connect to github.com port 443 after 131033 ms: Connection timed out
577.1 Cloning into 'googletest-src'...
577.1 fatal: unable to access 'https://github.com/google/googletest.git/': Failed to connect to github.com port 443 after 131038 ms: Connection timed out
577.1 -- Had to git clone more than once: 3 times.
577.1 CMake Error at googletest-subbuild/googletest-populate-prefix/tmp/googletest-populate-gitclone.cmake:39 (message):
577.1   Failed to clone repository: 'https://github.com/google/googletest.git'

thanks

**Comment by byshiue** [comment]
You could try setting the `BUILD_TESTS` [here](https://github.com/NVIDIA/TensorRT-LLM/blob/main/cpp/CMakeLists.txt#L33) as `OFF`.

**Comment by nv-guomingz** [comment]
Hi @whk6688 please feel free to reopen this ticket if needed.
