### ISSUE TITLE
Support for number of results per context

### ISSUE THREAD

**Issue by mzusman** [NVIDIA/TensorRT-LLM#911]
Hi TRT LLM Team, 

A general question about the requests inference API, 
Is there an option to get several results per context ? [OAI API "n" equivalent]
I couldn't find it in the documentation. If there's no support at the moment, Is it on the team's roadmap?

Thank you!

**Comment by avshalomman** [comment]
Joining @mzusman's question☝️

**Comment by byshiue** [comment]
You could use beam search or pass same inputs and set different random seeds for them under sampling.

**Comment by nv-guomingz** [comment]
hi do u still have further issue or question now? If not, we'll close it soon.
