### ISSUE TITLE
TensorRT LLM 0.7.1, llama infer failed

### ISSUE THREAD

**Issue by yuyinsl** [NVIDIA/TensorRT-LLM#918]
### System Info

GPU: NVIDIA A100-SXM4-80GB
CPU: AMD EPYC 7742 64-Core Processor
OS: Ubuntu 22.04.3 LTS
Linux Kernel: 5.4.0-149-generic

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

checkpoint and tokenizer_dir is /home/data/llama/llama-7b-hf, which has been verified in version 0.5.0 and there is no problem.

refer to https://github.com/NVIDIA/TensorRT-LLM/blob/v0.7.1/examples/llama/README.md
1. COMTAINER_NAME=trtllm-0.7.1
2. make -C docker release_build
3. sudo docker run -it -d -v /home/:/home/ -COMTAINER_NAMEv /raid/:/raid/ --privileged --cap-add=ALL --ulimit memlock=-1 --ulimit stack=67108864 --gpus=all --pid=host --ipc=host --name ${COMTAINER_NAME} tensorrt_llm/release:0.7.1 /bin/bash
4. python3 build.py --model_dir /home/data/llama/llama-7b-hf --dtype float16 --remove_input_padding --use_gpt_attention_plugin float16 --enable_context_fmha --use_gemm_plugin float16 --output_dir ./tmp/llama/7B/trt_engines/fp16/1-gpu/
output:
[01/19/2024-11:58:49] [TRT-LLM] [I] Timing cache serialized to ./tmp/llama/7B/trt_engines/fp16/1-gpu/model.cache
[01/19/2024-11:58:50] [TRT-LLM] [I] Total time of building all 1 engines: 00:01:06

Test 1
5. python3 ../run.py  --max_output_len=50 --engine_dir=./tmp/llama/7B/trt_engines/fp16/1-gpu/ --tokenizer_dir /home/data/llama/llama-7b-hf
output: 
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 1160, in unk_token_id
    return self.convert_tokens_to_ids(self.unk_token)
RecursionError: maximum recursion depth exceeded

I have confirmed that the version of transformers is 4.33.1

Test 2
5. python3 ../run.py  --max_output_len=50 --engine_dir=./tmp/llama/7B/trt_engines/fp16/1-gpu/ --input_text "Born in north-east France, Soyer trained as a"
output:
Input [Text 0]: "Born in north-east France, Soyer trained as a"
Output [Text 0 Beam 0]: "-erell Retro Luc-erell Retro Luc-erell Retro Luc-erell Retro Luc-erell Retro Luc-erell Retro Luc-erell Retro Luc-erell Retro Luc-erell Retro Luc-erell Retro Luc"

### Expected behavior

Input: "Born in north-east France, Soyer trained as a"
Output: "chef in Paris and London before moving to the United States in 1850. He became a naturalised American citizen in 1855 and was appointed chef at Delmonico's in New York. He was also a"

### actual behavior

result1:
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/5247106/d2e75e5f-17bc-4ccf-ac6b-f7f19d4aab96)

![image](https://github.com/NVIDIA/TensorRT-LLM/assets/5247106/53d596ae-2dcd-438b-acd7-e547a96954b1)

result2：
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/5247106/e67e5b95-ae09-4583-9403-2e253ef35746)

#### TensorRT LLM 0.5.0, llama is OK
python3 build.py --model_dir /home/data/llama/llama-7b-hf --dtype float16 --use_gemm_plugin float16 --output_dir ./tmp/llama/7B/trt_engines/fp16/1-gpu/ --max_batch_size 1 --max_input_len 256 --max_output_len 256

python3 run.py --max_output_len=50 --tokenizer_dir /home/data/llama/llama-7b-hf --engine_dir=./tmp/llama/7B/trt_engines/fp16/1-gpu/

======================================================
Input: "Born in north-east France, Soyer trained as a"
Output: "chef in Paris and London before moving to the United States in 1850. He became a naturalised American citizen in 1855 and was appointed chef at Delmonico's in New York. He was also a"

**Comment by heerkek** [comment]
+1 same error. TensorRT LLM 0.5.0, llama is working well.

**Comment by yuyinsl** [comment]
@QiJune , @byshiue Hello, what is the status of this issue now? After fixing this problem, will you commit on the _main_ branch or modify the _0.7.1_ tag?

**Comment by yuyinsl** [comment]
run.py文件有修改，readme未更新，修改运行命令，llama可以得到正确结果。
python3 ../run.py --max_output_len=50 --tokenizer_dir /home/data/llama/llama-7b-hf --engine_dir=./tmp/llama/7B/trt_engines/fp16/1-gpu/ --tokenizer_type "llama"

=================== output: =================== 
Input [Text 0]: "<unk> Born in north-east France, Soyer trained as a"
Output [Text 0 Beam 0]: "chef in Paris before moving to London in 1847. He worked at the Reform Club and the Royal Hotel in Brighton before opening his own restaurant in 1851. He was a pioneer of the use of steam cook"

**Comment by nv-guomingz** [comment]
please feel free to reopen this ticket if needed.
