### ISSUE TITLE
Support for all GPU arch in pre-built pypi wheel

### ISSUE THREAD

**Issue by shashikg** [NVIDIA/TensorRT-LLM#920]
Seems this `pip3 install tensorrt_llm -U --pre --extra-index-url https://pypi.nvidia.com` does not works for T4 GPU. Can the pre-built wheel include all the GPU archs?

**Comment by Shixiaowei02** [comment]
Thank you for the suggestion! We will fix this issue tomorrow.

**Comment by Shixiaowei02** [comment]
We have solved this issue, please try again. Thank you for your support!

**Comment by shashikg** [comment]
Thank you so much @Shixiaowei02 for superfast action! I verified it on T4 -- now it works.
