### ISSUE TITLE
Could not find any implementation for node {ForeignNode[QWenForCausalLM/layers/0/ln_2/CONSTANT_1 + QWenForCausalLM/layers/0/ln_2/SHUFFLE_0...QWenForCausalLM/layers/0/ln_2/ELEMENTWISE_PROD_0]}.

### ISSUE THREAD

**Issue by whk6688** [NVIDIA/TensorRT-LLM#921]
When I run,  error happen:

python build.py --hf_model_dir /home/wanghaikuan/.cache/huggingface/hub/models--Qwen--Qwen-7B-Chat-Int4/snapshots/5a9a1ed9203a3d4ccc62f24fbb9b7e3948ce8ec1/ \
                --dtype bfloat16  \
                --remove_input_padding \
                --use_gpt_attention_plugin bfloat16 \
                --enable_context_fmha \
                --use_gemm_plugin bfloat16 \
                --output_dir ./tmp/Qwen/7B/trt_engines/fp16/1-gpu/

![image](https://github.com/NVIDIA/TensorRT-LLM/assets/17873056/e3218842-077f-4dab-8e22-d8ba47583731)

Note: my platform is orin 32G,  I guess root cause is  insufficient memory. How to min memory uage?(Is there any parameters can reduce memory  such as batch size)

Thanks

**Comment by byshiue** [comment]
@whk6688 Can you please look at https://github.com/NVIDIA/TensorRT-LLM/issues/488#issuecomment-1848697981? As of right now Orin is not formally supported.

Also, please refine your issue by following the template of issue.
