### ISSUE TITLE
Layernorm plugin to be deprecated

### ISSUE THREAD

**Issue by ekagra-ranjan** [NVIDIA/TensorRT-LLM#925]
Hi, I noticed that there is warning of deprecating layernorm plugin. So it means that TRTLLM won't be using the layernorm kernel? So layernorm kernel will be used in the model instead?

https://github.com/NVIDIA/TensorRT-LLM/blob/2f169d17d5a2b7690f78deacedccb25831905e5c/tensorrt_llm/functional.py#L3644-L3646

@Shixiaowei02 @byshiue

**Comment by Shixiaowei02** [comment]
Yes, I think you are right.

**Comment by ekagra-ranjan** [comment]
@Shixiaowei02 My bad - there was a typo error in my question.

So it means that TRTLLM won't be using the layernorm kernel? So **which** layernorm kernel will be used in the model instead?
