### ISSUE TITLE
Can multiple threads share a GptSession? Can multiple threads call GptSession::generate() concurrently?

### ISSUE THREAD

**Issue by yifeihappy** [NVIDIA/TensorRT-LLM#926]
As a service, requests need to be processed concurrently.
Can multiple threads share a GptSession? Can multiple threads call GptSession::generate() concurrently?

**Comment by byshiue** [comment]
For "requests processed concurrently", this function should be supported in `gptManager` with inflight batching. What's your consideration to use multi-threads on `GptSession`?

**Comment by yifeihappy** [comment]
> For "requests processed concurrently", this function should be supported in `gptManager` with inflight batching. What's your consideration to use multi-threads on `GptSession`?

Thank you for your response.
In my application scenario, I hope to process requests concurrently and obtain contextLogits.
The 0.7.0 version of gptManager does not seem to have an interface for obtaining contextLogits.

**Comment by yweng0828** [comment]
Hi @yifeihappy , the main branch now supports obtaining `contextLogits` under gptManager, related docs are [here](https://github.com/NVIDIA/TensorRT-LLM/issues/926). You could get from `SendResponseCallback`, such as [here](https://github.com/NVIDIA/TensorRT-LLM/blob/main/benchmarks/cpp/gptManagerBenchmark.cpp#L405), `response_tensors` will contain `contextLogits`.

**Comment by yifeihappy** [comment]
> Hi @yifeihappy , the main branch now supports obtaining `contextLogits` under gptManager, related docs are [here](https://github.com/NVIDIA/TensorRT-LLM/issues/926). You could get from `SendResponseCallback`, such as [here](https://github.com/NVIDIA/TensorRT-LLM/blob/main/benchmarks/cpp/gptManagerBenchmark.cpp#L405), `response_tensors` will contain `contextLogits`.

Thank you for your answer! I look forward to bringing this feature to the next tag release.

**Comment by nv-guomingz** [comment]
hi do u still have further issue or question now? If not, we'll close it soon.
