### ISSUE TITLE
what is the different between the original tensorrt  api and tensorrt llm?

### ISSUE THREAD

**Issue by henbucuoshanghai** [NVIDIA/TensorRT-LLM#930]
trt-llm is better?

**Comment by byshiue** [comment]
TensorRT-LLM is based on TensorRT and add many features/functions about large language model.

So, if you want to run large langugae model inference, TensorRT-LLM is suggested.

**Comment by henbucuoshanghai** [comment]
stable diffusion？SDXL is not supported in 2024 year？I have to do it myself? this repo can be helpful?
