### ISSUE TITLE
Could not find any implementation for node {ForeignNode[QWenForCausalLM/layers/0/ln_2/CONSTANT_1 + QWenForCausalLM/layers/0/ln_2/SHUFFLE_0...QWenForCausalLM/layers/0/ln_2/ELEMENTWISE_PROD_0]}.

### ISSUE THREAD

**Issue by whk6688** [NVIDIA/TensorRT-LLM#931]
### System Info

cuda12.2  torch2.1

### Who can help?

@byshiue

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

1. When I run, error happen:

python build.py --hf_model_dir /home/wanghaikuan/.cache/huggingface/hub/models--Qwen--Qwen-7B-Chat-Int4/snapshots/5a9a1ed9203a3d4ccc62f24fbb9b7e3948ce8ec1/
--dtype bfloat16
--remove_input_padding
--use_gpt_attention_plugin bfloat16
--enable_context_fmha
--use_gemm_plugin bfloat16
--output_dir ./tmp/Qwen/7B/trt_engines/fp16/1-gpu/

### Expected behavior

finish to convert model 

### actual behavior

![image](https://github.com/NVIDIA/TensorRT-LLM/assets/17873056/13b25dad-9fec-4279-bba7-be5967ad9f01)

### additional notes

 How to min memory uage?(Is there any parameters can reduce memory such as batch size)

**Comment by whk6688** [comment]
sometime  i also met following error:

NotImplementedError: Cannot copy out of meta tensor; no data!

**Comment by jershi425** [comment]
@whk6688 It seems like you are trying to run the Qwen-7B-Chat-Int4 model which is a GPTQ quantized model. To run GPTQ quantized model, please add the following args to your build command: `--use_weight_only`, `--weight_only_precision int4_awq` and `--per_group`. For a full demo, please refer to https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/qwen#int4-gptq

**Comment by whk6688** [comment]
ok， I change it as you said,  error change:

![image](https://github.com/NVIDIA/TensorRT-LLM/assets/17873056/a6af282f-9b55-4410-8ae9-9b66a3b5063b)

**Comment by jershi425** [comment]
Hi @whk6688, I can't reproduce the error you are seeing here. It looks like an issue when trying to load the HF model. Are you using the official checkpoint https://huggingface.co/Qwen/Qwen-7B-Chat-Int4 ? It would be good if you can try to run the GPTQ example following this [instruction]( https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/qwen#int4-gptq). And feel free to let me know if following the instruction still leads to error.

**Comment by nv-guomingz** [comment]
would u please try our latest code base to see if the issue still exists?

And do u still have further issue or question now? If not, we'll close it soon.
