### ISSUE TITLE
debug help!

### ISSUE THREAD

**Issue by sjtu-cz** [NVIDIA/TensorRT-LLM#932]
How to debug the results layer by layer to determine the problems existing in the converted model during the Generation Session?

**Comment by byshiue** [comment]
Pleaserefer the document here https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/2023-05-19-how-to-debug.md

**Comment by sjtu-cz** [comment]
您好，你的邮件我已经收到~
