### ISSUE TITLE
An error occurred in MPI_Init_thread when running sqlcoder

### ISSUE THREAD

**Issue by 2496289471** [NVIDIA/TensorRT-LLM#934]
https://huggingface.co/defog/sqlcoder2
Can sqlcoder2 (based on starcoder) be run directly? I ran the code according to starcoder's example, but the following error message appeared:

python3 ../run.py --engine_dir sqlcoder_outputs_tp1 --tokenizer_dir /home/admin/code/sqlcoder2  --input_text "how many students in the school？"---max_output_len 200 --no_add_special_tokens
[TensorRT-LLM][WARNING] Parameter version cannot be read from json:
[TensorRT-LLM][WARNING] [json.exception.out_of_range.403] key 'version' not found
[TensorRT-LLM][WARNING] Parameter pipeline_parallel cannot be read from json:
[TensorRT-LLM][WARNING] [json.exception.out_of_range.403] key 'pipeline_parallel' not found
[TensorRT-LLM][WARNING] Parameter mlp_hidden_size cannot be read from json:
[TensorRT-LLM][WARNING] [json.exception.out_of_range.403] key 'mlp_hidden_size' not found
[TensorRT-LLM][WARNING] [json.exception.type_error.302] type must be number, but is null
[TensorRT-LLM][WARNING] Optional value for parameter max_num_tokens will not be set.
[TensorRT-LLM][INFO] Initializing MPI with thread mode 1
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[localhost.localdomain:204388] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!

**Comment by byshiue** [comment]
Please follow the issue template to file issue, thank you for cooperation.

**Comment by 2496289471** [comment]
> Please follow the issue template to file issue, thank you for cooperation.

thank you, this is the new issue #995

**Comment by byshiue** [comment]
Close this one.
