### ISSUE TITLE
Convert jais to TensorRT

### ISSUE THREAD

**Issue by ML-Mr-J** [NVIDIA/TensorRT-LLM#939]
"Thank you for the outstanding work of Tensorrt-llm! Now I would like to perform TensorRT conversion on the JAIS model, which has a GPT2-like structure, involving the swiglu activation function and alibi positional encoding. In the TensorRT conversion of JAIS, the weight for the gated SwiGlu corresponds to mlp.dense_h_to_4h.gate.weight. How should the corresponding bias for SwiGlu's weight be handled? I would be extremely grateful!"

**Comment by jdemouth-nvidia** [comment]
Hi @ML-Mr-J , [Llama](https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/llama) also uses SwiGLU. It may be a good starting point to see how to deal with that question. No?

**Comment by ML-Mr-J** [comment]
> Hi @ML-Mr-J , [Llama](https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/llama) also uses SwiGLU. It may be a good starting point to see how to deal with that question. No?

Thank you for your reply! And I've already solved the problem of SwiGLU, and finished to convert jais as a runable engine, while the results are totally wrong, I don't know how to have a check.

**Comment by byshiue** [comment]
You can print the intermediate results of the TensorRT engine, and compare with the reference. Here is document about how to print the intermediate results https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/2023-05-19-how-to-debug.md.

**Comment by 5cat** [comment]
`Jais` has been added as an example https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/jais
