### ISSUE TITLE
[Question]Does trt-llm support per-tensor smoothquant for Yi-6B

### ISSUE THREAD

**Issue by littletomatodonkey** [NVIDIA/TensorRT-LLM#945]
Hi, i tested yi-6B model smoothquant using trt-llm. The accuracy comparsion is as follows.  The `int8_sq_per_tensor` mode seems abnormal. Does llama series model support per-tensor smooth quant in trt-llm? Thanks!

| precision | accuracy |
|:--:|:--:|
| fp16 | 0.553 |
| w8 | 0.553 |
| int8_sq_per_channel_per_token | 0.549 |
| int8_sq_per_tensor | 0.0 |

* export per-token per-channel

```bash
python3 build.py \
--bin_model_dir="benchmark/trt_yi6b/sq/1-gpu/" \
--output_dir ${trt_model_dir} \
--use_gpt_attention_plugin float16 \
--enable_context_fmha \
--use_smooth_quant \
--per_token \
--per_channel
```

* export per-tensor

```bash
python3 build.py \
--bin_model_dir="benchmark/trt_yi6b/sq/1-gpu/" \
--output_dir ${trt_model_dir} \
--use_gpt_attention_plugin float16 \
--enable_context_fmha \
--use_smooth_quant
```

**Comment by Tracin** [comment]
Thanks for your test. We do find a lot bugs with per-tensor SQ. If it is urgent, we can fix it for Yi specifically or we are working on new workflow of SQ.

**Comment by littletomatodonkey** [comment]
Thanks for your reply, it not urgent, and i just want to know whether i use it for the right way, look forward to your further work~

**Comment by littletomatodonkey** [comment]
If possible, could you please provide a benchmark(fp16, W8, W4, smooth quant, etc) for Yi series model for difference batch size? Thanks !

**Comment by Tracin** [comment]
Sorry, we do not have those results for Yi model.
