### ISSUE TITLE
AssertionError，error happens when checking starcoder's gelu_pytorch_tanh activation function.

### ISSUE THREAD

**Issue by nullxjx** [NVIDIA/TensorRT-LLM#946]
### System Info

model: [bigcode/starcoderbase-3b](https://huggingface.co/bigcode/starcoderbase-3b)
Python 3.10.12
CUDA Version: 12.2
tensorrt_llm version: 0.8.0.dev2024011601
basic image: nvcr.io/nvidia/tritonserver:23.12-trtllm-python-py3

### Who can help?

@juney-nvidia @kaiyux @Shixiaowei02 @Eddie-Wang1120 

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

follow the [guide](https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/gpt#gpt-variant---starcoder) to convert the weigths of starcoder.

### Expected behavior

convert the weigths of starcoder successfully.

### actual behavior

When I followed the instruction as described [here](https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/gpt#gpt-variant---starcoder), an error happened as below:
<img width="1396" alt="image" src="https://github.com/NVIDIA/TensorRT-LLM/assets/21221616/1862377f-1fa4-4e9e-ab83-e55d34af0cd9">

the command is
```bash
python3 build.py \
    --model_dir ./c-model/starcoderbase-3b/2-gpu \
    --remove_input_padding \
    --use_gpt_attention_plugin \
    --enable_context_fmha \
    --use_gemm_plugin \
    --parallel_build \
    --output_dir engines/starcoderbase-3b/fp16/2-gpu \
    --world_size 2
```

I find starcoder uses the "gelu_pytorch_tanh" activation function instead of classic gelu as described [here](https://huggingface.co/docs/transformers/model_doc/gpt_bigcode#implementation-details)

I checked the code from the latest main branch, but I cannot find gelu_pytorch_tanh defined anywhere. 
<img width="1118" alt="企业微信截图_106b7526-a152-42a5-b294-c5952679b49c" src="https://github.com/NVIDIA/TensorRT-LLM/assets/21221616/cf6afcda-e6dd-4bac-996b-f028249a473b">

It seems that tensorRT-LLM did not adapt to the starcoder model. But there are instruction readme [here](https://github.com/NVIDIA/TensorRT-LLM/tree/main/examples/gpt#gpt-variant---starcoder), I wonder if you have tested on starcoder before?

### additional notes

none

**Comment by nv-guomingz** [comment]
would u please try our latest code base to see if the issue still exists?

And do u still have further issue or question now? If not, we'll close it soon.
