### ISSUE TITLE
RuntimeWarning: overflow encountered in multiply

### ISSUE THREAD

**Issue by Hukongtao** [NVIDIA/TensorRT-LLM#948]
https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/llama/README.md#int8-kv-cache

When using int8 kv-cache, you will encounter the above warning. Will this affect accuracy?

**Comment by Tracin** [comment]
Sorry, what is the warning? Do you paste the right link?

**Comment by brisker** [comment]
@Tracin 
`python hf_llama_convert.py -i /root/models/Llama-2-7b/ -o /root/TensorRT -LLM/examples/llama/llama2_7b_w8_int8_kv_cache/ --calibrate-kv-cache -t fp16`
after running the code above, I also got `overflow encounted in multiply`, which is raised by this line:
https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/llama/convert.py#L91

**Comment by Tracin** [comment]
Yes, it is an bug and `scale_w_orig_quant_c` should be converted to fp32. This only impact SQ when weight is per-tensor.

**Comment by nv-guomingz** [comment]
would u please try our latest code base to see if the issue still exists?

And do u still have further issue or question now? If not, we'll close it soon.
