### ISSUE TITLE
MBartForCausalLM problem

### ISSUE THREAD

**Issue by sjtu-cz** [NVIDIA/TensorRT-LLM#951]
### System Info

cpu:  model name      : AMD EPYC 7K62 48-Core Processor
GPU: 00:02.0 VGA compatible controller: Cirrus Logic GD 5446

### Who can help?

@kaiyux
@ncomly-nvidia

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

1.convert succ (hf_models->trt_models)
python bart/convert_dev.py -i ${workdir}/hf_models/mbart -o ${workdir}/trt_models/mbart --weight_data_type float32 --inference_tensor_para_size 1 --verbose
2.build succ (trt_models-> trt_engine)
python build_dev.py --model_type bart \
                --weight_dir ${workdir}/trt_models/mbart/tp1 \
                -o ${workdir}/trt_engines/mbart/1-gpu \
                --engine_name mbart \
                --remove_input_padding \
                --use_bert_attention_plugin \
                --use_gpt_attention_plugin \
                --use_gemm_plugin \
                --dtype float16 \
                --max_beam_width 1 \
                --max_encoder_input_len 1200 \
                --max_decoder_input_len 10 \
                --max_output_len 768
  3.run could not get same res as hf_models
python3 run_dev.py --engine_dir ${workdir}/trt_engines/mbart/1-gpu/float16/tp1 --engine_name mbart --model_name ${workdir}/hf_models/mbart --max_new_token=768 --num_beams=1 --compare_hf_fp32 --debug_mode

### Expected behavior

can anybody help? I can share my code via email.

### actual behavior

can anybody help? I can share my code via email

### additional notes

can anybody help? I can share my code via email

**Comment by sjtu-cz** [comment]
For my MBartForCausalLM model, its input is very similar to the donut and nougat models, requiring the encoder_output and the prompt input. Does tensorrt-LLM now support this capability?

**Comment by byshiue** [comment]
You could follow the document here https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/2023-05-19-how-to-debug.md to print the intermediate result and compare with HF.
