### ISSUE TITLE
layernorm kernel much slower than torch.

### ISSUE THREAD

**Issue by beegerous** [NVIDIA/TensorRT-LLM#957]
I wrap this kernel (https://github.com/NVIDIA/TensorRT-LLM/blob/main/cpp/tensorrt_llm/kernels/layernormKernels.h#L30) by pybind11 and test it's performance in python. find that it is much slower than torch.

I test different size of layernorm op, repeat 1e6 times and record latency. both torch and trt-llm run in fp16.

indicate code:
``` python3
        n = 1000000
        dtype = torch.float16
        M = 1024
        K = 1024
        m = torch.nn.LayerNorm(K, dtype=dtype).eval().to("cuda")
        x = torch.randn([M, K], dtype=dtype).to("cuda") * 0.01
        torch.cuda.synchronize()
        st = time.time()
        for _ in range(n):
            y1 = m(x)
        torch.cuda.synchronize()
        print("torch cost:", time.time() - st)

        torch.cuda.synchronize()
        st = time.time()
        for _ in range(n):
            y2 = mylib.layer_norm(x, m.weight, m.bias, m.eps)
        torch.cuda.synchronize()
        print("trt-llm cost:", time.time() - st)
```

test result:

| GPU | tokens | hidden_dim | torch cost(s) | trt-llm cost(s) |
|------|-------|-------------|--------------|---------------|
| A100 | 1024 | 1024 | 15.998201847076416 | 12.195645332336426 |
|          | 2048 | 2048 | 16.7151517868042 | 26.301640033721924 |
|          | 4096 | 4096 | 63.31942009925842 | 77.83161664009094 |
| V100 | 1024 | 1024 | 20.07244873046875 | 14.948951005935669 |
|          | 2048 | 2048 | 32.36647820472717 | 36.721962451934814 |
|          | 4096 | 4096 | 133.4487762451172 | 111.75524473190308 |

env:
| GPU | Driver Version | CUDA Version | Description |
| -------- | ---------- | -------- | ---------- |
| A100-SXM4-80GB | 535.129.03 | 12.2 | Ubuntu 20.04.6 LTS |
| Tesla V100-SXM2-32GB | 470.103.01 | 11.4 | Ubuntu 18.04.6 LTS |

I think it is weird that trt is slower than torch. Although trt-llm faster than torch in case 1024, but torch only use 50% gpu utils in 1024, and trt-llm use 100%. so I think it also prove that trt-llm version of layernorm kernel is slower.
Then I check the torch version of layernorm kernel, and find a difference.

https://github.com/NVIDIA/TensorRT-LLM/blob/main/cpp/tensorrt_llm/kernels/layernormKernels.cu#L236
https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/native/cuda/layer_norm_kernel.cu#L797

When launch kernel, trt-llm use block=1024 but torch use block=256. I can't figure out specific reason but think it worth a try. so I build a block=256 version lib and run the test again.

| GPU | tokens | hidden_dim | torch cost(s) | trt-llm cost(s) |
|------|-------|-------------|--------------|---------------|
| A100 | 1024 | 1024 | 16.19998550415039 | 7.388491630554199 |
|          | 2048 | 2048 | 16.7298641204834 | 14.972687721252441 |
|          | 4096 | 4096 | 63.43415188789368 | 60.46646189689636 |
| V100 | 1024 | 1024 | 19.828619718551636 | 9.059558868408203 |
|          | 2048 | 2048 | 32.32805252075195 | 29.712080240249634 |
|          | 4096 | 4096 | 133.47651624679565 | 105.48646426200867 |

I can't tell why but trt-llm layernorm become much faster. I think it is a kind of bug but don't know the right way to fix it. So just submit a issue.

**Comment by nekorobov** [comment]
Hi @beegerous, thank you for the feedback. Layer Norm plugin is now deprecated and removed from TensorRT-LLM repo. We now use layer norm natively in TensorRT. Could you try it again and open new bug if you still find the issues? Thank you!
