### ISSUE TITLE
How can we take advantage of in-flight batch with Python API to improve server throughput?

### ISSUE THREAD

**Issue by gesanqiu** [NVIDIA/TensorRT-LLM#96]
Thanks for your grate work. 
I've been reading the codes in `example/llama` for several days, since there haven't open-source the codes of `BatchManager`, I'm confused about the behaviors that the `decoder` present. In my understand, continuous batch or persistant batch is works like this picture:
![persistant batch inference](https://user-images.githubusercontent.com/67539920/251351971-e3876167-0671-44fc-ac52-5a0f9382493e.gif)
In general, if we want to achieve the continuous batch, we should implement a scheduler, which I didn't see in the TRT-LLM python apis.
In the [example/llama/run.py](https://github.com/NVIDIA/TensorRT-LLM/blob/1c4a0ee24cb0480c20a721c4bc6a77fc51644a22/examples/llama/run.py#L249), all inputs in one batch share one `SamplingConfig` object, I don't think this is a normal use case. In [handle_per_step](https://github.com/NVIDIA/TensorRT-LLM/blob/1c4a0ee24cb0480c20a721c4bc6a77fc51644a22/tensorrt_llm/runtime/generation.py#L1605), there is a comment "Free all blocks in all sequences. With in-flight batching and while loop we'll free some sequences, when they are done", and `should_stop` just one item but control the stop behavior of the whole batch. That's make no sense since we can't ensure that all the sequences in one batch will stop at same moment. So what's the definition of 'all sequences', why we need stop in a batch level or what's the minimum unit of in-flight batch?

Apologies in advance if this seems to be something obvious because I'm new in LLM field.

**Comment by jdemouth-nvidia** [comment]
Hi @gesanqiu, for this first release we have decided to focus on the C++ implementation in the batch manager. We plan to create a wrapper for it in Python - there's already a PR for it https://github.com/NVIDIA/TensorRT-LLM/pull/76. So, in-flight batching requires you to use the C++ runtime and the Triton Backend shows how to enable it. I hope it helps. Thanks for your interest in TensorRT-LLM. Julien
