### ISSUE TITLE
Are the three linear layers--q,k,v , merged in TensorRT-LLM for llama model?( potential bad influence on quantization accuracy)

### ISSUE THREAD

**Issue by brisker** [NVIDIA/TensorRT-LLM#964]
here:
https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/llama/hf_llama_convert.py#L37

https://github.com/NVIDIA/TensorRT-LLM/blob/main/examples/llama/convert.py#L88    **(the same output quantization scale for q,k,v)**

It seems that the qkv ,three linear layers' quantization scales are merged and shared, but this  seems to **have potential bad influence on quantization model accuracy.**

Will this be fixed in the future?

**Comment by byshiue** [comment]
From our experiment, it could keep good accuracy even if we merge the scales. Do you encounter any accuracy issue?

**Comment by brisker** [comment]
@byshiue 
yes, the accuracy drops too much. The details can be found here:

https://github.com/NVIDIA/TensorRT-LLM/issues/967

**Comment by brisker** [comment]
@byshiue 

In your experiment, accuracy is good. So is your experiment llama2-7b-int8-kv-cache+ int8-weight?

> From our experiment, it could keep good accuracy even if we merge the scales. Do you encounter any accuracy issue?

**Comment by brisker** [comment]
@byshiue 
It seems that llama2 quantization(not matter smoothquant or kv-cache quantization) has some bugs, which causes consistent bad accuracy ,and qkv scale merged or not may not be the main reason (but still a reason).

**Comment by byshiue** [comment]
I think we could discuss this issue in https://github.com/NVIDIA/TensorRT-LLM/issues/967, do you agree?

**Comment by nv-guomingz** [comment]
Hi @brisker do u still have further issue or question now? If not, we'll close it soon.
