### ISSUE TITLE
a compare with vllm 0.2.7

### ISSUE THREAD

**Issue by white-wolf-tech** [NVIDIA/TensorRT-LLM#965]
### System Info
ubuntu22.04
one Nvidia A800
driver info: 470.141.10
cuda: 12.3
tensorrt: 9.2.0.5

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

set Concurrency = 16.
when I use VLLM=0.2.7. use vllm asyncengine. 
min response time is 367 ms
max response time is 676 ms

I build Tensorrt-LLM and tensorrtllm_backend from the main branch.
use tritonserver deploy the model. test result is:
min response is 379 ms
max response is 4418 ms

Tensorrt-LLM is much lowest than VLLM0.2.7?
I think Tensorrt-LLM should be faster than VLLM.
why? any suggestion?

### Expected behavior

NULL

### actual behavior

NULL

### additional notes

Null

**Comment by kaiyux** [comment]
@Coder-nlper Please share your commands to build the engines and benchmarks so that we can check if the comparison is apple-to-apple. Thanks.

**Comment by white-wolf-tech** [comment]
commands to build:

hf_model_path=/root/chatglm3-6b/
engine_dir=/root/trtllm/trtllmmodels/fp16/
CUDA_ID="1"

CUDA_VISIBLE_DEVICES=$CUDA_ID python3 build.py \
       --model_dir $hf_model_path \
       --log_level "info" \
       --output_dir $engine_dir/1-gpu \
       --world_size 1 \
       --tp_size 1 \
       --max_batch_size 50 \
       --max_input_len 2048 \
       --max_output_len 512 \
       --max_beam_width 1 \
       --enable_context_fmha \
       --use_inflight_batching \
       --paged_kv_cache \
       --remove_input_padding

test use ab command:

ip=localhost
port=60025
ab -n 64 -c 16  -p "post.txt" -T "application/json" -H "Content-Type: application/json" -H "Cache-Control: no-cache" -H "Postman-Token: d6xxs-sdf-sdf09d" "http://$ip:$port/model/generate"

**Comment by white-wolf-tech** [comment]
Driver is 470.141.10. is there any relationship with it?

**Comment by kristiankielhofner** [comment]
> Driver is 470.141.10. is there any relationship with it?

I have to imagine that likely isn't ideal.

While it's supported per the [Nvidia Frameworks Support Matrix](https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html) you may want to try comparing to 535 for the current 23.10 based containers. Also be aware main has moved to 23.12 which would be 545 (CUDA 12.3).

**Comment by white-wolf-tech** [comment]
> > Driver is 470.141.10. is there any relationship with it?
> 
> I have to imagine that likely isn't ideal.
> 
> While it's supported per the [Nvidia Frameworks Support Matrix](https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html) you may want to try comparing to 535 for the current 23.10 based containers. Also be aware main has moved to 23.12 which would be 545 (CUDA 12.3).

but the latest is 535.x.x

<img width="755" alt="image" src="https://github.com/NVIDIA/TensorRT-LLM/assets/7296788/45f69cc3-02c2-46d7-915e-9a8f3c6f8157">

**Comment by Tlntin** [comment]
> > > Driver is 470.141.10. is there any relationship with it?
> > 
> > 
> > I have to imagine that likely isn't ideal.
> > While it's supported per the [Nvidia Frameworks Support Matrix](https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html) you may want to try comparing to 535 for the current 23.10 based containers. Also be aware main has moved to 23.12 which would be 545 (CUDA 12.3).
> 
> but the latest is 535.x.x
> 
> <img alt="image" width="755" src="https://private-user-images.githubusercontent.com/7296788/300320330-45f69cc3-02c2-46d7-915e-9a8f3c6f8157.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NjgxMTQsIm5iZiI6MTcwNjg2NzgxNCwicGF0aCI6Ii83Mjk2Nzg4LzMwMDMyMDMzMC00NWY2OWNjMy0wMmMyLTQ2ZDctOTE1ZS05YThmM2M2ZjgxNTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDJUMDk1NjU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDAyNTEyYTg1N2JkZGViYmEwMzI2N2I3MTY1NGVlYTgwZGIzZThkNTdmNTA5MjIxZmMyNzY4ZDIwODk2M2E3ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6lB3DU7o3DUlxul71f7gxYB88qUeJqr04_UoSBft1MA">

stable version is 535, dev version is 545, beta version is 550.
refer [link](https://forums.developer.nvidia.com/t/current-graphics-driver-releases/28500)
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/28218658/0a879f2c-4f2b-4d36-af90-4e1c8ca61eab)

**Comment by tp-nan** [comment]
Is there any update for this issue？An end to end example for QWenVLChat which is of higher throughput compared to vLLM is very helpful

**Comment by nv-guomingz** [comment]
Hi @white-wolf-tech do u still have further issue or question now? If not, we'll close it soon.
