### ISSUE TITLE
how can I debug the plugins? I mean when the model runing, it can print the message

### ISSUE THREAD

**Issue by liangbin123** [NVIDIA/TensorRT-LLM#969]
for example, the file cpp/tensorrt_llm/kernels/decoderMaskedMultiheadAttentionUtils.h,
when I change the function 

`

inline __device__ float update_rotary_base(
    const int kv_seq_len, const int max_positions, const int embed_dim, const float base, const float scale)
{

    const float b = (scale * kv_seq_len / max_positions) - (scale - 1);

    const float p = static_cast<float>(embed_dim) / (embed_dim - 2);

    return base * __powf(b, p);

}

`

to 
`

inline __device__ float update_rotary_base(
    const int kv_seq_len, const int max_positions, const int embed_dim, const float base, const float scale)
{

    printf("helloworld");

    const float b = (scale * kv_seq_len / max_positions) - (scale - 1);

    const float p = static_cast<float>(embed_dim) / (embed_dim - 2);

    return base * __powf(b, p);

}

`

And then I compile it, and then I install the tensorrt_llm, and run the model. But in the terminal, it didn't output the string "hello world".

How can I debug the function in cpp files and make sure my modify is success?

**Comment by byshiue** [comment]
It is possible that you don't really use the kernel you change (or not enter the part you change), or you don't install the changed tensorrt_llm successfully.
