### ISSUE TITLE
Compilation issue about weightOnlyBatchedGemvBs4Int8b.cu

### ISSUE THREAD

**Issue by yuehuayingxueluo** [NVIDIA/TensorRT-LLM#97]
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/26091437/87dea8bc-7ecd-4ebe-bf01-370fe323fc8e)
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/26091437/b855bf0e-d2dd-4bad-bdbc-0f41575cd927)
When I follow the build instructions in your Readme to build TensorRT-LLM, it always gets stuck at 98%. The background compilation-related program status is R+ and S+. 
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/26091437/50ecf468-e648-4efc-a3c1-dc4826e26108)
I also encounter this problem when building the image.

nvidia-smi
![image](https://github.com/NVIDIA/TensorRT-LLM/assets/26091437/5a1c9e81-0252-4ae0-b985-234c1b424112)

nvcc
`$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Jul_11_02:20:44_PDT_2023
Cuda compilation tools, release 12.2, V12.2.128
Build cuda_12.2.r12.2/compiler.33053471_0`

pip list
Package                 Version
----------------------- --------
boltons                 23.0.0
brotlipy                0.7.0
certifi                 2023.5.7
cffi                    1.15.1
charset-normalizer      2.0.4
conda                   23.5.2
conda-content-trust     0.1.3
conda-libmamba-solver   23.5.0
conda-package-handling  2.1.0
conda_package_streaming 0.8.0
cryptography            41.0.4
filelock                3.12.4
fsspec                  2023.9.2
huggingface-hub         0.17.2
idna                    3.4
jsonpatch               1.32
jsonpointer             2.1
libmambapy              1.4.1
packaging               23.0
pip                     23.1.2
pluggy                  1.0.0
pycosat                 0.6.4
pycparser               2.21
pyOpenSSL               23.2.0
PySocks                 1.7.1
PyYAML                  6.0.1
requests                2.29.0
ruamel.yaml             0.17.21
setuptools              67.8.0
six                     1.16.0
toolz                   0.12.0
tqdm                    4.65.0
typing_extensions       4.8.0
urllib3                 1.26.16
wheel                   0.38.4
zstandard               0.19.0

cmake --version
cmake version 3.16.3
CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by isky-cd** [comment]
The issue with the compilation of weightOnlyBatchedGemvBs4Int8b.cu has been resolved. It was due to the compilation of weightOnlyBatchedGemvBs4Int8b.cu is too slow. However, there were some issues that occurred later.

![image](https://github.com/NVIDIA/TensorRT-LLM/assets/26091437/035dbc66-8a0c-462b-93ce-2a9c2e1cf0f8)

**Comment by juney-nvidia** [comment]
> The issue with the compilation of weightOnlyBatchedGemvBs4Int8b.cu has been resolved. It was due to the compilation of weightOnlyBatchedGemvBs4Int8b.cu is too slow. However, there were some issues that occurred later.
> 
> ![image](https://user-images.githubusercontent.com/26091437/277638602-035dbc66-8a0c-462b-93ce-2a9c2e1cf0f8.png)

Pls try with this to ensure the library are properly fetched to your local storage via LFS.
https://github.com/NVIDIA/TensorRT-LLM/issues/100#issuecomment-1777104351
