### ISSUE TITLE
cuDDN minor version diffrences (TensorRT was linked against cuDNN 8.9.X but loaded cuDNN 8.9.X)

### ISSUE THREAD

**Issue by enochlev** [NVIDIA/TensorRT-LLM#974]
### System Info

I got this warning when trying to compile the model and I can imagine it may reduce performance

TensorRT was linked against cuDNN 8.9.6 but loaded cuDNN 8.9.4

the problem here is there is in the [read me](https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/build_from_source.md) it provides an option the change MAJOR.MINOR but not "extra_minor" version

this is how I compiled it
make -C docker release_build CUDA_ARCHS="89-real"  (i have a 4090)

should I not be wored about the extra_minor" version or is there a command to specify it?
I am aware of this [issue](https://forums.developer.nvidia.com/t/warnings-after-installing-tensorrt/184433), but ultimately the problem may be the build command

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

make -C docker release_build CUDA_ARCHS="89-real"

compile this with a WSL2 machine having a 4090

### Expected behavior

adding the third option may be nice

make -C docker release_build CUDA_ARCHS="896-real"

### actual behavior

TensorRT was linked against cuDNN 8.9.6 but loaded cuDNN 8.9.4

### additional notes

If thats not possible, then I would greatly appreciate it if you could point me to the solution

**Comment by enochlev** [comment]
just to note... I am able to compile model successfully. Just curiouse if it has a performance impact

**Comment by Shixiaowei02** [comment]
Could you please provide more detailed logs? BTW, I think there will be no compatibility issues between minor versions.

**Comment by nv-guomingz** [comment]
do u still have further issue or question now? If not, we'll close it soon.
