### ISSUE TITLE
[Question]The relationship between max_batch_size and max_input_len in the build command.

### ISSUE THREAD

**Issue by wjj19950828** [NVIDIA/TensorRT-LLM#977]
Because TRT_LLM has a mechanism, if the length of the request is greater than ```max_input_len```, the request will directly return error without processing.

For example, there is currently a request with a length of 3072. Because the ```max_input_len``` in my build command is set to 2048, the request directly returns an error.

Is there any way to directly handle requests with a length greater than 2048 without truncation?

The solution I am currently thinking of is to increase ```max_input_len``` to 3072 in the build command, but this behavior causes ```max_batch_size``` to become smaller, resulting in smaller concurrency and throughput.(It may be that the length of a few requests exceeds 2048)

Is there any better solution? Thank you~

The build command is as follows：
```shell
python build.py \
    --ft_model_dir=$IN_MODEL \
    --dtype float16 \
    --remove_input_padding \
    --enable_context_fmha \
    --use_inflight_batching \
    --paged_kv_cache \
    --world_size 1 \
    --tp_size 1 \
    --max_batch_size 70 \
    --max_input_len 3072 \
    --max_output_len 512 \
    --use_smooth_quant \
    --output_dir $OUT_MODEL \
    --per_token \
    --per_channel \
    --int8_kv_cache
```

**Comment by byshiue** [comment]
This document should be helpful for your question https://github.com/NVIDIA/TensorRT-LLM/blob/main/docs/source/memory.md#activation-size.
