### ISSUE TITLE
Weight cannot be divisible by tensor_parallel_size

### ISSUE THREAD

**Issue by haojiwei** [NVIDIA/TensorRT-LLM#98]
Try to convert `WizardLMCoder-Python-13B-V1.0`, whose `vocab_size` is 32001 and `architectures` is `LlamaForCausalLM`, using `examples/llama/build.py` and set the `use_parallel_embedding` false. 

When `tp_size` is set to 2, and split `lm_head.weight`, shape is (32001, 5120), encounter the problem that weight shape cannot be divided by tp size.

These is any method to padding the split weight, avoid splitting at the layer weight or others?

**Comment by byshiue** [comment]
A common way is padding the weight to times of `tp_size`. But it requires some additional work to prevent we select the padded tokens. Here is an example we use in GPT https://github.com/NVIDIA/TensorRT-LLM/blob/release/0.5.0/examples/gpt/weight.py#L193-L206

We will support it in llama in the future.

**Comment by jdemouth-nvidia** [comment]
@byshiue , Or you could try splitting in the other dimension (5120 % 2 == 0). No?

**Comment by byshiue** [comment]
@jdemouth-nvidia For lm_head, TensorRT-LLM only supports splitting on vocab dimension now. TensorRT-LLM supports splitting embedding lookup on both dimension.

**Comment by jdemouth-nvidia** [comment]
Thanks for the clarification @byshiue .

**Comment by haojiwei** [comment]
@byshiue I just padding the weight using constant_values 0 according to the gpt example. And what does "some additional work to prevent we select the padded tokens" means? There is any other adjustment needs to be done?

**Comment by byshiue** [comment]
> @byshiue I just padding the weight using constant_values 0 according to the gpt example. And what does "some additional work to prevent we select the padded tokens" means? There is any other adjustment needs to be done?

You can try first on your fix. I mention "some additional work to prevent we select the padded tokens" because constant value 0 should not guarantee that we will not select these virtual token, but it may be a corner case and we don't need to worry about it now.

**Comment by haojiwei** [comment]
@byshiue get it, thanks a lot

**Comment by byshiue** [comment]
Close this bug. Feel free to reopen it if needed.
