### ISSUE TITLE
What does two optimization profiles mean?

### ISSUE THREAD

**Issue by xesdiny** [NVIDIA/TensorRT-LLM#980]
in [runntime/gptSession.cpp](https://github.com/NVIDIA/TensorRT-LLM/blob/b57221b764bc579cbb2490154916a871f620e2c4/cpp/tensorrt_llm/runtime/gptSession.cpp#L76)
```C++
...
void GptSession::createContexts()
{
    TLLM_LOG_DEBUG("%s start", __PRETTY_FUNCTION__);
    mRuntime->clearContexts();

    auto const numProfiles = mRuntime->getNbProfiles();
    TLLM_CHECK_WITH_INFO(
        numProfiles == 1 || numProfiles == 2, "GPT only expects one optimization profile or two optimization profiles");

    // Instantiate 1 execution context for each profile
    for (auto contextId = 0; contextId < numProfiles; ++contextId)
    {
        mRuntime->addContext(contextId);
    }

    TLLM_LOG_DEBUG("%s stop", __PRETTY_FUNCTION__);
}
```
and in [tensorrt_llm/models/generation_mixin.py](https://github.com/NVIDIA/TensorRT-LLM/blob/b57221b764bc579cbb2490154916a871f620e2c4/tensorrt_llm/models/generation_mixin.py#L72)
```python
  enable_two_optimization_profiles = GenerationMixin.has_two_optimization_profiles(
            use_gpt_attention_plugin, use_gemm_plugin, remove_input_padding,
            paged_kv_cache)
```
How does building `mRuntime.addContext` with setting `=1 or 2` make sense in terms of performance?
Is the `context phase` or `generate phase` FLOPs percentage controlled?

**Comment by litaotju** [comment]
TensorRT-LLM depends on TensorRT to get the best performance. While TensorRT needs to know shape to find the optimal kernels.
In some cases, using two different optimal shapes for finding good kernels are needed. This is all done automatically, and should not be a concern to users. 

Thanks
