### ISSUE TITLE
Layernorm plugin to be deprecated

### ISSUE THREAD

**Issue by ekagra-ranjan** [NVIDIA/TensorRT-LLM#986]
Hi, this is continuation of #925 . I had a typo in the question and the Issue couldn't reopen so I am raising another issue.

I noticed that there is warning of deprecating layernorm plugin. 
1. So it means that TRTLLM won't be using the layernorm kernel? 
2. If yes, then **which** layernorm kernel will be used in the model instead?

@Shixiaowei02 @byshiue

**Comment by byshiue** [comment]
TensorRT-LLM will let TensorRT handle the layernorm kernel in the future.

**Comment by litaotju** [comment]
Closing this one. Since already answered, TRT-LLM will always try to find the best kernels to be used, whether to be plugin or TRT native kernels.
