### ISSUE TITLE
qwen end_id setting is wrong so cannot stop at right postition!

### ISSUE THREAD

**Issue by Liufeiran123** [NVIDIA/TensorRT-LLM#987]
in file  example/utils.py. 
So I changed the end_id  and All thing is right！

**Comment by kaiyux** [comment]
Hi @Liufeiran123 , thanks a lot for the kind reporting of the issue, we've fixed the issue in the internal codebase, and an update containing the fix will be pushed.

**Comment by kaiyux** [comment]
@Liufeiran123 We pushed an [update](https://github.com/NVIDIA/TensorRT-LLM/pull/1168) to the main branch which should contain the fix of this issue, can you please verify it on the latest main branch? Thanks.

**Comment by nv-guomingz** [comment]
hi @Liufeiran123 do u still have further issue or question now? If not, we'll close it soon.
