### ISSUE TITLE
[question] details about gpt_attention's inputs in the case of inflight batching

### ISSUE THREAD

**Issue by handoku** [NVIDIA/TensorRT-LLM#991]
Assumming gpt manager scheduled 1 context-phase sequence and 2 generation-phase sequences at a certain moment: 
```
[ctx_a, gen_a, gen_b]
```
Then, my understanding about `gpt_attention` inputs:

 - `qkv` : gpu tensor, shape is `[1, num_tokens,  hidden_size]`, where `num_tokens = len(ctx_a) + 2;`
 - `host_request_types` : cpu tensor, shape is `[3]`, and values are `[0, 1, 1]`
 - `host_context_length` : cpu tensor,  shape is `[3]`, and values are `[len(ctx_a),  context_len(gen_a), context_len(gen_b)]`
 - `context_lengths` : gpu tensor, shape is `[3]`,  and values are `[len(ctx_a), context_len(gen_a), context_len(gen_b)]`
 - `sequence_lengths` : gpu tensor, shape is `[3]`, and values are `[len(ctx_a), cur_token_idx(gen_a), cur_token_idx(gen_b)]`

`context_len(x)` means get sequence `x`'s prompt's length.
`cur_token_idx(x)` means get sequence `x`'s latest generated token's token_idx(context tokens and generated tokens both counted). 

Is my understanding right or not? I want to write a plugin to implement Qwen's [logn-scaling](https://huggingface.co/Qwen/Qwen-7B-Chat/blob/main/modeling_qwen.py#L489) for `q` tensor, which needs token_idx value of each token (including context prompt's tokens), `host_request_types` and `sequence_lengths` should be enough while others might help. 

Looking for answers, many thanks.

**Comment by PerkzZheng** [comment]
yes, your understanding is correct. 
`host_context_length`, `context_lengths` are mainly used for FMHA optimization.

**Comment by WingEdge777** [comment]
> yes, your understanding is correct. `host_context_length`, `context_lengths` are mainly used for FMHA optimization.

@PerkzZheng Thanks!

**Comment by nv-guomingz** [comment]
please feel free to reopen this ticket if needed.
