### ISSUE TITLE
Error Code 9: Internal Error (Builder was created on device different than current device.  qwen-7B INT4-GPTQ on A100

### ISSUE THREAD

**Issue by wujingbo-web** [NVIDIA/TensorRT-LLM#996]
i try to run qwen-7B INT4-GPTQ example， error comes:Error Code 9: Internal Error (Builder was created on device different than current device.
my gpu are two A100 80G,please help~~
------------------------------------------------------------------------------------------
! python3 /root/TensorRT-LLM/examples/qwen/build.py --hf_model_dir Qwen-7B-Chat-Int4 \
                --quant_ckpt_path Qwen-7B-Chat-Int4 \
                --dtype float16 \
                --remove_input_padding \
                --use_gpt_attention_plugin float16 \
                --enable_context_fmha \
                --use_gemm_plugin float16 \
                --use_weight_only \
                --weight_only_precision int4_gptq \
                --per_group \
                --world_size 1 \
                --tp_size 1 \
                --output_dir ./tmp/Qwen/7B/trt_engines/int4-gptq/1-gpu

[01/29/2024-03:10:12] [TRT] [E] 9: [backendBuilderConfig.cpp::validateBasicAssumptions::28] Error Code 9: Internal Error (Builder was created on device different than current device.)
[01/29/2024-03:10:12] [TRT-LLM] [E] Engine building failed, please check the error log.
[01/29/2024-03:10:12] [TRT-LLM] [I] Config saved to ./tmp/Qwen/7B/trt_engines/int4-gptq/1-gpu/config.json.
Traceback (most recent call last):
  File "/root/TensorRT-LLM/examples/qwen/build.py", line 710, in <module>
    build(0, args)
  File "/root/TensorRT-LLM/examples/qwen/build.py", line 682, in build
    assert engine is not None, f'Failed to build engine for rank {cur_rank}'
AssertionError: Failed to build engine for rank 0

**Comment by byshiue** [comment]
Please follow the issue template to file issue, thank you for cooperation.

**Comment by zeeshanvision** [comment]
faced the same issue

**Comment by lajiyuan** [comment]
@wujingbo-web  @zeeshanvision  Try specify CUDA device.
```
CUDA_VISIBLE_DEVICES=0 python build.py --...
```

**Comment by liyunhan** [comment]
> @wujingbo-web @zeeshanvision Try specify CUDA device.
> 
> ```
> CUDA_VISIBLE_DEVICES=0 python build.py --...
> ```

I just have two A6000-48GB and faced the same issue. what can i do?

**Comment by byshiue** [comment]
Do you use MIG? Also, please follow the template to share the reproduced steps and the full error logs.

**Comment by nv-guomingz** [comment]
do u still have further issue or question now? If not, we'll close it soon.
